### ISSUE TITLE
clickhouse-server docker initdb script sourcing ignores errors

### ISSUE THREAD

**Issue by abraithwaite** [ClickHouse/ClickHouse#10183]
Investigating some flaky builds we found that the initdb script doesn't check errors or issue retries for failed migrations:

https://github.com/ClickHouse/ClickHouse/blob/0ecfede695638a9565eb6815bf1772d7ea5445bc/docker/server/entrypoint.sh#L84-L100

Occasionally on our CI, the clickhouse client connection to zookeeper unexpectedly closes, which in turn causes the initial migration script to fail silently.

Zookeeper issues aside, I believe that the script should at least be checking that the migrations applied successfully (return code from clickhouse-client is 0).

**Comment by filimonov** [comment]
But what an action do you expect on failure? 

We can't blindly run the script once again. 

imagine it inserts 10K rows at the beginning successfully and fails later on line 10001.
If we will repeat you will get 20K rows instead of 10K. 

Init scripts can be shell script too (just use .sh extension).
You can script retry logic inside if needed.

**Comment by alexey-milovidov** [comment]
@filimonov Let it fail completely and not continue.

**Comment by abraithwaite** [comment]
> But what an action do you expect on failure?

That's why I'm not sure about retries, but failing the script would be better than continuing.
