### ISSUE TITLE
Partition minmax index should also store values about partition expression as a whole, not only its arguments.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10220]
This feature was suggested on 42th ClickHouse meetup, that was held online, YouTube: https://www.youtube.com/watch?v=QQSCn6nbyN8

**Comment by siradjev** [comment]
As a side comment we would recommend to store expression of each tuple element and have mapping of each tuple element to dependent columns, rather than overall expression, to cover proper partition elimination/pruning for multi-level partitioning with hash-partitioning cases like below: 
`
PARTITION BY (toYYYYMM(dateCol), userId%5)
`
Users and SQL generators usually won't use overall tuple expression in WHERE condition.

In case you store the whole expression as tuple only, partition elimination won't work for:
1. subset of partition key columns are specified in WHERE condition (subpartitioning use case in traditional big databases). E.g. below condition won't be applying partition pruning by whole expression as partitions can't be eliminated by minmax of column itself, and can't be eliminated by full expression because it's not supplied.
`
WHERE userId=3333
`

1. Inequality condition on part of tuple won't work.
`
WHERE dateCol>='2020-01-01' and dateCol<'2020-01-10' and userId%5 >=100500 and userId%5<900000
`

Shortly, when creating table clickhouse shall
- understand which columns are used in calculation of each part of tuple of partition-by expression and keep the dependency

`
PARTITION BY (toYYYYMM(dateCol), userId%5)
`
pb.1 dependent columns=dateCol
pb.2 dependent columns=userId

 parsing where condition clickhouse shall:

- understand which columns are used in calculation of which part of tuples of partition by expression (e.g. userId is used in "userId%5" calculation)
- apply those calculations to them and check which partitions are to be eliminated for equality conditions for expressions with non-monotonic functions (e.g. get userId=1000 or userId IN (1000) condition, derive 1000%5, and find related partition), and both inequality and equality conditions when only monotonic functions used in expression.
- apply partition elimination by minmax values of columns itself on remaining partitions (same as now)

Above functionality allows clickhouse to support both hash-partitioning and sub-partitioning cases properly.

**Comment by den-crane** [comment]
it does not needed anymore. It was solved by another way,
