### ISSUE TITLE
MUTATE_PART for part 202004_34751_34751_0_50646 because source parts size (2.58 MiB) is greater than the current maximum (0.00 B).

### ISSUE THREAD

**Issue by org0000h** [ClickHouse/ClickHouse#10224]
MUTATE_PART for part 202004_34751_34751_0_50646 because source parts size (2.58 MiB) is greater than the current maximum (0.00 B).

**Comment by org0000h** [comment]
why dose the current maximum  is 0.00B?
my clickhouse ver is 19.16.14.65

**Comment by filimonov** [comment]
Because there is already too many running concurrent merges / mutations. 

While some merge or mutation is running it decreases the maximum size for other mutations/mutations,  which can be executed at the same time. That logic makes prevent from running several huge merges/mutations simultaneously.

**Comment by org0000h** [comment]
thank you

**Comment by filimonov** [comment]
See also https://github.com/ClickHouse/ClickHouse/issues/4101#issuecomment-613791667
