### ISSUE TITLE
Wrong timestamp

### ISSUE THREAD

**Issue by BaltX** [ClickHouse/ClickHouse#10289]
**Describe the bug**
timezone "Etc/GMT+3"(+4, +5, etc) show results for tz -3 (-4, -5, etc)

**How to reproduce**
```
select
    toDateTime(toDateTime('2020-04-08 00:00:00'), 'Europe/Moscow'),
    toDateTime(toDateTime('2020-04-08 00:00:00'), 'Etc/GMT-3'),
    toDateTime(toDateTime('2020-04-08 00:00:00'), 'Etc/GMT+3')
```

**Expected behavior**

time for 'Europe/Moscow' and for 'Etc/GMT+3' must be same
The time for 'Etc/GMT+3' should be 6 hours later than for 'Etc/GMT-3'

**Comment by den-crane** [comment]
https://en.wikipedia.org/wiki/Tz_database#Area

Area

Area is the name of a continent, an ocean, or "Etc". The continents and oceans currently used are Africa, America, Antarctica, Arctic, Asia, Atlantic, Australia, Europe, Indian, and Pacific.

The oceans are included since some islands are hard to connect to a certain continent. Some are geographically connected to one continent and politically to another. See also Boundaries between continents.

The special area of "Etc" is used for some administrative zones, particularly for "Etc/UTC" which represents Coordinated Universal Time. In order to conform with the POSIX style, those zone names beginning with "Etc/GMT" have their **sign reversed** from the standard ISO 8601 convention. In the "Etc" area, zones west of GMT have a positive sign and those east have a negative sign in their name (e.g "Etc/GMT-14" is 14 hours ahead of GMT).
