### ISSUE TITLE
Support avg in SimpleAggregateFunction

### ISSUE THREAD

**Issue by vmihailenco** [ClickHouse/ClickHouse#10305]
``` sql
avg SimpleAggregateFunction(avg, Float32) Codec(Delta, LZ4)

DB::Exception: Unsupported aggregate function avg, supported functions are any,anyLast,min,max,sum,groupBitAnd,groupBitOr,groupBitXor
```

**Comment by vmihailenco** [comment]
I assumed `new_avg = avg((existing_val + new_val) / 2)` which only requires existing state and new state. I guess min works the same `new_min = min(existing_val, new_val)`. Am I missing something?

**Comment by filimonov** [comment]
> I assumed `new_avg = avg((existing_val + new_val) / 2)` which only requires existing state and new state. I guess min works the same `new_min = min(existing_val, new_val)`. Am I missing something?

You do. 
((10+50)/2 +90)/2=60 (proper avg for thouse 3 numbers is 50).

Avg = sum / count 
Sum and count can both be simple aggregate functions. Just divide one by another at select time.

**Comment by vmihailenco** [comment]
I use `sum / count` trick when I can and that is usually called `mean` value.

But sometimes I have only single value and want to calculate the value in between `(x+y)/2`. It seems to be better than using `min/max/any`.

**Comment by filimonov** [comment]
That has no sense at all.

It will be as accurate as random from the range min(value) ... max(value).

ClickHouse need a way to merge 2 states of aggregate functions. 

So if we have a block of data with value = 1, and a second block of data with value = 1000000.
Depending on the number of records participating in each block the real average can be close to 1 (because there was a lot of records with value 1), or to 1000000 (because there was a lot of records with value 1000000).

**Comment by vmihailenco** [comment]
>and as accurate as random from the range min(value) ... max(value).

For your example `10,50,90` it provides better result than random. And somehow world is using `x+y/2` despite all its flaws and it is definitely better than random. I would use better tools like tdigests or ddsketch - but first is broken and 2nd is not available.

**Comment by filimonov** [comment]
Just change the order to get completely another result.
`((90+50)/2 +10)/2=40`

Are you sure that 15 here is a correct answer?
((10+10)/2 + (20+20+20+20+20+20+20+20+20)/9)/2

That approach is not usable.
