### ISSUE TITLE
Introduce a setting that forbids to create tables in old/legacy format by default

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#10406]
Introduce a setting that forbids to create tables in old/legacy format by default

a) Without affecting existing tables - attach.
b) Or with 3 states `old_merge_tree_format` = `deny`, `allow_attach`, `allow_create`
By default  `old_merge_tree_format` =  `allow_attach`

**Comment by qoega** [comment]
Can we rewrite metadata from old format to new one after attach?

**Comment by den-crane** [comment]
> Can we rewrite metadata from old format to new one after attach?

Formats / parts are incompatible. 
There is no proper converter for parts from the old format to the new. It would be nice to have something like `alter table TTT convert to custom_partitioning` but it's way more complicated story.

**Comment by alexey-milovidov** [comment]
As far as I remember, we can convert table definition from old to new format on creation time. But we should not do it because it will make impossible to create new replicas for tables of old format.

Add a setting is easy task to do and reasonable.

Also this task is loosely related to the task of support CREATE TABLE without specifying columns/keys if it is a new replica.

**Comment by filimonov** [comment]
> Can we rewrite metadata from old format to new one after attach?

https://github.com/ClickHouse/ClickHouse/blob/master/utils/convert-month-partitioned-parts/main.cpp

**Comment by alexey-milovidov** [comment]
Add a query level setting `allow_created_merge_tree_tables_in_old_format`, 0 by default.
ATTACH will be always allowed.

**Comment by den-crane** [comment]
implemented in https://github.com/ClickHouse/ClickHouse/pull/38335 `allow_deprecated_syntax_for_merge_tree`
