### ISSUE TITLE
BUG: (small) negative variance & nan standard deviation

### ISSUE THREAD

**Issue by inkrement** [ClickHouse/ClickHouse#10532]
**Describe the bug**
I tried to calculate the standard deviation on a variable using `stddevSamp`. However, the command returned nan. Investigating this problem revealed, that `varSamp` returns a really small *and* _negative_ value, which cannot be the case. I thought about switching to log-scale to avoid the problem with too small numbers. Maybe this would be also a possibility for other users.

**How to reproduce**
I am using version 20.1.8.41. Sadly, I am not able to share the data set. However, I am calculating the variance on a single element of a float array `SELECT stddevSamp(features[73]) as ft_s FROM tbl`. I calculated it for multiple elements in the array and one out of 5 showed this behaviour. 

**Expected behavior**
Variance should never be negative. This should trigger at least a warning. 

**Error message and/or stacktrace**
No error message, just a nan in case of stddevSamp and a negative value for varSamp.

**Additional context**
I guess the problem is, that my numbers are really small (always between 0 and 1) and may contain nulls.

**Comment by alexey-milovidov** [comment]
We have two variants of every statistical function:

Ordinary:
`varSamp`
`varPop`
`stddevSamp`
`stddevPop`
`covarSamp`
`covarPop`
`corr`

And numerically stable:
`varSampStable`
`varPopStable`
`stddevSampStable`
`stddevPopStable`
`covarSampStable`
`covarPopStable`
`corrStable`

The difference is that numerically stable variants use sophisticated algorithm (similar to Kahan summation) to avoid growth of error during computations.

By default you get faster version of functions, because the difference is small enough in almost every use case. Most of other DBMS also use numerically unstable algorithm.

But we obviously should not return negative value for variance and stddev. Let's just trim to zero.

**Comment by inkrement** [comment]
Thanks! I wasn't aware of the stable functions!
