### ISSUE TITLE
Why we can't use IS NULL or IS NOT NULL as join condition

### ISSUE THREAD

**Issue by XavierQuiniou** [ClickHouse/ClickHouse#10690]
We meet this problem whe using Taleau V. 2019-4 (www.tableau.com).
This example shows a join condition based on the comparison of two null values.
<pre>
SELECT ...
INNER JOIN other_table
ON ( ... = ... )
AND( ... = ... )
<b>OR
  (
    (
      (
         (CAST(trunc(EXTRACT(YEAR FROM `MY_TABLES`.`Date`),0) AS INTEGER) * 100) +
          CAST(trunc(EXTRACT(MONTH FROM `MY_TABLES`.`Date`),0) AS INTEGER)
      ) IS NULL
    )
    AND 
    (
     `t0`.`my_Date_ok` IS NULL
    )
  )</b>
</pre>
<i>The OR section is a copy of an extract as observed in the log.</i>
CH rejects it because it does not recognize the classic expression A.id = B.id. 
<tt>DB::Exception: Invalid expression for JOIN ON. Expected equals expression, got 
(((CAST(trunc(toYear(`--MY_TABLES.Date`), 0), 'INTEGER') * 100) ... (version 20.3.3.6 (official build))</tt>
Is this normal?
If true, it would seem strange to consider that Tableau is buggy.

**Comment by den-crane** [comment]
Because CH does not support such joins now.

Actually CH able to support `JOIN ON a <=> b` but it is not implemented https://github.com/ClickHouse/ClickHouse/issues/3889

**Comment by XavierQuiniou** [comment]
Very disappointed with your answer, I draw your attention to the fact that this goes against the interests of Altinity, which is trying to promote the use of CLICKHOUSE among users of TABLEAU.

**Comment by den-crane** [comment]
Who is Altinity? Why I should worry about it? Or about TABLEAU?

It is what it is. CH is an open source product driven by the community. It will be implemented eventually. I hope.

**Comment by filimonov** [comment]
Keep calm @XavierQuiniou. Altinity's here :) 

Of course we aware that there are certain limitations (and workaround for them - check that issue and comments:
https://github.com/ClickHouse/ClickHouse/issues/3830 ) 

That issue will definitely be fixed - it was not done yet just because it's quite complicated, and require some intermediate  steps (in last half a year there was a lot of Join improvements, and more will arrive).

Usually users are able to forgive small inconsistancies in SQL support when they need to process really huge datasets fast. Most of the databases which support full sql standard and support Tableau are just not able to process the amount of data where ClickHouse feel comformltable :) 

And ClickHouse improves really fast, and you can also help in that :) 

Stay tuned :)

**Comment by XavierQuiniou** [comment]
Just a few words to conclude.

Our problem was solved by completing <tt>escape_sequences # replaceEscapeSequences (..)</tt>, with a step
additional parsing. We have written a parser that builds a very simple token tree.
The branches are created by the expression detection <tt>(.....)</tt>.
This technique thus allows us to delete  expressions <tt>(... IS NULL)</tt> relating to an <tt>ON</tt> token.

(This choice is relevant insofar as we do not use any nullable column).
