### ISSUE TITLE
Split background pools for merges/mutations and fetches.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#10987]
Merges and fetches are using the same BackgroundProcessingPool.
It has the following disadvantages:

1. When replica is recovering, it's possible that all the threads in pool are occupied for fetches and no merges are processing. It leads to "Too many parts" error.

2. The size of BackgroundProcessingPool is way large for fetches. Even a few connections can utilize 10 Gbit network and usually there is no point to fetch data with 16 connections.

Alternative solutions:
- limit amount of threads doing fetches in BackgroundProcessingPool.

@Akazz if you are interested, or unassign please.

**Comment by Akazz** [comment]
The way I see it, it is hardly possible to just limit number of fetches, because both merges and fetches are performed by the same service task. When executed, this task dynamically selects between the two actions based on the type of the queue entry (thus we cannot know beforehand what type it is going to be). So it all gets back to separating merges and fetches.
