### ISSUE TITLE
Investigate memory-related unstable latencies in performance tests

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#11121]
A list for me not to forget.

I've seen two main sources of unpredictable memory-related latency:
* Some pages we receive from the allocator may be newly allocated from the OS and still be copy-on-write references to zero page. On write to such pages, page fault occurs, and a new writable page is allocated and filled with zeros.
* Sometimes jemalloc decides that it's time to purge the arena and peforms MADV_DONTNEED on some pages.

What can we do about this:
* Increase (or maybe decrease instead?) the decay time for arenas, governed by the `arenas.dirty_decay_ms` and `arenas.muzzy_decay_ms` parameters. Read the docs carefully, because it's not obvious what they influence. Tried to do this once, but ran into some Weirdness with our cmake config that prevented me from using `mallctl` (USE_JEMALLOC not defined for Server.cpp). A sample snippet for `Server::initialize`:
```
+
+#if USE_JEMALLOC
+    const int64_t decay_time_ms = 10 * 60 * 1000;
+    logger().information("Will set jemalloc decay time to %ls ms\n", decay_time_ms);
+    logger().information("test");
+
+    int err = mallctl("arenas.dirty_decay_ms", nullptr, nullptr, &decay_time_ms, sizeof(decay_time_ms));
+    if (err != 0)
+        logger().error("Failed to set 'arenas.dirty_decay_ms' with code %ld", err);
+
+    err = mallctl("arenas.muzzy_decay_ms", nullptr, nullptr, &decay_time_ms, sizeof(decay_time_ms));
+    if (err != 0)
+        logger().error("Failed to set 'arenas.muzzy_decay_ms' with code %ld", err);
+#endif
+
```
* Decay the arenas explicitly using `arenas.<i>.decay` with `i = MALLCTL_ARENAS_ALL`. This could be a hidden system query e.g. `system reset memory`, and we could call it before we start test runs of each query from performance tests.

**Comment by alexey-milovidov** [comment]
The SYSTEM query to flush allocation cache can be generally useful.

**Comment by azat** [comment]
>arenas.muzzy_decay_ms

Note that current bundled version of jemalloc should not create muzzy pages, since `madviace(MADV_FREE)` is disabled:

https://github.com/ClickHouse/ClickHouse/blob/3ff28d0a7a4d53c2be2604bceae76149e3c5bf39/contrib/jemalloc-cmake/include_linux_x86_64/jemalloc/internal/jemalloc_internal_defs.h.in#L295-L296

(duplicated for history)

>Tried to do this once, but ran into some Weirdness with our cmake config that prevented me from using mallctl (USE_JEMALLOC not defined for Server.cpp).

I did something similar for testing `background_thread`, you can find it [here](https://github.com/ClickHouse/ClickHouse/pull/11086/files).

Also, for testing purpose you can enable using one of the following ways:
- add env variable - `MALLOC_CONF=dirty_decay_ms:-1`
- `ln -s dirty_decay_ms:-1 /etc/malloc.conf`

*`-1` will disable them completely*

Also if you will enable `background_thread`, then this operations can be done in background, I tried, [no difference for me](https://github.com/ClickHouse/ClickHouse/pull/11086):

>Performance — 1 faster, 1 slower, 131 unstable, 7 errors

**Comment by akuzm** [comment]
Changed muzzy decay to 10s without much effect. Let's consider it done for now.
