### ISSUE TITLE
clickhouse-local freezes on multiple read from pipe

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#11124]
```
echo 1 | build-clang10/programs/clickhouse-local --structure "a int" --query "select a from table where a in (select a from table)"
```

This does not finish. Works fine if I put this `1` into a file and specify it with `--file`.
This is a usability problem for using `clickhouse-local` in a pipeline. Also sometimes it doesn't freeze but returns unexpected result, which is even worse. I've had this happen but don't remember the exact scenario now.

**Comment by alexey-milovidov** [comment]
This is considered as the expected behaviour.
You have specified that table data is streamed from pipe. You cannot read this data twice.

But we can do better:
- check if it's a regular file or pipe;
- if it's a regular file, seek to begin before read;
- if it's pipe, throw exception if we are trying to read the same pipe twice.

**Comment by alexey-milovidov** [comment]
@Amesaru

**Comment by alexey-milovidov** [comment]
Amesaru did not try to do this task.

**Comment by BoloniniD** [comment]
I'll try to do the task.
