### ISSUE TITLE
Size of Memory table

### ISSUE THREAD

**Issue by Tri0L** [ClickHouse/ClickHouse#11147]
Hello!

Is it possible to get size of table with engine Memory?

**Comment by den-crane** [comment]
No.

**Comment by azat** [comment]
Actually it is possible already (#9919):

From the [doc](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/operations/system-tables.md#systemtables-system-tables) (cannot use link to the official documentation since anchor for `system.tables` broken by the `system tables` - article header):

-   `total_rows` (Nullable(UInt64)) - Total number of rows, if it is possible to quickly determine exact number of rows in the table, otherwise `Null` (including underying `Buffer` table).

-   `total_bytes` (Nullable(UInt64)) - Total number of bytes, if it is possible to quickly determine exact number of bytes for the table on storage, otherwise `Null` (**does not** includes any underlying storage).

    -   If the table stores data on disk, returns used space on disk (i.e. compressed).
    -   If the table stores data in memory, returns approximated number of used bytes in memory.

This should work for Memory and Buffer

**Comment by Tri0L** [comment]
Great, thanks a lot!
