### ISSUE TITLE
Table ORDER BY sanitization issue

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#11333]
Things like that should be forbidden:
```
CREATE TABLE a
(
    `number` UInt64
)
ENGINE = MergeTree
ORDER BY if(now() > toDateTime('2020-06-01 13:31:40'), toInt64(number), -number)
```

Just like those (which are forbidden already):
```
CREATE TABLE a
(
    `number` UInt64
)
ENGINE = MergeTree
ORDER BY if(rand() > 100, toInt64(number), -number)

Received exception from server (version 20.4.4):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Sorting key cannot contain non-deterministic functions, but contains function rand. 
```

**Comment by alexey-milovidov** [comment]
@alesapin Looks like easy to do. Could you please take a look?

**Comment by zxc111** [comment]
hi @alexey-milovidov 
I find `rand()` is based `IFunction`, but `now()` is based `IExecutableFunction` and return `createColumnConst` as result.
So the check in  [checkKeyExpression](https://clickhouse.tech/codebrowser/html_report/ClickHouse/src/Storages/MergeTree/MergeTreeData.cpp.html#281) is not work.(I'm not sure).
What should we do, change `now()` function to be based `IFunction` or any idea?

**Comment by alexey-milovidov** [comment]
@zxc111 Yes, it is related to constant folding.
The constant folding happens before the check and the function `now` does not exist in actions.

Proper solutions can be:
- ask ExpressionActions or ActionsDAG to check for non-determinism;
- save folded expressions in .sql metadata, so `now()` is resolved at creation time and substituted; but we should also do the same for ORDER BY key stored in ZooKeeper for Replicated tables, otherwise it will not match.
