### ISSUE TITLE
Add a setting `system_metrics_events_show_zero_values`.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#11384]
If set to 1, include all metrics, even with zero values.

**Comment by Slach** [comment]
I want to explain why this feature is required and which corner cases it covers
- `system.metrics`, `system.events` and `system.asyncronous_metrics` can be monitored via prometheus
- prometheus has a `scraping interval`
- when "system.events" doesn't contain data with some critical events, like `DelayedInserts` or `RejectedInserts` for example before the first increment this counters will occur then prometheus probably will scrape only `X value`, instead of sequence `0 and X value` between two scraping interval 
- so alerts which calculated as increase(DelayedInserts[1m]) will not triggered

**Comment by alexey-milovidov** [comment]
`system.metrics` and `system.asynchronous_metrics` already show zero values.
So, this setting is applicable only to `system.events` and should be named `system_events_show_zero_values`.

**Comment by alexey-milovidov** [comment]
Assigned to @dimarub2000
