### ISSUE TITLE
20.4 + dictGet + group by = Function dictGet... takes 3 or 4 arguments.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#11469]
Regression (20.3 and earlier work properly).

`dictGetString` works properly too. 

test case:
```sql
CREATE TABLE countries_table
(
  id UInt64,
  code String,
  country String
)
ENGINE = MergeTree()
ORDER BY id;

INSERT INTO countries_table VALUES (0,'AF','Afghanistan'), (1,'AL','Albania'), (2,'DZ','Algeria'), (3,'AS','American Samoa');

CREATE DICTIONARY countryId
(
  id UInt64 DEFAULT 0,
  code String DEFAULT '',
  country String DEFAULT ''
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 USER 'default' TABLE 'countries_table' PASSWORD '' DB 'default'))
LIFETIME(MIN 1 MAX 10)
LAYOUT(FLAT());

-- that works
SELECT dictGetString('default.countryId', 'country', toUInt64(number)) AS country FROM numbers(2) GROUP BY country;

-- that does not work on 20.4
SELECT dictGet('default.countryId', 'country', toUInt64(number)) AS country FROM numbers(2) GROUP BY country;

-- that works
SELECT dictGet('default.countryId', 'country', toUInt64(number)) AS country FROM numbers(2);
```

**Comment by admitad-github** [comment]
We are struggling with this issue, because we have to update ClickHouse up to version 20.4 due to this bug #6269 fixed only starting from 20.4. This is crucial because we have a large amount of data being marked as broken which is required to be restored manually.

We can't update to 20.4 because we already have a lot of queries with usage of `dictGet` in GROUP BY. It requires tremendous amount of work to update every query. It would be easy for as if we just could replace `dictGet` with `dictGetString`, but another problem appears as we have not just `String` type in dict, but `Decimal`. There is no special function as `dictGetDecimal`.

We are really looking forward to this fix.

**Comment by alexey-milovidov** [comment]
The bug was introduced in https://github.com/ClickHouse/ClickHouse/pull/10342
CC @azat

**Comment by alexey-milovidov** [comment]
@azat This is also broken:

```
milovidov-desktop :) SELECT dictGetString('default' || '.countryId', 'country', toUInt64(number)) AS country FROM numbers(2) GROUP BY country;

SELECT dictGetString(concat('default', '.countryId'), 'country', toUInt64(number)) AS country
FROM numbers(2)
GROUP BY country


Received exception from server (version 20.6.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::ASTFunction to DB::ASTLiteral.
```

**Comment by azat** [comment]
>The bug was introduced in #10342

Interesting, but this PR does not touches the dictionary handling, looking
