### ISSUE TITLE
Polymorphic parts

### ISSUE THREAD

**Issue by shubham721** [ClickHouse/ClickHouse#11500]
How to use polymorphic parts instead of buffer engines, If we have frequent updates (like 100 in a sec) ?

**Comment by CurtizJ** [comment]
You can set settings `min_rows_for_wide_part` and `min_bytes_for_wide_part` for any `MergeTree`-family table (by `ALTER MODIFY SETTING` query or globally in config). In that case, if size of inserted part in rows or in bytes less than corresponding threshold, part will will be written in compact format, otherwise in wide (current) format. `10M` is considered to be a good value for min_bytes_for_wide_part`. Note that you will be unable to downgrade to version lower than 20.3 if you use new parts format.
