### ISSUE TITLE
Final keyword in select doesn't work as expected with CollapsingMergeTree

### ISSUE THREAD

**Issue by lihaostar** [ClickHouse/ClickHouse#11640]
Using ClickHouse server version 20.4.5.36 (official build)
<pre>
-- Same example from official documents
CREATE TABLE UAct
(
    UserID UInt64,
    PageViews UInt8,
    Duration UInt8,
    Sign Int8
)
ENGINE = CollapsingMergeTree(Sign)
ORDER BY UserID

-- It doesn't matter if the two are in one part or two parts.
INSERT INTO UAct VALUES (4324182021466249494, 5, 146,-1)(4324182021466249494, 5, 146,1)
</pre>
Then we have the following which is expected -
<pre>┌──────────────<b>UserID</b>─┬─<b>PageViews</b>─┬─<b>Duration</b>─┬─<b>Sign</b>─┐
│ 4324182021466249494 │         5 │      146 │   -1 │
│ 4324182021466249494 │         5 │      146 │    1 │
└─────────────────────┴───────────┴──────────┴──────┘
</pre>
Because -1 comes first so these two won't be merged. 
<pre>
optimize table UAct final
select * from UAct
┌──────────────UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│ 4324182021466249494 │         5 │      146 │   -1 │
│ 4324182021466249494 │         5 │      146 │    1 │
└─────────────────────┴───────────┴──────────┴──────┘
</pre>
Next, run "Select ... Final" but it gives me another result - 
<pre>
select * from UAct final
┌──────────────<b>UserID</b>─┬─<b>PageViews</b>─┬─<b>Duration</b>─┬─<b>Sign</b>─┐
│ 4324182021466249494 │         5 │      146 │    1 │
└─────────────────────┴───────────┴──────────┴──────┘
</pre>

Shouldn't "Select ... Final" run as if "Optimize ... Final" has been done? Meaning, I should see both -1 and 1?
More specifically, if I only insert one record `INSERT INTO UAct VALUES (4324182021466249494, 5, 146, -1)` once the table is created, "Select * from UAct" gives that record but "Select * from UAct Final" gives me nothing. So what should I expect from "Final" keyword?

**Comment by alexey-milovidov** [comment]
Short answer is that OPTIMIZE and SELECT FINAL may behave in a different way if data is incomplete.

For more detailed answer, let's ask @KochetovNicolai

**Comment by KochetovNicolai** [comment]
Actually, `FINAL` for `CollapsingMergeTree` have being working that way form the beginning.
The main idea, as I understand it, that every row with `sign = -1` should have coupling **previous** row with `sign = 1`.
Data in your example is assumed by `CollapsingMergeTree` as incorrect. However, at the moment data is merged together, algorithm can't identify it, because there may be previous part with corresponding `sign = 1` row, which is not participate in merge.
At the moment of `SELECT FINAL` algorithm knows that all data will be read. So, it detects first `sign = -1` row as an wrong data and skips it. It is a special `only_positive_sign` flag in the code:
https://github.com/ClickHouse/ClickHouse/blob/25f941020b578f2e9d479ae7df02d0148619fdb1/src/Processors/Merges/Algorithms/CollapsingSortedAlgorithm.cpp#L78-L80

**Comment by KochetovNicolai** [comment]
So, the main idea is: row with `sign = -1` may *cancel* only **previously** inserted row. If there is no such row, `SELECT FINAL` just ignores it as a wrong data.

**Comment by lenhnv1305** [comment]
I got the same issue when sign = -1 but there is no a record exists previously the final keyword will still display this record. shouldnt this sign = -1 record show even there is no record exist before? I used VersionedCollapsingMergeTree
