### ISSUE TITLE
Import data with clickhouse-native-jdbc,disk space problem

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#11724]
I tried to import data using addBatch() with clickhouse-native-jdbc.After I import several batches,the disk space became full(I remained about 100GB free disk space), later,the disk space was slowly freed automatically.So can you tell me what's the reason and how to solve this problem?
Thank you!

**Comment by den-crane** [comment]
You can change MergeTree parameter old-parts-lifetime

```
<yandex>
    <merge_tree>
        <old_parts_lifetime>10</old_parts_lifetime>
        <temporary_directories_lifetime>10</temporary_directories_lifetime>
    </merge_tree>
</yandex>

```



---

## old \ _parts \ _lifetime {# old-parts-lifetime}

The time (in seconds) for storing inactive pieces to protect against data loss during spontaneous reboot of the server or OS.

Possible values:

- A positive integer.

The default value is 480.

After merging several pieces into a new piece, ClickHouse marks the original pieces as inactive and removes them after the `old_parts_lifetime` seconds.
Inactive chunks are deleted if they are not used in current requests, i.e. if the link reference counter is `refcount`, it is zero.

Inactive chunks are not deleted immediately, because `fsync` is not called when writing a new chunk, i.e. for a while, a new piece is only in the server’s RAM (OS cache). T.O. during a spontaneous reboot of the server, a new (contingent) piece may be lost or damaged. In this case, ClickHouse during the startup process when checking the integrity of the pieces will detect a problem, return inactive pieces to the list of active ones and later re-hold them. In this case, the broken piece is renamed (the prefix broken \ _ is added) and moved to the detached folder. If the integrity check does not detect problems in the contiguous chunk, then the original inactive chunks are renamed (the prefix ignored \ _ is added) and moved to the detached folder.

The default value for Linux dirty \ _expire \ _centisecs is 30 seconds (the maximum time that recorded data is stored only in RAM), but with heavy loads on the disk system, data can be written much later. The time was found experimentally - 480 seconds, during which a new piece is guaranteed to be recorded to disk.
