### ISSUE TITLE
high concurrency, high frequency, small inserts

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#11783]
We encountered an use case where a lot of tiny batches of data(several rows to dozens of rows) coming from online streaming data brokers (such as Kafka, Storm) are feeded into backend database.

As suggested, Clickhouse MergeTree engine cannot efficiently handle this situation. We also tested "Buffer" engine using single row insert. The result is as follows:

concurrency(thread),  performance(rows/seconds)
1, 1500
10, 3800
20,  some of threads reported "failed to response"

Is this result normal? Since "Buffer" is memory-based, I guess its inserting performance should be higher, 10 thousands/second?

Do we have a plan to add LSM-tree similar support for small inserts and to allevate “too many parts” problem?

“Note that it doesn’t make sense to insert data one row at a time, even for Buffer tables”, why?

Can we combine buffer Engine with "compact format of parts" together?

**Comment by den-crane** [comment]
>20, some of threads reported "failed to response"

Can you elaborate? Do you use JDBC driver? And got " :8123 failed to respond" ? 
It is small issue in JDBC driver and you should just repeat your query.

>Since "Buffer" is memory-based, 
>I guess its inserting performance should be higher, 10 thousands/second?

HTTP protocol has overhead and latency.
 10k/s is problem on HTTP level. Your **client** simly unable to handle 10k http calls/s, and it's a hard task for CH to serve 10k HTTP calls/s -- wasting CPU.

>“Note that it doesn’t make sense to insert data one row at a time, even for Buffer tables”, why?

because of 10k problem / C10k_problem -- Every HTTP/TCP call has some overhead and latency and this overhead is too high for one row.
So  `one row at a time` is just wasting resources on network communications/tcp connections serving in kernel.

**Comment by etah000** [comment]
Yes, I used jdbc to insert data one row each insert in 20 threads.

I just want to know where is performance bottlenect while CH processes a large number of small inserts in parallel. 

We know that mysql can handle 10k single row insert each second, so you mean that it is the connecting protocol that limits the performance of CH?

**Comment by den-crane** [comment]
>failed to respond

"Failed to respond" -- it's an JDBC driver issue. You should just repeat your insert in this case.
Or try another JDBC drivers https://github.com/blynkkk/clickhouse4j https://github.com/housepower/ClickHouse-Native-JDBC


>I just want to know where is performance bottlenect while 
>CH processes a large number of small inserts in parallel.

Overhead is huge for single-row inserts. It's recommended to insert at least 1000 rows (or once/per second) even into buffer table for better throughput.
