### ISSUE TITLE
MATERIALIZED VIEW always lost some data

### ISSUE THREAD

**Issue by icbinf** [ClickHouse/ClickHouse#11902]
We create a MATERIALIZED VIEW, but always lost some data (Less calculation results than the original table), how can I find out the problem?

create sql:
CREATE MATERIALIZED VIEW hp_rt.app_hp_resource_bit_v_test ON CLUSTER hpanalysisrt ENGINE = ReplicatedAggregatingMergeTree( '/clickhouse/ck.test.t/tables/{layer}-{shard}/hp_rt/app_hp_resource_bit_v_test', '{replica}') PARTITION BY toYYYYMMDD(time) ORDER BY(event_id,res_bit_title,activity_id,activity_name,time) TTL time + toIntervalDay(3) SETTINGS index_granularity = 8192 populate
AS
    SELECT
        toStartOfHour(event_time) AS time,
        event_id,
        res_bit_title,
        activity_id,
        activity_name,
        sumState(1) PV,
        uniqState(uid) AS UV
    FROM
        hp_rt.app_hp_resource_bit
    GROUP BY
        event_id,
        res_bit_title,
        activity_id,
        activity_name,
        toStartOfHour(event_time)

**Comment by filimonov** [comment]
Inserts into original table & matview is not atomic (yet). 

The issue may be due to some temporary errors / block deduplication on replicated tables / loosing the insert because MV executed in sequence an some of prev MV failed.

Check the settings
- parallel_view_processing
- deduplicate_blocks_in_dependent_materialized_views

**Comment by filimonov** [comment]
Also https://github.com/ClickHouse/ClickHouse/issues/11909

**Comment by tchaton** [comment]
Facing the same issue.
