### ISSUE TITLE
Early evaluation of function to Literal

### ISSUE THREAD

**Issue by hustnn** [ClickHouse/ClickHouse#11979]
I have a question about this SQL:

`SELECT * FROM test.hits2 WHERE date = today();`

Is there any way to evaluate the function `today` in parsing stage instead of executing stage?
Thanks.

**Comment by alexey-milovidov** [comment]
I wonder what is the motivation to evaluate it on the parsing stage and what will be visible side effect of it?

We do constant folding but it is implemented in query analysis step. It seems logical and provide better separation of concepts.

Btw, there is historical fact that gcc was doing simply constant folding at parsing stage (e.g. `1 + 1`) but clang does not and one of clang developers even promoted it as an example of one of the advantages of clang over gcc, because it simplifies error reporting, AST analysis and overall design of the system.

**Comment by hustnn** [comment]
@alexey-milovidov 
From the following figs, I found that the today() is still a function call, I thought the function will be called for each row in executing stage, if we can substitute it to 2020-06-24, then don't have the extra function call. (please correct me if I am wrong).

The dump tree of the query `SELECT * FROM test.hits2 WHERE date = today()`
![image](https://user-images.githubusercontent.com/73186/85848280-76f96c80-b7db-11ea-9ecf-e4566b738cab.png)


and the dump tree of the query `SELECT * FROM test.hits2 WHERE date = '2020-06-24'`
![image](https://user-images.githubusercontent.com/73186/85848297-81b40180-b7db-11ea-8ba8-829944878ceb.png)

**Comment by alexey-milovidov** [comment]
> I thought the function will be called for each row in executing stage

No, it won't. It will be evaluated once and substituted at query analysis stage.

**Comment by hustnn** [comment]
@alexey-milovidov 

Oh, Thanks. Is the evaluate and substitution implemented with AST rewrite? Can you point this part?

**Comment by alexey-milovidov** [comment]
It's done inside `ExpressionActions` - `ExpressionActions.cpp`, grep `constant folding` and `isSuitableForConstantFolding`.

**Comment by hustnn** [comment]
@alexey-milovidov Thanks a lot.
