### ISSUE TITLE
ReplicatedMergeTree in Atomic database

### ISSUE THREAD

**Issue by hohaftf** [ClickHouse/ClickHouse#12135]
What is the proper way to create replicated table in database with Atomic engine?
Should I use some template or it's a bug?

UPD: I found out that after about 8-9 minutes I can recreate table.
```
create database db1 engine=Atomic;

create table db1.test 
(i1 Int32) 
engine=ReplicatedMergeTree('/clickhouse/tables/db1/test', '{replica}') 
order by i1;

drop table db1.test;

create table db1.test 
(i1 Int32) 
engine=ReplicatedMergeTree('/clickhouse/tables/db1/test', '{replica}') 
order by i1;
```

When executing last CREATE query I got 
>2020.07.04 23:14:10.409366 [ 85 ] {} <Error> DynamicQueryHandler: Code: 253, e.displayText() = DB::Exception: Replica /clickhouse/tables/db1/test/replicas/1A already exists., Stack trace (when copying this message, always include the lines below):
>0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x103fa390 in /usr/bin/clickhouse
>1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x900b8ad in /usr/bin/clickhouse
>2. ? @ 0xd749a87 in /usr/bin/clickhouse
>3. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0xd720d9c in /usr/bin/clickhouse
>4. ? @ 0xda63dca in /usr/bin/clickhouse
>5. std::__1::__function::__func<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&), std::__1::allocator<std::__1::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::operator()(DB::StorageFactory::Arguments const&) @ 0xda67447 in /usr/bin/clickhouse
>6. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0xd66797d in /usr/bin/clickhouse
>7. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0xd157429 in /usr/bin/clickhouse
>8. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0xd15798d in /usr/bin/clickhouse
>9. DB::InterpreterCreateQuery::execute() @ 0xd158ea1 in /usr/bin/clickhouse
>10. ? @ 0xd52ecc9 in /usr/bin/clickhouse
>11. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd532700 in /usr/bin/clickhouse
>12. DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x90efb4c in /usr/bin/clickhouse
>13. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x90f35a6 in /usr/bin/clickhouse
>14. Poco::Net::HTTPServerConnection::run() @ 0x102aad43 in /usr/bin/clickhouse
>15. Poco::Net::TCPServerConnection::start() @ 0x102e610b in /usr/bin/clickhouse
>16. Poco::Net::TCPServerDispatcher::run() @ 0x102e659b in /usr/bin/clickhouse
>17. Poco::PooledThread::run() @ 0x10494166 in /usr/bin/clickhouse
>18. Poco::ThreadImpl::runnableEntry(void*) @ 0x1048f420 in /usr/bin/clickhouse
v19. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
>20. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 20.4.5.36 (official build))

**Comment by tavplubix** [comment]
It's because with `Atomic` database engine `DROP TABLE` query just marks table as dropped. Table are actually removed later in background, when all queries to the table are finished. Even if no queries to the table are running, there is a delay between `DROP TABLE` and background removal, it can be configured by `<database_atomic_delay_before_drop_table_sec>123</database_atomic_delay_before_drop_table_sec>`. Default value is 480 (8 minutes). When executing `DROP TABLE db.table NO DELAY`, this parameter is ignored and delay is 0, but removal is asynchronous anyway. 

It doesn't matter for all table engines except `ReplicatedMergeTree`, and new table with the same name can be created immediately after DROP. As for replicated tables, new table with the same path in ZooKeeper cannot be created while metadata of dropped table still exist. You can specify different ZooKeeper path for new replicated table. You also can set `database_atomic_delay_before_drop_table_sec` to zero or use `DROP TABLE db.table NO DELAY`, but it does not guarantee that metadata will be removed from ZooKeeper immediately.

Such behaviour is a bit confusing and unexpected. The ways we can fix it:

1. Allow `{uuid}` macro in ZooKeeper path and expand it to table UUID generated on initiator node, so new table can be created like `CREATE ... ON CLUSTER ... ENGINE=ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}/', '{replica}')`. It will not conflict with old table since ZooKeeper path is different. Also we can make those engine arguments optional and by default use `'/clickhouse/tables/{uuid}/{shard}/'` for path and `'{replica}'` or `'{FQDN}'` for replica name. 
**Disadvantages:** It's inconvenient to create replicated tables manually (without `ON CLUSTER`), because it this case user should care about unique paths and UUIDs if they want to avoid issues with `Replica already exists`. Cross-replication becomes harder to configure.

2. Generate table UUID on each node independently and use it as replica name by default or allow `{uuid}` macro for replica name. 
**Disadvantages:** There is no global table identifier for distributed and `ON CLUSTER` queries. ZooKeeper path still not unique, unexpected side effects are possible when creating new table as replica of some dropped table.

I prefer the first variant, but probably there are some other solutions and considerations that I didn't take into account.

**Comment by geekyouth** [comment]
> It's because with `Atomic` database engine `DROP TABLE` query just marks table as dropped. Table are actually removed later in background, when all queries to the table are finished. Even if no queries to the table are running, there is a delay between `DROP TABLE` and background removal, it can be configured by `<database_atomic_delay_before_drop_table_sec>123</database_atomic_delay_before_drop_table_sec>`. Default value is 480 (8 minutes). When executing `DROP TABLE db.table NO DELAY`, this parameter is ignored and delay is 0, but removal is asynchronous anyway.
> 
> It doesn't matter for all table engines except `ReplicatedMergeTree`, and new table with the same name can be created immediately after DROP. As for replicated tables, new table with the same path in ZooKeeper cannot be created while metadata of dropped table still exist. You can specify different ZooKeeper path for new replicated table. You also can set `database_atomic_delay_before_drop_table_sec` to zero or use `DROP TABLE db.table NO DELAY`, but it does not guarantee that metadata will be removed from ZooKeeper immediately.
> 
> Such behaviour is a bit confusing and unexpected. The ways we can fix it:
> 
> 1. Allow `{uuid}` macro in ZooKeeper path and expand it to table UUID generated on initiator node, so new table can be created like `CREATE ... ON CLUSTER ... ENGINE=ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}/', '{replica}')`. It will not conflict with old table since ZooKeeper path is different. Also we can make those engine arguments optional and by default use `'/clickhouse/tables/{uuid}/{shard}/'` for path and `'{replica}'` or `'{FQDN}'` for replica name.
>    **Disadvantages:** It's inconvenient to create replicated tables manually (without `ON CLUSTER`), because it this case user should care about unique paths and UUIDs if they want to avoid issues with `Replica already exists`. Cross-replication becomes harder to configure.
> 2. Generate table UUID on each node independently and use it as replica name by default or allow `{uuid}` macro for replica name.
>    **Disadvantages:** There is no global table identifier for distributed and `ON CLUSTER` queries. ZooKeeper path still not unique, unexpected side effects are possible when creating new table as replica of some dropped table.
> 
> I prefer the first variant, but probably there are some other solutions and considerations that I didn't take into account.


---
😢
`DROP TABLE metrics.dws_metric_meituan_demo_32_big_wide_table_ss_local ON CLUSTER s3r2 no delay;`

This sql caused my clickhouse cluster server very terrible trouble , I can not create table any more until i restart the cluster.

这个 sql 导致我的 Clickhouse 集群服务器非常严重的麻烦，在重新启动群集之前，我无法再创建表。

**Comment by tavplubix** [comment]
@geekyouth, please, create new issue with detailed information and attach related logs

**Comment by geekyouth** [comment]
![image](https://user-images.githubusercontent.com/12899262/119094046-14d4d600-ba43-11eb-8b69-950f7a2db8f8.png)
