### ISSUE TITLE
how can I revoke privileges from default user 

### ISSUE THREAD

**Issue by hiliuxg** [ClickHouse/ClickHouse#12950]
I want to revoke all of the default user privileges by sql way ,but it report exeception .
![image](https://user-images.githubusercontent.com/39675622/88561257-c1cc0580-d061-11ea-84da-c8eeb8e99f56.png)

other way , i modify the default user's password in users.xml , but i query failed by jdbc way . The jdbc username is not the default user . the error is that '**DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name**'

how can I revoke privileges from default user ? thanks !

**Comment by alexey-milovidov** [comment]
If the user is defined in `users.xml` (instead of being created by CREATE USER query) it's not possible to revoke grants.

You should
- add another user (with CREATE USER or inside users.xml);
- then remove default user from users.xml;
- then create default user with CREATE USER;

Now you can add or revoke grants.
