### ISSUE TITLE
The startup service always automatically and quickly dies automatically

### ISSUE THREAD

**Issue by boy-xiaozhang** [ClickHouse/ClickHouse#13318]
2020.08.04 09:16:32.473760 [ 47868 ] {} <Debug> real_dw.dwd_fact_cust_allo_log (ReplicatedMergeTreeQueue): Pulling 6 entries to queue: log-0001308950 - log-0001308955
2020.08.04 09:16:32.489470 [ 47855 ] {} <Debug> real_dw.dwd_dim_cust (ReplicatedMergeTreeQueue): Pulling 4 entries to queue: log-0003421840 - log-0003421843
2020.08.04 09:16:32.489479 [ 47845 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997016_2997016_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.489487 [ 47844 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997017_2997017_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.497387 [ 47837 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997018_2997018_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.497442 [ 47842 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997020_2997020_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.505691 [ 47839 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997019_2997019_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.505855 [ 47838 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2993383_2997013_435 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.505904 [ 47836 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997022_2997022_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.506098 [ 47868 ] {} <Debug> real_dw.dwd_fact_cust_allo_log (ReplicatedMergeTreeQueue): Pulled 6 entries to queue.
2020.08.04 09:16:32.506121 [ 47846 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997021_2997021_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.506231 [ 47843 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997023_2997023_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.506995 [ 47834 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997024_2997024_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.507258 [ 47847 ] {} <Debug> real_dw.dwd_dim_cust: Skipping action for part all_2997025_2997025_0 because part all_2993383_2997811_506 already exists.
2020.08.04 09:16:32.525442 [ 47845 ] {} <Debug> real_dw.dwd_fact_cust_dist: Skipping action for part all_68170_68217_3 because part all_25391_68382_3517 already exists.
2020.08.04 09:16:32.525558 [ 47855 ] {} <Debug> real_dw.dwd_dim_cust (ReplicatedMergeTreeQueue): Pulled 4 entries to queue.
2020.08.04 09:16:32.525601 [ 47844 ] {} <Debug> real_dw.dwd_fact_cust_dist: Skipping action for part all_68226_68226_0 because part all_25391_68382_3517 already exists.
2020.08.04 09:16:32.525715 [ 47837 ] {} <Debug> real_dw.dwd_fact_cust_dist: Skipping action for part all_68227_68227_0 because part all_25391_68382_3517 already exists.
2020.08.04 09:16:32.525771 [ 47842 ] {} <Debug> real_dw.dwd_fact_cust_dist: Skipping action for part all_68228_68228_0 because part all_25391_68382_3517 already exists.
2020.08.04 09:16:32.525923 [ 47839 ] {} <Debug> real_dw.dwd_fact_cust_dist: Skipping action for part all_68218_68223_1 because part all_25391_68382_3517 already exists.

The startup service always automatically and quickly dies automatically

**Comment by alexey-milovidov** [comment]
The log you've pasted is incomplete. Need full log from startup to shutdown. Also pay attention to the log messages with severity Warning or Error.

**Comment by boy-xiaozhang** [comment]
> 您粘贴的日志不完整。从启动到关闭都需要完整的日志。还请注意严重性为警告或错误的日志消息。
Hello, the scenario is as follows. In the case of large amounts of data, the Replicated meter will exit unexpectedly, and the restart log will only print the information as described above, without exception, after an attempt to start up will automatically break, and the specific log will be sent to you tomorrow

**Comment by boy-xiaozhang** [comment]
> The log you've pasted is incomplete. Need full log from startup to shutdown. Also pay attention to the log messages with severity Warning or Error.

Hello, the scenario is as follows. In the case of large amounts of data, the Replicated meter will exit unexpectedly, and the restart log will only print the information as described above, without exception, after an attempt to start up will automatically break, and the specific log will be sent to you tomorrow

**Comment by luoqg** [comment]
I also have this problem。Continuous automatic restart

2020.08.07 17:42:29.060255 [ 10662 ] {} <Debug> Application: rlimit on number of file descriptors is 500000
2020.08.07 17:42:29.060271 [ 10662 ] {} <Debug> Application: Initializing DateLUT.
2020.08.07 17:42:29.060282 [ 10662 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Shanghai'.
2020.08.07 17:42:29.060304 [ 10662 ] {} <Debug> Application: Setting up /var/lib/clickhouse/tmp/ to store temporary data in it
2020.08.07 17:42:29.060504 [ 10662 ] {} <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'yn-operation-platform' as replica host.
2020.08.07 17:42:29.062985 [ 10662 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
2020.08.07 17:42:29.063452 [ 10662 ] {} <Information> Application: Uncompressed cache size was lowered to 7.76 GiB because the system has low amount of memory
2020.08.07 17:42:29.063644 [ 10662 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
2020.08.07 17:42:29.064708 [ 10662 ] {} <Information> DatabaseOrdinary (system): Total 1 tables and 0 dictionaries.
2020.08.07 17:42:29.070068 [ 10668 ] {} <Information> BackgroundProcessingPool: Create BackgroundProcessingPool with 16 threads
2020.08.07 17:42:29.071261 [ 10668 ] {} <Debug> system.metric_log: Loading data parts
2020.08.07 17:42:29.095701 [ 10668 ] {} <Debug> system.metric_log: Loaded data parts (1 items)
2020.08.07 17:42:29.095887 [ 10662 ] {} <Information> DatabaseOrdinary (system): Starting up tables.
2020.08.07 17:42:29.099003 [ 10662 ] {} <Information> DatabaseOrdinary (boss): Total 6 tables and 0 dictionaries.
2020.08.07 17:42:29.101796 [ 10688 ] {} <Debug> boss.MOBIL_CODE: Loading data parts
2020.08.07 17:42:29.102273 [ 10687 ] {} <Debug> boss.COLLECTION_DATA: Loading data parts
2020.08.07 17:42:29.102878 [ 10668 ] {} <Debug> boss.COLLECTION_DATA1: Loading data parts
2020.08.07 17:42:29.102993 [ 10689 ] {} <Debug> boss.COMMON_AREA: Loading data parts
2020.08.07 17:42:29.107369 [ 10668 ] {} <Debug> boss.COLLECTION_DATA1: Loaded data parts (1 items)
2020.08.07 17:42:29.108722 [ 10668 ] {} <Debug> boss.SYS_CUSTOMER_MANAGEMENT: Loading data parts
2020.08.07 17:42:29.111452 [ 10689 ] {} <Debug> boss.COMMON_AREA: Loaded data parts (1 items)
2020.08.07 17:42:29.113739 [ 10689 ] {} <Debug> boss.SYS_USER_ACCOUNT: Loading data parts
2020.08.07 17:42:29.125683 [ 10689 ] {} <Debug> boss.SYS_USER_ACCOUNT: Loaded data parts (18 items)
2020.08.07 17:42:29.174251 [ 10668 ] {} <Debug> boss.SYS_CUSTOMER_MANAGEMENT: Loaded data parts (64 items)
2020.08.07 17:42:29.251155 [ 10688 ] {} <Debug> boss.MOBIL_CODE: Loaded data parts (1850 items)
2020.08.07 17:42:29.289094 [ 10687 ] {} <Debug> boss.COLLECTION_DATA: Loaded data parts (84 items)
2020.08.07 17:42:29.877660 [ 10662 ] {} <Information> DatabaseOrdinary (boss): Starting up tables.
2020.08.07 17:42:29.889509 [ 10689 ] {} <Warning> boss.COLLECTION_DATA: Removing temporary directory /var/lib/clickhouse/data/boss/COLLECTION_DATA/tmp_mut_202007_9155786_150814264_21205_172652977/
2020.08.07 17:42:29.897639 [ 10662 ] {} <Information> DatabaseOrdinary (default): Total 2 tables and 0 dictionaries.
2020.08.07 17:42:29.897946 [ 10696 ] {} <Debug> default.SYS_USER_ACCOUNT: Loading data parts
2020.08.07 17:42:29.898037 [ 10696 ] {} <Debug> default.SYS_USER_ACCOUNT: Loaded data parts (0 items)
2020.08.07 17:42:29.898097 [ 10690 ] {} <Debug> default.SYS_CUSTOMER_MANAGEMENT: Loading data parts
2020.08.07 17:42:29.933898 [ 10690 ] {} <Debug> default.SYS_CUSTOMER_MANAGEMENT: Loaded data parts (64 items)
2020.08.07 17:42:29.934103 [ 10662 ] {} <Information> DatabaseOrdinary (default): Starting up tables.
2020.08.07 17:42:29.934341 [ 10662 ] {} <Debug> Application: Loaded metadata.
2020.08.07 17:42:29.934384 [ 10662 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2020.08.07 17:42:29.934428 [ 10662 ] {} <Information> BackgroundSchedulePool: Create BackgroundSchedulePool with 16 threads
2020.08.07 17:42:29.935130 [ 10662 ] {} <Information> Application: Listening for http://0.0.0.0:8123
2020.08.07 17:42:29.935165 [ 10662 ] {} <Information> Application: Listening for connections with native protocol (tcp): 0.0.0.0:9000
2020.08.07 17:42:29.935190 [ 10662 ] {} <Information> Application: Listening for replica communication (interserver): http://0.0.0.0:9009
2020.08.07 17:42:29.935498 [ 10662 ] {} <Information> Application: Available RAM: 15.51 GiB; physical cores: 4; logical cores: 8.
2020.08.07 17:42:29.935511 [ 10662 ] {} <Information> Application: Ready for connections.
2020.08.07 17:42:31.937995 [ 10713 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config.xml'
2020.08.07 17:42:34.215413 [ 10683 ] {} <Debug> DiskLocal: Reserving 2.22 GiB on disk `default`, having unreserved 307.37 GiB.
2020.08.07 17:42:34.460292 [ 10683 ] {} <Debug> boss.COLLECTION_DATA (SelectExecutor): Key condition: unknown
2020.08.07 17:42:34.460342 [ 10683 ] {} <Debug> boss.COLLECTION_DATA (SelectExecutor): MinMax index condition: unknown
2020.08.07 17:42:34.460369 [ 10683 ] {} <Debug> boss.COLLECTION_DATA (SelectExecutor): Selected 1 parts by date, 1 parts by key, 4209 marks to read from 1 ranges
2020.08.07 17:42:34.460427 [ 10683 ] {} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202007_9155786_150814264_21205_172505064, approx. 34480128 rows starting from 0
2020.08.07 17:42:34.460510 [ 10683 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.08.07 17:42:34.466564 [ 10683 ] {} <Trace> Aggregator: Aggregating
2020.08.07 17:42:34.471257 [ 10683 ] {} <Trace> Aggregator: Aggregation method: without_key
2020.08.07 17:42:38.460329 [ 10683 ] {} <Trace> Aggregator: Aggregated. 43325 to 1 rows (from 0.011 MiB) in 3.994 sec. (10848.411 rows/sec., 0.003 MiB/sec.)
2020.08.07 17:42:38.460385 [ 10683 ] {} <Trace> Aggregator: Merging aggregated data
2020.08.07 17:42:38.460429 [ 10683 ] {} <Trace> virtual DB::MergingAndConvertingBlockInputStream::~MergingAndConvertingBlockInputStream(): Waiting for threads to finish
2020.08.07 17:42:38.471143 [ 10683 ] {} <Trace> boss.COLLECTION_DATA (MergerMutator): Mutating part 202007_9155786_150814264_21205_172505064 to mutation version 172652977
2020.08.07 17:42:40.789500 [ 10683 ] {} <Debug> boss.COLLECTION_DATA (SelectExecutor): Key condition: unknown
2020.08.07 17:42:40.789540 [ 10683 ] {} <Debug> boss.COLLECTION_DATA (SelectExecutor): MinMax index condition: unknown
2020.08.07 17:42:40.789555 [ 10683 ] {} <Debug> boss.COLLECTION_DATA (SelectExecutor): Selected 1 parts by date, 1 parts by key, 4209 marks to read from 1 ranges
2020.08.07 17:42:40.789594 [ 10683 ] {} <Trace> MergeTreeSelectProcessor: Reading 1 ranges from part 202007_9155786_150814264_21205_172505064, approx. 34480128 rows starting from 0
2020.08.07 17:42:40.789648 [ 10683 ] {} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2020.08.07 17:43:11.307835 [ 10792 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2020.08.07 17:43:11.307926 [ 10792 ] {} <Information> : Starting ClickHouse 20.3.8.53 with revision 54433
2020.08.07 17:43:11.307966 [ 10792 ] {} <Information> Application: starting up
2020.08.07 17:43:11.311889 [ 10792 ] {} <Information> StatusFile: Status file /var/lib/clickhouse/status already exists - unclean restart. Contents:
PID: 10662
Started at: 2020-08-07 17:42:29
Revision: 54433

2020.08.07 17:43:11.311959 [ 10792 ] {} <Debug> Application: rlimit on number of file descriptors is 500000
2020.08.07 17:43:11.311975 [ 10792 ] {} <Debug> Application: Initializing DateLUT.
2020.08.07 17:43:11.311982 [ 10792 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Shanghai'.
2020.08.07 17:43:11.312010 [ 10792 ] {} <Debug> Application: Setting up /var/lib/clickhouse/tmp/ to store temporary data in it
2020.08.07 17:43:11.312204 [ 10792 ] {} <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'yn-operation-platform' as replica host.
2020.08.07 17:43:11.314698 [ 10792 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
2020.08.07 17:43:11.315152 [ 10792 ] {} <Information> Application: Uncompressed cache size was lowered to 7.76 GiB because the system has low amount of memory
2020.08.07 17:43:11.315334 [ 10792 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
2020.08.07 17:43:11.316402 [ 10792 ] {} <Information> DatabaseOrdinary (system): Total 1 tables and 0 dictionaries.
2020.08.07 17:43:11.321760 [ 10796 ] {} <Information> BackgroundProcessingPool: Create BackgroundProcessingPool with 16 threads
2020.08.07 17:43:11.322964 [ 10796 ] {} <Debug> system.metric_log: Loading data parts
2020.08.07 17:43:11.348110 [ 10796 ] {} <Debug> system.metric_log: Loaded data parts (1 items)
2020.08.07 17:43:11.348294 [ 10792 ] {} <Information> DatabaseOrdinary (system): Starting up tables.
2020.08.07 17:43:11.351350 [ 10792 ] {} <Information> DatabaseOrdinary (boss): Total 6 tables and 0 dictionaries.

**Comment by alexey-milovidov** [comment]
Is there any messages in `dmesg` about clickhouse or OOM?

**Comment by liubaochuan** [comment]
2021.04.10 12:26:41.223092 [ 32034 ] {} <Warning> default.test_table: Removing temporary directory /home/program/data/clickhouse/data/default/test_table/tmp_mut_65a169db8e6913eff27422c5347536e7_187952_200424_392_1539869/
2021.04.10 14:08:00.547652 [ 41154 ] {} <Warning> ocean.cw_facedb_face_index: Removing temporary directory /home/program/data/clickhouse/data/default/test_table/tmp_mut_65a169db8e6913eff27422c5347536e7_187952_200424_392_1539869/
2021.04.10 15:49:07.929274 [ 46997 ] {} <Warning> ocean.cw_facedb_face_index: Removing temporary directory /home/program/data/clickhouse/data/default/test_table/tmp_mut_65a169db8e6913eff27422c5347536e7_187952_200424_392_1539869/
2021.04.10 17:29:11.795369 [ 52442 ] {} <Warning> ocean.cw_facedb_face_index: Removing temporary directory /home/program/data/clickhouse/data/default/test_table/tmp_mut_65a169db8e6913eff27422c5347536e7_187952_200424_392_1539869/

I also have this problem.
when the above log will automatically restart.
clickhouse version: 20.8.7.15-2
