### ISSUE TITLE
Ability to revoke certain rights from admin user

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#13390]
We want to have following configuration with enabled RBAC.
1) One `superuser` from users.xml
2) Second `admin` user without specific rights. It is trivial with partial revokes
3) We want to disallow admin user to change his own rights. Is there a way to make something like
``` sql
GRANT ALTER USER TO `admin` WITH GRANT OPTION ALL EXCEPT `admin`, `superuser`
```
It it possible?

**Comment by vitlibar** [comment]
To prohibit `admin` from changing access rights of anybody use

```
REVOKE GRANT OPTION FOR ALL ON *.* FROM admin
```

**Comment by vitlibar** [comment]
If you want to allow `admin` to change access rights of anyone except `admin` himself, the current implementation of `GRANT/REVOKE` commands doesn't allow to do that.

**Comment by qoega** [comment]
> If you want to allow admin to change access rights of anyone except admin himself, the current implementation of GRANT/REVOKE commands doesn't support that.
Lets convert it to feature request then?

**Comment by vitlibar** [comment]
I think I'll implement the following syntax:

```
GRANT ALTER USER ON *.* TO `admin` WITH GRANT OPTION(ALL EXCEPT `admin`, `superuser`)
```

Without parentheses `GRANT OPTION` will mean `GRANT OPTION(ALL)`, i.e. user will be allowed to grant to anyone.

**Comment by vitlibar** [comment]
I incline to try another approach to this problem. Instead of creating a new nonstandard syntax `WITH GRANT OPTION(ALL EXCEPT admin, superuser)` I think I'll make the `GRANT` command keep information which user gave that permission and then `REVOKE` will remove permissions after checking the current user is the same user. I mean who gave some permission will able to take it away. And if `A` gave some permission to `B` with grant option, and after that `B` gave it to `C`, then both `A` and `B` will able to take the permission from `C`, but `B` cannot take the permission from `A`.

**Comment by vitlibar** [comment]
Implemented via adding of a new optional clause GRANTEES for CREATE/ALTER USER commands:

```
CREATE USER ... GRANTEES {user | role | ANY | NONE} [,...] [EXCEPT {user | role} [,...]]
```

which specifies users or roles which are allowed to receive grants from this user on condition this user has also all required access granted with grant option. By default `GRANTEES ANY` is used which means a user with grant option can grant to anyone.
