### ISSUE TITLE
Self-balancing architecture: Moving parts between shards

### ISSUE THREAD

**Issue by xjewer** [ClickHouse/ClickHouse#13574]
## Issue:

So far ClickHouse as a data store shifts the responsibility of the balancing to an operator to provide inbound data flow in
a balanced manner - that is to say, once data is written to any of shards, it's hard to move it around involving manual interventions 
either tricking read pipeline by building a table with MergeEngine on top and copying partitions around or manually move parts with 
inevitable maintenance windows with partial response. Needless to say, it's cumbersome and exausting.

## Proposal:

The proposal doesn’t cover entire self-balancing architecture, rather suggests an extension of `ALTER TABLE table MOVE PARTITION|PART`
to be able to move parts between shards seamless.

Similar to `MOVING PARTITION|PART to a disk|volume to DISK|VOLUME,` proposed syntax is:

```
ALTER TABLE table_name MOVE PARTITION|PART partition_expr TO SHARD 'shard_id'
```

The process is sketchy explained as follows:
1. ClickHouse won't include in upcoming merges or stops running merges with moving parts
2. Copy data to a designated shard (all live replica) to detached directory
3. When the copy is done, initiate a part attachment on a new node:
    a. mark moving parts on an old node as OLD, during SELECTs return to a root executor all OLD part ids that were processed during query
    b. mark moving parts on a new node as NEW and ATTACH part locally on replicas, during SELECTs return to a root executor all NEW part ids that were processed during a query
    c. remove part from an old node
    d. remove NEW mark from parts on a new node.
During SELECTS against the cluster, root executor (a node that gets initial query from the client) will retry query to an old leaf node, if the result from the cluster has intersections between OLD and NEW part ids,  e.g. using virtual columns:
```
where _part != '202007_7145_7145_0
```

This is a pessimistic scenario when a SELECT hits both parts in old and new nodes during steps 3.b - 3.c. Depending on the data access pattern it's possible to consider a further optimization where OLD node can precompute both results with and without OLD parts.

UPDATE:

IRL @nvartolomei raised a few concerns regarding the concept:
1. Parts don’t necessary have the same names between shards
2. Re-attaching a part changes it’s name by renumbering a block_id suffix.

Both of those can be covered by extending a metadata of a part during movement: 
not only add an OLD/NEW marker, but also uniq identifier, that can be discarded later when the movement is complete.

**Comment by filimonov** [comment]
We discussed that idea some time ago, and hopefully, it will be taken / delivered. But there is a very problematic moment: commit into 3 places (filesystem on source shard, the filesystem on target shard, and zookeeper) which can't be executed safe enough in the distributed system.

So it seems that we need to allow duplicate parts to exists for some time on both shards, and we need to remember the mapping of parts that were moved, and the Distributed table should be aware of that.

**Comment by nvartolomei** [comment]
For the past week I've been experimenting with various approaches for adding "fingerprint" metadata to the parts and moving data between shards.

Orchestrating the whole process is a bit complicated and we reached the conclusion that the best way for now is to add a minimal set of primitives that would allow an operator to perform the whole process and handle the edge cases.

I need some feedback to understand if we are heading in the right direction and should continue or we need to revisit the approach.

---

The required primitives (in addition to de-duplication/retrying at query layer) are:

1. (p1) `ALTER TABLE ... ADD FINGERPRINT [a uuid] FOR PART 'part_name'` (p1_a) (and opposite § `REMOVE FINGERPRINT FOR PART 'part_name'` (p1_b) for revert)
2. (p2) `ALTER TABLE ... ATTACH PART 'part_name'` (already exists)
3. (p3) `ALTER TABLE ... DROP PART 'part_name'` https://github.com/ClickHouse/ClickHouse/pull/14499

Process for moving a part (restating what @xjewer already said but in terms of defined primitives):
1. (s1) the operator would asses first that shards tables are compatible, then will run (p1) on a source shard
   *  for (p1) to succeed the part must exist and there should be NO other commands in the replica queue and table log that:
      * want to add a fingerprint (different from the one already added)
      * there are no pending merges that could result in the part getting removed
      * ... any other conflicts? ie mutations? ...
   *  after this operation succeeds no new merges will be scheduled, basically it becomes "locked" to preserve its identity while movement is in progress
2. (s2). the operator moves physically the part from source shard to `detached/` folder of the destination shard and attaches it using p2 (it is up to the operator to ensure that while this is in progress the table structure remain consistent and no operations like `update on cluster` are run (as they later will result in data reappearing on destination shard))
   * the part should contain the "fingerprint" so that when it is attached it would be reported to the executor for deduplication
3. (s3) the part is removed from source shard using (p3)
4. (s4) fingerprint is removed from the part on the destination shard (p1_b)

---

I've been trying different approaches for implementing (p1). From what I have found the method that makes sense here (and the only one currently in existence) for adding a new piece of metadata to a part is to start a (metadata only) mutation.

The problem with mutations is that they are asynchronous which makes invariant checking a bit complicated and also it makes this simple "metadata only" operation a bit heavy (bunch of file renames).

Mutations cause some other problems (especially concurrent mutations), they change part names (at least for MergeTree engine) which makes the process of identifying which `part_name` to use for movement and later for `DROP PART` a bit tricky. (we could implement a "maintenance lock" on tables which would reject any new mutations but (including ALTERs) and allow running ADD FINGERPRINT only for parts which are at the latest mutation version).

---

Does this approach seems viable (using mutations) and something that could be accepted to master? If not, why and how would you change it? Are there any other possible conflicts beside merges that could interfere with "fingerprints" that must be considered?

@alesapin (who seems to have experience with mutations) @alexey-milovidov please help with early feedback.

**Comment by alesapin** [comment]
As @filimonov sad we had a very similar discussion. I think fingerprints for parts is a good idea, but they should be hidden from the user. Query `ADD FINGERPRINT` seems too low-level. Also, I don't understand how fingerprints will interact with merges. What will be a result of the merge of two parts with different fingerprints? What happens if the merge will be assigned for a moving part after (s2)? Probably we need to stop all merges for parts with fingerprints?

As far as parts are immutable there is no way to add a fingerprint without the part mutation. Also, mutations always affect all parts (at least just create hardlinks for the unchanged part) and it's quite suboptimal to touch all parts for a single fingerprint. Maybe we have to introduce some kind of single part mutations. Mutations are asynchronous, but we already have primitives to wait for them synchronously.

As far as I remember in our discussion we have decided to use some kind of a versioned centralized part Map, which the initiator (Distributed Table) will store in memory. The Map will be placed in ZooKeeper and Distributed tables will fetch this map into memory (probably asynchronously). They will use this information to deduplicate data from shards that have the same parts (parts in moving state). Move operation will update this map when the part is transferred to the new shard. Old shard will remove it's part copy from disk and Map only when there will be no Distributed tables which use the old map state (holds some ephemeral lock in zookeeper?).

But your idea looks better (and more detailed). It doesn't require additional interactions with ZooKeeper.

**Comment by nvartolomei** [comment]
@alesapin take a look at #14860 which attempts to implement it for MergeTree engine.

> Query ADD FINGERPRINT seems too low-level.

In my initial POC these queries weren't present and ClickHouse would have been responsible for everything (a worker), but getting it right is hard. From my last comment:

> Orchestrating the whole process is a bit complicated and we reached the conclusion that the best way for now is to add a minimal set of primitives that would allow an operator to perform the whole process and handle the edge cases.

Even if we would have done the orchestration part having these low level queries is helpful to fix cases where something goes wrong.

> What will be a result of the merge of two parts with different fingerprints?

Merges are not allowed.

https://github.com/ClickHouse/ClickHouse/pull/14860/files#diff-5663dd20a29f27f6b6a30d51e6559939R651-R656

Although this might seem questionable it is perfectly fine when used with care. The plan is to move big parts from old partitions after cluster expansion in order to re-balance data. Think tables with 1y+ retention. These old partitions have close to 0 activity by the time expansion is needed.

> As far as I remember in our discussion we have decided to use some kind of a versioned centralized part Map, which the initiator (Distributed Table) will store in memory. The Map will be placed in ZooKeeper and Distributed tables will fetch this map into memory (probably asynchronously).

I spent too much time thinking about a similar approach, even putting coordination in read path and use a scheme similar to Calvin to achieve performance. This would permit achieving a lot of things, including write transactions across shards and tables (MVs), consistent reads, probably re-sharding. But currently I see no way ClickHouse would get anything like this in near future (and maybe the idea is not workable at all), but we need some flexibility for moving data soon.

The PRs we're proposing are specifically designed to touch as few moving parts as possible, keep things simple for reviewers and for interaction with other parts, not preclude better approaches for re-sharding, and, most importantly, provide low level primitives for users who can't live without them.

**Comment by alesapin** [comment]
As @filimonov sad we had a very similar discussion. I think fingerprints for parts is a good idea, but they should be hidden from the user. Query `ADD FINGERPRINT` seems too low-level. Also, I don't understand how fingerprints will interact with merges. What will be a result of the merge of two parts with different fingerprints? What happens if the merge will be assigned for a moving part after (s2)? Probably we need to stop all merges for parts with fingerprints?

As far as parts are immutable there is no way to add a fingerprint without the part mutation. Also, mutations always affect all parts (at least just create hardlinks for the unchanged part) and it's quite suboptimal to touch all parts for a single fingerprint. Maybe we have to introduce some kind of single part mutations. Mutations are asynchronous, but we already have primitives to wait for them synchronously.

As far as I remember in our discussion we have decided to use some kind of a versioned centralized part Map, which the initiator (Distributed Table) will store in memory. The Map will be placed in ZooKeeper and Distributed tables will fetch this map into memory (probably asynchronously). They will use this information to deduplicate data from shards that have the same parts (parts in moving state). Move operation will update this map when the part is transferred to the new shard. Old shard will remove it's part copy from disk and Map only when there will be no Distributed tables which use the old map state (holds some ephemeral lock in zookeeper?).

But your idea looks better (and more detailed). It doesn't require additional interactions with ZooKeeper.

**Comment by xjewer** [comment]
@alesapin can you elaborate, why the issue is closed with the same comment, that @nvartolomei was trying thoroughly addressing. Seems like we have a bit of misunderstanding in the proposed implementation.

Unarguably, parts mutations is not something convenient to propagate fingerprints, but it does handle stopping merges on the part (see #14860).

as stated here https://github.com/ClickHouse/ClickHouse/issues/13574#issuecomment-694175585
introducing cross shard coordination isn't straightforward, hence the first step forward is to give all necessary primitives to move data around.

Adding new primitives:

* ADD/REMOVE FINGERPRINT #14860
* DROP PART #14499 
* Distributed query deduplication #14885

Existing:
* FREEZE part
* ATTACH part
* FETCH partition, or copy data whatever way is suitable

Specifically about part *fingerprint* - is something query deduplication is rely on: no extra ZooKeeper sync during the part movement. Once part is attached on the destination shard, root executor can infer from the fingerprints duplicated data if any in processed query and retry it against the leaf node explicitly asking to exclude those parts.

----

>As far as I remember in our discussion we have decided to use some kind of a versioned centralized part Map, which the initiator (Distributed Table) will store in memory. The Map will be placed in ZooKeeper and Distributed tables will fetch this map into memory (probably asynchronously). They will use this information to deduplicate data from shards that have the same parts (parts in moving state). 

Drawback in the aforementioned approach is to bound to ZooKeeper in a read path, if not, there will be no consistency if a root executor lost zk connection but still can participating in read queries.

>Also, mutations always affect all parts (at least just create hardlinks for the unchanged part) and it's quite suboptimal to touch all parts for a single fingerprint. Maybe we have to introduce some kind of single part mutations. Mutations are asynchronous, but we already have primitives to wait for them synchronously.

not sure I follow why all the parts have to be mutated on adding fingerprint to one?

**Comment by alesapin** [comment]
Oh sorry, I didn't notice when I've closed this issue.

**Comment by abyss7** [comment]
Do you take into account all kinds of skip-shard optimizations?

The whole idea (about manual parts' movement) sounds like a design-flaw since it's assumed that the sharding key should uniformly distributed incoming data between shards, and there should be no need to manually move some random parts.

In case of a shard addition/removal isn't it better to perform global resharding with help of consistent-hashing or any other helpful mechanism?

**Comment by xjewer** [comment]
>Do you take into account all kinds of skip-shard optimizations?

can you elaborate how it can affect the flow, I might missing something.

>The whole idea (about manual parts' movement) sounds like a design-flaw since it's assumed that the sharding key should uniformly distributed incoming data between shards, and there should be no need to manually move some random parts.

good question. there are a few moments here that need to be highlighted:

* writing data can be done directly to MergeTree table, bypassing distributed on top. that's just a note and I assume sharding can be done on application side during the insertion.
* shards on the cluster can be heterogenous, that can affect expanding or read optimizations.

one potential example, let's say we have

cluster with 5 shards NVME + 5 bigger shards on HDD and call them HOT/COLD respectively.

writes firstly go to HOT storage, participate in HOT reads and merges and once they become `old`, move them to COLD shards.

Proposed solution with movement and query deduplication won't affect regular query execution until movement is triggered. You can call it MANUAL but once movement is implemented (merged) third party system can trigger part movements when a part passed some threshold: either time or access pattern (TBD)

**Comment by mdianjun** [comment]
@xjewer I have a question：
Theoretically, all parts of a partition will be merged into one, and maybe it will be very large. Then "MOVE PART" is not appropriate for that large part, since we might expect some of the data (not all data) in the partition to be moved to the new shard.

**Comment by xjewer** [comment]
>Theoretically, all parts of a partition will be merged into one, and maybe it will be very large. Then "MOVE PART" is not appropriate for that large part, since we might expect some of the data (not all data) in the partition to be moved to the new shard.

what is the question?

there is a setting that can configure max part size https://clickhouse.tech/docs/en/operations/settings/merge-tree-settings/#max-bytes-to-merge-at-max-space-in-pool.

default is 150GiB (which is peanuts compare to modern hard drives)

**Comment by alexey-milovidov** [comment]
There are multiple issues with the implementation, see https://github.com/ClickHouse/ClickHouse/issues/49574, https://github.com/ClickHouse/ClickHouse/issues/40814, https://github.com/ClickHouse/ClickHouse/issues/40189, https://github.com/ClickHouse/ClickHouse/issues/40188

**Comment by Slach** [comment]
so sad to view, when important architectural changes that significantly improve the operation of the clickhouse are simply closed as "wontfix"

**Comment by alexey-milovidov** [comment]
The test for this feature was flaky. But if you can improve the test, you can resubmit it.
