### ISSUE TITLE
Expired parts which should have been automatically removed by TTL settings are still present

### ISSUE THREAD

**Issue by macEar** [ClickHouse/ClickHouse#14261]
**Describe the bug**

Old parts which should have been automatically removed by TTL settings are still present.

**`CREATE TABLE` statement**

```sql
CREATE TABLE logs.syslog
(
    `source` LowCardinality(String),
    `severity` UInt8,
    `facility` UInt8,
    `timestamp` DateTime,
    `timestampMsg` DateTime,
    `hostname` LowCardinality(String),
    `fromhostIp` IPv4,
    `tag` LowCardinality(String),
    `message` String,
    `sdata` String,
    `appname` LowCardinality(String),
    `procid` String,
    `msgid` LowCardinality(String)
)
ENGINE = MergeTree()
PARTITION BY (source, toYYYYMMDD(timestamp))
ORDER BY (source, timestamp)
TTL timestamp + toIntervalMonth(6)
SETTINGS index_granularity = 8192,
    ttl_only_drop_parts = 1,
    merge_with_ttl_timeout = 86400
```

Check how many old parts exist:

```
SELECT count(*)
FROM `system`.parts p
WHERE database = 'logs'
    AND table = 'syslog'
    AND active
    AND delete_ttl_info_max < now() - 60*60*24*7
    AND rows != 0
```

Result:

| count() |
|---------|
| 217 |

* Which ClickHouse server version to use

Docker image: `yandex/clickhouse-server:20.5.3.27`

**Expected behavior**

Expired parts are removed automatically with correspondence to TTL settings.

**Additional context**

Manually removing is possible but why make things difficult if automatic removing is supposed to work, as I can understand

**Comment by alexey-milovidov** [comment]
The data in parts is cleared according to the TTL logic but parts theirself are not removed even if they are empty.
This is the current behaviour.

**Comment by alexey-milovidov** [comment]
See #13252

**Comment by macEar** [comment]
Could you please explain to me why `delete_ttl_info_max` is in past but those parts (expired ones) include more than 0 rows? If there were only parts with 0 rows than I wouldn't question you.

**Comment by alexey-milovidov** [comment]
Let's ask @CurtizJ

**Comment by CurtizJ** [comment]
One possible issue is that there are a lot of merges with TTL and it takes a lot off time to execute them due to timeout. Since you have `ttl_only_drop_parts = 1`, you can lower `merge_with_ttl_timeout` without any performance drawbacks. 
Also you can run manually query `ALTER TABLE <table_name> MATERIALIZE TTL`.

Another possible issue is the case, when you added TTL by `ALTER` query in version older than 20.5. TTL might didn't apply for old data. To check it look at `delete_ttl_info_max`. If it is 0 in parts, that should be cleared by TTL it is not applied and  `ALTER TABLE <table_name> MATERIALIZE TTL`  query is requiered.

**Comment by macEar** [comment]
@CurtizJ thanks, it helps
