### ISSUE TITLE
Centos/8: sysV vs systemd mess. Service status is 'stopped' although it is running

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#14298]
**Description**
Whenever I run `sudo service clickhouse-server status` I get `clickhouse-server service is stopped`, although the server is actually running.

I can verify that it is running with the following:

```
$ ps -ef | grep clickhouse
clickho+    2646       1  0 20:00 ?        00:00:01 clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml
```

or

```
$ sudo lsof -i:9000
COMMAND    PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
clickhous 2646 clickhouse   54u  IPv6  60885      0t0  TCP *:cslistener (LISTEN)
```

or simpliy, I can open `clickhouse-client` with no problems.

It is not just about the displayed status; I cannot stop the server using `sudo service clickhouse-server stop`, I must kill the process manually. I cannot restart the server using `sudo service clickhouse-server restart` because the other process is allocating the resources.

**Environment**
I am using a fresh image of CentOS 8.2 with ClickHouse 20.7.2.30 installed.

Here is the configuration that I am using:

```
<yandex>
    <path>/mnt/clickhouse/</path>
    <tmp_path>/mnt/clickhouse/tmp/</tmp_path>
    <user_files_path>/mnt/clickhouse/user_files/</user_files_path>
    <access_control_path>/mnt/clickhouse/access/</access_control_path>
    <format_schema_path>/mnt/clickhouse/format_schemas/</format_schema_path>

    <listen_host>::</listen_host>

    <compression>
        <case>
            <min_part_size>10000000000</min_part_size>
            <min_part_size_ratio>0.01</min_part_size_ratio>
            <method>lz4</method>
        </case>
    </compression>

    <remote_servers>
        <clickhouse_cluster>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>clickhouse-02</host>
                    <port>9000</port>
                </replica>
            </shard>
        </clickhouse_cluster>
    </remote_servers>

    <zookeeper>
        <node index="1">
            <host>zookeeper-01</host>
            <port>2181</port>
        </node>
    </zookeeper>
</yandex>

```

**Comment by den-crane** [comment]
Please show an output of 

`systemctl status clickhouse-server`

`cat /etc/cron.d/clickhouse-server`

**Comment by OmarBazaraa** [comment]
I installed the latest version of the official pre-compiled rpm packages for CentOS.

```
$ systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-08-31 20:29:50 UTC; 27s ago
  Process: 3390 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid (code=exited, status=70)
 Main PID: 3390 (code=exited, status=70)

Aug 31 20:29:50 clickhouse-01 systemd[1]: clickhouse-server.service: Main process exited, code=exited, status=70/SOFTWARE
Aug 31 20:29:50 clickhouse-01 systemd[1]: clickhouse-server.service: Failed with result 'exit-code'.
```

```
$ cat /etc/cron.d/clickhouse-server
#*/10 * * * * root (which service > /dev/null 2>&1 && (service clickhouse-server condstart ||:)) || /etc/init.d/clickhouse-server condstart > /dev/null 2>&1
```

**Comment by den-crane** [comment]
try `/etc/init.d/clickhouse-server status `, `/etc/init.d/clickhouse-server stop`

**Comment by OmarBazaraa** [comment]
Still giving me `stopped` status.

```
$ /etc/init.d/clickhouse-server status
clickhouse-server service is stopped
```

**Comment by filimonov** [comment]
Please

1) check the pid of the running clickhouse - server process = pid reporter by service status
2) show the content of /run/clickhouse-server/clickhouse-server.pid
3) show the content of /mnt/clickhouse/status

**Comment by filimonov** [comment]
Also it looks like clickhouse was started by init.d (sysv script in the /etc/init.d/clickhouse-server) and you are checking the status of systemd service.

May be it is inaccurate update - did you saw that message during updating the package?

https://github.com/ClickHouse/ClickHouse/blob/9791be4effc3cb74d0e7460a13505b187f1e3f90/debian/clickhouse-server.postinst#L26-L29

**Comment by OmarBazaraa** [comment]
I didn't update ClickHouse, I installed the latest version 20.7.2.30 directly.

1. The PID is 2646:

    ```
    $ sudo lsof -i:9000

    COMMAND    PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
    clickhous 2646 clickhouse   54u  IPv6  60885      0t0  TCP *:cslistener (LISTEN)
    ```

2. The process file is not found:
    ```
    $ sudo cat /run/clickhouse-server/clickhouse-server.pid

    cat: /run/clickhouse-server/clickhouse-server.pid: No such file or directory
    ```

3. The status file content:
    ```
    $ sudo cat /mnt/clickhouse/status

    PID: 2646
    Started at: 2020-08-31 20:00:28
    Revision: 54437
    ````

**Comment by OmarBazaraa** [comment]
By the way, this issue happens also with the default configurations when I just try to restart the server.

**Comment by filimonov** [comment]
Tried on VM with centos/8 without success. 

It is possible if you will start clickhouse not through `service` / `systemctl` command but directly via SysV script, i.e.
```
sudo /etc/init.d/clickhouse-server start
```

But in that case, the simple restart should solve the issue, and `sudo /etc/init.d/clickhouse-server status` should show proper status. 

Please run the following:
```
sudo /etc/init.d/clickhouse-server start
sudo service clickhouse-server status
sudo systemctl status clickhouse-server

sudo chkconfig --list
sudo systemctl list-unit-files

sudo chkconfig clickhouse-server
sudo systemctl is-enabled clickhouse-server

sudo /etc/init.d/clickhouse-server stop
sudo kill $(pidof clickhouse-server)
sudo kill $(pidof clickhouse-server)

sudo systemctl start clickhouse-server
```

**Comment by filimonov** [comment]
Please share the output & try to restart the server afterward.

**Comment by OmarBazaraa** [comment]
Here is the output that you asked for:


```
$ sudo /etc/init.d/clickhouse-server status
clickhouse-server service is stopped

$ sudo service clickhouse-server status
clickhouse-server service is stopped

$ sudo systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-09-01 14:36:25 UTC; 2s ago
  Process: 1866 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid (code=exited, status=70)
 Main PID: 1866 (code=exited, status=70)

Sep 01 14:36:25 clickhouse-02 systemd[1]: clickhouse-server.service: Main process exited, code=exited, status=70/SOFTWARE
Sep 01 14:36:25 clickhouse-02 systemd[1]: clickhouse-server.service: Failed with result 'exit-code'.

$ sudo chkconfig --list

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

$ sudo systemctl list-unit-files | grep clickhouse
clickhouse-server.service                  enabled

$ sudo chkconfig clickhouse-server
Note: Forwarding request to 'systemctl is-enabled clickhouse-server.service'.
enabled

$ sudo systemctl is-enabled clickhouse-server
enabled

$ sudo /etc/init.d/clickhouse-server stop
$ sudo kill $(pidof clickhouse-server)
$ sudo kill -9 $(pidof clickhouse-server)
kill: not enough arguments

$ sudo systemctl start clickhouse-server

$ sudo service clickhouse-server status
clickhouse-server service is running

$ sudo /etc/init.d/clickhouse-server status
clickhouse-server service is running

$ sudo systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-09-01 14:37:56 UTC; 2s ago
 Main PID: 1938 (clickhouse-serv)
    Tasks: 62 (limit: 50048)
   Memory: 104.3M
   CGroup: /system.slice/clickhouse-server.service
           └─1938 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid

Sep 01 14:37:56 clickhouse-02 clickhouse-server[1938]: Include not found: clickhouse_compression
Sep 01 14:37:56 clickhouse-02 clickhouse-server[1938]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Sep 01 14:37:56 clickhouse-02 clickhouse-server[1938]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Sep 01 14:37:56 clickhouse-02 clickhouse-server[1938]: Processing configuration file '/etc/clickhouse-server/users.xml'.
Sep 01 14:37:56 clickhouse-02 clickhouse-server[1938]: Include not found: networks
Sep 01 14:37:56 clickhouse-02 clickhouse-server[1938]: Saved preprocessed configuration to '/var/lib/clickhouse//preprocessed_configs/users.xml'.
Sep 01 14:37:58 clickhouse-02 clickhouse-server[1938]: Processing configuration file '/etc/clickhouse-server/config.xml'.
Sep 01 14:37:58 clickhouse-02 clickhouse-server[1938]: Include not found: clickhouse_remote_servers
Sep 01 14:37:58 clickhouse-02 clickhouse-server[1938]: Include not found: clickhouse_compression
Sep 01 14:37:58 clickhouse-02 clickhouse-server[1938]: Saved preprocessed configuration to '/var/lib/clickhouse//preprocessed_configs/config.xml'.
```

But restarting the server one or more time using `sudo service clickhouse restart` produces the same issue again.

**Comment by OmarBazaraa** [comment]
It seems that `sudo service clickhouse restart` while `sudo systemctl restart clickhouse-server` does not.

**Comment by filimonov** [comment]
systemd vs sysV. 

Centos 8 provides is systemd based, but it also has support layer for sysV. 

So do clickhouse - it provides both systemd service file and sysV init script. 

Because of that when you use `systemctl` - it uses systemd service, when you use `service` it uses init.d script. 

And it seem like it messes up when you try to use one after another. systemctl using fallback to init.d and vice versa. 

For now - try using systemctl always, and it should work. 

(we need to figure out how to package sysV init sctipt to avoid that mess).

**Comment by filimonov** [comment]
https://gist.github.com/filimonov/49a8333dabb9882cbeb095abd8829235

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/13162#discussion_r463580125

**Comment by Awezome** [comment]
I think /etc/cron.d/clickhouse-server also needs to be upgraded for systemctl . I used systemctl to start the server and still turned on the cron.d then got pid conflict because of the different pid .

**Comment by mastertheknife** [comment]
If it helps, i recently decided to share the RPMs i created for use at my workplace.
We're a 95% CentOS company, and i didn't like the deb->rpm approach, i preferred native RPMs, so i made the effort of getting it done. I saw that @filimonov started working on it here: https://github.com/ClickHouse/ClickHouse/pull/7120
I started with that as a base and ended up pretty much rewriting it.
You can find it here, but be warned that these use ~14 non-clickhouse-modified libraries from the OS instead of bundled (to reduce size and improve compatibility with ppc64le) so it may behave differently, although for now we haven't had any issue:
https://github.com/mastertheknife/clickhouse-rpms

I hope the ClickHouse team will adapt this spec file to the main project, and i am willing to help with RHEL8\CentOS8 packaging if needed. Currently i am working on patches and builds for ppc64le.

**Comment by filimonov** [comment]
> You can find it here

I see only readme there. Can you commit spec file somewhere? It's quite silly to unpack srpm for that.

**Comment by filimonov** [comment]
Great effort! I think that it worth comminting (at least some, or maybe most of) cmake patches to clickhouse main repo. 

About external libs - for things like openldap or gsasl it's almost safe. With openssl it's more risky (should work,  but clickhouse now switched to boringssl and for ex. aes_encrypt functions work much slower in openssl).

**Comment by mastertheknife** [comment]
> Great effort! I think that it worth comminting (at least some, or maybe most of) cmake patches to clickhouse main repo.
Thank you!

I have created pull requests for all ppc64le patches except two, which i am not sure how they should be handled.
@alexey-milovidov also for you. These i'm not sure how to handle, because they involve submodules and there few ways to fix these, so if i'll possible i'll leave it for you to decide on the proper approach and for fixing this.
1. rocksdb on ppc64le with Clang requires ppc-asm.h, but that is only available on GCC. This issue also exists upstream:
https://github.com/facebook/rocksdb/issues/7691
I fixed it by bundling GCC 10's ppc-asm.h, but there may be licensing issues if done in source.
https://build.opensuse.org/package/view_file/home:mastertheknife:clickhouse-lts/ClickHouse/0029-ppc64le-rocksdb_clang_fix_compile.patch?expand=1
Upstream fixed it similarly:
 https://github.com/facebook/rocksdb/commit/b937be377901afa32357b60eebbee80f14087180
 2. sentry-native on ppc64le. I fixed it like this:
 https://build.opensuse.org/package/view_file/home:mastertheknife:clickhouse-lts/ClickHouse/0031-ppc64le-sentry_fix_compile.patch?expand=1
 And today pushed this fix upstream to sentry-native:
 https://github.com/getsentry/sentry-native/pull/505
 Perhaps update ClickHouse's version from upstream, now or in the next upstream release. Or, apply this in ClickHouse's version.

Not yet pushed to ClickHouse: Enable external openldap. ClickHouse's version is pretty much stock, but slightly outdated. We can use the OS one here to reduce compile time and binary size.

Also, i build without libunwind on aarch64 and ppc64le.
On aarch64, ClickHouse's version is broken: https://github.com/ClickHouse/ClickHouse/issues/20221#issuecomment-802203224
I haven't tested with ppc64le and decided to skip it for now, to avoid nasty suprises.

> About external libs - for things like openldap or gsasl it's almost safe. With openssl it's more risky (should work, but clickhouse now switched to boringssl and for ex. aes_encrypt functions work much slower in openssl).

Interesting about OpenSSL. I remember from OpenVPN that usually it can use hardware acceleration for AES when available, but perhaps its implementation is still slower than BoringSSL's.

> For compression libraries - the version is very important (not sure how old are they in centos 8).

They are typically from ~2019, the RHEL8\CentOS8 release date.

Thank you! If possible please continue this effort, modify the spec file accordingly and implement official builds (as you started)
P.S, the most time-consuming issue on every release, is to update the list of bundled packages. I am really doing this by hand, perhaps this can be automated, or the list of bundled packages removed from the official RPMs.

**Comment by filimonov** [comment]
> Thank you! If possible please continue this effort, modify the spec file accordingly and implement official builds (as you started)

Actually we want to have only single option for official build for all distributions (it depends only on old version of glibc). Packaging can be improved, but binary should be the same as in ubuntu. 

But having  working srpm is advantage. It can be pushed to different build systems,

**Comment by filimonov** [comment]
https://presentations.clickhouse.tech/cpp_russia_2020/index.html

**Comment by mastertheknife** [comment]
> https://presentations.clickhouse.tech/cpp_russia_2020/index.html

Interesting read :-)
Thank god for Google translate. I know how to read russian, but i don't know too much about the language itself, stopped learning too early.

> Actually we want to have only single option for official build for all distributions (it depends only on old version of glibc). Packaging can be improved, but binary should be the same as in ubuntu.

Support-wise that makes sense.
And yes, i agree and understand. The official one targets any deb & rpm distro, pretty much dependency free, at the cost of size, of course.

But when targeting specific new-enough distros, e.g. RHEL8, which maintains ABI compatibility for its entire lifetime (10 years), using external libraries is generally possible. e.g. libicu will always have ABI version 60. The benefit is smaller binaries and also faster building.

I am glad that ClickHouse kept the ability to use external libraries possible. Maybe it needs a few touches here and there, e.g. allow external openldap, fix external finding of libzlib when its called libz (Fedora\RHEL\CentOS), etc, but overall its already very good and makes distro packaging fairly easy.

**Comment by mastertheknife** [comment]
> https://presentations.clickhouse.tech/cpp_russia_2020/index.html

P.S
I spotted this yesterday, i can correlate with some of the things mentioned in this article:
https://blogs.gentoo.org/mgorny/2021/02/19/the-modern-packagers-security-nightmare/
Especially the ClickHouse-Extras/* repositories that aren't forked from upstream, but have an initial commit instead. These are very inconvenient to compare to upstream. 
And in general, the effort should be to fix upstream when possible, for a better open source eco system :-)

**Comment by alexey-milovidov** [comment]
It's not always possible to fix the upstream. Sometimes they just ignore patches.
Examples: 

https://bugs.llvm.org/show_bug.cgi?id=48186

https://issues.apache.org/jira/browse/AVRO-2717?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=17314187#comment-17314187
(they don't understand what UBSan is and I forgot my JIRA password that I created only to submit this patch)

**Comment by mastertheknife** [comment]
Yeah of course, but at least you tried :-)

The distro packagers aren't perfect either. At work we use MariaDB 10.3 from CentOS8 for our OLTP billing system. RHEL rebased from 10.3.17 to 10.3.27 due to security bugs, but 10.3.27 has two nasty bugs, e.g. mysqld crashes during loading of big writes (e.g. loading a dump). I asked RHEL to rebase to 10.3.28 (bugs are fixed there), but they ignored it. Eventually i took their srpm, rebased it to 10.3.28, built and deployed in all servers.

So yes, sometimes its just inevitable. But if possible, it should be a fork instead of initial commit, making it possible to rebase/merge from upstream fairly easy.

Another issue with packaging, is the SSE4.2 code. Its just built into the code with ifdefs like __SSE4_2__.
When packaging for a distro, x86_64 means just SSE2 is available (mandatory on x86_64) and that we have to leave out SSE4.2 if its not runtime activated. With ARM its easier, because Neon is mandatory on AArch64.
When i wrote all the SIMD code for ZoneMinder project, i solved this by making the program run asm cpuid on startup, and then setup the function pointers. I had multiple versions for each function: standard(unrolled), SSE2 , SSSE3, AArch32 and AArch64. For example here:
https://github.com/ZoneMinder/zoneminder/pull/1881

I hope when time allows, i'll add Neon code for ClickHouse and hopefully split the SSE4.2 code to be runtime-activated.
