### ISSUE TITLE
How to Run non-gtest unit test in ClickHouse?

### ISSUE THREAD

**Issue by AlexanderChiuluvB** [ClickHouse/ClickHouse#14437]
Hi I'm new to ClickHouse and new to C++
Let's say I want to run the main function in Processors/tests/processors_test.cpp
And I notice that there is a CMakeLists.txt in the tests directory.

So I run
```
cmake
make
```

but here comes the error:
```
fatal error: Columns/ColumnsNumber.h: No such file or directory
 #include <Columns/ColumnsNumber.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

So my question is how to build the unit test code ?

**Comment by nikitamikhaylov** [comment]
You can build the whole ClickHouse, go to your build directory, then src/processors/tests and there will be a binary. 

But building the whole ClickHouse is very expensive (on CPU and memory) operation. There have to be another way to do this. I will check and answer.

**Comment by alexey-milovidov** [comment]
You can build a single target, example:

`ninja hash_map_string_3`
or
`make hash_map_string_3` (if you use make)

**Comment by wangzhen11aaa** [comment]
Hi, every one.
➜  tests git:(comment_code) ✗ make merge_selector 
CMake Error: Error processing file: /Users/wangzhen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake
make[1]: *** [cmake_check_build_system] Error 1
make: *** [src/Storages/tests/CMakeFiles/merge_selector.dir/rule] Error 2
➜  tests git:(comment_code) ✗ tail -n 10 Makefile 
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
        cd /Users/wangzhen/ClionProjects/ClickHouse && $(CMAKE_COMMAND) -P /Users/wangzhen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake
        cd /Users/wangzhen/ClionProjects/ClickHouse && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system


➜  tests git:(comment_code) ✗ ls /Users/wangzhen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake
ls: /Users/wangzhen/ClionProjects/ClickHouse/CMakeFiles/VerifyGlobs.cmake: No such file or directory

I did not have this file.
