### ISSUE TITLE
Aliases hiding column names

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#14534]
Quite often people accidentally redefine the column by alias, which lead to full scan, because WHERE conditions use aliases instead of real columns (unexpectedly)

```sql
create table alias_hide_real_columns (d Date, x UInt64) Engine=MergeTree partition by d order by x;
insert into alias_hide_real_columns select toDate('2001-01-01'), number from numbers(8192);
insert into alias_hide_real_columns select toDate('2002-02-02'), number+8192 from numbers(8192);
insert into alias_hide_real_columns select toDate('2003-03-03'), number+8192+8192 from numbers(8192);

set max_rows_to_read = 8192;

-- works ok, read needed partitions / ranges only
select d from alias_hide_real_columns where d='2001-01-01'; 
select x from alias_hide_real_columns where x < 1000;

-- WHERE conditions are the same, but query ends up with a full scan
select d + INTERVAL 1 DAY as d from alias_hide_real_columns where d='2001-01-01'; 
select x/10000 as x from alias_hide_real_columns where x < 1000;
```

Maybe we can improve UX by helping users to avoid such accidents. For example we can introduce a setting like redefining_columns = 'allowed / forbidden / safe'

allowed = like now. 
forbidden = exception 
safe = rewrite a query in a following manner:

```
select func(a) as a from table where a = ... 
-- becomes 
select rand_alias_XYZ as a from (select func(a) as rand_alias_XYZ from table where a = ... );
```

Maybe there are some better options possible?

**Comment by filimonov** [comment]
#14739

**Comment by andrea-s** [comment]
My two cents: in an analytics setting, it is *extremely* useful to be able to redefine a column on the fly - as it allows to build cleaning logic in place  without altering the overarching data model.

Example (oversimplified):
1) customer is consuming the column "country" as part of their analysis
2) customer complains that data is somewhat dirty in the column "country" (e.g. RU, Russia, russia, Russian Federation)
3) developer redefines country on the fly with a case statement ("else country") and moves on with his life

This is an extremely useful pattern - I expect that changing this behavior today would also break a lot of applications (I assume that's why we need a flag :-)).

As I noted in #14739 , it feels to me that the fact that the *order* of such clauses matter, and alters the query result, is the real unexpected behavior.

**Comment by alexey-milovidov** [comment]
Duplicate #9715.
