### ISSUE TITLE
Restoring MergeTree table with s3 storage on another server

### ISSUE THREAD

**Issue by macEar** [ClickHouse/ClickHouse#14690]
### Clickhouse version

Docker image: yandex/clickhouse-server:20.5.3.27 (standalone)

### Question

There is a MergeTree table with s3 storage specified by a policy. Is there any way to restore this table on another clickhouse server in case the main clickhouse server is down. As I got it, there is a local metadata file which stores information about s3 objects. As MergeTree engine is used, merges are constantly processed, and the metadata file is constantly being re-written as well. That's how I understand how it works. Therefore to restore this table on another server we do need to have this metadata file, right? What if we have an old metadata file? Is it still possible to restore the table? Or the only way to restore is to download the partitions and attach them from detached dir?

**Comment by Jokser** [comment]
Hello,
Such problems can be resolved using ReplicatedMergeTree, but there is no deduplication on S3 side, each part for each replica is stored to S3 separately. Functionally ReplicatedMergeTree works well with S3 storage, but not optimally.
To resolve the deduplication problem we need to have a shared metadata engine. We have plans to do that thing.
Also, there is no inner mechanism to restore metadata from the data in S3. 
As one of the solution I propose just copy metadata files from an old server to a new server with a configured storage policy and created a table with the same structure. It should work. Rewriting metadata files shouldn't be a problem, because any insert, merge, or mutation first written to a temporary directory and only then is renamed and attached to MergeTree (atomicity).
