### ISSUE TITLE
How to build clickhouse-client only?

### ISSUE THREAD

**Issue by kekekedeng** [ClickHouse/ClickHouse#14691]
I want to build clickhouse-client only and try `ninja -j 16 clickhouse-client`, but got a symbol link:
![image](https://user-images.githubusercontent.com/5371877/92717003-27661e00-f392-11ea-91d3-4ec06151001c.png)
And my goal is to get a smaller client tool.

clickhouse version 19.16

**Comment by den-crane** [comment]
Yes, clickhouse-client is the same binary and it's very fat application and shares a huge piece of code with clickhouse-server. 
clickhouse-client parses SQL, understands formats (including everything protobuf/parquet), parses input files (in parallel), formats output. Basically it's doing a huge part of work instead of clickhouse-server. And clickhouse-server able to do the same.

There are some idea to make another lightweight client but it's a lot of work and this project is in a backlog.

**Comment by kekekedeng** [comment]
Get it, tks a lot.
