### ISSUE TITLE
Using _part and _partition_id inside MATERIALIZED VIEW

### ISSUE THREAD

**Issue by sokolov-alexey** [ClickHouse/ClickHouse#14802]
Hi

I want to optimize my query by filtering partition name in WHERE clause like this:
```sql
select
	*
from
	test1
where
	_partition_id = '20200914'
````

It works well for me, but when I try to insert it into `CREATE MATERIALIZED VIEW TO` statement I get error:
> Not found column _partition_id in block.

Further tests made me think `_part` and `partition_id` fields are not visible in MV neither in WHERE clause nor in SELECT.
Code example:
```sql
drop table if exists test1;
create table test1
(
	name String
	, loaded datetime materialized now()
)
ENGINE = MergeTree()
partition by toYYYYMMDD(loaded)
order by name
;

drop table if exists test2;
create table test2
(
	name String
	, value UInt8
)
ENGINE = MergeTree()
order by name
;

drop table if exists test_trigger;
create materialized view test_trigger to test2
(
	name String
	, value UInt8
	, partition_id String
)
as
(
	select
		name as name
		, 1 as value
		, _partition_id as partition_id
	from
		test1
)
;

insert into test1 values('aaa'); -- this will occur the error
```
ClickHouse 20.5.3.27

Is it an expected and correct behavior of ClickHouse or am I doing something wrong?

**Comment by den-crane** [comment]
>_partition_id = '20200914'

1. It's huge mistake overall. CH does not guarantee that partition pruning will work against _partition_id column in the future.

use `toYYYYMMDD(loaded) = 20200914`
or better `loaded  >= '2020-09-14 00:00:00' and loaded < '2020-09-15 00:00:00'`


2. _partition_id is a virtual column in the table `test1`. MV select works over **inserted buffer** (rows from insert command). 
MV never reads real `test1` table.

instead of  `_partition_id as partition_id`
you should use `toYYYYMMDD(loaded) as partition_id`
