### ISSUE TITLE
RBAC Materialized Views - User is required additional privileges to INSERT into the source table.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#14810]
**Describe the bug**
When a materialized view is created using a table as a source table, in order to insert on that table, the user is required INSERT and SELECT privilege on the source table, and INSERT privilege on the target table.

**How to reproduce**
* ClickHouse server version 20.9.1 revision 54439.
* `CREATE TABLE` statements for all tables involved
```
clicktest :) create materialized view mat1 to target0 as select * from table0

CREATE MATERIALIZED VIEW mat1 TO target0 AS
SELECT *
FROM table0

Ok.

0 rows in set. Elapsed: 0.009 sec.
```

After granting INSERT on table0
```
#clickhouse-client -u user0
ClickHouse client version 20.9.1.4571 (official build).
Connecting to localhost:9000 as user user0.
Connected to ClickHouse server version 20.9.1 revision 54439.

clicktest :) insert into table0(d) Values ('01-14-2020')

INSERT INTO table0 (d) VALUES

Received exception from server (version 20.9.1):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: user0: Not enough privileges. To execute this query it's necessary to have the grant SELECT(d, a, b, x, y) ON default.table0.
```
And after granting SELECT on table0
```
clicktest :) insert into table0(d) Values ('01-14-2020')

INSERT INTO table0 (d) VALUES

Received exception from server (version 20.9.1):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: user0: Not enough privileges. To execute this query it's necessary to have the grant INSERT(d) ON default.target0.

0 rows in set. Elapsed: 0.008 sec.
```
**Expected behavior**
Only INSERT is required.

**Comment by alexey-milovidov** [comment]
@MyroTk I see nothing wrong in this behaviour.
@vitlibar Please clarify.

**Comment by vitlibar** [comment]
Inserting into the source table of a material view causes automatically inserting into the materialized view's target table.
Both operations are executing in the same context, that's why you should have the INSERT privilege on both the source table and the target table to make the inserting into the source table.

I think we should fix that, because the user executing an INSERT into the source table must be able to do that without even knowing about the existence of the target table. It looks more convenient if ClickHouse would check the INSERT privilege on the target table when the materialized view is created, not when someone's trying to insert into the source table.

**Comment by alexey-milovidov** [comment]
Duplicate #27570
