### ISSUE TITLE
Table system.query_log does not exist for few systems

### ISSUE THREAD

**Issue by John-belt** [ClickHouse/ClickHouse#15161]
Hi,
We are using clickhouse on our production servers. I have noticed that query_log table sometimes exist on some server and on some it does not exist.
Like I am running clickhouse on two servers with same default configs, no changes except for clickhouse version:
1)Clickhouse version 20..6.3 (here the table exists) 
2)Clickhouse version 20..4.6 (here the table does not exist)
Question: 
1) does query_log is enabled by default in latest version??
2) Does it depend on disk space also?? i mean the table will grow over time and does it get deleted afterwards or something like that?? When does the table flushes??

**Comment by alexey-milovidov** [comment]
It is enabled by default for all queries since version 20.5.
That's consistent with your report :)

> Does it depend on disk space also?? i mean the table will grow over time and does it get deleted afterwards or something like that?? 

No, there is no cleanup, it will grow indefinitely.
Usually it is quite small nevertheless and there is no issue.
Otherwise you can manually `TRUNCATE`, `ALTER ... DROP PARTITION` or `ALTER MODIFY TTL` to set automatic cleaning.

> When does the table flushes??

The data is flushed from in-memory buffer to the table every 7 seconds by default.

**Comment by John-belt** [comment]
Yup that makes sense.
