### ISSUE TITLE
Alias to NESTED field results in missing column error

### ISSUE THREAD

**Issue by worenga** [ClickHouse/ClickHouse#15190]
**Describe the issue**
I want to add a convenience alias to a nested field column

This is the query I am trying to run
```
CREATE TABLE IF NOT EXISTS foo
(
    `bar` Nested(    id String,     outcome UInt8),
    `barName` Array(String) ALIAS arrayMap(x -> dictGetString('somedict', 'name', toUInt64(x)), bar.outcome)
)
ENGINE = Null
```

What I get is

```
Received exception from server (version 20.9.2):
Code: 47. DB::Exception: Received from clickhouse-server:9000. DB::Exception: Missing columns: 'bar.outcome' while processing query: 'CAST(arrayMap(x -> dictGetString('somedict', 'name', toUInt64(x)), bar.outcome) AS barName_tmp, 'Array(String)') AS barName, barName_tmp', required columns: 'bar.outcome', source columns: 'barName' 'bar': default expression and column type are incompatible.. 

0 rows in set. Elapsed: 0.008 sec. 
```

Is there a way to achieve this?

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/7677

**Comment by den-crane** [comment]
check this https://github.com/ClickHouse/ClickHouse/issues/12586

**Comment by worenga** [comment]
@den-crane I do not agree that 

    `bar` Nested(    id String,     outcome UInt8),

is syntactic sugar and could be replaced by 

    `bar.id`  Array(String),
    `bar.outcome`  Array(UInt8),

Reason being is that clickhouse ensures that the length of the two arrays are the same with nested why having 2 separate arrays the length could be potentially different

**Comment by den-crane** [comment]
@worenga  you did not understand. 

>Reason being is that clickhouse ensures that the length

because of the **dot** in a column name.

Nested it's a syntax sugar for "CREATE TABLE" only.  It means nothing. It do nothing.

**Comment by den-crane** [comment]
```
create table foo (`bar` Nested(id String,outcome UInt8) ) Engine=MergeTree order by tuple();

show create table foo;

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE dw.foo
(
    `bar.id` Array(String),
    `bar.outcome` Array(UInt8)
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘


drop table foo;
ok

CREATE TABLE dw.foo
(
    `bar.id` Array(String),
    `bar.outcome` Array(UInt8)
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192;

Ok.

insert into foo values (['', ''],[0])

Received from localhost:9000. DB::Exception: Elements 'bar.id' and 'bar.outcome' of Nested data structure 'bar' (Array columns) have different array sizes..

```

**Comment by fzyzcjy** [comment]
@den-crane Hi, thanks for the information that the dot is special! When creating my table, I am both having some nested/array and some normal columns. This thread makes me clear how to do aliasing for the first half.

So, I wonder, is it allowed to add dots to *normal* columns (merely to make the name better)? Will it cause any special unwanted behavior? For example,

```
CREATE TABLE a (
  sub_type Enum('apple'=1,'orange'=2),
  apple.a String,
  apple.b Int32,
  orange.x Double,
  orange.y String,
)
```

**Comment by victor-perov** [comment]
Hey @den-crane! It doesn't look like the problem @worenga explained has actually been discussed. The comms were diverted a little bit by the _sugar_ thing.

`a Nested (name UInt16, value String)` is the way available for us to use to describe a nested column when we create a table. Whether it is an alternative way of writing `a.name UInt16, a.value String` it doesn't matter - users should not be bothered which way of writing nested datasets they need to use - both ways should do exact the same thing, otherwise there is bug and/or one option MUST not be accepted by the create table statement.

In other words, when I create a table like

```
CREATE TABLE my_table
(
    `id` UInt32,
    `N` Nested(name UInt16, value String),
    `X` Array(String) ALIAS arrayMap(x -> dictGetStringOrDefault('desc', 'name', x, 'unknown'), N.name)
)
ENGINE = MergeTree
ORDER BY id
```
and when I create table like

```
CREATE TABLE my_table
(
    `id` UInt32,
    `N.name` UInt16,
    `N.value` String,
    `X` Array(String) ALIAS arrayMap(x -> dictGetStringOrDefault('desc', 'name', x, 'unknown'), N.name)
)
ENGINE = MergeTree
ORDER BY id
```

I'm expecting to get the exact same outcome.
However, the first option fails with: `DB::Exception: Missing columns: 'N.name' while processing: '_CAST(arrayMap(x -> dictGetStringOrDefault('desc', 'name', x, 'unknown'), N.name) AS X_tmp_alter4875321099442560198, 'Array(String)') AS X, X_tmp_alter4875321099442560198', required columns: 'N.name', available columns: 'X' 'N' 'id': default expression and column type are incompatible.. (UNKNOWN_IDENTIFIER)` in no matter which version I use (from v23.3 til v25.1) but the second - succeeds.

I do agree though it is related to #7677.

The issue is still exists. Can we get some light on the issue, please?
