### ISSUE TITLE
Can support table based synchronization for MaterializeMySQL?

### ISSUE THREAD

**Issue by chang0391** [ClickHouse/ClickHouse#15211]
At present, synchronization is based on database in MaterializeMySQL engine. However, there are many tables under a database. there may be very few tables that need to be synchronized to CH for analysis. so, It is useless and waste of resources to synchronize unneeded tables. if can support table based synchronization for MaterializeMySQL, It will be more flexible and effective

**Comment by zhang2014** [comment]
Yes, it's very useful.
There are two ways implement this:
- [ ] Support MaterializeMySQL table engine(It will be implemented in #14541. I understand that this approach is not suitable for synchronizing MySQL ddl, because this may cause the behavior to be inconsistent with other table engines.)
- [ ] Support filter tables in MaterializedMySQL database engine(In my todo list).

**Comment by l1t1** [comment]
can it support sync the views of mysql table, such as some columns,rows of a table?

**Comment by chang0391** [comment]
@zhang2014 
   Good idea, thanks for your effort

**Comment by chang0391** [comment]
@zhang2014
    Have the function of support MaterializeMySQL table engine already began to do it?

**Comment by tavplubix** [comment]
#15409
