### ISSUE TITLE
Neither merge nor OPTIMIZE TABLE remove duplicates from a ReplacingMergeTree table

### ISSUE THREAD

**Issue by damienknox** [ClickHouse/ClickHouse#15430]
Hello, I am using the latest CH version:
>ClickHouse client version 20.9.2.20 (official build).

I want to keep unique records for YMD, StoreID, ProductID
```
CREATE TABLE prod_stats.PriceChanges2
(
    `YMD` Date,
    `StoreID` UInt32,
    `ProductID` UInt32,
    `Cnt` UInt32
)
ENGINE = ReplacingMergeTree()
PARTITION BY YMD
ORDER BY (YMD, StoreID, ProductID)
PRIMARY KEY (YMD, StoreID, ProductID)
```

but there are 23064 duplicated records. They have been there for several weeks already.
```
SELECT count(*)
FROM
(
    SELECT YMD, StoreID, ProductID, count(*)
    FROM prod_stats.PriceChanges2
    GROUP BY YMD, StoreID, ProductID
    HAVING count(*) > 1
)

┌─count()─┐
│   23064 │
└─────────┘

```

Optimize table does not help either:
```
OPTIMIZE TABLE prod_stats.PriceChanges2

Ok.

0 rows in set. Elapsed: 0.001 sec.

```

```
SELECT count(*)
FROM
(
    SELECT YMD, StoreID, ProductID, count(*)
    FROM prod_stats.PriceChanges2
    GROUP BY YMD, StoreID, ProductID
    HAVING count(*) > 1
)

┌─count()─┐
│   23064 │
└─────────┘

```

Here is an example of a dupicated record:
```
SELECT top 1 YMD,StoreID,ProductID,count(*) FROM prod_stats.PriceChanges2
GROUP BY YMD,StoreID,ProductID
HAVING count(*)>1


┌────────YMD─┬─StoreID─┬─ProductID─┬─count()─┐
│ 2020-09-23 │    3206 │  37733776 │       2 │
└────────────┴─────────┴───────────┴─────────┘

1 rows in set. Elapsed: 0.085 sec. Processed 411.97 thousand rows, 4.12 MB (4.83 million rows/s., 48.27 MB/s.)

```

```
SELECT * FROM prod_stats.PriceChanges2
WHERE YMD='2020-09-23' AND StoreID=3206 AND ProductID=37733776

┌────────YMD─┬─StoreID─┬─ProductID─┬─Cnt─┐
│ 2020-09-23 │    3206 │  37733776 │   1 │
│ 2020-09-23 │    3206 │  37733776 │   1 │
└────────────┴─────────┴───────────┴─────┘

2 rows in set. Elapsed: 0.004 sec. Processed 7.81 thousand rows, 109.35 KB (2.06 million rows/s., 28.90 MB/s.)

```

Using the **final** keyword helps, but that does not explain why neither merge nor optimize table remove duplicates.

**Comment by den-crane** [comment]
`OPTIMIZE TABLE prod_stats.PriceChanges2` initiates an unplanned merge. It's not designed to remove duplicates. 
For example your table has 100 partitions and each partition has 100 parts. OPTIMIZE TABLE can just merge 2 of the parts inside one partitions and leave 10000 unmerged parts. Furthermore it can do nothing because of lack of free resources in background pool. 

Try `OPTIMIZE TABLE prod_stats.PriceChanges2 final` -- final modifier makes OPTIMIZE to merge all possible / available parts. 


https://clickhouse.tech/docs/en/sql-reference/statements/optimize/

https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replacingmergetree/

_Data deduplication occurs only during a merge. Merging occurs in the background at an unknown time, so you can’t plan for it. Some of the data may remain unprocessed. Although you can run an unscheduled merge using the OPTIMIZE query, don’t count on using it, because the OPTIMIZE query will read and write a large amount of data._

_Thus, ReplacingMergeTree is suitable for clearing out duplicate data in the background in order to save space, but it doesn’t guarantee the absence of duplicates._

**Comment by damienknox** [comment]
Thanks, `OPTIMIZE TABLE prod_stats.PriceChanges2 final` helped!
