### ISSUE TITLE
Some queries are taking more that 10-15 seconds while some are completed within few seconds

### ISSUE THREAD

**Issue by John-belt** [ClickHouse/ClickHouse#15474]
On our production system we have 5 node cluster. We have 3 clickhouse nodes running on 3 hosts(circular config with replication factor of 2). **Also the table has only 5 rows and partitioned by every week. Engine: ReplicatedMergeTree**

. We are inserting around 100-200K rows per batch every 1-2 seconds(Sometime concurrent inserts also happens). Performance is Good but every 4-5th query is taking 10-15secs as compare to others which take 2-3 seconds. I am trying to find out what might be bottlenecking these. No high CPU utilization or io utilization can be seen on the system. 
I don't find any per table which give me this type of data per query. Maybe limited number of threads are creating this kind of behaviour.

Is there a way to increase the insert speed of the queries????. Maybe assigning more threads or something?? i have ample amount of RAM(128gigs) and running 40 Core, hyperthreaded system, so resource is not the problem. Just want a better insert speed

**Comment by den-crane** [comment]
it could be merges or `parts_to_delay_insert`



## parts\_to\_delay\_insert {#parts-to-delay-insert}

If the number of active parts in single partition exceeds the value of `parts_to_delay_insert` ` INSERT` artificially slows down.

Possible values:

-   Any positive integer.

Default value: 150.

ClickHouse artificially executes `INSERT` longer (adds ‘sleep’) so that the background merge process can merge parts faster than they are added.

## max\_delay\_to\_insert {#max-delay-to-insert}

The value in seconds, which is used to calculate the `INSERT` delay, if the number of active parts in single partition exceeds the value [parts\_to\_delay\_insert](#parts-to-delay-insert).

Possible values:

-   Any positive integer.

Default value: 1.

The delay (in milliseconds) for `INSERT` is calculated by the formula:

``` code
max_k = parts_to_throw_insert - parts_to_delay_insert
k = 1 + parts_count_in_partition - parts_to_delay_insert
delay_milliseconds = pow(max_delay_to_insert * 1000, k / max_k)
```

For example if a partition has 299 active parts and parts\_to\_throw\_insert = 300, parts\_to\_delay\_insert = 150, max\_delay\_to\_insert = 1, `INSERT` delays for `pow( 1 * 1000, (1 + 299 - 150) / (300 - 150) ) = 1000` milliseconds.

**Comment by John-belt** [comment]
Changed 'parts_to_delay_insert' from 150 to 200.
Now 'select count(*) from system.parts;'  => return 356
and then 'select count(*) from system.parts where active = 1;'   => return 54
'select * from system.merges'  => return 0
No performance boost

**Comment by den-crane** [comment]
Can you provide a clipping from clickhouse-server.log around that long insert ?

**Comment by John-belt** [comment]
[new_log.txt](https://github.com/ClickHouse/ClickHouse/files/5307001/new_log.txt)

**Comment by den-crane** [comment]
> "Failed to get size of directory DB_1: lstat /bp2/data/data/DB_1/tempo_for_ls/tmp_insert_20200921_20200921_92285_92285_0: no such file or directory

It does not look like CH logs. And I see weird errors. Probably because of K8s.

**Comment by John-belt** [comment]
@den-crane 'tempo_for_ls' is my table name. These are the snippet from  the logs in /var/log/clickhouse-server/clickhouse-server.log.

**Comment by den-crane** [comment]
@John-belt Do you use k8s kubernetes ? It looks like you run CH in some docker or kubernetes?

**Comment by John-belt** [comment]
yup running docker inside docker container

**Comment by den-crane** [comment]
@John-belt What is /bp2 ? ` /bp2/data/data/DB_1/tempo_for_ls/ ) `
How /bp2 attached into docker ?

**Comment by John-belt** [comment]
/bp2 is the naming convention we use for directory in our prod servers

**Comment by John-belt** [comment]
@den-crane does all these processing happening in the background. I mean these must be async. processes right?? All those inserts and merges running in background and our client is not being delayed waiting for the insert completion to process next insertion right??

**Comment by den-crane** [comment]
No, that's not what I am asking.

Can you show compose or docker command.

What is bp2 ?
   *  data volume
   * mounted host directory
   *  network attached

**Comment by John-belt** [comment]
It is a data volume.

**Comment by John-belt** [comment]
I ran 'select * from system.metrics LIMIT 1;' and i got
Number of executing queries was 8, this probably means 8 concurrent queries are running which might be bottlenecking??

**Comment by alexey-milovidov** [comment]
It is easy to check why a query is slow by using Query Profiler:
https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/
