### ISSUE TITLE
Connecttion refused after kill the clickhouse server process

### ISSUE THREAD

**Issue by y45398jp123** [ClickHouse/ClickHouse#15802]
I have a clickhouse table containing more than 40 billion records.  One day I want to modify a parameter in my config.xml. So I attempted to stop the server but it was stuck. I guess there were many background processes working. Then I kill the clickhouse server with "kill -9".
However when I tried to restart the server and run clickhouse-client again, I got "connection refused". 
If I remove all data partitions and the corresponding table metadata (sql), it works fine again. Once I move the table data back to its position, I got the same error "connection refused" again.

**How to reproduce**
if I tried to stop the clickhosue server process with "kill -9", but not "clickhouse-server stop". the error occurs. Especially when its a massive table.

* Which ClickHouse server version to use
version 20.0.10

If any ideas? Thanks.

**Comment by den-crane** [comment]
40 billion records -- it's not big table. There are installation with 40 trillions.
CH start time depends on number of parts (table partitioning).

Can you show `select count() from system.parts` ?

**Comment by y45398jp123** [comment]
Thanks for your reply @den-crane 
the table contains 14521 partitions and 119 columns.
do i have to wait for longer time after restart the server before trying to connect? have no idea...
Thanks.

**Comment by den-crane** [comment]
>The table contains 14521 partitions and 119 columns.

Then slow start is expected. Especially on slow HDD or IOPS limited cloud disks (like AWS EBS GP1)
You should wait longer  for a start minutes. I've heard that in case of 100000 CH can start up to 40 minutes.
This is expected by design. Because CH reads reads every part (metadata) on start. 

You can use disks with low latency (SSD/NVME) or reduce number of partitions (by re-desingning your table -- partition by section).

**Comment by y45398jp123** [comment]
thanks so much for reply, quick and professional !
