### ISSUE TITLE
could you release an android version binary like the following post

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#15830]
(you don't have to strictly follow this form)
https://github.com/ClickHouse/ClickHouse/blob/95c6efbdc1d607306c5bee79b18a27885efaa218/website/blog/en/2020/pixel-benchmark.md
**Use case**
A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akuzm** [comment]
I lost it :fearful:

You might be able to build it using the Android toolchain as described here: https://github.com/ClickHouse/ClickHouse/blob/95c6efbdc1d607306c5bee79b18a27885efaa218/website/blog/en/2020/pixel-benchmark.md#using-the-android-toolchain

It might be helpful to add `-DENABLE_LIBRARIES=0` cmake flag, so that most of third-party libraries are disabled.
