### ISSUE TITLE
to create MaterializeMySQL engin wasn't finished successfully

### ISSUE THREAD

**Issue by yanchaoguo** [ClickHouse/ClickHouse#15883]
The first few completed tables can be queried normally

`
2020.10.13 09:14:48.751772 [ 23597 ] {} <Error> MaterializeMySQLSyncThread(): Query EXTERNAL DDL FROM MySQL(hd_db, eqs_hd) B wasn't finished successfully: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 102 ('B'): B. Expected one of: RENAME DATABASE, TRUNCATE, RENAME TABLE, DROP query, RENAME DICTIONARY, DETACH, RENAME query, DROP, create query, CREATE, EXCHANGE TABLES, ALTER TABLE, alter query, Stack trace (when copying this message, always include the lines below):

0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0xe922219 in /usr/bin/clickhouse
1. ? @ 0xdeb61b7 in /usr/bin/clickhouse
2. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdeb5dbd in /usr/bin/clickhouse
3. ? @ 0xdaf5594 in /usr/bin/clickhouse
4. DB::MaterializeMySQLSyncThread::onEvent(DB::MaterializeMySQLSyncThread::Buffers&, std::__1::shared_ptr<DB::MySQLReplication::EventBase> const&, DB::MaterializeMetadata&) @ 0xdaf1752 in /usr/bin/clickhouse
5. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdaeeaac in /usr/bin/clickhouse
6. ? @ 0xdb0acbd in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x7b8375d in /usr/bin/clickhouse
8. ? @ 0x7b87273 in /usr/bin/clickhouse
9. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
10. clone @ 0xfdead in /usr/lib64/libc-2.17.so
 (version 20.10.1.4881 (official build))
`

after that，all tables can not be queried

2020.10.13 09:19:10.930722 [ 24253 ] {} <Error> MaterializeMySQLSyncThread: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 13. Bytes expected: 14., Stack trace (when copying this message, always include the lines below):

**Comment by zhang2014** [comment]
Can you provide some information on how to reproduce this problem?

**Comment by yanchaoguo** [comment]
> Can you provide some information on how to reproduce this problem?

this is source table schema in mysql 

CREATE TABLE `dashboard_datasource` (
  `datasource_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(50) NOT NULL,
  `source_name` varchar(100) NOT NULL,
  `source_type` varchar(100) NOT NULL,
  `config` text,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`datasource_id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4

**Comment by yanchaoguo** [comment]
即便是表里面没有数据 clickhouse也报下面的错误 @zhang2014 
Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 4.

**Comment by zhang2014** [comment]
> Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 4.

能提供一下堆栈信息么? 另外针对第一个错误的复现步骤(或者可以提供一下第一个错误发生时的clickhouse完整日志)？

**Comment by yanchaoguo** [comment]
> > Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 4.
> 
> @yanchaoguo 能提供一下堆栈信息么? 另外针对第一个错误的复现步骤(或者可以提供一下第一个错误发生时的clickhouse完整日志)？

上面的错误信息是日志中的全部了 ，您可以按照我上面的提供的表结构在mysql5.6版本中创建空表 让后在clickhouse20.10中生成MaterializeMySQL database  这个时候去查询clickhouse对应的表就会复现上面的错误了

**Comment by zhang2014** [comment]
>>> Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 4.

>> @yanchaoguo 能提供一下堆栈信息么? 另外针对第一个错误的复现步骤(或者可以提供一下第一个错误发生时的clickhouse完整日志)？

> 上面的错误信息是日志中的全部了 ，您可以按照我上面的提供的表结构在mysql5.6版本中创建空表 让后在clickhouse20.10中生成MaterializeMySQL database 这个时候去查询clickhouse对应的表就会复现上面的错误了

库中还包含其它表么?

**Comment by yanchaoguo** [comment]
> 还包含其它表么

就这一张表就可以复现问题了

**Comment by yanchaoguo** [comment]
> > > > Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 4.
> 
> > > @yanchaoguo 能提供一下堆栈信息么? 另外针对第一个错误的复现步骤(或者可以提供一下第一个错误发生时的clickhouse完整日志)？
> 
> > 上面的错误信息是日志中的全部了 ，您可以按照我上面的提供的表结构在mysql5.6版本中创建空表 让后在clickhouse20.10中生成MaterializeMySQL database 这个时候去查询clickhouse对应的表就会复现上面的错误了
> 
> 库中还包含其它表么?

初步判定 是clickhouse目前遇到 表结构中timestamp类型被NOT NULL DEFAULT CURRENT_TIMESTAMP修饰时就会报上述错误

**Comment by zhang2014** [comment]
暂不支持MySQL 5.6 #14564

**Comment by yanchaoguo** [comment]
> 暂不支持MySQL 5.6 #14564

大概在哪个版本会支持 因为5.6现在在企业当中还是使用很广泛的

**Comment by yanchaoguo** [comment]
> 暂不支持MySQL 5.6 #14564
不幸的是 我在5.7版本上试了一下 也有同样的问题

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3757518
Server version: **5.7.18**-txsql-log 20200331

**Comment by yanchaoguo** [comment]
> 暂不支持MySQL 5.6 #14564



不幸的是 我在5.7版本上试了一下 也有同样的问题

`Welcome to the MySQL monitor. Commands end with ; or \g.
Your MySQL connection id is 3757518
Server version: 5.7.18-txsql-log 20200331`

**Comment by zhang2014** [comment]
@yanchaoguo 通过提供的复现用例无法在我的环境中复现. 您能提供一下复现的mysql的binlog文件么？

另外您可以使用clickhouse-client 尝试执行以下SQL, 并粘贴结果到issues中么:
``` sql
SELECT * FROM system.build_options WHERE name like '%VERSION%' ;
```

**Comment by yanchaoguo** [comment]
> ```sql
> SELECT * FROM system.build_options WHERE name like '%VERSION%'
> ```


┌─name─────────────────┬─value────────────────────────────────────┐
│ VERSION_FULL         │ ClickHouse 20.10.1.4881                  │
│ VERSION_DESCRIBE     │ v20.10.1.4881-testing                    │
│ VERSION_INTEGER      │ 20010001                                 │
│ VERSION_GITHASH      │ 76a04fb4b4f6cd27ad999baf6dc9a25e88851c42 │
│ VERSION_REVISION     │ 54441                                    │
│ CMAKE_VERSION        │ 3.16.3                                   │
│ C_COMPILER_VERSION   │ 11.0.0                                   │
│ CXX_COMPILER_VERSION │ 11.0.0                                   │
│ TZDATA_VERSION       │ 2020a                                    │
└──────────────────────┴──────────────────────────────────────────┘

**Comment by zhang2014** [comment]
@yanchaoguo 能提供一下复现该问题的MySQL 的binlog文件么?

**Comment by yanchaoguo** [comment]
> @yanchaoguo 能提供一下复现该问题的MySQL 的binlog文件么?

这个日志在哪里看

**Comment by zhang2014** [comment]
执行```cat ${ClickHouse的数据目录下}/metadata/test_database/.metadata``` 得到如下内容:
```text
Version:	2
Binlog File:	binlog.000026
Executed GTID:	2ac45abe-931e-11ea-8515-607d56350782:1-131
Binlog Position:	10046316
Data Version:	1%
```

去MySQL数据目录下找到对应的binlog文件(最好包含后续的binlog文件, binlog.0000xx 其中xx为binlog的顺序, 在这个例子中找到比26大的所有的binlog文件, 截取前5个文件打包发送即可)。

**Comment by yanchaoguo** [comment]
[243](https://mysql-database-backup-sh-local-1256569818.cos.ap-shanghai.myqcloud.com/1252021759%2Fmysql%2F0fe55062-f04c-11e7-bc91-70e2840e12bd%2Fbinlog%2Fautomatic-delete%2F2020-10-15%2Fautomatic%2Fbinlog%2Fbl_334_11822971%2Fcdb-2fhxmzdt_binlog_20201015130303.log?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDjGYxDI8SBhz1zr7UdY8VfYEQhyzoI0HJ%26q-sign-time%3D1602740939%3B1602784139%26q-key-time%3D1602740939%3B1602784139%26q-header-list%3D%26q-url-param-list%3D%26q-signature%3Da182e47b0ae39777f16fcc8299e87ced8964edc5&response-content-disposition=attachment%3Bfilename%3D%22big_data%E5%A4%A7%E6%95%B0%E6%8D%AE_binlog_mysqlbin.000243%22&response-content-type=application%2Foctet-stream)
今天就只有这个文件 你看下

**Comment by yanchaoguo** [comment]
`[root@VM_8_129_centos` ~]# cat /data//work/clickhouse/metadata/bigdata_db/.metadata
Version:	2
Binlog File:	mysql-bin.000243
Executed GTID:	19831069-f04c-11e7-8e4b-6c92bf479de4:1-514984,262b31bb-f04c-11e7-a29b-c81fbecfcfdf:1-111,535eacda-93b3-11e9-848d-a4dcbef43ebe:1-913541241,5fc474d5-93b3-11e9-88a7-e435c87fc7f2:1-2,9b07b534-ba0c-11ea-bf4b-e435c881d062:1-3,d6886002-bcec-11ea-8f67-94292fc1df7f:1-97086022,ed71d648-06f6-11e8-85ba-5cb9018d7a68:1-572869758,f5a79f7c-06f6-11e8-8864-5cb901896350:1-996
Binlog Position:	261790019`

[binlog-243](https://mysql-database-backup-sh-local-1256569818.cos.ap-shanghai.myqcloud.com/1252021759%2Fmysql%2F0fe55062-f04c-11e7-bc91-70e2840e12bd%2Fbinlog%2Fautomatic-delete%2F2020-10-15%2Fautomatic%2Fbinlog%2Fbl_334_11822971%2Fcdb-2fhxmzdt_binlog_20201015130303.log?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDjGYxDI8SBhz1zr7UdY8VfYEQhyzoI0HJ%26q-sign-time%3D1602740939%3B1602784139%26q-key-time%3D1602740939%3B1602784139%26q-header-list%3D%26q-url-param-list%3D%26q-signature%3Da182e47b0ae39777f16fcc8299e87ced8964edc5&response-content-disposition=attachment%3Bfilename%3D%22big_data%E5%A4%A7%E6%95%B0%E6%8D%AE_binlog_mysqlbin.000243%22&response-content-type=application%2Foctet-stream)

今天只有1个文件

**Comment by linlancer** [comment]
@zhang2014  我的版本是 20.10.4887 prestable的版本 遇到类似情况导致的报错 Code: 538. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse MySQL create query
我遇到了类似的问题 我的表结构如下
 ```
CREATE TABLE `activity_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `subject_id` int(11) DEFAULT NULL,
  `subject_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `causer_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `causer_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `properties` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_log_log_name_index` (`log_name`)
) ENGINE=InnoDB AUTO_INCREMENT=185207 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
只要我往MySQL源数据库里面加入这张表  clickhouse里面这个数据库查询就会报 **Code: 538. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse MySQL create query**
删掉timestamp这俩字段 重新创建MaterializeMySQL才能正常

**Comment by linlancer** [comment]
@zhang2014  删掉timestamp 和 text的所有字段 重建才能正常 ，如果这时候往里加text timestamp字段反而能正常同步 不会报错

**Comment by linlancer** [comment]
> @zhang2014 删掉timestamp 和 text的所有字段 重建才能正常 ，如果这时候往里加text timestamp字段反而能正常同步 不会报错

Varchar(0) Text 这种没有指定长度或者长度为0的 在初始话同步的时候好像就会报错

**Comment by zhang2014** [comment]
@yanchaoguo The reason for this problem may be `binlog_checksum = NONE`, which you can check it with `SHOW VARIABLES WHERE Variable_name ='binlog_checksum';`

**Comment by yanchaoguo** [comment]
> @yanchaoguo The reason for this problem may be `binlog_checksum = NONE`, you can check it with `SHOW VARIABLES WHERE Variable_name ='binlog_checksum';`

好的  明天我试试

**Comment by yanchaoguo** [comment]
> @yanchaoguo The reason for this problem may be `binlog_checksum = NONE`, you can check it with `SHOW VARIABLES WHERE Variable_name ='binlog_checksum';`

mysql> SHOW VARIABLES WHERE Variable_name ='binlog_checksum'
    -> ;
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| binlog_checksum | NONE  |
+-----------------+-------+

**Comment by zhang2014** [comment]
@yanchaoguo 暂不支持binlog_checksum = None的MySQL主从消费，我将尝试修复它。

**Comment by peerhyw** [comment]
MySQL version: 8.0.21-0ubuntu0.20.04.4
ClickHouse version: 20.9.3

<Error> MaterializeMySQLSyncThread(joomla_clickhouse): Query EXTERNAL DDL FROM MySQL(test_clickhouse, test)  CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `username` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `password` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `block` tinyint NOT NULL DEFAULT '0',
  `sendEmail` tinyint DEFAULT '0',
  `registerDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `lastvisitDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `activation` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `params` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastResetTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Date of last password reset',
  `resetCount` int NOT NULL DEFAULT '0' COMMENT 'Count of password resets since lastResetTime',
  `otpKey` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Two factor authentication encrypted keys',
  `otep` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'One time emergency passwords',
  `requireReset` tinyint NOT NULL DEFAULT '0' COMMENT 'Require user to reset password on next login',
  PRIMARY KEY (`id`),
  KEY `idx_block` (`block`),
  KEY `username` (`username`),
  KEY `email` (`email`),
  KEY `idx_name` (`name`(100))
) ENGINE=InnoDB AUTO_INCREMENT=112728 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci wasn't finished successfully: Code: 46, e.displayText() = DB::Exception: Unknown function name, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe736dad in /usr/bin/clickhouse
2. ? @ 0x1546de1a in /usr/bin/clickhouse
3. DB::FunctionFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context const&) const @ 0x1546d5f5 in /usr/bin/clickhouse
4. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x15b8ee25 in /usr/bin/clickhouse
5. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::__1::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x15b8ef9b in /usr/bin/clickhouse
6. ? @ 0x15b688b9 in /usr/bin/clickhouse
7. DB::ExpressionAnalyzer::getActions(bool, bool) @ 0x15b6bd17 in /usr/bin/clickhouse
8. ? @ 0x15e4f6a8 in /usr/bin/clickhouse
9. ? @ 0x15e513dd in /usr/bin/clickhouse
10. DB::MySQLInterpreter::InterpreterCreateImpl::getRewrittenQueries(DB::MySQLParser::ASTCreateQuery const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15e53e85 in /usr/bin/clickhouse
11. DB::InterpreterExternalDDLQuery::execute() @ 0x15ac20e2 in /usr/bin/clickhouse
12. ? @ 0x15e2fdd2 in /usr/bin/clickhouse
13. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15e31732 in /usr/bin/clickhouse
14. ? @ 0x15a1fff4 in /usr/bin/clickhouse
15. ? @ 0x15a2a055 in /usr/bin/clickhouse
16. ? @ 0x15a2b793 in /usr/bin/clickhouse
17. DB::commitMetadata(std::__1::function<void ()> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15a65b69 in /usr/bin/clickhouse
18. DB::MaterializeMetadata::transaction(DB::MySQLReplication::Position const&, std::__1::function<void ()> const&) @ 0x15a67fbe in /usr/bin/clickhouse
19. DB::MaterializeMySQLSyncThread::prepareSynchronized(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15a23a19 in /usr/bin/clickhouse
20. DB::MaterializeMySQLSyncThread::synchronization(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15a286ab in /usr/bin/clickhouse
21. ? @ 0x15a28bc6 in /usr/bin/clickhouse
22. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe7645b7 in /usr/bin/clickhouse
23. ? @ 0xe762b03 in /usr/bin/clickhouse
24. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
25. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
 (version 20.9.3.45 (official build))


I created a MaterializeMySQL with the table ddl like above and it failed, but when i removed the length limit of last index `idx_name`(`name`(100)) to `idx_name`(`name`), it successed, so if the clickhouse not support index length limit of mysql ddl?

**Comment by zhang2014** [comment]
> I created a MaterializeMySQL with the table ddl like above and it failed, but when i removed the length limit of last index `idx_name`(`name`(100)) to `idx_name`(`name`), it successed, so if the clickhouse not support index length limit of mysql ddl?

Yes, index length limit is not support.
