### ISSUE TITLE
In the same partition in the system.parts table, why the size difference of different file names is too large

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#15989]
![demo](https://user-images.githubusercontent.com/37869445/96062744-0630aa00-0ec9-11eb-8313-ed459f00f185.jpg)

We found a phenomenon when querying the system.parts table, when the same partition (column:partition), the size of the merged file (column:name) is very different (column:size_on_disk). Is this what is the reason?

**Comment by nickevin** [comment]
![Uploading Screen Shot 2020-10-15 at 16.03.56.png…]()

**Comment by den-crane** [comment]
Because they contain different number of rows. Check the **rows** column.

_0_1607 -- means that it's a zero level part -- just inserted. You inserted 65k rows by an insert.
Later this parts will be merged into bigger parts. _1 _2 _3 level 1,2,3

**Comment by gubinjie** [comment]
@den-crane 
How do I know that the folders of this partition have been merged？
What is the meaning of active in the system.parts table?

**Comment by den-crane** [comment]
>How do I know that the folders of this partition have been merged？

You don't need to know.
But if you want you can check count of parts in system.parts group by partition.

>What is the meaning of active in the system.parts table?

https://clickhouse.tech/docs/en/operations/system-tables/parts/

_active (UInt8) – Flag that indicates whether the data part is active. If a data part is active, it’s used in a table. Otherwise, it’s deleted. Inactive data parts remain after merging._
