### ISSUE TITLE
ClickHouse server version 20.10.1 MaterializeMySQL metadata  file Include clear text password

### ISSUE THREAD

**Issue by YansongLi-Dr** [ClickHouse/ClickHouse#16256]
ClickHouse server version 20.10.1 experimental function MaterializeMySQL metadata  file
Include clear text password
it's not safe

**Comment by den-crane** [comment]
JFYI: CH always operate clear text passwords in case if CH is a client. External dictionaries, remote_servers.

No sense to encrypt these passwords. Because they have to be decrypted by a clear password stored somewhere near. Encryption here gives you a false sense of security.
It's your responsibility to defend these files.

It would have sense if CH asks for a master password on each start and stores this password in memory only. You can implement such feature by yourself using `from_env`  (https://github.com/ClickHouse/ClickHouse/issues/3483#issuecomment-433872369)
