### ISSUE TITLE
I don't want to put a plaintext password in the metrika.xml

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/ClickHouse#16396]
Currently,I must put shard/replicator plaintext passwords in metrika.xml under cluster scenario.
Obviously this is not secure and it is regarded as a serious problem by guys in my project,I want to use a encrypted password string which is encrypted by a reversible algorithm to replace the plaintext password.
So I must modify the souce code to implement a decrypted method to decrypt the encrypted string,can you give me some advise how to implement the method?ClickHouse version is 20.3.2.1.
Thank you!

**Comment by den-crane** [comment]
No sense to encrypt these passwords. Because they have to be decrypted by a clear password stored somewhere close. **Encryption here gives you a false sense of security.**
It's your responsibility to defend these files.

It would have sense if CH asks for a master password on each start and stores this password in memory only. You can implement such feature by yourself using `from_env`  (https://github.com/ClickHouse/ClickHouse/issues/3483#issuecomment-433872369)
