### ISSUE TITLE
Better git commit tree

### ISSUE THREAD

**Issue by sundy-li** [ClickHouse/ClickHouse#16789]
Have a glance at the git branch graph, it looks a mess compared to some other projects (such as Apache Spark).

![image](https://user-images.githubusercontent.com/3325189/98455093-28a3a380-21a7-11eb-94d9-f09eacade624.png)

But compared with `spark`, it's much better, the master branch with Require linear history.

![image](https://user-images.githubusercontent.com/3325189/98455456-e16be180-21ab-11eb-9c66-6600f60a34d6.png)

Github settings allow us to disable "Allow merge commits", but use "Allow rebase merging“ or ”Allow squash merging“, and delete temp branch when merged.

Pros:
- Linear history for master commit
- Better for cherry-pick
- Contributors no need to rebase commits any more

**Comment by akuzm** [comment]
Try `git log --first-parent master`, it should show linear history with mostly merge commits.

It was worse before and even filtering by first parent didn't help -- git completely ruins history with default settings when you do basic operations such as pull or merge. This was a big problem for automatic backports and generation of changelog, because the history we had was basically impossible to parse automatically.

Now we use the following settings for git:
```
git config --global merge.ff false
git config --global pull.rebase true
git config --global rebase.autoStash true
```
This at least prevents diamond merges and fast-forward merges, making the history readable with `--first-parent`.

**Comment by akuzm** [comment]
For cherry-picking merge commits, as far as I recall we use `git cherry-pick -m1`.

**Comment by filimonov** [comment]
@sundy-li afaik guys want to preserve original history of commits, i.e. to have complete and accurate history instead of clean history.

**Comment by alexey-milovidov** [comment]
That's true. We don't care about clean history but we want to keep commits to be able to find individual commits.

**Comment by alexey-milovidov** [comment]
You can filter only "Merge pull request" commits from the log and you will get clean history at least for several years.

**Comment by pan3793** [comment]
> We don't care about clean history but we want to keep commits to be able to find individual commits.

Actually git can keep both clean history and individual commits, just use rebase rather than squash.

![微信截图_20201110113739](https://user-images.githubusercontent.com/26535726/98625083-f7afa400-2349-11eb-8fc2-dbc7cc6fa540.png)

In my view, git merge likes diamond-inheritance in cpp, it will confuse us what branch the commit exactly belongs to, and the more people cooperate, the worse the situation. Look at elasticsearch with 1500+ contributors

![微信截图_20201110113812](https://user-images.githubusercontent.com/26535726/98625492-a6ec7b00-234a-11eb-9f44-9b22e0a39d48.png)

![微信截图_20201110113824](https://user-images.githubusercontent.com/26535726/98625506-ace25c00-234a-11eb-9670-3152b47db485.png)

**Comment by alexey-milovidov** [comment]
We don't use rebase for another reasons:
- it makes difficult to find commits from PR in master and find PRs for commit in master;
- it makes difficult to check if PR was merged;
- if multiple PRs are based on the same set of commits and will be rebased to master, commits will duplicate;
- the history becomes linear but the sequence of commits will contain broken/incomplete state.

PS. We don't really care about cleanliness of commit history.
