### ISSUE TITLE
MaterializeMySQL synchronization

### ISSUE THREAD

**Issue by wonsaign** [ClickHouse/ClickHouse#16833]
I used engine(MaterializeMySQL) to synchronize data from mysql, but when i update the data of mysql,  i see the clickhouse logs show:

> 2020.11.10 19:14:42.888949 [ 27085 ] {} <Debug> MaterializeMySQLSyncThread: Skip MySQL event:
> 
> === UpdateRowsEventV2 ===
> Timestamp: 1605006837
> Event Type: 31
> Server ID: 1
> Event Size: 77
> Log Pos: 6031
> Flags: 0
> [DryRun Event]
> 
> 2020.11.10 19:14:42.888981 [ 27085 ] {} <Debug> MaterializeMySQLSyncThread: Skip MySQL event:
> 
> === XIDEvent ===
> Timestamp: 1605006837
> Event Type: 16
> Server ID: 1
> Event Size: 31
> Log Pos: 6062
> Flags: 0
> XID: 375

and the tables of clickhouse has not change。

this is mysql config：

```
log-bin=mysql-bin
binlog_format=ROW  
server-id=1 

gtid-mode=on
enforce-gtid-consistency=1    
log-slave-updates=1 
```

**Comment by zhang2014** [comment]
```
2020.11.10 19:14:42.888949 [ 27085 ] {} MaterializeMySQLSyncThread: Skip MySQL event:

=== UpdateRowsEventV2 ===
Timestamp: 1605006837
Event Type: 31
Server ID: 1
Event Size: 77
Log Pos: 6031
Flags: 0
[DryRun Event]
```
This means that the current binlog event modifies data that is not in replicate database(`MaterializeMySQL('hostname:port', 'replicate_database', 'user', 'password')`)

```
2020.11.10 19:14:42.888981 [ 27085 ] {} MaterializeMySQLSyncThread: Skip MySQL event:

=== XIDEvent ===
Timestamp: 1605006837
Event Type: 16
Server ID: 1
Event Size: 31
Log Pos: 6062
Flags: 0
XID: 375
```
ClickHouse only processes events related to data changes(`INSERT`, `UPDATE`, `DELETE` and other DDL statements.)

**Comment by wonsaign** [comment]
> ```
> 2020.11.10 19:14:42.888949 [ 27085 ] {} MaterializeMySQLSyncThread: Skip MySQL event:
> 
> === UpdateRowsEventV2 ===
> Timestamp: 1605006837
> Event Type: 31
> Server ID: 1
> Event Size: 77
> Log Pos: 6031
> Flags: 0
> [DryRun Event]
> ```
> 
> This means that the current binlog event modifies data that is not in replicate database(`MaterializeMySQL('hostname:port', 'replicate_database', 'user', 'password')`)
> 
> ```
> 2020.11.10 19:14:42.888981 [ 27085 ] {} MaterializeMySQLSyncThread: Skip MySQL event:
> 
> === XIDEvent ===
> Timestamp: 1605006837
> Event Type: 16
> Server ID: 1
> Event Size: 31
> Log Pos: 6062
> Flags: 0
> XID: 375
> ```
> 
> ClickHouse only processes events related to data changes(`INSERT`, `UPDATE`, `DELETE` and other DDL statements.)

em.. 
In my docker , i only just run one "mysql" , it means that i need to set up mysql cluster?  Can the 'ch' synchronize one "mysql"?

**Comment by tavplubix** [comment]
> In my docker , i only just run one "mysql" , it means that i need to set up mysql cluster? Can the 'ch' synchronize one "mysql"?

Yes, MaterializeMySQL supports replication from single MySQL server, you don't need to setup a cluster.

>  i update the data of mysql ... and the tables of clickhouse has not change

MaterializeMySQL replicates tables from one database in MySQL, changes in other databases are ignored.  If you want to replicate data from several databases in MySQL, you should create several corresponding MaterializeMySQL databases in ClickHouse. To enable replication from some database, you should specify correct name of database in MySQL when creating MaterializeMySQL database in ClickHouse. For example, if you have database named `some_db_name` in MySQL, then you should create database in ClickHouse with `engine=MaterializeMySQL('hostname:port', 'some_db_name', 'user', 'password')`. Most likely there is no changes in ClickHouse tables because you specified name of wrong database.
