### ISSUE TITLE
RBAC - KILL MUTATION requires 0 grants, but KILL MUTATION ON CLUSTER requires 4 ALTER grants.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#17146]
A user doesn't need any grants to execute `KILL MUTATION` , but needs `ALTER UPDATE`, `ALTER DELETE`, `ALTER MATERIALIZE INDEX`, and `ALTER MATERIALIZE TTL` to execute `KILL MUTATION ON CLUSTER`.

**How to reproduce**
* ClickHouse server version 20.12.1

* Queries to run that lead to unexpected result
```
clickhouse1 :) kill mutation where 1

KILL MUTATION WHERE 1 ASYNC

Query id: e7a0a643-28d1-40bd-a0fe-45137868f0aa

Ok.

0 rows in set. Elapsed: 0.006 sec.

clickhouse1 :) kill mutation on cluster sharded_cluster where 1

KILL MUTATION ON CLUSTER sharded_cluster WHERE 1 ASYNC

Query id: e3be7b71-03f7-410c-9b40-7761d9a92fcd

Received exception from server (version 20.12.1):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: user0: Not enough privileges. To execute this query it's necessary to have the grant ALTER UPDATE, ALTER DELETE, ALTER MATERIALIZE INDEX, ALTER MATERIALIZE TTL ON *.*.

0 rows in set. Elapsed: 0.023 sec.
```

**Comment by alexey-milovidov** [comment]
@MyroTk 

Most likely you are being able to execute your KILL MUTATION query because there is no mutations and there is nothing to kill.

**Comment by vitlibar** [comment]
To execute `KILL MUTATION` (without `ON CLUSTER`) for a mutation you must have the exact grant which is required to start that mutation. It means e.g. to kill `alter delete` mutation you must have the `ALTER DELETE` grant.

To execute `KILL MUTATION ON CLUSTER` you must have all the grants `ALTER DELETE, ALTER UPDATE, ALTER MATERIALIZE TTL ON *.*` because it's executed on cluster and while we're checking the access righs we don't know yet which mutations we're actually going to kill.

**Comment by alexey-milovidov** [comment]
@MyroTk Please update the documentation.
