### ISSUE TITLE
Generate server UUID at first start.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#17278]
Write a file `uuid` in server's data directory that contains random UUID, generated at startup if file does not exist.

It will be used for several purposes:
- to anonymously identify server in Sentry (currently Sentry is unusable);
- (possible future usage) to identify server in ensemble.

@tavplubix comments?

**Comment by sundy-li** [comment]
why not `FQDN ` with `tcp_port` ?

**Comment by filimonov** [comment]
> why not `FQDN ` with `tcp_port` ?

to *anonymously* identify.

**Comment by filimonov** [comment]
BTW: in sentry / collecting anounimous stats context: it can be problematic to use even such anonymous ids without clear user opt-in in some countries (GDPR and similar laws) - using any kind of uniques identifiers / device ids etc. in 'anonimous' statistics is regulated, and should not happen without clear user opt-it. But since sentry is disabled by default i think it's ok - so user need to enable (opt-in) it manually.

**Comment by alexey-milovidov** [comment]
Yes, Sentry is opt-in.

I also first considered using crypto-hash of FQDN, but it can be brute-forced if reverse DNS is available.

**Comment by bharatnc** [comment]
@alexey-milovidov  I have started working on this. /assign to me ?

**Comment by alexey-milovidov** [comment]
Ok, thank you!
