### ISSUE TITLE
More reliable async inserts into Distributed 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#17380]
* support fsync after insert into Distributed (i saw many times damaged files in distributed tables after hard restarts)
* mechanism similar to "Too many parts" when inserting to Distributed - when something wrong in underlying table Distributed tables tends to collect (even millions) of unprocessed files completely silently for user (unless he monitor metrics / distributed_queue).

Question here - where to put those settings. Should it live in user settings or maybe engine=Distributed should have it's own settings?

**Comment by den-crane** [comment]
Another issue that Distributed table tries to insert into underlying table indefinitely.
It needs some stopper. For example after some number of tries/errors block insert into Distributed for example to signal to a client.
 
https://github.com/ClickHouse/ClickHouse/issues/12530#issuecomment-658902526

**Comment by alexey-milovidov** [comment]
Workaround: set insert_distributed_sync = 1.

**Comment by filimonov** [comment]
> Workaround: set insert_distributed_sync = 1.

Actually async in desired in many cases. For example it can do proper retries into Replicated. It properly deals with partial failure. It easily survive that some server is temporary unavailiable or we loose the connection during sending the data.

**Comment by azat** [comment]
>It needs some stopper.

There is `system stop distributed sends db.table`, but I guess you are talking about some automatic way of doing this.
There are also `distributed_directory_monitor_sleep_time_ms`/`distributed_directory_monitor_max_sleep_time_ms`.

> For example after some number of tries/errors block insert into Distributed for example to signal to a client.

You cannot get this error from the INSERT query context anyway, only from `SYSTEM FLUSH DISTRIBUTED`

So that said that it seems to me that `system stop distributed sends db.table` should be enough.
