### ISSUE TITLE
Is it a bug when number of ast elements >  max_expanded_ast_elements if there are many mutations.

### ISSUE THREAD

**Issue by yiguolei** [ClickHouse/ClickHouse#17882]
I am reading clickhouse mutation code. In StorageMergeTree->selectPartsToMutate() function, there is a check 
`if (current_ast_elements + commands_size >= max_ast_elements)
                break;`

I think if there are many mutations then the check result will be true, so that it will skip the remaining mutations.
But the new part's mutation is set to the last one in mutation map, and it does not apply the remaining mutations actually.
`new_part_info.mutation = current_mutations_by_version.rbegin()->first;`

Then the new part will miss the remaining mutations in future mutation job.

I think it's wrong here. Am I right?

If it is right, I will submit a PR

**Comment by tavplubix** [comment]
@yiguolei, nice catch! Yes, it's a bug. I'm really sorry, that we missed you report. I've just accidentally discovered this bug while debugging flaky test for another feature and fixed it in #32814. And only then I found this issue. Unfortunately, sometimes don't have enough time to take a deep look at all issues with "question" label and answer. It's better to choose "Bug report" issue type instead of "Question" to report a bug, but, anyway, I'm sorry that we did non answer for more than one year.
