### ISSUE TITLE
the standards of the max_threads ... setting?

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#17913]
![2020-12-09_130943](https://user-images.githubusercontent.com/23301704/101587982-52f3b580-3a20-11eb-8b5f-1324a915e883.png)
why the max_final_threads is bigger than max_threads?

**Comment by KochetovNicolai** [comment]
`max_threads` setting uses the number of physical cores by default, and it is usually an optimal value.
`max_final_threads` does not use the number of physical cores because it is not as optimal. When I tested parallel final on 32 cores, values between 8 and 16 were the most optimal for many cases.
In case if `max_final_threads < max_threads`, `max_threads` will be used instead of `max_final_threads`.

**Comment by l1t1** [comment]
thanks
