### ISSUE TITLE
drop table on cluster but not delete on zookeeper

### ISSUE THREAD

**Issue by wangxuanyue** [ClickHouse/ClickHouse#18382]
drop table on cluster but not delete on zookeeper，In a while it will delete in zookeeper.

**How to reproduce**
* Which ClickHouse server version to use  :  20.10.3.30

step1:
create table if not exists test on cluster dev
(
    day_id                String,
    user_id               String,
    device_number  String
)
engine = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/test', '{replica}')
      partition by day_id
      order by device_number;

step2:
drop table test on cluster dev;

step3:  change day_id type to Int64，different step1
create table if not exists test on cluster dev
(
    day_id                Int64,
    user_id               String,
    device_number  String
)
engine = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/test', '{replica}')
      partition by day_id
      order by device_number;

after run DDL:

Received exception from server (version 20.10.3):
Code: 122. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: There was an error on [*.*.*.*:9000]: Code: 122, e.displayText() = DB::Exception: Table columns structure in ZooKeeper is different from local table structure (version 20.10.3.30 (official build)).

**Comment by den-crane** [comment]
This is a behavior related to Atomic database engine.
When a table in Atomic database been dropped it is not removed immediately but after 480s.

```
config.xml
<database_atomic_delay_before_drop_table_sec>480</database_atomic_delay_before_drop_table_sec>
```
https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/database_atomic.xml 

You can 
1. use ordinary database instead of atomic. `create database ... Engine=Ordinary.`
2. use uniq ZK path `/clickhouse/tables/{layer}-{shard}-{uuid}/streams.streams_apps_ext_log_test`
3. reduce `database_atomic_delay_before_drop_table_sec = 0;` &  `drop table ... sync`

**Comment by wangxuanyue** [comment]
thank you
