### ISSUE TITLE
Fire and forget mode or limited number of retries for distributed sends.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18407]
**Use case**

1. Mirror data from production to testing environment with MATERIALIZED VIEW with Distributed engine. The testing cluster should not affect production in any way: better to skip data when testing is unavailable than to accumulate it.

2. Send query_log, metric_log, text_log, etc. to third-party unreliable service. If the third-party service is unavailable just skip sending the data batch.

**Describe the solution you'd like**

A table-level setting to Distributed table.
Either simple fire-and-forget mode (no retries) or specify the maximum number of retries before dropping the data (better).

**Alternatives**

A table with URL engine. But we should also introduce mode to ignore sending errors or do retries.
It can be even more flexible than Distributed table.

**Comment by alexey-milovidov** [comment]
Halfway fixed by introduction of `wait_for_async_insert` setting.
But even if this setting is disabled, we ensure that data is being received by the server.

**Comment by azat** [comment]
I've just needed something similar - send data to some 3d party service and ignore any errors.

@alexey-milovidov what do you think about introducing something syntax to the MVs to ignore errors, or another option is to introduce some setting for this - #21721, i.e. `materialized_views_ignore_errors`?

I've looked through other DBMS'es and haven't found any syntax for such behavior there.

P.S. not sure how `wait_for_async_insert` is related here, since async inserts is when you have values in the query.
