### ISSUE TITLE
Evaluate and integrate with TerarkDB

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#18487]
https://github.com/bytedance/terarkdb

**Use case**
As a backend for dictionaries to key-value access.
Similar to `EmbeddedRocksDB` table engine.

**Comment by alexey-milovidov** [comment]
@sundy-li @spongedu Do you consider it as even marginally useful?

**Comment by sundy-li** [comment]
I don't know how popular is `EmbeddedRocksDB` in other companies used currently. If the upvote of this issue is larger than some number (maybe 20), we can go ahead to add this.

Some advice on this feature.
1.  We can have a common abstraction of embedded kv store, then lots kv store(sled, badger..) can be chosen by factory method.
2. `EmbeddedRocksDB` can have an alias named `rocksdb`, since it's hard to spell `Embedded` and rocksdb is already embedded store.
3. It's better to add `TerakDB` features by developers from `TerakDB`.

**Comment by alexey-milovidov** [comment]
Ok. I've created this task only to invite enthusiasts. Looks like there are none :)
