### ISSUE TITLE
add ANALYZE COMPRESSION query

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#18536]
**Use case**
Give users an easy way to automatically check/test multiple codecs and suggest a good enough combination of them.

**Describe the solution you'd like**
Like amazon redshift has 
https://docs.aws.amazon.com/redshift/latest/dg/r_ANALYZE_COMPRESSION.html

**Comment by alexey-milovidov** [comment]
There are a few interesting facts about codecs:

1. The usage of specialized codecs like DoubleDelta, Gorilla, and FPC is useless in the presence of ZSTD and is worse than simply using ZSTD. So, there is no point in suggesting them.
2. For all other cases, the choice should be between LZ4 and ZSTD. ZSTD should be preferred most of the time, with level 1. Higher levels are not so useful (not because they are bad, but because of the specific usage of ZSTD in ClickHouse).
3. It is much better to have autodetection than to introduce another type of query.
4. There is another related task - decoupling column types from data types - to choose between Const, Sparse, LowCardinality, and normal columns automatically without specifying it inside the data type. We can also introduce something for when a user provides hex and base64-encoded strings - to autodetect and decode them in the storage. This task is also needed for semistructured data support.

**Comment by UnamedRus** [comment]
>  ZSTD should be preferred most of the time, with level 1

I'm not so sure about that, ie imagine, you have regular Pareto distribution of table size between columns: 
20% of columns takes 80% of disk space and rest (80%) columns use 20% of disk space.
If we will encode those 80% with ZSTD codec, it will significantly decrease write and read performance without any impact on table size. (Don't forget that we now also compress mark files, which is another cpu penalty)

> We can also introduce something for when a user provides hex and base64-encoded strings - to autodetect and decode them in the storage.

I think, it should be separate data type, it will allow us to have better specialization for `=` operator and other functions...
BTW, feature request for that: https://github.com/ClickHouse/ClickHouse/issues/20042#issuecomment-772646814

**Comment by alexey-milovidov** [comment]
Let's not implement it for now.
