### ISSUE TITLE
Subpartition (RFC)

### ISSUE THREAD

**Issue by amosbird** [ClickHouse/ClickHouse#18695]
Subpartitions are parts of a MergeTree table's partition. It's defined by an expression based on minmax columns (not the partition expr). It provides the ability to confine merges inside a single partition, and allows user to select a subset of parts of a given partition during ALTER PARTITION commands, notably, REPLACE PARTITION. It's useful to support dynamic partitioning, which helps with applications related to the "lambda architecture".

### Subpartition Examples:
```
create table x (dt DateTime) engine MergeTree partition by toYYYYMM(dt);
alter table x add partition expr hourly toStartOfHour(dt) where toDate(dt) >= today() - 3 days;
alter table x add partition expr daily toDate(dt) where toDate(dt) >= today() - 7 days;
alter table x replace partition expr hourly = '2021-01-01 00:00:00' from x_base;
```

All the partition manipulating commands will be extended.

### Subpartition Internals:

Given a partition expr, the table's part merging process will be confined to only merge parts with the same value of the expr. It also requires the parts to be in the same partition. Block insertion will also split into the finest granule based on all partition exprs. The `WHERE` clause presents the effectiveness of a partition expr. We can select parts to replace using the expr directly, as shown in the example.

The partition expr requires to be monotonic. If there are any selected parts containing more than one value of the expr. The alter command will fail with informative error messages.

The name `expr` is used for now. Other names might be `identifier`, `tag` or `rule`. Any suggestions are very much appreciated.

**Comment by filimonov** [comment]
Whats about assigning block numbers vs merges?

Now merges happen only on sequence of parts with no 'holes' in block numbering. 

Imagine situation when 2 inserts will deliver data to 3 subpartitions (last minute, last 10 minutes, last hour) in dayly partitioning. 

20210104_0_0 - first insert, last minute data
20210104_1_1 - first insert, last 10 min data
20210104_2_2 - first insert, last hour data
20210104_3_3 - second insert, last minute data
20210104_4_4 - second insert, last 10 min data
20210104_5_5 - second insert, last hour data

So now we somehow need to merge blocks 0 and 3, 1 and 4, 2 and 5.

**Comment by filimonov** [comment]
Check also:

https://github.com/ClickHouse/ClickHouse/issues/13826 - quite simple building block to do self-made multipartitioning (several tables with different partitioning, engine=Merge on top of them, and moving data manually with ATTACH PARTITION). 

https://github.com/ClickHouse/ClickHouse/issues/8089 - refer to REORGANIZE PARTITIONS existing in MySQL 

FR requesting the same thing:
https://github.com/ClickHouse/ClickHouse/issues/12436 
https://github.com/ClickHouse/ClickHouse/issues/16565
https://github.com/ClickHouse/ClickHouse/issues/17623#issuecomment-738809030

That partitioning is also more backup-friendly (limits operations on the data at rest).
https://github.com/ClickHouse/ClickHouse/issues/8841#issuecomment-578731703

**Comment by amosbird** [comment]
It's non-trivial to manipulate partitions for insertion, however it's possible to modify existing partitions.

I've implemented the following:

```
ALTER TABLE REPLACE PARTITION <expr> UPDATE <expr_to_modify_partition_keys> WHERE <filter_to_select_other_partitions>
```

**Comment by filimonov** [comment]
> It's non-trivial to manipulate partitions for insertion, however it's possible to modify existing partitions.

Yep, that idea sounds very similar to #13826. 

So for example you first insert data into the minute partition. 

When the minute ends minute partition gets attached/mutated to an hourly partition.
When the hour ends hourly partition gets attached/mutated to a daily partition, etc. 

If some obsolete insert comes it directly write to the corresponding hourly/daily partition, bypassing the minute partitions. 

Smth like that should be doable, I think.

**Comment by olegkv** [comment]
Just my 2 cents:
It seems much easier to understand and likely, implement such an idea, if partition expressions just put limits on number of partitions of each type.
So, instead of:
alter table x add partition expr hourly toStartOfHour(dt) where toDate(dt) >= today() - 3 days
this seems much easier:
create table partition by toYYYYMMDD(date) LIMIT 10, toYYYYMM(date) LIMIT 6, toYYYY(date)
so, any new inserts always use first expression for partitioning,
but background process checks limits and if number of partitions at first level becomes higher than first limit, it merges them with larger partitions which use second expression. If number of second level partitions becomes to high, they got merged into next level and so on.

**Comment by filimonov** [comment]
One more - a bit opposite, but very popular usecase. 

We want to have realtime inserts (so we need to insert into a single partition w/o fan out to hundreds of partitions) but when parts get bigger we want to partition it by something like (tenant_id, month)

**Comment by siradjev** [comment]
@amosbird , some 2 cents. 
the name may be misleading, as "subpartition" are usually subset of partition in generic DB terminology (e.g. partition by date, subpartition by tenant). Since clickhouse allows partition by multiple keys already, and allows partition pruning on individual column predicates, classic subpartitioning is something that is already part of clickhouse. 
 
I believe "hybrid partitioning" or "mixed partitioning" may be better naming for the improvement. 
There may be several issues with proposed design:
- conflicting expressions (choose first?)
- since in most cases for lambda arch, it would be about timestamp of data, it may be simpler to have default partitioning + support different partitionings with TTL? (e.g. default hourly, after 3 days - monthly, or reverse default none - after 3 days fan out to tenantgroups+months)

**Comment by alexey-milovidov** [comment]
Subpartitioning is difficult to implement.
