### ISSUE TITLE
what kind of optimization interpreter CK used? cost-based or rule-based?

### ISSUE THREAD

**Issue by tenderisthenightGM** [ClickHouse/ClickHouse#18810]

**Comment by alexey-milovidov** [comment]
Mostly rule-based. Also simple cost-based for one case ("move-to-prewhere" optimization).
Also optimization with bayesian bandits for lz4 decompression and for some functions dispatch.

**Comment by tenderisthenightGM** [comment]
Thanks, but could you please tell me why it did not introduce the cost-base optimizer likes GPDB or Spark.

**Comment by den-crane** [comment]
@tenderisthenightGM
1. because mostly CBO is needed for choosing of the most efficient access path: indexes / joins (choosing what type of join to use. Right now CH does not support inverted indexes and supports mostly only HJ. So the access path is straightforward and does not require even RBO.

2. there are tons of more important tasks.

**Comment by tenderisthenightGM** [comment]
@den-crane Thanks very much.
