### ISSUE TITLE
<Error> void DB::AsynchronousMetrics::run(): Code: 173, e.displayText() = DB::ErrnoException: Cannot get vmmap info, errno: 1, strerror: Operation not permitted

### ISSUE THREAD

**Issue by headhu** [ClickHouse/ClickHouse#18882]
I installed latest available version of CH on freebsd and when starting I get the following error

<Error> void DB::AsynchronousMetrics::run(): Code: 173, e.displayText() = DB::ErrnoException: Cannot get vmmap info, errno: 1, strerror: Operation not permitted

I am getting the same error when installing from ports and from pkg

FreeBSD 12.2-RELEASE-p1
ClickHouse server version 20.7.2.30

I feel inside that this has something to do with folder permissions, but my data folder has correct perms

**Expected behavior**
no error displaying?

**Comment by headhu** [comment]
It was improper setting of sysctl on my server, to be specific I had set
hw.kbd.keymap_restrict_change=4 (should be 0)

**Comment by feld** [comment]
I hit this same issue on FreeBSD but it had nothing to do with `hw.kbd.keymap_restrict_change` and I'm unsure how that would be possible anyway.

My issue was due to running Clickhouse in a FreeBSD jail and I had `securelevel=2`. You need to set `securelevel=0` to permit Clickhouse to run in a jail.
