### ISSUE TITLE
RBAC: Stored Object Access Control / DEFINER / SQL SECURITY

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#19228]
Typical examples:
* give the user access to the VIEW without giving access to the main table
* allow the user to insert into the table even if he doesn't have explicit permission to insert into some of the MV

(you can think of more - with all sorts of dictionaries, engine = Merge, Distributed, etc.)

See also:
* https://dev.mysql.com/doc/refman/8.0/en/stored-objects-security.html
* https://docs.oracle.com/cd/E17952_01/mysql-5.7-en/stored-objects-security.html

**Comment by aadant** [comment]
@alexey-milovidov  : not sure why this was not considered as a long term improvement. Granting access through a view (via a definer) allows for finer access control. MySQL did not implement row policies (they still should, Oracle has that for years !) but because of this feature, they could grant access to views without disclosing the underlying tables.

**Comment by alexey-milovidov** [comment]
This task starts to be relevant with the introduction of parameterized views.

**Comment by Algunenano** [comment]
Reverting because it needs a way to safely upgrade. Please resend with it
