### ISSUE TITLE
RFC: different priorities for different ClickHouse users ?

### ISSUE THREAD

**Issue by bharatnc** [ClickHouse/ClickHouse#19388]
As far as I have seen, I don't think ClickHouse has very fine grained control of determining which user get's more priority or which one get's lesser priority while interacting with the database though queries. Closest reference that I could actually find regarding any work that is being planned this year relating to this is the `WorkLoad Management` section in #17623.  Though I might be wrong. But I' anyway going to continue to explain the use case that I have on my mind.

I'm aiming this issue be a beginning or a RFC or a exploratory conversation. 

To put this feature in context, many times, we have seen a lot of user intensive queries by many analysts hog entire ClickHouse clusters concurrently affecting production workloads. In such scenarios, if there was a way to set different priorities for production_service_users, and analyst_users, then the queries initiated by our production services could be prioritized and the queries from the analyst_users can be penalized or set to a lower priority.  

I am not sure what would be the best way to go about doing this or not sure if this can even be done from an architectural perspective but perhaps this could be implemented in ClickHouse using the [ioprio_set ](https://man7.org/linux/man-pages/man2/ioprio_get.2.html) functions that Linux provides. 

@alexey-milovidov @filimonov just ccing. Would be interested to explore and contribute if:

- this sounds like a good idea
- provided this doesn't yet exist inside CH (which I think doesn't)

Thank you in advance!

**Comment by filimonov** [comment]
there is a setting currently called `os_thread_priority` which adjust process niceness. 
1) When you adjust the niceness it also adjusts io priority
2) It's only CFQ scheduler that supports the io priorities. 

Due to the above the importance of that feature is questionable, while there are potential use cases for that feature (mostly it's about decreasing the IO priorities w/o decreasing CPU priorities - for example long-running low priority exports to file tasks). 

Please see https://github.com/ClickHouse/ClickHouse/pull/12076#issuecomment-656046350

If you want we can make the build from that PR, and test that feature (to confirm with real numbers / use cases that it has some advantages against `os_thread_priority`)  - after that it can be accepted (we don't want to accept it blindly, because it's not clear if it introduces some visible advantages).

**Comment by bharatnc** [comment]
Thank you for your reply @filimonov . 

>  test that feature (to confirm with real numbers / use cases that it has some advantages against os_thread_priority)

That would be great. I'm eager to help test your PR. Let me know how you would like me to help.

**Comment by alexey-milovidov** [comment]
I've checked: the `os_thread_priority` works perfectly.
