### ISSUE TITLE
the execute method in the ITableFunction.cpp file is called twice when a sentence of sql is executed

### ISSUE THREAD

**Issue by yinpeng1993** [ClickHouse/ClickHouse#19560]
I find a problem by reading the code, which is that  execute is called twice in ITableFunction.cpp.
First, the joined_tables.getLeftTableStorage() method on line 306 of the InterpreterSelectQuery.cpp file
Second, the joined_tables.resolveTables() method on line 318 of the InterpreterSelectQuery.cpp file
Both methods internally call the executeTableFunction method in the Context.cpp file。

Is there no problem here？

**Comment by tavplubix** [comment]
Please take a look into `Context::executeTableFunction(...)`:

https://github.com/ClickHouse/ClickHouse/blob/813b2bcc7334672889bda8c148c324a28a126c98/src/Interpreters/Context.cpp#L994-L1011

There is no problem, `ITableFunction::execute(...)` is actually called once due to `table_function_results` cache.

**Comment by yinpeng1993** [comment]
Okay, thank you so much, I found the relevant code
