### ISSUE TITLE
Nobody can use the data from ClickHouse's Prometheus exporter... because of a simple invalid escape sequence \' 😭

### ISSUE THREAD

**Issue by fzyzcjy** [ClickHouse/ClickHouse#19883]
**Describe the bug**
Hi thanks for the lib! However, nobody can use the data from ClickHouse's Prometheus exporter... because of a simple invalid escape sequence `\'` :(

More details:

The `/metrics` endpoint does provide Prometheus-compatible data. However, some lines look like the following:

```
...
# HELP ClickHouseProfileEvents_Seek Number of times the \'lseek\' function was called.
...
```

Notice the `\'`. According to the official Prometheus format parser, this is ***invalid***. Thus, the data are rejected by Prometheus or similar services like MetricBeat in Elastic Stack.

**Does it reproduce on recent release?**
Yes!

**How to reproduce**
* Which ClickHouse server version to use 20.12.4.5
* Which interface to use, if matters N/A
* Non-default settings, if any: open the Prometheus metrics
* `CREATE TABLE` statements for all tables involved N/A
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary N/A
* Queries to run that lead to unexpected result: N/S

**Expected behavior**
Should not have `\'`

**Error message and/or stacktrace**
N/A

**Additional context**
N/A

**Comment by alexey-milovidov** [comment]
This issue is relevant in 20.12 but it is fixed in 21.1.

> Does it reproduce on recent release?

The latest release is 21.1.

**Comment by fzyzcjy** [comment]
Aha, sounds great!

P.S. Do you suggest using 21.1 - is it stable enough?

**Comment by alexey-milovidov** [comment]
Version 21.1 was release to stable on Jan 18. It was in prestable (staging) since Dec 10 and we have fixed all the issues that were found during that month: #17951

Please read the changelog in "backward incompatible changes" - there are a few: https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#backward-incompatible-change

Also we are preparing the first patch release for version 21.1 (21.1.3) that will be released this week. It will contain at least the following patches:

Backport #19218 to 21.1: Update Dragonbox
Backport #19237 to 21.1: Don't wait forever for log update after tabl…
Backport #18446 to 21.1: Fix constant folding when the result is unknown
Backport #19316 to 21.1: Refactor now64
Backport #19383 to 21.1: Fix buffer overflow in Uber H3
Backport #19322 to 21.1: Fix segfault on aggregation when MV has unex…
Backport #19072 to 21.1: Fix checkpoint in PeekableReadBuffer over Co…
Backport #19397 to 21.1: Fix MSan report in AES functions
Backport #19354 to 21.1: Function accurateCastOrNull fixed unitialize…
Backport #19472 to 21.1: Fix buffer overflow in DateLUT
Backport #19443 to 21.1: Addition to #15537
Backport #19572 to 21.1: Fix DROP TABLE ON CLUSTER SYNC hang with Ato…
Backport #19571 to 21.1: Query CREATE DICTIONARY id expression fix
Backport #19672 to 21.1: Remove old code for BigInt.
Backport #19713 to 21.1: RoaringBitmapWithSmallSet rb_andnot fix
Backport #19788 to 21.1: Fix trivial bug in arrayEnumerateUniq
Backport #19773 to 21.1: Fix stack overflow in FieldVisitorAccurateEq…

Most of them addresses issues that were also present in versions before 21.1.

**Comment by fzyzcjy** [comment]
@Alex-Burmak Thanks for the info! So IMHO I should (1) look at those incompatible changes (2) wait a bit for 21.1.3?

**Comment by alexey-milovidov** [comment]
> (1) look at those incompatible changes

Yes, this is necessarily.

> (2) wait a bit for 21.1.3

Most likely no. There are no regressions in 21.1 comparing to 20.12 (in the list above).

**Comment by fzyzcjy** [comment]
@alexey-milovidov Thanks!

**Comment by vdimir** [comment]
Dup https://github.com/ClickHouse/ClickHouse/issues/10571
