### ISSUE TITLE
Will the data be cached when clickhouse-benchmark tool is used for multiple queries?

### ISSUE THREAD

**Issue by nautaa** [ClickHouse/ClickHouse#19943]
Like `select * from table`,`select count(*) from table `

**Comment by den-crane** [comment]
yes, 

`select count(*) from table ` -- uses optimization and reads in-memory parts structure.

--optimize_trivial_count_query arg                               Process trivial 'SELECT count() FROM table' query from metadata.

`select * from table` -- also cached because CH relays on Linux file cache and does not control it.
but you can use 
--min_bytes_to_use_direct_io arg                                 The minimum number of bytes for reading the data with O_DIRECT option during SELECT queries execution. 0 - disabled.

So you can try

```
create table table10kRows(A Int64) Engine =MergeTree() order by A;
insert into table10kRows select number from numbers(10000);

clickhouse-benchmark -c 16 --database=default <<< 'select count() from table10kRows'
QPS: 4983.314


clickhouse-benchmark -c 16 --optimize_trivial_count_query=0 --database=default <<< 'select count() from table10kRows' 
QPS: 10597.303

clickhouse-benchmark -c 16 --optimize_trivial_count_query=0 --min_bytes_to_use_direct_io=1 --database=default <<< 'select count() from table10kRows'
QPS: 11212.843
```

funny that optimize_trivial_count_query=0 gives a boost, probably it's only for a small tables.

**Comment by nautaa** [comment]
So if I don't want to use the cache for testing disk io, can I use it `--optimize_trivial_count_query=0 --min_bytes_to_use_direct_io=1`, and why it is faster? @den-crane

**Comment by den-crane** [comment]
>So if I don't want to use the cache for testing disk io, 
>can I use it --optimize_trivial_count_query=0 --min_bytes_to_use_direct_io=1

Yes.

>and why it is faster?

It's only for my test. 
Because of my hardware + table table10kRows is too small.
