### ISSUE TITLE
How to know a table is in readonly mode with a script to lookup?

### ISSUE THREAD

**Issue by ahutsunshine** [ClickHouse/ClickHouse#20014]
Case: We want to mark the replica disable before ingesting data if the replica table is in a readonly mode.

Question: 
1. What situations can cause the readonly?
- Network issue which causes session expired
- No meatadata in Zookeeper
The above two is what I can see. Glad to know other situations.
2. How can we know the table is in readonly mode with a script to lookup? In other words, what's the mark for readonly table?
3. How can we reproduce the readonly issue manually and easily?

**Comment by ahutsunshine** [comment]
My solution:
Use the below sql to discovery the readonly table. Is that correct and enough?
```
select database, table, replica_name, replica_path from system.replicas where is_readonly
```

**Comment by den-crane** [comment]
1. yes. these all cases (  Network issue  / ZK xid overflow - ZK restart /  No meatadata in Zookeeper)
2. correct ` from system.replicas where is_readonly`
3. attach table with non-existent ZK path 
```sql

attach table test123 (a Int64) Engine=ReplicatedMergeTree('/clickhouse/test123qq', '{replica}') order by tuple();


SELECT
    database,
    table,
    replica_name,
    replica_path
FROM system.replicas
WHERE is_readonly

┌─database─┬─table───┬─replica_name─┬─replica_path──────────────────────────┐
│ dw       │ test123 │ sde894       │ /clickhouse/test123qq/replicas/sde894 │
└──────────┴─────────┴──────────────┴───────────────────────────────────────┘

detach table test123;
```

**Comment by ahutsunshine** [comment]
@den-crane Thank you for your great answer. If I have created multiple ReplicatedMergeTree tables in the clickhouse cluster, do you have a way to make one of the tables as readonly mode rather than all tables?

**Comment by chandrabhushansingh16** [comment]
Hi @den-crane 
How to solve incase all the replica turned into read-only?

**Comment by chandrabhushansingh16** [comment]
Hi all
Following is my Clickhouse details
clickhouse-server: 20.12.4 revision 54442 
Number of replicas: 2
Number of shards : 2

I am facing a problem in which Clickhouse frequently turns into read-only mode. It happens for both the instances of Clickhouse

Following workaround does not work:
 1. sudo -u clickhouse touch /var/lib/clickhouse/flags/force_restore_data
 2. Restart the server

system.replicas table shows "is_readonly" flag true.

How I can remove the is_readonly = 1 to 0 , so that insertion in table can work as usual.
Or if there is any way to make the tables writable.

Thanks

cc @den-crane
