### ISSUE TITLE
Does insert_distributed_sync set to 1 have some negative effects?

### ISSUE THREAD

**Issue by gubinjie** [ClickHouse/ClickHouse#20053]
When we insert a distributed table and query the quantity immediately, it may be because the insertion of the distributed table is asynchronous, resulting in inaccurate query data volume, so we set insert_distributed_sync to 1, we want to ask if there are some negative aspects to setting it to 1 Impact.

**Comment by hexiaoting** [comment]
It will be slower.

**Comment by gubinjie** [comment]
Will there be some unexpected bugs

**Comment by alexey-milovidov** [comment]
There are no known bugs with this setting in the release 21.1.

`insert_distributed_sync = 1` has the following advantages:
- data is available to SELECT from replica immediately;
- if all replicas are unavailable, you get the error instead of buffering data on local filesystem;
- better resource usage due to less data copying;
- no risk of data loss when server with Distributed table will fail;

`insert_distributed_sync = 1` has the following disadvantages:
- when there are large number of shards (in order of 100), the latency of INSERT will increase significantly;
- when there are large number of shards (in order of 100), synchronous INSERT will be less reliable, you will have more transient errors;
- does not work if `insert_quorum` is set but `insert_quorum_parallel` is disabled;
- it does not batch large number of small INSERTs - every INSERT goes to the shards immediately;

**Comment by gubinjie** [comment]
@alexey-milovidov
  Does this sentence "have more transient errors" cause data loss

**Comment by alexey-milovidov** [comment]
In case of any error you will get exception in your client - that means - you need to retry the INSERT query again.
If INSERT query succeeded - then data was successfully written to replica.

Only if you do something really wrong, e.g. run INSERT query and don't look at its result - you will lose the data.
