### ISSUE TITLE
Current recommendations around partition size?

### ISSUE THREAD

**Issue by mzealey** [ClickHouse/ClickHouse#20188]
We have two MergeTree tables looking like:

```
CREATE TABLE logs (
    time DateTime64(3) CODEC(DoubleDelta, ZSTD(1)),
    ...
) ENGINE = MergeTree()
PARTITION BY toStartOfInterval(time, INTERVAL 1 HOUR)
PRIMARY KEY (cust id, some other cols, toDateTime(time))
```

these get roughly 2b and 8b rows/day into them respectively.

We typically want quite short-range queries (eg past hour or so) but on occasion want to do scans over month- or year- long periods. Is it best to use hour-long partitions for this as at present (but this means many partitions over the course of a year), or to use day partitioning, however this probably makes most of our queries slower as they have to scan the whole day? What are the current downsides of having many partitions with the ATOMIC engine?

**Comment by den-crane** [comment]
CH recommends monthly (toYYYYMM) partitioning.

With hourly partitioning you'll have (24*365) 8760 partitions per year, and > 10000 parts.
Your queries (over month/year) will be slowed down because they need to read many partitions.
CH start will take some time (could be hours for HDD , need to read each part metadata).
If you use replicated tables then you need to configure ZK -Djut to be able to handle big transactions otherwise alters of this table will be impossible.

I recommend to consider/test this:
```
PARTITION BY toDate(time) -- or toYYYYMM(time) 
PRIMARY KEY (toStartOfHour(time), cust id, some other cols)
```

**Comment by filimonov** [comment]
Optimal
partition size is between few gigs and 150 Gb. 
partition in a single table - hundreds.

So if you collect 150 Gb of data per hour and you data retention is limited to couple of days then you can keep hourly.
