### ISSUE TITLE
Exposing AggregateFunction types in the client libraries.

### ISSUE THREAD

**Issue by fpacifici** [ClickHouse/ClickHouse#20216]
Hi,
a question about AggregationFunctions and AggregatingMergeTree. 
We really like them at Sentry, and we use to build rollup into materialized views very often. 
Is there any plan to expose the aggregation function in the client libraries to allow a client to build an aggregation state and inserting it? 
I am thinking about this use case: being able to produce a uniqState or a quantileState in a data ingestion pipeline early on, close to the clients and being able to insert the states themselves into an AggregatingMergeTree? 
This instead of preserving each individual data points up to Clickhouse, inserting each individual point in a raw table and materialize the aggregation state into an Aggregating Merge Tree.

Also is there any plan to ever support custom aggregation functions as some sort of extensions or plugins ?

Thanks
Filippo

**Comment by filimonov** [comment]
Aggregation function states internally just store some structures the most suitable to store correct & the most compact form of function state (because states are passed between clickhouse nodes during distributed queries).  

Every aggregate function uses its own structures, very context-specific.

So client libraries actually can reverse engineer the used format using clickhouse sources and add support for those functions. It's quite complicated and not sure if there is a easy way for that.

Maybe something more portable could be used for state serialization (like Protobuf with published schemas), but migration may be very problematic (due to compatibility issues), and anyway - even if you will be able to split the binary into some structures easy way you will need to apply sometimes relatively complex algorithms to make some sense to that numbers (or to create that). 

P.S. Do you know some enthusiasts who want to reimplement clickhouse aggregate function state in golang / python / java etc.?

**Comment by fpacifici** [comment]
Hi, thanks for the reply. This is appreciated.

I see the issue with backward compatibility of the schema. Assuming you are talking about that when mentioning the challenges around migrations. Out of curiosity, how do you handle breaking changes on the aggregation state structure on existing aggregating merge trees? Are aggregation states structures always backward compatible between versions or does clickhouse provide migration logic for existing aggregating merge trees ?

> So client libraries actually can reverse engineer the used format using clickhouse sources and add support for those functions.

I actually tried for uniqState :D .  Complexity aside, I think the biggest challenge is maintaining such solution as aggregation states are internal implementation details. I believe they may change in a non backward compatible way in the future.

> Do you know some enthusiasts who want to reimplement clickhouse aggregate function state in golang / python / java etc.?

I think we could help with python and rust. But most likely we would just wrapping the C++ implementation as the Apache Datasketches project does rather than rewriting the aggregation functions from scratch.

**Comment by alexey-milovidov** [comment]
Sometimes we have to change the internal representation of aggregation states.
We are going to add some means for compatibility: https://github.com/ClickHouse/ClickHouse/issues/12552

But it will be only one way compatibility: ClickHouse will be able to read older states of aggregate functions. But it will not serialize the states with old format for old clients.

**Comment by alexey-milovidov** [comment]
So, if you can construct binary format of aggregate function state by hand and pass it to ClickHouse - it is fine.

I don't know any libraries that are doing that.
