### ISSUE TITLE
Clickhouse Kafka consumer - "Exactly once semantic"

### ISSUE THREAD

**Issue by YordanPavlov** [ClickHouse/ClickHouse#20285]
Is there a way to make a Clickhouse Kafka stream table to consume messages using transactions - so called "exactly once semantic". I have already implemented needed changes on producer side.

Thank you!.

**Comment by filimonov** [comment]
EOS consumer (isolation.level=read_committed) is enabled by default since librdkafka 1.2.0, so for clickhouse - since 20.2

See 
* https://github.com/edenhill/librdkafka/commit/6b2a1552ac2a4ea09d915015183f268dd2df96e6
* https://github.com/ClickHouse/ClickHouse/pull/9000/commits/9de5dffb5c97eb93545ae25eaf87ec195a590148

There was a report recently that it was giving some duplicates https://github.com/ClickHouse/ClickHouse/issues/18668 and in should be fixed in 21.2. 

BUT: while EOS semantics will guarantee you that no duplicates will happen on the Kafka side (i.e. even if you produce the same messages few times it will be consumed once), but ClickHouse as a kafka client can currently guarantee only at-least-once. And in some corner cases (connection lost etc) you can get duplicates.

We need to have something like transactions on clickhouse side to be able to avoid that. Adding something like simple transactions is in plans for Y2021.
