### ISSUE TITLE
How to get the part directory generated by an insert query?

### ISSUE THREAD

**Issue by Qsimple** [ClickHouse/ClickHouse#20877]
Dear team:
   Sometimes we want to know the part directory generated by an insert query for rollback the insert request. How can we do this? 
   Check all issues, never meet an matched issues. Hope your reply, tks

**Comment by den-crane** [comment]
You cannot intervene in a table on a directory level. I
t will break a table because a list of directories with parts is stored in CH-server memory. 
Moreover your last insert can be merged right after insert.

You need to use atomic inserts. Use search in this repo to get the ideas how to insert atomically.
