### ISSUE TITLE
process has no CAP_IPC_LOCK capability, binary mlock will be disabled

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#21617]
2021.03.11 13:43:14.558479 [ 1 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.

**Comment by alexey-milovidov** [comment]
The message is correct.

**Comment by filimonov** [comment]
> binary mlock will be disabled

binary mlock = put whole clickhouse binary in ram and forbid paging.

To be enabled the Linux capability CAP_IPC_LOCK is needed. (The log message is relevant and help you to fix the issue).

When you don't have such a capability the feature can not be enabled, that potentially may to less stable performance due to paging of the execuatable. That is the only side-effect.
