### ISSUE TITLE
Why not use `mutations_sync` to control synchronicity in `StorageReplcatedMergeTree::alter`

### ISSUE THREAD

**Issue by spongedu** [ClickHouse/ClickHouse#21821]
When executing `ALTER TABLE` operation on `ReplicatedMergeTree`,  why we use `replication_alter_partitions_sync` instead of `mutations_sync` to control the synchronicity  when wait mutations to finish ? Saying following line:  

https://github.com/ClickHouse/ClickHouse/blob/d02726bcac071d63fb7811e4e3d454da43f8a589/src/Storages/StorageReplicatedMergeTree.cpp#L4601

**Comment by filimonov** [comment]
Historical reasons:
replication_alter_partitions_sync
was exists long before mutations were added. 

https://github.com/ClickHouse/ClickHouse/commit/d3664eac890691f06068459d57895550f70aaefe

**Comment by spongedu** [comment]
@filimonov  Do we have plan to make a change here ?

**Comment by alesapin** [comment]
From my point of view, it's clear from the documentation that `replication_alter_partitions_sync` control the synchronization of alters: https://clickhouse.com/docs/en/operations/settings/settings/#replication-alter-partitions-sync. I agree that the name of the setting is strange, but it's hard to change it because it would be a backward incompatible change.
