### ISSUE TITLE
[Question] Parallel execution of subqueries

### ISSUE THREAD

**Issue by zhoudehui** [ClickHouse/ClickHouse#2203]
If we have a query Q like:

```sql

select 
  c1, 
  c2,
  c3 / c4 
from 
  ( select  c1,
                c2,
                count() as c3
    from T1
    where ...
    group by c1, c2
  )
  ALL LEFT JOIN
  ( select c1, 
               c2,
               count() as c4
    from T2
    where ...
    group by c1, c2
  ) 
  USING (c1, c2)
```
T1 and T2 are distributed tables with merge tree engine, will Clickhouse execute those two sub queries   in parallel and then join the  subquery results?  In our test settings, they seems execute sequentially. just want to check if there are any settings to control this behavior.  

Thanks.

**Comment by alexey-milovidov** [comment]
No.

The reason is that the "left" subquery is not buffered in memory. It is processed in a streaming fashion with lookups in the right table. That's why we have to first make a lookup-optimized data structure for "right" subquery and then proceed with streaming reading and joining of the "left" subquery. It allows to save memory when "left" subquery is going to produce huge resultset.

**Comment by zhoudehui** [comment]
> No.
> 
> The reason is that the "left" subquery is not buffered in memory. It is processed in a streaming fashion with lookups in the right table. That's why we have to first make a lookup-optimized data structure for the "right" subquery and then proceed with streaming reading and joining of the "left" subquery. It allows to save memory when the "left" subquery is going to produce huge resultset.

Thanks Alex.
