### ISSUE TITLE
Explicit secret management in ClickHouse

### ISSUE THREAD

**Issue by Enmk** [ClickHouse/ClickHouse#22471]
**Use case**
Passwords/connection data scattered in different parts of the system is difficult/impossible to reuse in other contexts, which is why the same connection data can appear repeatedly in different places.

E.g. if the MySQL server connection password ever changes, you will have to recreate tables with the MySQL engine, rewrite selections using the MySQL table function, dictionaries using the same connection, etc. 

And it is extremely hard to avoid leaking such secrets to just about any database user.

**Describe the solution you'd like**
Develop a secret management API in clickhouse, so the secrets can be provided\managed from outside of CH and don't have to be explicitly typed in.

E.g. add a new function in ClickHouse's SQL dialect:
```
secret('secret_name')
```
This way the secret itself doesn't leak to the query log or doesn't even need to be known by the client. It is easy to reuse and change if required.

Each secret is managed by some backend, with controls secret acquisition from external (or internal source), its lifetime, refresh rate, etc.

### Examples:
```sql
SELECT encrypt('aes-256-cfb128',  'plaintext to encrypt', secret('mysecret'));
SELECT * FROM mysql('localhost:3306', 'test', 'test', secret('mysql_localhost_user'), secret('mysql_localhost_password'));
```

Where `mysecret` is a name that is resolved to a secret value at run-time.

There could be many backends that manage the secrets: in-memory plaintext, server-key based (just like in #22423), (Hashicorp vault)[https://www.vaultproject.io/] or anything else that provides a reasonable API.

Of course, all of those backends have to be developed separately or used via some generic HTTP-API.

### Configuration example
Given that we have implemented 3 backends: plaintext, server-key-derivation based backend and hashicorp-vault-based one, we may have the following configuration:
```
<secrets>
    <!-- plaintext secret, accessible by name `literal_password` -->
    <literal_password>this is the password</literal_password>

    <!-- server-key-derivation-based secret, accessible by name `server_key_32` -->
    <server_key_32>
        <secret_backend>server_key_provider</secret_backend>
        <server_key_provider>
            <key_bytes>32</key_bytes>
        </server_key_provider>
    </server_key_32>

    <!-- hashicorp-vault-managed secret, accessible by name `external_secret` -->
    <external_secret>
        <secret_backend>hashicorp_vault</secret_backend>
        <hashicorp_vault>
            <token>blah-blah</token>
            <namespace>blah-blah</namespace>
            <vault_host>some url</vault_host>
            <secret_name>some secret name</secret_name>
        </hashicorp_vault>
        <!-- generic options, like lifetime or renewing period -->
    </external_secret>
</secrets>
```

Where `<secret_backend>backend_name</secret_backend>` section controls which backed is going to be used, and the corresponding config section describes particular settings of the backend.

**Additional context**
Possible future extension points:
* `SYSTEM RESET SECRET 'secret_name';`
* `SYSTEM RESET ALL SECRETS;`
* Access management for the secrets: `GRANT / REVOKE SECRET`

**Comment by qoega** [comment]
It useful to add secret to a vault from SQL.

**Comment by filimonov** [comment]
Alexey Milovidov, [04/02/21 01:10]
Everything is fine - this is exactly what we need! And it shouldn't be hard.

Let's make a config as one of the (first) backend. And the names of the secrets will be as paths to the elements through a dot. Will already cover a bunch of cases at the start.

```
<vault>
 <a>
  <b>
```
`secret('a.b')`

Mikhail Filimonov, [02.04.21 09:18]
So treelike and any depth? With flat structure, you can also write the same thing (common prefix), but the tree is also ok.

What if, given this structure, the user asks for "a"? i.e. "folder" with  "subfolders"?

Alexey Milovidov, [02.04.21 09:19]
Exception.

Mikhail Filimonov, [02.04.21 09:19]
Well, then (if we go out of considerations that some secrets require strange initialization at startup), it will be necessary to traverse the tree, not the list.

Alexey Milovidov, [02.04.21 09:20]
This is so that you can group credentials, take out all the connection settings - user, password, host - so that the user does not have to enter them.

Mikhail Filimonov, [02.04.21 09:24]
Hmm. Looking at how it is done, for example, in the hashcorp vault, they have many subkeys for such use cases inside one "logical" secret.

But probably the option "tree-like and dot in secret name" and access to separate "sub-elements" of the secret as to separate secrets - is fine too.

By the way, it will be nice to add the ability to use these secrets later inside the xml configuration too (similar to substitutions file), smth like  
```xml
 <password incl_from_vault="mysql.server1.password">
```

**Comment by dbug-river** [comment]
any plans on this being implemented please?

**Comment by alexey-milovidov** [comment]
Duplicate of #28367
