### ISSUE TITLE
2 almost identical queries but one takes much longer.

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#22481]
These are 2 almost identical queries but query1 takes much longer.

Any idea about why this happens?

(*Clickhouse version: 21.3.4.25*)

**Query1**

```sql
SELECT count()
FROM
(
    SELECT num1.number
    FROM numbers(5000000000) AS num1
    ,
    (
        SELECT number
        FROM numbers(1000)
    ) AS num2
    WHERE num1.number = num2.number
)

Query id: 26c01eeb-d56d-42ba-871e-c2bf71570c7e

┌─count()─┐
│    1000 │
└─────────┘

1 rows in set. Elapsed: 36.661 sec. Processed 5.00 billion rows, 40.00 GB (136.39 million rows/s., 1.09 GB/s.)
```

**Query2**
```sql
SELECT count()
FROM
(
    SELECT num1.number
    FROM numbers(5000000000) AS num1
    INNER JOIN numbers(1000) AS num2 ON num1.number = num2.number
)

Query id: b5d00081-f5e4-413c-b91b-8e68ecdd1beb

┌─count()─┐
│    1000 │
└─────────┘

1 rows in set. Elapsed: 22.304 sec. Processed 5.00 billion rows, 40.00 GB (224.18 million rows/s., 1.79 GB/s.)
```

**Comment by l1t1** [comment]
```sql
SELECT count()
FROM
(
    SELECT number
    FROM system.numbers limit 5000000000) AS num1
    INNER JOIN 
(select number from system.numbers limit 1000) AS num2 
ON num1.number = num2.number

Elapsed: 20.810 sec, read 5000063155 rows

SELECT count()
FROM
(
    SELECT number
    FROM system.numbers limit 5000000000) AS num1
where num1.number in (select number from system.numbers limit 1000) AS num2 

Elapsed: 16.399 sec, read 5000063155 rows

```

**Comment by ILYenBui** [comment]
The first one uses comma-separated join, because of the subquery `( SELECT number FROM numbers(1000))` so it first selects out all the data in this subquery. By default, ClickHouse uses the hash join algorithm. It takes the right table - this subquery and creates a hash table for it in RAM without any data filter yet then I will join with the left table based on where condition.

For the second one(direct inner join), the data is filtered by condition (after on) and just process the matched data only(not all the data `from numbers(1000) `need to be loaded into RAM, the only data loaded is data with the number in the left table). This leads to faster performance than the first query.
