### ISSUE TITLE
what is "enabling/disabling compact parts for a table" ,which setting variables should i related to

### ISSUE THREAD

**Issue by chenzhiping007** [ClickHouse/ClickHouse#22974]
what is "enabling/disabling compact parts for a table" ,which setting variables related to

issues related  : https://github.com/ClickHouse/ClickHouse/issues/12408

**Comment by CurtizJ** [comment]
Data parts of `MergeTree`-family tables can be stored on disk in 2 formats: Wide (read optimized) and Compact (write optimized). In Wide format data of each column is stored in one or several files. In Compact format all columns are written to one file: granules are written one by one, while every granule has columnar format (like Apache Parquet or ClickHouse native format). Compact parts require less disk operations than Wide parts and significantly improve performance of small and frequents inserts to tables with many columns (about 4-10 times, depending on number of columns and type of the disk).

There are settings `min_bytes_for_wide_part` and `min_rows_for_wide_part`. If amount of data in new part exceeds one of these thresholds, part will be created in Wide format, otherwise in Compact format. By default `min_bytes_for_wide_part` is set to 10MiB since version 20.10.
