### ISSUE TITLE
Mixed shards with replicas

### ISSUE THREAD

**Issue by undiabler** [ClickHouse/ClickHouse#2305]
I have 3 replica servers. Each of them contains all records. 

My questions are:
- Will I have faster requests if I make 3 shards?
- Can I have on each server 1 shard replicated to other 2 servers?
- How can check if some records was inserted directly or via replica?

**Comment by alexey-milovidov** [comment]
> Will I have faster requests if I make 3 shards?

Heavy queries will be faster and light queries will be slightly slower.

> Can I have on each server 1 shard replicated to other 2 servers?

Yes, it is named "cross-replication" (search for "ClickHouse cross replication"). I don't recommend this configuration because it has higher operational complexity.

> How can check if some records was inserted directly or via replica?

It's almost impossible. But you can find the log of data parts insertion or replication in a `system.part_log` table, which has to be enabled in config.xml (see `<part_log>`).
