### ISSUE TITLE
[Block deduplication] Kafka and block deduplication

### ISSUE THREAD

**Issue by paeolo** [ClickHouse/ClickHouse#23069]
I planned to integrate ClickHouse with Kafka using the `Kafka` Engine. From the [doc](https://clickhouse.tech/docs/en/engines/table-engines/integrations/kafka/#description) the three steps I want to follow are:
>* Use the engine to create a Kafka consumer and consider it a data stream.
>* Create a table with the desired structure.
>* Create a materialized view that converts data from the engine and puts it into a previously created table.

Later we can read:
>Received messages are grouped into blocks the size of **max_insert_block_size**.

>If the block wasn’t formed within **stream_flush_interval_ms milliseconds**, the data will be flushed to the table
>regardless of the completeness of the block.

On the other hand using `ReplicatedMergeTree` Engine we have a data block deduplication feature:
>Data blocks are deduplicated.
>For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once

My questions are: 
* Does this feature interacts with the Kafka scenario described, ie. do we have block deduplication in the scenario described ?
* If so what happens in the case the data is flushed regardless of the completeness of the block ?

To answer the second question let's imagine that for some reason `Kafka` failed to deliver some messages `exactly once` and the first time ClickHouse decided to flush the data to the table regardless of the completeness of the block and the second time the block was complete. If this scenario is possible:

* what happens, is there any duplication here ?
* Can we avoid duplication in this situtation ?

Thanks a lot for your time,
Cheers,

Paul

**Comment by filimonov** [comment]
> Does this feature interacts with the Kafka scenario described, ie. do we have block deduplication in the scenario described?

No, unfortunately not. Due to the possibility of consumer group rebalances it's not always possible to repeat exactly the same block. 

There are some plans to address that issue. Currently, you can try to do inserts via Distributed table, the chances it will fail are lower, and it will do proper retries to push data forward.

> what happens, is there any duplication here ?
> Can we avoid duplication in this situtation ?

engine=Kafka provides a fair 'at least once' guarantee. In corner cases, you will get duplicates. Chances of those duplicates are low, but they are still possible. 

Getting real exactly-once requires rework of current implementation of engine=Kafka.

**Comment by paeolo** [comment]
@filimonov Got it, thanks a lot;)
