### ISSUE TITLE
jemalloc percpu arena with limited CPUs

### ISSUE THREAD

**Issue by maliangzhu** [ClickHouse/ClickHouse#23174]
In ```contrib/jemalloc-cmake/CMakeLists.txt```
I can see
```set (JEMALLOC_CONFIG_MALLOC_CONF "percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:10000")```

I think this is a bug if  don't specifiy ```narenas``` in JEMALLOC_CONFIG_MALLOC_CONF when  ```percpu_arena:percpu``` is specified.

Because in numa mode(e.g. 2cpu,64cores), if we bind to one numa node, jemalloc will only alloc 32 arenas, but threads may be run in 1/3/5/...63, which may greater than 31. jemalloc may lead to some unexpected errors, especially in shared_ptr destructor

**Comment by azat** [comment]
> if we bind to one numa

percpu_arena with limited CPUs to run on has this known issue, but it is not the case for clickhouse since it uses patched version of jemalloc, that as the following patch - 93e27e435cac846028da20cd9b0841fbc9110bd2, which basically ignore CPU limiting and will always use narenas=all-available-cpus (so for you case narenas will be 64)

I send it upstream (https://github.com/jemalloc/jemalloc/pull/1939), but there are some caveats and the patch wasn't accepted.

This may have some minor caveats, since some threads may not be active for a while and may not release memory, but I doubt that this is a problem, since the difference is not that huge (if you compare to arena per thread approach).

Although, if you still care about this, you may use `export MALLOC_CONF=background_thread:true,confirm_conf:true` but for this you need to disable watchdog, i.e. `export CLICKHOUSE_WATCHDOG_ENABLE=0` since watchdog does fork() which will disable `background_thread`

>especially in shared_ptr destructor

Note, that this is consequences it may bail in any place actually.

*P.S. @alexey-milovidov can you adjust the subject to smth like "jemalloc percpu arena with limited CPUs"*
