### ISSUE TITLE
which version support field=value in JOIN ON clause

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/ClickHouse#23214]
my test case is:

`select A.country, B.area from city A inner join city B on A.city=B.city and B.area='south'`

Exception shows: No columns in one of equality side.: While processing B.area = 'south'

I search for the exception in issues and find the same question asked before #18720 and #19685.

Indeed, by using  `select A.country, B.area from city A inner join city B on A.city=B.city where B.area='south'` could solve it, but maybe the performance would be better if putting `B.area='south'` before `where`.

The question is
1. will `on B.area='south'` improve performance for Clickhouse?
2. I test it on V21.1.2.15. do you have any roadmap for supporting this feature? or which version has already implemented the feature?

**Comment by den-crane** [comment]
You can use:
```sql
select A.country, B.area from city A inner join (select * from city where area='south') B on A.city=B.city
```
This is actually CH conventional way, because 3 years ago ON syntax was not implemented yet. And Clickhouse JOIN-rewriter transforms queries with join into this form with subqueries.

**Comment by ILYenBui** [comment]
I am using the version: ┌─version()─┐ 22.3.3.44 and this support area filter after on as the following screenshot as an example: 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/102578911/162599145-11357c1b-99c6-4038-ab09-47d883c1cb4b.png">

To answer your question:
1. `on B.area='south` will help to improve performance coz it helps to filter out and make the processed dataset smaller(if it did).
2. For other database systems and I think the same for ClickHouse when you use inner join, you put filter condition either using on or where the performance will stay the same. It just has a different performance in case you use outer join(left, right join). In those cases, putting filter after Where clause basically will have a better performance rather than putting after on clause. This is because of the outer join, even the condition after on clause is matched or not it still returns entered right/left table.
3. For ClickHouse, as default, the hash join will be used and the right table will be hash and loaded into the RAM, so for the best performance, you should do a filter on subquery before doing join as den-crane mentioned above.
4. You can have a look at the query's execution plan for a more detailed deep dive by typing `explain plan <select statement>.`
