### ISSUE TITLE
I found that when I turn off a replica, the file of zookeeper "/is_active" does not change the state, and the "/is_lost" either.

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#23350]

**Comment by tavplubix** [comment]
Looks like expected behavior. Replica does not become lost if it just turned of, so it's `/is_lost` should not be changed. It's changed only when other replicas consider inactive replica as staled according to its log pointer. As for `/is_active` node, it's ephemeral and it disappears when replica is turned off, but it may happen not immediately and may take from seconds up to 1 minute (depends on ZooKeeper configuration)
