### ISSUE TITLE
The ddl is hang, and the query cant be killed!

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#23482]
version:19.17.4.11

![image](https://user-images.githubusercontent.com/45587738/115666534-480a4380-a377-11eb-985f-3cc15e4494e7.png)

**Comment by Sallery-X** [comment]
And after restart, the ddl still can't work

**Comment by tavplubix** [comment]
> version:19.17.4.11

This version is outdated and no longer supported. [Currently supported stable versions](https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease): 20.8 (lts), 21.2, 21.3 (lts), 21.4, 21.5

There was several issues with hanging DDL queries in old versions, most of them are fixed in newer version.

> the query cant be killed

Yes, there is no way to kill DDL query, `KILL` works for `SELECT`s and `INSERT`s only
