### ISSUE TITLE
Insert to Distributed over MergeTree vs. ReplicatedMergeTree 

### ISSUE THREAD

**Issue by ilejn** [ClickHouse/ClickHouse#23633]
We have a nonsharded table to keep on several boxes probably in several datacenters. 
It seems that there are two approaches

1. A ReplicatedMergeTree
1. Distributed over independent MergeTree tables with internal_replication false. 

What are advantages and disadvantages of each?
According to https://clickhouse.tech/docs/en/engines/table-engines/special/distributed/  second approach "is worse than using replicated tables, because the consistency of replicas is not checked, and over time they will contain slightly different data".
Why?
Doesn't insert_quorum helps here?
Is insert_quorum applicable to ReplicatedMergeTree as well as to Distributed? 

Thanks.

**Comment by den-crane** [comment]
>What are advantages and disadvantages of each?

1. Replication works with issues with large network latency 
  (though I use inter-ocean replication ~250ms, but I keep all zookeeper in one datacenter and insert data only in this DC). 
2. MergeTree tables don't check parts consistency. 


>>slightly different data".
>Why?

Because plain MergeTree tables don't check parts consistency. 
For example eventually the second replica (MergeTree) will lost just inserted data because of a hardware reboot.

MergeTree engine does not have the insert_deduplication feature.
Distributed table repeats insert into underlying tables until success and knows nothing about table partitioning. 
For example eventually a Distributed table will insert into the first replica without a retry, and into the second replica with retry and with small probability will insert duplicates only into only one replica.

**Comment by ilejn** [comment]
@den-crane , thanks for the explanation.
Could you please tell a few more words about parts consistency check.
It is implied that ReplicatedMergeTree performs the check, right? 
What is the nature of the check and what kind of issues does it prevent?

**Comment by den-crane** [comment]
Replication works on parts level. Consistency of parts data are verified by checksums. If a part has incorrect checksum (because of bit-rot, or hardware reboot) then replica downloads the corrupted part from another replica.

Set of parts in general is consistent among replicas because replicas create parts using a single point of truth -- Zookeeper. When a replica process an insert / creates a part it makes a record in ZK about it and other replicas download this part. Merges also are coordinated using ZK. So the result of merges always the same (if checksum of a resulting merge is incorrect then replica do merge-retries and eventually can download the part from other replicas. 
If for some reason (e.g. manual interventions in ZK) a replica does not have some parts then eventually replica will find out it (for example during merges) and will download the missing parts.
