### ISSUE TITLE
OPTIMIZE PARTITION FINAL on replicatedcollapsingmergetree tables

### ISSUE THREAD

**Issue by rpfennin** [ClickHouse/ClickHouse#2379]
i am noticing an issue with trying to merge out records in a replicated collapsing mergetree table, however if i copy the table to a single collapsingmergetree table and then run OPTIMIZE TABLE [tablename] PARTITION '[partition]' FINAL it works as I would expect.  Is there an issue with optimize final in relation to replicated tables?

**Comment by rpfennin** [comment]
Following up on this.  The following code does not do what I would expect (remove all rows):

create table testcp (p date, v Int32, sign Int8) Engine = CollapsingMergeTree(p, v, 8192, sign)

insert into testcp values ('2018-05-16', 33, 1);
insert into testcp values ('2018-05-16', 33, -1);
insert into testcp values ('2018-04-16', 34, 1);
insert into testcp values ('2018-04-16', 34, -1);

optimize table testcp partition 201805 final;
optimize table testcp partition 201804 final;

select * from testcp

results:
2018-04-16	34	1
2018-04-16	34	-1
2018-05-16	33	1
2018-05-16	33	-1

**Comment by alexey-milovidov** [comment]
> Is there an issue with optimize final in relation to replicated tables?

It works in the same way as for non-Replicated tables. You should consider the cost of data processing.

> why is there a difference?

Long time ago there was a limitation that empty parts cannot exist in a table. That's why we have to leave at least a pair of records to avoid creating empty data parts. That's not an issue anymore and your example now works as you expect (data is removed after OPTIMIZE).
