### ISSUE TITLE
bitmap,When the value range becomes larger, the time consumption increases rapidly

### ISSUE THREAD

**Issue by ustcrczhang181** [ClickHouse/ClickHouse#23850]
create table database.table_bit (
wealth_level String,
dt String,
user_id_bit AggregateFunction(groupBitmap, Int64),
user_id_count AggregateFunction(count, Int64)
) ENGINE= AggregatingMergeTree()
ORDER BY (wealth_level)
partition by (dt)
SETTINGS index_granularity=2;

There are six values for field wealth_level, which are '0', '1', '2', '3', '4', and '5'.
The corresponding number of data is about 400 million, 4 million, 4 million, 4 million, 4 million, 4 million.
sql:
select bitmapCardinality(
(select groupBitmapMergeState(user_id_bit)
from database.table_bit
where  wealth_level in ('3','4','5')));

When modifying the value condition of field wealth_level , the corresponding SQL time consumption is:
wealth_level in ('5')                  :0.36s
wealth_level in ('4','5')              :1s 
wealth_level in ('3','4','5')          :1.2s
wealth_level in ('2','3','4','5')      :4.5s
wealth_level in ('1','2','3','4','5')  :4.8s

I'm very puzzled that when the range of values is changed from three to four, the time consumption increases so much(from 1.2s to 4.5).
In my usage scenario, there are many cases with multiple value ranges.

**Comment by ustcrczhang181** [comment]
Well, I have tested some methods myself, and the effective measures are listed below for your reference.
1. change AggregateFunction(groupBitmap, Int64) to AggregateFunction(groupBitmap, UInt32);
2. The original user ID is not continuously increasing, which is relatively scattered. The original user ID is mapped to a new ID increasing from 1.

**Comment by alexey-milovidov** [comment]
Also you may ask why when changing from two to three values, the time changes from 1s to just 1.2s - less that 50%.
Most likely this is because the dependency between time and the amount of data is not strictly linear.

Roaring bitmap is not a simple data structure. There can be some steps in query execution time due to resizes. There can also be some "phase changes" in the data structure depending on the data volume.

I don't see anything paradoxical in these timings.
