### ISSUE TITLE
Dictionaries with 'update_field' use more memory

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#23870]
Tested on 21.6.1.6748
```
name          | type             | bytes_allocated | element_count | source                                 | length(attribute.names)
--------------+------------------+-----------------+---------------+----------------------------------------+------------------------
dict_flat1    | Flat             |        44689464 |        838596 | MySQL: db.table_flat                   |                      11
dict_flat     | Flat             |        55437368 |        838596 | MySQL: db.table_flat + update_field    |                      11

dict_hashed1  | Hashed           |        10865896 |        180240 | MySQL: db.table_hashed                 |                      12
dict_hashed   | Hashed           |        15338728 |        180240 | MySQL: db.table_hashed + update_field  |                      12

dict_complex1 | ComplexKeyHashed |       999847480 |      10450665 | MySQL: db.table_complex                |                      45
dict_complex  | ComplexKeyHashed |      1156085304 |      10450665 | MySQL: db.table_complex + update_field |                      45
```

**Comment by minaevmike** [comment]
Hi, I have faced the same problem. Any updates on this?

**Comment by rsaphala** [comment]
Im having the same issue. It seems that the dictionary is also rebuilt completely despite specifying update_field which causes memory to spike when this process is running

**Comment by rsaphala** [comment]
Any updates on this?

**Comment by azat** [comment]
The problem is in the interface, each update dictionary is re-created from scratch:

https://github.com/ClickHouse/ClickHouse/blob/2703b47d31b59f2a7dff9cfa290a45ad949644b3/src/Interpreters/ExternalLoader.cpp#L1516-L1519

That's why you need to store the whole block in addition to the dictionary (`update_field_loaded_block`), that is passed to the dictionary constructor later.

https://github.com/ClickHouse/ClickHouse/blob/2703b47d31b59f2a7dff9cfa290a45ad949644b3/src/Dictionaries/HashedDictionary.cpp#L51

If you will adjust the interface to call `updateData` instead, then it will be significantly more optimal.
But this will require proper locking which is not good.

**Comment by alexey-milovidov** [comment]
Dictionaries of every family, other than cache, are immutable - it means they have to be copied on update.

**Comment by Slach** [comment]
@SaltTan could you provide CREATE DICTIONARY statements with `update_field` and without `update_field`?
Is more allocations was provided after the first data loading? or after second data loading?
