### ISSUE TITLE
HHMMSSxxxxxxxxx to DateTime64

### ISSUE THREAD

**Issue by kimmolinna** [ClickHouse/ClickHouse#23888]
What is the best way to replace the following code `parseDateTime64BestEffort(concat('20201210',substring(time,1,6),'.',substring(time,7,9)),9) as time`

**Comment by ILYenBui** [comment]
Hi [kimmolinna], Could you please provide more detail such as how does your "time" field looks like? what do you want to achieve so I can help you with the answer? Otherwise, you might want to have a look special datetime cast from a chunk of number for snowflake like this: `SELECT snowflakeToDateTime64(CAST('1426860802823350272', 'Int64'), 'UTC')`
