### ISSUE TITLE
https://gh-api.clickhouse.tech/play?user=play shows UInt64 values (inside Array) as strings

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#23917]
in my computer
```sql
mysql> select [1,2,3] a, sumForEach(a)x,toTypeName(x),toTypeName(a);
+---------+---------+-----------------------------------+-----------------------+
| a       | x       | toTypeName(sumForEach([1, 2, 3])) | toTypeName([1, 2, 3]) |
+---------+---------+-----------------------------------+-----------------------+
| [1,2,3] | [1,2,3] | Array(UInt64)                     | Array(UInt8)          |
+---------+---------+-----------------------------------+-----------------------+
1 row in set (0.00 sec)
```
in the web site, second column shows ["1","2","3"]
select [1,2,3] a, sumForEach(a)x,toTypeName(x),toTypeName(a)

a	x	toTypeName(sumForEach([1, 2, 3]))	toTypeName([1, 2, 3])
[1,2,3]	["1","2","3"]	Array(UInt64)	Array(UInt8)

**Comment by l1t1** [comment]
select [toUInt32(4)] a,[toUInt64(4)]b, [toUInt8(4)]c
returns


a | b | c
-- | -- | --
[4] | ["4"] | [4]

**Comment by l1t1** [comment]
select [toUInt32(4)] a,[toUInt64(4)]b, [toUInt8(4)]c,[toUInt16(4)] d,[toInt128(4)]e, [toUInt256(4)]f
returns

a | b | c | d | e | f
-- | -- | -- | -- | -- | --
[4] | ["4"] | [4] | [4] | ["4"] | ["4"]

**Comment by alexey-milovidov** [comment]
@l1t1 It is a very minor issue, I doubt we should fix it.
The culprit is that basic JavaScript types do not support 64-bit integers (all numbers are double precision floats).

We transfer data into UI in JSON format. JSON format has support for arbitrary numbers. But we also use JSON deserialization routines in JavaScript. And it can mangle 64-bit integer, so we have to pass it in string.

**Comment by alexey-milovidov** [comment]
I prefer to avoid fixing this issue just to keep the code of Web UI simple.
JavaScript programming language is a field where it's too easy to get buried with complexity :)
