### ISSUE TITLE
show estimates (estimated query complexity / parts / marks / rows) 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#23941]
Clickhouse knows before a query execution 
```
Selected 4/4 parts by partition key, 4 parts by primary key, 
126/126 marks by primary key, 126 marks to read from 4 ranges
Reading approx. 1032192 rows with 7 streams
```

I need ability to get these numbers without query execution:

```
show estimates for select count() from table;

┌─parts─┬─marks─┬────rows─┐
│   343 │  1126 │ 1032192 │
└───────┴───────┴─────────┘
```

also it seems they will be helpful in system.processes & system.query_log

**Comment by fastio** [comment]
It's ok like following ?
```
show estimates  database_name.table_name;

┌─parts─┬─marks─┬────rows─┐
│   343 │  1126 │ 1032192 │
└───────┴───────┴─────────┘
```

**Comment by alexey-milovidov** [comment]
It can be a mode of EXPLAIN query.

**Comment by fastio** [comment]
Ok, I'll try it.

**Comment by amosbird** [comment]
> Ok, I'll try it.

Please also take distributed queries into account.

**Comment by fastio** [comment]
> Please also take distributed queries into account.

Sure.

**Comment by alexey-milovidov** [comment]
@filimonov 

Two options exist:
- sum the values across all tables;
- display the values corresponding to every table in separate rows.

**Comment by filimonov** [comment]
> @filimonov
> 
> Two options exist:
> 
> * sum the values across all tables;
> * display the values corresponding to every table in separate rows.

I'm voting for the second one

**Comment by UnamedRus** [comment]
I also would like to see count of ranges. (Probably even marks_id?)
And how much each index/partition by/skip index contributed to amount of read rows.

And if you have some nested query like

```
SELECT * FROM table WHERE id IN (SELECT id FROM table_2 WHERE x = 1)
```

In order to get estimates for each level of sub query, you actually need to execute at least some stages of this query.
Probably you can have some setting like this:

```
EXPLAIN ESTIMATES analyze=1 SELECT ...
```


BTW, we already have quite a lot of explaining columns in query_log (column names / functions) and total amount of read rows.
Probably we can also include rows per table in it.
