### ISSUE TITLE
toDate() and toDateTime() functions work incorrectly

### ISSUE THREAD

**Issue by kraeiri** [ClickHouse/ClickHouse#2420]
Hi, 
we've found that some date functions work incorrectly.
1. toDateXXX function

toDateOrZero('2017-02-10')
actual result: 0000-00-00
expected result: correct date 2017-02-10

toDateOrNull('2017-02-10')
actual result: nan
expected result: 2017-02-10

toDate('2017-10-X0')
actual result: 0000-00-00
expected result:  exception/error

2. toDateTime function

toDateTime('2017-02-10 xx:10:34')
actual result: 2017-02-11 00:10:34
expected result: exception/error

toDateTime('2017-AA-10 xx:10:bb')

actual result: 1970-01-02 00:10:38
expected result: exception/error

**Comment by tru1** [comment]
Vote for this issue

**Comment by nullquery** [comment]
toDate('2028-09-25') = 2028-09-25
toDate('2118-09-25') = 0000-00-00

Why? 😭

**Comment by blinkov** [comment]
@nullquery it's beyond max date, see https://clickhouse.yandex/docs/en/data_types/date/

**Comment by alexey-milovidov** [comment]
1.

```
toDateOrZero('2017-02-10')
actual result: 0000-00-00
expected result: correct date 2017-02-10

toDateOrNull('2017-02-10')
actual result: nan
expected result: 2017-02-10
```

This is not reproduced anymore.

```
toDate('2017-10-X0')
toDateTime('2017-02-10 xx:10:34')
toDateTime('2017-AA-10 xx:10:bb')
```

This is expected behaviour and should be documented. We explicitly allow implementation defined behaviour on incorrect data for performance reasons.

We can improve this behaviour in various ways:
- add a setting for more strict parsing (but we cannot enable it by default, so no much sense);
- implement more strict parsing for string literals in query (where performance is not the concern), but still leave fast parser for data formats (this will make behavior inconsistent).
