### ISSUE TITLE
If git is present during build, print sha and status.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#24373]
It will allow to easily figure out if the user is building unmodified ClickHouse source code.

**Comment by filimonov** [comment]
That means that info should be regenerated on build stage (not on cmake configure). 

Also there is already a few places when similar stuff is written / passed / generated ("official" flag for build, git sha for build_options, version string, binary checksum etc). It would be cool to do it a bit more organized, especially because of https://github.com/ClickHouse/ClickHouse/issues/22113

**Comment by alexey-milovidov** [comment]
@filimonov It will run on configure stage and it is needed for https://github.com/ClickHouse/ClickHouse/issues/24370.

**Comment by filimonov** [comment]
> @filimonov It will run on configure stage 

For ex. I often first checkout the branch and do cmake configuration step, and only later do some changes and ninja runs. If that build will still show the clear branch state (as is was during cmake run) - that will not work much better than git sha in which alseady is in build_options

**Comment by filimonov** [comment]
> @filimonov It will run on configure stage and it is needed for #24370.

So you mean just to output that in the log w/o compiling it in?

**Comment by alexey-milovidov** [comment]
Yes, it is diagnostic message to help us to close issues quickly.
