### ISSUE TITLE
19.17 is a very old and currently unsupported version - a lot of improvements have been made since then. If you can reproduce the same behavior on the more recent version, then please try it.

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#24389]
19.17 is a very old and currently unsupported version - a lot of improvements have been made since then. If you can reproduce the same behavior on the more recent version, then please try it.

_Originally posted by @abyss7 in https://github.com/ClickHouse/ClickHouse/issues/24216#issuecomment-843020081_

I found the version 21.3.5.42 have the same problem

**Comment by alexey-milovidov** [comment]
What problem?

**Comment by Sallery-X** [comment]
> What problem?

When I set the value of max_server_memory_usage, the instance also happened OOM

**Comment by Sallery-X** [comment]
> > What problem?
> 
> When I set the value of max_server_memory_usage, the instance also happened OOM

My log can't find the  info 'Setting max_server_memory_usage was set to'

**Comment by Sallery-X** [comment]
@alexey-milovidov

**Comment by filimonov** [comment]
> @alexey-milovidov

How do you think we can help you if you didn't provide any information? 

The setting work for sure. Most probably you do something wrong.

If you want us to help you - you need to provide detailed and accurate report: what exactly did you change, when oom happened, what clickhouse was doing at that moment, `dmesg` report, fragment of logs etc.

If you want to get a better help please try to create better reports / issues. See for example https://tomasvotruba.com/blog/2019/07/08/7-tips-to-write-flawless-issue-report-on-github/ or just try to follow the issue template existing in that repo.

Closing that issue, because it has wrong title and non-informative description. Please open the new one if it's still important, but please do it corrent next time (otherwise it can also be closed)
