### ISSUE TITLE
JOIN on constant fails with 21.5.5.12 - worked with 21.4.7.3

### ISSUE THREAD

**Issue by ray-at-github** [ClickHouse/ClickHouse#24437]
**Describe the bug**
JOIN on constant fails with latest stable version 21.5.5.12. It worked with previous stable version 21.4.7.3.

**Does it reproduce on recent release?**
Yes. On 21.5.5.12.

**How to reproduce**
21.5.5.12

```
SELECT a.number
FROM
(
    SELECT number
    FROM numbers(5)
) AS a
INNER JOIN
(
    SELECT number
    FROM numbers(5)
) AS b ON (b.number = a.number) AND (b.number = 5)
```

**Expected behavior**
Query should run without errors.

**Error message and/or stacktrace**
```
Received exception from server (version 21.5.5):
Code: 403. DB::Exception: Received from localhost:9000. DB::Exception: Not equi-join ON expression: b.number = 5. No columns in one of equality side.: While processing b.number = 5.
```

**Comment by vdimir** [comment]
This functionality was introduced here https://github.com/ClickHouse/ClickHouse/pull/19685 but removed later because it leads to some errors (See https://github.com/ClickHouse/ClickHouse/pull/22753 and linked issues).

We will introduce this feature again it in https://github.com/ClickHouse/ClickHouse/pull/24420, it will support not only INNER join, but also LEFT/RIGHT/FULL.

For now you can change you query moving `b.number = 5` into WHERE section to execute it.

**Comment by ray-at-github** [comment]
Noted, thanks
