### ISSUE TITLE
What will happen if we don't update the mutation version in old data part for delete or update?

### ISSUE THREAD

**Issue by zhangjmruc** [ClickHouse/ClickHouse#25071]
For the delete and update statement in ch, we will call cloneAndLoadDataPartOnSameDisk() if no change in this part for this mutation. This function do hard link for all data, and also update mutation in part_info and checksum in this part.

This is why mutation is heavy in ch, we may touch all the data parts for a single row delete. To avoid this, can we just leave the old part with old mutation version in part_info? Is there any bad impact? Like update newest inserted data (inserted after executing update), which should not be updated.

Please share with me your opinions.

**Comment by den-crane** [comment]
CH needs to have a list of parts which should be mutated before a mutation started to execute because only active parts which are exists now should mutated. 

Partition pruning is not implemented for Mutations yet.

You can do "pruning" manually:
UPDATE IN PARTITION
DELETE IN PARTITION
https://clickhouse.tech/docs/en/sql-reference/statements/alter/partition/#update-in-partition

**Comment by zhangjmruc** [comment]
@den-crane Thanks Denny for the reply. By the way, is there any process on the light delete and update implimentation?

**Comment by tavplubix** [comment]
> Thanks Denny for the reply. By the way, is there any process on the light delete and update implimentation?

See #19627
