### ISSUE TITLE
clickhouse server started too slowly.

### ISSUE THREAD

**Issue by trollhe** [ClickHouse/ClickHouse#25112]
i startup time of clickhouse server is too long,bellow is log:
```
2021.06.09 15:11:06.123529 [ 61890 ] {} <Information> DatabaseAtomic (rpt): 79.19463087248322%
2021.06.09 15:11:13.967352 [ 61965 ] {} <Information> DatabaseAtomic (rpt): 81.87919463087249%
2021.06.09 15:11:20.102968 [ 61877 ] {} <Information> DatabaseAtomic (rpt): 85.90604026845638%
2021.06.09 15:11:31.961187 [ 61898 ] {} <Information> DatabaseAtomic (rpt): 86.57718120805369%
2021.06.09 15:11:59.973110 [ 61879 ] {} <Information> DatabaseAtomic (rpt): 87.24832214765101%
2021.06.09 15:12:30.538191 [ 61930 ] {} <Information> DatabaseAtomic (rpt): 88.59060402684564%
2021.06.09 15:13:06.260821 [ 61890 ] {} <Information> DatabaseAtomic (rpt): 89.26174496644295%
2021.06.09 15:13:57.812199 [ 61920 ] {} <Information> DatabaseAtomic (rpt): 89.93288590604027%
2021.06.09 15:14:53.032014 [ 61889 ] {} <Information> DatabaseAtomic (rpt): 90.60402684563758%
```
bellow is parts count:
![image](https://user-images.githubusercontent.com/41068725/121315119-9e890c80-c93a-11eb-9ccf-2a3e09af15b5.png)

please,partion number is stationary,how to speed startup time ?

**Comment by filimonov** [comment]
Every part is a folder on a filesystem with files inside. I see about 400k folders which need to be iterated during the server startup. I guess inside every folder you have from 10 to few thousands of files (depends on the number of columns).

So your question can sound "how can I iterate over tens of millions of files faster" :) 
And there are no smart answers to that question, because the question itself is wrong.

Better try to answer: do you really need those millions of files? That typically a sign of a bad / wrong partitioning schema and misunderstanding of how clickhouse works.
