### ISSUE TITLE
Replication queue deadlock after clone replica

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#25168]
Happened today in production on 20.8. Posting here to get some opinions or maybe this was already discussed. 

The problem is caused by the fact that source replica crashes (node crash) before others had time to fetch the parts. When replica did come back online its log pointer was far behind the one found in ZK. ClickHouse tries to bound how many log entries are kept in ZK, when a threshold is met old log entries are removed and replicas that are behind are marked as "is_lost". When these new replicas come online they can't reconstruct their state and instead start a process called "replica cloning". At the same time they try to clone a different replica and tail the log from the log pointer of that new replica.

In this process the crashed replica discovered some local parts that other replicas know nothing about. It did the sensible thing of moving these local parts to detached folder. https://github.com/ClickHouse/ClickHouse/blob/e25d9843d189306728d6a7fdfc78fad53d2bd9c5/src/Storages/StorageReplicatedMergeTree.cpp#L2756-L2764

Arguably ClickHouse should be able to resolve this problem, but it doesn't today.

You can attach the part by removing clone_ prefix. This gets data back into ClickHouse but because this parts also gets a new block name it can't really fix the replication queue.

I attached the data back and fixed manually the queue by looking at which entries are deadlocked and removing them from zk.

ClickHouse could easily see that the part it is moving to detached is in replication queue on the replica it is cloning 
- and it is also the source replica 🙂
- and it also has the part locally

Sounds like an easy fix but the evil is in the details.

**Comment by tavplubix** [comment]
Replication queue deadlock (which is actually livelock) may happen due to #10368, because it's usually impossible to cancel scheduled merge even if some source part is lost. But there is another way to deal with such merges, see discussion in #24777. 

> The problem is caused by the fact that source replica crashes (node crash) before others had time to fetch the parts. When replica did come back online its log pointer was far behind the one found in ZK. 

Do I understand correctly that source replica became lost too? It looks like very rare case and I think it's ok to move all parts to `detached/` in this case. Yes, such parts will be considered lost, but after fixing "some merges may stuck" it will not cause any problems.

> ClickHouse could easily see that the part it is moving to detached is in replication queue on the replica it is cloning

I agree that the evil is in the details, but it does not sound like an easy fix for me. Also it's very rare case when source replica become lost and it's hard to test such cases. We could make the fix, but it probably will work incorrectly in some more rare corner cases (just like "part is lost forever" mechanism does not work now and breaks invariants in replication queue). So I think we should not do it automatically.

**Comment by nvartolomei** [comment]
Yes, it was the source replica which got lost. I think I know how to write
a test for this and other similar cases.

Create 2 replicas, make an insert then network partition the replicas. Make
1 more insert and run an optimize final.

A: Stop the replica, delete the part created by second insert and the
merged part, start the replica (this will reproduce the issue from the
other ticket).

B: Stop the replica. Make sure it gets lost (configure max log entries to
keep to some low value like 0) and make sure cleanup thread runs (guess we
can force it). Start the replica back.

Would this work?

**Comment by tavplubix** [comment]
Most likely it will not cover complicated corner-cases and distributed race conditions like this: https://github.com/ClickHouse/ClickHouse/pull/24777#issuecomment-851525932

Such test will check only the simplest case.

**Comment by tavplubix** [comment]
This issue should not be reproducible after #25820, #30346 and other fixes.
