### ISSUE TITLE
online modification of configuration

### ISSUE THREAD

**Issue by zhbdesign** [ClickHouse/ClickHouse#25194]
Whether it can provide the function of online modification of configuration, in the form of SQL or HTTP interface, and can be persistent, and restart does not affect

**Comment by alexey-milovidov** [comment]
I prefer not to implement this feature.

Only some parts of configuration can be changed without server restart.
For example, users, clusters and dictionaries configuration can be changed, while path, tcp_port, max_connections cannot be changed. And implementation to change these parts of configuration is not easy. Actually server restart is the only generic way to implement configuration change. And when you have replicated setup, you can do it without service downtime.

Also we cannot allow to access all the configuration from SQL, because some parts of configurations better to remain static from security standpoint.
