### ISSUE TITLE
No columns in nested table ERROR in Nested Type with Chinese field names

### ISSUE THREAD

**Issue by kilik52** [ClickHouse/ClickHouse#25594]
You have to provide the following information whenever possible.

**Describe the bug**

When use chinese as field name for nested type and query:

````
SELECT * from table array join `xxxx`;
````

it will raise error:

No columns in nested table xxx

**Does it reproduce on recent release?**

ClickHouse server version 21.3.5 revision 54447.

**How to reproduce**

1. create table

````
CREATE TABLE tmp.test1 (`id` String, `products` Nested (`产品` Array(String), `销量` Array(Int32))) ENGINE = ReplacingMergeTree ORDER BY id
````

2.  query

````
SELECT * FROM tmp.test2 array join products;
````

Error：

````
Received exception from server (version 21.3.5):
Code: 208. DB::Exception: Received from localhost:9000. DB::Exception: No columns in nested table products. 
````

**Additional Information**

I've tried using english character as field name, and it works.

**Comment by fengguangyuan** [comment]
Hi, I am fresh on ClickHouse, but I offered an glimpse of the related source code and find out the possible cause:
```c++
// this slice code is defined in TreeRewriter.cpp::getArrayJoinedColumns(...)
bool found = false;
auto split = Nested::splitName(column.name);
if (split.first == source_name && !split.second.empty())
{
   result.array_join_result_to_source[Nested::concatenateName(result_name, split.second)] = column.name;
   found = true;
   break;
}
if (!found)
  throw Exception("No columns in nested table " + source_name, ErrorCodes::EMPTY_NESTED_TABLE);
```
As we know that the Chinese characters should be represented by GBK/UTF8/Unicode etc., rather than the simple ASCII characters in program, so here the root reason comes:
When creating a new table with Chinese named columns, the parser, `ParserIdentifier` defined in `ExpressionElementParsers.h` and implemented in `ExpressionElementParsers.cpp`, could correctly recognize these complex identifiers utilizing `ReaderHelpers::parseComplexEscapeSequence(...)`, but `TreeRewriter` will try to split the complex nested column name, e.g. `products`.`产品`, using `NestedUtils::splitName(const std::string & name)` in which treating  the nested `name` as simple ASCIIs.
Finally, no doubt an exception `No columns in nested table ...` should be thrown.

_So I recommend you alter `product` table to substitute all the Chinese name with ASCII characters, then after joined, give each of them an alias._

I hope these is no mistakes in my answer, and someone could give a more decisive advice whether it's worthwhile to fix it or not! 
:)
