### ISSUE TITLE
In clickhouse21.4.5.46 version, under the RBAC authorization mechanism, there is no data after MATERIALIZED VIEW is created.

### ISSUE THREAD

**Issue by mjh568412187** [ClickHouse/ClickHouse#25723]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

---
When I am under a personal user such as zhangsan, I have given zhangsan the query permissions for the local_ods.ods_order_db__t_trade_order_header table
Created MATERIALIZED VIEW
The specific table statement is as follows:

`CREATE table local_temp.test_table_2
(
    id String,
    root_order_id String,
    pay_at String,
    version_id UInt64
)
ENGINE = MergeTree()
order by (version_id);

CREATE MATERIALIZED VIEW local_temp.consumer To local_temp.test_table_2
(
	   id String,
    root_order_id String,
    pay_at String,
    version_id UInt64
)
as
select id,root_order_id,pay_at,version_id

from local_ods.ods_order_db__t_trade_order_header;
`
When I am under individual user, I created MATERIALIZED VIEW
The specific table statement is as follows:

When I query the local_temp.test_table_2 table, no data can be found

When I use the admin user of the cluster, I can query data completely.
Suspected it is a permission problem
I checked the documentation, but I didn’t find a command on how to empower MATERIALIZED VIEW.

**Comment by e-mars** [comment]
Hi @mjh568412187 ,

I think the issue is probably one or both of these:
- the way the materialized view was created was to have a target storage table and was not populated so unless there were new rows the materialized view would not have data.
-  there is a missing grant for the regular user to access the view

Below is an example that you can try and adjust for your tables and views.

1. create a table to serve as the table to store the materialized view data
```
CREATE TABLE table1 (
  id UInt64,
  column1 String
)
ENGINE MergeTree
ORDER BY (column1)
```
2.  create another table to be the source table for the view
```
CREATE TABLE table2 (
  id UInt64,
  column1 String,
  column2 String
)
ENGINE MergeTree
ORDER BY (column1)
```
3. populate the source table with data
```
INSERT INTO table2 
(id, column1, column2) 
VALUES 
(1, 'a', 'x'),
(2, 'b', 'y'),
(3, 'c', 'z')
```
4. Create the materialized view
```
CREATE MATERIALIZED VIEW mv_1 TO table1
AS
SELECT id, column1 FROM table2
```
*at this point if you do a `SELECT * FROM mv_1`, there will be no data returned since the target table was not populated.
5.  create the regular user and grant permissions to the new materialized view
```
CREATE USER regular_user IDENTIFIED WITH plaintext_password BY 'password'
GRANT SELECT ON mv_1 TO regular_user
```
6. connect with the regular user and do `SELECT * FROM mv_1`
*this will allow you to connect without any authentication errors but the view will still not have data to show.
7. insert a new row into the source table
```
INSERT INTO table2 
(id, column1, column2) 
VALUES 
(4, 'd', 'w')
```
8. Test the configuration with the regular user. 
![Screen Shot 2022-03-04 at 7 27 04 PM](https://user-images.githubusercontent.com/18219420/156864280-5a51360e-750b-4fcd-8db6-a00ca7f25405.png)

hope this helps.
thanks.
