### ISSUE TITLE
Is it possible to change zkpath for a ReplicatedMergeTree table?

### ISSUE THREAD

**Issue by lucasguo** [ClickHouse/ClickHouse#25953]
At first I have created a distributed table (let us name it **table_A**). And then I decided to move the data to a ReplicatedMergeTable. I did it as below:

`create table table_B as table_A engine=ReplicatedMergeTree('/clickhouse/tables/01/{database}/{table}', '{replica}');`
`insert into table_B select * from table_A;`

So far so good. After that, I drop the distributed table and rename the new one to the old name.

`drop table table_A;`
`rename table table_B to table_A;`

Then I tried to insert some data into table_A, it threw an error:

`Table is in readonly mode (zookeeper path: /clickhouse/tables/01/default/table_B)`

I have tried to find some command to fix the zookeeper path for this table as alter table and etc. but nothing found.

Is it a solution to make it out?

**Comment by den-crane** [comment]
There is no good solution. ZK does not allow to rename znodes. 
You can manually fix table_A.sql file in metadata folder. 

This is impossible situation in the latest CH versions. Because CH now expand {database}/{table} macros on create command, so in the table's metadata (.sql) will be real name table_B, instead of {table} macro.

Also the latest CH versions allow to use Atomic databases and uuid as ZK path. You  can simply omit ZK path parameter `ReplicatedMergeTree()`

**Comment by lucasguo** [comment]
> There is no good solution. ZK does not allow to rename znodes.
> You can manually fix table_A.sql file in metadata folder.
> 
> This is the impossible situation in the latest CH versions. Because CH now expands {database}/{table} macros on a create command, so in the table's metadata (.sql) will be the real name `table_B`, instead of `{table}` macro.
> 
> Also the latest CH versions allow to use Atomic databases and uuid as ZK path. You can simply omit ZK path parameter `ReplicatedMergeTree()`

Thanks for your fast response! After changing the table_A.sql under /clickhouse/metadata/default/ by replacing the {table} macro to the real table name,  and restarting the clickhouse service, everything goes fine now.
