### ISSUE TITLE
Write distributed table, no ZK, how to avoid data inconsistency between replic

### ISSUE THREAD

**Issue by shadowDy** [ClickHouse/ClickHouse#26071]
In our cluster, the query results are inconsistent for many times. After investigation, it is found that the reason is that the query is executed on different copies and the returned results are inconsistent.

Comparing the data of two replicates, there are some differences.

Write method: write distributed table, randomly to each local table.

Read mode: read distributed table.

config:
insert_distributed_sync :default 0；
internal_replication: default false;

how to fix it。thanks~

**Comment by filimonov** [comment]
Use replicated tables / zookeeper

**Comment by shadowDy** [comment]
> Use replicated tables / zookeeper

Why do distributed tables have this problem

I understand that if local is written first and then distributed to other nodes or replicas in the form of files, the short-term data will be delayed (inconsistent), but it should be the same in the end.

**Comment by den-crane** [comment]
>Comparing the data of two replicates, there are some differences.

Distributed table do insert retry in case of error.
MergeTree table does not have a deduplication feature.

There is a scenario possible:
1. Distributed table inserts into the shard
2. Shard successfully applies the insert.
3. Distributed gets insert timeout because of network error 
4. Distributed table repeats the same insert from the step 1
5. You got double data.
