### ISSUE TITLE
Miserable quality of documentation search

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#26209]
Cannot find a page about ClickHouse Keeper.

![Screenshot_20210711_015246](https://user-images.githubusercontent.com/18581488/125178165-d3fb7100-e1ea-11eb-8474-e63bea3ae932.png)

https://clickhouse.tech/docs/en/operations/clickhouse-keeper/

**Comment by alexey-milovidov** [comment]
@rfraposa The quality of the documentation search is slightly less miserable than before. This is an achievement. I assume this task is done.

**Comment by rfraposa** [comment]
Funny. FWIW, we actually have complete control over search results by configuring Algolia. @DanRoscigno and I are working on tweaking Algolia, and over time hopefully we will have search that is considerably less miserable.

**Comment by DanRoscigno** [comment]
As we find things that are not showing in the search we look into the reason and fix it.  So far the reason is that the terms we search on are not tagged with H1 - H4 tags.  One that I fixed yesterday was the [codecs page](https://github.com/ClickHouse/ClickHouse/pull/38325/files), I searched for DoubleDelta, did not find it, saw that the codecs were in a list, and switched the list to H4's.  After a re-crawl the codecs are now found.

So, I would like to reopen this and ask that the three of us ask people to post in here when the search results stink.

**Comment by alexey-milovidov** [comment]
> the reason is that the terms we search on are not tagged with H1 - H4 tags

Shouldn't it search through all the text?

**Comment by rfraposa** [comment]
Yes - it should. @DanRoscigno do we know if Algolia is indexing all the text on every page?

**Comment by DanRoscigno** [comment]
Algolia is indexing all of the content on the English pages.  I checked a few terms yesterday and found that:

- all content is indexed
- the order is H1 - H5 and then content
- changelog entries *may* be favored over deeper pages

A little background: I looked into this because of feedback from a customer.  The customer reported that some engine settings were undocumented.  We looked together and saw that there were pages returned by Algolia, but that the first several pages of results were all changelog entries and not the reference material (I am suspecting that the depth of the URL has something to do with it). We did not look far enough on the call, but based on the checks I did before and after adding the H4 headers over the past few days I believe that the results we expected were just down further.

I will open an issue with Algolia today asking if we can prefer the doc pages over the changelogs, I believe that we can do this by adding metadata to the changelog pages, but I did not see a detailed explanation of this while reading the Algolia docs.

Based on past conversations with an SEO expert I still believe that moving the settings from list entries up to H headings is important to get the docs indexed in external search engines.
