### ISSUE TITLE
clickhouse-local remote() fails with localhost on default port

### ISSUE THREAD

**Issue by davidmanzanares** [ClickHouse/ClickHouse#26712]
**Describe the bug**

With a clickhouse server running on local at the default port (9000), this should work:
```
$ clickhouse-local -q "SELECT * FROM remote('127.0.0.1:9000', 'system.parts') LIMIT 3;"
Code: 60, e.displayText() = DB::Exception: Table system.parts doesn't exist (version 21.7.2.7 (official build))
```

Note that no tables can be accessed, not just system.parts.

**Does it reproduce on recent release?**

Yes, 21.7.2.7

**How to reproduce**

* Start a clickhouse server at default port
* Make any query with clickhouse-local to the clickhouse server using the `remote` function

**Expected behavior**

Clickhouse-local should be able to access it, just like clickhouse-client can with the same query.

**Additional context**

The problem only happens when using localhost and the default port. Starting the server at other port works.

The issue seems to be caused by incorrectly treating the address as local instead of as remote. We are working on a PR to fix it.

**Comment by Algunenano** [comment]
I've been working on a fix for this issue which requires changing the behaviour of clickhouse-local connections (and breaks a test).

The idea would be that clickhouse-local remote connections:
- To an external address: Same behaviour, it creates a new connection.
- To localhost / local domain / local address without declaring a port: Connects to self, that is, it doesn't go anywhere.
- To localhost:port / domain:port / local address:port: Uses an external connection, no matter the port (even for the default one, which was the issue here).

I think it makes sense to work like this since clickhouse-local isn't actively listening anywhere, so if you declare a connection to localhost:9000 you are actively trying to connect somewhere that isn't the local instance.

Some examples:
* `remote('localhost', 'system.tables')` -> Connects to self
* remote('localhost:9000', 'system.tables') -> Connect to an external database
*
* `remote('127.0.0.1', 'system.tables')`: Self
* `remote('127.0.0.1:9000', 'system.tables')`: External
* `remote('127.0.0.1:19000', 'system.tables')`: External

Another option would be to assume that any connection under clickhouse-local is external, but that would break the possibility of clickhouse-local connecting to itself which some people might be using.

Any thoughts?

**Comment by alexey-milovidov** [comment]
@Algunenano It will be the perfect solution.
