### ISSUE TITLE
s2geometry: ERROR Invalid S2LatLng in S2LatLng::ToPoint

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#27090]
https://clickhouse-test-reports.s3.yandex.net/0/6951e8147d7a25f7bb4f7d43738793cff239db6d/stress_test_(debug).html#fail1

```
:) SELECT geoToS2(toFloat64(toUInt64(-1)), toFloat64(toUInt64(-1)));

SELECT geoToS2(toFloat64(toUInt64(-1)), toFloat64(toUInt64(-1)))

Query id: f1ef3f1d-b46d-4ef4-a5e5-869798d8379c

┌─geoToS2(toFloat64(toUInt64(-1)), toFloat64(toUInt64(-1)))─┐
│                                       4864204703484167331 │
└───────────────────────────────────────────────────────────┘
```

```
$ grep -Fa ERROR stderr.log 
../contrib/s2geometry/src/s2/s2latlng.cc:37 ERROR Invalid S2LatLng in S2LatLng::ToPoint: [1.84467e+19, 1.84467e+19]
```

Maybe it should throw exception if point is invalid. Also it should not print errors to `stderr`.

**Comment by tavplubix** [comment]
`Illegal type Array(Nullable(Nothing)) of first argument of function parseDateTime32BestEffortOrNull. Conversion functions with postfix 'OrZero' or 'OrNull'  should take String argument: While processing parseDateTime32BestEffortOrNull([NULL], [NULL])` - looks like expected behavior

`Cannot add message to the log` caused by `MEMORY_LIMIT_EXCEEDED` exception on attempt to write message to log

Assertion in DatabaseReplicated - duplicate of #27011

**Comment by qoega** [comment]
Same lib. Other place.
```
../contrib/s2geometry/src/s2/s2latlng_rect.h:382 ERROR Invalid rect: [50.4210420, 0.4931979], [2.1000000, 2.9000000]
```

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/51502/bbd4159beeca878616546b77a3dd36b3a9a391d6/stateless_tests__debug__[4_5]/stderr.log
```
/build/contrib/s2geometry/src/s2/s2latlng_rect.h:382 ERROR Invalid rect: [50.4210420, 0.4931979], [2.1000000, 2.9000000]
/build/contrib/s2geometry/src/s2/s2latlng.cc:38 ERROR Invalid S2LatLng in S2LatLng::ToPoint: [1.84467e+19, 1.84467e+19]
```
