### ISSUE TITLE
RBAC: new testing version 21.9 is going to change what privileges needed to insert into a tables that is used by one or more Materialized Views. Is it intentional?

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#27570]
**Describe the bug**

21.9 breaks privileges needed to insert into a tables that used by one or more Materialized Views.

**Does it reproduce on recent release?**

21.9 (master)

**How to reproduce**

Add MV over some source table and try to insert into it with the user that only has INSERT privilege for source table and check
that an ACCESS_DENIED error is returned.

**Expected behavior**

Privileges needed to insert into a source table shall not be affected by the presence or absence of any
number of materialized views.

**Comment by vzakaznikov** [comment]
> > Privileges needed to insert into a source table shall not be affected by the presence or absence of any
> > number of materialized views.
> 
> Why?

First reason is that the behavior has changed from 21.8. Secondly, this dependency is unmanageable
in real systems that could have hundreds of materialized views with any number of nesting of materialized views over other
materialized views.

**Comment by alexey-milovidov** [comment]
It looks like intentional change.
At least it makes access control more understandable and more safe.
You need to be allowed to INSERT into every table where data is, in fact, inserted.

But I'm not 100% sure if it was intentional.
Let's ask author @vitlibar.
If he will not answer, I simply close this issue.

**Comment by vitlibar** [comment]
That wasn't intentional. It's understandable why it's working this way, but sometimes this behaviour is just not friendly for managing access rights. I think we should add kind of option for the CREATE VIEW query, like:

```
CREATE MATERIALIZED VIEW ... INVOKER(user 'default' password '')
```

and that will make a newly created materialized view to execute its own queries on behalf of a specified user. If `INVOKER` is specified it will work like a dictionary with CLICKHOUSE source which executes its own queries on behalf of another user too.

**Comment by alexey-milovidov** [comment]
Please don't do anything on this task before triaging this list: https://github.com/ClickHouse/ClickHouse/issues?q=is%3Aopen+label%3Acomp-rbac+label%3Abug

**Comment by alexey-milovidov** [comment]
This task has a low chance to be implemented.

**Comment by vitlibar** [comment]
I think it's better to implement this issue along with https://github.com/ClickHouse/ClickHouse/issues/19228 and implement the DEFINER feature both for views and matviews.
