### ISSUE TITLE
Subscribe to data

### ISSUE THREAD

**Issue by sigirisetti** [ClickHouse/ClickHouse#28309]
Hello folks,

I have some experience with Kdb which supports data subscription. Real time update are pushed to table susbcriptions

I was going through clickhouse documentation for such a feature and didn't find any or may be missed it. Is it possible to subscribe to clickhouse table updates or any other clickhouse feature to achieve the same

Thank you

**Comment by den-crane** [comment]
Nothing like this. Try https://clickhouse.tech/docs/en/sql-reference/statements/create/view/#live-view-monitoring 
https://altinity.com/blog/tag/live-views/

**Comment by den-crane** [comment]
ah, Also materialized view is an insert trigger.

**Comment by loyd** [comment]
Be careful, LV reruns the query after every `max_live_view_insert_blocks_before_refresh` (64 by default) inserted blocks. So, even the simplest queries like `SELECT max(timestamp) FROM some_table` will be slow for large tables.

Thus, I don't recommend you to get any data from LV and use it only to get events about new data:
```sql
CREATE LIVE VIEW test1_lv AS SELECT now64(9) FROM test1 LIMIT 1
WATCH test1_lv EVENTS
```
You will receive events on every INSERT. Then, you can select data, probably with throttling.

---

Also, the next approach is useful to filter events in order to reduce extra SELECTs:
For instance, we have some table with a field that we want to use to filter stream (`name`):
```sql
CREATE TABLE test1 (name String, ts DateTime) ENGINE = MergeTree ORDER BY (name, ts)
```

Create a filter table:
```sql
CREATE TABLE filter(name String) ENGINE = Memory;
```

Now, use the filter table in your LV:
```sql
CREATE LIVE VIEW test1_lv AS SELECT now64(9) FROM test1 WHERE name IN filter LIMIT 1
WATCH test1_lv EVENTS
```

You can modify the filter table programmatically to add/remove subscriptions on the fly:
```sql
-- Subscribe to "a"
INSERT INTO filter VALUES ('a');
-- Unsubscribe
ALTER TABLE filter DELETE WHERE name = 'a'
```

You will receive events only on names in the test filter.

**Comment by loyd** [comment]
Also, It's reasonable to invite @vzakaznikov here to comment on this approach)
