### ISSUE TITLE
When to use skipping index vs ORDER BY for a column

### ISSUE THREAD

**Issue by iameugenejo** [ClickHouse/ClickHouse#28424]
#### A few questions regarding this topic:

1. What is the characteristics of a column that makes it suitable to be included in `ORDER BY` or as a `Skipping Index`?

2. I'm under an impression that generally the columns in `ORDER BY `should be from low cardinality to high cardinality, is this correct?

#### Follow-up question:

I have a set of hierarchical columns, let's say `parent_id`, `child_id`, `grandchild_id`, where their cardinalities are like this - `parent_id` is under 100, `child_id` is under 500, `grandchild_id` is under 50,000.

I could use dictionary for the relationship if the relationship doesn't change at all, however it's rare but does change time to time, so I'm saving these along with the main id, `grandchild_id`

The table is partitioned by the `toStartOfDay(timestamp)`, `timestamp` itself is in `5-minute` segments and the total number of rows per daily partition is about `100 million` rows (there are other fields that make the row count higher, but omitted to make the question simple)

What should the ORDER BY look like? 

#### Characteristics of each columns:
- `parent_id`: 
  - **CAN** be used in `WHERE` and **NEVER** used by `GROUP BY`
  - cardinality < 100
- `child_id`: 
  - **CAN** be used in `WHERE` or `GROUP BY` with `parent_id` in WHERE
  - cardinality < 500
- `grandchild_id`: 
  - **CAN** be used in `WHERE` or `GROUP BY` with `parent_id` or `child_id` in `WHERE`
  - cardinality < 50,000
- `timestamp`: 
  - **MUST** be used in `WHERE` and **CAN** be used in `GROUP BY`
  - cardinality == 288 within a partition (`5-minute` chunk, partitioned by `toStartOfDay(timestamp)`)

1. `parent_id`, `child_id`, `grandchild_id`, `timestamp`?

2. `timestamp`, `parent_id`, `child_id`, `grandchild_id`?

3. `grandchild_id`, `timestamp` with skipping index on `parent_id` and `child_id`?

4.  `timestamp`, `grandchild_id` with skipping index on `parent_id` and `child_id`?

5. something else?

I tested 1 ~ 4, and 3 is coming out with the least `marks to read and ranges`, and I'm not sure if it's due to the small size of the sample (1.5 billion rows) or not.

**Comment by genzgd** [comment]
The goal of both the primary key and data skipping indexes is to reduce the number of granules to read (blocks by default of  8192 row/key values).  In general query patterns are more important than cardinality.   It would also be beneficial to actually run the queries rather than just relying on the EXPLAIN plan to see the actual amount of data read.

Because timestamp is always used in your WHERE clause, it should normally be the first element of your ORDER BY/primary key since it allows limiting the number of blocks read.   The main exception to this is if your queries normally span more than one partition (assuming the PARTITION BY expression is based on the timestamp), so that further filtering by timestamp beyond the partition level does not result in excluding any more data.

If your data is sorted such that most blocks contains only a handful of grandchild_id values, that will permit skipping a larger number of blocks that don't contain the requested values, so that could be improving your estimated performance in combination with partition level filtering.

Skipping indexes are only useful if there is a high correlation between the primary key and the index value or if the data is naturally grouped.  If your parent_id and child_id are evenly scattered among your rows such that each block of 8192 rows contains the parent_id or child_id, reading those blocks cannot be skipped and the skipping index provides no benefit.

Again selecting the correct primary key and skipping indexes is not easy to do based on broad principles like cardinality; the query pattern is more important.  Over the next few months ClickHouse Inc. will be developing more in depth articles to cover partition key, primary key, sorting key, and skip index tuning.
