### ISSUE TITLE
How to understand ClickHouse explain

### ISSUE THREAD

**Issue by ggchangan** [ClickHouse/ClickHouse#28847]
I'm using explain to get SQL plan, there is one like the following:
```
┌─explain─────────────────────────────────────────────────────────────────────────────────────────┐
│ Expression (Projection)                                                                         │
│   Expression (Before ORDER BY and SELECT)                                                       │
│     MergingAggregated                                                                           │
│       SettingQuotaAndLimits (Set limits and quota after reading from storage)                   │
│         Union                                                                                   │
│           Expression (Convert block structure for query from local replica)                     │
│             CreatingSets (Create sets before main query execution)                              │
│               Aggregating                                                                       │
│                 Expression (Before GROUP BY)                                                    │
│                   Filter (WHERE)                                                                │
│                     Join (JOIN)                                                                 │
│                       Expression (Before JOIN)                                                  │
│                         SettingQuotaAndLimits (Set limits and quota after reading from storage) │
│                           ReadFromStorage (MergeTree)                                           │
│               CreatingSet (Create set for JOIN)                                                 │
│                 Expression (Projection)                                                         │
│                   Expression (Before ORDER BY and SELECT)                                       │
│                     SettingQuotaAndLimits (Set limits and quota after reading from storage)     │
│                       ReadFromStorage (MergeTree)                                               │
│           ReadFromPreparedSource (Read from remote replica)                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────┘
```
However I don't understand each step means, for example SettingQuotaAndLimits, Expression, CreatingSets, Union and so on, And I can't get detail documents. Is there any way I can get to understand each step means?
And the second questions is what the indent means? I can see some indents in each line for Explain output, Is there any hints using intent?

**Comment by KochetovNicolai** [comment]
Query plan is a tree which represents decomposition of a query into basic steps.
Usually, each step represents some logical transformation over a set of columns. There is no documentation about it because query plan is still in development stage, and may be changed over versions. Its main reason for now is to give some introspection, more to developer than to user.

Let me describe each step a little bit:
* `ReadFromStorage` reads a set columns from table (in recent version, there will be `ReadFromMergeTree` for merge tree engine).
* `SettingQuotaAndLimits ` is a technical step which does actually nothing with data, but responsible for checking quota and limits (like checks for `max_rows_to_read`). I will try to remove it later.
* `Expression` calculates functions over columns, like `x, y -> x + 1, y * 2`. Use `explain actions = 1 select ...` to see more details.
* `Join` executes join. For this query, it is a hash join, which adds joined columns from hash table (which is filled in `CreatingSet`)
* `Filter` is an implementation of `WHERE` or `HAVING`. Removes rows buy some expression.
* `Aggregating` is responsible for `GROUP BY`. See `actions = 1`.
* `CreatingSets` fills hash table for `IN (subquery)` or hash join (in this query).
* `ReadFromPreparedSource` here is actually reading from remote table (changed in recent versions).
* `Union` is an implementation of `UNION`, or just a fusion of data from several sources (`Expression` and `ReadFromPreparedSource ` here).
* `MergingAggregated ` is also a part of `GROUP BY`, which merges aggregate function states from different sources (remote and local here) together.

About idents, it is all about a tree representation. Every tree node adds the same ident to its children. Here, for `CreatingSets` children are `Aggregating` and `CreatingSet`, and for `Union` are `Expression` and `ReadFromPreparedSource`. Other steps have no more than one children.
