### ISSUE TITLE
FR: fixed size database setup

### ISSUE THREAD

**Issue by pryg-skok** [ClickHouse/ClickHouse#2908]
Hi, 

can't find anything in documentation about such thing as capped collections of data (like in mongodb). There are setups, when it's necessary to fix size of database and if database gets closer to its limits - its just drop or replace old values with new. 

So as user I can be assured that database will not grows in size no matter how fast and how many data I push into it. It simplifies code and db management in resource restricted environments.

How to achieve such setup with clickhouse?

**Comment by blinkov** [comment]
Usually people just do this externally by dropping old partitions whenever it seems suitable.

**Comment by pryg-skok** [comment]
The problem with such approach that I need to externally watch on database size and size of partitions, and also If in a moment many metrics rush into the base I can encounter overflow by size. Or I need to externally check DB size before insert every N metrics, which can be CPU intensive, isn't it?

Also is there any recommendations about how often one need to drop old partitions for which sizes of databases?

**Comment by filimonov** [comment]
I don't think that removing some data silently based on size is brilliant idea.

Generally **you** should know how much data you need to store  - it depends on scenario, sometimes 1 day is enough, sometimes 50 years is not enough. 

After that you should estimate how much servers and how big disks you need. And how big your partitions should be (generally in clickhouse you can operate data on partitions level). 

After that create some scripts which will clean old unneeded partitions. 

You can check how big your partitions and columns are using system.parts_columns. For example using that selects
```
:) select database, table, partition, column, formatReadableSize(sum(data_compressed_bytes)) as compressed, formatReadableSize(sum(data_uncompressed_bytes)) as uncompressed, sum(data_compressed_bytes)*100/sum(data_uncompressed_bytes) as compress_ratio, min(min_date) as min_date from system.parts_columns group by database, table, partition, column with totals order by database, table, partition, sum(data_compressed_bytes);

:) select database, table, partition, formatReadableSize(sum(data_compressed_bytes)) as compressed, formatReadableSize(sum(data_uncompressed_bytes)) as uncompressed, sum(data_compressed_bytes)*100/sum(data_uncompressed_bytes) as compress_ratio, min(min_date) as min_date from system.parts_columns group by database, table, partition with totals order by database, table, partition, sum(data_compressed_bytes);
```

**Comment by pryg-skok** [comment]
I don't agree - sometimes removing data silently is completely acceptable, because data has different nature and importance :) In my project it's OK that data will be dropped, because it's just become outdated.

Also I have different setups with different disk spaces - somewhere there will be more data, with higher resolution, and in other places there will be less data or lower metrics resolution.

So I'd like to just setup initial conditions based on available disk space and then push metrics into DB. That's it.

Scripts with partitions is possible approach, but as I said sometimes there may be metrics boosts when multiple workers push large data sets which can overflow partition size. So I need to check size of partitions very often and even in this case I can't guarantee that overflow not happens. How to deal with that?

**Comment by filimonov** [comment]
> In my project it's OK that data will be dropped, because it's just become outdated.

I'm just telling that defining data lifetime in terms of diskspace can't guarantee how long your data will be in place. 

I.e. lets assume that you give 100 Gb of disk space for your logs, and currently it's enough to store 7 days of data, which satisfy your needs. You made a setup and forget about that. Afterward the project start growing, and data lifetime start degrading 6,5,4,3,2... After a year some incident happen in a weekend and your project manager asks you to debug it on Monday. You start checking and find that you have only 1 day of data (from Monday), rest was removed because it doesn't fit to 100Gb anymore.

So if you don't have ANY minimum expectations about data lifetime, and disk is more important for you than data - it's easier and cheapier to write it directly to `/dev/null` :)

> Also I have different setups with different disk spaces - somewhere there will be more data, with higher resolution, and in other places there will be less data or lower metrics resolution.
> So I'd like to just setup initial conditions based on available disk space and then push metrics into DB. That's it.

Do you know some DB which implement something like that, internally?

P.S. Currenlty there is GraphiteMergeTree which do degradation of resolution.

**Comment by alexey-milovidov** [comment]
Now we have TTL expressions: https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/
It's not for fixed-size database setup but is suitable to store data for a limited time period.

**Comment by pryg-skok** [comment]
Very interesting, thanks. I'm not sure we will use it in production because we have strong space restrictions, but will give it a try.

**Comment by alexey-milovidov** [comment]
True fixed size database setup is not likely to be implemented, because we use copy-on-write strategy for data parts and it will be very difficult to approach data size limit while still control the maximum data size exactly. Instead, it's recommended to estimate your data size depending on storage duration and setup TTL.
