### ISSUE TITLE
Is it possible to specify the status file path ?

### ISSUE THREAD

**Issue by qingant** [ClickHouse/ClickHouse#29607]
### Discussed in https://github.com/ClickHouse/ClickHouse/discussions/29606

<div type='discussions-op-text'>

<sup>Originally posted by **qingant** October  1, 2021</sup>
We are running Clickhouse on top of some shared file system, we want to start multi Clickhouse in different servers on same directory to enable smooth failover. Well, it's prevented by status file lock ? it there any method that we can config the status file path ?</div>

**Comment by tavplubix** [comment]
No, status file path is always `<path>/status`, where `<path>` is ClickHouse root directory. It's not possible to choose different path and it's done this way intentionally, because table and database engines do not expect that files on disk can be concurrently changed by another ClickHouse instance. Multiple instances cannot work correctly with shared filesystem.

See also #23300
