### ISSUE TITLE
Missing merged parts are checked regularly, missing blocks

### ISSUE THREAD

**Issue by jzombi** [ClickHouse/ClickHouse#29778]
We have a ReplicatedMergeTree table with 2 replicas. The error log `clickhouse-server.err.log` is full of warnings like:

```
Checking part [...]
Checking if anyone has a part [...] or covering part.
Found parts with the same min block and with the same max block as the missing part [...]. Hoping that it will eventually appear as a result of a merge.
```

We could identify the problematic parts, from the log files and based on this comment: https://github.com/ClickHouse/ClickHouse/issues/10368#issuecomment-616310015, but in our case the type field is `'GET_PART'`, not `'MERGE_PARTS'`.

We've checked whether min_block_number, max_block_number ranges of existing parts with the same partition_id covers the range of the missing "merged" part's min_block_number, max_block_number. It turned out that all missing "merged" part but one are covered by existing parts. The missing part that is not fully covered has the same block numbers missing in both replicas.

The missing "merged" part: `b762d3709bf376c5f06287ec8e9d2665_0_822_4`
Parts found in the file system / system.parts table:
```
b762d3709bf376c5f06287ec8e9d2665_0_198_3
b762d3709bf376c5f06287ec8e9d2665_199_233_2
[...]
b762d3709bf376c5f06287ec8e9d2665_679_708_2
b762d3709bf376c5f06287ec8e9d2665_742_775_2
[...]
```
Missing block numbers: 709-741

My questions regarding the situation:
1. Is it ok to delete the queue nodes in ZooKeeper to avoid getting the warnings, even when `type='GET_PART'`?
2. Are the block numbers expected to be continuously assigned? Does the missing block numbers indicate data loss?
3. Can the missing block numbers cause any trouble in the future, eg. in later merges, etc.? (Apart from the possibly already lost data,) I couldn't find any other warnings/errors in the log files for the affected partition_id, it seems as if ClickHouse checks only the minimum and maximum block numbers.

Thanks!

**Comment by genzgd** [comment]
Is this issue still happening?  If so, what version of ClickHouse are you running?

To answer your questions:
  1.  As noted in #10368, if the queue entry is more than 24 hours old and the message indicates that no replica has the missing part or a merged part covering the missing part, it should be okay to remove the problematic part from zookeeper.  However, in the most recent versions of ClickHouse, if it is determined that a part is lost and cannot possibly be recovered from any known replica, it will be replaced with an empty part (with an error message and a tracking metric) so that merges can continue without any need to modify zookeeper data.
  2.  Block/part numbers are only assigned when data has been marked received by the ingesting node, so missing block numbers do normally represent data loss.
  3. Once a part has been merged, individual part numbers no longer matter -- you are correct that only the minimum and maximum block numbers are important for subsequent merges.
