### ISSUE TITLE
Converting an `Array(String)` into an `Array(LowCardinality(String))` with `arrayMap()` fails

### ISSUE THREAD

**Issue by davidmanzanares** [ClickHouse/ClickHouse#30357]
Converting an `Array(String)` into an `Array(LowCardinality(String))` with `arrayMap()` and `toLowCardinality()` fails.

```
clickhouse local -q "SELECT arrayMap(y -> toLowCardinality(y), ['hi'])"
Code: 44. DB::Exception: Invalid column type for ColumnUnique::insertRangeFrom. Expected String, got ColumnLowCardinality. (ILLEGAL_COLUMN) (version 21.9.5.15 (official build))
```

It fails with a similar error on all tested versions: 21.9.5.15, 21.3.17.2 and 20.7.2.30.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai @Algunenano This issue makes sense. Let's try to fix.

**Comment by Algunenano** [comment]
Here are my (internal) notes about this from that date:

> The problem is that all functions work under the assumption that no LowCardinality type will be passed or returned and to fix one you need to change all the others; otherwise once I fix something other issues pop up (it's happening).

Basically many functions (IIRC at least all the array functions and all aggregations) are prepared to work only with full columns and once you allow passing LowCardinality types you need to fix each of them individually and there are a lot. It's sad because knowing that you are working with a LowCardinality string should allow for much better approaches in some cases but the amount of worked it required for the little benefit it offered seemed too high at that moment. I might still revisit it at some point.

**Comment by KochetovNicolai** [comment]
I suppose at least for arrayMap, and maybe for other array functions, we can let return `LowCardinality` if inner lambda can do it.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai This issue still looks fresh.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai allowing lambda to return LowCardinality is reasonable. Why not?

**Comment by Algunenano** [comment]
IIRC the problem I found when looking into this wasn't about allowing lambda to return LowCardinality types but about allowing `arrayMap` and the rest of array operations to return a LowCardinality type (`Array(LowCardinality(String))` in this case).

I started working on this and I didn't find a way to do it without hundreds of changes, so I decided it wasn't worth the effort. There might (should?) be a better way though.
