### ISSUE TITLE
Is there any best practices for PostgreSQL to Clickhouse replication

### ISSUE THREAD

**Issue by kartaris** [ClickHouse/ClickHouse#30371]
Hi there! Is there any best practices for PostgreSQL to Clickhouse replication using MaterializedPostgreSQL engine(except setting  max_replication_slots and creating  replica index)?
Maybe there are some suggestions on changing database schema in Postgres to make Clickhouse queries more efficient?

**Comment by kssenii** [comment]
@kartaris 

For now I think I cannot give an advice to make it work faster. About performace of SELECT query -- there is not much to be done regarding that it is executed with FINAL modifier, thus not very quick. But this can be done in the future (I write it more like a TODO list to myself):
1. https://github.com/ClickHouse/ClickHouse/issues/30354
2. Now pulling replication changes is done by time and with backoff, and if there are not many changes they are not buffered but written into table at once, so if replication is not intense -- there might be many small inserts, which is bad for clickhouse. So I am planning to add settings to control rescheduling time for replication reader and a settings which will control how much rows in total must be buffered until inserted into tables (this can be done without any loss of data because of benefits of replication slots).
