### ISSUE TITLE
Whether ClickHouse supports JobSchedule 

### ISSUE THREAD

**Issue by 16601746291** [ClickHouse/ClickHouse#30480]
in sql server ，we can create job schedule, then job schedule call sql script or procedure，like this(notice  "...... "  Meas Some omitted statements)：

DECLARE @jobid uniqueidentifier, @jobname sysname, @returncode INT
SET @jobname = N'job'
BEGIN
......  
@sql_basic_dim=N'EXECUTE pro_basic_dim_merge' 
......  
@command = @sql_basic_dim 
......  
EXEC msdb.dbo.sp_add_jobschedule
         @job_id = @jobid,
         @name = 'MAIN_SCHEDULE',
         @freq_type = 4, -- every day
         @freq_interval = 1, --  
         @freq_subday_type = 0x4, -- 0x4 minute，0x8 hour
         @freq_subday_interval = 5, 
         @active_start_time = 000500; --  job start time,formate HHMMSS
......  
--  start job
EXEC @returncode = msdb.dbo.sp_start_job @job_id = @jobid
GO

so, clickhouse have like sql server similar reference  ？

**Comment by tom-clickhouse** [comment]
ClickHouse currently doesn’t have a built-in mechanism for regularly running/scheduling sql scripts.

You can set up cron jobs in linux operating systems calling the ClickHouse client in order to schedule the execution of sql scripts in ClickHouse. 

And maybe slightly related, you also can automatically get notifications from ClickHouse via [WATCH](https://clickhouse.com/docs/en/sql-reference/statements/watch/) statements when the result of a query on a [live view table](https://clickhouse.com/docs/en/sql-reference/statements/create/view/#live-view) changes due to new data in the table.

**Comment by tom-clickhouse** [comment]
There is open feature #33919 proposing automated batch jobs running queries for automated periodic imports of data into ClickHouse and automated data transformation.
