### ISSUE TITLE
Add separate packages/files for clickhouse-keeper and publish artifacts

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#30682]
Currently splitted build is only made for master. There are no stable splitted binaries. And clickhouse-keeper is only available in large binary with excessive dependencies for system libraries.
We can add splitted build for stable branches and publish binaries and packages that make sense. Start with clickhouse-keeper.

**Comment by michael1589** [comment]
Hi, may I try this issue?

**Comment by alexey-milovidov** [comment]
@michael1589 I'm not quite sure.

To make this task properly we should also split many dependencies inside ClickHouse.
Otherwise if we split 300 MB clickhouse-server to separate clickhouse-server and clickhouse-keeper, we will get 300 MB clickhouse-server and ~250 MB clickhouse-keeper.

The task in it's current form just does not make sense to do.

**Comment by michael1589** [comment]
Got it!
