### ISSUE TITLE
Support PostgreSQL style ALTER MODIFY COLUMN

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#30874]
**Use case**

PostgreSQL is using `ALTER TABLE t ALTER COLUMN c TYPE type` instead of `ALTER TABLE t MODIFY COLUMN c type`.
There is a risk that some people already get used to PostgreSQL syntax.

Let's implement it in ClickHouse.

```
tutorial=# ALTER TABLE hits_100m_obfuscated MODIFY COLUMN UserAgentMinor TEXT
tutorial-# ;
ERROR:  syntax error at or near "MODIFY"
LINE 1: ALTER TABLE hits_100m_obfuscated MODIFY COLUMN UserAgentMino...
                                         ^
tutorial=# ALTER TABLE hits_100m_obfuscated ALTER COLUMN UserAgentMinor TYPE TEXT
;
ALTER TABLE
tutorial=#
```

**Proposed implementation**

Implement it in parser level.

**Comment by cmsxbc** [comment]
some questions:

1. Does it work just a alias to currently `ALTER TABLE MODIFY COLUMN`? 
```SQL
# Current style
MODIFY COLUMN [IF EXISTS] name [type] [default_expr] [codec] [TTL] [AFTER name_after | FIRST]
# the PostgreSQL like style
ALTER COLUMN [IF EXISTS] name TYPE [type] [default_expr] [codec] [TTL] [AFTER name_after | FIRST]
```
2. If just implement it in the parser level, it will be formatted and printed as ClickHouse style, when it is executed in `clickhouse-client`, will it be ok?

3. And it seems that we need a new parser to parse the `TYPE` between `name` and declaration, because currently they are parsed together...

https://github.com/ClickHouse/ClickHouse/blob/93ed4948b43e1caeac14424409f437019621fc8d/src/Parsers/ParserAlterQuery.cpp#L116

https://github.com/ClickHouse/ClickHouse/blob/93ed4948b43e1caeac14424409f437019621fc8d/src/Parsers/ParserAlterQuery.cpp#L622-L629

https://github.com/ClickHouse/ClickHouse/blob/93ed4948b43e1caeac14424409f437019621fc8d/src/Parsers/ParserCreateQuery.h#L134-L136
