### ISSUE TITLE
Disks are almost full because of `moving` folder

### ISSUE THREAD

**Issue by OmarBazaraa** [ClickHouse/ClickHouse#30893]
We suddenly found that the disk space utilization of some of our ClickHouse machines has increased significantly from ~30% to ~70%. After doing some quick investigations, it seems that there are lots of parts in those machines in a folder called `clickhouse/data/{database}/{table}/moving` and this folder is empty in all the other machines, including the replicas.

So, I'd like to know:
1. What is the `moving` folder responsible for?
2. And most importantly, **is it safe to delete files there** to free some space?

**Clickhouse version:** 20.10.7.4

**Comment by amralaa-MSFT** [comment]
It seems that these folders are temporary and are meant to be safely deleted in case they couldn't be successfully swapped. 

I believe removal is skipped because caller method `MergeTreeData::moveParts` expects `swapClonedPart` to throw an error in case of failure in order to remove these folders
https://github.com/ClickHouse/ClickHouse/blob/fefac35befc5a20346f4a04bd96086c6196d0cbe/src/Storages/MergeTree/MergeTreeData.cpp#L5459-L5472

However, when swapping fails due to part merge or mutation, `swapClonedPart` just logs the failure message and returns with no exception as follows:
https://github.com/ClickHouse/ClickHouse/blob/fefac35befc5a20346f4a04bd96086c6196d0cbe/src/Storages/MergeTree/MergeTreePartsMover.cpp#L243-L248
