### ISSUE TITLE
Exception thrown when using sumMapFiltered on a distributed table

### ISSUE THREAD

**Issue by ivantopo** [ClickHouse/ClickHouse#30975]
**Describe what's wrong**

An exception is thrown when trying to use the `sumMapFiltered` function on a distributed table. 

**Does it reproduce on recent release?**

Yes. The tests below ran on ClickHouse 21.9.3

**How to reproduce**

Create the test tables and insert a couple rows of data:
```sql
CREATE TABLE local ON CLUSTER 'cluster_name' (
  time     DateTime,
  data     Nested(
    key      Int16,
    value    Int64
  )
) ENGINE = MergeTree()
  PARTITION BY toYYYYMM(time)
  ORDER BY time

CREATE TABLE distributed ON CLUSTER 'cluster_name' (
  time     DateTime,
  data     Nested(
    key      Int16,
    value    Int64
  )
) ENGINE = Distributed('cluster_name', 'cluster_name', 'local') 

INSERT INTO local VALUES
  (1635794296, [1, 2, 3], [10, 10, 10]),
  (1635794296, [1, 2, 3], [10, 10, 10]),
  (1635794296, [1, 2, 3], [10, 10, 10])
```

Then run this query against the distributed table:

```sql
SELECT sumMapFiltered([toInt16(1),toInt16(2)])(data.key, data.value) FROM distributed
```

**Expected behavior**

I would expect the query to return the correct aggregation value, but an error is thrown instead

**Error message and/or stacktrace**

```
Received exception from server (version 21.9.3):
Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: Syntax error (data type): failed at position 34 ('['): [1, 2]), Array(Int16), Array(Int64)). Expected one of: number, nested table, literal, NULL, identifier, data type argument, string literal, name and type pair list, list of elements, data type, list, delimited by binary operators, name and type pair: while receiving packet from [redacted]:9000: While executing Remote. (SYNTAX_ERROR)
```

**Additional context**

The exact same query works as expected when executed against the local table.

**Comment by VCCcs** [comment]
We have the exact same behavior using the version 21.3.13.9

**Comment by alexey-milovidov** [comment]
Let's invite the author, @LeoErcolanelli

**Comment by jkuklis** [comment]
Hey, I have taken a look at this problem, here are my thoughts, might be useful for someone who is going to pick up this issue:

**SUMMARY**: it seems like a problem with remote execution in general, rather than with `sumMapFiltered`.

**DETAILS**:
* `sumMapFiltered` seems to be implemented correctly
* as written in the issue, the function works well locally, but fails with distributed tables with remote shards
* `SYNTAX ERROR` is thrown when the query is parsed before sending to a remote shard
* the parser cannot process the array literal in the aggregating function parameter for the remote shard (even though array literals are accepted when invoking the query locally)
* the error is thrown in `parseQueryAndMovePosition` in src/Parsers/parseQuery.cpp, the parser issue is actually detected in `tryParseQuery` in line 293
* what is parsed for the remote shard is the initial query already processed in some way, for `sumMapFiltered([toInt16(1),toInt16(2)])(data.key, data.value)` from the issue what is processed for the remote shard is `([1, 2]), Array(Int16), Array(Int64))` - the columns listed in the second parentheses transformed into these column types, the literal from the first parentheses remained roughly the same (ignore `toInt16`, for some reason `sumMapFiltered` doesn't like unsigned ints, error is thrown with `safeGet` in `AggregateFunctionSumMapFiltered` constructor)
* I think `sumMapFiltered` is the only aggregating function which takes an array as an argument, so this problem doesn't occur with other functions
* I used https://github.com/tetafro/clickhouse-cluster configuration for a local cluster. I tried creating a "remote" shard with localhost ip, but I think it didn't act as a truly remote shard, the query would pass like for a local table
* as in the summary, the problem seems to stem from some problem with general remote execution, which might be as simple to solve as adding an attempt at using another parser variant somewhre in the query parsing, or could be more involved - hard to say without ClickHouse expertise

**Comment by alexey-milovidov** [comment]
It's a strange choice to pass an array as a parameter to `sumMapFiltered` while we have a similar function - `quantiles`, taking multiple parameters instead of an array.
