### ISSUE TITLE
a lot of  operation timeout 

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#31140]
CH version  21.8.11
We saw a lot of "operation timeout" errors in the log, such as
`2021.11.08 16:09:40.323538 [ 20338 ] {} <Error> yj_01.yst_tfeedback_record_new_LOCAL (ReplicatedMergeTreeCleanupThread): void DB::ReplicatedMergeTreeCleanupThread::run(): Code: 999, e.displayText() = Coordination::Exception: Operation timeout, path: /clickhouse/tables/yj_01/yst_tfeedback_record_new_LOCAL/1/log, Stack trace (when copying this message, always include the lines below):`

1. Only one node of  the cluster of 5 nodes reported these errors.  its average load ranks second in the cluster.
2.  I saw that all "ReplicatedMergeTree"s share a zookeeper client which is easily subject to usage conflication. Why not use a zookeeper client for each ReplicatedMergeTree? Is there any special consideration in design?

**Comment by etah000** [comment]
yes, I made a mistake. I built it from the latest 21.8 branch, the version tag is "v21.8.10.19-lts".

**Comment by alexey-milovidov** [comment]
@etah000 

It is related to network issue (timeout when communicating with remote server) or to high load.
Some moderate amount of these errors is ok, no actions required.

> I saw that all "ReplicatedMergeTree"s share a zookeeper client which is easily subject to usage conflication.

It is important to use single ZooKeeper connection, because some operations may require synchronization across tables.
ZooKeeper is "sequentially consistent", not "strict linearizeable" system and different connections may see data from different point in time that is inconsistent to each other.
