### ISSUE TITLE
Extended temporary tables (RFC).

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#31497]
1. Allow to create TEMPORARY tables with arbitrary ENGINE.
These tables will be automatically removed on session close, similarly to how regular tables are removed in Atomic database after being dropped.

2. Allow to create TEMPORARY databases. All tables created inside a temporary database are also temporary.

3. Allow to create tables and databases with limited lifetime. They will be automatically removed after specified time interval after last usage. It can be defined with some syntax like `DROP AFTER ...`, not to be confused with temporary tables and tables' data TTL. These tables are visible to all clients.

**Additional context**

Can we make tables with limited lifetime available only for user who created them - with appropriate setting of RBAC rules?

See also #31496

**Comment by Lirikl** [comment]
I want to take this task

**Comment by ilejn** [comment]
We (Arenadata) are interested in p. 1

BTW, is not it possible to bind a number of queries to a session to be executed when the session is terminated to generalize  p. 1 and p. 2 ? 
Like defer in golang.
_create temporary table aaa_ may be a syntax sugar for _create table aaa_ + _defer drop table aaa_ in this paradigm.

**Comment by alexey-milovidov** [comment]
@ilejn This task is not in progress.

**Comment by ilejn** [comment]
Please, assign this issue to my colleague @rvasin

**Comment by tavplubix** [comment]
GitHub does not allow to assign issues to external contributors unless they commented on the issue

**Comment by rvasin** [comment]
Please assign me to this issue.

**Comment by rvasin** [comment]
Hi, I am working on No. 1:
> 1. Allow to create TEMPORARY tables with arbitrary ENGINE.

Here is my branch:
https://github.com/arenadata/ClickHouse/tree/ADQM-639

Please consider it as a draft/prototype. 

Could you please take a look? I see @serxa was working recently with tables engines, @rschu1ze and @den-crane maybe also interested in in too.

The main idea is to use `StorageFactory` to create temporary tables with arbitrary engine. 
And inside `_temporary_and_external_tables` database (which is `Memory` type of databases) we may create any types of table engines.

Then in case of a sudden server shutdown `MergeTree`, `Log` etc tables will leave some traces in `/var/lib/clickhouse/data/_temporary_and_external_tables`

So the approach is simple: on the next server startup it will remove the folder:
`/var/lib/clickhouse/data/_temporary_and_external_tables`
Thus there are no traces left. I think it's OK because there is no metadata left for temporary tables on the sudden server shutdown. Thus everything left in .`/var/lib/clickhouse/data/_temporary_and_external_tables` is not important and we may remove it. 

Right now the branch works well for `Memory` engine and for `MergeTree` engine. For example:

```
CREATE TEMPORARY TABLE temp_table_3
   (
     id UInt64,
     column1 String
   )
ENGINE = MergeTree()
ORDER BY id
PRIMARY KEY id;
insert into temp_table_3 values (1, 'a'), (2, 'b'), (3, 'c');
select * from temp_table_3;
drop TEMPORARY TABLE temp_table_3;
```

It also works for `Log` engine but right now it does not cleanup data path folder. If `MergeTree` temporary table uses `dropAllData()` for cleanup then for Log engine right now it does not cleanup in `DatabaseMemory::dropTable()` probably because of using relative paths for data path. I will correct it later.

I did not test it yet with other engines. But theoretically it should work too. The main discussion questions: 
1. Can we use temporary tables for Replicated* engines?
2. Can we use temporary tables for Distributed engine?
3. Can we use temporary tables with ON CLUSTER keywords? 
4. Can we use temporary tables with Integration Engines?

**Comment by ilejn** [comment]
Hello @rvasin , great!
As far as I know Arenadata needs (2).
I would opt out of (4) or at least postpone, it might be too risky/complicated.
About (1). On the one hand it seems useful, on the other hand the idea to cleanup something in zookeeper upon a user session termination is worrying.
(3) may be nice to have.

**Comment by rvasin** [comment]
Commented more changes: both MergeTree and Log table engines correctly remove data on explicit DROP TEMPORARY TABLE and on session end.

**Comment by alexey-milovidov** [comment]
Please don't hesitate to send a PR.

**Comment by tavplubix** [comment]
> Then in case of a sudden server shutdown MergeTree, Log etc tables will leave some traces in /var/lib/clickhouse/data/_temporary_and_external_tables
> So the approach is simple: on the next server startup it will remove the folder:
/var/lib/clickhouse/data/_temporary_and_external_tables
> Thus there are no traces left. I think it's OK because there is no metadata left for temporary tables on the sudden server shutdown. Thus everything left in ./var/lib/clickhouse/data/_temporary_and_external_tables is not important and we may remove it.

If a table has a UUID (AFAIR all temporary tables have it) then it will actually store data in `/var/lib/clickhouse/store/xxx/<uuid>` and `/var/lib/clickhouse/data/_temporary_and_external_tables` will be a symlink. But unused dirs in `store/` will be eventually cleaned up: https://github.com/ClickHouse/ClickHouse/blob/6eb557b2ba6e837c60678b1f583202f48fb1223a/src/Interpreters/DatabaseCatalog.cpp#L1118

**Comment by rvasin** [comment]
The important thing: 

https://clickhouse.com/docs/en/engines/database-engines/atomic#table-uuid
> All tables in database `Atomic` have persistent UUID and store data in directory /clickhouse_path/store/xxx/xxxyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy/, where xxxyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy is UUID of the table

So as I understand store/xxx/ plus symlinks to data/ are used only in `Atomic` engine. 
But for temporary tables we use `Memory` database engine. In `Memory` database engine we don't use store/ and we put tables directly into data/db_name/table_name (for the case then tables stores data on disk).
It means that the approach in my branch is probably correct.

**Comment by alexey-milovidov** [comment]
@tavplubix We need to make the Memory database also Atomic to allow CREATE OR REPLACE, EXCHANGE, atomic DROP, and avoid losing the cache on RENAME in clickhouse-local.

**Comment by rvasin** [comment]
Hi, I mentioned above I created PR #46071 
If needed I may refactor it as needed. For example now I disabled Replicated table engines for temporary tables.
