### ISSUE TITLE
Seek Help: ClickHouse memory grows indefinitely

### ISSUE THREAD

**Issue by 1014660991** [ClickHouse/ClickHouse#31610]
test method：Create 3000 tables, delete them ten minutes later, and repeat，for a day or so, the memory footprint is 40%
clickhouse version：21.4.6.55
Server Configuration：4 core 8 GB

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/tips/#ram



_Attention

If your system has less than 16 GB of RAM you may experience various memory exceptions because default settings does not match this amount of RAM. Recommended amount of RAM is 32 GB or more. You can use ClickHouse in system with small amount of RAM, even with 2 GB of RAM, but it requires an additional tuning and able to process small ingestion rate._

**Comment by 1014660991** [comment]
I have a server that is configured with 16 core 32 GB but has the same problem.
Some of the clickhouse-server configurations are:
config.xml:
  <total_memory_profiler_step>4194304</total_memory_profiler_step>
<uncompressed_cache_size>8589934592</uncompressed_cache_size>
 <mark_cache_size>3221225472</mark_cache_size>
 <mmap_cache_size>1000</mmap_cache_size>

user.d/user.xml
<max_bytes_before_external_group_by>2000000000</max_bytes_before_external_group_by>
<max_memory_usage>4000000000</max_memory_usage>
 <max_execution_time>3600</max_execution_time>
<load_balancing>random</load_balancing>
<max_query_size>262144000</max_query_size>
<max_ast_elements>1000000</max_ast_elements>
<max_expanded_ast_elements>1000000</max_expanded_ast_elements>

@den-crane

**Comment by den-crane** [comment]
Do you have some evidences, that memory grows indefinitely?

21.4.6.55 is obsolete. 

>3000 tables

What engine did you use?

**Comment by 1014660991** [comment]
table engine: MergeTree 
We tested it with 21.11.3.6 and had the same problem.
test method：Create 3000 tables, delete them ten minutes later,  then Create 3000 tables, delete them ten minutes later ,and repeat
