### ISSUE TITLE
What's the use of written_offset_columns?

### ISSUE THREAD

**Issue by fanhualta** [ClickHouse/ClickHouse#31649]
Recently I have read the source code of the writing process. I wonder about the use of `written_offset_columns` in class `MergeTreeDataPartWriterOnDisk.h`. 
![image](https://user-images.githubusercontent.com/26211279/142966242-764cdbbb-971d-41c9-9fab-4733ef9cb303.png)

It seems to deal with nested type when merging in the vertical algorithm, but the variable is always empty because value passing is always been used(such as in `MergeTreeDataPartWriterWide.cpp`, as shown in the figure below). Can someone explain more details? What scenario is the variable used for? thanks.
![image](https://user-images.githubusercontent.com/26211279/142966067-cd5ad824-64a3-4c8e-8fc9-c44810e7ed9b.png)

**Comment by CurtizJ** [comment]
You are right, `written_offset_columns` is used to store already written shared offsets for `Nested` type. 

Looks like it's a bug and offsets are rewritten several times now, but actually shouldn't. Of course in place that you mentioned we should get mutable reference for offsets instead of copy. Thanks that you noticed it.

**Comment by fanhualta** [comment]
> You are right, `written_offset_columns` is used to store already written shared offsets for `Nested` type.
> 
> Looks like it's a bug and offsets are rewritten several times now, but actually shouldn't. Of course in place that you mentioned we should get mutable reference for offsets instead of copy. Thanks that you noticed it.

Can you show me a concrete example? For a Nested type, for example, Array(Array(int)), why do we need to store written offset? As I understand it, in Vertical merge algorithm, each column will be written once.

**Comment by CurtizJ** [comment]
`Nested` is not an `Array(Array(Int))`, but is a syntax sugar for `Array(Tuple(...)` (https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested/) and by default this structure is flattened to several arrays with dot delimiter. 

E.g.

```sql
CREATE TABLE t_nested
(
    `id` UInt32,
    `n` Nested(a UInt32, b UInt32)
)
ENGINE = MergeTree
ORDER BY id;


SHOW CREATE TABLE t_nested;

CREATE TABLE default.t_nested
(
    `id` UInt32,
    `n.a` Array(UInt32),
    `n.b` Array(UInt32)
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192 
```
All arrays of `Nested` should have the same sizes. So `n.a` and  `n.b` are separate `Array` columns, but have the same sizes and we store one subcolumn `n.size0` instead of two: `n.a.size0` and `n.b.size0`.

**Comment by fanhualta** [comment]
> `Nested` is not an `Array(Array(Int))`, but is a syntax sugar for `Array(Tuple(...))` (https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested/) and by default this structure is flattened to several arrays with dot delimiter.
> 
> E.g.
> 
> ```sql
> CREATE TABLE t_nested
> (
>     `id` UInt32,
>     `n` Nested(a UInt32, b UInt32)
> )
> ENGINE = MergeTree
> ORDER BY id;
> 
> 
> SHOW CREATE TABLE t_nested;
> 
> CREATE TABLE default.t_nested
> (
>     `id` UInt32,
>     `n.a` Array(UInt32),
>     `n.b` Array(UInt32)
> )
> ENGINE = MergeTree
> ORDER BY id
> SETTINGS index_granularity = 8192 
> ```
> 
> All arrays of `Nested` should have the same sizes. So `n.a` and `n.b` are separate `Array` columns, but have the same sizes and we store one subcolumn with offsets `n.size0` instead of two: `n.a.size0` and `n.b.size0`.

I got it, thanks very much
