### ISSUE TITLE
avgWeighted return wrong result with Decimal value, and float weight

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#31768]
```sql
SELECT avgWeighted(CAST(-398., 'Decimal(38, 10)'), CAST(0.05453896522521973, 'Decimal(38,10)')) AS x; 
-- ok -398 

select avgWeighted( CAST(-398., 'Decimal(38, 10)'),  CAST(0.05453896522521973, 'Float64') ) as x;
-- wrong! 0 


SELECT avgWeighted(CAST(-398., 'Float64'), CAST(0.05453896522521973, 'Decimal(38,10)')) AS x
-- ok: -398

SELECT avgWeighted(CAST(-398., 'Float64'), CAST(0.05453896522521973, 'Float64')) AS x
-- ok: -398
```

**Comment by tavplubix** [comment]
The bug is here: https://github.com/ClickHouse/ClickHouse/blob/3401b32e37357e68f0cd85c6626f78e2c425bafc/src/AggregateFunctions/AggregateFunctionAvgWeighted.h#L41

Seems like it initially was implemented incorrectly in #15419
When `Weight` is `double` and `Numerator` is `Decimal128` static cast does not actually cast double to decimal, it works more like reinterpret cast

cc: @myrrc

**Comment by j-f-r** [comment]
> When `Weight` is `double` and `Numerator` is `Decimal128` static cast does not actually cast double to decimal, it works more like reinterpret cast

I don't think that the problem is in this cast.
```
select avgWeighted(toDecimal64(number, 9), toDecimal64(number, 9)) from numbers(0)
```
Throws the same error.

In fact
```
select avgWeighted(toDecimal256(number, 9), toDecimal128(number, 9)) from numbers(1)
```
does not throw an error.

Which indicate that the problem is in
https://github.com/ClickHouse/ClickHouse/blob/3401b32e37357e68f0cd85c6626f78e2c425bafc/src/AggregateFunctions/AggregateFunctionAvg.h#L55

**Comment by tavplubix** [comment]
@j-f-r, it's different issues, #31768 is about incorrect result due to incorrect cast and #32053 is about crash due to integer division by zero. But the cause of both issues is that Decimal support was implemented incorrectly (and, unfortunately, it's too late to revert it as suggested in https://github.com/ClickHouse/ClickHouse/issues/26732#issuecomment-885787213).

**Comment by UnamedRus** [comment]
>  (and, unfortunately, it's too late to revert it as suggested in #26732 (comment)).

But we have versioning of aggregate functions now.

Can we just implement new version with correct implementation?

https://github.com/ClickHouse/ClickHouse/pull/24820

**Comment by filimonov** [comment]
so right now if the nominator (or the sum) is decimal we also assume that denominator part (or the count) should also be decimal. And if the denominator part is actually afloat wrong casing happens.

**Comment by filimonov** [comment]
The safe workaround is using either decimal as both args of avgWeighed, either floats, but not a combination of them.

**Comment by alexey-milovidov** [comment]
Writing `sum(x * weight) / sum(weight)` will be more precise and faster.

**Comment by myrrc** [comment]
I'll look at this bug
