### ISSUE TITLE
Stored procedures

### ISSUE THREAD

**Issue by gotlium** [ClickHouse/ClickHouse#32]
Hi, what about stored procedures/functions/procedural languages?

**Comment by alexey-milovidov** [comment]
Is is umbrella issue.
Lets look at different possible features that are related to stored procedures.

1. User defined functions and aggregate functions.
Discussed here: https://github.com/yandex/ClickHouse/issues/11

2. User defined streaming transformations of data.
Like mapreduce. Definitely makes sense.
But it is a different scenario relative to typical ClickHouse usage for online queries from web interface.
We don't want to re-implement Hadoop Mapreduce.

3. Stored procedures with multiple queries and control flow logic.
Its questionable. Control flow logic consists of loops and conditional statements.
Loops are discouraged for analytical database because processing of O(n) simple queries is usually worse than processing few hard queries.
Much easier to implement that "glue" control flow logic outside of the database.

4. Processing of multiple queries at once or from single data snapshot.
For example, to create report with many tables and diagrams from consistent data.
Nice feature, need to implement. It's very loosely related to stored procedures.

5. Saved parametrized expressions and statements.
For example, to define aggregate function like this: `anyRandom(x) = argMax(x, rand())`
Also, it's nice to have configurable per user basis query rewriting rules, to dynamically rewrite "bad" queries to good ones.

**Comment by gotlium** [comment]
My case: I have one realtime data table and once on day on background I insert all data from realtime table to persistent pre-calculated OLAP table. For this case will be super if I call from code simple procedure to calculate and insert data to OLAP table.

**Comment by Rostish** [comment]
Hi!
Could you update status for stored procedure feature?

**Comment by blinkov** [comment]
@Rostish afaik nothing new here

**Comment by stigsb** [comment]
Could this be doable as a macro instead? Like a preprocessing step before the actual query parsing?

**Comment by crakjie** [comment]
Is stored expression a possible feature ?

`CREATE TABLE Toto
(
    `id` String,
    `fn` Int32 => Int32
)
ENGINE = Memory()
`
The idea is to in one query both data preparation and selecton. Data preparation depending on the row and some dynamic value.

**Comment by alexey-milovidov** [comment]
Superseded by https://github.com/ClickHouse/ClickHouse/issues/33919.
