### ISSUE TITLE
URLPathHierarchy with redirect query parameters not working as expected

### ISSUE THREAD

**Issue by tybirk-accuranker** [ClickHouse/ClickHouse#32272]
**Describe the unexpected behaviour**

When using URLPathHierarchy the urls are also split on an url provided in a query parameter, e.g.

```
select URLPathHierarchy('https://www.abc.com/lorem/dolor?created_at=1587106230&url=https://www.abc.dk/lorem/')
```

gives an array like
```
[
  '/lorem/',
  '/lorem/dolor?',
  '/lorem/dolor?created_at=1587106230&url=https:/',
  '/lorem/dolor?created_at=1587106230&url=https://www.abc.dk/',
  '/lorem/dolor?created_at=1587106230&url=https://www.abc.dk/lorem/'
]
```

where the desired result (in my opinion) would be

```
[
  '/lorem/',
  '/lorem/dolor?',
  '/lorem/dolor?created_at=1587106230&url=https://www.abc.dk/lorem/'
]
```

**Comment by alexey-milovidov** [comment]
In fact this is expected behaviour, if we look into perspective of how this function is used.
This function is needed to provide hierarchical reports by website content in metrica.yandex.com
And for this purpose it is reasonable to split by paths even inside query parameters or fragment identifiers.

The docs should be updated.
