### ISSUE TITLE
max_memory_usage cannot limit some query

### ISSUE THREAD

**Issue by lelezhan** [ClickHouse/ClickHouse#32334]
About memory usage in ClickHouse and here is my question

max_memory_usage in users.xml was set to 100
<img width="881" alt="image" src="https://user-images.githubusercontent.com/50923457/144996188-3bb78e47-34ac-4c3c-a72d-70dd477c6e92.png">
When I execute a simple distinct query, it can be limited and throw exception
 select distinct(group_name) from aa.testTable; 
![image](https://user-images.githubusercontent.com/50923457/145010409-e2a56752-fbdc-41d4-a98a-ef588b1f8aae.png)
However，When I execute the  group by query, it can be executed successfully, and it used 446.34 MB memory
 select group_name,  count(*) from aa.testTable;
![image](https://user-images.githubusercontent.com/50923457/145010481-196c35e6-2380-45d4-a3eb-05ef1efba448.png)

Why max_memory_usage can not limit such query?

Another question is, since clickhouse set default max_server_memory_usage=(total memory)*0.9, when some big join query happened, why server's memory usage might higher than default max_server_memory_usage  value and clickhouse server crash down? Is Memory tracker can not track memory accurately?

**Comment by genzgd** [comment]
The 446.34 MB number in the result line `Process 23.24 million rows, 446.34 MB` does not represent the memory used, it represents the amount of data read from disk.  Also a setting of 100 bytes is too small to provide a useful test, and the different between 113 rows with distinct() vs all 116 rows with  GROUP BY with that tiny limit could just be the result of a minor differences in how ClickHouse processes the query.

As for your second question, there were some edge cases where ClickHouse could run out of memory despite the max_server_memory_usage value.  See https://github.com/ClickHouse/ClickHouse/issues/33004.  This should be fixed in the latest ClickHouse release.  In general however, large joins can cause problems because at least one of the joined result sets must be loaded entirely into memory.
