### ISSUE TITLE
How stable is ClickHouse's on-disk file format?

### ISSUE THREAD

**Issue by bnaecker** [ClickHouse/ClickHouse#32491]
How often does the on-disk file format change? Does ClickHouse provide any guarantees about the format's stability? For example, can the format change between minor revisions (21.x -> 21.y) or major revisions (20.x -> 21.y)? If the format does indeed change, is this documented in the changelog or another location when it occurs?

For context, we are developing systems in which we may upgrade ClickHouse. We'll need to understand when these upgrades may be done simply by updating the application but keeping the data files unchanged, and when such an upgrade will require more involved export and re-import of the data into a new on-disk format.

I could not find any notes about this topic in the documentation sections related to [backup](https://clickhouse.com/docs/en/operations/backup/) or [upgrade](https://clickhouse.com/docs/en/operations/update/). Adding details on these pages about this topic might help future users as well.

Thanks!

**Comment by den-crane** [comment]
All files are backward compatible. Any new version of Clikhouse able to read any files from the previous versions.
The reason of that is that parts / files are immutable and Clikhouse does not convert files when you install a new version.
So the table created in 2016 can contain parts created by version 1.1.5431 and by 21.11 simultaneously.

The new versions are Clikhouse able to use new features and use new datatypes, and new types files or compressors so parts are not forward compatible. 
But even with 21.11 you can configure your MergeTree table and disable new features and create parts compatible with version 1. It's not true about Replicated tables because the structure of metadata in ZK has changed.
