### ISSUE TITLE
Lazy marks loading

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#32505]
When ClickHouse reads MergeTree data from disk it uses [MergeTreeReaderStream](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeReaderStream.cpp) for each column.

Data readers/streams are initialized before any actual data reading is done. MergeTreeReaderStream opens mark files to pre-compute a buffer size as an optimization for small reads.

When [PREWHERE](https://clickhouse.com/docs/en/sql-reference/statements/select/prewhere/) feature is used some columns within some parts can get excluded from reads. In the case that happens, the initialization and marks reads done in MergeTreeReaderStream are thrown away.

It is possible to delay that initialization until the marks are actually needed (eg by moving the initilization from the constructor to a method which is called to initialize data_buffer). This improves performance in some edge cases where marks don't fit the cache and PREWHERE is very effective.

Or, maybe the lazyness can be lifted even higher than MergeTreeReaderStream?

_behaviour confirmed on 21.8_

**Comment by den-crane** [comment]
Also Clickhouse reads .mrk file at whole. But currently .mrk files are not compressed and it's possible to read only part / required rows from .mrk file.
The problem that building of a mark table in memory is very slow.

```sql
CREATE TABLE IF NOT EXISTS t ( a Int64, s String, s1 String, s2 String, s3 String, s4 String ) ENGINE = MergeTree ORDER BY (a) SETTINGS index_granularity=64;
insert into t(a) select number from numbers(5000000000);

system drop mark cache;

SELECT * FROM t WHERE a=42;
1 rows in set. Elapsed: 0.407 sec.

SELECT * FROM t WHERE a=42;
1 rows in set. Elapsed: 0.002 sec.
```

**Comment by nvartolomei** [comment]
Reading subset of marks seems doable. E.g. if we know that we need mark 34 to 76 we can just compute the offsets in the file 34 * 16 (or 24 for adaptive granularity) and read until 76 * 16 (24 respectively) (+/- 1). That would complicate caching a bit. 

If compression is to be added on top, we'll need a mark file for the mark file? :) Somewhat related PR that adds in-memory compression #30434.

**Comment by den-crane** [comment]
BTW, I believe/I suspect the reading and seeking in mrk even compressed mrk is not the reason of the poor performance.
I think the root cause that CH builds a huge table (c++ array or something) in memory and it takes time because it's huge or not optimized.

**Comment by nvartolomei** [comment]
Data point: reading from a table with `index_granularity_bytes = 0` is twice as fast in this scenario.

**Comment by alexey-milovidov** [comment]
@nvartolomei 

Yes, we can postpone reading .mrk files after initialization. Let's do it.

I don't recommend to implement partial reading of .mrk files for these reasons:
- the code will become more complicated;
- the use case when it will give benefits is limited;
- it will complicate implementation of compressed marks.

Yes, we want to implement compressed marks. It should be very easy.
And we can always use zstd with some decent level (e.g. 3), because the files are small.

This task has low priority, because usually the size of marks is negligible.

Side notes:
- for data skipping indices we want to implement hierarchical aggregations;
- for in-memory format of marks we want to implement ad-hoc compression #30434;
- we want to avoid reading of index columns if their value is guaranteed to be constant from the primary key.

**Comment by den-crane** [comment]
solved https://github.com/ClickHouse/ClickHouse/pull/36879
