### ISSUE TITLE
Existing Data in Table gets corrupted when more data imported with insufficeint disk space.

### ISSUE THREAD

**Issue by nadarkathiresh** [ClickHouse/ClickHouse#3250]
I tried to import data into a table which already had data. The disk space was running low and by mistake i tried importing more data. The import failed with error.

When the check the data in column some data partially imported, but when running aggeregate queries the queries started to fail & it could not read the full table.

Due to this the whole table needed to be replaced.

**Comment by alexey-milovidov** [comment]
What table engine do you use?

This issue should not happed if you use `MergeTree` family of table engines. Appends are atomic and table should be always in physically consistent state; moreover, it will do automatic repair if data is rendered broken in filesystem.

But it may be considered normal if you use `Log` family of table engines, because writes are non-atomic, as documented.

**Comment by blinkov** [comment]
@nadarkathiresh have you tried switching to MergeTree engine?
