### ISSUE TITLE
live view query using java client

### ISSUE THREAD

**Issue by sigirisetti** [ClickHouse/ClickHouse#32547]
Hi all 

I am able to run most of the queries using clickhouse yandex driver for java. Any one tried creating live view and receiving periodic updates using java clients? Any reference page/example is great

Thanks all

**Comment by den-crane** [comment]
You should ask it in https://github.com/ClickHouse/clickhouse-jdbc
The problem that `watch` is impossible to use it with jdbc-http because it returns a result when a command has finished, but `watch` never finished, and it's impossible to get intermediate results. Probably it will be possible with a new jdbc-grpc driver.
