### ISSUE TITLE
The group by field is not correctly identified during aggregation query

### ISSUE THREAD

**Issue by h1k** [ClickHouse/ClickHouse#32639]
**Describe what's wrong**
The group by field is not correctly identified during aggregation query

**Does it reproduce on recent release?**
21.8.12.29-lts
**How to reproduce**
* Which ClickHouse server version to use
21.8.10.19-lts , 21.8.12.29-lts
```
create table groupby_test(id Int8)
engine=MergeTree
Order by tuple();
```
```
insert into groupby_test values (1),(2);
```
```
select multiIf(1=2 and id>0,1,2) as a ,sum(id) from  groupby_test GROUP BY a;
```
**Expected behavior**
| 2 | 3 |
**Error message and/or stacktrace**
Column `id` is not under aggregate function and not in GROUP BY: While processing mulitIf((1=2) AND id>0,1,2) as a,sum(id).

**Comment by alexey-milovidov** [comment]
Minimal reproducing example:

```
SELECT 0 AND id ? 1 : 2 AS a, sum(id) FROM (SELECT 1 AS id) GROUP BY a;
```

**Comment by KochetovNicolai** [comment]
My understanding what is going on:
* expression `0 AND id ? 1 : 2 AS a` is detected as constant
* `GROUP BY` is removed because `a` is constant and there is `sum` function
* query now looks like `SELECT 0 AND id ? 1 : 2 AS a, sum(id) FROM (SELECT 1 AS id)`
* now, `0 AND id ? 1 : 2 AS a` is not a key and depend on `id` which is not under aggregate function

It probably works for other cases if AST optimization can detect that expression (in case of `0 AND id ? 1 : 2 AS a` it can't).

I have no idea how to fix it.
The possible way - remove group-by-constant-key optimisation completely (or make it somewhere else)
