### ISSUE TITLE
Documentation around LTS releases

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#32636]
Hello and thanks for developing Clickhouse.

According to [the Ops FAQ](https://clickhouse.com/docs/en/faq/operations/production/#how-to-choose-between-clickhouse-releases) LTS is released twice a year.

Yet, the [github tags](https://github.com/ClickHouse/ClickHouse/releases?expanded=true&page=2&q=lts) show frequent patch version releases and multiple release trains.

Could you kindly clarify in the documentation:
- Are users expected to pin down a given major+minor version and update to the last available patch version?
- Are LTS releases (and backports) tested more extensively than stable releases?
- Are there guarantees of backward compatibility between different minor versions?
- What type of fixes are backported other than security patches? Specifically, is backward compatibility guaranteed?

As a side note, is there any plan to provide longer LTS? Various software projects commonly use the term "LTS" to refer to 3, 5 or 10 years.

**Comment by alexey-milovidov** [comment]
> Are users expected to pin down a given major+minor version and update to the last available patch version?

Users may prefer to stay on LTS version and only install patch releases. Or to install newer releases regardless to LTS version.

> Are LTS releases (and backports) tested more extensively than stable releases?

Newer releases are better tested, because more tests and more extensive testing techniques are added over time. Newer tests are not applied and not applicable to older LTS releases.

The customers that have installed and using LTS version for a significant time period will find that the installed version is better *de-facto* tested in their production environment than any newer version. But this does not relate to the release readiness testing.

> Are there guarantees of backward compatibility between different minor versions?

We guarantee backward compatibility on data formats and protocols for all versions.

Different versions may introduce the following changes:
- changes in undocumented behavior and corner cases; example: #31390
- changes in low-level system introspection capabilities; example: #32336
- changes in experimental features; example: #26233
- if different versions of ClickHouse are operating in the same cluster, some distributed queries may stop to work during the upgrade operation: #26030
- unintentional changes.

> What type of fixes are backported other than security patches? Specifically, is backward compatibility guaranteed?

We backport security and stability fixes. Until recently, other bugfixes were also backported if they are easy to backport. But we are aiming to avoid backporting insignificant bugfixes if workaround is available.

These backports don't affect compatibility in most of the cases, although there are a few records when some behaviour in a corner case has been unintentionally affected by backports.

If you need all the behaviour to be unaltered, including subtle changes in resourse utilization in undocumented corner cases, you can simply avoid any changes in your production environment, and only install new version if you find the patches relevant to you.

Even installing a small patch does not guarantee that your production environment will not be affected.

There is an anecdotal case when updating a version introduced a failure in one customer's environment. After investigation, we figured out that the failure was caused by fixing a performance issue in ClickHouse. After installing a patch, ClickHouse becomes faster. The customer was running a script that queried ClickHouse in infinite loop (one query after another) and then pushed the results to another system. Due to the fact that performance of ClickHouse was significantly improved, the other client's system has been overloaded by the script, and that led to failure.

> As a side note, is there any plan to provide longer LTS? Various software projects commonly use the term "LTS" to refer to 3, 5 or 10 years.

We have no plans to apply patches for more than a year. ClickHouse codebase is rapidly changing and backporting patches to very old versions requires many efforts and introduce unnecessary risks.
