### ISSUE TITLE
keep_free_space_bytes is inoperative.

### ISSUE THREAD

**Issue by wlacp** [ClickHouse/ClickHouse#32738]
This is my setting. it's working. but my disk is become 0 byte. so what can I do?

<yandex>
  <storage_configuration>
    <disks>
      <vdc>
        <path>/data01/log/clickhouse-server/</path>
        <keep_free_space_bytes>322122547200</keep_free_space_bytes> 
      </vdc>
      <vdb>
        <path>/data/log/clickhouse-server/</path>
        <keep_free_space_bytes>322122547200</keep_free_space_bytes> 
      </vdb>
    </disks>
    <policies>
      <hdd_in_order>
        <volumes>
          <hot>
            <disk>vdb</disk>
            <max_data_part_size_bytes>53687091200</max_data_part_size_bytes> 
          </hot>
          <cold>
            <disk>vdc</disk>
          </cold>
        </volumes>
        <move_factor>0.8</move_factor> 
      </hdd_in_order>
    </policies>
  </storage_configuration>
</yandex>

**Comment by wlacp** [comment]
![1639449902425](https://user-images.githubusercontent.com/34258886/145923712-9b9ded10-f058-4570-a723-05f92d7d24f2.png)
![1639449905832](https://user-images.githubusercontent.com/34258886/145923736-915dcea5-b7db-46f7-bcb1-019fded0c8e5.png)

**Comment by wlacp** [comment]
My keep_free_space is 200GB, butthe free_space is 0

**Comment by den-crane** [comment]
it's expected. 

Parts can be moved only into one direction. From smallest priority volume to the highest.
You have policy `hdd_in_order` with 2 volumes `hot (vdc) priority=1` -> `cold (vdb) priority=2`. Your cold disk (vdb) priority=2 is out of space. But there is no volumes with higher priority.

Or you misconfigured you policy and made hot->cold instead of 2 cold `round-robin`
