### ISSUE TITLE
Consider removing the "nullable primary key" feature

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#32780]
(Until it will be properly fixed).

Proper DBMS don't allow nullable primary key.

The feature was initially questionable: #12455
Then multiple defects appeared: #28269, #28636, #31823, #27197, #27250
Some of them are not resolved after three months: #32765, #28769, #22585
Not many users are using nullable primary key in production.

Now people demand backporting some of the fixes for this feature to LTS releases
(that is not welcomed due to low quality of this feature and the importance of keeping releases sane).

**Comment by alexey-milovidov** [comment]
Let's make a deadline of Dec 31.
We need to clear the following checklist:
- [ ] #32765
- [ ] #28769
- [ ] #22585

**Comment by amosbird** [comment]
Both #28769 and #32765 are not because of #12455 but on the contrary due to not have it. Nullable primary keys are allowed in #12443 starting from version 20.7, while #12455 is landed in version 21.9. It's too late to backport the entire #12455 to 21.8. I'll instead make a dedicated fix for the LTS version.

Nullable keys are generally not recommended. But the feature also allows nullable skip indices. And AggregatedMergeTree would also get benefits. I'll do the following before the deadline on behalf of the nullable primary key feature:

- [ ] Add a pedantic guard to avoid nullable keys being mistakenly allowed, like the situation of https://github.com/ClickHouse/ClickHouse/issues/22585 and https://github.com/ClickHouse/ClickHouse/issues/28769#issuecomment-927232969

- [ ] Fix the serde issue that https://github.com/ClickHouse/ClickHouse/issues/22585 exposes.

- [ ] Add more tests with different types and merge tree kinds, plus randomly generated data.

- [ ] Document the risk of the MergeTreeSetting: `allow_nullable_key` and it's main use cases.

**Comment by alexey-milovidov** [comment]
Good, thank you!

By the way, it is not needed to backport something around nullable primary key in 21.8.
The users of nullable primary key should feel free to upgrade to the stable versions instead of LTS.
