### ISSUE TITLE
clickhouse-keeper not installed by Debian package 21.11.6.7

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#32863]
Hello,
The `clickhouse-server` Debian package at version `21.11.6.7` installs the following binaries without clickhouse-keeper (and without a systemd unit file to run it):
```
/usr/bin/clickhouse-report
/usr/bin/clickhouse-copier
/usr/bin/clickhouse-server
```
(Workaround: create a symlink to /usr/bin/clickhouse-server)

**Comment by den-crane** [comment]
21.11.6.7
all applications of clickhouse are the symlinks to the single binary

just run `ln -s /usr/bin/clickhouse /usr/bin/clickhouse-keeper`

then you will be able to use `clickhouse-keeper`

Or install new stable 21.12.2.17 it should have  `clickhouse-keeper` because  `clickhouse-keeper` is officially released today.

**Comment by windylcx** [comment]
i use the rpm to install ,but not found clickhosue-keeper of version  21.12.3.32-2

**Comment by alexey-milovidov** [comment]
I have fixed it.
