### ISSUE TITLE
After DB::Exception, clickhouse ask password again.

### ISSUE THREAD

**Issue by SunguckLee** [ClickHouse/ClickHouse#3326]
I had run the query with tailing "FORMAT VERTICAL", But clickhouse server throw DB::Exception.
```
Exception on client:
Code: 73. DB::Exception: Unknown format VERTICAL
```

After this error, clickhouse client ask password agiain like this.
```
ch_7 :) select version();

SELECT version()

┌─version()─┐
│ 18.12.17  │
└───────────┘

select * from matt FORMAT VERTICAL;

Exception on client:
Code: 73. DB::Exception: Unknown format VERTICAL

Password for user matt_lee:
Connecting to database matt at localhost:9000 as user matt_lee.
Connected to ClickHouse server version 18.12.17 revision 54407.

ch_7 :)
```

But there's no password asking when syntax error of the other query. Is this really connection is closed ? 
And one more thing is that why upper-case "VERTICAL" is not allowed ?

**Comment by filimonov** [comment]
> clickhouse ask password again

Sounds like a bug connected to #2293.
Just to ensure - you call clickhouse-client with `--ask-password`, do you?

> And one more thing is that why upper-case "VERTICAL" is not allowed ?

[By design](https://clickhouse.yandex/docs/en/query_language/syntax/#keywords): _Keywords (such as SELECT) are not case-sensitive. Everything else (column names, functions, and so on), in contrast to standard SQL, is case-sensitive._

**Comment by SunguckLee** [comment]
> Just to ensure - you call clickhouse-client with --ask-password, do you?
Yes

**Comment by alexey-milovidov** [comment]
clickhouse-client reconnects to the server on client-side errors. This is required due to possible protocol desynchronization errors.
Asking of password is necessary because client does not keep entered password for further reuse, because it's insecure
(but it can still reside in memory).

Although reconnection is not necessarily in your particular case, it is handled as a generic case.

**Comment by alexey-milovidov** [comment]
Fixed.

**Comment by alexey-milovidov** [comment]
Not fixed.

**Comment by alexey-milovidov** [comment]
Does not reproduce.
