### ISSUE TITLE
clickhouse regexp extract

### ISSUE THREAD

**Issue by xugege1** [ClickHouse/ClickHouse#33280]
*?ActivityJunBCJ&amp;a=payment(|M)&amp;id=(\\d+)(&amp;.*?){0,}&amp;fromTypes=(\\d+)(&amp;.*?){0,}

How to use regexp extract to fromTypes ?

**Comment by xugege1** [comment]
I transferred from impala, impala's regexp_extract can do it, but clickhouse did not find a similar method

**Comment by lingnancfy** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/string-search-functions/#matchhaystack-pattern

**Comment by den-crane** [comment]
`\` is an escape character in CH strings, you need double them `\\`

**Comment by alexey-milovidov** [comment]
@den-crane You will be surprised... single escaping also works.

**Comment by den-crane** [comment]
> @den-crane You will be surprised... single escaping also works.

@alexey-milovidov Ok. Good to know.

Should I fix the documentation? 

_Note that the backslash symbol (\) is used for escaping in the regular expression. The same symbol is used for escaping in string literals. So in order to escape the symbol in a regular expression, you must write two backslashes (\) in a string literal._

**Comment by alexey-milovidov** [comment]
@den-crane Yes, the details are here: https://github.com/ClickHouse/ClickHouse/pull/11208
