### ISSUE TITLE
Does clickhouse allow to use openmp? 

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#33420]
Background is I want to do a multi threading memset to set zero of a big memory about 100MB or more, openmp can do this very easily. But I don't see any openmp code in all this project even in the contrib code, So does clickhouse allow to use openmpt to do some parallel things?
Thanks in advance.

**Comment by alexey-milovidov** [comment]
If we use our HashMap, it will do `mmap` for memory chunks 64MB or larger and avoid using memset from userspace, because OS kernel is already zeroing memory. And we cannot avoid this work that is done by OS kernel.

Also if we want to lower the latency (and we do) it makes sense to amortize resizes (by doing incremental data movement from old buffer to the new buffer).

**Comment by zhanglistar** [comment]
> If we use our HashMap, it will do `mmap` for memory chunks 64MB or larger and avoid using memset from userspace, because OS kernel is already zeroing memory. And we cannot avoid this work that is done by OS kernel.
> 
> Also if we want to lower the latency (and we do) it makes sense to amortize resizes (by doing incremental data movement from old buffer to the new buffer). It will lower the latency to microseconds range.

Thanks for your reply. mmap is 30% faster than calloc, but still 2x slower than openmp version memset, but I will not use openmp, and using malloc and memset part of memory to reduce latency. 
BTW this is the first buffer that needed to malloc for new hashmap, and need to initialize the managing metadata, the following process is incremental.
