### ISSUE TITLE
Testcase Failure :  tests/queries/0_stateless/01153_attach_mv_uuid.sql

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#33460]
[Error.txt](https://github.com/ClickHouse/ClickHouse/files/7831358/Error.txt)
Description:
The storage attach mv is throwing error in case last attach mv was unsuccesful/threw exception for any reasons with same inner UUID. (Refer attached file)

Steps to reproduce: 

tests/queries/0_stateless/01153_attach_mv_uuid.sql
Update the line#29 - modify UUID 'e15f3ab5-6cae-4df3-b879-f40deafd82c2' to 3bd68e3c-2693-4352-ad66-a66eba9e345e. and execute the test - It should throw exception which is expected , table cannot point to itself.

Now execute the actual test case after removing updations, it will fail with error - TABLE already exist with datastore/3bd68e3c-2693-4352-ad66-a66eba9e345e. 

PR reference  : Fix attach MV in Atomic database #23047

**Comment by tavplubix** [comment]
> Update the line#29

The line 29 is empty (since 2021-09-13, changed in https://github.com/ClickHouse/ClickHouse/commit/39d73c01b225d5b274c11f75d786b6c81a53f1c8), do you mean [the line 31](https://github.com/ClickHouse/ClickHouse/blob/39d73c01b225d5b274c11f75d786b6c81a53f1c8/tests/queries/0_stateless/01153_attach_mv_uuid.sql#L31)? I've tried to reproduce it on fresh master, but test passed after changing UUID back:

```
avtokmakov@avtokmakov-dev:~/ch/ClickHouse/tests$ ./clickhouse-test 01153_attach_mv_uuid
Using queries from 'queries' directory
Using clickhouse-client as client program (expecting split build)
Connecting to ClickHouse server... OK

Running 1 stateless tests (MainProcess).

01153_attach_mv_uuid:                                                   [ FAIL ] - return code: 36
Received exception from server (version 21.13.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Materialized view test_rsuehq.mv cannot point to itself. (BAD_ARGUMENTS)
(query: ATTACH MATERIALIZED VIEW mv UUID '3bd68e3c-2693-4352-ad66-a66eba9e345e' TO INNER UUID '3bd68e3c-2693-4352-ad66-a66eba9e345e' (n Int32, n2 Int64) ENGINE = MergeTree PARTITION BY n % 10 ORDER BY n AS SELECT n, n * n AS n2 FROM src;)
, result:

1	1
2	4
1	1
2	4
3	9
4	16
CREATE MATERIALIZED VIEW default.mv UUID \'e15f3ab5-6cae-4df3-b879-f40deafd82c2\'\n(\n    `n` Int32,\n    `n2` Int64\n)\nENGINE = MergeTree\nPARTITION BY n % 10\nORDER BY n AS\nSELECT\n    n,\n    n * n AS n2\nFROM default.src
1	1
2	4
CREATE MATERIALIZED VIEW default.mv UUID \'e15f3ab5-6cae-4df3-b879-f40deafd82c2\'\n(\n    `n` Int32,\n    `n2` Int64\n)\nENGINE = MergeTree\nPARTITION BY n % 10\nORDER BY n AS\nSELECT\n    n,\n    n * n AS n2\nFROM default.src
1	1
2	4
3	9
4	16

stdout:
1	1
2	4
1	1
2	4
3	9
4	16
CREATE MATERIALIZED VIEW default.mv UUID \'e15f3ab5-6cae-4df3-b879-f40deafd82c2\'\n(\n    `n` Int32,\n    `n2` Int64\n)\nENGINE = MergeTree\nPARTITION BY n % 10\nORDER BY n AS\nSELECT\n    n,\n    n * n AS n2\nFROM default.src
1	1
2	4
CREATE MATERIALIZED VIEW default.mv UUID \'e15f3ab5-6cae-4df3-b879-f40deafd82c2\'\n(\n    `n` Int32,\n    `n2` Int64\n)\nENGINE = MergeTree\nPARTITION BY n % 10\nORDER BY n AS\nSELECT\n    n,\n    n * n AS n2\nFROM default.src
1	1
2	4
3	9
4	16


Database: test_rsuehq

Having 1 errors! 0 tests passed. 0 tests skipped. 1.19 s elapsed (MainProcess).
Won't run stateful tests because test data wasn't loaded.
All tests have finished.

avtokmakov@avtokmakov-dev:~/ch/ClickHouse/tests$ ./clickhouse-test 01153_attach_mv_uuid
Using queries from 'queries' directory
Using clickhouse-client as client program (expecting split build)
Connecting to ClickHouse server... OK

Running 1 stateless tests (MainProcess).

01153_attach_mv_uuid:                                                   [ OK ]

1 tests passed. 0 tests skipped. 1.28 s elapsed (MainProcess).
Won't run stateful tests because test data wasn't loaded.
All tests have finished.

```

**Comment by HeenaBansal2009** [comment]
Yes @tavplubix , I mean to say Line#31, Did you tried the same steps as below , I tried executing the test case on new master too  .
1. Without modifying the test case - it passed.
2. Update line#31 , update the UUID - failed  with error"cannot point to itself"
3. Modify file again to the previous mv - failed with error , database_exist.

**Comment by tavplubix** [comment]
> Did you tried the same steps as below

Yes, but I cannot reproduce the issue. How exactly do you run tests? What version of clickhouse-server do you run? Have you changed some server settings?

> database_exist

As I can see from attached Error.txt file, the test failed with TABLE_ALREADY_EXISTS, so probably it's something different now.

**Comment by HeenaBansal2009** [comment]
./clickhouse-server --version
ClickHouse server version 21.13.1.1.

./clickhouse-client --version
ClickHouse client version 21.13.1.1.

I haven't changed any configurations . It is as is by default.

I captured the whole activity I am doing (Attached)

[failure_logs.txt](https://github.com/ClickHouse/ClickHouse/files/7847590/failure_logs.txt)

**Comment by tavplubix** [comment]
Try enable `database_atomic_wait_for_drop_and_detach_synchronously` setting in server config.

What (probably) happens:
 - The test creates `".inner_id.e15f3ab5-6cae-4df3-b879-f40deafd82c2"` table with `UUID '3bd68e3c-2693-4352-ad66-a66eba9e345e'`
 - The test fails with `Materialized view test_3m803j.mv cannot point to itself` before reaching `DROP TABLE mv SYNC;` so create table is not dropped. 
 - `clickhouse-test` [drops](https://github.com/ClickHouse/ClickHouse/blob/b3f1951c158cded5044d3cb29add34974d1afa37/tests/clickhouse-test#L622) database `test_3m803j`, but without enabled setting and `SYNC` modifier `DROP` query is executed asynchronously (with `database_atomic_delay_before_drop_table_sec` delay), so table with UUID `3bd68e3c-2693-4352-ad66-a66eba9e345e` still exists on disk (but it's not visible for a user)
 - You undo changes and run the test second time, but it fails to create table with this UUID, because previous one still exists.
