### ISSUE TITLE
Using Kafka engine on cluster with replicas

### ISSUE THREAD

**Issue by cainiaodidi** [ClickHouse/ClickHouse#33475]
I am confused about table creating on cluster with replicas. 
For example, the cluster has 4 nodes, config is 2 shards(node_A1, node_B1) and 2 replicas(node_A2, node_B2).
1. create kafka engine table and materialized view on all nodes and the result table using MergeTree engine on cluster
2. create kafka engine table and materialized view only on half of nodes(eg. node_A1 and node_B1), and the result table using ReplicatedMergeTree engine on cluster
What happen if the node with Kafka engine table is broken? Which is the best way about using Kafka engine table？

**Comment by genzgd** [comment]
First, unlike some other databases, ClickHouse does not have a concept of a "primary node" versus a "replica node". Multiple nodes that hold the same copy of data are both considered replicas, and those replicas are equal in all respects.  Data written to a replicated table on any replica node will be copied to all other replica nodes for that table.

Second, shards in ClickHouse are tables on different ClickHouse nodes that have the same structure but hold different data.  Distributed tables are used to allow queries that combine the data from multiple shards.  Distributed tables require a cluster definition in the \<remote_servers> section of the ClickHouse configuration so that ClickHouse can retrieve that data from all shards of the table.  In your \<remote_servers> cluster definition you will create a list of shards, and within each shard you will add the list of ClickHouse replica nodes where the data for that shard can be retrieved.

Replication of the data for each shard can be implemented in two ways:

A)  Create the table on each replica node using a Replicated version of the appropriate MergeTree engine (such as plain ReplicatedMergeTree or ReplicatedSummingMergeTree).  Metadata about the replicated table will be stored in zookeeper under the zookeeper path set as the first parameter in the Engine definition, and the shard number is normally included in this path.  ClickHouse will automatically keep all replicas of the table in sync for each shard, and as noted above, data inserted into the table on any node will be copies to all other replicas.  In this case the \<internal_replication> element in each shard of the cluster definition must be set to `true`

B)  Create the table with a MergeTree engine that is not replicated, and set the \<internal_replication> element of each shard in the cluster definition to `false`.  In this case data will only be replicated if you insert into a distributed table.  When inserts happen to the distributed table, the node handling the insert will be responsible for inserting a copy of the data into all replicas defined in the shard.  This is less reliable than using zookeeper and Replicated tables, because if some problem happens with copying data to multiple nodes on insert, ClickHouse does not automatically ensure that the replicas hold the same data.

The recommended way to do any replication is to use a ReplicatedMergeTree table, option A above.

Now to get to the Kafka part.  If you try your option 1, create a Kafka engine table and MV and result on all nodes with a MergeTree engine for the "result" table, your materialized view will have to use the distributed table as the actual target so the data is copied to the other replicas.  This will mostly work, but it is not recommended for the same reasons that replication option B is not recommended -- Replicated tables using zookeeper are much more reliable (and also perform better) than using distributed tables for replication.

Your option 2 will also work, but if one of the nodes is down or the Kafka engine is down, all of the data will go to the other node and your shards will be unbalanced for the period that one of the nodes is down.  This imbalance might be okay if you are able to repair the broken node quickly.

Depending on your Kafka volume and number of partitions, it's also possible to add the Kafka engine and materialized view on all four shards even if you are using Replicated tables.  Because consuming multiple partitions will be split among all four nodes, data will not be duplicated.  If one of the four node goes down, data will still be unbalanced, but only half as much.  Adding your Kafka engine to all four nodes will spread the ingest processing cost and increase your reliability.

**Comment by cainiaodidi** [comment]
Thanks a lot, and I am a little confused about this.
> create a Kafka engine table and MV and result on all nodes with a MergeTree engine for the "result" table, your materialized view will have to use the distributed table as the actual target so the data is copied to the other replicas

How to use the distributed table as the actual target? Could you please write some sql connecting kafka engine table, mv and target table to explain this?


> it's also possible to add the Kafka engine and materialized view on all four shards even if you are using Replicated tables

If I use Replicated tables and four Kafka engine tables consume different partitions, then 'result' table will get different data between node_A1 and node_A2, and I think this will be against with Replicated tables

**Comment by genzgd** [comment]
Again it's not recommended to use a Distributed Table as a target for a materialized view, but it is possible.  The syntax is the same as any other Materialized View using TO:

  ```CREATE MATERIALIZED VIEW table_name [TO[db.]name] ```

where db.name is a distributed table.  The target distributed table must exist, and should use a regular MergeTree table as the source table.

If you use the Kafka engine on all four nodes, the data _initially_ inserted on node_A1 from Kafka will be different from the data _initially_ inserted on node_A2, but since they are replicas, inserted data on node_A1 will be quickly copied to node_A2, and vice versa.  Both node_A1 and node_A2 will end up with identical data, just the inserts happened on different nodes.

**Comment by cainiaodidi** [comment]
> If you use the Kafka engine on all four nodes, the data _initially_ inserted on node_A1 from Kafka will be different from the data _initially_ inserted on node_A2, but since they are replicas, inserted data on node_A1 will be quickly copied to node_A2, and vice versa. Both node_A1 and node_A2 will end up with identical data, just the inserts happened on different nodes.

Thanks, I try to understand that. If there are two partitions of topic, node_A1 consumes partition 0 and node_A2 consumes partition 1, and for the replicated result table on node_A1 and node_A2, it will contain data from both two partitions. I used to think that the original data on node_A2 will be deleted when the data is copied from node_A1.

**Comment by BransonNg** [comment]
Hi @genzgd thanks for your responses so far.

Would like to about an extension to this question assuming we adopt option A described in this thread:
- Would it be possible to optimize queries with a Distributed Table Engine by declaring a shard key that is the same as the partition key declared for the kafka topics consumed for the table targeted? 
- My main concern is about how coordination would work where instances in a shard would be able to inform zookeeper about the types of key present in a particular shard
