### ISSUE TITLE
How can I force to handle all rows in one time execution of IExecutableFunction::executeImpl()

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#33495]
I am implementing a special function for our business as a `class ExecutableFunctionXXX final : public IExecutableFunction`. The special function needs to get all rows to work(cannot do work with partial data, must need all data). However, the IExecutableFunction::executeImpl is called with part of rows each time(determined by max_block_size) and executeImpl() function is get called many times. That does not meet our needs. 

Can I force to make calling to ExecutableFunctionXXX::executeImpl() one time and passed all rows? Can I set something like max_block_size = INFINITE to achieve it?

Thank you very much.

**Comment by nvartolomei** [comment]
This sounds like an aggregate function rather than an executable function https://github.com/ClickHouse/ClickHouse/tree/master/src/AggregateFunctions.

**Comment by kitaisreal** [comment]
@Alex-Cheng you cannot use executable user defined functions for that specified scenario, because you need to read all data to provide some output. We have StorageExecutable but is works like storage. Example `SELECT * FROM executable(script_name, Format, TableStructure, Queries)`.
Script can read all data from queries and provide output, similar to aggregation, but it is not convenient use case.

**Comment by Alex-Cheng** [comment]
I got a workaround, adding `settings max_block_size=<very large number which is greater than total row number>` to the end of SQL query. It makes sure all data of column as input argument are passed into the function executable.

Thank you for help.
