### ISSUE TITLE
ReplicatedSummingMergeTree`s result is different with SummingMergeTree

### ISSUE THREAD

**Issue by DaemonMonch** [ClickHouse/ClickHouse#33517]
###   I have a SummingMergeTree with this ddl:
  
  CREATE TABLE dsp_rpt.solution_hourly_local (
    `day` Date,
    `hour` Int8,
    `solutionId` Int32,
    `bids` Int64,
    `shows` Int64,
    `clicks` Int32,
    `cost` Int64,
    `cost0` Int64
) ENGINE = SummingMergeTree PARTITION BY day
ORDER BY (solutionId, hour) ;
 
### then a kafka stream with ddl:

CREATE TABLE `dsp_rpt_cluster`.log_stream (
    `timestamp` UInt64,
    `type` UInt8,
    `impId` String,
    `exchange_id` Int32,
    `adspace_id` String,
    `solution_id` Int32,
    `creative_id` Int32,
    `price` Int32,
    `user_id` String,
    `ip` String,
    `user_agent` String,
    `referrer` String,
    `no_bid_reason` String,
    `deal_id` String,
    `client_ip` String,
    `region` String,
    `user_id_type` Int32,
    `price0` Int32,
    `campaign_id` Int32
)ENGINE = Kafka(
    'localhost:9092',
    'de.log.bid,de.log.show,de.log.click',
    'dsp-rpt-cluster-group1'
) SETTINGS kafka_format = 'ProtobufSingle',
kafka_schema = 'log.proto:LogEvent',
kafka_num_consumers = 2,
kafka_skip_broken_messages = 1000000;

### the question is when i use the same MV :
CREATE MATERIALIZED VIEW `dsp_rpt_cluster`.solution_hourly_mv  TO `dsp_rpt_cluster`.solution_hourly[_local] (
     `day` Date,
    `hour` Int8,
    `solutionId` Int32,
    `bids` Int64,
    `shows` Int64,
    `clicks` Int32,
    `cost` Int64,
    `cost0` Int64
) AS
SELECT toDate(toDateTime(timestamp / 1000)) AS day,
    toHour(toDateTime(timestamp / 1000)) AS hour,
    solution_id AS solutionId,
    countIf(type = 1) AS bids,
    countIf(type = 3) AS shows,
    countIf(type = 4) AS clicks,
    sumIf(price, type = 3) AS cost,
    sumIf(price, type = 3) AS cost0
FROM `dsp_rpt_cluster`.log_stream
WHERE type < 20
GROUP BY day,
    solution_id,
    hour;

**Comment by DaemonMonch** [comment]
sorry,my CH server version is 21.11.4.14

**Comment by den-crane** [comment]
Probably it's because insert_deduplication.

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/

_Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application does not know if the data was written to the DB, so the INSERT query can simply be repeated. It does not matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings._

https://clickhouse.com/docs/en/operations/settings/settings/#settings-insert-deduplicate

I suggest to add into your ReplicatedSummingMergeTree virtual columns from Kafka engine _partition_id and _offset this will bring unique info and prevent deduplication.

**Comment by DaemonMonch** [comment]
@den-crane thx for reply,I`ll try this
