### ISSUE TITLE
Prevent infinite loop caused by recursive query

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#33802]
Below query will end up with error `Too many simultaneous queries. Maximum: 100 (TOO_MANY_SIMULTANEOUS_QUERIES)`. I think using different table function like jdbc or database like Apache Drill or Trino etc. have similar issue. It would be great if the infinite loop can be detected and stopped right before the second run.

```sql
use default;
drop table if exists url_self;
create table url_self (s String)
engine=URL('http://localhost:8123/?query=select%20*%20from%20url_self', CSV);
-- Code: 86. DB::Exception: Received error from remote server
select * from url_self;
```

**Comment by alexey-milovidov** [comment]
Yes, I have also tried this query a while ago :)
It's not infinite loop, because it is terminated by exception.
It is also possible to do with Distributed tables.

In some cases it is impossible to prevent - if you use another intermediate server to relay the requests and this server does not leave any tracing information to distinguish the origin of the request.
