### ISSUE TITLE
<Error> executeQuery: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 30. Bytes expected: 250.

### ISSUE THREAD

**Issue by mylqf** [ClickHouse/ClickHouse#33839]
How can I solve this problem when I insert data in batches? Thank you

**Comment by genzgd** [comment]
Can you post the full stack trace and ClickHouse version?  What are the conditions where you see this message?

**Comment by genzgd** [comment]
What client are you using to insert data?  I would first recommend upgrading your version of ClickHouse to the latest or at least latest LTS version (21.8).  Because you are using the native TCP interface, it's possible that your client library and ClickHouse version are incompatible.  If you are using clickhouse-client make sure it's the same version as the server.

It's also possible there this is a network issue or some other hardware problem with your environment.  Are your server or client under heavy load or are there other stresses on your system?

**Comment by den-crane** [comment]
What library do you use ?

It seems that native stream is broken in the middle.

NativeBlockInputStream : For example, you defined that String Length will be 250 bytes, but you sent only 30 bytes

**Comment by mylqf** [comment]
> What library do you use ?
> 
> It seems that native stream is broken in the middle.
> 
> NativeBlockInputStream : For example, you defined that String Length will be 250 bytes, but you sent only 30 bytes

What did you say lib

**Comment by den-crane** [comment]
>What did you say lib

I assume that you use some golang or python or java/jdbc library. I am asking which one do you use?

**Comment by mylqf** [comment]
Python lib





------------------ Original ------------------
From: Denny Crane ***@***.***&gt;
Date: Sat,Jan 22,2022 0:06 PM
To: ClickHouse/ClickHouse ***@***.***&gt;
Cc: mylqf ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ClickHouse/ClickHouse] <Error&gt; executeQuery: Code: 33,e.displayText() = DB::Exception: Cannot read all data. Bytes read: 30. Bytesexpected: 250. (Issue #33839)





  
What did you say lib
  
I assume that you use some golang or python or java/jdbc library. I am asking which one do you use?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by den-crane** [comment]
Can you please provide a code sample to reproduce the issue?
