### ISSUE TITLE
Invalid Kerberos auth flow: Server sends 403 instead of 401

### ISSUE THREAD

**Issue by DarkWanderer** [ClickHouse/ClickHouse#33858]
**Describe the unexpected behaviour**
Server behavior during Kerberos authentication does not conform to [RFC4559](https://datatracker.ietf.org/doc/html/rfc4559#section-4.1). When a client authenticates using Kerberos, it *may* not send authentication headers on first request. In that case, the server should send a "401 Unauthorized" status code, and a "WWW-Authenticate:" header, which triggers SPNEGO workflow in Curl. However, ClickHouse does not do that and sends back a HTTP 403 instead

**How to reproduce**
* Observed on 21.9 but likely is present in latest version
* HTTP interface
* Kerberos authentication

```
curl -v -u : --negotiate "http://clickhouse.server:8123/?query=SELECT+VERSION()"
```

**Sent headers**
```
> GET ?query=SELECT+VERSION()
> User-Agent: curl/7.29.0
> Host: clickhouse.server:8123
> Accept */*
```
**Expected server response**
```
< HTTP/1.1 401 Unauthorized
< Date: .....
< Connection: Keep-Alive
< WWW-Authenticate: Negotiate
< Content-Type: .....
```

**Observed server response**
```
< HTTP/1.1 403 Forbidden
< Date: .....
< Connection: Keep-Alive
< X-Clickhouse-Exception-Code: 516
< Content-Type: .....

Code: 516. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED) (version 21.9.2.1)
```

**Comment by traceon** [comment]
@DarkWanderer could you please also attach the relevant log messages from the ClickHouse server (should be somewhere before the generic `password is incorrect or there is no user with such name.`)?

**Comment by DarkWanderer** [comment]
Unfortunately not (closed network, cannot send data)

Partial stack trace:
```
DB::IAccessStorage::throwCannotAuthenticate
DB::IAccessStorage::login
DB::Session::authenticate
DB::HTTPHandler::authenticateUser
DB::HTTPHandler::processQuery
```

Same server authenticates correctly if accessed with a custom Curl version which sends headers straightaway

**Comment by traceon** [comment]
> Unfortunately not (closed network, cannot send data)

This would really help.

> Same server authenticates correctly if accessed with a custom Curl version which sends headers straightaway

What do you send in this case?

Are these header lists complete?

**Comment by traceon** [comment]
Oh, I see where this limitation comes from. ClickHouse is not switching to Kerberos authentication unless it is initiated by the client, i.e. the client should explicitly mention that is it attempting SPNEGO, which means sending the non-empty token in the first request. Otherwise, the server wouldn't even know which user is trying to connect at all. (And the first token has user credentials, specifically, the user name.)

Note, that your initial curl request doesn't carry user name in any form. That's why it resorted to `default` user.

One of possible solution to this would be disabling defaulting to `default` username for anonymous requests if Kerberos is enabled. Or adding support for auth method detection, based on a user name that is provided in some way, e.g., via `X-ClickHouse-User` and detecting, if that user is configured to authenticate via Kerberos. The latter, however, exposes some information about the setup, which might be seen as an undesired thing from security point of view.

**Comment by vitlibar** [comment]
Probably the best solution is disabling defaulting to `default` username for anonymous requests if Kerberos is enabled. I don't think it's an often case when someone enables Kerberos for authentication and at the same time needs to be able to authenticate as the `default` user without specifying username or password. Perhaps it's better to add a setting to the Kerberos part in our server configuration for such cases.

Can we add a comment to the `401 Unauthorized` response to make clear that ClickHouse server has returned that response because of Kerberos?

**Comment by DarkWanderer** [comment]
Possibly the parameter could be `<use_default_user_for_unauthorized_http>` - `1` by default, `0` to disable? Then if server returns 401, it can also return following headers (based on whether relevant auth type is enabled):
```
WWW-Authenticate: Negotiate
WWW-Authenticate: Basic
```
and let the client decide

**Comment by alexey-milovidov** [comment]
The problem is understood, but we don't plan to support Kerberos.
