### ISSUE TITLE
Why changing nullable values to double cause  Clickhouse tables became read-only frequently?

### ISSUE THREAD

**Issue by qinglin** [ClickHouse/ClickHouse#34000]
Hi, Guys, I have been working with clickhouse for a while and clickhouse is running pretty well on our prod environment, but last week, I tried to change the value of 5 columns from null to a double value, and the affected rows are about 3600, the sql is like `'alter table XXX update columnA = 1.11 where timestamp = '2022-01-01 08:00:00'` (The original columnA value is null)

Then wired things happen, all the prod clickhouse tables became read-only mode, I checked the log and found the zookeeper is complaining about out of memory, after I increased the jvm of zookeeper, the tables are still kept read-only mode, so I checked the zookeeper nodes and found a `mutation znode` containing huge amount of data in the table I tried to do mutation operations. After I deleted the mutation znode, clickhouse gradually became stable but still slow. 

It's after I checked the replication-queue table in system database, and delete the /queue znode in zookeeper, the clickhouse insert and read speed became much faster, I think it's because too much merging operations stuck in the queue made clickhouse insertion became much slower. 

So finally our clickhouse is working well again now in the prod environment, but I still did not get it, why my mutation operations of changing null values to double would cause this tragedy? 

Does anyone has any idea about this issue? 

![image](https://user-images.githubusercontent.com/1820978/151128834-8b1f5814-0504-46f6-a181-994cc61452b0.png)
The zookeeper queue znode causing insertion very slow

**Comment by genzgd** [comment]
Currently replicated mutations require tracking all of the parts of the table in zookeeper.  This creates a great deal of zookeeper data and zookeeper traffic until the mutation is complete.  If your zookeeper cluster is relatively small (that is, good enough for normal operations but not for several concurrent mutations) this high load can cause errors and  corrupted queue operations.

Also, I'm not sure what you mean by the 'affected rows', but even if only a few rows actually match the `where` filter the operation is quite expensive because all of values in the column for the entire table must be checked, and in most cases the entire column file in each part must be rewritten.  Accordingly mutation operations are often very slow (and might also be limited to the resources assigned to the background pool for merging and mutations.)

Accordingly we recommend running only a single mutation at a time to protect both zookeeper and you ClickHouse server nodes (you can validate the previous mutation has completed by `SELECT * FROM system.mutations where is_done = 0`).
