### ISSUE TITLE
 it is not working correctly when apply  Distributed on system.query_log

### ISSUE THREAD

**Issue by windylcx** [ClickHouse/ClickHouse#34048]
i want to query all to the query log of a cluster ,and i create a Distributed table system.query_log_dist.

```
create TABLE if not exists system.query_log_dist  on cluster cluster1
as system.query_log
ENGINE = Distributed('cluster1', 'system', 'query_log', rand());
```

and  query like this:

`select count(*) from  system.query_log_dist where toDate(event_time)=yesterday()`

but the result is random.

how Distributed table work on  system  build in tables?
![image](https://user-images.githubusercontent.com/917238/151285326-4ccff02d-289f-4d51-8c16-db8dc1d913fa.png)

it seems just execute on 3 nodes,but i got 6 nodes(3 shard 2 replica,deploy 2 instance server on same ip)

is one table is treat as a shard of the Distributed,but the system tables is no ReplicatedMergeTreeTable

refer to the docs, https://clickhouse.com/docs/en/engines/table-engines/special/distributed/

how can i use Distributed to query all the nodes's  records  of a cluster?

**Comment by den-crane** [comment]
cluster1 is 3 shard 2 replica that's why.

You have 2 options
* use clsterAllRelplicas `select count(*) from clsterAllRelplicas('cluster1', system.query_log_dist) where toDate(event_time)=yesterday()`
* create one more cluster 'cluster-all' where all 6 nodes will shards with a single replica and use this 'cluster-all'  in your Distributed table.

ClickHouse nodes can be a member of any number of clusters.
With 6 nodes you can define the same time
* 6 shards * 1 replica
* 1 shard * 6 replica
* 3 shard * 2 replica
* 2 shard * 3 replica
...

**Comment by windylcx** [comment]
> 

got it,thank you!
