### ISSUE TITLE
What's the difference between Clickhouse's pipeline execution and Volcano model?

### ISSUE THREAD

**Issue by YjyJeff** [ClickHouse/ClickHouse#34045]
I am interested in the pipeline execution model in ClickHouse. After searching, I only find this [website][1] that tells me how ClickHouse's pipeline model works. But I am still very confused. Why the pipeline execution is better than volcano model? 

Thanks in advance  

  [1]: https://presentations.clickhouse.com/meetup24/5.%20Clickhouse%20query%20execution%20pipeline%20changes/#processors-1

**Comment by alexey-milovidov** [comment]
The main difference is that volcano has implicit control flow (calculations are controlled by function calls)
and pipeline has explicit control flow (there is query execution graph and external scheduler can select what computation blocks to run in what threads).

Here is the old list (2018) of what to achieve with Processors:

1. Proper conditions push-down.
Current implementation of "enable_optimize_predicate_condition" works on AST level and it's very fragile, because semantic correctness of AST transformation is not ensured. We want to implement it on dataflow level insted. It will rely on algebraic properties of data streams to ensure correctness.

2. Proper handling of scalar subqueries.
Current implementation of scalar subqueries is very special. They are executed at query analysis stage, out of the scope of query execution. Progress info, limits and quotas just don't work for scalar subqueries. This is needed because results of scalar subqueries are used in query conditions involving index and index analysis must be performed before start of query execution. Instead, we will implement scalar subqueries as a part of common query execution graph. Some nodes of the graph will wait for scalar subqueries and possibly rebuild other parts of graph depending of subqueries results (change number of threads, skip shards, etc).

3. Less total number of threads on server.
Now we create a separate thread pool for each query. Instead, we will have single thread pool dedicated for computation-intensive tasks. All concurrently running queries will be presented as a single execution graph (containing subgraphs for all the queries). Scheduler will assign threads to execution tasks.

4. CPU priorities.
Scheduler will assign tasks selected from global execution graph depending on query priorities.

5. IO threadpool.
IO and network bound tasks can be executed in separate threadpools in natural way. But currently we almost have no idea if some data stream is IO, network or CPU bounded.

6. ✔️ Remove duplication of Input/OutputStreams.
Sometimes Input and Output streams contain identical transformations. For example, we have SquashingBlockInputStream and SquashingBlockOutputStream. With processors, no issue exists.

7. Processing of multiple queries in a single pass.
Multiple concurrently running queries may have identical data sources and identical transformations in their pipeline. We can dynamically merge their pipelines to read and transform data just once, executing multiple queries.

8. Cache of intermediate data.
If a query has already performed some transformation, we may keep intermediate data blocks for a while to reuse these data blocks for the next queries with the same part of pipeline.

9. Data stealing.
One query can "subscribe" for intermediate data processed by another query.

10. ✔️ EXPLAIN query.
We can present data processing graph for the user.

11. Distributed query execution plan.
Currently our query execution plan is managed separately on each node. We want to maintain global plan with all servers taken into account to perform global optimizations.

12. Shuffle distributed JOIN.
With global query execution plan we can easily build a graph that will involve multiple steps with data re-distribution over the network, that is required for scalable JOINs of large tables.

13. ✔️ Simple implementation of query cancellation.
In current implementation, the query is executed asynchronously. To cancel the query we have to set atomic flag, and the query have to check it in another thread. With "processors", all query execution steps are controlled by scheduler. To cancel the query, scheduler will simply cancel its execution: no complex synchronization logic is needed.

14. ✔️ Make query progress, profiling, quotas and limits to be external to data processing logic.
Now all the query accounting is done inside block input stream. It performs resource accounting by itself. Insted, we want all query accounting to be performed by scheduler, that is independent on data transformations. We want to be able to also calculate very precise metrics: as amounts of data passed on every edge of data execution pipeline.

------

Only 4 of 14 items are done :crying_cat_face:

**Comment by YjyJeff** [comment]
@alexey-milovidov  Awesome， looking forward to all of them will be done.  
You have not mentioned that the processor can accelerate the single query, but I find the query based on processor is much faster than volcano model on this [website](https://presentations.clickhouse.com/meetup24/5.%20Clickhouse%20query%20execution%20pipeline%20changes/#processors-1)(10.599s VS 23.227s). Why does it happen?

**Comment by alexey-milovidov** [comment]
@YjyJeff Processors parallelize query both horizontally (different parts of data is processed in parallel by the same computation) and vertically (different stages of computation are run in parallel). The old volcano model only parallelize horizontally.

**Comment by YjyJeff** [comment]
> @YjyJeff Processors parallelize query both horizontally (different parts of data is processed in parallel by the same computation) and vertically (different stages of computation are run in parallel). The old volcano model only parallelize horizontally.

Thanks~
