### ISSUE TITLE
Why is float datatype usage not recommended?

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#34313]
On https://clickhouse.com/docs/en/sql-reference/data-types/float/ there is said:

> We recommend that you store data in integer form whenever possible. For example, convert fixed precision numbers to integer values, such as monetary amounts or page load times in milliseconds.

So is float usage discouraged? It is not specified why. I know culpits of floats in general. I've stored money amount as int*100 instead of float in my life few times already.

I have a packet loss value as float32 and need to store it in clickhouse. So I wonder whether there are any specifics to floats in clickhouse context. Or can I safely use it if I know what float means and how it works?

Thanks.

**Comment by genzgd** [comment]
Float is discouraged for two reasons -- the loss of precision when precision matters (like with money), and the performance cost when using float instead of integer types.  That cost can be significant for compression (network and storage), where something like a delta based algorithm is much more efficient with integers than floats, and for aggregate functions, especially complex ones such as quantiles or uniques.  When multiplied by millions or billions of values such costs quickly add up.

But there are no specific issues with floats in ClickHouse and they are perfectly safe.
