### ISSUE TITLE
questions about clickhouse user defined functions

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#34674]
I know  this point is done  in new clickhouse， I want  to know where the modifies add of user defined functions ， can you tell me the branch of user defined functions  or  the commites of user defined functions ， I want to know  where themodifies done， I want 
to  move these modifies  to my old clickhouse，  In my old clickhouse， I have done some  processes so I do not wanto update to the newest clickhouse， I just want to  move the point  user defined functions  to my ck,   thank you

**Comment by kitaisreal** [comment]
@miaojianxin it is impossible to cherry pick Executable UDF or SQL UDF, because there were a lot of steps to produce them in different pull requests and a lot of bug fixes also in different pull requests.
I suggest if you need UDF functionality, use Executable Dictionaries, they have same functionality as ExecutableUDF but less convenient API, and they also do not have timeouts settings https://clickhouse.com/docs/en/sql-reference/functions/#executable-user-defined-functions.
