### ISSUE TITLE
Switch CI builds to clang-14

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#34681]
The current clang version is 14, so it makes sense to start using it.

**Comment by Algunenano** [comment]
As a side note: I'm waiting for libc++14 to be released and stable to try and update it and close https://github.com/ClickHouse/ClickHouse/issues/32018

I didn't try to update the libc++ submodules to 13 because the forks had included stuff from experimental and I'm expecting that updating to 14 will be much simpler and reduce the amount of work (vs 12 -> 13 -> 14).

**Comment by alexey-milovidov** [comment]
Ok.

PS. I've checked that ClickHouse is build successfully with clang-14 with default options.

**Comment by alexey-milovidov** [comment]
Also checked with llvm/clang-15 (master).

**Comment by alexey-milovidov** [comment]
clang-15 generated DWARF info that cannot be parsed by ClickHouse:
```
milovidov-nix :) SELECT throwIf(1)

SELECT throwIf(1)

Query id: 08179a77-d85a-4038-b8b9-ef3852787bb6

Exception on client:
Code: 465. DB::Exception: invalid info version. (CANNOT_PARSE_DWARF)
```

**Comment by danlark1** [comment]
Also note some silent failures happen in contrib

https://github.com/intel/hyperscan/pull/345
