### ISSUE TITLE
SELECT toDateTime('1970-01-01 00:00:00') -> 1970-01-01 06:28:16 for time zone other than UTC

### ISSUE THREAD

**Issue by ghuname** [ClickHouse/ClickHouse#3470]
Selecting when time zone is not UTC shows wrong (1970-01-01 06:28:16) datetime.

`ClickHouse client version 18.14.10.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.10 revision 54409.

blade8.lab.bulb.hr :) SELECT toDateTime('1970-01-01 00:00:00')

SELECT toDateTime('1970-01-01 00:00:00')

┌─toDateTime('1970-01-01 00:00:00')─┐
│               1970-01-01 06:28:16 │
└───────────────────────────────────┘

1 rows in set. Elapsed: 0.011 sec.`

**Comment by filimonov** [comment]
the same:
```
select toDateTime('1969-12-29 00:00:01') ; -- 1970-01-01 06:28:17
select toDateTime('1008-02-29 00:00:01') ; -- 1970-01-01 06:28:17
```

Generally those dates are out of clickhouse supported range, but probably should be printed as '0000-00-00 00:00:00'

**Comment by ghuname** [comment]
How come that 1970-01-01 is not supported? It is zero epoch.

**Comment by filimonov** [comment]
Caused by the fact that when it was 1970-01-01 in UTC in some other timezones  it still was 1969 which can'be properly processed. Accurate processing of that date is possible but AFIAK it was just simpler just to assume that epoch starts a little bit later, and no extra costs on processing border effects of first day of epoch. BTW for that reason documentation usually call minimal day as 'some date in past'.

**Comment by ghuname** [comment]
I understand what you are telling me, but it would be better to return an error, or 0000-00-00 00:00:00 instead of 1970-01-01 06:28:17 for GMT +1 time zone.
Anyway, thank you for clarification.

**Comment by filimonov** [comment]
> better to return an error, or 0000-00-00 00:00:00 instead of 1970-01-01 06:28:17

Yes, it's a bug.

**Comment by alexey-milovidov** [comment]
Now it returns `2106-02-07 06:28:16`. Even better.

**Comment by demenkov** [comment]
> Now it returns `2106-02-07 06:28:16`. Even better.

I think it's no better, because when I'm try to select with use range of dates, it will produce unexpectable results.

`SELECT 
    close_time, 
    count(*)
FROM mt4_trade 
WHERE close_time <= '1971-00-00 00:00:00'
GROUP BY close_time
ORDER BY close_time ASC
LIMIT 10

┌──────────close_time─┬─count()─┐
│ 2014-10-02 20:43:47 │       1 │
│ 2014-10-02 21:00:52 │       1 │
│ 2014-10-03 15:27:46 │       1 │
│ 2014-10-03 15:29:45 │       1 │
│ 2014-10-03 15:43:07 │       4 │
│ 2014-10-03 15:43:54 │       1 │
│ 2014-10-03 15:44:20 │       1 │
│ 2014-10-03 15:45:09 │       1 │
│ 2014-10-03 16:47:02 │       1 │
│ 2014-10-03 17:01:43 │       1 │
└─────────────────────┴─────────┘

10 rows in set. Elapsed: 0.481 sec. Processed 11.99 million rows, 47.95 MB (24.93 million rows/s., 99.73 MB/s.)`

**Comment by demenkov** [comment]
> Now it returns `2106-02-07 06:28:16`. Even better.

I think it is not better, because when use in interval it will produce unexpected results.

`SELECT 
    close_time, 
    count(*)
FROM mt4_trade 
WHERE close_time <= '1970-01-01 00:00:00'
GROUP BY close_time
ORDER BY close_time ASC
LIMIT 10

┌──────────close_time─┬─count()─┐
│ 2014-10-02 20:43:47 │       1 │
│ 2014-10-02 21:00:52 │       1 │
│ 2014-10-03 15:27:46 │       1 │
│ 2014-10-03 15:29:45 │       1 │
│ 2014-10-03 15:43:07 │       4 │
│ 2014-10-03 15:43:54 │       1 │
│ 2014-10-03 15:44:20 │       1 │
│ 2014-10-03 15:45:09 │       1 │
│ 2014-10-03 16:47:02 │       1 │
│ 2014-10-03 17:01:43 │       1 │
└─────────────────────┴─────────┘

10 rows in set. Elapsed: 0.473 sec. Processed 11.99 million rows, 47.95 MB (25.34 million rows/s., 101.34 MB/s.) 
`

**Comment by GanBob** [comment]
hello，I  am troubled by this situation：
 clickhouse-client -q "select toStartOfMinute(toDateTime(0));"
0000-00-00 00:00:00
clickhouse-client -q "select toStartOfHour(toDateTime(0));"
0000-00-00 00:00:00
clickhouse-client -q "select toDate(toDateTime(0));"
0000-00-00
 clickhouse-client -q "select toStartOfYear(toDateTime(0));"
0000-00-00
but 
clickhouse-client -q "select toMonday(toDateTime(0));"
2106-02-07
I want clickhouse-client -q "select toMonday(toDateTime(0));" return 0000-00-00
please help me
