### ISSUE TITLE
MaterializedPostgresql database does not show all tables

### ISSUE THREAD

**Issue by zkuser2002** [ClickHouse/ClickHouse#34712]
when I use  MaterializedPostgresql as this way
CREATE DATABASE postgres_database
ENGINE = MaterializedPostgreSQL('postgres1:5432', 'postgres_database', 'postgres_user', 'postgres_password')
SETTINGS materialized_postgresql_schema = 'postgres_schema';

it only show some tables of that schema and does not  all tables . I use 22.1.3.7 version (edited) 

When I use Matrerialized_Postgresql_table_list it work But I have to do for each 50 table one by one it's so difficult to do that in each db

**Comment by zkuser2002** [comment]
@kssenii thanks if you send an example quesry for do that, because I do every method in documentation but at the end I got error or I got only some tables for database again

**Comment by kssenii** [comment]
> @kssenii thanks if you send an example quesry for do that

I just sent it in the previous comment above:
```
SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = <schema>;
```
Tables list is determined by this query.

If some tables are in this list and are not in MaterializedPostgreSQL database then it means that there was some error when loading them from PostrgeSQL. You can see the reason for that in logs. Most often this happens because there is not primary key/replica identity index in PostgreSQL tables or some other error. 
Such tables (which fail to be loaded) are just skipped from replication. This is an expected behaviour. See logs for more information why some tables were skipped.

**Comment by zkuser2002** [comment]
you're right Kssenii, I try to do that again with use materialized_postgresql_tables_list ={}, and when I write all tables name, it does not work and output show 0 tables in db, but when I write only the tables_name that show in last query; in new query it works, so it maybe for other reason as you told in PostgreSQL definition of other tables .
