### ISSUE TITLE
weird magic with projections + minmax index  

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#34779]
```sql
create table test ( id Int64, d Int64 ) Engine=MergeTree partition by (intDiv(d, 10000)) Order by id;
set max_partitions_per_insert_block=0;
insert into test select number, number from numbers(1e8);

select count(if(d=4, d, 1)) from test;
1 rows in set. Elapsed: 0.009 sec.

select count(if(d=4, Null, 1)) from test;
1 rows in set. Elapsed: 0.998 sec. Processed 100.00 million rows, 800.00 MB (100.19 million rows/s., 801.52 MB/s.)

select count(d/3) from test;
1 rows in set. Elapsed: 0.006 sec.

-- WHY Processed 10.10 thousand rows ? Number of partitions? is it normal ?
select count(1) from test;
1 rows in set. Elapsed: 0.053 sec. Processed 10.10 thousand rows, 338.81 KB (188.96 thousand rows/s., 6.34 MB/s.)

select count(id) from test;
1 rows in set. Elapsed: 0.803 sec. Processed 100.00 million rows, 800.00 MB (124.50 million rows/s., 996.02 MB/s.)
```

**Comment by amosbird** [comment]
> -- WHY Processed 10.10 thousand rows ? Number of partitions? is it normal ?

It's the number of parts (projection parts of  `_minmax_count_projection` )

It seems trivial count optimization is better for certain cases because of its simpler pipeline. And current strategy of picking the opitmization is based on our implementation details:  `AggregateFunctionCountNotNullUnary`.

BTW, this means https://github.com/ClickHouse/ClickHouse/issues/34035 will also be slower compared to the current implementation of trivial count optimization . (@KochetovNicolai please check if it's true)

I'll reimplement trivial count optimization inside projection instead to avoid such performance regression.

**Comment by KochetovNicolai** [comment]
Yes, for this case count + projections are better. (Actually, ordinary trivial-count-optimization does not work).
I think we can have both actually, one for trivial count - when we clearly see that no columns are to read from storage, and another one more sophisticated with projections (and it could be disabled just in case).
