### ISSUE TITLE
ALTER TABLE UNFREEZE for removed tables

### ISSUE THREAD

**Issue by ianton-ru** [ClickHouse/ClickHouse#34794]
In ordinary case backup creation has these steps:
- "ALTER TABLE table_name FREEZE WITH NAME 'backup_name'"
- copy files from <disk_path>/shadow/backup_name to backup storage
- "ALTER TABLE table_name UNFREEZE WITH NAME 'backup_name'" to cleanup data.

When ClickHouse uses remote storage like S3/HDFS/etc. then UNFREEZE cannot be executed after backup, because files in 'shadow' folder are required to keep remote objects from removing (partitions in actual table can be removed by TTL or other reasons but remote data still required to restore old state from backup), so UNFREEZE is called only when backup removed, may be weeks or months later.

With this gap table has a good chance to be removed between FREEZE and UNFREEZE. In this case "ALTER TABLE table_name UNFREEZE" fails with error "Table table_name doesn't exist", and files in 'shadow' keeps space on local drive.
This files can be removed with external script, but this script can't correctly remove objects on remote storage (some of them can be still required, for other backup on other replica for example).

So I think we need ability to unfreeze this freezed data by some request to ClickHouse.

It may be calls MergeTreeData::removeDetachedPart for all freezed part folders, but this needs some valid SQL request.

Variants:
- "ALTER TABLE table_name UNFREEZE WITH NAME 'backup_name'" with removed table_name. May be difficult and unclean, because shadow data contains table UUID but not table name, table may be recreated with the same name and other UUID. But request will be the same before and after table removing.
- "(SYSTEM) UNFREEZE (ALL) WITH NAME 'backup_name'" to remove all data for all tables with this freeze name.

**Comment by den-crane** [comment]
removed tables OR remote tables ?

**Comment by Alex-Burmak** [comment]
Removed/Deleted tables. ALTER TABLE UNFREEZE works only for existing tables and there is no SQL query to remove freezed data for deleted tables.

**Comment by PolyProgrammist** [comment]
Ok, so more about both variants:

1) "ALTER TABLE table_name UNFREEZE WITH NAME 'backup_name'"
The problem is that the table may be deleted and then created again. In this case UUID will not be the same and backup is not going to be deleted on unfreeze. 
The table with UUID that was at the moment of backup creation is the one that should be deleted. In order to do that, there are two options: 
a) Try to figure out an old uuid somehow based on the files of backup and unfreeze them
b)  Create a system.backups table that will track all backups. It will include at least backup id, table name and table uuid. The table's uuid could be figured out from this table. The corresponding partitions could be unfreezed

his solution is more consistent with current status so that one table at a time can be freezed and unfreezed. 

2) (SYSTEM) UNFREEZE (ALL) WITH NAME 'backup_name'" to remove all data for all tables with this freeze name.
 The drawback is that it doesn't fix the problem for one table and if you would like to delete just one table for backup, it is not possible. However this solution seems easier to implement. Also it provides a simple approach to delete the whole backup without thinking which tables a backup has. It is common to freeze and unfreeze all the tables in backup at once.

What do you think? Which way do you prefer?

**Comment by Alex-Burmak** [comment]
I'd start with implementing the second option. It's straightforward to implement and easy to use.

The first option provides more fine-grained control on what data to delete. It can be implemented later if required.
