### ISSUE TITLE
What is the role of Pipe in the Pipeline executor?

### ISSUE THREAD

**Issue by XinShuoWang** [ClickHouse/ClickHouse#34930]
Recently, I was looking at the code of Clickhouse's executor, and I found that there is an abstract structure called `Pipe`. There is such a sentence "Pipe is a set of processors which represents the part of pipeline" in the comments, but I still don't quite understand it. 

- The role of Pipe, such as in Figure 1, which parts are Pipe? 
- Why abstract the structure of Pipe?
- Is the specific composition of the Pipeline in the form of the upper figure in Figure 2, or the form below? The upper picture in Figure 2 indicates Pipeline=Pipe1 + Pipe2, and the lower picture indicates Pipeline=Pipe1 + Processor1 + ...+Processor5
- Is there anything to learn about Clickhouse's Pipeline executor?

![Fig 1](https://user-images.githubusercontent.com/56379080/155869470-7a41106a-c690-4b34-933c-0ee981b24ae0.png)

![image](https://user-images.githubusercontent.com/56379080/155869564-3c12dd18-6165-44d0-b8b7-bad3638d937d.png)

**Comment by KochetovNicolai** [comment]
Pipe is just a specific container for processors, with some useful invariants.
PipelineExecutor itself uses `std::vector` of processors, it also checks all ports are connected. So, you don't need a pipe to create/execute pipeline. However, in order to build a graph, it is more convenient not to use just a `std::vector`, but also maintain a set of non-connected ports.
https://github.com/ClickHouse/ClickHouse/blob/af4362e40a995af76be449dc87728b0a1c174028/src/QueryPipeline/Pipe.h#L19-L22

**Comment by KochetovNicolai** [comment]
Figure 1 does not show any Pipe. Gray rectangles are steps from query execution plan.
