### ISSUE TITLE
CAST to IPv6 on empty strings changed between 21.x and 22.x

### ISSUE THREAD

**Issue by Ryado** [ClickHouse/ClickHouse#35156]
**Describe the issue**
On empty strings, the behaviour of the function `CAST('', 'IPv6')` changed between the versions 21.x and 22.x

**How to reproduce**
On 21.8.14.5:
```
SELECT CAST('', 'IPv6');
Returns: 
	
::
```

On 22.2.2.1:
```
SELECT CAST('', 'IPv6');
Triggers error: 

Code: 441. DB::Exception: Invalid IPv6 value.: While processing CAST('', 'IPv6'). (CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING) (version 22.2.2.1)

```

**Additional context**
This can prevent some users from upgrading to 22.x when the use of this function is spread across a number of table definitions and environments. The following workaround `CAST(toFixedString('', 16), 'IPv6')` works but the manual task of updating all the occurrences is challenging.

**Comment by alexey-milovidov** [comment]
@kitaisreal checked the code and found that previous behaviour was a bug.
In previous versions, every invalid input was casted to `::`.

For bug-compatibility with old versions we are going to introduce a setting that a customer can enable.

**Comment by genzgd** [comment]
Unfortunately the fix doesn't work for column default expressions.  We have a request to extend the setting/fix behavior.

```
set cast_ipv4_ipv6_default_on_conversion_error = 1

ALTER TABLE ipv6_test
    MODIFY COLUMN `value` IPv6 DEFAULT ''

Received exception from server (version 22.4.1):
Code: 441. DB::Exception: Received from localhost:9000. DB::Exception: Invalid IPv6 value: While processing _CAST('' AS value_tmp_alter12115621927106792052, 'IPv6') AS value: default expression and column type are incompatible.. (CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING)
```

**Comment by tavplubix** [comment]
#37761 does not fix the issue and even makes it worse: https://pastila.nl/?0059f5ea/c81104572f98aa7be4639d617268b619
Also Stress Tests in CI fail because of this sometimes: https://s3.amazonaws.com/clickhouse-test-reports/0/753a51908309dd9c71bc107ec9ad23b0aeac1a5d/stress_test__thread__actions_.html
(seems like it's the first real bug caught by Backward Compatibility Check)

**Comment by kitaisreal** [comment]
This setting need to be set in config.xml during migration. You can accidentially set this setting create invalid table state and after that server cannot be restarted. This can be done with dozen of other settings. In backward compatibility check we need to somehow detect such settings.

**Comment by tavplubix** [comment]
What migration are you talking about? I've simply executed a few queries from `02316_cast_to_ip_address_default_column` and restarted clickhouse-server (the same version, without any migrations). Server failed to start. It should never happen.

**Comment by kitaisreal** [comment]
You set setting that is necessary for migration. Then you created table with such setting (it is not allowed by default). Then you restarted server.

**Comment by kitaisreal** [comment]
Probably it makes sense to replace part of `cast_ipv4_ipv6_default_on_conversion_error` setting that works for internal cast with some `internal_cast_ipv4_ipv6_default_on_conversion_error`, that will work only during migration, and cannot be specified as part of session. `cast_ipv4_ipv6_default_on_conversion_error` make sense for session level if some queries are depend on old behaviour.
Now this can be an issue if client does not understand internals he can set setting, insert wrong data into table, or create table with wrong configuration, checks will be disabled because of setting, after restart it will not work.

**Comment by tavplubix** [comment]
A user should not be able to make server fail to restart by simply executing some queries (just like they should not be able to make server crash). We cannot avoid all such cases, but we should reduce number of them as much as possible. 

It gets especially funny, when clickhouse-server is running in k8s and it enters crash loop...

We can set this setting to `true` when starting the server, so it will be able to load any metadata.

**Comment by tavplubix** [comment]
Another way to fix it is to normalize AST before writing it on disk and automatically replace expressions like `CAST('', 'IPv4')` with `CAST('0.0.0.0', 'IPv4')`
