### ISSUE TITLE
quantileDeterministic() returns NaN when the number of input datum exceeds a certain threshold

### ISSUE THREAD

**Issue by MikageSawatari** [ClickHouse/ClickHouse#35317]
**Describe what's wrong**
    
    The function `quantileDeterministic()` returns NaN when the
    number of input datum exceeds a certain threshold.
    
    **Does it reproduce on recent release?**
    
    The issue happens on ClickHouse server version 21.12.2.
    
    v21.12.2.17-stable was released on 2021-12-16.
    
    **How to reproduce**
    
    Perform a query so that more than 8192 data points are given to
    the function:
    
    ```
    SELECT quantileDeterministic(A.number, 1) AS quantileDeterministic
    FROM
    (
        SELECT number
        FROM system.numbers
        LIMIT 8193
    ) AS A
    ```
    
    Result:
    ```
    quantileDeterministic
    nan
    ```
    
    **Expected behavior**
    
    The function returns a result similar to that of
    `quantileExactWeighted()`, which returns a numeric result for the
    same input:
    
    ```
    SELECT quantileExactWeighted(A.number, 1) AS quantileExactWeighted
    FROM
    (
        SELECT number
        FROM system.numbers
        LIMIT 8193
    ) AS A
    ```
    
    Result:
    ```
    quantileExactWeighted
    4096
    ```

**Comment by alexey-milovidov** [comment]
@MikageSawatari Your usage of `quantileDeterministic` is invalid.
The second argument is "determinator". It has to be deterministic pseudo-random number that will be used to filter out the data when the amount of data is large. When you passed constant 1, then all of the data will be filtered away if the amount of data is large. That's why you get `NaN`.

PS. `quantileDeterministic` is an "expert only" function. Better not to use it.
