### ISSUE TITLE
Is there a way to remove duplicate data on ReplacedMergeTable between shards when select on distributed table on cluster?

### ISSUE THREAD

**Issue by yandongl** [ClickHouse/ClickHouse#35352]
Is there a way to remove duplicate data on ReplacedMergeTable between shards when select on distributed table on cluster?
Hi, I build a distributed table on cluster based on ReplacedMergeTable. However, I found the ops of remove duplicate data only happen each server inside. Is there a way to remove duplicate data on ReplacedMergeTable between shards when select on distributed table on cluster?

1. using **FINAL**: ops of remove duplicate data only happen each server inside.
2. using the sorting key as sharding key. So, there will no duplicate data between shards.

However, I still want to know, how can i do if not using sorting key as sharding key or there is already some duplicate data between shards.

**Comment by genzgd** [comment]
This is not currently supported.  Shard data is completely independent other than when it is combined as part of a query to a distributed table.  You must either ensure that shard data is unique by controlling inserts (as you did with by creating a sharding key based on sort key), deduplicate with your query with GROUP BY and aggregate functions (which is slow), or otherwise deduplicate in your client application (also slow).
