### ISSUE TITLE
clickhouse ignores LDAP configuration part when LDAP is used as remote catalog

### ISSUE THREAD

**Issue by drook** [ClickHouse/ClickHouse#35481]
**Env:**
OS: FreeBSD 13.0-RELEASE
Server version: clickhouse-22.1.3.7 from ports.
LDAP: external OpenLDAP installation.

I'm able to configure LDAP instance as an external authenticator in the users.xml file. But not as a remote catalog - when I'm configuring it that way, clickhouse ignores LDAP configuration. I'm concluding this observing tcpdump on external (actually the only) interface of clickhouse server - it doesn't attempt to resolve and/or establish a tcp/389 connection to a configured server. Logs shows only the usual stuff also shown below.

Relevant config part:
````
    <ldap_servers>
        <fmk>
            <host>ldap.findmykids.org</host>
            <port>389</port>
            <bind_dn>cn={user_name},ou=users,dc=findmykids,dc=org</bind_dn>
            <verification_cooldown>10</verification_cooldown>
            <enable_tls>no</enable_tls>
        </fmk>
    </ldap_servers>

    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/db/clickhouse/access/</path>
        </local_directory>

        <ldap>
            <server>fmk</server>
                <roles>
                    <test/>
                </roles>
        </ldap>
    </user_directories>
````

Role test is configured locally. The behavior doesn't change with or without <roles/> part.

Relevant log entries:
````
2022.03.21 19:55:05.072289 [ 232348 ] {} <Error> Access(user directories): from: 127.0.0.1, user: ezheganin: Authentication failed: Code: 192. DB::Exception: There is no user `ezheganin` in user directories. (UNKNOWN_USER), Stack trace
(when copying this message, always include the lines below):

0. 0xf960952
1. 0x6c1b1eb
2. 0xdb8ce7f
3. 0xdba932c
4. 0xdb8ff72
5. 0xdb0e732
6. 0xe563068
7. 0xe562bd8
8. 0xee8f2ce
9. 0xee8b023
10. 0xee9abe7
11. 0xf94ebec
12. 0xf94f0d5
13. 0xf9c8737
14. 0xf9c5dd4
15. 0x8108e282b
 (version 22.1.3.1)
2022.03.21 19:55:05.072452 [ 232348 ] {} <Error> ServerErrorHandler: Code: 516. DB::Exception: ezheganin: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):

0. 0xf960952
1. 0x6c1b1eb
2. 0xdb0e902
3. 0xe563068
4. 0xe562bd8
5. 0xee8f2ce
6. 0xee8b023
7. 0xee9abe7
8. 0xf94ebec
9. 0xf94f0d5
10. 0xf9c8737
11. 0xf9c5dd4
12. 0x8108e282b
 (version 22.1.3.1)
````

**Comment by e-mars** [comment]
Hi @drook .

the ldap configuration should be in the `config.xml`.

Below is a preview of a user guide that will be in our next set of documentation:
*This example works with a public and external ldap so should be simple to test in your environment and compare settings with your target ldap server.

------
# Configuring ClickHouse to use LDAP for authentication and role mapping

ClickHouse can be configured to use LDAP to authenticate ClickHouse database users.
This guide provides a simple example of integrating ClickHouse with an LDAP system authenticating to a publicly available directory.

***In the following procedures the ClickHouse CLI is used.***

## 1. Configure LDAP connection settings in ClickHouse
1. Test connection to public ldap server:
```bash
$ ldapsearch -x -b dc=example,dc=com -H ldap://ldap.forumsys.com
```

the reply will be something like this:
```
# extended LDIF
#
# LDAPv3
# base <dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# example.com
dn: dc=example,dc=com
objectClass: top
objectClass: dcObject
objectClass: organization
o: example.com
dc: example
...
```

2. Edit the `config.xml` file and add the following to configure ldap settings
```xml
    <ldap_servers>
        <test_ldap_server>
           <host>ldap.forumsys.com</host>
           <port>389</port>
           <bind_dn>uid={user_name},dc=example,dc=com</bind_dn>
           <enable_tls>no</enable_tls>
           <tls_require_cert>never</tls_require_cert>
        </test_ldap_server>
    </ldap_servers>
```

_*the `<test_ldap_server>` tags is an arbitrary label to identify a particular ldap server_

These are the basic settings used above:

|Parameter |Description                   |Example              |
|----------|------------------------------|---------------------|
|host      |hostname or IP of LDAP server |ldap.forumsys.com    |
|port      |directory port for LDAP server|389                  |
|bind_dn   |template path to users        |uid={user_name},dc=example,dc=com|
|enable_tls|whether to use secure ldap    |no     |
|tls_require_cert |whether to require certificate for connection|never|

:::note
In this example, since the public server uses 389 and does not use secure port, we disable TLS to allow it to connect for demonstration purposes.
:::

**Below is link to the full configuration parameters available for the server definitions:**

https://clickhouse.com/docs/en/operations/external-authenticators/ldap/#ldap-server-definition

3. Add the `<ldap>` section to `<user_directories>` section to configure the user role mapping

This section defines when a user is authenticated, what role the user will receive. In this basic example, any user authenticating to LDAP will receive the `scientists_role` which will be defined at a later step in ClickHouse.

The section should look similar to this:

```xml
    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/lib/clickhouse/access/</path>
        </local_directory>
        <ldap>
              <server>test_ldap_server</server>
              <roles>
                 <scientists_role />
              </roles>
              <role_mapping>
                 <base_dn>dc=example,dc=com</base_dn>
                 <search_filter>(&amp;(objectClass=groupOfUniqueNames)(uniqueMember={bind_dn}))</search_filter>
                 <attribute>cn</attribute>
              </role_mapping>
        </ldap>
    </user_directories>
 ```

These are the basic settings used above:

|Parameter |Description                   |Example              |
|----------|------------------------------|---------------------|
|server    |label defined in the prior ldap_servers section|test_ldap_server|
|roles      |name of the roles defined in ClickHouse the users will be mapped to|scientists_role|
|base_dn   |base path to start search for groups with user        |dc=example,dc=com|
|search_filter|ldap search filter to identify groups to select for mapping users    |(&amp;(objectClass=groupOfUniqueNames)(uniqueMember={bind_dn}))|
|attribute |which attribute name should value be returned from|cn|


**Below is link to the full configuration parameters available for the ldap group and role mapping:**

https://clickhouse.com/docs/en/operations/external-authenticators/ldap/#ldap-external-user-directory

4. Restart ClickHouse server to apply settings.

## 2. Configure ClickHouse database roles and permissions

:::note
The procedures in this section assumes that SQL Access Control and Account Management in ClickHouse has been enabled. To enable see SQL Users and Roles admin guide.
:::

1. Create a role in clickhouse with the same name used in the role mapping section of the `config.xml` file
```sql
CREATE ROLE scientists_role;
```

2. Grant needed privileges to the role:

_*for demonstration purposes, the following grants admin privileges to any user able to authenticate through ldap._

```sql
GRANT ALL ON *.* TO scientists_role;
```

## 3. Test the LDAP configuration

1. Login using the ClickHouse client
```bash
$ clickhouse-client --user einstein --password password
ClickHouse client version 22.2.2.1.
Connecting to localhost:9000 as user einstein.
Connected to ClickHouse server version 22.2.2 revision 54455.

chnode1 :)
```

:::note
Use the `ldapsearch` command in step 1 to view all of the users available in the directory and for all of the users the password is `password`
:::

2.  Test that the user was mapped correctly to the `scientists_role` role and has admin permissions
```sql
chnode1 :) SHOW DATABASES;

SHOW DATABASES

Query id: 93b785ff-1482-4eda-95b0-b2d68b2c5e0f

┌─name───────────────┐
│ INFORMATION_SCHEMA │
│ db1_mysql          │
│ db2                │
│ db3                │
│ db4_mysql          │
│ db5_merge          │
│ default            │
│ information_schema │
│ system             │
└────────────────────┘

9 rows in set. Elapsed: 0.004 sec.
```

## 4. Summary
This article demostrated the basics of configuring ClickHouse to authenticate to an LDAP server and also to map to a role.  There are also options for configuring individual users in ClickHouse but having those users be authenticated by LDAP without configuring automated role mapping. The LDAP module can also be used to connect to Active Directory.
----

**Comment by drook** [comment]
Oh, that is a fine piece of the documectation indeed. I can also see that _**ldap.forumsys.com**_ is a nice and properly configured public LDAP server (may the ones who configured it live long and prosper). But the thing is - even with your proposed parts of the configuration files that I applied, my clickhouse installation behaves identically.

Could you point me to a diirection where the logger facilities are described so I could push the verbosity to a maximum for AAA facility and see why the CH doesn't even try to look in the LDAP catalog ?

**Comment by e-mars** [comment]
hi @drook,

currently there is no specific logging to just enable for ldap. 
the logging would be in:
```
<logger>
   <level>trace</level>
</logger>
```

Were you able to test to `ldap.forumsys.com` with the settings in the document from your environment?
It would help to know if there is something wrong with the config steps I provided or the ClickHouse instance.
Or basically, is there some configuration to the external ldap where possibly the `search_filter` or `DN` or `attribute` is not quite correct. 
in the filter I used above, it is due to the object and member classes used by the public server, maybe your target is defined with other attributes.

i checked my lab instance where this doc is drawn from and i can see that there is currently no messages that get emitted like `connecting to my.ldapserver.com`, etc.  which is what i'm assuming you are looking for.
I'm checking with some team members to see if there is a way to enable.

**Comment by drook** [comment]
No, CH doesn't log anything about LDAP at trace level - I'm running it right now.

The more we are discussing this, the more I get the feeling that this is some sort of bug.

**Comment by e-mars** [comment]
hi @drook ,

i checked with dev team at ClickHouse, looks like we don't have more info/debug type logging other than the error level you see currently.
I also checked the main ldap modules and looks like they do not have verbose logging:
https://github.com/ClickHouse/ClickHouse/blob/fe1bed0b401691be3bcc12e8b7d4f35073399b37/src/Access/LDAPClient.cpp

This can be put in as an enhancement request but will need to identify what messages and at what steps would be useful.

You may be able to use `strace` to get a bit more info on what ClickHouse is using for connections, something like this:
```
strace -f -e trace=network -o strace.txt -p <pid>
```

i ran it on my lab instance and can see a few items, like user (tesla), ldap url, IP, etc. which might provide some useful information.
```
469329 recvfrom(174, "\0\21ClickHouse client\26\2\267\251\3\0\5tesla\10"..., 1048576, 0, NULL, NULL) = 40
469329 getpeername(174, {sa_family=AF_INET, sin_port=htons(34442), sin_addr=inet_addr("127.0.0.1")}, [128->16]) = 0
469329 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 176
469329 setsockopt(176, SOL_IP, IP_RECVERR, [1], 4) = 0
469329 connect(176, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, 16) = 0
469329 sendmmsg(176, [{msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="(\v\1 \0\1\0\0\0\0\0\1\4ldap\10forumsys\3com\0\0"..., iov_len=46}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=46}, {msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\361\6\1 \0\1\0\0\0\0\0\1\4ldap\10forumsys\3com\0\0"..., iov_len=46}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=46}], 2, MSG_NOSIGNAL) = 2
469329 recvfrom(176, "(\v\201\200\0\1\0\1\0\0\0\1\4ldap\10forumsys\3com\0\0"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, [28->16]) = 62
469329 recvfrom(176, "\361\6\201\200\0\1\0\0\0\0\0\1\4ldap\10forumsys\3com\0\0"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, [28->16]) = 46
469329 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 176
469329 setsockopt(176, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
469329 setsockopt(176, SOL_TCP, TCP_NODELAY, [1], 4) = 0
469329 connect(176, {sa_family=AF_INET, sin_port=htons(389), sin_addr=inet_addr("52.87.186.93")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

As far as being a bug, there could be, however, the example should work and if we can get the right parameters configured in the way that the target ldap server wants, should help in determining where the issue might be.

**Comment by drook** [comment]
Turns out that LDAP functionality was merely missing from FreeBSD databases/clickhouse port. Terribly sorry for consuming this amount of your time. Official build binary is simply working with configuration intact.
