### ISSUE TITLE
schema interface question

### ISSUE THREAD

**Issue by Faynebupt** [ClickHouse/ClickHouse#35792]
File function uses schema inference, saying that it is not in this folder. Only the data in this folder can be inferred and read

![image](https://user-images.githubusercontent.com/19455764/161017243-7a1362b3-1b4c-45e0-bbb5-51ad1ecd12de.png)

![image](https://user-images.githubusercontent.com/19455764/161017541-501ce480-d6a7-45c2-bd9f-80fa1b9f8ab5.png)

**Comment by Avogar** [comment]
This is an expected behaviour. You can look at the documentation: https://clickhouse.com/docs/en/sql-reference/table-functions/file/
Table function file accepts relative path to the file from [user_files_path](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-user_files_path) setting. You cannot access files outside this folder, but you can change this folder in server config.
