### ISSUE TITLE
Bad insert into MV with Engine=URL

### ISSUE THREAD

**Issue by adubovikov** [ClickHouse/ClickHouse#35837]
It will be great have some retries and drops for INSERTS if you have a material view with Engine=URL and HTTP server is gone.
Currently all INSERTS will be failed, even in the main table, so it should be like soft exception. 

Also will be great if ENGINE=Url won't send "Connection: close" in HTTP request  :-)

P.S. We have discussed about this feature with @alexey-milovidov :-)

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/21721

**Comment by alexey-milovidov** [comment]
insert_into_url_max_tries = 5
insert_into_url_retry_initial_backoff_ms = 1000
insert_into_url_retry_max_backoff_ms = 10000
insert_into_url_drop_on_failure = false

The backoff time will start with the initial_backoff_ms, will be multiplied by 2 on every subsequent try, and capped by the max_backoff_ms. If all the retries are unsuccessful, if insert_into_url_drop_on_failure is false, an exception will be thrown, otherwise, the error will be logged but the query will succeed.
