### ISSUE TITLE
Fallback format and table for streaming engines (Kafka, RabbitMQ, FileLog)

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#36035]
**Use case**

Put unparsed records into a separate table. The records will be splitted by fallback format, like LineAsString or RawBLOB.

**Comment by alexey-milovidov** [comment]
Ilya Yatsishin
It can be some common system table with format database, table, timestamp, offset, value.

Alexey Milovidov
Yes, makes sense. Like system.unparsed_messages

**Comment by UnamedRus** [comment]
Not only those.

There is such table in Redshift for import of data from S3 as well.

BTW for Kafka and other streaming engines it's already possible https://github.com/ClickHouse/ClickHouse/pull/21850
https://kb.altinity.com/altinity-kb-integrations/altinity-kb-kafka/error-handling/#after-216

**Comment by alexey-milovidov** [comment]
@Avogar looks like implemented, can we close this?

**Comment by Avogar** [comment]
> @Avogar looks like implemented, can we close this?

Not quite. Now we can write unparsed records in a file in `user_files` directory, file name can be specified by setting `input_format_record_errors_file_path` and format for file can be specified by setting `errors_output_format`. But it will work only when `input_format_allow_errors_num` or `input_format_allow_errors_ratio` is used. And it will work only for some subset of formats (row formats with diagnostic info like CST, TSV, Template, CustomSeparated and JSONCompact). And by now `input_format_record_errors_file_path` doesn't work with streaming engines (it requires some additional changes, not difficult).
So, what I think:
We can try to extend current implementation to save unparsed records for formats that support sync after error, not only with diagnostic info (all row text input formats plus Avro and Protobuf) and support it for streaming engines.
Questions:
Do we need to extend current implementation to save unparsed messages to system table or file is ok? If we will create system table, will it contain unparsed messages only for streaming engines or for any data parsing processes? For example, we can add setting like `input_format_record_errors_method` with values `none/file/system_table`. When it's `file` we will use file from setting `input_format_record_errors_file_path`, if `system_table` then use system table, if `none` we will do nothing.
Also there is a possible problem that we cannot always get unparsed message from buffer, because this data could be already gone from buffer (current implementation just writes `Buffer has gone, cannot extract information about what has been parsed` instead of unparsed row).
So, what do you think?

**Comment by alexey-milovidov** [comment]
> Do we need to extend current implementation to save unparsed messages to system table or file is ok?

A file is ok.

> Also there is a possible problem that we cannot always get unparsed message from buffer, because this data could be already gone from buffer

We can use `PeekableReadBuffer`, if it has almost zero overhead.

**Comment by alexey-milovidov** [comment]
Let's do this: https://github.com/ClickHouse/ClickHouse/issues/16716

**Comment by Avogar** [comment]
I was wrong, it's indeed already implemented in https://github.com/ClickHouse/ClickHouse/pull/21850 for Kafka engine. Just need to implement the same logic for other streaming engines. I will do it
