### ISSUE TITLE
 why optimize_move_to_prewhere skips PK fields?

### ISSUE THREAD

**Issue by neilxxx** [ClickHouse/ClickHouse#36096]
#2601

 why optimize_move_to_prewhere skips PK fields?

#2601 answer actually the case when PREWHERE helps for indexed fields is not frequent. If we will allow to move conditions on indexed fields to PREWHERE, they will be almost always selected for PREWHERE, because these fields are usually high compressed. But it will usually make less profit than moving other columns

Can you explain it in more detail

**Comment by tom-clickhouse** [comment]
Assume a table with three columns `user`, `url`, and `timestamp` containing logs about users that accessed urls at a specific time.

- `user` is PK field which means that the table rows are sorted by user ascending:

user url timestamp
u1 u3 ts...
u1 u1 ts...
u1 u8 ts...
u1 u1 ts...
u1 u4 ts...
u1 u5 ts...
u1 u1 ts...
u2 u4 ts...
u2 u12 ts...
u2 u2 ts...
... ... ...

- we assume a granule size of 3 for this mini example, by default the granule size is 8192 (set by [index_granularity](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/) setting)
- ClickHouse is processing data in terms of granules meaning that not individual rows are read but blocks of rows, the following shows the first 4 granules of the table:   

user url timestamp

u1 u3 ts...
u1 u1 ts...
u1 u8 ts...

u1 u1 ts...
u1 u4 ts...
u1 u5 ts...

u1 u1 ts...
u2 u4 ts...
u2 u12 ts...

u2 u2 ts...
... ... ...


- the primary index that results from the table's primary key `user` contains the minimum primary key value for each granule, and for our example table the index would like this:

u1 -> location of first granule
u1 -> location of second granule
u1 -> location of third granule
u2 -> location of fourth granule...

- If we are searching for all rows where the user is u1 (`SELECT * ... WHERE user = u1`) then via binary search over the index entries ClickHouse can identify all granules (the first three granules for our example table) that possibly contain matching rows
- ClickHouse then is reading (streaming) all `user` values AND all `url` values AND all `timestamp` values for the rows belonging to the first three granules
- note that ClickHouse is unnecessarily reading all the column values from two rows from the third granule ([u2 u4 ts...] and [u2 u12 ts...]

If instead `WHERE user = u1` would be moved to a `PREWHERE user = u1` then ClickHouse would first ONLY read the `user` values of the selected granules, then check for which rows the user values are `u1` and then read the other columns `url` and `timestamp` ONLY for blocks of rows where the  `PREWHERE user = u1` is true for at least some rows.

But because the table rows are sorted by the primary key column `user`, most granules selected by the primary index are completely encompassing the WHERE condition, so moving the WHERE to a PREWHERE results in ClickHouse doing extra work (checking the user values from the selected granules) without much profit.

However, for a query like `SELECT * ... WHERE user = u1 AND url = u5` it is beneficial to move `url = u5` to a `PREWHERE url = u5`. Then ClickHouse would first ONLY read the `url` values of the selected three granules (selected for the `user = 1` predicate), and then read the other column's values ONLY for blocks of rows where the `PREWHERE url = u5` is true for some rows. Effectively ClickHouse will read the other column's values only for the second granule, but not for the first and third granule.
This profit stems from the fact that the non key column values of our example table are more scattered.

**Comment by neilxxx** [comment]
@tom-clickhouse Thanks for your answer

But because the table rows are sorted by the primary key column user, most granules selected by the primary index are completely encompassing the WHERE condition, so moving the WHERE to a PREWHERE results in ClickHouse doing extra work (checking the user values from the selected granules) without much profit.

No matter WHERE or PREWHERE, checking the user values from the selected granules ,it is unavoidable，isn't it？WHERE also need to checking the user values from the selected granules

However, for a query like `SELECT * ... WHERE user = u1 AND url = u5` it is beneficial to move `url = u5` to a `PREWHERE url = u5`. Then ClickHouse would first ONLY read the `url` values of the selected three granules (selected for the `user = 1` predicate), and then read the other column's values ONLY for blocks of rows where the `PREWHERE url = u5` is true for some rows. Effectively ClickHouse will read the other column's values only for the second granule, but not for the first and third granule. This profit stems from the fact that the non key column values of our example table are more scattered.

ONLY  move `url = u5` to a `PREWHERE ，no move user =1， ClickHouse will first filter user  get  three granules ,before  read the `url` ?

**Comment by tom-clickhouse** [comment]
"No matter WHERE or PREWHERE, checking the user values from the selected granules ,it is unavoidable，isn't it？WHERE also need to checking the user values from the selected granules,so what extra work did PREWHERE do"

You are right. There is not really extra work - that was a wrong terminology, it's just that there is no real benefit of PREWHERE compared to WHERE in this case.

"ONLY move url = u5 to a PREWHERE ，no move user =1， ClickHouse will first filter user get three granules ,before read the url` ?"

Correct. But note that the filtering to get the three granules that potentially contain rows with `user =1` takes place with only accessing/reading the primary key entries. No data from the user column file is read yet. Only after 
reading the entries from the three selected granules from the url column file, the entries from the user column files are read for the rows where `url = 5 ` (which is checked by the PREWHERE).

**Comment by neilxxx** [comment]
@tom-clickhouse Thank you very much again for your answer

but I'm still a little torn

You are right. There is not really extra work - that was a wrong terminology, it's just that there is no real benefit of PREWHERE compared to WHERE in this case.

So PREWHERE is better than WHERE in any case(filter fields only PK), and the worst is the same,why optimize_move_to_prewhere skips PK fields?

**Comment by seanlaff** [comment]
Sometimes a PREHWERE on a primary key can speed up a query- imagine a table like this
```sql
CREATE TABLE t
(
    `entity` String
    `measurement` String,
    `val` Float64,
    `ts` DateTime
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(ts)
ORDER BY (entity, measurement, val, ts)
```
This table is optimized for compressibility (having `ts` be the last column)

Clickhouse will currently choose `measurement` for the PREWHERE automatically, but that may not be the best primary key to optimize.

If we query a timerange that is a tiny piece of the partition (query for 1 day of the 30 day partition), then it makes sense to put `ts` in the PREWHERE manually. If our timerange is more of the partition (25 days of the 30 day partition), moving `ts` to the PREWHERE is less beneficial.

**Comment by neilxxx** [comment]
hello,@tom-clickhouse 

I still don't understand，can you help me solve this test

mentioned in the #2601 

Table has an index (tags_id, created_at), 100M rows. Prewhere on index columns improves performance 3 times.

:) SELECT sum(cityHash64(*)) a FROM benchmark_cpu  where (tags_id, created_at) in (select tags_id, max(created_at) from benchmark_cpu group by tags_id);
1 rows in set. Elapsed: 2.132 sec. Processed 33.52 million rows, 4.46 GB (15.72 million rows/s., 2.09 GB/s.) 

:) SELECT sum(cityHash64(*)) a FROM benchmark_cpu  prewhere (tags_id, created_at) in (select tags_id, max(created_at) from benchmark_cpu group by tags_id);
1 rows in set. Elapsed: 0.680 sec. Processed 33.52 million rows, 268.69 MB (49.33 million rows/s., 395.37 MB/s.) 

where = 33.52 million rows,4.46GB
prewhere = 33.52 million rows,268.69MB



my test;

CREATE TABLE test(`user_id` Int64,url String) Engine=MergeTree() ORDER BY number;

user_id     url
1           size≈1.4MB string
...             ....
1           size≈1.4MB string 
2           size≈1.4MB string
...             ....
2           size≈1.4MB string

index_granularity  = 8192（default）;

so only one granule; 

total rows = 2000 rows.
user_id = 1   total = 1000 rows.
user_id = 2   total = 1000 rows.

selecet * from test where user_id = 1; 1000 rows in set. Elapsed: 13.814 sec. Processed 1.00 thousand rows, 1.45 GB (72.39 rows/s., 104.90 MB/s.)
selecet * from test prewhere user_id = 1; 1000 rows in set. Elapsed: 20.604 sec. Processed 1.00 thousand rows, 1.45 GB (48.53 rows/s., 70.33 MB/s.)

mentioned in the your answer ,note that ClickHouse is unnecessarily reading all the column values from two rows from the third granule ([u2 u4 ts...] and [u2 u12 ts...]

why where data size = 1.45GB，prewhere data size = 1.45GB? where not read all `url`（granule have 2000 rows `url`）?

**Comment by neilxxx** [comment]
> hello,@tom-clickhouse
> 
> I still don't understand，can you help me solve this test
> 
> mentioned in the #2601
> 
> Table has an index (tags_id, created_at), 100M rows. Prewhere on index columns improves performance 3 times.
> 
> :) SELECT sum(cityHash64(*)) a FROM benchmark_cpu where (tags_id, created_at) in (select tags_id, max(created_at) from benchmark_cpu group by tags_id); 1 rows in set. Elapsed: 2.132 sec. Processed 33.52 million rows, 4.46 GB (15.72 million rows/s., 2.09 GB/s.)
> 
> :) SELECT sum(cityHash64(*)) a FROM benchmark_cpu prewhere (tags_id, created_at) in (select tags_id, max(created_at) from benchmark_cpu group by tags_id); 1 rows in set. Elapsed: 0.680 sec. Processed 33.52 million rows, 268.69 MB (49.33 million rows/s., 395.37 MB/s.)
> 
> where = 33.52 million rows,4.46GB prewhere = 33.52 million rows,268.69MB
> 
> my test;
> 
> CREATE TABLE test(`user_id` Int64,url String) Engine=MergeTree() ORDER BY number;
> 
> user_id url 1 size≈1.4MB string ... .... 1 size≈1.4MB string 2 size≈1.4MB string ... .... 2 size≈1.4MB string
> 
> index_granularity = 8192（default）;
> 
> so only one granule;
> 
> total rows = 2000 rows. user_id = 1 total = 1000 rows. user_id = 2 total = 1000 rows.
> 
> selecet * from test where user_id = 1; 1000 rows in set. Elapsed: 13.814 sec. Processed 1.00 thousand rows, 1.45 GB (72.39 rows/s., 104.90 MB/s.) selecet * from test prewhere user_id = 1; 1000 rows in set. Elapsed: 20.604 sec. Processed 1.00 thousand rows, 1.45 GB (48.53 rows/s., 70.33 MB/s.)
> 
> mentioned in the your answer ,note that ClickHouse is unnecessarily reading all the column values from two rows from the third granule ([u2 u4 ts...] and [u2 u12 ts...]
> 
> why where data size = 1.45GB，prewhere data size = 1.45GB? where not read all `url`（granule have 2000 rows `url`）?

@tom-clickhouse hey,tom,Could you help me answer my questions when you have time

**Comment by tom-clickhouse** [comment]
@neilxxx Sorry for the delayed response as I was a week off for Easter Holidays here in Europe.

I reply to both parts of your last question.

--------------------------------------------
(1) Table has an index (tags_id, created_at)
--------------------------------------------

First of all, and sorry for the potential confusion, everything I discussed above, was related to conditions consisting only of the first primary key column. In the current version, and for the reasons discussed above, [ClickHouse is not moving such WHERE to a PREWHERE](https://github.com/ClickHouse/clickhouse-private/blob/v22.3.3.44-lts/src/Storages/MergeTree/MergeTreeWhereOptimizer.cpp#L196).

However, for your example - that I tried to reproduce on my own ClickHouse instance - in the current ClickHouse version `where (tags_id, created_at) in (select tags_id, max(created_at)` is automatically moved to `prewhere (tags_id, created_at) in (select tags_id, max(created_at)`:

```
CREATE TABLE benchmark_cpu
(
    `tags_id` UInt32,
    `created_at` UInt32,
    `runtime` UInt32
)
ENGINE = MergeTree()
PRIMARY KEY (tags_id, created_at);

INSERT INTO benchmark_cpu
SELECT
   rand() % 100,
   rand(),
   rand()
FROM numbers(1000000);
```

The amount of data processed without the explicit prewhere...
```
SELECT sum(cityHash64(*)) FROM benchmark_cpu where (tags_id, created_at) in (select tags_id, max(created_at) from benchmark_cpu group by tags_id);

1 rows in set. Elapsed: 0.021 sec. Processed 1.81 million rows, 17.01 MB (85.16 million rows/s., 799.68 MB/s.)
```

...is identical to the amount of data processed with the explicit prewhere
```
SELECT sum(cityHash64(*)) FROM benchmark_cpu prewhere (tags_id, created_at) in (select tags_id, max(created_at) from benchmark_cpu group by tags_id);

1 rows in set. Elapsed: 0.017 sec. Processed 1.81 million rows, 17.01 MB (106.13 million rows/s., 996.57 MB/s.)
```

And in the server log (with [trace logging enabled](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-logger)) I can see this
```
MergeTreeWhereOptimizer: condition "(tags_id, created_at) IN ((SELECT tags_id, max(created_at) FROM benchmark_cpu GROUP BY tags_id) AS _subquery34)" 
moved to PREWHERE
```

What version of ClickHouse are you running? 


--------------------------------------------
(2) your test
--------------------------------------------

I also reproduced that and think I can explain what happened:
```
CREATE TABLE test(user_id Int64, url String) Engine=MergeTree() ORDER BY user_id;

INSERT INTO test
SELECT
   1,
   randomString(10)
FROM numbers(1000);

INSERT INTO test
SELECT
   2,
   randomString(10)
FROM numbers(1000);
```

Now I check how many parts the table has:
```
SELECT count(*) FROM system.parts WHERE table = 'test' and active = 1;

┌─count()─┐
│       2 │
└─────────┘
```
Because of our two insert statements we have two parts and 

- each part contains 1000 rows
- each part has its own granules, in this case each part has one granule with 1000 rows
- each part has its own primary index

When we now execute the query 
```
select * from test where user_id = 1;
```
then only one primary index of the two primary indexes will select the granule from its part and all 1000 rows are streamed into ClickHouse
```
1000 rows in set. Elapsed: 0.008 sec. Processed 1.00 thousand rows, 27.00 KB (117.62 thousand rows/s., 3.18 MB/s.)
```

However, if we optimize the table to contain only a single part with a single granule containing 2000 rows and a single primary index...
```
OPTIMIZE TABLE test FINAL;

SELECT count(*) FROM system.parts WHERE table = 'test' and active = 1;

┌─count()─┐
│       1 │
└─────────┘
```
...and execute the query again
```
select * from test where user_id = 1;
```
Then our primary index selected the single granule with 2000 rows:
```
1000 rows in set. Elapsed: 0.009 sec. Processed 2.00 thousand rows, 54.00 KB (227.12 thousand rows/s., 6.13 MB/s.)
```

**Comment by neilxxx** [comment]
> 



> @neilxxx Sorry for the delayed response as I was a week off for Easter Holidays here in Europe.
> 
> I reply to both parts of your last question.
> 
> ## (1) Table has an index (tags_id, created_at)
> First of all, and sorry for the potential confusion, everything I discussed above, was related to conditions consisting only of the first primary key column. In the current version, and for the reasons discussed above, [ClickHouse is not moving such WHERE to a PREWHERE](https://github.com/ClickHouse/ClickHouse/blob/22.4/src/Storages/MergeTree/MergeTreeWhereOptimizer.cpp#L196).
> 
> However, for your example - that I tried to reproduce on my own ClickHouse instance - in the current ClickHouse version `where (tags_id, created_at) in (select tags_id, max(created_at)` is automatically moved to `prewhere (tags_id, created_at) in (select tags_id, max(created_at)`:
> 
> ```
> CREATE TABLE benchmark_cpu
> (
>     `tags_id` UInt32,
>     `created_at` UInt32,
>     `runtime` UInt32
> )
> ENGINE = MergeTree()
> PRIMARY KEY (tags_id, created_at);
> 
> INSERT INTO benchmark_cpu
> SELECT
>    rand() % 100,
>    rand(),
>    rand()
> FROM numbers(1000000);
> ```
> 
> The amount of data processed without the explicit prewhere...
> 
> ```
> SELECT sum(cityHash64(*)) FROM benchmark_cpu where (tags_id, created_at) in (select tags_id, max(created_at) from benchmark_cpu group by tags_id);
> 
> 1 rows in set. Elapsed: 0.021 sec. Processed 1.81 million rows, 17.01 MB (85.16 million rows/s., 799.68 MB/s.)
> ```
> 
> ...is identical to the amount of data processed with the explicit prewhere
> 
> ```
> SELECT sum(cityHash64(*)) FROM benchmark_cpu prewhere (tags_id, created_at) in (select tags_id, max(created_at) from benchmark_cpu group by tags_id);
> 
> 1 rows in set. Elapsed: 0.017 sec. Processed 1.81 million rows, 17.01 MB (106.13 million rows/s., 996.57 MB/s.)
> ```
> 
> And in the server log (with [trace logging enabled](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-logger)) I can see [this](https://github.com/ClickHouse/ClickHouse/blob/22.4/src/Storages/MergeTree/MergeTreeWhereOptimizer.cpp#L308)
> 
> ```
> MergeTreeWhereOptimizer: condition "(tags_id, created_at) IN ((SELECT tags_id, max(created_at) FROM benchmark_cpu GROUP BY tags_id) AS _subquery34)" 
> moved to PREWHERE
> ```
> 
> What version of ClickHouse are you running?
> 
> ## (2) your test
> I also reproduced that and think I can explain what happened:
> 
> ```
> CREATE TABLE test(user_id Int64, url String) Engine=MergeTree() ORDER BY user_id;
> 
> INSERT INTO test
> SELECT
>    1,
>    randomString(10)
> FROM numbers(1000);
> 
> INSERT INTO test
> SELECT
>    2,
>    randomString(10)
> FROM numbers(1000);
> ```
> 
> Now I check how many parts the table has:
> 
> ```
> SELECT count(*) FROM system.parts WHERE table = 'test' and active = 1;
> 
> ┌─count()─┐
> │       2 │
> └─────────┘
> ```
> 
> Because of our two insert statements we have two parts and
> 
> * each part contains 1000 rows
> * each part has its own granules, in this case each part has one granule with 1000 rows
> * each part has its own primary index
> 
> When we now execute the query
> 
> ```
> select * from test where user_id = 1;
> ```
> 
> then only one primary index of the two primary indexes will select the granule from its part and all 1000 rows are streamed into ClickHouse
> 
> ```
> 1000 rows in set. Elapsed: 0.008 sec. Processed 1.00 thousand rows, 27.00 KB (117.62 thousand rows/s., 3.18 MB/s.)
> ```
> 
> However, if we optimize the table to contain only a single part with a single granule containing 2000 rows and a single primary index...
> 
> ```
> OPTIMIZE TABLE test FINAL;
> 
> SELECT count(*) FROM system.parts WHERE table = 'test' and active = 1;
> 
> ┌─count()─┐
> │       1 │
> └─────────┘
> ```
> 
> ...and execute the query again
> 
> ```
> select * from test where user_id = 1;
> ```
> 
> Then our primary index selected the single granule with 2000 rows:
> 
> ```
> 1000 rows in set. Elapsed: 0.009 sec. Processed 2.00 thousand rows, 54.00 KB (227.12 thousand rows/s., 6.13 MB/s.)
> ```

@tom-clickhouse hey,tom  My English is not very good, thank you for tolerating me, I really want to understand 

my clickhouse version 22.2.2.1 

Maybe I didn't describe it very well，I tried to recount my problem

my test;

CREATE TABLE test(user_id Int64,url String) Engine=MergeTree() ORDER BY number;

user_id          url 
1                   size≈1.4MB string 
...                   .... 
1                   size≈1.4MB string  (1000)
2                   size≈1.4MB string  (1001)
...                   .... 
2                   size≈1.4MB string (2000)

index_granularity = 8192（default）;

so only one granule;

total rows = 2000 rows. 
user_id = 1 total = 1000 rows.
user_id = 2 total = 1000 rows.



OPTIMIZE TABLE test FINAL;

WHERE
selecet * from test where user_id = 1; 
1000 rows in set. Elapsed: 13.814 sec. Processed 1.00 thousand rows, 1.45 GB (72.39 rows/s., 104.90 MB/s.) 

PREWHERE
selecet * from test prewhere user_id = 1; 
1000 rows in set. Elapsed: 20.604 sec. Processed 1.00 thousand rows, 1.45 GB (48.53 rows/s., 70.33 MB/s.)

why PREWHERE does not read less data than WHERE

 only one granule, WHERE doesn't seem to be reading all of them 2000rows column url，because WHERE 1.45 GB ,PREWHERE Is also 1.45GB

Your answer earlier
If instead WHERE user = u1 would be moved to a PREWHERE user = u1 then ClickHouse would first ONLY read the user values of the selected granules, then check for which rows the user values are u1 and then read the other columns url and timestamp ONLY for blocks of rows where the PREWHERE user = u1 is true for at least some rows.

**Comment by tom-clickhouse** [comment]
@neilxxx you are welcome, it's good that you really want to understand how ClickHouse works under the hood.

In the last example WHERE and PREWHERE are reading the same amount of data because we only have one granule and in both cases data is consumed in terms of blocks of rows / granules instead of single rows:

WHERE case

- use primary index to identify the granule(s) that potentially contain rows where user_id = 1
- stream *all* entries from that granule(s) from the user_id column file and from the url column file
- output all entries for the rows (positionally aligned entries from the two column files) where actually user_id = 1

PREWHERE case

- use primary index to identify the granule(s) that potentially contain rows where user_id = 1
- stream *all* entries from that granule(s) from just the user_id column file in order to check for which specific entries user_id = 1
- if there are entries where user_id = 1 then also stream *all* entries from the same granule from the url column file
- output all entries for the rows (positionally aligned entries from the two column files) where user_id = 1

Because there is only a single granule WHERE and PREWHERE behave the same here, whereas in my earlier answer that you cited, we have more than one granule.

**Comment by neilxxx** [comment]
> @neilxxx you are welcome, it's good that you really want to understand how ClickHouse works under the hood.
> 
> In the last example WHERE and PREWHERE are reading the same amount of data because we only have one granule and in both cases data is consumed in terms of blocks of rows / granules instead of single rows:
> 
> WHERE case
> 
> * use primary index to identify the granule(s) that potentially contain rows where user_id = 1
> * stream _all_ entries from that granule(s) from the user_id column file and from the url column file
> * output all entries for the rows (positionally aligned entries from the two column files) where actually user_id = 1
> 
> PREWHERE case
> 
> * use primary index to identify the granule(s) that potentially contain rows where user_id = 1
> * stream _all_ entries from that granule(s) from just the user_id column file in order to check for which specific entries user_id = 1
> * if there are entries where user_id = 1 then also stream _all_ entries from the same granule from the url column file
> * output all entries for the rows (positionally aligned entries from the two column files) where user_id = 1
> 
> Because there is only a single granule WHERE and PREWHERE behave the same here, whereas in my earlier answer that you cited, we have more than one granule.

@tom-clickhouse Thank you very much，I sort of get it, so PREWHERE should read at least  all the rowss of one granule

**Comment by neilxxx** [comment]
> 1000 rows in set. Elapsed: 20.604 sec. Processed 1.00 thousand rows, 1.45 GB (48.53 rows/s., 70.33 MB/s.)




@tom-clickhouse hey,tom

1000 rows in set. Elapsed: 20.604 sec. Processed 1.00 thousand rows, 1.45 GB (48.53 rows/s., 70.33 MB/s.)

1.45GB  is  final output size    or    stream read size ?

Because  there are 2000 rows in the granule（about 3 GB）

Now both WHERE and PREWHERE are printed 1.45 GB， 1.45GB is not all url size（there are 2000 rows in the granule about 3GB）

**Comment by tom-clickhouse** [comment]
As I tried to explain [above](https://github.com/ClickHouse/ClickHouse/issues/36096#issuecomment-1106582518), your table most likely consists of two parts and each part has one granule with 1000 rows.

Each part has its own primary index and only one primary index selected its part's granule. The 1.45 GB is the processed / streamed data size for the streamed entries from the url and the user_id data files.

**Comment by neilxxx** [comment]
> As I tried to explain [above](https://github.com/ClickHouse/ClickHouse/issues/36096#issuecomment-1106582518), your table most likely consists of two parts and each part has one granule with 1000 rows.
> 
> You can check by yourself:
> 
> ```
> SELECT count(*) FROM system.parts WHERE table = 'test' and active = 1;
> ```
> 
> Each part has its own primary index and only one primary index selected its part's granule. The 1.45 GB is the processed / streamed data size for the streamed entries from the url and the user_id data files of the one part.

@tom-clickhouse 


SELECT count(*) FROM system.parts WHERE table = 'aaa' and active = 1;
I executed and got the results is 1

OPTIMIZE TABLE test FINAL;
I used the above statement before querying

Here are the results of each statement I execute

 select number,a from aaa ;
2080 rows in set. Elapsed: 42.376 sec. Processed 2.08 thousand rows, 3.01 GB (49.08 rows/s., 71.13 MB/s.)

select number,a from aaa WHERE number = 1;
1000 rows in set. Elapsed: 10.958 sec. Processed 1.00 thousand rows, 1.45 GB (91.26 rows/s., 132.24 MB/s.)

select number,a from aaa PREWHERE number = 1;
1000 rows in set. Elapsed: 20.502 sec. Processed 1.00 thousand rows, 1.45 GB (48.78 rows/s., 70.68 MB/s.)

select all  result  3.01 GB
WHERE number = 1 result 1.45GB
PREWHERE number =1 result  1.45GB

I wonder if I can give you my  db file,I can't find a way to upload attachments

These are my real running data，my clickhouse version 22.2.2.1


ATTACH TABLE _ UUID 'c3c090b6-55a2-4364-bbe5-d5c6af589fe0'
(
    `number` Int64,
    `a` String
)
ENGINE = MergeTree
ORDER BY number
SETTINGS index_granularity = 2000

**Comment by tom-clickhouse** [comment]
Another possibility is that [adaptive index granularity](https://clickhouse.com/docs/en/whats-new/changelog/2019/#experimental-features-1) is creating more than one granule in your case:

ClickHouse automatically assigns a group of n rows to a granule
- if either n is less than 8192 but the size of the combined row data for that n rows is larger than or equal 10 MB (the default value for [index_granularity_bytes](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/)) or
- if the combined row data size for n rows is less than 10 MB but n is 8192.

Could you please execute these two queries and post the results:
```
SELECT
    part_type,
    path,
    formatReadableQuantity(rows) AS rows,
    formatReadableSize(data_uncompressed_bytes) AS data_uncompressed_bytes,
    formatReadableSize(data_compressed_bytes) AS data_compressed_bytes,
    formatReadableSize(primary_key_bytes_in_memory) AS primary_key_bytes_in_memory,
    marks,
    formatReadableSize(bytes_on_disk) AS bytes_on_disk
FROM system.parts
WHERE (table = 'aaa') AND (active = 1)
FORMAT Vertical;
```

```
EXPLAIN indexes = 1
select number,a from aaa WHERE number = 1;
```

**Comment by neilxxx** [comment]
> 

@tom-clickhouse hi,tom  sorry for the slow reply, I always work overtime recently，here are the results

SELECT
    part_type,
    formatReadableQuantity(rows) AS rows,
    formatReadableSize(data_uncompressed_bytes) AS data_uncompressed_bytes,
    formatReadableSize(data_compressed_bytes) AS data_compressed_bytes,
    marks,
    formatReadableSize(bytes_on_disk) AS bytes_on_disk
FROM system.parts
WHERE (table = 'aaa') AND (active = 1)
FORMAT Vertical;

Query id: c31213d2-22ab-47ea-84e8-12a3bef7a481

Row 1:
──────
part_type:               Wide
rows:                    2.08 thousand
data_uncompressed_bytes: 2.81 GiB
data_compressed_bytes:   11.40 MiB
marks:                   221
bytes_on_disk:           11.41 MiB

1 rows in set. Elapsed: 0.010 sec. 




EXPLAIN indexes = 1
select number,a from aaa WHERE number = 1;

Query id: 8f7d283c-52fe-41a9-a16a-e3d3cddd97b4

┌─explain─────────────────────────────────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))                                 │
│   Filter (WHERE)                                                            │
│     SettingQuotaAndLimits (Set limits and quota after reading from storage) │
│       ReadFromMergeTree                                                     │
│       Indexes:                                                              │
│         PrimaryKey                                                          │
│           Keys:                                                             │
│             number                                                          │
│           Condition: (number in [1, 1])                                     │
│           Parts: 1/1                                                        │
│           Granules: 100/220                                                 │
└─────────────────────────────────────────────────────────────────────────────┘

11 rows in set. Elapsed: 0.026 sec.

**Comment by neilxxx** [comment]
> I try to elaborate on this a bit more, hope it helps :)
> 
> "because the table rows are sorted by the primary key column `number`, most granules selected by the primary index are completely encompassing the WHERE condition, so moving the WHERE to a PREWHERE brings no data read reduction":
> 
> * WHERE and PREWHERE both have to read/stream `all rows from all selected granules`* from the `number column file`** in order to figure out which selected granules indeed contain rows WHERE number = 1. Therfore for the `number column file` there is no data read reduction possible for WHERE vs PREWHERE
> * in the WHERE case ClickHouse also in parallel reads/streams `all rows from all selected granules` from the `a column file` and outputs the a column values for the positionally aligned number column values where number = 1
> * in the PREWHERE case ClickHouse only reads/streams `all rows from those granules` from the `a column file` where it actually found matching number column values (where number = 1) in the corresponding selected granules of the `number column file` and then outputs only the a column values for the positionally aligned number column values where number = 1
> * PREWHERE would read less (`a column file`) data than WHERE if ClickHouse would have wrongly selected some granules containing zero matching rows (WHERE number = 1). But that is highly unlikely "because the table rows are sorted by the primary key column `number`, most/all granules selected by the primary index are completely encompassing the WHERE condition, meaning that they guaranteed contain at least one matching row. There are some edge cases but they can be neglected for this discussion.
> 
> Further infos: *[granules](https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/#data-is-organized-into-granules-for-parallel-data-processing) are [selected](https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/#the-primary-index-is-used-for-selecting-granules) **[column file](https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/#data-is-stored-on-disk-ordered-by-primary-key-columns)
> 
> Maybe together with the [deep dive tutorial about granules](https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes) this makes more sense?

@tom-clickhouse Tom, thank you so much. I finally understand everything
