### ISSUE TITLE
Whether i understand  setting replication_alter_partitions_sync uncorrectly?

### ISSUE THREAD

**Issue by Yanbuc** [ClickHouse/ClickHouse#36121]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/28927682/162693560-4ca94b48-d443-4817-a6c0-b4b474093c85.png">

I think it means that query such as `alter table ... on cluster` will return result a instantly even if one node in cluster died
by settings replication_alter_partitions_sync = 0, but the result is out of my expectation.

This is my environement.
ClickHouse version: 21.4.6.55
Cluster: four nodes. Two shards and one shard has two replications.
My query sql 
```
alter table www on cluster default  DROP PARTITION tuple(toYYYYMMDD(addDays(now(),-1))) settings replication_alter_partitions_sync = 0;
```
I killed one node and execute my query.
query execute result : it blocks.
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/28927682/162694943-c6026fda-c2d6-43b1-ba69-aa63898fa090.png">
Whether i understand the param uncorrectly?
I

**Comment by genzgd** [comment]
Your query is blocking because you have run it `ON CLUSTER`.  When you run `ON CLUSTER` ClickHouse will block waiting for a response or a timeout from every node in the cluster.  That behavior is not related to `replication_alter_partitions_sync`.  Most ALTER, OPTIMIZE, and TRUNCATE queries executed on one replica will be replicated automatically using zookeeper on all other replicas in the shard.  The `replication_alter_partitions_sync` applies to this behavior.

For example if you have a cluster with 5 shards, each with 3 replicas (15 nodes total) and run `ALTER TABLE my_table UPDATE COLUMN count = count * 100 WHERE 1` on shard 1, replica 1 (without ON CLUSTER), that query will return immediately if the sync setting is 0, it will return after the `UPDATE` operation has completed only on shard 1, replica 1, and will return after the 'UPDATE` operation has completed on all three replicas of shard 1 if set to 2.

Note that when you do run `ON CLUSTER` ClickHouse will still coordinate the ALTER operation for the replicas within each shard, so each ALTER statement is still only executed once per node.

Finally the `replication_alter_partition_sync` setting is ignored for distributed tables (as in your example) since operations on distributed tables are never automatically replicated by zookeeper.
