### ISSUE TITLE
"Connection refused" issue, with clickhouse-jdbc driver

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#36331]
We used clickhouse-jdbc driver (ru.yandex.clickhouse, 0.2.4, 8123 port) to connect Clickhouse server, but we always get "Connection refused" issue. 

Then we used clickhouse-native-jdbc (com.github.housepower, 9000 port) to replace. Unfortunately, we found severl bugs in this driver. 

Is there any good soluction to avoid the issues?  Which driver should we use? Is there any configuration need to set? Thanks!

**Comment by genzgd** [comment]
Can you reach port 8123 of your ClickHouse server from the command line via curl?  Is ClickHouse configured to run via TLS?  In that case the JDBC connection string must use port 8443 and use https instead of http.

Also is there some reason you're using an old version of the JDBC driver?  The current version is 0.3.2-patch7 (and is being migrated from yandex to clickhouse.com).

**Comment by taotaizhu-pw** [comment]
> 

Yes, most of the time, our system works fine with 8123 clickhouse. Sometime, "Connection refused" issue.  What is "VIA TLS"?

Another question, 8123 is HTTP or TCP? Thanks

**Comment by genzgd** [comment]
TLS is an encrypted, secure connection.  The older name is SSL.  If you can connect otherwise on port 8123 then you are not using encryption/TLS/SSL.

8123 uses the standard HTTP protocol.  9000 uses the "Native" ClickHouse protocol (both protocols are based on TCP, so it can be less confusing to use the term Native).

If the connection to 8123 mostly works but you only occasionally get "connection refused" the problem is almost certainly not the JDBC driver.  That is an operating system/network level message that is just being forwarded by JDBC.  Are you using any kind of load balancer or proxy in front of your ClickHouse server?  Is it possible your ClickHouse server is occasionally crashing/restarting which would mean the port isn't open?  Is it possible that the hostname for the ClickHouse system somehow is pointing to the wrong server?
