### ISSUE TITLE
Question Will system stop ttl merges  stop all existing ttl  task on a table?

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#36389]
Cause the consistent ttl task has made the io rates raise largely and the disk become readonly one by one.

**Comment by mo-avatar** [comment]
After we  add ttl of all the tables on our cluster which  already has two years data, the io rate raise significantly , and it may some how triggered some bugs of the disk on our cluster, about half of over disks turn to readonly.  
what we do now is remove ttl  and restart the replica, it seems work now, but we don't know whether the io rate will raise again later.

I have find a issue which describe that modify ttl will trigger a materialize ttl alter command , which will leads to huge io.

as we can not upgrade our cluster now, I'm eager to know if the operation which we have done is sufficient to lower the io rates,  the continues broken disk is an nightmare.

ps : we are now on 21.8.5.1 lts now

Thank you guys.

**Comment by e-mars** [comment]
Hi @mo-avatar 
In your ttl is it configured to drop on a per column basis or for all columns on the table?
are the parts configured for a set timespan? e.g. so that the part would contain only that day/month, etc.? 
If so, may want to try to use `ttl_only_drop_parts` which helps lessen impact on performance so that the system is not having to rewrite parts. 
https://clickhouse.com/docs/en/operations/settings/settings/#ttl_only_drop_parts

There are improvements in TTL in 21.10 that will help with performance in materialized TTL which looks like it is the other issue that you are currently experiencing:
https://github.com/ClickHouse/ClickHouse/pull/27019
