### ISSUE TITLE
Effective range of MergeTree settings

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#36442]
What is the effective range of MergeTree settings? Is it effective for one MergeTree table or all MergeTree tables? For example, parts_to_throw_insert = 1200. Will it be triggered when the parts of one MergeTree table reach 1200, or when the parts of all MergeTree tables reach 1200? Thanks.

**Comment by genzgd** [comment]
It depends on the setting.  That particular setting applies **_per partition_**, as listed in the description, not even per table.  Other settings such as `max_parts_in_total` apply per table, and others a per server, like `max_replicated_sends_network_bandwidth` apply for all Replicated tables.

As a general rule, the default setting values have been carefully selected, and we strongly advise against changing `parts_to_throw_insert` above its default value of 300.  If you have more than 300 parts in a single partition this very often indicates a server issue that should be addressed, and otherwise is a sign that your inserts are probably too small (at least a 1000 rows is recommended).
