### ISSUE TITLE
A new option to limit total number of running threads because too many threads used for query processing could significantly decrease server’s performance

### ISSUE THREAD

**Issue by rvasin** [ClickHouse/ClickHouse#36551]
**Use case**

I had several situations when many clients connect to CH server and they send the many queries. There is max_threads parameter to manage how many threads are used to process a single query. In most cases it was possible to set small number like max_threads = 4 or 8 and to achieve a better server performance. I did many tests by using benchmark tool. In some cases I could achieve about 30% higher QPS by changing max_threads. The problem is that in real situation CH server receives in some cases complex queries requiring 70-100 threads to process each query and in other cases a client sends simple queries requiring 5-10 threads to process a query.

**Describe the solution you'd like**
The problem could be solved by having a possibility to set total number of allowed to run in process list. So we need to have a possibility to limit total number of allowed threads. I am thinking about new configuration parameter named like max_threads_for_all_queries. I am planning to implement it

**Comment by rvasin** [comment]
Finally I implemented new total_max_threads parameter to address the issue. I did several tests/benchmarks on different datasets and it looks like the parameter works fine. I created the attached article to better explain how does the parameter work and which are the benchmark results.  
Initially I called the parameter as global_max_threads. Then I had several brainstorming to choose a better name. I had the following variants for the name of parameter: max_threads_for_all_queries, max_threads_for_all_users, global_max_threads (my initial version). Finally I ended up with the name total_max_threads.  Any new variants  for better name are appreciated. 
Please read the attached article.
[article.pdf](https://github.com/ClickHouse/ClickHouse/files/8688153/article.pdf)

**Comment by rvasin** [comment]
Finally I implemented new total_max_threads parameter to address the issue. I did several tests/benchmarks on different datasets and it looks like the parameter works fine. I created the attached article to better explain how does the parameter work and which are the benchmark results.
Initially I called the parameter as global_max_threads. Then I had several brainstorming to choose a better name. I had the following variants for the name of parameter: max_threads_for_all_queries, max_threads_for_all_users, global_max_threads (my initial version). Finally I ended up with the name total_max_threads. Any new variants for better name are appreciated.
Please read the attached article.
[article.pdf](https://github.com/ClickHouse/ClickHouse/files/8688545/article.pdf)

**Comment by ilejn** [comment]
Hello @serxa @azat @alexey-milovidov ,
we (Arenadata) consider this small feature really important.
The main reason - it makes clickhouse-keeper really useful for customers because it is often still impossible to avoid using dedicated servers for clickhouse-keeper. 
Limiting the number of threads for clickhouse does help.
We've made PR https://github.com/ClickHouse/ClickHouse/pull/37285 as simple as possible to make its way to production easier, while currently it got stuck. Is it possible to assist somehow?

**Comment by serxa** [comment]
Sorry for that delay #37558 is almost ready. I switched to other tasks for some time, because this one turned out to be more complicated than I initially thought, but I'm going to return and finish it soon. Any assistance would be helpful, but the only thing left to do is just fix known bugs.

Btw, it is an interesting idea to use this feature to contain workload from clickhouse-server. It should help if you have not a lot of concurrent queries, but both implementation we have now won't completely isolate keeper, because at least one thread is provided to every query and also clickhouse-server has a lot of other threads outside pipeline executor influence.

Anyways, imho better way to isolate keeper from server in the same node would be using different cgroups for clickhouse-server and clickhouse-keeper with cpu sharing (maybe set higher share to keeper if it is important). Or if cgroups cannot be used, just decrease nice value of clickhouse-keeper process (all threads) to give it higher cpu weight.
