### ISSUE TITLE
Kafka consume performance down when table ttl is triggered?

### ISSUE THREAD

**Issue by ErikXu** [ClickHouse/ClickHouse#36727]
I am using CH as log storage and my CH version is `22.3.3.44`. Our system produces about 2 billion logs per day. Everything works well before the table ttl is triggered. When the ttl is triggered, the lag between kafka and CH consumer increases fast which causes the log record delay. Any idea of this situation? 
Below is the information:

``` sql
CREATE TABLE `logs`.`logs`
(
  _time_second_ DateTime,
  _source_ String,
  _cluster_ String,
  _log_agent_ String,
  _namespace_ String,
  _node_name_ String,
  _node_ip_ String,
  _container_name_ String,
  _pod_name_ String,
  http_traceid String,
  http_client_ip String,
  http_elapse Nullable(Float32),
  http_status Nullable(Int16),
  http_method String,
  http_origin String,
  http_domain String,
  http_path String,
  http_from String,
  http_user_agent String,
  message String
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(_time_second_)
ORDER BY _time_second_
TTL toDateTime(_time_second_) + INTERVAL 7 DAY
SETTINGS index_granularity = 8192;

CREATE TABLE `logs`.`logs_stream`
(
  _source_ String,
  _pod_name_ String,
  _namespace_ String,
  _node_name_ String,
  _container_name_ String,
  _cluster_ String,
  _log_agent_ String,
  _node_ip_ String,
  _time_ String,
  http_traceid String,
  http_client_ip String,
  http_elapse Nullable(Float32),
  http_status Nullable(Int16),
  http_method String,
  http_origin String,
  http_domain String,
  http_path String,
  http_from String,
  http_user_agent String,
  _log_ String
) ENGINE = Kafka SETTINGS kafka_broker_list ='locahost:9092', kafka_topic_list = 'eks-logs', kafka_group_name = 'clickhouse',kafka_skip_broken_messages=10000,kafka_format = 'JSONEachRow', kafka_num_consumers = 6, kafka_thread_per_consumer=10;

CREATE MATERIALIZED VIEW `logs`.`logs_view` TO `logs`.`logs` AS
SELECT
  parseDateTimeBestEffort(_time_) AS _time_second_,
  _source_,
  _cluster_,
  _log_agent_,
  _namespace_,
  _node_name_,
  _node_ip_,
  _container_name_,
  _pod_name_,
  http_traceid,
  http_client_ip,
  http_elapse,
  http_status,
  http_method,
  http_origin,
  http_domain,
  http_path,
  http_from,
  http_user_agent,
  _log_ AS message
FROM `logs`.`logs_stream`
WHERE 1=1;
```

**Comment by genzgd** [comment]
TTL operations are expensive because they require rewriting all data columns without the expired rows.  In our case I would actually recommend dropping old partitions through an automated script, since you are partition by day.  Dropping whole partitions is much more efficient that rewriting columns.

If you don't want to implement some automated script to drop partitions that are older than 7 days, you can probably get some performance improvement by enabled the setting `ttl_only_drop_parts` -- see https://clickhouse.com/docs/en/operations/settings/settings#ttl_only_drop_parts.   That will avoid rewriting data with the downside that some data that is more than 7 days old will still be accessible until all the data in the data part has been expired.  

If otherwise your merges and part fetches from other replicas are keeping up, you could consider reducing the `background_pool_size` so that fewer concurrent merges execute, but that can have other unwanted side effects and is more of last resort.

Finally the fact that you are experiencing ingest degradation when TTL merges execute suggests you are near system capacity overall, so it might be time to expand your cluster.

**Comment by ErikXu** [comment]
@genzgd Thanks for your response.
Since our partition is large, the `ALTER TABLE xxx DROP PARTITION|PART expr` command will cost so much time. 
As this command is a sync one but not a async mutation, the operation will always timeout. 
Is it better to use `ALTER TABLE xxx DELETE WHERE expr` instead?

**Comment by genzgd** [comment]
No, DELETE WHERE is similarly expensive and has to rewrite columns.  The correct solution is to drop partitions which does much, much less overall work.  The DROP PARTITION operation will not time out in ClickHouse itself or in ClickHouse client.  If you are using a different client to execute the DROP PARTITION command you should modify its timeout settings.  Note that the DROP operation should also not be executed ON CLUSTER, since it is automatically replicated by zookeeper.

**Comment by ErikXu** [comment]
Thanks @genzgd, Your advice is really helpful!
