### ISSUE TITLE
Crons on ClickHouse

### ISSUE THREAD

**Issue by stovmasyan89** [ClickHouse/ClickHouse#3685]
Or something like that..
Materialized View is triggered by inserting in parent table but sometimes I want to have tables that fill every night AS some select from another table

**Comment by alexey-milovidov** [comment]
Materialized views with scheduled refresh.

It's a good feature to implement. And it is especially useful when SELECT is performed from external data source.

We can allow to store it with arbitrary table engine in ClickHouse (with exception to Replicated tables) and refresh with atomic tables exchange.

**Comment by davidcsisk** [comment]
I would like to see a simple ALTER command to force refresh of a Materialized View (versus having to drop and re-create the Materialized View).  That ALTER...REFRESH command could then simply be cron'd.  I would vote, but I don't see a vote icon to click!

**Comment by sundy-li** [comment]
@davidcsisk 
Seems it's like a ticked `materialized view`. We used to find it's hard to calculate realtime DAU in ClickHouse with materialized view.

 
![image](https://user-images.githubusercontent.com/3325189/90844051-98b74000-e395-11ea-8e1d-06f4ca582776.png)



`DAU` (daily active users)  represents a distinct user count `at that time` (not like windows active users), yet it's not an easy way to have these metrics in ClickHouse from streaming logs.  We used airflow to schedule the `SQL` and insert the results to another table every 5 minutes.


How to handle it in ClickHouse?  Maybe something like

```sql
CREATE Materialized View  view_name(time DateTime, country String, users UInt64) Engine=xxx   cron by '*/5 * * * * *'  as select country,  '${schedule_time}'  , count(distinct user) from logs group by country
```

But there are more things to do rather than a tickerd SQL, eg:

- History States :  we should fill the history states after ClickHouse crashes
- Alter this table to rerun the SQL
- ...
