### ISSUE TITLE
Using Enum or LowCardinality(String) in JSON data type

### ISSUE THREAD

**Issue by maxpain** [ClickHouse/ClickHouse#37134]
Hello. I want to use JSON data type. My events contain fields, which could be represented as `Enum` or `LowCardinality(String)`, but ClickHouse creates a `String` column for them. Is it possible to fix this?

**Comment by UnamedRus** [comment]
> Is it possible to fix this?

It touch quite a difficult problem, make some syntax, which allow you to override some column TYPE/DEFAULT value/ CODEC for Object data type.

May be it can be implemented like table overrides https://github.com/ClickHouse/ClickHouse/issues/31480, but i can't say that syntax doesn't looks over complicated for me.

**Comment by CurtizJ** [comment]
There is a task in our roadmap #32513 to make `LowCardinality` not only a type, but also a kind of dynamic serialization (the same like it's done for `Sparse` serialization now). So, `String` columns will be encoded automatically with `LowCardinality` if they have few distinct values. It will be supported for all columns, including columns of type `JSON`.

Also there is in plans to extend set of types, recognizable by type `Object`, e.g. to extract `Enum` or `Date` from strings. 

About syntax, I think it's a good idea to implement a `SETTINGS` clause for columns, like it's suggested in #36428, especially for type `Object`, because potentially it has a lot of parameters to tune.

**Comment by kamalmarhubi** [comment]
Since the item wasn’t checked off in the 2022 roadmap, and there’s now the [2023 roadmap](https://github.com/ClickHouse/ClickHouse/issues/44767), could someone give a quick update on any plans for this? There’s an item ‘uniform treatment of LowCardinality, Sparse, and Const columns’, but I don’t know if that’s the same feature or not.

@CurtizJ perhaps?
