### ISSUE TITLE
Question about  ALTER TABLE ... MODIFY COLUMN  ...

### ISSUE THREAD

**Issue by kaynewu** [ClickHouse/ClickHouse#37179]
While I  create a  table on clickhouse 
```
CREATE  TABLE  test
(
    `name` LowCardinality(String),
    `id` String,
    `type` String,
     `version` String
)
ENGINE = MergeTree
PARTITION BY name
PRIMARY KEY id
ORDER BY id
```

now I  want to modify to column

```
ALTER TABLE  TEST MODIFY COLUMN idLowCardinality(String)
ALTER TABLE  TEST MODIFY COLUMN type LowCardinality(String)
ALTER TABLE  TEST MODIFY COLUMN version LowCardinality(String)
```
and the history data in clickhouse  will be rebuid three times, 
 How to make those three modify in one sql and only rebuild once?

**Comment by genzgd** [comment]
You should be able to execute multiple `MODIFY COLUMN` expressions in a single `ALTER TABLE` statement separated by columns:

```
ALTER TABLE TEST MODIFY COLUMN type LowCardinality(String), MODIFY COLUMN version LowCardinality(String)
```
 
Note that in your example you cannot modify the id column because it's a primary key.  Modify column types for primary keys is not permitted because it would require a rewrite/resort of the entire table.
