### ISSUE TITLE
INFILE clause doesn't resolve ~

### ISSUE THREAD

**Issue by gingerwizard** [ClickHouse/ClickHouse#37283]
**Describe the unexpected behaviour**

INFILE clause doesn't respect ~ as home dir.

**How to reproduce**

1. `mkdir ~/nyc-taxis`
2. `cd ~/nyc-taxis`
3. curl -O https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_3.gz
4. From clickhouse-client

```
clickhouse-cloud :) INSERT INTO trips FROM INFILE '~/nyc-taxis/trips_3.gz' FORMAT TSVWithNames;

INSERT INTO trips FROM INFILE '~/nyc-taxis/trips_3.gz' FORMAT TSVWithNames

Query id: 68ea7f48-3a79-4f43-9873-1e4324029c4c

Exception on client:
Code: 107. DB::Exception: File /home/ubuntu/nyc-taxis/~/nyc-taxis/trips_3.gz doesn't exist: data for INSERT was parsed from file. (FILE_DOESNT_EXIST)

```

file exists:
```
ubuntu@ip-172-31-8-70:~/nyc-taxis$ ls ~/nyc-taxis/trips_3.gz
/home/ubuntu/nyc-taxis/trips_3.gz
```

* Which ClickHouse server version to use
22.4

**Expected behavior**

Would expect it to respect and resolve path.

**Comment by alexey-milovidov** [comment]
It is not expected to work.
The `~` is expanded as home by shell interpreters, the applications don't have to do it.

We can convert it to a feature request. But it can be controversial because it's permitted to have `~` inside file names, and some disambiguation will be needed.

I prefer to not implement this feature~

**Comment by gingerwizard** [comment]
Reasonable justification, no reason to keep open unless you feel this is controversial.
