### ISSUE TITLE
Question about ALTER TABLE ADD COLUMN IF NOT EXISTS ... , modify order by () ....

### ISSUE THREAD

**Issue by PatrickUncle** [ClickHouse/ClickHouse#37310]
While i create a table on clickhouse

```
CREATE TABLE TEST
(
	ID String,
    NAME String
)
ENGINE = MergeTree
ORDER BY (ID)
```

now i want to **add column** and modify to **order by**

```
alter table TEST add column if not exists VERSION String, modify order by (ID, VERSION)

alter table TEST add column if not exists HELLO String, modify order by (ID, VERSION, HELLO)
```

ok

The table structure at this time is as follows

```
CREATE TABLE TEST
(

    ID String,

    NAME String,

    VERSION String,

    HELLO String
)
ENGINE = MergeTree
PRIMARY KEY ID
ORDER BY (ID,VERSION,HELLO)
```

but, When I execute the following statement again

`alter table TEST add column if not exists VERSION String, modify order by (ID, VERSION)`

ok

The table structure at this time is as follows

```
CREATE TABLE TEST
(

    ID String,

    NAME String,

    VERSION String,

    HELLO String
)
ENGINE = MergeTree
PRIMARY KEY ID
ORDER BY (ID,VERSION)
```

**My question is**, if the condition of **IF NOT EXISTES** is not established, will it not take effect for the following **modify order by** statement?

What should I do so that the **column exists** without modification **order by**

please help me, thanks.

**Comment by genzgd** [comment]
Multiple operations in a single `ALTER TABLE` command are normally independent, so you cannot make the second operation depend on the first.  Adding an `ORDER BY` column is a special case where the column itself must be ADDed in the same `ALTER TABLE` statement to preserve the correct sorting of both old and new data parts, but that doesn't change the general rule.

You could submit a feature request to support this use case but since modifying the sorting key is a rare operation it would probably not be a high priority for the community.

If you really must change the ORDER BY statement depending on whether the column exists, you can write a script testing for the existence of the column and then execute the ALTER TABLE statement if it does not.  A really ugly example:

```
#!/usr/bin/env bash
HAS_COL=`clickhouse-client --query="SELECT count() FROM system.columns WHERE database='default' and table='table' and name='new_col'"`
if [ $HAS_COL == '0' ]
then
  clickhouse-client --query="ALTER TABLE default.table ADD COLUMN new_col String, MODIFY ORDER BY (key, new_col)"
fi
```

**Comment by PatrickUncle** [comment]
Thanks

**Comment by den-crane** [comment]
@PatrickUncle it's normal / designed behavior. You can reduce ORDERBY by columns from the tail not included into PRIMARYKEY. It does not change ORDER of the rows in the table and does not change Index.

```
CREATE TABLE TEST(a int,b int,c int,d int,e int, f int)
ENGINE = MergeTree PRIMARY KEY (a,b)
ORDER BY (a,b,c,d,e,f);

alter table TEST  modify order by (a,b,c,d,e);

alter table TEST  modify order by (a,b);
```

**Comment by den-crane** [comment]
And `alter table` allows multiple commands.

```
alter table TEST add column z int, drop column e, modify column f String, drop partition tuple(), freeze;

Ok.

0 rows in set. Elapsed: 0.014 sec.
```
