### ISSUE TITLE
Access non-string Kafka message key

### ISSUE THREAD

**Issue by sxm51** [ClickHouse/ClickHouse#37503]
Hi,

Have a Kafka topic with key encoded (key serializer) with protobuf.
Following the [Kafka docs on virtual columns](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka/#virtual-columns), I read that we assume the keys to be serialised as a String.
Is there any way to decode the key protobuf and access the attributes.

Thanks.

**Comment by genzgd** [comment]
There are no functions in ClickHouse for decoding Protobuf values at a single value/column level.  There are input formats to deserialize structured Protobuf records into complete rows that you can use as the `kafka_format` for the Kafka messages, but there are no plans to extend that functionality to a single string.  Using the Kafka key for an entire Protobuf record seems like an unusual use case.

It might be possible to create a user defined function (maybe with a hardcoded Profotbuf schema?) to process the virtual `_key` column.  You can treat that column as a variable length byte array, since no encoding is assumes or stored with ClickHouse Strings.

**Comment by sxm51** [comment]
Thanks for that.

Looking at UDF, It can nearly support above ootb. 
Do you know if we can specify `format` as `Protobuf`. If we can, Is there a way to specify `format_schema`.
