### ISSUE TITLE
【MultiDisk related】Why clickhouse allow to config different disks with the same path? what is the purpose of such design

### ISSUE THREAD

**Issue by mo-avatar** [ClickHouse/ClickHouse#37592]
- Why clickhouse allow to config different disks with the same path? what is the purpose of such design?
-  If we miss config the disks  with same path, will it cause part corruption or moving  in replicated mergetree, or in other senario.
thanks！

**Comment by e-mars** [comment]
Hi @mo-avatar ,

Is what you're referring to the `<storage_path>` configuration and the server setting `<path>`?

For the storage path, it is meant to be used with storage policies, where you want to store certain data in "hot" and "cold" architectures:
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-multiple-volumes
and the storage policies control which disk data will be stored in or as part of migrations.

The `<path>`, however, remains the same since all node data will be kept in the path regardless of what storage policy is used..
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/

The data would not be corrupt, it would land in the disk configured per the policy and filenames would be different.

The setting is per node and on one node may have placed in different path than another but would still be accessible.

thanks.

**Comment by mo-avatar** [comment]
Alright, thanks for your help!
