### ISSUE TITLE
on a cluster with shards but without replica, mutation "alter table on CLUSTER delete..." failed

### ISSUE THREAD

**Issue by seaner90** [ClickHouse/ClickHouse#37620]
Hi,

We use clickhouse with shards, but no replica(don't want to operate another zookeeper cluster), everything is working fine, but when we trying to delete some old data by
```
alter table events on CLUSTER democluster delete where user_id='abc'
```

clickhouse return **DB::Exception: There is no Zookeeper configuration in server config**

we indeed have no zookeeper config because we don't use replica, I have to perform "alter...delete..." query on each shards, but that's not good approach I think, is there any other way to delete data on such cluster?

clickhouse version: **22.3.2.2**

cluster config:
```
<clickhouse_remote_servers>
    <democluster>
        <shard>
             <internal_replication>true</internal_replication>
             <replica>
                <host>ch1.us-west-2.com</host>
                <port>9000</port>
                <user>default</user>
                <password>superpass</password>
             </replica>
        </shard>
    </democluster>
</clickhouse_remote_servers>
```

local table
```
CREATE TABLE `events_local` (
   `event_time` DateTime('UTC'),
    `click_id` FixedString(32),
    `user_id` LowCardinality(String),
    `clicks` Int8
) ENGINE = MergeTree()
ORDER BY (`click_id`)
PARTITION BY toYYYYMM(`event_time`);
```

distributed table
```
CREATE TABLE `events` as `events_local`
ENGINE = Distributed(democluster, demodb, events_local, rand())
```

Thank you.

**Comment by genzgd** [comment]
Zookeeper is required for all ON CLUSTER DDL commands to coordinate the query.  Among other important functions, zookeeper ensures that the commands are eventually run on all nodes in the cluster, even if some of them are down/unreachable.  See https://clickhouse.com/docs/en/sql-reference/distributed-ddl

To run an ALTER or other DDL query on multiple nodes without zookeeper you would have to have some script that connects to each node independently (using clickhouse-client or some other client).

Since replication is recommended in almost all production cases with multiple nodes (for data protection and redundancy in the case of losing a node), the use case of "ON CLUSTER" without zookeeper is not likely to be supported in the near future.

**Comment by techkuz** [comment]
@genzgd take a look at clickhouse keeper, it also coordinates
