### ISSUE TITLE
startPos optional arg in position/locate functions

### ISSUE THREAD

**Issue by blinkov** [ClickHouse/ClickHouse#3776]
#3711

**Comment by Vdimir** [comment]
Is it still relevant? I think I can try to implement this feature.
Cc @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Yes, it is still relevant.

**Comment by Vdimir** [comment]
I have not enough time to work on this issue. But now I returned to this and main problem that I cannot figure out – how to pass one more argument to `PositionImpl`. It already contains four functions for constant/vector needle and constant/vector haystack. If I decide to add parameter it shouldn't be concrete constant or vector, because it produces a lot of variants. It should be abstract and function may handles both(constant/vector) cases. But I cannot decide what concrete thing to pass. Also this parameter would be added to all `*Impl` used in searchers. Maybe issue requires slightly deeper refactor to perserve other implementation clean and handle startPos in `PositionImpl`.
Can you give some hint how better implement this feature?

**Comment by alexey-milovidov** [comment]
You can pass it as abstract (IColumn) argument and extract the position with `IColumn::getUInt64` virtual function.
(no need to dispatch over column types manually)

**Comment by vdimir** [comment]
> You can pass it as abstract (IColumn) argument and extract the position with `IColumn::getUInt64` virtual function.
> (no need to dispatch over column types manually)

Thanks, it really helps me!
