### ISSUE TITLE
How can i close the maybe useless connections?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#37798]
As you can see, there are more than 1500 connections.
![image](https://user-images.githubusercontent.com/22699037/171652340-03698e7b-8aba-4456-a761-c9cb023d0d64.png)

I used to use Python [clickhouse-drive](https://github.com/mymarilyn/clickhouse-driver) to establish a lot of connections. When I Ctrl+C stopped the script and it had been 6 hours, the indicator still showed a lot of connections.

How can i close the maybe useless connections manually? Or are there any other ways to avoid this excessive idle connection? Can [this](https://github.com/ClickHouse/ClickHouse/pull/6230) help?

The version is 22.4.4.7.

Thanks.

**Comment by genzgd** [comment]
The clickhouse-driver will normally close the connection on exit.  Does the operating system still show open connections?  What state are they in (CLOSE_WAIT or ESTABLISHED?). How long do the connections stay open?

**Comment by LGDHuaOPER** [comment]
Let me repeat that the pod I run through k8s still behaves the same after 'kubectl delete' as after Ctrl + C manually.


> The clickhouse-driver will normally close the connection on exit.

I see https://github.com/mymarilyn/clickhouse-driver/blob/master/clickhouse_driver/client.py#L176. Yeah, it did handle Exception and KeyboardInterrupt, but why a lot of connections after Ctrl + C manually? And I see https://docs.python.org/3.7/library/exceptions.html#exception-hierarchy. Whether I run through the k8s pod, use the command 'kubectl delete' to delete the pod, it won't trigger KeyboardInterrupt exception, but trigger the SystemExit exception?


> Does the operating system still show open connections?

Yes，I still query a lot of connections through the following statements. At this time, it has passed 3 to 4 days.
```
SELECT * FROM system.metrics WHERE metric LIKE '%Connection'
```
![image](https://user-images.githubusercontent.com/22699037/172119195-7c1bf6ac-8d7a-43d4-8e47-035f92c47ce2.png)


> What state are they in (CLOSE_WAIT or ESTABLISHED?).

I'm not sure about this. Can you give me some advice.


> How long do the connections stay open?

Three to four days have passed, and there are still 1300 TCP connections in system.metrics table.


Thanks!

**Comment by genzgd** [comment]
`system.metrics` is the ClickHouse table, not the operating system.  It is the ClickHouse count of what is open, which may not have been updated correctly.  You need to determine if there is a bug in ClickHouse reporting the number of TCPConnections or if there are actual connections showing on the Kubernetes pod or Kubernetes host.

Since you have deleted the pod where the connections came from, even if there are actual TCPConnections on the ClickHouse pod they cannot be "open", and could be in a `CLOSE_WAIT` state.  If you have that many connections in a stuck `CLOSE_WAIT` state the  is the case the problem might be with the Kubernetes cluster or networking and not with ClickHouse or the Python driver.

**Comment by LGDHuaOPER** [comment]
I think I understand what you mean.I found these CLOSE_WAIT state connections using netstat. Thank you again.

**Comment by Enoq00** [comment]
Same issue for me. as there any solution?

**Comment by LGDHuaOPER** [comment]
> Same issue for me. as there any solution?

decrease `idle_connection_timeout`
