### ISSUE TITLE
the distributed table retries the statement that failed to write indefinitely

### ISSUE THREAD

**Issue by sunny19930321** [ClickHouse/ClickHouse#37938]
> 
When changing the table structure of a local table, write failures and infinite retries occur before the distributed table has finished forwarding data

> 
1、changed the local table structure
![image](https://user-images.githubusercontent.com/20608540/172757830-ff6fbc6f-b8b1-42ab-b5cb-1a384ffdbc45.png)

2、the distributed table retries the logs written
![image](https://user-images.githubusercontent.com/20608540/172757828-d6d544e5-5620-466f-a7ab-75259f2b7bf8.png)

3、code logic
![image](https://user-images.githubusercontent.com/20608540/172757829-cb388275-ad61-4e58-9ed5-679cbcdb0c97.png)

**Comment by genzgd** [comment]
Is this a feature request?  What would you expect to happen?

The core responsibility of the distributed table is to ensure that data is not lost and writes should be retried in case of temporary failures like network, etc.  What criteria would you add to fail the insert and how would clients handle that failure?

A simple solution to this problem is to monitor logs and ensure that changes between a distributed and source table are synchronized.

**Comment by sunny19930321** [comment]
local table has changed the table structure，distributed tables are difficult to keep consistent with local tables, so need to mark this exception(NO_SUCH_COLUMN_IN_TABLE) broken.

**Comment by sunny19930321** [comment]
local table has changed the table structure，distributed tables are difficult to keep consistent with local tables, so need to mark this exception(NO_SUCH_COLUMN_IN_TABLE) broken.

    bool isFileBrokenErrorCode(int code, bool remote_error)
    {
        return code == ErrorCodes::CHECKSUM_DOESNT_MATCH
            || code == ErrorCodes::EMPTY_DATA_PASSED
            || code == ErrorCodes::TOO_LARGE_SIZE_COMPRESSED
            || code == ErrorCodes::CANNOT_READ_ALL_DATA
            || code == ErrorCodes::UNKNOWN_CODEC
            || code == ErrorCodes::CANNOT_DECOMPRESS
            || code == ErrorCodes::DISTRIBUTED_BROKEN_BATCH_INFO
            || code == ErrorCodes::DISTRIBUTED_BROKEN_BATCH_FILES
            **|| code == ErrorCodes::NO_SUCH_COLUMN_IN_TABLE**
            || (!remote_error && code == ErrorCodes::ATTEMPT_TO_READ_AFTER_EOF);
    }

**Comment by genzgd** [comment]
You can submit a pull request to let the ClickHouse engineering team evaluate whether this correct behavior.

However, since all of those errors are irrecoverable by the user and an inconsistent local table is not.  In particular, in the case where the distributed table has been updated and the local table has but is about to be, your proposed change may result in unnecessary data loss.
