### ISSUE TITLE
Proper deduplication of async inserts.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38075]
**Use case**

Async inserts should optionally support per-INSERT deduplication similar to usual inserts.

**Describe the solution you'd like**

Async inserts are concatenated into a single block before insertion. Add BlockInfo containing the offsets of the source inserts in the resulting block. `ReplicatedMergeTreeSink` will calculate multiple hashes (one per source insert), check all of them against deduplication data in Keeper, and filter out the duplicates.

A setting should exist to enable or disable this behavior as deduplication can be heavy for a high number of small inserts.

**Caveats**

The problem is that the hash is normally calculated from the serialized data part.
Here we are trying to calculate a hash from a range in a block. It will be different.
Should we always calculate it this way if async insert is enabled? Can it introduce some overhead?

**Additional context**

The lack of this feature is the only reason async_insert is not enabled by default.

**Comment by hanfei1991** [comment]
After discussion, our initial solution is to record multiple checksums in zookeeper for a part serving `aysnc inserts`. This solution is straitfoward and not hard to implement.

One problem is, when we are trying to apply transactions for multiple checksums, we are more likely to meet conflicts and retry multiple times because zookeeper return only one conflict in one rpc. The optimization is to cache the block_id paths and pre-check conflicts.

I would retry to implement a simple version without the pre-check optimization. This will be two PRs and easier to review.

**Comment by hanfei1991** [comment]
Update: a basic and correct version is merged. Next step is going to support a cache of keeper path to filter as many duplicate block ids as possible. We can turn on async_insert after then.

**Comment by dozer111** [comment]
hi I have this problem:

i write data to db using async insert and try to deduplicate with ReplacingMergeTree and `insert_deduplication_token` on each asyncInsert query

do u plan to fix it?

**Comment by sfrk** [comment]
> The lack of this feature is the only reason async_insert is not enabled by default.

Will `async_insert = 1` become the default now that https://github.com/ClickHouse/ClickHouse/pull/89140 has been merged? From that PR:

> Async insert deduplication now works with dependent materialized views.
