### ISSUE TITLE
too many datafiles in system.distribution_queue table

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ClickHouse#38254]
There are more than 750 K datafiles in my distributed table!
`
SELECT error_count,data_files, table FROM system.distribution_queue  FORMAT Vertical;
`
![截屏2022-06-21 下午2 10 51](https://user-images.githubusercontent.com/52686065/174728519-33a2d3de-ca4a-42bf-820e-7ea822f80773.png)

It seems like the distributed table send speed is slower than consume speed.
my background_distributed_schedule_pool_size is 16.
I write about 100mb/s data into distributed table, per insert contain about 50mb data.

 what should i do to solve this problem?

**Comment by genzgd** [comment]
If you think that consumption speed is slower than your distributed table insert/send speed you should make sure the nodes in your cluster have sufficient resources.  100mbs may be too fast for your network, or too fast for the disk/CPU/memory on the target nodes.  You could also consider inserting directly into your source tables on each server rather than incurring the extra network and disk storage of inserting into a distributed table.

If you believe this is a ClickHouse issue and not a cluster resources/operations issue please check the logs and report any errors/warnings.
