### ISSUE TITLE
Only in `Openshift`: DB::Exception: Group {} is not found in the system

### ISSUE THREAD

**Issue by xRomZak** [ClickHouse/ClickHouse#38583]
Unclear error after version upgrade

```
Code: 36. DB::Exception: Group {} is not found in the system. (BAD_ARGUMENTS) (version 22.6.2.12 (official build))
  | ClickHouse init process failed.
```

**Comment by xRomZak** [comment]
Nothing special. OpenShift, StatefulSet, 1 Pod (default ClickHouse image). 
Just upgrading ClickHouse 22.4.5.9 defined in StatefulSet => ... (same issue with 22.5.xx)

**Comment by filimonov** [comment]
it is an issue with `clickhouse su` tool.

It happens on those lines: 

https://github.com/ClickHouse/ClickHouse/blob/be213c0be70bc53a5e04a0de87ef02f259a4640c/docker/server/entrypoint.sh#L98-L106

Most probably because `clickhouse` group does not exists (somehow) in the container.

**Comment by bkuschel** [comment]
The problem is on openshift the clickhouse process owner is the root group.
The `getgrnam_r` functions if you pass a group called "0" as the name argument. 
This can be avoided if the entry point script uses `id -gn` rather than id -g in the case the user is non-root.

This should probably be reworked though, it doesn't make sense that `clickhouse su clickhouse:root` succeeds where `clickhouse su clickhouse:0` fails

**Comment by rumeshmadhusanka** [comment]
Is there a workaround for this issue?

**Comment by anvaari** [comment]
still same issue with open shift and 23.4.2.11.

**Comment by anvaari** [comment]
[This workaround](https://github.com/ClickHouse/ClickHouse/issues/42400#issuecomment-1510461662) fix the issue for me.
