### ISSUE TITLE
Prevent user to run a function

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#38624]
Is Clickhouse have any way to prevent user to run certain functions (UDF for example)? 
When i create new user, he can run any function

**Comment by surbhiarorasehgal** [comment]
Hello

In order to modify the user permissions you could check the documentation here https://clickhouse.com/docs/en/sql-reference/statements/create/role/.

The user can have specific roles defined. Like in the example you referred, In order to stop the user from creating UDF functions you should not give the user INSERT permission since to create a function, you must have the INSERT privilege.

Let me know if this works for you.

Surbhi

**Comment by lesandie** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/40982

**Comment by alexey-milovidov** [comment]
Currently, no. We don't have per-function grants.
We are going to introduce grants for table engines first: #56945
