### ISSUE TITLE
Search function that ignore special characters 

### ISSUE THREAD

**Issue by alexon1234** [ClickHouse/ClickHouse#38825]
**Use case**

Sometimes you want to be able to search for a text, but you don't care if the text contains special characters (á, Ú, ... )

**Describe the solution you'd like**

It would be really nice to have a function or a parameter to the existing functions to be able to ignore these characters

**Describe alternatives you've considered**

The only alternative I found it to do 

```
SELECT arrayMap(x -> arrayStringConcat(arrayMap(y -> if((indexOf(['Á', 'á', 'é', 'í', 'ó', 'ú'], y) AS i) = 0, y, ['a', 'a', 'e', 'i', 'o', 'u'][i]), extractAll(x, '.'))), ['camión', 'elástico', 'Árbol']) AS r

Query id: 8a9f6514-ea27-4cde-92ed-21d5fad66a95

┌─r─────────────────────────────┐
│ ['camion','elastico','arbol'] │
└───────────────────────────────┘
```

Following [this](https://stackoverflow.com/questions/69150435/how-replace-each-accented-characters-with-non-accented-characters-foreach-word-i) answer in StackOverflow

**Comment by alexey-milovidov** [comment]
We need a function for the removal of diacritics or combining characters.
IIRC this is nontrivial as there are different kinds of combining characters (in addition to Latin diacritic marks).
Maybe we need a function for the removal of code points with certain Unicode properties.

**Comment by alexey-milovidov** [comment]
@den-crane The answer on Stackoverflow is not correct.

**Comment by rschu1ze** [comment]
"Special characters" is not a concept known to Unicode. @alexon1234's original question refers to "special characters" in a more narrow sense as combining characters / diacritical marks in Latin writing.

> ```
> SELECT replaceRegexpAll(normalizeUTF8NFKD('Hôtel Genève'), '\pM', '')
> 
> Hotel Geneve
> ```

[Further explanation](https://en.wikipedia.org/wiki/Combining_character) of a "mark" aka. `\pM'. Also some explanation of [Unicode code point categories](https://en.wikipedia.org/wiki/Unicode_character_property#General_Category). And for reference, the [re2 syntax](https://github.com/google/re2/wiki/Syntax).

I think the key is to find replacements for every "special characters", otherwise we loose semantics. We basically want  "Hotel Geneve", and not "Htel Genve". Here, this is achieved using the NFKD normalization + mark removal trick. 

But this is just simplest case. Not everything which one may consider as special character has a natural replacement. E.g. within the symbol character class ("S"), simple emoji faces may have a replacement (😀 --> :-) ) but the dustbin emoji ♻ has not.
I am also not sure what a "special character" means in other writing systems. E.g. in Cyrillic writing, if "ѣ" is considered a "special character, can it [always be replaced by "е"](https://en.wikipedia.org/wiki/Reforms_of_Russian_orthography#The_post-revolution_reform)? (and "ѣ" is a normal letter, not a "diacritic symbol", so the trick wouldn't work anyways). Not to speak about CJK or the many other writing systems. 

It seems to me that the original requirement is fairly simple (and has a simple solution given by Alexey) but a general solution will be complex because of Unicodes complexity. Well, we could offer a function that removes just diacritics but internally it will also do normalization with the unwanted effect of also rewriting non-diacritic symbols, e.g. ½ --> 1/2 or ℤ --> Z (in case of NFKD). To be honest, a new function would look equally complex in terms of parameters than the `regexReplaceAll` call, so we might as well recommend regexReplaceAll.

**Comment by alexon1234** [comment]
Thanks for all the suggestions and help :heart:

**Comment by xoelop** [comment]
Seems like in `26.3`, a new [removeDiacriticsUTF8](https://clickhouse.com/docs/sql-reference/functions/string-functions#removeDiacriticsUTF8) function was introduced, and it does this exact thing :D

```sql
SELECT removeDiacriticsUTF8('café résumé naïve')

┌─removeDiacriticsUTF8('café résumé naïve')─┐
│ cafe resume naive                          │
└────────────────────────────────────────────┘
```
