### ISSUE TITLE
Unicode character class matching with regexp works in a strange way.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#38835]
When I ask to extract uppercase characters, it's extracting everything except uppercase (lowercase and combining), and when I ask to extract lowercase it's extracting everything but lowercase (uppercase and combining).

```
play-eu :) SELECT extractAll('Привёт', '\P{Ll}')

SELECT extractAll('Привёт', '\\P{Ll}')

Query id: f492b7d1-333a-46fc-a83e-e0479d6fcaa3

┌─extractAll('Привёт', '\\P{Ll}')─┐
│ ['П','̈']                        │
└─────────────────────────────────┘

1 row in set. Elapsed: 0.003 sec. 

play-eu :) SELECT extractAll('Привёт', '\P{Lu}')

SELECT extractAll('Привёт', '\\P{Lu}')

Query id: 5c298d96-9a8d-4c26-b7b7-e24f252eb558

┌─extractAll('Привёт', '\\P{Lu}')─┐
│ ['р','и','в','е','̈','т']        │
└─────────────────────────────────┘

1 row in set. Elapsed: 0.003 sec.
```

**Comment by evillique** [comment]
According to the re2 [docs](https://github.com/google/re2/wiki/Syntax) while `\p` means a certain class of Unicode characters, `\P` mean negation of the character class:

kinds of single-character expressions | examples
-- | --
Unicode character class | \p{Greek}
negated Unicode character class | \P{Greek}

`extractAll` function in ClickHouse seems to work according to this standard:
```
SELECT extractAll('Привёт', '\\P{Ll}')

┌─extractAll('Привёт', '\\P{Ll}')─┐
│ ['П','̈']                        │
└─────────────────────────────────┘

SELECT extractAll('Привёт', '\\p{Ll}')

┌─extractAll('Привёт', '\\p{Ll}')─┐
│ ['р','и','в','е','т']           │
└─────────────────────────────────┘
```
Because of this reason exactly we also parse the U+0308 Combining Diaeresis character in both of the original examples, since it does not belong to the lowercase or the uppercase character class.
