### ISSUE TITLE
Dedicated support for Base64URL encoding

### ISSUE THREAD

**Issue by marcioapm** [ClickHouse/ClickHouse#38832]
**Use case**
Clickhouse is missing the common Base64URL encoding/decoding. 
Having a dedicated function for this would be much faster.

**Describe the solution you'd like**
Have implementations of `Base64UrlDecode()`/`Base64UrlEncode()` and `FROM_BASE64URL()`/`TO_BASE64URL()`

**Describe alternatives you've considered**
Current alternative is to replace `+` and `/` for `-` and `_` before/after decode/encode.

**Comment by evillique** [comment]
As a temporary solution `translate` function introduced in #38935 can be used:

``` translate(s, '+/', '-_')```

**Comment by mgorshkov** [comment]
Some research on Base64URL support.
Base64URL, as specified in "RFC 4648 - The Base16, Base32, and Base64 Data Encodings" at https://tools.ietf.org/html/rfc4648, is as variation of the standard Base64 encoding specified in "RFC 1521 - MIME (Multipurpose Internet Mail Extensions) Part One: Mechanisms for Specifying and Describing the Format of Internet Message Bodies" at https://tools.ietf.org/html/rfc1521.
In RFC 4648, 2 modifications on Base64 encoding are suggested to define Base64URL encoding:
* “+” in the encoding map is replaced with “-”, since "+" in URL represents a space character " ".
* “/” in the encoding map is replaced with “_”, since "/" in URL represents the directory separator.

ClickHouse features base64Encode (alias: TO_BASE64)/base64Decode (alias: FROM_BASE64)/tryBase64Decode functions, but without URL replacement pre/postprocessing support.
Libraries to consider:

1. [Aklomp-base64](https://github.com/aklomp/base64) (SSSE3/SSE4.1/SSE4.2/AVX2/NEON/AVX512 SIMD optimizations) - this library is currently used in base64Encode/decode CH implementation, but it does not support RFC 4648. ClickHouse switched to aklomp-base64 from Turbo-Base64 in PR https://github.com/ClickHouse/ClickHouse/issues/31643. The reason is: "Replaced the library to handle (encode/decode) base64 values from Turbo-Base64 to aklomp-base64. Both are SIMD-accelerated on x86 and ARM but 1. the license of the latter (BSD-2) is more favorable for ClickHouse, Turbo64 switched in the meantime to GPL-3, 2. with more GitHub stars, aklomp-base64 seems more future-proof, 3. aklomp-base64 has a slightly nicer API (which is arguably subjective), and 4. aklomp-base64 does not require us to hack around bugs (like non-threadsafe initialization). Note: aklomp-base64 rejects unpadded base64 values whereas Turbo-Base64 decodes them on a best-effort basis. RFC-4648 leaves it open whether padding is mandatory or not, but depending on the context this may be a behavioral change to be aware of."
2. Poco::Base64Encoder - supports URL encoding/decoding - this library is not SIMD-optimized, but supports RFC 4648 (by using another replacement table, and no line breaks in output stream for URLs)

Solutions proposed:
1. Switching to Poco::Base64Encoder/Decoder (it lacks hand-written SIMD optimizations, but who benchmarked compiler-generated optimizations there?)
2. Look for some other 3-rd party library that supports Base64URL and SIMD (it is quite expensive and may have a lot of issues such as performance, licensing and compatibility issues).
3. Stay with aklomp library and do pre/post-processing URLs before/after submitting them to aklomp separately (it will require double string processing, but is a good compromise).
4. Submit a PR into aklomp library with RFC 4648 support (there is an issue on Base64url there: https://github.com/aklomp/base64/issues/66). Technically, it is possible to change translation table (see author’s comment below).
5. Same, but patch aklomp library and create a fork in https://github.com/ClickHouse

The aklomp library author says:
“Hi! Currently this library only supports the [standard](https://github.com/aklomp/base64/blob/master/lib/tables/tables.c#L5) Base64 alphabet.
It would probably be feasible, but difficult, to add support for additional alphabets. It could be non-trivial to add that support to the SIMD codecs, because they do arithmetic on the raw character values. Here's [an encoder example](https://github.com/aklomp/base64/blob/master/lib/arch/ssse3/enc_translate.c) and here's [a decoder](https://github.com/aklomp/base64/blob/master/lib/arch/ssse3/dec_loop.c).
My intuition is that it would probably be possible to find an arithmetic-based solution that works with the alternative alphabet since the differences are small. However, it would require duplicating a lot of code, and adding some sort of user-visible flag to the API to indicate which alphabet to use. Maybe it could be a compile-time flag to not incur runtime penalties or complexities.” (https://github.com/aklomp/base64/issues/66#issuecomment-594227849)

Currently, solution 3 seems most viable to me, since URL string are comparatively small and there will be no performance impact compared to the workaround proposed in the issue.

Test: [tests/queries/0_stateless/00732_base64_functions.sql]

@marcioapm @Algunenano pls comment on this what do you think?

**Comment by mgorshkov** [comment]
@rschu1ze Maybe you look at this as well?
If there is no objections, I'll implement option 3: URLs pre/post-processing before/after encode/decode.

**Comment by rschu1ze** [comment]
@mgorshkov Thanks for looking into this.

Thoughts:
- Poco is a jack-of-all-trades, and we should not use it more than necessary. ClickHouse's current fork (actually code dump) lags behind upstream, poco is not very popular these days (people usually prefer Boost), and it lacks a SIMD implementation. Let's not go this route.
- As you noticed we switched to aklomp-base64 from Turbo-Base64. Indeed, aklomp-base64 is actually quite nice (in terms of speed and license) but it obviously does not support base64url.
- Regarding your proposals 1-5: The "right" and "open-source" way to build this feature are 4. and 5. Basically, make a PR which extends the 3rd-party library with base64url support, then either update ClickHouse's submodule to include the upstream patch or if that takes too long or is otherwise not possible, we can fork aklomp0-base64 in the ClickHouse organization (happens all the time, see https://github.com/ClickHouse/) and include the patch over there.

But I'd also totally fine with option 3.

As far as I understand, we not only need to replace `+` and `/`, we also need to make sure there is no padding with `=`. Padding in the base64 standard is optional, so we either might want to force the aklomp library to omit padding or remove the padding in a postprocessing step.
