### ISSUE TITLE
Getting current value of max_concurrent_queries

### ISSUE THREAD

**Issue by ryanrolds** [ClickHouse/ClickHouse#38870]
I believe I've made the appropriate XML file change to increase `max_concurrent_queries` and deployed it, I'm trying to confirm the value change was applied correctly without having to write something that makes 101 concurrent queries. Ideally, I would be able to query the value in `system.settings`.

**Comment by genzgd** [comment]
`max_concurrent_queries` is specifically for MergeTree queries.  Its value is accordingly available in the `system.merge_tree_settings` table.  Depending on your use case you may want to modify `max_concurrent_queries_for_user` and `max_concurrent_queries_per_user` as well as or instead of the `max_current_queries` MergeTree setting.

**Comment by ryanrolds** [comment]
I'm looking at `system.merge_tree_settings` and it has 0 for `max_concurrent_queries`. It's not disabled. We are getting an error about hitting the max.

**Comment by ryanrolds** [comment]
Also, the docs at https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#max-concurrent-queries have no mention of it being related to that value. It looks like it's config.xml value.

**Comment by ryanrolds** [comment]
The description of that setting is: `Max number of concurrently executed queries related to the MergeTree table (0 - disabled). Queries will still be limited by other max_concurrent_queries settings.` It looks like there are two layers of limits here.

**Comment by ryanrolds** [comment]
`Too many simultaneous queries. Maximum: 100`

**Comment by genzgd** [comment]
Yes, there are two layers of limits.  What are the values of the other settings?  `max_concurrent_queries_for_user` and `max_concurrent_queries_for_all_users`?

**Comment by ryanrolds** [comment]
Both 0 in system.settings.

**Comment by ryanrolds** [comment]
Is it normal practice to close issues before they are confirmed resolved?

**Comment by genzgd** [comment]
You asked how to get the setting, not how to fix your issue :)

**Comment by ryanrolds** [comment]
Sometimes people ask questions as a way to demonstrate a problem (Socratic method). Hopefully, we understand the problem now and that this setting should be available via `system.settings` or `SHOW max_concurrent_queries`.

**Comment by genzgd** [comment]
I don't know the historical reason why merge_tree_settings are separate, and I agree it's confusing.  Feel free to open a feature request if there is not one already.  I would also suggest that if you have an error that you are attempting to fix, include it in the issue.

In any case, It is possible that you are in fact inserting into too many partitions at once.  The relevant setting is `max_partitions_per_insert_block` which defaults to 100.  What is the partition key of the table you are inserting into?  Is the data you are inserting in a single block likely to be stored on many partitions?  In general data should be inserted so that it goes to only a handful of data partitions.

**Comment by ryanrolds** [comment]
We were getting the error when doing SELECTs, not INSERTs. I wouldn't expect it to be an error related to INSERTs.

**Comment by ryanrolds** [comment]
Ok, that is an interesting point. If we are doing a lot of inserts in another process(s) would that cause a problem for reads that are using those parts?

**Comment by ryanrolds** [comment]
```
PARTITION BY toYYYYMM(timestamp)
ORDER BY (metric_id, date, timestamp)`
```

**Comment by genzgd** [comment]
Is it possible you are inserting data from more than 100 months at once?  I'm not sure how that value interacts with SELECTs but given that all the other limits are "unlimited" I don't know of another reason you'd get that error with 100 as the stated limit.

**Comment by ryanrolds** [comment]
Nope, only data from the last few days.

**Comment by den-crane** [comment]
There is global setting `max_concurrent_queries` 
it impacts any queries `clickhouse-benchmark -c 400 <<< 'select 1'`

A year ago Amos added "Per MergeTree table query limit"  https://github.com/ClickHouse/ClickHouse/pull/19544

It's not related to `max_partitions_per_insert_block`

**Comment by genzgd** [comment]
Yes, Denny is correct, I was mistaken.  The global setting defaults to 100 and is not correctly displayed in system.settings.

**Comment by genzgd** [comment]
After discussion with the devs, the `max_concurrent_queries` configuration value is not visible in system.settings because it is global and unmodifiable by the user at a profile or query level (similar to various other config.xml settings such as `listen_host` or `http_port`).  It's confusing because it's mentioned in the docs in connection with other profile/user level settings.

At some point we hope to make all configuration setting available within ClickHouse (for a user with appropriate permissions).

**Comment by ryanrolds** [comment]
The issue is that when packaging up ClickHouse and deploying it there are plenty of opportunities to get something wrong and the value not applied. It would be very helpful to be able to validate that ClickHouse did consume the new value set its max_concurrent_queries to the new value. Without being able to interrogate settings like this one, it's hard for people maintaining a ClickHouse cluster to move quickly and confidently. This is really a developer or operations experience problem and it's sad that the ClickHouse developers do not appear to care about the user experience.

**Comment by HwiLu** [comment]
> After discussion with the devs, the `max_concurrent_queries` configuration value is not visible in system.settings because it is global and unmodifiable by the user at a profile or query level (similar to various other config.xml settings such as `listen_host` or `http_port`). It's confusing because it's mentioned in the docs in connection with other profile/user level settings.
> 
> At some point we hope to make all configuration setting available within ClickHouse (for a user with appropriate permissions).

Hi,Are you sure `max_concurrent_queries` cannot by modified, why someone modified it successfully https://github.com/ClickHouse/ClickHouse/issues/21567

**Comment by genzgd** [comment]
In that issue it was modified by changing the config.xml.  It was still not visible as a profile or user setting, and could not be modified by a SET statement.

**Comment by HwiLu** [comment]
so then it can be modified by configuration files, but not by SET statement
