### ISSUE TITLE
performance of Inserting to sparse wide table is bad

### ISSUE THREAD

**Issue by yuzhichang** [ClickHouse/ClickHouse#38878]
I have a table of 1K sparse Nullable(String) columns, all are dynamically added after the `__name__` column .

```
CREATE TABLE prom_extend ON CLUSTER abc (
    timestamp DateTime,
    value Float64,
    __name__ String
) ENGINE=ReplicatedMergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (__name__, timestamp);


CREATE TABLE dist_prom_extend ON CLUSTER abc AS prom_extend ENGINE = Distributed(abc, default, prom_extend);
```

[clickhouse_sinker](https://github.com/housepower/clickhouse_sinker) (based on `clickhouse/clickhouse-go/v2`) writes batches (each consists of ~130K rows) to a cluster(2 physical nodes, one shard, two replicas). 

Every row contains only random 10 among the 1K Nullable(String) columns. And each value contains 5~10 characters.

Inserting to such table is very slow. From `query_log`, each `INSERT` of a batch costs ~13s.
`SETTINGS min_bytes_for_wide_part=209715200;` (each compact part is 33.4MB on disk) make things worse, each `INSERT` cost ~18.9s.

clickhouse-server processes each `INSERT` in one thread. From the `top`, it occupies ~100% of a vCPU. So it's obviously CPU bottle-neck.
Here's the `perf record` of several seconds of the clickhouse-server process.

![Screenshot_2022-07-06_10-33-06](https://user-images.githubusercontent.com/153784/177458308-07ca2148-30e2-4ca1-bfaf-df00bc4f30fd.png)

**Comment by genzgd** [comment]
First, Nullable columns are always slower than non-Nullable columns, as a separate Null dictionary/index has to be written for each column, so that doubles the number of writes for each insert.  In addition you could reduce your batch size and increase the number inserts to use more than one thread.  Also if you are not doing so already, inserting into the shards directly instead of the distributed table would improve performance.

That said, having 1k columns that each must be sorted and written is going to be "slow" with only a single VCPU.  I don't know that there is much more you can do with that somewhat artificial schema.  Is there some performance improvement that you are proposing?  What would you have ClickHouse do differently?

**Comment by yuzhichang** [comment]
`Nullable(String)` is used since I need to distinguish `NULL` and zero-length.
Reducing the batch size doesn't help to the throughput per insert thread. 
I'm using sync insertion. Using more than one insert thread requires multiple DB connections at the client side.
I'm already inserting into local table instead of distributed table.

**Comment by genzgd** [comment]
There's only so much that ClickHouse can do in a single thread under those conditions.  Feel free to suggest an improvement or submit an appropriate pull request.

**Comment by yuzhichang** [comment]
Inserting into `JSON` with 1K sparse subcolumns is even slower.

```
CREATE TABLE default.prom_extend_json ON CLUSTER abc (
    `timestamp` DateTime,
    `value` Float64,
    `__name__` String,
    `labels` JSON
) ENGINE=MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (__name__, timestamp);

CREATE TABLE default.dist_prom_extend_json ON CLUSTER abc AS prom_extend_json ENGINE = Distributed(abc, default, prom_extend_json);
```

Inserting a batch with 1024 records costs 4.343 seconds on average.

**Comment by den-crane** [comment]
I would use 50 columns `Array(String)`
