### ISSUE TITLE
2/3 questions about CollapsingMergeTree

### ISSUE THREAD

**Issue by MockingMagician** [ClickHouse/ClickHouse#39111]
Hi clickhouse team !

I have 2/3 question about CollapsingMergeTree engine : 

When I test this engine with the insertion of two 1 signs it results in only one line with the values of the second one, is this the expected behavior, and can the engine be used this way without going through a -1 sign followed by a 1 sign?

In the example where a -1 sign is sent followed by a 1 sign, examples are given for number fields with the use of sum * sign to obtain the concrete state of the selection. What about text or other fields?
Also, in the case of a large amount of data being sent, could you explain how this amounts to storing less data and how summing fields can be faster than reading an updated value?

In the documentation you mention: It must copy the key sort fields of the cancelled report except for Sign. 
Do you confirm that it is just necessary to transmit the value of these fields when sending the -1 sign?

Kind regards

**Comment by tom-clickhouse** [comment]
## Q1: When I test this engine with the insertion of two 1 signs  

1. Testing this engine with the insertion of two 1 signs is actually creating a logical error that is recorded in the server log. 
2. Because (logically) the same data were inserted more than once, the results of calculating statistics got changed.

To demonstrate 1. I'm adapting the [example from the docs](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/#example-of-use):
```
SET send_logs_level='warning';

CREATE TABLE UAct
(
    UserID UInt64,
    PageViews UInt8,
    Duration UInt8,
    Sign Int8
)
ENGINE = CollapsingMergeTree(Sign)
ORDER BY UserID;

INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 1);
INSERT INTO UAct VALUES (4324182021466249494, 6, 146, 1);

OPTIMIZE table UAct;
```
This results in this warning
```
<Warning> CollapsingSortedTransform: Incorrect data: number of rows with sign = 1 (2) differs with number of rows with sign = -1 (0) by more than one (for key: 4324182021466249494).
```

Regarding 2. above, the example initially created two parts because of the two separate INSERT queries, therefore a `SELECT * FROM UAct;` executed before `OPTIMIZE table UAct;` (or before the next background merge) would give both inserted rows as the result. 

In that case, you can use `SELECT ... FINAL` in order to logically (but not physically on disk) merge parts just for that query (resulting in the same warning message from above by the way), but this way of selecting the data is very inefficient. Don’t use it for big tables. 

Instead, it is more efficient to use an aggregation query like shown for the [example from the docs](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/#example-of-use)

```
SELECT
    UserID,
    sum(PageViews * Sign) AS PageViews,
    sum(Duration * Sign) AS Duration
FROM UAct
GROUP BY UserID
HAVING sum(Sign) > 0
``` 
But that query would give incorrect results when you don't cancel a row with the -1 sign before inserting the new version of that row with a 1 sign. It would give 11 PageViews instead of 6 for the example above (as long as collapsing didn't take place yet for the two rows with the next background merge). That is the reason for the `
<Warning> CollapsingSortedTransform: Incorrect data: number of rows with sign = 1 (2) differs with number of rows with sign = -1 (0) by more than one (for key: 4324182021466249494).
` from above.

## Q2: Also, in the case of a large amount of data being sent, could you explain how this amounts to storing less data and how summing fields can be faster than reading an updated value?

- **storing less data**: ClickHouse doesn't have efficient row updates ([yet](https://github.com/ClickHouse/ClickHouse/issues/32513)). One could use [Mutations](https://clickhouse.com/docs/en/sql-reference/statements/alter/#mutations) for updating rows but that is very inefficient and not recommended for large tables. ClickHouse is very efficient and fast for inserting new rows though. Therefore it is faster for ClickHouse to insert a new additional row representing the new version of an existing row instead of updating the existing row. And as mentioned above, and explained in more detail in the docs part about the [algorithm](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/#table_engine-collapsingmergetree-collapsing-algorithm), instead of keeping all the previous versions of a row, the collapsing algorithm reduces all inserted versions of a row to not more than two rows. 
- **how summing fields can be faster than reading an updated value**: As mentioned above, the data collapsing occurs only during a merge. Merging occurs in the background at an unknown time, so you can’t plan for it, and therefore either have to use `SELECT ... FINAL` which is, especially for large tables, inefficient, or you can use an aggregation query that is summing your numeric fields as discussed above, and that is indeed more efficient than `SELECT ... FINAL` for large tables.

## Q3: examples are given for number fields with the use of sum * sign to obtain the concrete state of the selection. What about text or other fields
There is unfortunately no elegant/efficient solution for text fields. You could use an [VersionedCollapsingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/versionedcollapsingmergetree/) with a JOIN

```
CREATE TABLE UAct
(
    UserID UInt64,
    PageViews UInt8,
    Duration UInt8,
    Message String,
    Sign Int8,
    Version UInt8
)
ENGINE = VersionedCollapsingMergeTree(Sign, Version)
ORDER BY UserID;

INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 'a', 1, 1);

INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 'a', -1, 1),(4324182021466249494, 6, 185, 'b', 1, 2);
```

The result of the [any aggregate function](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/any) is indeterminate, unfortunately, so you can't rely on it selecting the correct value from a group
```
SELECT
    UserID,
    sum(PageViews * Sign) AS PageViews,
    sum(Duration * Sign) AS Duration,
    any(Message),
    Version
FROM UAct
GROUP BY
    UserID,
    Version
HAVING sum(Sign) > 0;
```
this selects the correct Message in my tests, but it is not reliable.

The JOIN solution gives the correct result but is not efficient:
```
WITH t1 AS
    (
        SELECT
            UserID,
            sum(PageViews * Sign) AS PageViews,
            sum(Duration * Sign) AS Duration,
            Version
        FROM UAct
        GROUP BY
            UserID,
            Version
        HAVING sum(Sign) > 0
    )
SELECT
    t1.UserID, t1.PageViews, t1.Duration, t2.Message
FROM t1
INNER JOIN UAct AS t2 ON (t1.UserID = t2.UserID) AND (t1.Version = t2.Version)
```
## Q4: In the documentation you mention: It must copy the key sort fields of the cancelled report except for Sign. Do you confirm that it is just necessary to transmit the value of these fields when sending the -1 sign?
Confirmed. 
For example, for the collapsing itself, this works - using the schema from Q1 above, note the 0 for the Duration:
```
INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 1);
INSERT INTO UAct VALUES (4324182021466249494, 5, 0, -1);

INSERT INTO UAct VALUES (4324182021466249494, 6, 148, 1);
```
`SELECT * from UAct FINAL` correctly selects only the values of the last row (4324182021466249494, 6, 148, 1).

BUT the aggregation query
```
SELECT
    UserID,
    sum(PageViews * Sign) AS PageViews,
    sum(Duration * Sign) AS Duration
FROM UAct
GROUP BY UserID
HAVING sum(Sign) > 0
```
is now calculating the wrong result for Duration (294 instead of 148). Therefore it is better to send all the fields of the to be cancelled row, or at least the fields you use in the aggregation query.

**Comment by MockingMagician** [comment]
Wow @tom-clickhouse, a big thank you for these answers!

This one brings me new ones :)

The answer to question 1 and 4 confirms that for a concrete update you have to send in one transaction the -1 sign with all previous values and the +1 sign with all new values.

Regarding this fact, 2 questions:
- Is there a recommended table size (number of fields) that should not be exceeded, which would cause a form of performance inversion of the engine?
- What are your recommendations in terms of best practices for sending the correct values of the row for the -1 sign in an application with concurrent queries that may potentially try to update the row in question at the same time?

Regarding the answer to question 3:
- You show me a secure example with the VersionedCollapsingMergeTree engine, I imagine that in the case of the CollapsingMergeTree engine the results are when uncertain?

Thanks again for these answers full of details!

**Comment by tom-clickhouse** [comment]
> Is there a recommended table size (number of fields) that should not be exceeded, which would cause a form of performance inversion of the engine?

It depends. (Versioned)CollapsingMergeTree table engines are just MergeTree table engines with additional actions during a merge. And for MergeTree tables up to a few hundred columns are reasonable, depending on system resources (CPU cores, Disk speed, Memory size, etc). Per [part](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-data-storage), each column is using two files on disk ([one for the column data](https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-design#data-is-stored-on-disk-ordered-by-primary-key-columns) and [one for locating specific groups of column values](https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-design#mark-files-are-used-for-locating-granules). Therefore when inserting row(s) with 100 columns, (at least) 200 files will be touched. The more CPU cores you have, and the faster the disk is, the faster this will take place and vice versa. 

 

> What are your recommendations in terms of best practices for sending the correct values of the row for the -1 sign in an application with concurrent queries that may potentially try to update the row in question at the same time?

For such scenarios the [VersionedCollapsingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/versionedcollapsingmergetree/) is better suited than the CollapsingMergeTree. A cite from the docs:
_VersionedCollapsingMergeTree serves the same purpose as CollapsingMergeTree but uses a different collapsing algorithm that allows inserting the data in any order with multiple threads. In particular, the Version column helps to collapse the rows properly even if they are inserted in the wrong order. In contrast, CollapsingMergeTree allows only strictly consecutive insertion._

> You show me a secure example with the VersionedCollapsingMergeTree engine, I imagine that in the case of the CollapsingMergeTree engine the results are when uncertain?

Indeed. The version column of the VersionedCollapsingMergeTree enables me to robustly join with the correct rows containing the text columns.

Whereas with CollapsingMergeTree, even when I join on all available columns, it is not robust:
```
DROP TABLE UAct;

CREATE TABLE UAct
(
    UserID UInt64,
    PageViews UInt8,
    Duration UInt8,
    Message String,
    Sign Int8
)
ENGINE = CollapsingMergeTree(Sign)
ORDER BY UserID;


INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 'a', 1);

INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 'a', -1), (4324182021466249494, 6, 185, 'b', 1);

INSERT INTO UAct VALUES (4324182021466249494, 6, 185, 'b', -1), (4324182021466249494, 6, 185, 'c', 1);

WITH t1 AS
    (
        SELECT
            UserID,
            sum(PageViews * Sign) AS PageViews,
            sum(Duration * Sign) AS Duration
        FROM UAct
        GROUP BY
            UserID
        HAVING sum(Sign) > 0
    )
SELECT
    t1.UserID,
    t1.PageViews,
    t1.Duration,
    t2.Message
FROM UAct AS t2
JOIN t1 ON (t1.UserID = t2.UserID) AND (t1.PageViews = t2.PageViews)  AND (t1.Duration = t2.Duration) AND t2.Sign = 1;
```
this will wrongly give two rows instead of one:
```
(4324182021466249494, 6, 185, 'b', 1)
(4324182021466249494, 6, 185, 'c', 1)
```

> Also you say that the JOIN solution gives the right result but is not efficient. Should we deduce that it is not recommended to use fields other than numeric with this type of engine?

It depends. You should test with realistic data and volume, and check if it satisfies your query time expectations.

By the way, regarding performance, it is better to switch the join clause order of the two joined tables, because, in order to execute a join, [ClickHouse takes the right_table and creates a hash table for it in RAM](https://clickhouse.com/docs/en/sql-reference/statements/select/join/#memory-limitations), therefore it is better to put the smaller table right in the join clause (before it was `FROM t1
INNER JOIN UAct AS t2` now it is `FROM UAct AS t2
INNER JOIN t1`):

```
CREATE TABLE UAct
(
    UserID UInt64,
    PageViews UInt8,
    Duration UInt8,
    Message String,
    Sign Int8,
    Version UInt8
)
ENGINE = VersionedCollapsingMergeTree(Sign, Version)
ORDER BY UserID;


INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 'a', 1, 1);

INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 'a', -1, 1),(4324182021466249494, 6, 185, 'b', 1, 2);

INSERT INTO UAct VALUES (4324182021466249494, 6, 185, 'b', -1, 2),(4324182021466249494, 6, 185, 'c', 1, 3);



WITH t1 AS
    (
        SELECT
            UserID,
            sum(PageViews * Sign) AS PageViews,
            sum(Duration * Sign) AS Duration,
            Version
        FROM UAct
        GROUP BY
            UserID,
            Version
        HAVING sum(Sign) > 0
    )
SELECT
    t1.UserID,
    t1.PageViews,
    t1.Duration,
    t2.Message
FROM UAct AS t2
INNER JOIN t1 ON (t1.UserID = t2.UserID) AND (t1.Version = t2.Version) AND (t2.Sign = 1)
```
This correctly and robustly returns just one row:
```
(4324182021466249494, 6, 185, 'c', 1, 3)
```

**Comment by MockingMagician** [comment]
Hello @tom-clickhouse , sorry for my late return. 

I thank you for all your detailed feedback and the time you spent on it. It gave me the answers I needed.

Best regards

**Comment by tom-clickhouse** [comment]
Hello @MockingMagician, thanks, am glad I could help :)

By the way, after thinking about it once more, I believe that using `any` or `groupArray` in order to obtain text fields is save/robust in the case of `VersionedCollapsingMergeTree` (and the join version is unnecessary)

```
CREATE TABLE UAct_version
(
    UserID UInt64,
    PageViews UInt8,
    Duration UInt8,
    Message String,
    Sign Int8,
    Version UInt8
)
ENGINE = VersionedCollapsingMergeTree(Sign, Version)
ORDER BY UserID;

INSERT INTO UAct_version VALUES (4324182021466249494, 5, 146, 'a', 1, 1);

INSERT INTO UAct_version VALUES (4324182021466249494, 5, 146, 'a', -1, 1),(4324182021466249494, 6, 185, 'b', 1, 2);

SELECT
    UserID,
    sum(PageViews * Sign) AS PageViews,
    sum(Duration * Sign) AS Duration,
    any(Message),
    groupArray(Message)[1],
    Version
FROM UAct_version
GROUP BY
    UserID,
    Version
HAVING sum(Sign) > 0;
```
