### ISSUE TITLE
Suspicious memory-leak in "create table engine=Join as select..." query

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#39472]
**Describe the unexpected behaviour**
Repeat running "create table engine=Join as select ..." query causes suspicious memory leak.

**How to reproduce**
* Which ClickHouse server version to use
22.6.3.35

* Which interface to use, if matters
clickhouse-client 

* Queries to run that lead to unexpected result
Repeat running the following query, leading to continuously increasing of memroy.
```
--- assume table `T1` is a talbe of 10M rows

DROP TABLE IF EXISTES test;

CREATE TABLE test
ENGINE = Join(any, left, `col1`) AS
SELECT
    `col1`, 
    `col2`
FROM `T1`
SETTINGS transform_null_in = 1
SETTINGS join_use_nulls = 1
```

* The problem is that the memory usae is continuousely increasing until the clickhouse process aborts.

**Comment by tavplubix** [comment]
Is it reproducible with `DROP TABLE test SYNC`?

**Comment by Alex-Cheng** [comment]
Thank you, let me have a try.

**Comment by tavplubix** [comment]
I suppose `SYNC` modifier helped. So the reason is clean: by default table removal is postponed for `database_atomic_delay_before_drop_table_sec` seconds to avoid accidental data removal. But it does not really make sense for in-memory tables that do not store data on disk, so we can remove them without delay.
