### ISSUE TITLE
Is feature 'Using S3 for Data Storage' is experimental ?

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/ClickHouse#39481]
As per the docs , Using S3 for Data Storage is experimental. 
If Yes , Any plans when it can be roasted and  used in production ?

<img width="636" alt="image" src="https://user-images.githubusercontent.com/86018844/180352049-283af30c-6e37-4a4a-9912-316154c83175.png">

if not, [Docs](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-multiple-volumes_configure) needs to be updated .:

**Comment by tom-clickhouse** [comment]
[S3-backed MergeTree](https://clickhouse.com/docs/en/integrations/s3/s3-merge-tree) indeed started to be [production ready](https://clickhouse.com/docs/ru/whats-new/changelog/#new-feature-4).
Unless you use [S3 zero copy replication](https://clickhouse.com/docs/en/operations/storing-data/#zero-copy) with it, because that feature is exeperimental.

We just [updated](https://github.com/ClickHouse/clickhouse-docs/pull/253) the docs accordingly.
