### ISSUE TITLE
How many thread execute for each insert

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ClickHouse#39480]
In you document, i found that the advice for insert is `insert once per second`.
Is it means that each insert will use all thread to execute?
And thus parallel insert is not efficient as batch insert in one thread?

**Comment by tom-clickhouse** [comment]
For a normal `INSERT INTO` (that can/should contain many rows, a good number would be at least 1000 rows) `one thread` is used - that stores the rows in part(s).
And because each `INSERT INTO` is creating (at least) one part, we give the advice to not send too many inserts per second to the server in order to not cause "Too many parts exceptions" - parts are merged eventually into fewer parts, but when constantly too many new parts are getting created, ClickHouse will raise the "Too many parts exceptions".

For `INSERT INTO . . . SELECT` the [max_insert_threads](https://clickhouse.com/docs/en/operations/settings/settings/#settings-max-insert-threads) setting is used.

> And thus parallel insert is not efficient as batch insert in one thread?

Both can be efficient.
You can use one batch insert sending 100k rows - that will use one thread creating one part.
Or you can use 2 parallel batch inserts sending 50k rows - that will use two threads creating 2 parts in parallel, that will be merged eventually.

**Comment by den-crane** [comment]
@tom-clickhouse 

>For a normal INSERT INTO (that can/should contain many rows, a good number would be at least 1000 rows) one thread is >used - that stores the rows in part(s).

It's not true for text formats. Because `input_format_parallel_parsing=1` by default.

https://kb.altinity.com/altinity-kb-queries-and-syntax/atomic-insert/
