### ISSUE TITLE
full_sorting_merge errors out due to memory

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#39542]
I thought the whole point of full_sorting_merge was to allow for larger than memory joins, so I am somewhat surprised by the behavior.

100 million x 100 million is fast and great. But I am joining 9 billion table to itself (e.g. 9 by 9 billion row query, it's a bit of an extreme case) using "full_sorting_merge". I have also tried 9 billion by small right table. 

I gave it 350GB of memory. I have tried various ratios of max_bytes_before_external_sort and basically the query errors out due to a lack of memory. Is this expected?

**Although I can't pass the data over a Dropbox link, I can pass over the data or some easily obfuscated data confidentially, it is just market data**

**Comment by vdimir** [comment]
Thank you for your feedback!

The `full_sorting_join` can consume lots of memory if many rows have the same key. In that case, a cross-like join of them would be produced in memory. It's applicable only for `ALL JOIN`, but not for `ANY JOIN`, which takes only one row for a particular key and wouldn't load all of them into memory. To check how many blocks were loaded simultaneously, you can grep logs for the message `<Trace> MergeJoinTransform: Finished pocessing in 1096.3877 seconds, left: 8804 blocks, 576699750 rows; right: 8804 blocks, 576699750 rows, max blocks loaded to memory: 4`. (I add displaying the message for the canceled query too for debugging such cases).

---

But sorting can consume memory as well.

_What is the values of `max_bytes_before_external_sort` and `max_threads`?_
You can try to reduce the number of threads because each can consume memory during the sorting step.

Maybe it's possible to create a synthetic example to reproduce your problem?

I've experimented with this synthetic data:

```sql
CREATE TABLE t1 (
    key UInt64
    , attr1 String
    , attr2 String
) Engine = MergeTree ORDER BY key;


INSERT INTO t1 SELECT
    sipHash64(number, 't1_key') % 1000000000 as key
    , randomString(rand() % 100) as attr1
    , randomString(rand() % 100) as attr2
    FROM numbers(1000000000);
```

By setting `max_bytes_before_external_sort` and reducing the number of threads, the query finishes with the usage of approximately just 20GB for 1B rows.

Set settings and execute:

```sql
SET join_algorithm = 'full_sorting_merge';

SET max_memory_usage = '25G';
SET max_bytes_before_external_sort = '1G';

SET max_threads = 8;

SELECT
    query_id(),
    countIf(t1.attr1 != t2.attr1 AND t1.attr2 != t2.attr2)
FROM t1 JOIN t1 as t2 ON t1.key = t2.key;
```

Collect memory usage info:

```
:) SELECT toString(round(memory_usage / 1024 / 1024 / 1024, 2)) || ' GB' as memory_usage from system.query_log where query_id = '473f375e-2cd0-48d8-a61a-bc3f1c40fe49' AND type = 'QueryFinish';

┌─memory_usage─┐
│ 19.77 GB     │
└──────────────┘
```

---

What you can do now:
1. Provide a synthetic example that fails when you expect to finish.
2. Provide a log for query with your data.
3. Try to get a memory profile for the query. 

To do that you may want to run query with `SET memory_profiler_sample_probability=0.1;` (you can try different values, let's say `0.1,0.25,0.5,1.0`)

And then analyze it (e.g., as described [here](https://kb.altinity.com/altinity-kb-queries-and-syntax/trace_log/))
Or send trace log:

```bash
clickhouse-client --format=Native -q "SELECT * from system.trace_log WHERE query_id = '473f375e-2cd0-48d8-a61a-bc3f1c40fe49' > trace_log.bin"
```

**Comment by alanpaulkwan** [comment]
I'll provide a query later, but your suggestion basically made me realize the issue was cardinality explosion. For some reason my right table has a lot of duplicates (not my intended business purpose) which when de-duplicated the full_sorting_merge works great.

Limiting the number of threads was also necessary to make it feasible (20x vs 8x, I don't know if the RAM is proportional to the threads but this helped).

**Comment by vdimir** [comment]
It's one of our points to improve in full_sorting_merge - not to load all blocks with duplicated keys into the memory (dump them on disk). In the initial implementation, we omitted it because we assumed it's a rare case but still have it in the TODO list.
