### ISSUE TITLE
Missing columns while using Object('json') with subquery or join

### ISSUE THREAD

**Issue by Melonico** [ClickHouse/ClickHouse#39543]
clickhouse version: 22.6.3.35

I'm running some tests for data type JSON
my test table: 
```sql
set allow_experimental_object_type = 1;
create table t_map_test (
                            `user_id` String,
                            `time` Int64,
                            `event_name` String,
                            `json` JSON
) engine = MergeTree order by `time`;
```
insert some data 

```sql
insert into t_map_test values ('test', 123123123, 'test', '{"param1": "test"}');
insert into t_map_test values ('test', 123123123, 'test', '{"param1": "test", "param2": "test2"}');
```

do a simple query
```sql
select json.param1 from t_map_test;
```
it works!

but when I try to use subquery
```sql
select json.param1 from (select * from t_map_test);
```
it cause 
```
Code: 47. DB::Exception: Missing columns: 'json.param1' while processing query: 'SELECT json.param1 FROM (SELECT * FROM t_map_test)', required columns: 'json.param1' 'json.param1'. (UNKNOWN_IDENTIFIER) (version 22.6.3.35 (official build))
```
`join` opration have the same problem

i can get `json` column from subquery 
```sql
select json from (select * from t_map_test);

"('test','test2')"
"('test','')"
```
but i can't use dot to get `param1` in `json`

i don't know how to deal with this problem

btw, function `tupleElemet` can deal this problem, but it will take more time , so I wonder how to solve this problem with dot

**Comment by tom-clickhouse** [comment]
Internally, [JSON](https://clickhouse.com/docs/en/sql-reference/data-types/json/) is implemented/represented as a [Tuple](https://clickhouse.com/docs/en/sql-reference/data-types/tuple/).
And this has some consequences, like your unexpected query behavior.

`SELECT * FROM t_map_test` returns values of type Tuple for your column with the name `json`.

Therefore you could do this (to simulate `select json.param1 from (select * from t_map_test);`):
`select json.1 from (select * from t_map_test);` (here `json` is the name of a column of type Tuple)

Whereas, when you do `select json.param1 from (select * from t_map_test);` then the outer select is trying to select a column with the name `json.param1`, but the inner select returns a table that, next to other columns, has a column with the name `json`.

What you also can do is `select json.param1 from (select json.param1 from t_map_test);`  because here the inner select return a table with a column with the name `json.param1` with values of type String, and the outer select selects this column.

**Comment by liuzhiguo630** [comment]
Plz support this.

**Comment by alexey-milovidov** [comment]
We don't support the JSON data type.

**Comment by deyveloper** [comment]
https://youtu.be/qeZOT8B8QiA 20:27
