### ISSUE TITLE
Jepsen: invalid analysis

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#39559]
https://s3.amazonaws.com/clickhouse-test-reports/0/73c04b64e35354264a5943b131f879753f3eaaca/clickhouse_keeper_jepsen.html

cc: @antonio2368, @alesapin

**Comment by antonio2368** [comment]
Based on a quick look it seems like a timing issue inside NuRaft.
A node crashed because of an invalid assert. On the broken node this happened:

```
2022.07.24 18:25:00.591989 [ 10770 ] {} <Trace> RaftInstance: resp of req 3 -> 1, type append_entries_request, OK
2022.07.24 18:25:00.591998 [ 10770 ] {} <Debug> RaftInstance: Receive a append_entries_response message from peer 1 with Result=0, Term=3, NextIndex=623
2022.07.24 18:25:00.592003 [ 10770 ] {} <Trace> RaftInstance: src: 1, dst: 3, resp->get_term(): 3
2022.07.24 18:25:00.592433 [ 10765 ] {} <Debug> RaftInstance: Receive a client_request message from 0 with LastLogIndex=0, LastLogTerm=0, EntriesLength=18, CommitIndex=0 and Term=0
2022.07.24 18:25:00.592453 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 591
2022.07.24 18:25:00.592460 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 592
2022.07.24 18:25:00.592466 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 593
2022.07.24 18:25:00.592471 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 594
2022.07.24 18:25:00.592477 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 595
2022.07.24 18:25:00.592488 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 596
2022.07.24 18:25:00.592498 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 597
2022.07.24 18:25:00.592504 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 598
2022.07.24 18:25:00.592511 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 599
2022.07.24 18:25:00.592518 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 600
2022.07.24 18:25:00.592526 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 601
2022.07.24 18:25:00.592547 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 602
2022.07.24 18:25:00.592554 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 603
2022.07.24 18:25:00.592559 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 604
2022.07.24 18:25:00.592566 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 605
2022.07.24 18:25:00.592574 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 606
2022.07.24 18:25:00.592580 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 607
2022.07.24 18:25:00.592585 [ 10765 ] {} <Debug> RaftInstance: append at log_idx 608
2022.07.24 18:25:00.599294 [ 10770 ] {} <Trace> RaftInstance:   FOLLOWER
```

NuRaft sets the term of the current node to the term of the resp if it's larger than the current one. This happens even if the node is leader. The lock for processing requests and changing the node status from leader to follower is taken after the state is set.
What happened is:
- node 3 is the leader with term 2 and because of partitioning doesn't know that it lost the majority
- node3 got a response from node 1 (the new leader with term 3)
- node 3 set the term to 3
- node 3 processes the client request because it thinks it's leader but with term 3 from new leader
- node 3 becomes follower
- when it processes logs from node 1, it thinks they have the same logs because of the same term so it doesn't rollback what it should

Why didn't we notice it before?
This is a data race that can only happen if the cluster is in a specific state + we didn't have any safety checks.

I'll take a deeper look, but I would say the logic is wrong.
WDYT @alesapin

**Comment by alexey-milovidov** [comment]
@antonio2368 let's invite people from NuRaft, you can create an issue in their repository with the reference to this issue.

**Comment by antonio2368** [comment]
No need, the explanation was correct and it was fixed in March https://github.com/eBay/NuRaft/pull/294
I'll pull the latest changes.
