### ISSUE TITLE
mutations stuck

### ISSUE THREAD

**Issue by AceHCL** [ClickHouse/ClickHouse#39885]
Table Engine: ReplicatedMergeTree
Action: alter table delete where
Problem: Mutations stuck on individual nodes, resulting in the accumulation of ddl statements waiting to be executed, and the table became read-only mode. I would like to ask if there is any optimized configuration for this kind of mutation stuck phenomenon? At present, I restore the use of the node by restarting.

**Comment by tbragin** [comment]
Not sure if this problem is still happening. 

Mutations can appear stuck because of various type of resource exhaustion, often resulting from workloads writing data not according to best practices (too small batches, too frequently). 

If this is still happening, please share what version of ClickHouse you are running. If the version is not in supported versions, please upgrade - many problems were fixed since 2022. https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions

**Comment by Algunenano** [comment]
It's impossible to guess what's the reason a mutation might be "stuck", without checking the logs of the server and the mutation. There is no silver bullet here, just case by case analysis.
