### ISSUE TITLE
best practices to create a fully replicated local table on clusters

### ISSUE THREAD

**Issue by IvanWoo** [ClickHouse/ClickHouse#40013]
greetings!

## context

- 2 shards, 2 replicas cluster
- a small local table needs to be replicated among every nodes, that is the local table is identical in all 2x2=4 nodes 

## options

there are two options

### 1

create the table using `engine=ReplicatedMergeTree('/clickhouse/{cluster}/tables/{database}/{table}', '{replica}')`

we don't have the `{shard}` macro in the zk path.
we just need to sink into one node and leverage the ch internal replication feature to propagate to every nodes.
but the single node maybe become the bottleneck when we have more shards or the table size increase a lot.

### 2

create the table using `engine=ReplicatedMergeTree('/clickhouse/{cluster}/tables/{shard}/{database}/{table}', '{replica}')`

shard-awareness replication.
we remove the bottleneck of the single node and might have better ingestion throughput.
but we need to manage the sink job to insert the same local table into every shards.

## questions

- does my understand correct in term of the pros and cons for these two options?
- which one is better based on your production experiences? (we might have more shards and bigger local table in the future)

thanks!

**Comment by DerekChia** [comment]
Hello, 

Abstractly, a ReplicatedMergeTree table has two main parameters - `ZooKeeperPath` and `ReplicaName`:
`engine=ReplicatedMergeTree(ZooKeeperPath, ReplicaName)`

ReplicatedMergeTree tables that have the same `ZooKeeperPath` but different `ReplicaName` will automatically replicate from each other.  

Assuming that you use 4 nodes with the hostnames `host1`, `host2`, `host3`, and `host4`, and on these 4 nodes you want to create
- a table with 2 shards and 2 replicas per shard (cluster1), and
- a table with 4 replicas (cluster2)

Then you can
1. Define two cluster topologies for the two tables in the [ClickHouse server configuration file](https://github.com/ClickHouse/ClickHouse/blob/22.7/programs/server/config.xml#L702) on all 4 nodes:
```
<remote_servers>

  <cluster1>
    <shard>
      <internal_replication>true</internal_replication>
      <replica>
        <host>host1</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>host2</host>
        <port>9000</port>
      </replica>
    </shard>
    <shard>
      <internal_replication>true</internal_replication>
      <replica>
        <host>host3</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>host4</host>
        <port>9000</port>
      </replica>
    </shard>
  </cluster1>

  <cluster2>
    <shard>
      <internal_replication>true</internal_replication>
      <replica>
        <host>host1</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>host2</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>host3</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>host4</host>
        <port>9000</port>
      </replica>
    </shard>
  </cluster2>

</remote_servers>
```
2. Define macros in the [ClickHouse server configuration file](https://github.com/ClickHouse/ClickHouse/blob/22.7/programs/server/config.xml#L896) on all 4 nodes:

`host1`:
```
<macros>
    <shard_cluster1>1</shard_cluster1>
    <shard_cluster2>1</shard_cluster2>
    <replica>replica_1</replica>
</macros>
```
`host2`:
```
<macros>
    <shard_cluster1>1</shard_cluster1>
    <shard_cluster2>1</shard_cluster2>
    <replica>replica_2</replica>
</macros>
```
`host3`:
```
<macros>
    <shard_cluster1>2</shard_cluster1>
    <shard_cluster2>1</shard_cluster2>
    <replica>replica_3</replica>
</macros>
```
`host4`:
```
<macros>
    <shard_cluster1>2</shard_cluster1>
    <shard_cluster2>1</shard_cluster2>
    <replica>replica_4</replica>
</macros>
```
3. Create the two tables with a distributed DDL query (execute the DDL queries on one of the nodes, the other nodes will create the replicas automatically):
- a table with 2 shards and 2 replicas per shard:
```
CREATE TABLE ... ON CLUSTER cluster1
(
   ...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard_cluster1}', '{replica}')
ORDER BY (...);
```
- a table with 4 replicas
```
CREATE TABLE ... ON CLUSTER cluster2
(
   ...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard_cluster2}', '{replica}')
ORDER BY (...);
```
Note that we [recommend](https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper-uuid/) using the built-in {uuid} macro setting within the `ZooKeeperPath` in order to be able to destroy and recreate tables (for example for tests) without delay. Otherwise, you will experience [delay](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#database_atomic_delay_before_drop_table_sec) (defaults to 8 minutes of wait time) when trying to drop and recreate table with the same `ZooKeeperPath`.
