### ISSUE TITLE
DROP PART vs DROP PARTITION

### ISSUE THREAD

**Issue by Mall0c** [ClickHouse/ClickHouse#40144]
Consider a table that is partitioned by month. The parts in these partitions, however, do not span a whole month. Lets say Partition 202207 for July has three parts:

* one with min_time 2022-07-01 and max_time 2022-07-10
* one with min_time 2022-07-11 and max_time 2022-07-20
* one with min_time 2022-07-21 and max_time 2022-07-31

In order to delete data, I could go either with the TTL statement or regular execution of the DROP PARTITION statement, at least that's what is recommended in https://clickhouse.com/docs/zh/faq/operations/delete-old-data/ and online when googling this topic. I've never come across a thread, where someone would suggest using DROP PART instead of DROP PARTITION. Is there a reason for this, e. g. in terms of functionality or stability of the Clickhouse servers? Or can one simply use DROP PART as well without any further issues?

**Comment by den-crane** [comment]
>The parts in these partitions, however, do not span a whole month

It's not true in general.

> Is there a reason for this, e. g. in terms of functionality or stability of the Clickhouse servers? Or can one simply use DROP PART as well without any further issues?

You can use DROP PART for this.
DROP PART was implemented rather recently and it was implemented as a maintenance tool.

BTW, there are merge_tree setting `ttl_only_drop_parts`, if enabled TTL merge only drops whole parts when all rows are expired in a part instead of re-writing a part into a new part without expired rows.
