### ISSUE TITLE
Question - How to make consistent backup with FREEZE during mutations

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [ClickHouse/ClickHouse#4022]
Hello,

*Edited this ticket after learning more about nature of my problem, and that SELECT during mutation returns mixed data*

I'm creating backup procedure for our ClickHouse database, using "ALTER ... FREEZE" directive. Everything works smooth, and like intended, except when mutations are running.

One "ALTER ... FREEZE" for YYYYMM is atomic operation that is done before, or after mutation (thanks for this information)

My problem is that I'm backuping whole year, or multiple years - and loop over multiple freeze operations is (if I understand correctly) not atomic. In result I can get some data after mutation, and some data before mutation (in worst scenario). Backup won't be consistent.

As solution, I can wait for all mutations to end, but it means that in theory backup can never succeed. Also I can't ensure that between my select, and alter freeze, there won't be any other mutation run.

Could you suggest valid solution for this problem? How to make consistent backup of whole ClickHouse database, with assumption that we are using ALTER ... DELETE/UPDATE operations.

**Comment by filimonov** [comment]
switching partitions (old without mutation to new with mutated data) should be atomic (after mutated partition is created old marked as inactive and new marked as active atomically).
`Alter ... freeze` should be atomic too (it just create a hardlink)

I.e. if you run freeze before mutation finish - you should get backup of unmutated data, if you run freeze after mutation - you should get backup of mutated data.  In both case it should give proper results with `active` partitions. To use restored backup, you can additionally store mutations log which were fired after freeze, 

If you encounter some problems with that - please provide more details and try to create a reproducible sample.

**Comment by ztlpn** [comment]
A single ALTER FREEZE command will operate on a snapshot of data (just as a single SELECT does). So yes there can be some consistency problems if you backup using multiple statements at once. Maybe the new variant of the ALTER FREEZE command that first appeared in 18.16.0 and backs up all table at once will suit you. Note that it isn't possible to backup a subset of partitions (e.g. a year of data) with a single ALTER FREEZE command for tables created with the custom-partitioning syntax (for tables created with the old-style month partitioned syntax you can pass a partition prefix, e.g. `2018` to the command).

Note that if you want stronger consistency with respect to mutations (i.e. the mutated data is "published" at some point in time and all operations either see no changes or all changes at once) then this is unlikely to be implemented because it potentially requires x2 disk space.

**Comment by blinkov** [comment]
@TomaszUrugOlszewski, do you have any further questions?

**Comment by TomaszUrugOlszewski** [comment]
No, thank you

**Comment by filimonov** [comment]
#13953
