### ISSUE TITLE
How to do bitTest for hex formatted string efficiently?

### ISSUE THREAD

**Issue by jiegui-2021** [ClickHouse/ClickHouse#40242]
There is a string column A, its content is hex formatted string, like: "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020400000".
4 here means bit 23 is 1. Cannot use integer data type because max bit pos might>124.
I'd like to select Agg(*) from Table WHERE {bit n of A is 1}. Here's what I am doing:
bitTest(reinterpretAsUInt8(unhex(substr(AdExtensionType, (length(AdExtensionType) - (n/4)) + 1, 1))), n%4) == 1.
But it is slow.
Would like to know if there's more efficient way implement it? Thank you.

**Comment by rschu1ze** [comment]
About `String` as a data type: As all values have the same length, `FixedString(N)` is a little bit more efficient than `String`. For the former, no value separators are stored value internally.

But what is really expensive is the string manipulation. So you rather like to get rid of it. If I understand correctly, the underlying type is an integer, currently encoded as string because it's rather wide. So what about splitting the integer, e.g. instead of a single string column, you use four `UInt64` colums for bits `0 ... 63`, `64 ... 127`, etc.? You could then have a `WHERE` clause with [if condition](https://clickhouse.com/docs/en/sql-reference/functions/conditional-functions/#if) to route the filter to the correct column: (dummy code, untested) `... where if (0 <= n <= 63(bitTest(col_0, n % 64), if (...))` (could surely be written more beautifully using [CASE](https://clickhouse.com/docs/en/sql-reference/operators/#conditional-expression)).
