### ISSUE TITLE
arrayJoin docs make use of disabled by default feature

### ISSUE THREAD

**Issue by IvanIvanoff** [ClickHouse/ClickHouse#40294]
The [arrayJoin page](https://clickhouse.com/docs/en/sql-reference/functions/array-join/) has 3 examples of `GROUP BY` using column numbers.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/6518376/185089592-0f844ae1-77d1-4825-ba7d-5f3287c7e99a.png">

The `GROUP BY` column numbers feature was introduced in [version 21.10](https://clickhouse.com/docs/en/whats-new/changelog/2021/#clickhouse-release-v2110-2021-10-16)

This feature is disabled by default, as can be seen in the [enable_positional_arguments setting docs](https://clickhouse.com/docs/en/operations/settings/settings/#enable-positional-arguments)

Given the fact that this is a relatively new feature and is disabled by default, I think the `arrayJoin` examples should use column names instead of column numbers.

Edit: Since https://github.com/ClickHouse/ClickHouse/pull/38204 `enable_positional_arguments`'s default value is `1`, which is not reflected in the documentation. This does not change my opinion that the documentation's examples should work in as many versions as possible, not only in the most recent ones.

**Comment by den-crane** [comment]
CH documentation reflects master branch.
I did these examples 2 days ago.
I did used positional_arguments intentionally to show full power of CH and encourage people to upgrade. Every line in this examples intentional, I could write this without arrayZip, without tuple indexes, without inline aliases, but I decided to use them to expose all features.
