### ISSUE TITLE
Question about the implementation of sample

### ISSUE THREAD

**Issue by fancyqlx** [ClickHouse/ClickHouse#4035]
Hi, I have read the code about sample and have a question about the implementation of sample. In the follow part of codes, the sampled lower and upper bound have been added into key condition so that w will get sampled mark ranges. But why we still add a filter expression to filter read results. In my opinion, sampled ranges is enough to get sampled data.
![image](https://user-images.githubusercontent.com/6196299/51025853-0b601700-15c8-11e9-94e1-3caaece0c69e.png)

I also did an experiment by deleting filter expression. As a result, I get a good enough sampled data. The following pictures are my test experiment. The first two pictures are the results before deleting filter expression. We can find that after deleting filter expression, the engine get fewer data and run faster.

![image](https://user-images.githubusercontent.com/6196299/51026317-2b440a80-15c9-11e9-9b5d-a6f79f9a3a1e.png)
![image](https://user-images.githubusercontent.com/6196299/51026443-7d852b80-15c9-11e9-8ecb-96d9bed76360.png)

![image](https://user-images.githubusercontent.com/6196299/51026327-3008be80-15c9-11e9-97ff-c09ea888fb36.png)
![image](https://user-images.githubusercontent.com/6196299/51026403-66ded480-15c9-11e9-809f-da9becbc2942.png)

**Comment by blinkov** [comment]
@fancyqlx is this questions still relevant to you?

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/blob/a62866918fc333338bc7ac624db1681761fc5029/dbms/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L450

@fancyqlx i think if you remove the filter expression the sample will became non-determenistic. To check that / say more - you can prepare pull request with that change and look which tests will fail.

**Comment by blinkov** [comment]
@fancyqlx, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@fancyqlx Yes, the reason is to get deterministic and well defined subset of data.

You can execute a query with SAMPLE 1/2 and another query with SAMPLE 1/2 OFFSET 1/2 and be sure that the subsets of data have no intersections and covers 100% of data together.

Even more, you can execute the same SAMPLE expression for different tables on different servers at different time and still get the guarantee that exactly the same subset of "universum" of all possible values get processed.

This is especially important if you want to JOIN / IN data from different tables.
