### ISSUE TITLE
Make AVX and AVX2 prerequisites for running ClickHouse (tasks for 2025+)

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#40459]
**Use case**

We should require that the system where ClickHouse runs on supports the AVX1 and AVX2 instruction sets on the x86 platform. This will provide the auto-vectorizer of the compiler with better optimization opportunities beyond SSE.

**Additional context**

We tried to enable AVX1 as a first step in August 2022 #39000. On the one hand, the performance benefit was mixed (some tests got faster, for other tests a workaround had to be added to avoid performance regression). On the other hand, some users reported that some machines, e.g. embedded/industrial systems, don't support AVX which was released 10+ years ago. As a result, the AVX1 enablement was [~~rolled back~~](https://github.com/ClickHouse/ClickHouse/pull/40444) [rolled back](https://github.com/ClickHouse/ClickHouse/pull/40462).

It may still be a good idea to enable AVX1/2, also because preliminary results with AVX 2 were promising. But we better don't do this in the near future, maybe somewhen in 2025.

**Comment by alexey-milovidov** [comment]
Please don't plan for 2025 :)

**Comment by alexey-milovidov** [comment]
Maybe we will enable AVX-2 after a month if the benefits in performance will be significant.

**Comment by rschu1ze** [comment]
Sure. 

I was also thinking that we could appease the no-AVX hobbyist/embedded crowd by exposing a CMake switch a la `-DNO_AVX=1`. Users then at least won't have to go to the source code to build a working version for their old hardware.

**Comment by pkit** [comment]
Having a non-avx client with avx-only server would be a good compromise? Right now it's not possible, AFAIU?

**Comment by konnectr** [comment]
It seems to me that it is not economically clear to support different code. If most servers support AVX

**Comment by pavel-odintsov** [comment]
Hello!

I'm really glad that it was reverted and returned to discussion phase. I appreciate it.

Even Clickhouse's demand to have SSE 4.2 causes significant issues for us as we deliver our product to really large number of on premise server platforms.

We still keep alternative databases which are way worse in terms of performance for machines without SSE 4.2. It causes additional development overhead for us for sure.

Requirement to have AVX will cause havoc for us and we're already considered switching to our fork or moving to alliterative build of Clickhouse just to avoid this issue.

I completely support your fight for performance and separate build which requires AVX would be great option.

I can highlight some reasons which lead to lack of SSE42 or AVX on many platforms below.

Old server CPUs. Well, it's obvious but I want to highlight that these CPUs are perfectly fit to run modern workloads. CPU development is going over path of adding more cores but single core performance is not growing significantly for last decade. 

I would like to add this graph by Chuck Moore of AMD to prove my point:
![Screenshot from 2022-09-03 12-43-14](https://user-images.githubusercontent.com/2744166/188268888-6309d642-6d46-4f71-8237-4850948ba29e.png)

As you may see just banning 10 year old CPUs which are perfectly fit to run almost any modern workload due to lack of quite niche feature as AVX is not something which does make sense.

Second reason of AVX lack is virtualisation. 

There are two reasons why AVX may be ecluded from CPU flags by hypervisor:
- Mistake with CPU profile selection during VM provision phase. Some virtualisation platforms have defaults which disable SSE 4.2 and AVX intentionally: https://forum.proxmox.com/threads/processor-compatibility-mode.95508/ 
- Live migration. To use such modern features as live migration for your private or public cloud you need to maintain exactly same subset of features for all your servers. Otherwise it will lead to issues like this: https://kb.vmware.com/s/article/65151 So even if you have 1000 machines with AVX and 20 without it then AVX must be disabled. Otherwise it will lead to issues

I mostly covered these things in context of server CPUs but so many customer grade CPU will definitely lack of AVX and it will effectively ban them from playing with Clickhouse on their developer machines. It will make things way worse in developing countries which just cannot afford modern AVX capable equipment even for their server. 

Thank you for reading.

**Comment by alexey-milovidov** [comment]
@pavel-odintsov we can add additional builds without SSE 4.2 to our CI, or even with SSE 2 only.

**Comment by pavel-odintsov** [comment]
That would be amazing. I think version without SSE4.2 will be useful for sure. I do not remember any case of CPU which has no SSE 2.

Thank you!

**Comment by alexey-milovidov** [comment]
All amd64 CPUs have SSE2, it is mandatory.

**Comment by alexey-milovidov** [comment]
@rschu1ze let's add it for "Special Build Check", then it will be easy downloadable for releases.

**Comment by alexey-milovidov** [comment]
@pavel-odintsov The SSE2-only build has been added.

**Comment by alexey-milovidov** [comment]
@rschu1ze One idea almost "for fun" - let's create a draft PR (not for merging) where we will check performance tests for SSE2-only build.

**Comment by pavel-odintsov** [comment]
Hello!

Thank you so much! 

What is the best way to download these packages?

Thank you!

**Comment by rschu1ze** [comment]
@pavel-odintsov Go to any of the [last merged PRs](https://github.com/ClickHouse/ClickHouse/commits/master), then click button "View Details" which opens the CI checks on that PR. Next, search "BuilderBinAmd64SSE2 " and click "Details". Unfold the "Build" step. You will find at the bottom the link to the static clickhouse binary as it was stored on S3, e.g. `https://s3.amazonaws.com/clickhouse-builds/41033/0df6173e4a9d77d25b243b12ae2e04e27790591a/binary_amd64sse2/clickhouse` [here](https://github.com/ClickHouse/ClickHouse/actions/runs/3013649007/jobs/4858954927).

To save resources, the binary is not "packaged" but stored as is.

> @rschu1ze One idea almost "for fun" - let's create a draft PR (not for merging) where we will check performance tests for SSE2-only build.

Created #41288, will be interesting to see the result.
