### ISSUE TITLE
exception after drop nested column

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#40672]
version: 21.8.9.13
engine: ReplicatedReplacingMergeTree

```
alter table t1 on cluster '{cluster}' drop column nest;
```

after drop a nested column like above on my production, then I found some exception in system.replication_queue, it  seems the task retries all the time, the info in system.replication_queue show as below, how can  i fix the exception? 
unfortunately  I can't reproduce. appreciate for any help.

```
type: MUTATE_PART
num_tries: 249116222
last_exception: Code: 47. DB::Exception: Missing columns: dropped nest column.
postpone_reson: Not executing log entry queue-0000001362 of type MUTATE_PART for part 202206_0_27562_17080_27567 because source parts size (307.86 KiB) is greater than the current maximum (0.00 B).
```

**Comment by mofei920** [comment]
is it possiable to fix it by creating a new table and replace the old table, at last drop the old table?

**Comment by tbragin** [comment]
Dropping a table and re-creating seems like a possible solution, but not sure if what you experienced should be expected behavior. Curious if you are still seeing this error, and if so whether that happened on a more recent version since then? https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions
