### ISSUE TITLE
Parameterized views as table functions

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#40907]
A user should be able to create a view from a parameterized query:
```
CREATE VIEW test AS SELECT * FROM hits WHERE user_id = {user:UInt64}
```
There can be an arbitrary number of parameters in this query.

This view can be used as a table function, where parameters are provided in form of `param_name = param_value, ...` pairs:

```
SELECT * FROM test(user = 123)
```

This view cannot be used as a regular table:

```
SELECT * FROM test
```
will return an error.

These views are created in a database, like tables, and can be qualified with the database name:

```
SELECT * FROM default.test(user = 123)
```

If the view has the same name as any existing table function (like `mysql`), it is only accessible if qualified with the database name.

The parameters, defined externally, are not propagated into the view.
E.g., this will not work:

```
SET param_user = 123;
SELECT * FROM default.test;
```

So, the parameters inside views are local.

But you can propagate them manually:
```
SET param_user = 123;
SELECT * FROM default.test(user = {user:UInt64});
```

**Describe alternatives you've considered**

Maybe `CREATE TABLE FUNCTION` will be better than `CREATE VIEW` for defining it.
But views are created inside databases, while other user-defined objects like UDFs don't belong to databases.
For this reason, `CREATE VIEW` is more natural.

If there is only one query parameter in a view, we can also consider allowing `view_name(value)` instead of `view_name(param_name = value)`.

**Additional context**

This feature will be used for creating custom API handlers from SQL.

**Comment by ramazanpolat** [comment]
Will this work?
```sql
CREATE VIEW test AS 
SELECT * FROM hits LIMIT {lim:UInt64}

SELECT * FROM default.test(lim = 100)
```

**Comment by alexey-milovidov** [comment]
@ramazanpolat yes, your example perfectly fits.

**Comment by ramazanpolat** [comment]
If this feature gets implemented then it will be the next big enhancement after UDF because this opens up a lot of possibilities. But I'm still not conviced to make it only avaliable as VIEW because I think this feature should not be constrained to a database, just like UDFs.

Since CH does not isolate databases and treats databases as table schemas (like `dbo` in MSSQL and `public` in Postgres), views can span to multiple databases. E.g:
```sql
CREATE VIEW  default.my_view AS
SELECT *
FROM default.table1
JOIN test.table2 USING id
```
As you can see, although `default.my_view` belongs to default database, it can also get information from test database.
Therefore, a view belonging to a specific database brings only two outcomes:
1. You can omit the database name when calling.
2. GRANT statements on a database are also applied to VIEWs in the databases (but still needs additional permission if they SELECT from other databases).

Do we really need these 2 outcomes for this feature? Since UDFs don't have the aforementioned outcomes, it is more suitable to use this feature as `TABLE FUNCTION`. My point is, **why not have them both**? When someone needs it as a view, they create it as a `parametric view` under a database. Otherwise they create it as a `table function` which makes it available globally, independent from the database (please also read #40982). Because we certainly may need a table that needs to be independent from a specific database, just like `system.numbers` is available as `numbers()`.

### Possible use cases to use it as a VIEW

1. Restricting access to a table without a WHERE condition so the users always have to use the columns specified in ORDER BY. Will be granting SELECT only on the VIEW:

```sql
CREATE TABLE default.my_big_table
(
  date Date,
  ...
) 
Engine=MergeTree 
ORDER BY (date, asset);

CREATE VIEW default.my_big_table_by_date AS
SELECT * FROM default.my_big_table WHERE date = {date:Date}

SELECT * FROM default.my_big_table_by_date('2022-01-02')
```
2. Multiplexing
```sql
CREATE VIEW test.events AS
SELECT * EXCEPT _table_source FROM (
  SELECT 'foo' as _table_source, event_date, ... FROM foo_events WHERE _table_source = {source:String}
  UNION ALL
  SELECT 'bar' as _table_source, event_date, ... FROM bar_events WHERE _table_source = {source:String}
)

SELECT * FROM test.events(source='foo')
```
### Possible use cases to use it as a TABLE FUNCTION
1. Tables that are independent from databases like `system.numbers`, e.g. `postal_codes`:
```sql
CREATE TABLE FUNCTION postal_code AS
SELECT * EXCEPT _country FROM (
  SELECT 'NL' as _country, code, city, address FROM foo_events WHERE _country = {country: String }
  UNION ALL
  SELECT 'US' as _country, code, city, address FROM foo_events WHERE _country = {country: String }
)
```

2. Getting data from an external data source to make it available to all users and databases. This can make CH a good rest client that hides most of the complexity and private information from users.

```sql
CREATE TABLE FUNCTION coins AS
SELECT * FROM 
url('https://clickhouse.free.beeceptor.com/coins',CSV,'coin String, layer UInt8') 
WHERE layer={layer:UInt8}

SELECT * FROM coins(layer=2)

┌─coin──┬─layer─┐
│ OMG   │     2 │
│ MATIC │     2 │
│ SNX   │     2 │
│ ZRX   │     2 │
│ OP    │     2 │
└───────┴───────┘

CREATE TABLE FUNCTION coin_price AS
SELECT * FROM 
url('https://clickhouse.free.beeceptor.com/coin_price',CSV,'coin String, price Float32')
WHERE coin={coin:String}

SELECT * FROM coin_price('BTC')

┌─coin─┬─────price─┐
│ BTC  │ 123456.78 │
└──────┴───────────┘

```

**Comment by ramazanpolat** [comment]
I know that having a view and a table with the same name is not possible but it is possible to have a table/view and a function with the same name. CH correctly distinguishes between the function and the table/view when parsing a query(which is fascinating):

```sql
CREATE TABLE min
(
    `min` int,
    `max` int,
    `avg` int,
    `sum` int
)
ENGINE = MergeTree ORDER BY tuple()

SELECT
    min(max),
    sum(avg)
FROM min
WHERE (min > 0) AND (avg > 0)

Query id: ea367046-263b-497e-8acb-42e018211f7f

┌─min(max)─┬─sum(avg)─┐
│        0 │        0 │
└──────────┴──────────┘
```
Therefore being able to have this feature as a `table function` would also bring the benefit of having a table and a table function with the same name (not sure if it's possible buecase this is a different thing than the example above) which will allow us writing a query like this:
```sql
CREATE TABLE FUNCTION my_table AS
SELECT * FROM my_table WHERE id = {user: UInt64};

SELECT * FROM my_table;
SELECT * FROM my_table(123);
SELECT * FROM my_table(user=123);
```


Q1: Can we have a VI

**Comment by ramazanpolat** [comment]
What about default values for parameters?

```sql
CREATE [TABLE FUNCTION | VIEW] my_table AS
SELECT * FROM table WHERE {date: Date DEFAULT today()} AND {parent:UInt64 DEFAULT 0}

-- OR with Python style --

CREATE [TABLE FUNCTION | VIEW] my_table AS
SELECT * FROM table WHERE {date: Date = today()} AND {parent:UInt64 = 0}
```

**Comment by ramazanpolat** [comment]
Also, in time, people will be utilizing this feature like this:
```sql
CREATE TABLE FUNCTION table_by_user AS SELECT * FROM table WHERE user = {user: UInt64}
CREATE TABLE FUNCTION table_by_date AS SELECT * FROM table WHERE date = {date: Date}
CREATE TABLE FUNCTION table_by_source AS SELECT * FROM table WHERE source = {source: String}

SELECT * FROM table;
SELECT * FROM table_by_user(123);
SELECT * FROM table_by_date(today());
SELECT * FROM table_by_source('logs');
```
Here we are hitting a problem where programming languages solve it by employing function overloading (multiple dispatch). In strongly typed languages, function overloading uses types of function parameters to correctly pick the desired function. If this would also be the case for CH then the following will work:

```sql
CREATE TABLE FUNCTION table AS SELECT * FROM table WHERE user = {user: UInt64}
CREATE TABLE FUNCTION table AS SELECT * FROM table WHERE id = {id: UInt64}
CREATE TABLE FUNCTION table AS SELECT * FROM table WHERE date = {date: Date}
CREATE TABLE FUNCTION table AS SELECT * FROM table WHERE source = {source: String}

SELECT * FROM table(user=123);
SELECT * FROM table(id=456);
SELECT * FROM table(date=today());
SELECT * FROM table(source='logs');
```

This feature is opening the door to have STORED PROCEDURE for CH in the future. The only thing missing is having multiple statements. Considering the fast evolution of CH, I believe it will not take much time to have it.

**Comment by alexey-milovidov** [comment]
Let's put default and overloading aside, and implement something really primitive first.
