### ISSUE TITLE
How to close the list objects operation when using S3 Table Function with INSERT INTO statement?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#40919]
## Promble
When I use S3 Table Function with INSERT INTO statement:
```sql
INSERT INTO FUNCTION s3('http://localhost:80/bucket-test/test2', 'test1', 'test1', 'TabSeparated', 'col1 String, col2 String, col3 String')
                                    SELECT col1, col2, col3 FROM database.log WHERE notEmpty(col1) LIMIT 100;
```

Then it made the following error:
```text
Received exception from server (version 22.4.4):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: Could not list objects in bucket 'bucket-test' with key 'test2', S3 exception: `AccessDenied`, message: ''. (S3_ERROR)
```

I just need to export the data to the bucket, why do I need the authority of read(list bucket)? Can this settings be closed?

I don't think you need read permission when inserting, because it may be to export data to other users' buckets.

## ClickHouse Version
22.4.4.7

## End
Thanks!

**Comment by tom-clickhouse** [comment]
Did you try to set the `s3_truncate_on_insert` setting to 1?

[Here](https://github.com/ClickHouse/ClickHouse/blob/22.8/src/Storages/StorageS3.cpp#L984) you can see the logic in the C++ code:
- If `s3_truncate_on_insert` is set to 0, and `s3_create_new_file_on_insert` is set to 1, then ClickHouse is checking what files already exist in the bucket (by calling the [checkIfObjectExists](https://github.com/ClickHouse/ClickHouse/blob/22.8/src/Storages/StorageS3.cpp#L552) function), in order to generate a numeric suffix that will be appended to the end of your specified filename.

- If `s3_truncate_on_insert` is set to 1, and `s3_create_new_file_on_insert` is set to 0, then ClickHouse does not need to check what files already exist in the bucket because there is no need to generate a filename with a suffix, instead, your specified filename will be used.

As a reference for this behavior from our [docs](https://clickhouse.com/docs/en/integrations/s3/s3-table-engine/) (it's for the s3 table engine but true also for the s3 table function):
Rows can only be inserted into new files. There are no merge cycles or file split operations. Once a file is written, subsequent inserts will fail. Users have two options here:

- Specify the setting `s3_create_new_file_on_insert=1`. This will cause the creation of new files on each insert. A numeric suffix will be appended to the end of each file that will monotonically increase for each insert operation. For the above example, a subsequent insert would cause the creation of a trips_1.bin file. `for this to work, ClickHouse needs to read what files already exist in the bucket` 

- Specify the setting `s3_truncate_on_insert=1`. This will cause a truncation of the file, i.e. it will only contain the newly inserted rows once complete. `for this to work, ClickHouse does NOT need to read what files already exist in the bucket`

Both of these settings default to 0 - thus forcing the user to set one of them. `s3_truncate_on_insert` will take precedence if both are set.
