### ISSUE TITLE
Dynamic sub columns with Object(json) vs wide-sparse table

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#41059]
Hi,

I have a question about the impact and differences between different approaches to a problem using ClickHouse capabilities. One of the tables in my database needs to store a JSON. There are going to be a lot of keys I know beforehand in the JSON. Either I can create a new column for each key which leads to a wide and sparse table because each row is going to contain only 10 values out of around 800-1000 columns or go with `Object('json')` which I belive infers and automatically creates columns under the hood. My question is does is make any difference in terms of storage and query response time for table with big number of columns? Does `Object('json')` with dynamic sub-columns already includes the necessary optimizations?

**Comment by tom-clickhouse** [comment]
A quick example will make it easier for me to reply:

```
SET allow_experimental_object_type=1;

CREATE TABLE test (
   myColumn Object('json')
)
Engine = MergeTree
ORDER BY tuple()
SETTINGS min_bytes_for_wide_part = 0;

INSERT INTO test VALUES ('{"name": "john", "age": 25}'), ('{"hair-color": "brown"}'), ('{"coordinates": {"long" : 23, "lat": 42}}');
```
(SETTINGS min_bytes_for_wide_part = 0; is just there in order to immediately use the [wide format](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/) for data storage, that would be chosen once the table stores more than [10MB](https://github.com/ClickHouse/ClickHouse/blob/22.8/src/Storages/MergeTree/MergeTreeSettings.h#L30) of data)

The JSON datatype is implemented with nested Tuples:
```
DESCRIBE TABLE test
SETTINGS describe_extend_object_types = 1

Query id: 621fa167-e6a1-4767-b0a5-f93200e54650

┌─name─────┬─type──────────────────────────────────────────────────────────────────────────────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ myColumn │ Tuple(age Int8, coordinates Tuple(lat Int8, long Int8), `hair-color` String, name String) │              │                    │         │                  │                │
└──────────┴───────────────────────────────────────────────────────────────────────────────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```
And all non-Tuple elements within the Tuple(s) like `age Int8`, `lat Int8`, `long Int8`, `hair-color String`, and `name String` are stored on disk in their own compressed column data file each:
```
cd <ClickHouse-data-directory>/test/<current-part-directory>
ls *.bin

myColumn%2Eage.bin			
myColumn%2Ecoordinates%2Elat.bin	
myColumn%2Ecoordinates%2Elong.bin	
myColumn%2Ehair%2Dcolor.bin		
myColumn%2Ename.bin
```

Therefore the above table with the JSON column is equivalent to this table:
```
CREATE TABLE test2 (
  age Int8,
  lat Int8, 
  long Int8, 
  hair-color String, 
  name String
)
Engine = MergeTree
ORDER BY tuple()
```

Both table test and table test2 have the advantage that ClickHouse is only accessing (reading/writing) column files on disk that are required for a specific query - for both queries...
```
SELECT myColumn.age
FROM test 
where myColumn.name = 'john';
```
and 
```
SELECT age
FROM test2 
where name = 'john';
```
...ClickHouse will only read the two-column files that store the age and the name values, but ClickHouse will not touch the other column files that store lat, long, and hair-color values. That means that even if the tables have 1k columns (either directly for table test2 or indirectly in form of 1k different keys contained in the stored JSON values in table test), as long as a specific query is not doing a SELECT *, but instead selects and filters on just a subset of those columns, ClickHouse will also only just touch that subset of data files on disk.

Table test has the advantage, that the schema is automatically extended when rows are inserted that contain new JSON keys.

But, for table test2 you can 
-  choose different codecs and compression algorithms per explicit column.
-  create a (compound) primary key and therefore primary index on some of the explicit columns in order to speed up queries.

You can also do a [hybrid approach](https://clickhouse.com/docs/en/guides/developer/working-with-json/json-semi-structured#adding-primary-keys) and extract specific JSON keys as explicit table columns in order to create a primary index on them for faster queries.

**Comment by tom-clickhouse** [comment]
Hi @sundarv85 
Correct, plus test2 has the advantage that you can directly use some of the columns for a primary key in order to speed up your query execution times, for test1 you would need to [extract](https://clickhouse.com/docs/en/guides/developer/working-with-json/json-semi-structured/#adding-primary-keys) some JSON keys to top-level table columns in order to do the same.

You mentioned 
> a wide and sparse table because each row is going to contain only 10 values out of around 800-1000 columns 

For test2 you would need to either use Nullable columns and fill the majority of columns for each row with NULL which almost always [negatively affects performance](https://clickhouse.com/docs/en/sql-reference/data-types/nullable/) (Nullable column takes more disk space and slow down queries because Nullable creates a separate column of UInt8 type and it has to be processed every time when a user works with this column) or, and this happens automatically also for test1, you would fill the majority of columns for each row with default values, which takes disk space and processing time.

An alternative could be to use a column of type [Map](https://clickhouse.com/docs/en/sql-reference/data-types/map/) instead (and there are some [functions](https://clickhouse.com/docs/en/sql-reference/functions/tuple-map-functions/) for working with maps) :
```
CREATE TABLE test3 (
   myColumn Map(String, String)
)
Engine = MergeTree
ORDER BY tuple();

INSERT INTO test3 VALUES (map('name', 'john', 'age', '25')), (map('hair-color', 'brown')), (map('coordinates_long', '23', 'coordinates_lat', '42'));

SELECT * FROM test3;

Query id: f98892b6-5ff9-425d-afb8-e8e6e992b83c

┌─myColumn─────────────────────────────────────────┐
│ {'name':'john','age':'25'}                       │
│ {'hair-color':'brown'}                           │
│ {'coordinates_long':'23','coordinates_lat':'42'} │
└──────────────────────────────────────────────────┘

3 rows in set. Elapsed: 0.007 sec.
```

**Comment by franchb** [comment]
Thank you, @tom-clickhouse .

Is there any benchmarks or thoughts on performance of `Map` vs `Object` for data object containing ~20-40 keys in one row from range of total ~1000 keys?

**Comment by tom-clickhouse** [comment]
I'm not aware of any benchmark. Technically `Map` is implemented internally as `Array(Tuple(Key, Value))` meaning that there will be two column data files - one for the keys, and one for the values.

Note that, similar to `Object` you can't index a `Map` column.
