### ISSUE TITLE
CREATE   EMPTY AS SELECT  ERROR on 22.8

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#41073]
hello !
when i run 
 create table xx1 empty as select * from xx;

CREATE TABLE xx1 EMPTY AS
SELECT *
FROM xx

Query id: fd018c3a-79db-4fbd-8e34-c893307ce9b6

0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 22.8.4):
Code: 119. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Table engine is not specified in CREATE query. (ENGINE_REQUIRED)

I tried  the table engine of  MergeTree() and Replicated_MergeTree().
all of these engines  i got this error!

what can i do?

**Comment by melvynator** [comment]
Hello

In your example you don't define the engine and you don't specify the primary key. The examples below should be working:

```
CREATE TABLE xx1 
ENGINE=MergeTree() 
ORDER BY number 
EMPTY 
AS
	SELECT *
	FROM numbers(100)
```
	

`CREATE TABLE xx2 Engine=MergeTree() ORDER by number EMPTY AS SELECT * FROM xx1
`

**Comment by yangshike** [comment]
Like mysql, create table xx1 like XX; No engine is specified. InnoDB is created by default

**Comment by melvynator** [comment]
It's a feature we added recently, there is room for improvement. I will make sure these feedbacks are added as feature request.

**Comment by yangshike** [comment]
Especially after upgrading the database engine atomic, replicatedmergetree adopts the default_ replica_ path and default_ replica_ After the name parameter is set, there should be no problem with this creation syntax.

**Comment by tavplubix** [comment]
> However, I think that when creating a new table based on the original table, most users want the structure, sorting, primary key and partition of the original table to be the same.

But in your example a new table is created based on the SELECT query, not on other table. SELECT query has result structure, but does not have engine. And we cannot simple take the storage definition from the table specified in FROM section, because SELECT query may contain UNION or JOIN or subquery and therefore may read from multiple different tables with different storage definitions. That's why you have to specify storage definition explicitly when using `CREATE AS SELECT`. But you can use `CREATE TABLE AS <table>`:
```
CREATE TABLE xx1 AS xx;
```
It will take storage definition from the original table. 
See also `default_table_engine` setting (but it will not completely solve your problem, because *MergeTree requires ORDER BY key which cannot be chosen automatically).

**Comment by yangshike** [comment]
oh thank you，CREATE TABLE AS <table>: Solved my problem。 But I have to enter on cluster XXX every time

When creating a database, atomic and replicated can be specified at the same time
