### ISSUE TITLE
The size of processed data

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [ClickHouse/ClickHouse#41101]
```sql
localhouse :) SELECT * FROM hits WHERE URL LIKE '%google%' ORDER BY EventTime LIMIT 10;
...
10 rows in set. Elapsed: 6.029 sec. Processed 100.00 million rows, 25.45 GB (16.58 million rows/s., 4.22 GB/s.) 

localhost :) SELECT * FROM hits ORDER BY EventTime LIMIT 10 Format Null
...
0 rows in set. Elapsed: 9.844 sec. Processed 100.00 million rows, 82.77 GB (10.16 million rows/s., 8.41 GB/s.)
```

The size of processed data of the first SQL is 25.45 GB which is much less than the second SQL. That looks so cool. Can the primary index used in this case? Or any other magic technology here like deferred materialize? Any docs about this?

**Comment by den-crane** [comment]
There is `PREWHERE` and `optimize_move_to_prewhere`.

Because of optimize_move_to_prewhere =1, CH moves `URL LIKE '%google%'` to PREWHERE.

Because of `PREWHERE URL LIKE '%google%'` CH reads first only URL column filters out granules, and after that reads only that granules to solve remain parts of a query `SELECT *`.

**Comment by Lloyd-Pottiger** [comment]
> There is `PREWHERE` and `optimize_move_to_prewhere`.
> 
> Because of optimize_move_to_prewhere =1, CH moves `URL LIKE '%google%'` to PREWHERE.
> 
> Because of `PREWHERE URL LIKE '%google%'` CH reads first only URL column, filters out granules, and after that reads only that granules to solve remaining parts of a query `SELECT *`.

I get it. Thanks for your clear reply and your excellent work, it is really a wonderful idea.
