### ISSUE TITLE
Indexing by space-filling curves.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#41195]
This task consists of two parts:

## 1. Implement one or a few functions for space-filling curves in SQL.

`zCurve` or `mortonCode` (choose the name more pleasant for you).

It takes an arbitrary number of integer arguments of arbitrary size, and returns UInt64 using the following algorithm:

If the argument is a signed number, convert it to unsigned number of the same width, using zigzag encoding.

If the argument width is less than 32 bits, convert it to UInt32 and shift left, so it will be aligned to the most significant bit.

Iterate over bits of the arguments, starting with the most significant bit. For every bit position, iterate over the arguments, extract the corresponding bit and put it as the bit of the result, starting with the most significant bit of the result.

If all 64 bits of the results were filled, finish the operation.

### Example 1:

Two UInt32 numbers:

```
           bits, <-- most significant -------------- least significant -->
x, UInt32: a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f
y, UInt32: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F

Result:
r, UInt64: a A b B c C d D e E f F g G h H i I j J k K l L m M n N o O p P q Q r R s S t T u U v V w W x X y Y z Z a A b B c C d D e E f F
```

### Example 2: numbers of different width:

```
x, UInt32: a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f
y, UInt8:  A B C D E F G H

Result:
r, UInt64: a A b B c C d D e E f F g G h H i 0 j 0 k 0 l 0 m 0 n 0 o 0 p 0 q 0 r 0 s 0 t 0 u 0 v 0 w 0 x 0 y 0 z 0 a 0 b 0 c 0 d 0 e 0 f 0
```

### Example 3: more than two arguments:

```
x, UInt16: a b c d e f g h i j k l m n o p
y, UInt16: q r s t u v w x y z a b c d e f
z, UInt16: g h i j k l m n o p q r s t u v

r, UInt64: a q g b r h c s i d t j e u k f v l g w m h x n i y o j z p k a q l b r m c s n d t o e u p v f 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

The special case of two numbers can be additionally optimized.
Note that Geo Hash is a special case of Z-order curve, and it can be reviewed as well.

You can also implement Hilbert Curve and Peano Curve if needed.

## 2. Implement index analysis to support ordering by space filling curves.

Let's suppose the user has created a table ordered by some function of multiple arguments:

```
CREATE TABLE t ... ORDER BY f(x1, x2, ...)
```

Let's suppose the function `f` allows to obtain a *preimage of a result range as a union of hyperrectangles in the space of its arguments*.

So, for example, 
if `a <= f(x, y) <= b` (this represents a granule in MergeTree)
then an expression of form `(xa1 <= x <= xb1 AND ya1 <= y <= yb1) OR (xa2 <= x <= xb2 AND ya2 <= y <= yb2) OR ...` can be derived.

(The boundaries can be infinities; the comparison can be strict or non-strict, see `forAnyHyperrectangle` in `KeyCondition.cpp`)

Z-order curve is an example of a function of this kind.
See the picture: https://en.wikipedia.org/wiki/Z-order_curve#/media/File:BIGMIN_search_in_a_Z-order_curve.svg

Add a method to `IFunction` to obtain this preimage. 
Add a method to `IFunction` to check if the function allows to obtain this preimage.

Then simply use these methods in KeyCondition.
See `forAnyHyperrectangle` in `KeyCondition.cpp`

Note: when this index analysis will work, the user will not have to use `zCurve` function in the SELECT query. The user will write a query with conditions on the arguments (x, y) as usual, and the analysis of the space-filling curve will happen under the hood, and automatically skip the granules; while the granules determine the boundaries of the values of `zCurve` on the arguments.

Note: it may sound complicated but it isn't. In fact, we already do this "range preimage" operation on the `tuple` function, by reversing the range of tuple values in lexicographic order.

**Comment by pkit** [comment]
I can implement it using a pretty efficient https://github.com/morton-nd/morton-nd
But it uses `constexpr` and friends to do compile-time specifications. Which means there would be a hard limit on number of dimensions. Is it ok? If ok, then what's the limit? (I would say 8 is a good number, leaves 8 bit per dimension)

**Comment by alexey-milovidov** [comment]
@pkit This is ok.
Yes, 8 is reasonable.

**Comment by alexey-milovidov** [comment]
Looks like a good library :+1: Although I didn't find functions for preimages, there is no requirement on speed, we can implement them ad-hoc.

**Comment by alexey-milovidov** [comment]
Let's name the functions `mortonEncode`, `mortonDecode` (returning tuple).

**Comment by pkit** [comment]
Ok, I think I don't have more questions for now. Will start it.

**Comment by canhld94** [comment]
Recently I've been talking with a colleague about this and came up with a little different solution for Z index analysis as follow:
Assume that we have the table:
```
CREATE TABLE t ... ORDER BY zCurve(x1, x2, x3);
```
Normally, MergeTree engines will create primary index on `zCurve(x1, x2, x3)`. Instead of that, we think we can create **minmax index for each column `x1`, `x2`, `x3`** (data is still sorted by `zCurve(x1, x2, x3)`). So when queries come with any kind of condition on `x1`, `x2`, `x3`, we can use the minmax index to filter marks (no primary index needed).
We think that the approach naturally works, and it's simpler than deriving `x1`, `x2`, `x3` ranges from  `zCurve(x1, x2, x3)` ranges. However, the  drawbacks are:
- We cannot mix `zCurve` with normal ordering keys
- We cannot use the same primary index analysis for Z ordering and normal ordering
- Mark ranges filtering from key conditions for Z index is always O(num_marks_in_part)

@alexey-milovidov @pkit how do you think about this approach? Thanks!

**Comment by canhld94** [comment]
Share another interesting finding that the approach we mentioned above can be simulated w/o any code changes. We did an experiment as follow:
Prepare tables:
```sql
-- Create a normal lexical order table
CREATE TABLE test_pk_lexical
(
    `x` UInt64,
    `y` UInt64,
    `z` UInt64,
    `t` UInt64
)
ENGINE = MergeTree
PRIMARY KEY tuple()
ORDER BY (x, y, z, t);
-- Create a zorder table w. minmax index on each order key and w/o primary keys
CREATE TABLE test_pk_lexical
(
    `x` UInt64,
    `y` UInt64,
    `z` UInt64,
    `t` UInt64
)
ENGINE = MergeTree
PRIMARY KEY tuple()
ORDER BY (x, y, z, t);
-- Make sure 2 tables have same data
INSERT INTO test_pk_lexical SELECT rand(), rand(), rand(), rand() FROM numbers(100000000);
INSERT INTO test_pk_zorder SELECT * FROM test_pk_lexical ORDER BY x, y, z, y;
```
Now let try a select query:
```sql
-- lexical table
localhost :) SELECT * FROM test_pk_lexical where y in (43242, 545) and t in (747348, 3149823) FORMAT Null

SELECT *
FROM test_pk_lexical
WHERE (y IN (43242, 545)) AND (t IN (747348, 3149823))
FORMAT `Null`

Query id: 79b7cd0d-58d6-49d0-b3e0-e6c0f367dd56

Ok.

0 rows in set. Elapsed: 0.090 sec. Processed 100.00 million rows, 800.00 MB (1.11 billion rows/s., 8.84 GB/s.)
--- zorder table
localhost :) SELECT * FROM test_pk_zorder where y in (43242, 545) and t in (747348, 3149823) FORMAT Null

SELECT *
FROM test_pk_zorder
WHERE (y IN (43242, 545)) AND (t IN (747348, 3149823))
FORMAT `Null`

Query id: 8820e49e-c5fd-4869-8ea5-9721c6f7eba5

Ok.

0 rows in set. Elapsed: 0.027 sec. Processed 6.96 million rows, 55.81 MB (259.18 million rows/s., 2.08 GB/s.)
```
With Z index, we got much smaller data to read when having predicate on 2nd sorting column (though this is just a simple PoC). Somehow, we can say that ClickHouse users are able use Z Index now...

**Comment by pkit** [comment]
> Somehow, we can say that ClickHouse users are able use Z Index now...

I think the idea is to not use any index. As indexes interfere with ingestion.
With pre-image support a scanner can reject blocks which do not match the hyperrectangle easily.

**Comment by canhld94** [comment]
Hi @pkit, thanks for your answer, my opinion as below:

> As indexes interfere with ingestion

Yes, there's a trade-off here, we don't need to write primary key, but need to write minmax index for sorting columns.

> I think the idea is to not use any index

I think no matter which index we use, the most important thing is how much data can we skip. In ClickHouse, we have primary index and skip indices, however, primary index can be seen as an minmax index with granule 1 on sorting column(s). Primary index is special because data is sorted **lexicographically** by primary keys, so ClickHouse has a special way to treat them (can evaluate the key condition on a range of marks instead of a single mark). Now moving to z-order, we **change the sorting pattern** , so it's understandable that primary key may not be as special as when using lexical-order.

> With pre-image support a scanner can reject blocks which do not match the hyperrectangle easily

I believe that the minmax index on each sorting column with granule 1 gives us more optimal hyperrectangles than any other index.

Thanks.

**Comment by canhld94** [comment]
Just found out that the example I gave in the above comment was not good, because `rand()` will be evaluated only once, for each row all columns have the same value. So I experimented again, this time, more comprehensively. The main objective of the experiment is:
- Provide a PoC of my idea that we can use the min-max index when data is sorted in z-order instead of the primary key as usual
- Try to give a basic comparison between z-ordering and lexical ordering, and in which case should we use z-ordering

## Create tables
Create a normal table with lexical order
```sql
CREATE TABLE test_pk_lexical
(
    `x` UInt64,
    `y` UInt64,
    `z` UInt64,
    `t` UInt64
)
ENGINE = MergeTree
ORDER BY (x, y, z, t);
```
Create the same table with z-order. For this table, we don't build the primary index, instead, create a min-max index on each sorting column with granularity 1.
```sql
CREATE TABLE test_pk_zorder
(
    `x` UInt64,
    `y` UInt64,
    `z` UInt64,
    `t` UInt64,
    INDEX z_x x TYPE minmax GRANULARITY 1,
    INDEX z_y y TYPE minmax GRANULARITY 1,
    INDEX z_z z TYPE minmax GRANULARITY 1,
    INDEX z_t t TYPE minmax GRANULARITY 1
)
ENGINE = MergeTree
PRIMARY KEY tuple()
ORDER BY mortonEncode(x, y, z, t);
```
Create another table that data is sorted in lexical order, but don't build the primary index and create a min-max index on each sorting column.

The main objective of this table is to confirm that z-order can *organize* (or *cluster*) data in a more efficient way to filter conditions on the 2nd, 3rd, and 4th columns.

```sql
CREATE TABLE test_pk_lexical_minmax
(
    `x` UInt64,
    `y` UInt64,
    `z` UInt64,
    `t` UInt64,
    INDEX z_x x TYPE minmax GRANULARITY 1,
    INDEX z_y y TYPE minmax GRANULARITY 1,
    INDEX z_z z TYPE minmax GRANULARITY 1,
    INDEX z_t t TYPE minmax GRANULARITY 1
)
ENGINE = MergeTree
PRIMARY KEY tuple()
ORDER BY (x, y, z, t);
```

## Performance test: high cardinality data
Insert 200M rows into each table, each column has a cardinality of 100M
```sql
INSERT INTO test_pk_lexical SELECT rand() % 100000000, rand(1) % 100000000, rand(2) % 100000000, rand(3) % 100000000 FROM numbers(200000000);
-- 0 rows in set. Elapsed: 44.074 sec. Processed 200.25 million rows, 1.60 GB (4.54 million rows/s., 36.35 MB/s.)
INSERT INTO test_pk_zorder SELECT * FROM test_pk_lexical ORDER BY x, y, z, y;
-- 0 rows in set. Elapsed: 58.391 sec. Processed 200.00 million rows, 6.40 GB (3.43 million rows/s., 109.61 MB/s.)
INSERT INTO test_pk_lexical_minmax SELECT * FROM test_pk_lexical ORDER BY x, y, z, y;
-- 0 rows in set. Elapsed: 32.539 sec. Processed 200.00 million rows, 6.40 GB (6.15 million rows/s., 196.69 MB/s.)
```
We generate a couple of queries with the following pattern (which is very typical in our business):
```sql
SELECT * FROM test_pk_* WHERE x IN ({}, {}) AND y IN ({}, {}) AND z IN ({}, {}) AND  t in ({}, {}) FORMAT Null;
```
We try to measure the total rows read for each query (not the total amount of data to exclude the `PREWHERE` 's effect). One example below shows that z-order performs worse compared to lexical order:

```sql
SELECT * FROM test_pk_lexical WHERE x IN (77171087, 56426808) AND y IN (45117276, 89947178) AND z IN (80695788, 9393584) AND  t in (91705403, 18502651) FORMAT Null;
-- 0 rows in set. Elapsed: 0.006 sec. Processed 16.38 thousand rows, 131.07 KB (2.90 million rows/s., 23.21 MB/s.)
SELECT * FROM test_pk_zorder WHERE x IN (77171087, 56426808) AND y IN (45117276, 89947178) AND z IN (80695788, 9393584) AND  t in (91705403, 18502651) FORMAT Null;
-- 0 rows in set. Elapsed: 0.080 sec. Processed 63.93 million rows, 511.74 MB (802.12 million rows/s., 6.42 GB/s.)
SELECT * FROM test_pk_lexical_minmax WHERE x IN (77171087, 56426808) AND y IN (45117276, 89947178) AND z IN (80695788, 9393584) AND  t in (91705403, 18502651) FORMAT Null;
-- 0 rows in set. Elapsed: 0.040 sec. Processed 16.38 thousand rows, 319.71 KB (408.61 thousand rows/s., 7.97 MB/s.)
```
I haven't aggregated the result of all queries yet, but overall what I observed was that lexical_minmax performs best, then lexical, and the worst is zorder. Note that z-order performs much worse than lexical ( 63.93 million rows vs 16.38 thousand rows).

What if the condition on the 1st column is not useful? Let's add `NOT` to the first condition:
```sql
SELECT * FROM test_pk_lexical WHERE x NOT IN (77171087, 56426808) AND y IN (45117276, 89947178) AND z IN (80695788, 9393584) AND  t in (91705403, 18502651) FORMAT Null;
-- 0 rows in set. Elapsed: 0.169 sec. Processed 200.00 million rows, 1.60 GB (1.18 billion rows/s., 9.46 GB/s.)
SELECT * FROM test_pk_zorder WHERE x NOT IN (77171087, 56426808) AND y IN (45117276, 89947178) AND z IN (80695788, 9393584) AND  t in (91705403, 18502651) FORMAT Null;
-- 0 rows in set. Elapsed: 0.524 sec. Processed 200.00 million rows, 6.40 GB (381.61 million rows/s., 12.21 GB/s.)
SELECT * FROM test_pk_lexical_minmax WHERE x NOT IN (77171087, 56426808) AND y IN (45117276, 89947178) AND z IN (80695788, 9393584) AND  t in (91705403, 18502651) FORMAT Null;
-- 0 rows in set. Elapsed: 0.580 sec. Processed 200.00 million rows, 6.40 GB (344.78 million rows/s., 11.03 GB/s.)
```
Now both lexical and z-order cannot filter any marks. We test with many queries, and the result is the same.
So our conclusion is: **if sorting keys have high cardinality and most queries are points-based, we shouldn't use z-order at all.**

## Performance test: low cardinality data
The main motivation we study z-order is to improve the query performance in an important business scenario. We examine their table and found that their sorting keys usually have very low cardinality, ranging from 100 to 1000. I think this is a typical scenario, for example, if we want to track the traffic between apps, the table typically will have sorting key `(src_app_id, dst_app_id)`, with both `src_app_id` and `dst_app_id` have cardinality less than 100. So let's make a test with low cardinality.

Insert 200M rows into each table, each column has a cardinality of 200:
```sql
INSERT INTO test_pk_lexical SELECT rand() % 200, rand(1) % 200, rand(2) % 200, rand(3) % 200 FROM numbers(200000000);
-- 0 rows in set. Elapsed: 41.938 sec. Processed 200.25 million rows, 1.60 GB (4.77 million rows/s., 38.20 MB/s.)
INSERT INTO test_pk_zorder SELECT * FROM test_pk_lexical ORDER BY x, y, z, y;
-- 0 rows in set. Elapsed: 40.643 sec. Processed 200.00 million rows, 6.40 GB (4.92 million rows/s., 157.47 MB/s.)
INSERT INTO test_pk_lexical_minmax SELECT * FROM test_pk_lexical ORDER BY x, y, z, y;
-- 0 rows in set. Elapsed: 46.916 sec. Processed 200.00 million rows, 6.40 GB (4.26 million rows/s., 136.41 MB/s.)
```

We run the same query pattern `SELECT * FROM test_pk_* WHERE x IN ({}, {}) AND y IN ({}, {}) AND z IN ({}, {}) AND  t in ({}, {}) FORMAT Null;`. Below is an example:

```sql
SELECT * FROM test_pk_lexical WHERE x IN (62, 170) AND y IN (196, 81) AND z IN (105, 125) AND  t in (84, 127) FORMAT Null;
-- 0 rows in set. Elapsed: 0.008 sec. Processed 229.38 thousand rows, 5.34 MB (30.48 million rows/s., 710.11 MB/s.)
SELECT * FROM test_pk_zorder WHERE x IN (62, 170) AND y IN (196, 81) AND z IN (105, 125) AND  t in (84, 127) FORMAT Null;
-- 0 rows in set. Elapsed: 0.062 sec. Processed 450.56 thousand rows, 12.28 MB (7.28 million rows/s., 198.62 MB/s.)
SELECT * FROM test_pk_lexical_minmax WHERE x IN (62, 170) AND y IN (196, 81) AND z IN (105, 125) AND  t in (84, 127) FORMAT Null;
-- 0 rows in set. Elapsed: 0.034 sec. Processed 90.11 thousand rows, 2.62 MB (2.63 million rows/s., 76.67 MB/s.)
```

Z-order still performs worse than lexical, but this time the gap is not too big as when cardinality is high (450.56 thousand rows vs 229.38 thousand rows,). Lexical sorting with a min-max index on each sorting key gives the best performance.

Now let's add `NOT` to the first condition to make it not useful:

```sql
SELECT * FROM test_pk_lexical WHERE x NOT IN (62, 170) AND y IN (196, 81) AND z IN (105, 125) AND  t in (84, 127) FORMAT Null;
-- 0 rows in set. Elapsed: 0.129 sec. Processed 22.28 million rows, 526.23 MB (172.25 million rows/s., 4.07 GB/s.)
SELECT * FROM test_pk_zorder WHERE x NOT IN (62, 170) AND y IN (196, 81) AND z IN (105, 125) AND  t in (84, 127) FORMAT Null;
-- 0 rows in set. Elapsed: 0.076 sec. Processed 1.27 million rows, 38.49 MB (16.79 million rows/s., 508.77 MB/s.)
SELECT * FROM test_pk_lexical_minmax WHERE x NOT IN (62, 170) AND y IN (196, 81) AND z IN (105, 125) AND  t in (84, 127) FORMAT Null;
-- 0 rows in set. Elapsed: 0.084 sec. Processed 6.91 million rows, 191.13 MB (81.90 million rows/s., 2.27 GB/s.)
```

Finally, we can see the good side of the z-order. When the condition on the 1st sorting key is not useful, z-order still effectively filters more than 99% of data, while lexical order only filters about 90% of data. Lexical sorting with a min-max index on each key is better than normal lexical but still worse than z-order.

Our conclusion is:

- When sorting keys have low cardinality, z-order can be beneficial **if a considerable number of queries doesn't have a predicate on the 1st sorting key**
- There's no free lunch. **With z-order, we increase the skipping effectiveness on 2st, 3rd, and 4nd column, but the skipping effectiveness on the 1st column will be lower than lexical order**. That is, if a query has an effective condition on the 1st column, z-order performs worse than lexical order.

## Conclusion

As I mentioned in a previous comment, no matter which index we use, the most important thing is how much data can we skip. If we can effectively use the min-max index to skip data then we can just use it and bypass the primary index.

Note that even with pre-image support, the experiments and conclusions above are still valid.

**Comment by alexey-milovidov** [comment]
@canhld94 

Let's compare the case when you have a table with:
1. `... INDEX i_x (x) TYPE minmax GRANULARITY 1, INDEX i_y (y) TYPE minmax GRANULARITY 1) ORDER BY (x, y)`
2. `ORDER BY mortonEncode(x, y)`

In the first case, the data is sorted lexicographically by (x, y).
The data for nearby values of `x` is close to each other. You cannot say the same for the data for nearby values of `y`. They might be close to each other if there are long ranges with constant `x`, or randomly distributed if every value of `x` does not repeat. In the latter case, the minmax index by y does not work at all.

In the second case, the data is ordered by a mix of `x` and `y`, almost symmetrical, without a preference of `x` or `y`.
The index analysis will be able to limit the search space if a range of `x` or `y` is provided - in both cases.

That's why we need index analysis for `mortonEncode` - it can work even if minmax index cannot.
I hope @pkit will implement it as a Christmas gift :)

**Comment by alexey-milovidov** [comment]
@pkit Interesting to know about the experiments...

**Comment by pkit** [comment]
@alexey-milovidov nothing much, unfortunately. As you know, we are kinda in turmoil right now. I will update you as soon as I have time. But it's not abandoned in any way.
