### ISSUE TITLE
Improvements on MVs with Simple and non-Simple aggregate functions

### ISSUE THREAD

**Issue by a-dot** [ClickHouse/ClickHouse#41334]
Hello, I'm fairly new to CH and definitely no expert in designing Materialized Views but would like to learn more. I have a source table with telemetry events from our product and want to create a MV to track usage of our product per IP for each hour of each day of the week over a sliding window of 28 days.

I've got a working solution but would appreciate any input to improve my solution.

Storage table and materialized view:

```
CREATE TABLE IF NOT EXISTS events_mv_usage_pattern_storage (
    day Date,
    day_of_week LowCardinality(String),
    hour UInt8,
    ip String,
    count SimpleAggregateFunction(sum, UInt64)
)
ENGINE = AggregatingMergeTree()
PRIMARY KEY ip
ORDER BY (ip, day, hour)
PARTITION BY toYYYYMMDD(day)
TTL day + toIntervalDay(28);

CREATE MATERIALIZED VIEW IF NOT EXISTS events_mv_usage_pattern
TO events_mv_usage_pattern_storage
AS SELECT
    toDate(when) AS day,
    dateName('weekday', when) AS day_of_week,
    client_ip AS ip,
    sumSimpleState(1) AS count
FROM events
GROUP BY when, client_ip;
```

And then I have a view to query the MV:
```
CREATE VIEW IF NOT EXISTS events_v_usage_pattern
AS SELECT
    day_of_week,
    hour,
    ip,
    avg(count) AS avg,
    min(count) AS min,
    max(count) AS max
FROM (
    SELECT
        day_of_week,
        hour,
        ip,
        count
    FROM events_mv_usage_pattern
    FINAL
    GROUP BY day_of_week, hour, ip, count
)
GROUP BY day_of_week, hour, ip
```

As I said, this produces the output that I want, avg/min/max for each hour of each day of the week (Mon-Sun) over the last 28 days. However, would it be possible to do more in the MV and not rely on aggregate functions at query time? Originally I had tried to use an avg AggregateFunction and SimpleAggregateFunctions min and max in the MV but I was running with issues applying the TTL to 28 days to enforce the 28 day sliding window. Any insights on how to do this would be great. Thank you very much for your help!

**Comment by den-crane** [comment]
read this https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

materialized view and source table and destination tables are not related.

materialized view select basically does nothing except transforming inserted rows. In case it can be `select * from events` and it will change nothing.

views like events_v_usage_pattern is counter productive. Use direct queries to events_mv_usage_pattern.

**Comment by a-dot** [comment]
@den-crane no offense (I usually love reading your responses) but you're completely avoiding my question. Thanks for pointing out that the view is counter productive, that's the basis of me asking this question... I'm trying to learn.

Can you answer the question? Is calculating the avg/min/max on a 28-day window for a given IP per day of the week doable through a materialized view that would keep the "State" for the avg over the course of the time window?

**Comment by den-crane** [comment]
> Is calculating the avg/min/max on a 28-day window for a given IP per day of the week doable 
>through a materialized view that would keep the "State" for the avg over the course of the time window?

No it's not possible.

Materialized view does nothing, it's not relevant. 
All magic happens inside the MergeTree (I mention MergeTree on purpose, it does not matter is it AggregatingMergeTree or Summing or ...).

Collapsing/Replacing/calculations of AggregateFunctions/SimpleAggregateFunctions are by-product of the merge process.

MergeTree has an ORDERBY section and during merges it is able to combine several parts into a new single part using this ORDERBY key and only this key.

So for example you have a table `create table t( key Int64, metric Float64 ) Engine = SummingMergeTree order by key`.

And 2 data parts

| part  | key | metric | 
| ---|---|---|
| part1 | 1 | 10 |
| part1 | 2 | 20 |

| part  | key | metric | 
| ---|---|---|
| part2 | 1 | 5 |

Within the merge MergeTree produces a new part and the merge process is very simple and streamable because parts are ordered, you just need to iterate through all participating parts and produce a new combined / ordered rows.

| part  | key | metric | 
| ---|---|---|
| part1-2 | 1 | 15 |
| part1-2 | 2 | 20 |

You don't need to involve other parts in the partition, you don't need to have a knowledge about any other parts. You can insert or merge drop parts in parallel with many rows and the result stays consistent.

Because of this simplicity is only possible one level of groupby. Basically the merge is doing `aggregate group by ORDERBY_KEY`.

**Comment by den-crane** [comment]
BTW check Window view 
https://clickhouse.com/docs/en/sql-reference/statements/create/view/#window-view-experimental
https://altinity.com/blog/battle-of-the-views-clickhouse-window-view-vs-live-view
