### ISSUE TITLE
Unexpected 'column is not under aggregate function and not in GROUP BY' error

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#41402]
The GROUP BY columns which is actually a constant will be optimized and the occurence of the columns after SELECT will be regarded as an error, "column is not under aggregate function and not in GROUP BY".

**How to reproduce**
```SQL
-- throw exception
select col1, multiIf(and(0, col2), -1, 0) as col3 from (select number as col1, number * 2 as col2 from numbers(100)) group by col1, col3;

-- run without any errors
select col1, multiIf(and(1, col2), -1, 0) as col3 from (select number as col1, number * 2 as col2 from numbers(100)) group by col1, col3;
```

**Comment by canhld94** [comment]
I think the reason is current query analyzer does constant folding at expression actions layer but not AST layer. So in AST layer, we still have `multiIf(and(1, col2), -1, 0)` but in expression actions layer, `multiIf(and(1, col2), -1, 0)`  is folded to `0`.

Can provide an adhoc fix by rewriting some logic in `TreeOptimizer::optimizeIf`. However, there's a new query analyzer is being developed here https://github.com/ClickHouse/ClickHouse/pull/41167, so better to wait for it first.
