### ISSUE TITLE
Got an memory allocation error on MaterializedMySQL Replication

### ISSUE THREAD

**Issue by SZDRZ** [ClickHouse/ClickHouse#41606]
ClickHouse version: 22.8.5.29
Machines Memory: 8G
OS: CentOS 7.9
Error Message:  MaterializedMySQLSyncThread: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 4.60 GiB (attempt to allocate chunk of 2147483648 bytes), maximum: 4.00 GiB.OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero.: While executing MySQL: While executing dump MySQL test.bigdata table data. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

Hello! I want to load the data from mysql server to clickhouse but got that memory error. I thought it could be solved by setting max_server_memory_usage, but it didn't work.
Had any idea to fixe that problem?

**Comment by SZDRZ** [comment]
![image](https://user-images.githubusercontent.com/103322931/191435776-87610b2b-688c-40b0-b1bf-c545ad6729e7.png)
This is my config file.

**Comment by den-crane** [comment]
>Memory limit (total) exceeded: would use 4.60 GiB (attempt to allocate chunk of 2147483648 bytes), maximum: 4.00 GiB.

That means that 4.00 GiB is not enough, you need bigger hardware.

Check https://clickhouse.com/docs/en/operations/tips/#ram

## warning

_If your system has less than 16 GB of RAM, you may experience various memory exceptions because default settings do not match this amount of memory. The recommended amount of RAM is 32 GB or more. You can use ClickHouse in a system with a small amount of RAM, even with 2 GB of RAM, but it requires additional tuning and can ingest at a low rate._

**Comment by SZDRZ** [comment]
@den-crane Any ideas to tuning and ingest at a low rate ?

**Comment by SZDRZ** [comment]
By setting max_rows_in_buffer and max_bytes_in_buffer parameter?

**Comment by den-crane** [comment]
>@den-crane Any ideas to tuning and ingest at a low rate ?

It's impossible in this case.
