### ISSUE TITLE
BC check: Unknown Index type 'annoy'

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#41729]
```
2022.09.23 02:46:02.920563 [ 274232 ] {} <Error> Application: Caught exception while loading metadata: Code: 80. DB::Exception: Unknown Index type 'annoy'. Available index types: hypothesis, bloom_filter, tokenbf_v1, ngrambf_v1, set, minmax: Cannot attach table `test_15`.`02354_annoy` from metadata file /var/lib/clickhouse/store/ad1/ad11a090-35e4-4a18-9dd5-2ed9ff4234c1/02354_annoy.sql from query ATTACH TABLE test_15.`02354_annoy` UUID 'cf756b6c-e980-414b-88e0-12e725214223' (`id` Int32, `embedding` Array(Float32), INDEX annoy_index embedding TYPE annoy(100) GRANULARITY 1) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 5. (INCORRECT_QUERY), Stack trace (when copying this message, always include the lines below):
2022.09.23 02:46:04.141045 [ 274232 ] {} <Error> Application: DB::Exception: Unknown Index type 'annoy'. Available index types: hypothesis, bloom_filter, tokenbf_v1, ngrambf_v1, set, minmax: Cannot attach table `test_15`.`02354_annoy` from metadata file /var/lib/clickhouse/store/ad1/ad11a090-35e4-4a18-9dd5-2ed9ff4234c1/02354_annoy.sql from query ATTACH TABLE test_15.`02354_annoy` UUID 'cf756b6c-e980-414b-88e0-12e725214223' (`id` Int32, `embedding` Array(Float32), INDEX annoy_index embedding TYPE annoy(100) GRANULARITY 1) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 5
2022.09.23 02:46:11.505649 [ 274665 ] {} <Error> Application: Caught exception while loading metadata: Code: 80. DB::Exception: Unknown Index type 'annoy'. Available index types: hypothesis, bloom_filter, tokenbf_v1, ngrambf_v1, set, minmax: Cannot attach table `test_15`.`02354_annoy` from metadata file /var/lib/clickhouse/store/ad1/ad11a090-35e4-4a18-9dd5-2ed9ff4234c1/02354_annoy.sql from query ATTACH TABLE test_15.`02354_annoy` UUID 'cf756b6c-e980-414b-88e0-12e725214223' (`id` Int32, `embedding` Array(Float32), INDEX annoy_index embedding TYPE annoy(100) GRANULARITY 1) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 5. (INCORRECT_QUERY), Stack trace (when copying this message, always include the lines below):
```

https://s3.amazonaws.com/clickhouse-test-reports/41699/981c1e95c6f78617e0aa7c9976a900106d88544d/stress_test__ubsan_.html

cc: @FArthur-cmd, @rschu1ze

**Comment by rschu1ze** [comment]
AFAIS, the BC check loads data created by a newer ClickHouse version to check file format downwards compat. Annoy indices (added with #40818) created by the new version are rejected by the old version and as a result, the load fails.

I guess the general question is which behavior is expected in such a situation? 
a) the current behavior, i.e. abort load. The main argument is that Annoy indices can only be created/written by the new version if an experimental cfg param is on.
b) ignore presence of the Annoy index and continue loading. Main argument is that index structures are auxiliary and not necessary for data access.

**Comment by rschu1ze** [comment]
Alright, thanks.

I was not really sure which code states were used in the stress test as old and new versions.

Side question: I saw a "build id" in the logs (search for "[build id:](https://s3.amazonaws.com/clickhouse-test-reports/41699/981c1e95c6f78617e0aa7c9976a900106d88544d/stress_test__ubsan_/clickhouse-server.clean.log)"), it is embedded by the compiler as ELF metadata but different from the Git hash. Do we include the Git hash into the build or can I find the Git hash otherwise for old and new versions?

To reproduce, I first tried a code state which included the Annoy PR as old/new versions. But no combination of creating the index, detaching the table, disabling the annoy cfg flag and re-attaching it could reproduce the issue.

I next tried a code state with the Annoy PR included as new version and a code state without Annoy as old version. To Test, I created the index in the new version, shut the server down and started the new version of the server. That reproduced the problem.

So I guess we are back at my [above question](https://github.com/ClickHouse/ClickHouse/issues/41729#issuecomment-1256203230) 😉 To what degree must the persistence format stay downwards compatible? (let me also ask in our internal channels)

**Comment by tavplubix** [comment]
Seems like `download_release_packets` downloads release build of previous version. Release build creates a table with Annoy index and then ubsan build fails to load this table, because this feature is disabled with ubsan.

```
+ download_release_packets
INFO:root:Will download v22.9.1.2603-stable
Download https://github.com/ClickHouse/ClickHouse/releases/download/v22.9.1.2603-stable/clickhouse-common-static_22.9.1.2603_amd64.deb to previous_release_package_folder/clickhouse-common-static_22.9.1.2603_amd64.deb
Download https://github.com/ClickHouse/ClickHouse/releases/download/v22.9.1.2603-stable/clickhouse-common-static-dbg_22.9.1.2603_amd64.deb to previous_release_package_folder/clickhouse-common-static-dbg_22.9.1.2603_amd64.deb
Download https://github.com/ClickHouse/ClickHouse/releases/download/v22.9.1.2603-stable/clickhouse-server_22.9.1.2603_amd64.deb to previous_release_package_folder/clickhouse-server_22.9.1.2603_amd64.deb
Download https://github.com/ClickHouse/ClickHouse/releases/download/v22.9.1.2603-stable/clickhouse-client_22.9.1.2603_amd64.deb to previous_release_package_folder/clickhouse-client_22.9.1.2603_amd64.deb
+ echo -e 'Download script exit code\tOK'
```

@Avogar, it is expected? (I suppose it's mostly ok to run release build for prev version, because we don't really want to test old version with sanitizers in master)

**Comment by Avogar** [comment]
> @Avogar, it is expected?

Yes, because we download packets for previous release from https://github.com/ClickHouse/ClickHouse/releases and we don't have builds with sanitizers there. Maybe it would be better to use build with same sanitizer but it's not obvious from where to download such packages, AFAIK we create such builds only in CI, so we don't have such place (we can try to download from last commit with corresponding tag, but I guess it's possible that such build report will be already deleted)

**Comment by tavplubix** [comment]
Seems like https://github.com/ClickHouse/ClickHouse/pull/41767 did not help for some reason 
https://s3.amazonaws.com/clickhouse-test-reports/41484/922834ccde612f81ac5da61c72ef2f0afdadd64c/stress_test__ubsan_.html

**Comment by Avogar** [comment]
> Seems like https://github.com/ClickHouse/ClickHouse/pull/41767 did not help for some reason

I guess it's because this test doesn't have this tag in previous release (we take tests from previous release). So we should backport this tag so after next patch release it will work, or we can change stress test a bit and collect all tests with this tag from current commit and add them to skip list. I can try to do it if you think it will be better.

**Comment by tavplubix** [comment]
Backported to 22.9: https://github.com/ClickHouse/ClickHouse/pull/41855
