### ISSUE TITLE
Running clickhouse in docerk, backgroup task always MEMORY_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by fernee** [ClickHouse/ClickHouse#41959]
Machine OS: macOs 12.6
Machine CPU: Apple M1 Pro(ARM Architecture, 8 cores)
Machine Memory: 32G

docker version: 4.12.0 (85629)
docker resources: CPUs: 4; Memory:8.00 GB; Swap:1 GB

container image: clickhouse/clickhouse-server:22.3.8.39
container resources limit: memory: 1024M; cpus: 1

Hello, I'm running clickhouse in docker container for devlopment. after the container started for a while, I got some error logs:
```
 <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMu
tateRuntimeQueue]: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 1.01 GiB (attempt to allocate chunk of 4365959 bytes), maximum: 921.60 MiB. (ME
MORY_LIMIT_EXCEEDED)
```

In clickhosue, there is only very few data, less than 200m.  
First I think it may be clickhosue doesn't supported cgroupv2, so the limit not works. 
Then I set docker cgroup version to v1, and throuth the clickhosue log, it realy worked:
```
<Information> Application: Available RAM: 1.00 GiB; physical cores: 1; logical cores: 4.
```
But I still got the same error. 

Had any idea about this problem?

**Comment by genzgd** [comment]
One quick recommendation, don't ever use swap with ClickHouse.

I don't understand why you didn't think cgroupsv2 was working.  The error you are getting is consistent with ClickHouse not having enough memory to do what it needs to do.  Limiting the memory available to ClickHouse to 1GB is the cause of that error.

1GB is almost certainly not enough memory for the amount of data you are processing and the other settings you have.  Memory is needed for inserts, merges, queries, and in this particular case, it looks like you are trying to run an ALTER TABLE mutation (or possibly a large merge) that needs more than 1GB (at least in connection with other memory usage in the system).

**Comment by fernee** [comment]
@genzgd 
sorry, I should make it clear: cgroupsv2 wasn't working means: in cgroupsv2, clickhosue read the memory amount from the docker resources(in my case, 8.00 GB), not the container limit(1024M). in this situation, clickhosue decide max_server_memory_usage is docker resources ram * max_server_memory_usage_to_ram_ratio(in my case, 8GB * 0.9, much more than container limit 1GB), docker always kill clickhosue contianer because of oom. After some wokring, I figure out I should use cgroupv1 to resolve this promblem.

after I switch to cgroupsv1, docker oom kill don't happened, but I got clickhosue MEMORY_LIMIT_EXCEEDED. I just can not understand, why just startting a clickhouse server with few data need so much memory? we use this clickhouse container settings for develop team members debug our app in local machine, more than 1GB memory for a container is not friendly for some members with small memory machine.

**Comment by fernee** [comment]
@genzgd 
btw, I think these issues are very similar to my issue

#40215
#41465

**Comment by genzgd** [comment]
Okay, I understand better now.  It looks like you are correct that cgroupsv2 limits aren't respected:  https://github.com/ClickHouse/ClickHouse/issues/33865, so that does explain the docker OOM killer.

The basic issue remains, however, that ClickHouse will need a certain amount of memory based on your insert volume, query volume, and the amount of memory needed for background merges and mutations (plus at least the `mark_cache` size).   Each situation is different depending on how ClickHouse is being used, and the "Memory Limit Exceeded" exception means your ClickHouse installation with its current settings can't handle the workload.  That exception indicates that you need to modify the workload and/or the settings related to the tasks ClickHouse is asked to perform.

In your case, it might be possible to run ClickHouse in 1GB, but you almost certainly have to make a number of adjustments to get it to work.  You can find some hints about how to do that here:  https://clickhouse.uptrace.dev/clickhouse/low-memory.html, but even then it's expected you need at least 2GB of memory.

**Comment by genzgd** [comment]
I believe the asynchronous_trace_log resources usage has  been improved in the most recent versions of ClickHouse.

The trace_log is a specialized log for query profiling (https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler), so it seems likely you have various query profiling settings enabled that you may not need.

**Comment by fernee** [comment]
@genzgd thanks once again, I think this question is solved

**Comment by LYJ1999904** [comment]
@genzgd 
We use the ClickHouse container to allow our development team members to debug our application on their local machines. After upgrading to clickhouse/clickhouse-server:22.3.8.39, we encountered an issue where the container cannot start. The error message we receive is:

DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 493.54 MiB (attempt to allocate chunk of 4194306 bytes), maximum: 460.80 MiB. (MEMORY_LIMIT_EXCEEDED)

We attempted to increase the <max_memory_usage> and <max_server_memory_usage> values in both the docker/clickhouse/config.d/config.xml and docker/clickhouse/config.d/users.xml files to 2GB, but the issue still persists. Interestingly, this problem only occurs on Windows systems within our team, while Mac systems work fine."
I think this problem is similar. Can you help me solve it
