### ISSUE TITLE
Add support of Date32 arguments for date_diff function

### ISSUE THREAD

**Issue by rvasin** [ClickHouse/ClickHouse#41977]
**Use case**

Currently date_diff function accepts only Date, DateTime and DateTime64 arguments but it does not support Date32 arguments. 

For example:

`select date_diff('day', toDate32('1979-01-01'), toDate32('1980-01-01'))`

Returns:

> DB::Exception: Second argument for function dateDiff must be Date or DateTime

**Describe the solution you'd like**

Implement support of Date32 arguments.

**Comment by rvasin** [comment]
@rschu1ze and @ilejn could you please comment: will adding support of Date32 arguments create a backward compatibility case? Or is it OK to just implement Date32 support without additional compatibility option?

**Comment by rvasin** [comment]
Created related issue #41978

**Comment by ilejn** [comment]
1. Note, that date_diff handles all combinations of arguments (select date_diff('day', toDate('1979-01-01'), toDateTime('1980-01-01')) and select date_diff('day', toDate('1979-01-01'), toDateTime64('1980-01-01', 3)) work fine). We should keep this level of flexibility for Date32.
2. I cannot make up a code that would be broken if Date32 added as date_diff argument, so I believe that no compatibility considerations make sense here.

**Comment by rschu1ze** [comment]
There might be compatibility issues / unexpected behavior if there was implicit casting between types but that is not the case in ClickHouse. All data type conversions are explicit. So I would not expect any issues with a `date_diff` function that accepts Date32 arguments.

And there was some [earlier discussion](https://github.com/ClickHouse/ClickHouse/pull/40217#issuecomment-1236177537) about the usage of date/time functions as a partitioning clause. I personally don't think that fixing this issue (#41977) will break any such use cases because of the above reason, i.e. the lack of implicit casting in ClickHouse.

**Comment by ilejn** [comment]
To me, the question is if this change **solves** the compatibility issue. 
Do we have reasons to keep _enable_extended_results_for_datetime_functions_ false by default when date_diff can handle Date32?

**Comment by ilejn** [comment]
Apparently we do have reasons to keep _enable_extended_results_for_datetime_functions_  . The list of functions that do not accept Date32 consists not only of date_diff, we should cover dateName and formatDateTime (atl least)

**Comment by rvasin** [comment]
@rschu1ze Could you please share your vision?

As I see in dateDiff.cpp there is the usage of functions like [ToRelativeDayNumImpl](https://clickhouse.com/codebrowser/ClickHouse/src/Functions/DateTimeTransforms.h.html#DB::ToRelativeDayNumImpl) or [ToRelativeWeekNumImpl](https://clickhouse.com/codebrowser/ClickHouse/src/Functions/DateTimeTransforms.h.html#DB::ToRelativeWeekNumImpl) and these functions return UInt16 even for dates before 1970. 
This causes the problems #41978 and #22927.
So in case of adding support of Date32 arguments for date_diff function the problem will persist. 

Right now I see in ClickHouse code ToRelativeDayNumImpl etc is used only  in two places:

1. dateDiff.cpp 
2. in functions calls of toRelativeDayNum itself.

I see two main solutions:

A. For ToRelative*NumImpl family of functions use enable_extended_results_for_datetime_functions option and it should return for example Int32 in extended mode. In this case date_diff will work fine for DateTime64 and Date32 arguments.

B. Use a new set of functions:  To**Extended**Relative*NumImpl which return Int32 for DateTime64 and Date32 arguments. 

Which variant do you think is better? 

Very interesting that @alexey-milovidov closed #22927 as "This is how it is supposed to work.".
Does it mean that in this case variant B is better? We simply implement extended variant of toRelativeDayNum functions?

**Comment by rschu1ze** [comment]
Thanks for the interesting exploratory work.

Not 100% sure if this is your approach A or B, but how about adding `executeExtendedResult` methods to each of the transformations, similar to #41214? E.g. we could have

```cpp
struct ToRelativeMonthNumImpl
{
    // existing methods
    static inline UInt16 execute(Int64 t, const DateLUTImpl & time_zone) {...}
    static inline UInt16 execute(UInt32 t, const DateLUTImpl & time_zone) {...}
    static inline UInt16 execute(Int32 d, const DateLUTImpl & time_zone) {...}
    static inline UInt16 execute(UInt16 d, const DateLUTImpl & time_zone) {...}

   // new methods
   static inline UInt32 executeExtendedResult(Int64 t, const DateLUTImpl & time_zone) {...}
   // etc.
};
```

This will allow to adjust SQL function `date_diff` and the "direct" callers (i.e. SQL functions `toRelative*Num()`) independently. But I guess that in the end, both types of callers should be able to handle extended-precision arguments.

Option B looks a bit more bloated than option A ... it provides the same conversion functions but organizes them in a separate class. I like option A or my proposal better.

(Btw., it would be useful to assemble a checklist of remaining time/date functions which currently don't accept extended-precision date/time arguments, e.g. in the form of a GitHub issue. Once all functions are done, cfg "enable_extended_results_for_datetime_functions" can be turned on.)

About https://github.com/ClickHouse/ClickHouse/issues/22927#issuecomment-816574952: I would say @alexey-milovidov's comment written in 2021 is obsolete as of 2022 where the extended-precision support is much better. As a user, I would expect that `toRelativeDayNum(toDateTime64(...))` with arguments < 1970-01-01 works just fine.

The reference date for functions `toRelative*Num()` should be considered. It is hardcoded and [not documented](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/) as far as I see ("starting from a certain fixed point in the past"). For
- For DateTime arguments, the reference date is 1970-01-01, e.g. `toRelativeDayNum(toDateTime('1970-01-05', 6, 'UTC'))` is `4`
- For DateTime64 arguments, the reference date is 0000-01-01, e.g. `toRelativeDayNum(toDateTime64('1950-01-01', 6, 'UTC'))` is `58231` (likely unintended due to overflow 😉 )

(didn't try out other argument types or `toRelative*Num()` functions)
I think that for DateTime64, it should be 1900-01-01 for consistency with DateTime.

**Comment by rvasin** [comment]
@rschu1ze By variant A I meant what you said: 
add `executeExtendedResult()` methods to all `toRelative*Num()` which are controlled by `enable_extended_results_for_datetime_functions` option the same way as in #41214

> it would be useful to assemble a checklist of remaining time/date functions which currently don't accept extended-precision date/time arguments

Right now I think the following functions don't support Date32 arguments: date_diff, dateName and formatDateTime. I will do more a careful research to find out maybe there are some other functions to add to the list.

**Comment by ilejn** [comment]
Hello, 
how about
1. keep result tyles of ToRelative*NumImpl that we currently have for Date and DateTime
2. extend result types of ToRelative*NumImpl for Date32 and DateTime64
3. make it unconditional, do not use enable_extended_results_for_datetime_functions (or use this flag for DateTime64 only bacause it is currently implemented)
4. be prepared to negative ToRelative*NumImpl results for Date32 or DateTime64, document it
5. introduce Int32 ToRelativeMonthNumImpl::executeExtendedResult (not UInt32)

**Comment by rvasin** [comment]
OK. I will try to summarize the variants listed above:
Variant A:
`Int32 executeExtendedResult() `methods to all toRelative*Num()

Variant B:
Write new functions like toExtendedRelativeNum() which return Int32.

Variant C:
`UInt32  executeExtendedResult()` methods to all toRelative*Num()

In master we have now:

`select toRelativeDayNum(toDate('1970-01-05'))`
4

`select toRelativeDayNum(toDateTime('1970-01-05'))`
4

`select toRelativeDayNum(toDateTime64('1970-01-05', 6))`
4

So re-basing toRelativeDayNum for DateTime64 to 0000-01-01 or 1900-01-01 will create a backward compatibility problem. Should we create a compatibility option such way that it returns
`select toRelativeDayNum(toDateTime64('1970-01-05', 6))`
4
and it the compatibility option is turned on it returns some big number because it's based on 0000-01-01? I think it will complicate the code too much and it will decrease the performance.

While now the documentation says: "starting from a certain fixed point in the past"
In fact it's a wrong statement because already now `toRelativeDayNum` for `DateTime64` is based on 1970-01-01.

Also please consider the implementation of any toRelative*Num for example `ToRelativeYearNumImpl` which is also used in `date_diff`:

Inside we have for example:
```
    static inline UInt16 execute(Int64 t, const DateLUTImpl & time_zone)
    {
        return time_zone.toYear(t);
    }
```
and

`inline Int16 toYear(DateOrTime v) const { return lut[toLUTIndex(v)].year; }`

So toYear returns signed type `Int16`. And the same is true for all other toRelative*Num functions.
For example:
`inline Int32 toRelativeWeekNum(DateOrTime v) const`

All these functions return signed types and only execute() methods return unsinged results.

Thus I think probably variant A is a "less pain" solution and we should simply replace the text:
"starting from a certain fixed point in the past"
with more clear text:
"starting from Unix epoch".

What do you think?

**Comment by rschu1ze** [comment]
Wall of text below, sorry ... it took me a while to think through this mess. There are more things to consider than I first thought. Summary of the current situation in master:

- `date_diff` accepts `Date`, `DateTime` and `DateTime64` arguments but no `Date32`s (--> original issue)

- `toRelativeYearNum()`, `toRelativeQuarterNum()`, `toRelativeMonthNum()`:
  - produce results relative to 0000 for all input data types

- `toRelativeWeek()`, `toRelativeDayNum()`, `toRelativeHourNum()`, `toRelativeMinuteNum()`, `toRelativeSecondNum()`
  - for `Date` and `DateTime`: produce results relative to 1970
  - for `Date32` and `DateTime64`:
     - with arguments >= 1970 produce results relative to 1970
     - with arguments < 1970 produce weird results relative to a fixed base year specific to the function, e.g. 709 for toRelativeWeekNum(), 1791 for toRelativeDayNum() etc. This is caused by an overflow in a returned value.

The documentation of `toRelative*Num()` "starting from a certain fixed point in the past" may have been deliberately unspecific.

I briefly talked to @KochetovNicolai today. Braindump: we concluded there are two cases: a) allowing extended precision arguments (`Date32` / `DateTime64`) for a SQL function that could not handle it before. This creates no backward compatibility issue. b) changing (correcting) the computation for a SQL function that already allows extended precision arguments. This can be problematic for backward compat.

For `date_diff` with `Date32` arguments, we are in a)-territory. For the `toRelative*Num()` functions we are in b)-land. 

About the latter, there are few approaches to avoid breaking existing primary key expressions or partitioning clauses which contain such functions:
1. provide each SQL function twice, in a "correct" and a "legacy" version. This was done for "modulo" and "moduloLegacy" (undocumented, try it out). Depending on a cfg parameter, rewrite the AST / PK expression / partitioning clause from one to the other. An ugly approach, IMHO.
2. Nicolai told me that somewhere in the code, there is a block list of SQL functions which must not be used in PK / partitioning clauses. It includes functions with random results but could include also `toRelative*Num()`. Downside: Limits the user's expressiveness.
3. Dispatch the behavior based on a cfg parameter. We could theoretically re-use `enable_extended_results_for_datetime_functions` for that BUT I would rather propose a new cfg parameter because of two reasons: First, its name refers to case a) above. Second, the existing parameter affects many functions already, we should de-risk by having more than one parameter and not do a big bang in future. Maybe `use_consistent_reference_year_for_toRelativeWeekDayHourMinuteMinuteSecondNum_functions`? Horrendously long but unambiguous.

Okay, where do we go from here?

About @ilejn's proposal:
> keep result tyles of ToRelative*NumImpl that we currently have for Date and DateTime
> extend result types of ToRelative*NumImpl for Date32 and DateTime64
> make it unconditional, do not use enable_extended_results_for_datetime_functions (or use this flag for DateTime64 only bacause it is currently implemented)
> be prepared to negative ToRelative*NumImpl results for Date32 or DateTime64, document it
> introduce Int32 ToRelativeMonthNumImpl::executeExtendedResult (not UInt32)

IIUC, this would break backward compatibility because always using signed return types in `toRelative*Num` will fix the overflow and return the "correct" value unconditionally (see above).

About @rvasin proposal:

> Variant B:
> Write new functions like toExtendedRelativeNum() which return Int32.

Variant B seems too bloated and too difficult to understand from a user POV. And with that variant, someone may get silly ideas like replacing functions in the AST 😉 

> So re-basing toRelativeDayNum for DateTime64 to 0000-01-01 or 1900-01-01 will create a backward compatibility problem. Should we create a compatibility option such way that it returns
> select toRelativeDayNum(toDateTime64('1970-01-05', 6))
> 4

Yes, a compatibility option is definitely needed, e.g. `use_consistent_reference_year_for_toRelativeWeekDayHourMinuteMinuteSecondNum_functions`. But I don't like that 0000 will be the reference year for the fixed version. It should be the lower bound of the respective argument type (1900 or 1970).

> I think it will complicate the code too much and it will decrease the performance.

Well, looking at what I wrote above, only `toRelative(Week|Day|Hour|Minute|Second)Num` with extended precision arguments are affected, all other paths are okay. And it is just one additional `if` that is added.

(In an ideal world, we could go even a bit further and have a cfg parameter `use_consistent_reference_year_for_toRelativeNum_functions` that sets the reference year also for `toRelative(Year|Quarter|Month)` to 1900/1970. Basically, while at it, the behavior could be fixed comprehensively...)

> While now the documentation says: "starting from a certain fixed point in the past"
> In fact it's a wrong statement because already now toRelativeDayNum for DateTime64 is based on 1970-01-01.

That said, 1970 as base year for Date32/DateTime64 (and negative results for inputs < 1970) would also be okay for me. My feeling is that 1900 is more natural and intuitive.

I think your Variant A fits best for 1900 (date32/datetime64) / 1970 (date/datetime) as base years and Variant B fits for 1970 as base year. Any of these would be fine with me.

PS: Please make sure that the result type is able to hold the largest possible offset to the base year (e.g. with the year 2299 as input). E.g. I see that already today, `ToRelativeSecondNumImpl` sometimes returns UInt64 because of that.

**Comment by rvasin** [comment]
@rschu1ze Robert I read your message probably 4 times and it will probably read it even more :) 
What I see that probably it's not idea to touch toRelative* functions at all. These functions maybe used for partition names etc.

For my variant B I want to explain:

Yes, making new public functions toExtendedRelative* available for users it's not a good idea. It will be some kind of bloating as you said. But I meant to make these functions private, not available for users. Even more: maybe put these functions directly into dateDiff.cpp. 

I created the following branch to demonstrate this approach:
https://github.com/arenadata/ClickHouse/tree/ADQM-584

Please take a look. I added Date32 arguments support too.
It works now:

`select date_diff('day', toDate32('1969-12-25'), toDate32('1970-01-05')`

Returns: 11

`select date_diff('day', toDateTime64('1969-12-25 10:00:00.000', 3), toDateTime64('1970-01-05 10:00:00.000', 3)) `

Returns: 11

What do you think about it?

**Comment by rschu1ze** [comment]
I looked at your branch and I think such an approach work as well. It looks quite minimal-invasive actually (good!).

**Comment by rvasin** [comment]
OK. Maybe I will finish this approach the next week (after further reasoning on it).

**Comment by ilejn** [comment]
Roman, do we actually need _execute_ methods besides
Int64 execute(Int64 t, const DateLUTImpl & time_zone)
in ToExtendedRelativeDayNumImpl?
We have good for all TransformDateTime64<Transform> called in vectorVector
so it seems that the argument is Int64 always.

**Comment by ilejn** [comment]
@rvasin   Ok, I am wrong, TransformDateTime64 is about the result, of course, it does not mean that arguments are Int64.

About the idea to split date_diff and ToRelative*Num.
On the one hand, it is tempting. On the other hand, it may be too peculiar if we assume that ToRelative*Num are needed for date_diff.
