### ISSUE TITLE
Benchmark sharding vs s3 vs hdfs disk storage

### ISSUE THREAD

**Issue by ArsenyClean** [ClickHouse/ClickHouse#42030]
Is there any  benchmarks for compare speed for such storages?

**Comment by alexey-milovidov** [comment]
S3 can be both slower and faster in terms of throughput than local storage - it depends on the network speed.
S3 is slower in terms of latency than local storage (a rule of thumb: S3: 100ms, HDD: 10ms, SSD: 1ms), but it can be easily mitigated with the local cache.

We don't have benchmarks for HDFS, but I expect it to be very slow with ClickHouse.
The reason is: we didn't test it, and every optimization for S3 we've made in past years was motivated by performance testing.
