### ISSUE TITLE
Duplicated LLVM submodules

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#42245]
With the update to LLVM 15, which was great, CH now has multiple copies of the same LLVM submodules:

* libunwind: Unwind fork. AFAICT heavily modified.
* libcxx: Only minor differences with libc++ (LLVM 14)
* libcxxabi: Only minor differences with libc++-abi (LLVM 14)
* llvm-project: Has all the submodules (LLVM 15)

I think it'd be way easier to keep things in sync and update properly if at least libcxx, libcxxabi were using the llvm-project submodule code instead. I'm not sure about libunwind since that seems to include lots of changes that might be harder to integrate and keep updated.

**Comment by alexey-milovidov** [comment]
Ok to integrate all the changes inside the single LLVM repository, but the following caveats exist:
1. We need to carefully port every change as a separate commit, otherwise it will be difficult to support.
2. Currently, we have an LLVM submodule optional, but all the rest is mandatory. If we integrate everything inside the LLVM submodule, the checkout will slow down the fast test.

Up to @rschu1ze

**Comment by rschu1ze** [comment]
I have this on my TODO list and in fact yesterday checked how our libcxx(abi) differ from their upstream versions :-)

A single LLVM repository would not save a lot of space compared to what we have now. The main improvement will be that we can use [sane branch management](https://clickhouse.com/docs/en/development/contrib#adding-third-party-libraries) instead of our current messy history. This will simplify future upgrades.

The comment about fast test is a valid one. LLVM checkout takes ca. 1 -2 min for me. Git provides some tricks to further speed that up (shallow, sparse and partial checkouts). Will check if these can be applied to submodules.

**Comment by rschu1ze** [comment]
Just noticed that fast test [checks out](https://github.com/ClickHouse/ClickHouse/blob/151137d6d5c182b752ffaff6c8cbb35e7f72874f/docker/test/fasttest/run.sh#L142) all submodules with `--depth=1`. This is a partial checkout, i.e. only blobs needed for the required Git hash are fetched. This reduces checkout time for llvm-project from ca. 2:03 min to 1:10 min. I also experimented with sparse checkouts but it removes just 5 more secs and is fiddly with submodules.
