### ISSUE TITLE
Flag `is_frozen` of data part is not persistent.

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#42404]
**Describe the unexpected behaviour**
Flag `is_frozen` of data part disapears from `system.parts` table after restarting the server or detaching the table.

**How to reproduce**
```sql
CREATE TABLE test_frozen (id UInt64) ENGINE = MergeTree ORDER BY id;

INSERT INTO test_frozen VALUES (1);

ALTER TABLE test_frozen FREEZE;

SELECT name, is_frozen FROM system.parts WHERE table = 'test_frozen';

┌─name──────┬─is_frozen─┐
│ all_1_1_0 │         1 │
└───────────┴───────────┘

DETACH TABLE test_frozen;
ATTACH TABLE test_frozen;

SELECT name, is_frozen FROM system.parts WHERE table = 'test_frozen';

┌─name──────┬─is_frozen─┐
│ all_1_1_0 │         0 │
└───────────┴───────────┘

```

**Expected behavior**
Flag survives the restart.

**Comment by alexey-milovidov** [comment]
The flag was added for the convenience of a single customer (Yandex).
When we added this flag, the customer was warned about this behavior but confirmed this is ok to them.

In fact, we don't need this flag, and this issue has zero chance to be fixed.

**Comment by azat** [comment]
So maybe it worth to remove the column then?

**Comment by azat** [comment]
Also after So maybe it worth to remove the column then?

Although there are some tests (at least) that needs this flags, i.e. `tests/queries/0_stateless/01414_freeze_does_not_prevent_alters.sql`, but maybe we should convert it to an entry into `system.part_log`?

Also note that after #36424 it became even more complex to address it, since after it you need to match the table with the folder, not only parse partition name from the folder name.
