### ISSUE TITLE
MacOS build with gRPC enabled

### ISSUE THREAD

**Issue by hkrutzer** [ClickHouse/ClickHouse#42490]
**Use case**

I am trying to connect to Clickhouse from Elixir in a way that is fast and allows to stream queries. Unfortunately, both MySQL and Postgres drivers do not work because they expect Mysql/Postgres system tables to be there. Existing Elixir clients use the HTTP interface I don't think can do streaming. The TCP protocol is undocumented.

That leaves gRPC as a decent option, which can be used with Elixir. However, the provided server binary for macOS is not compiled with gRPC. I think this has something to do with cross-compilation? That means everyone who uses macOS would need to compile Clickhouse themselves, if they want to connect via gRPC.

**A clear and concise description of what you want to happen.**
I am unsure what the best route is, but Github Runners can run on macOS. It would be great if those could be used to have a build that includes gRPC, or to achieve this in some other way.

**Comment by alexey-milovidov** [comment]
> The TCP protocol is undocumented.

https://clickhouse.com/docs/en/native-protocol

**Comment by hkrutzer** [comment]
Ah, apologies, I was looking at https://clickhouse.com/docs/en/interfaces/tcp which still says

>Unfortunately, native ClickHouse protocol does not have formal specification yet, but it can be reverse-engineered from ClickHouse source code (starting [around here](https://github.com/ClickHouse/ClickHouse/tree/master/src/Client)) and/or by intercepting and analyzing TCP traffic.

**Comment by rschu1ze** [comment]
Bad news 1: ClickHouse [is only build](https://github.com/ClickHouse/ClickHouse/blob/d85bfe6ea346889680314edfa1bea6c5309ea11e/contrib/grpc-cmake/CMakeLists.txt#L5) with gRPC if `-DENABLE_LIBRARIES` or `-DENABLE_GRPC` is passed to CMake. We currently do neither of that in our non-Linux-on-x86-or-ARM builds (i.e. Darwin, FreeBSD, PowerPC, RISC-V etc.). I think the reasons are a) simplicity, b) keep CI load low, c) not all 3rd party libs work on all OSs/CPUs d) "special builds" are only considered "appetizer" to play around with ClickHouse but not considered production-ready (e.g. functional/performance tests only run on Linux-on-x86/ARM builds). At least to me these reasons make overall sense and I am a bit reluctant to make an exception for gRPC in Darwin.

But after all, gRPC should be enabled in the Linux-x86/ARM builds. Maybe this build is an option to continue Elixir integration?

Bad news 2: I tried to build with gRPC locally using cross-compilation for Darwin on a Linux host, and I got errors. gRPC is doing some non-trivial things in its build which I haven't looked into yet. The problem is that gRPC is one of few remaining 3rd party libs where ClickHouse's build script calls the 3rd party's upstream build script. This will at some point hopefully go away and the build procedure will then be completely different...

**Comment by hkrutzer** [comment]
>But after all, gRPC should be enabled in the Linux-x86/ARM builds. Maybe this build is an option to continue Elixir integration?

Even if it is an option for me personally, everyone who is also using a Mac would also need to run Clickhouse on Linux during development, so I don't see this as an option. It also makes gRPC seem like it's not a good option because it's not available everywhere.

>We currently do neither of that in our non-Linux-on-x86-or-ARM builds (i.e. Darwin, FreeBSD, PowerPC, RISC-V etc.). I think the reasons are a) simplicity

I would argue that cross-compilation itself is a little more complex than compiling on the target platform ;) But I am sure there are good reasons for this setup. 

I did find some good news: there is a build that can be installed with brew over at https://github.com/Altinity/homebrew-clickhouse which does have gRPC enabled. So for me this issue is solved, I'm not sure whether you want to keep this issue open to eventually build with gRPC in the official build.

**Comment by rschu1ze** [comment]
I guess we can put that into the "one fine day" category.
