### ISSUE TITLE
Allow to easily create a user with the same grants as the current user.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#42497]
Or read-only grants to the same set of tables as the current user.
Or write-only grants to the same set of tables as the current user.

Currently, there is no easy way to do it: if the current user is limited by the grants to some subset of tables,
`GRANT ... ON *.*` does not work.

**Comment by vitlibar** [comment]
I thought about adding function `current_grants()` and the supporting syntax `GRANT current_grants() TO username`.
What do you mean by "read-only" or "write-only" grants?

**Comment by alexey-milovidov** [comment]
@vitlibar 

read-only grants: same set of tables but only SELECT
write-only grants: same set of tables but only INSERT

**Comment by alexey-milovidov** [comment]
@vitlibar it's interesting, although it is not a real function, more like a special syntax.
Then better to make it look like this:

```
GRANT CURRENT GRANTS TO username
```

**Comment by tavplubix** [comment]
@pufit, the current error message is misleading: `DB::Exception: default: Not enough privileges. To execute this query, it's necessary to have the grant SELECT ON system.* WITH GRANT OPTION. (ACCESS_DENIED)`
A user may think that the default user doesn't have `GRANT OPTION`, but actually it doesn't have access to one of the system tables. It's not easy to figure out that you need to add `CURRENT` because it's not standard syntax

**Comment by vitlibar** [comment]
`GRANT SELECT ON system.* TO username` - gives `username` the right to `SELECT` from all the `system` database. That command implies the current user has the `SELECT` grant with grant option for all the system database (you can't transfer privileges which you don't have)

`GRANT CURRENT GRANTS(SELECT ON system.*) TO username` - gives `username` the right to `SELECT` from only the tables which the current user is allowed to select from.

**Comment by vitlibar** [comment]
Oh, you're suggesting that the error message should contain some hint about `GRANT CURRENT GRANTS` in addition to that message "Not enough privileges", right?

**Comment by tavplubix** [comment]
I do understand how `GRANT` and `GRANT CURRENT GRANTS` work, and I do understand that it's not possible to grant privileges that you don't have. But it may be not obvious to a user. Yes, I mean that we can improve usability by making the exception message better, because currently the message about `GRANT OPTION` is misleading (the default user has grant options, but it doesn't have access to `system.zookeeper`), and also it's hard to find the `CURRENT GRANTS` if you don't know what to look for.

**Comment by tavplubix** [comment]
Also, how do I revoke all "current grants" I have previously granted?
```
clickhouse-cloud :) REVOKE ALL ON *.* FROM username

REVOKE ALL ON *.* FROM username

Query id: 4cfc3203-d386-41ea-bca1-bc528be039f0


Elapsed: 0.077 sec. 

Received exception from server (version 23.9.2):
Code: 497. DB::Exception: Received from my-hostname.clickhouse-staging.com:9440. DB::Exception: default: Not enough privileges. To execute this query, it's necessary to have the grant SHOW DICTIONARIES, SELECT, INSERT, ALTER, CREATE DATABASE, CREATE TABLE, CREATE DICTIONARY, CREATE TEMPORARY TABLE, CREATE FUNCTION, DROP DATABASE, DROP TABLE, DROP DICTIONARY, DROP FUNCTION, TRUNCATE, OPTIMIZE, KILL QUERY, ACCESS MANAGEMENT, SYSTEM DROP CACHE, SYSTEM RELOAD CONFIG, SYSTEM RELOAD DICTIONARY, SYSTEM RELOAD MODEL, SYSTEM RELOAD FUNCTION, SYSTEM RELOAD EMBEDDED DICTIONARIES, SYSTEM SYNC REPLICA, SYSTEM RESTART REPLICA, SYSTEM SYNC DATABASE REPLICA, SYSTEM FLUSH DISTRIBUTED, SYSTEM FLUSH LOGS, dictGet, INTROSPECTION, URL, REMOTE, MONGO, MYSQL, POSTGRES, S3 ON *.* WITH GRANT OPTION. (ACCESS_DENIED)
```

**Comment by pufit** [comment]
> Also, how do I revoke all "current grants" I have previously granted?

Yes, it is a valid concern. I will implement `REVOKE CURRENT GRANTS ON *.* FROM user`
