### ISSUE TITLE
Error with Parquet file on S3

### ISSUE THREAD

**Issue by darkebe** [ClickHouse/ClickHouse#42506]
When I use S3 function with Parquet file with exact path or wildcard,
I have an error : 
Error: Code: 499. DB::Exception: No response body. (S3_ERROR) (version 22.8.1.1536 (official build)).

If I compress with gzip, it's ok.
If I download the file and use SELECT * FROM file('...','Parquet'), it's ok.

**Comment by alexey-milovidov** [comment]
Parquet format requires HTTP range requests to be read.
If you are using a proxy server for s3 (like Cloudflare) or some alternative s3 provider (other than AWS), the range requests might not be supported correctly and this is the reason for this error.

**Comment by alexey-milovidov** [comment]
A bug in AWS SDK: https://github.com/aws/aws-sdk-cpp/issues/1558

**Comment by alexey-milovidov** [comment]
https://github.com/aws/aws-sdk-cpp/issues/1391

**Comment by CurtizJ** [comment]
Error `No response body` is returned only if another error appeared. So it just hides the real issue.

**Comment by darkebe** [comment]
@alexey-milovidov it's a bug in implementation of aws sdk by Clickhouse or by the S3 provider ?

**Comment by alexey-milovidov** [comment]
Most likely, this is an error in AWS SDK, but it can be reproduced only with alternative S3 implementations.

**Comment by darkebe** [comment]
We find the real issue : 
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'

For Parquet file, we have to specify region in configuration file for each S3 endpoint. Just for parquet file.

The Object Storage provider is Scaleway.

**Comment by bkuschel** [comment]
I've encountered this issues as well and the problem is indeed https://github.com/aws/aws-sdk-cpp/issues/1558. This occurs when the endpoint URL needs a redirect to the actual endpoint, this is usually the case for cross-region endpoints, possibly in non-AWS s3 implementations. `HeadObject` seemingly is unable to handle this (whereas other calls do). 
To get around this I needed to specify the actual s3 region specific endpoint and then it worked.
