### ISSUE TITLE
when CREATE TABLE [IF NOT EXISTS] [db.]table_name AS table_function() there is question

### ISSUE THREAD

**Issue by dazhangzhang** [ClickHouse/ClickHouse#42558]
when CREATE TABLE [IF NOT EXISTS] [db.]table_name AS table_function() there is question
replicas/00 already exists. (REPLICA_IS_ALREADY_EXIST)  
who can tell me how to do thanks !!!

**Comment by e-mars** [comment]
hi @dazhangzhang .
If a table is dropped, ensure that the table is dropped using `ON CLUSTER` if the table was created on several nodes in the cluster.
Drop the table individually from each node in the cluster and to prevent the table from being created with a fixed zookeeper path, use UUID if it's an older version of ClickHouse, otherwise upgrade to newer version and it will uatomatically set UUID for you.
if you were doing tests such as creating and dropping tables, there may be up to an 8 minute latency before the metadata is cleared from zookeeper.
see this:
https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper-uuid/

thanks.
