### ISSUE TITLE
How primary.idx files of multiple partitions stored in memory

### ISSUE THREAD

**Issue by vasonyang** [ClickHouse/ClickHouse#42614]
1、How primary.idx files of multiple partitions stored in memory？
2、if I do not use the partition key as a condition in the where expression, but the order by key column is in the where expression, how clickhouse server works when query?

**Comment by tom-clickhouse** [comment]
- Partitions organize parts, meaning that parts belong to a specific partition.
- Each part (regardless of if partitioning is used or not) has its own primary.idx file.
- Each part that belongs to a partition also has a minmax_{PARTITIONING_KEY_COLUMN}.idx file.

- For a Select query that filters on the partition key, the minmax_{PARTITIONING_KEY_COLUMN}.idx files will be used  to exclude/include parts. In the trace log you will see corresponding entries: 
```
MinMax index condition: (column ... in [..., ...])
Selected 3/15 parts by partition key
```
- For each of the selected parts the part's primary.idx file is loaded into memory, in order to exclude/include granules. In the trace log you will see corresponding entries: 
```
Selected 24/1083 marks by primary key
```

> if I do not use the partition key as a condition in the where expression, but the order by key column is in the where expression, how clickhouse server works when query?

We have a [detailed guide](https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-design) about that in our docs.
