### ISSUE TITLE
Incorrect use of `check_cxx_source_compiles`

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [ClickHouse/ClickHouse#42754]
https://github.com/ClickHouse/ClickHouse/blob/d7d730cc578adb81704a93b8814de4267f9a4b42/cmake/cpu_features.cmake#L105-L281

we use `check_cxx_source_compiles` to check simd Instructions, but it is incorrect.

for a file main.cc:

```cpp
#include <immintrin.h>
int main() {
    auto a = _mm512_setzero_epi32();
    (void)a;
    auto b = _mm512_add_epi16(__m512i(), __m512i());
    (void)b;
    auto c = _mm_cmp_epi8_mask(__m128i(), __m128i(), 0);
    (void)c;
    return 0;
}
```

We can compile successfully using `clang++ main.cc -mavx512f -mavx512bw -mavx512vl -O0 -o main` even without avx512 support on my cpus. But when we run `./main`, it will raise core dump.

```shell
$ clang++ main.cc -mavx512f -mavx512bw -mavx512vl -O0 -o main
$ ./main 
Illegal instruction (core dumped)
```

**Comment by cangyin** [comment]
see #40307

**Comment by cangyin** [comment]
But we cannot compile on CPUs not supporting AVX instruction with AVX feature enabled. During compilation, then compiled `protoc` will crash on AVX instructions, thus interrupts and makes the entire compilation process to fail.

**Comment by Lloyd-Pottiger** [comment]
> But we cannot compile on CPUs not supporting AVX instruction with AVX feature enabled. During compilation, the compiled `protoc` will crash on AVX instructions when generating protocol buffer files with `protoc`, thus interrupts and makes the entire compilation process to fail.
> 
> Please correct me if I am wrong.

Yeah, you are right. But the check do not do anything useful, it can not output some useful message when I compile on CPUs not supporting AVX instruction with AVX feature enabled. I think it is better to find a way can really check the CPU features which we can depend on it to enable advance features.

**Comment by rschu1ze** [comment]
The original issue is answered in #40307.

As for the other problem (https://github.com/ClickHouse/ClickHouse/issues/42754#issuecomment-1304062926), IIUC, there is a problem if 1. the build calls an intermediate generator tool (e.g. protoc, llvm tablegen, possibly there are more) and 2. the build is done on an "old" x86 host w/o support for specific SIMD instruction (e.g. AVX2) for a "new" x86 target with support for these SIMD instructions. I guess/hope this scenario doesn't occur too often in practice.

As a workaround, protobuf can be disabled using `-DENABLE_PROTOBUF=0` or `-DENABLE_LIBRARIES=0` and llvm can be disabled using `-DENABLE_EMBEDDED_COMPILER=0`.

(Actually, since the default x86 build assumes SSE4.2 for the target (and host), the SIMD instructions in question can only be AVX1, AVX2 or the AVX512 variants. Just FYI, these instructions haven't been enforced for the target host due to performance regressions (#40459), but that might happen in future. At least all build/test machines in CI support AVX2 so there won't be a problem.)

The real fix would be to compile the intermediate tools with conservative SIMD flags. Unfortunately, protobuf and llvm are not "bundled" yet, meaning that ClickHouse's CMake scripts currently call into the native CMake script of these external dependencies. It is planned to bundle both until the end of the year (*), and once that is done, we have much more control over the build of these intermediate tools.

(*) Stating this on 2nd Jan gives plenty of time ^^

**Comment by rschu1ze** [comment]
> Yeah, you are right. But the check do not do anything useful, it can not output some useful message when I compile on CPUs not supporting AVX instruction with AVX feature enabled. I think it is better to find a way can really check the CPU features which we can depend on it to enable advance features.

I think you are alluding to the original issue. I'll add some comments (--> #44854).

**Comment by Lloyd-Pottiger** [comment]
I got it, and thanks for your reply which makes it clear.
