### ISSUE TITLE
cutToFirstSignificantSubdomain unexpected behavior

### ISSUE THREAD

**Issue by sepremento** [ClickHouse/ClickHouse#42820]
`cutToFirstSignificantSubdomain` behaves weirdly when working with `.net` links.

**How to reproduce**

* This behavior reproduced in [Clickhouse Playground](https://play.clickhouse.com/play?user=play#U0VMRUNUCiAgJ2FiY2RlLmNsb3VkYXBwLm5ldCcgYXMgZG9tYWluXwogICwgY3V0VG9GaXJzdFNpZ25pZmljYW50U3ViZG9tYWluKGRvbWFpbl8pCiAgLCAnYWJjZGUuY2xvdWRhcHBwLm5ldCcgYXMgZG9tYWluXzIKICAsIGN1dFRvRmlyc3RTaWduaWZpY2FudFN1YmRvbWFpbihkb21haW5fMik=) and on version 22.9.1.2603

```
SELECT
  'abcde.cloudapp.net' as domain_
  , cutToFirstSignificantSubdomain(domain_)
  , 'abcde.cloudappp.net' as domain_2
  , cutToFirstSignificantSubdomain(domain_2)
```

**Expected behavior**

Consistent results with both statements. However `cutToFirstSignificantSubdomain` returns `abcde.cloudapp.net` in the first case and `cloudappp.net` in the second. 

**Additional context**

This bug vanishes with `.org` and `.com` domains and when something else is in the link except `cloudapp`.

**Comment by azat** [comment]
This actually works as intended, since `cloudapp.net` is in the TLD list - https://github.com/ClickHouse/ClickHouse/blob/404a9a0135dcb3480c2b4dcdba7d96b42a2689d0/src/Functions/URL/tldLookup.gperf#L4583

And I would leave this as-is since someone may relay on this behaviour.

But you can use [`cutToFirstSignificantSubdomainCustom`](https://clickhouse.com/docs/en/sql-reference/functions/url-functions/#cuttofirstsignificantsubdomaincustom) instead, that allows you to use your own TLD list. For example from [publicsuffix.org](https://publicsuffix.org/list/public_suffix_list.dat).
