### ISSUE TITLE
Support bitmap_build_agg function

### ISSUE THREAD

**Issue by chenzhx** [ClickHouse/ClickHouse#43208]
**Use case**
Function: base64Encode(bitmapBuild([1, 2, 3, 4, 5]))

**Describe the solution you'd like**
Input : bitmap
Output: String
Description:  Enter an bitmap to return the string form of base64.

**Comment by lhuang09287750** [comment]
Need this function too
Has  anyone already done this, or my buddy would have a try， @vdimir

**Comment by vdimir** [comment]
@chenzhx @lhuang09287750 
Could you please describe use-case a bit, why not use `base64Encode(bitmapBuild(...))` ?

**Comment by chenzhx** [comment]
@vdimir
Function base64Encode only support  string input.
We need a function like base64Encode but it support bitmap input.

**Comment by vdimir** [comment]
We still can convert bitmap to string and apply encode function. We can probably support bitmap argument to base64Encode directly (like already `hex` function does, so if you need _any_ serialization of bitmap you can use `hex` instead of base64). We can't de-serialize bitmap from a raw string (obtained from  `toString(bitmap)`). We can introduce the function `bitmapFromString` and it will probably cover all the use cases. What do you think?


```sql

-- serialization (already works)
SELECT base64Encode(toString(bitmap)); 
SELECT hex(bitmap); 

-- de-serialization
SELECT bitmapFromString( base64Decode( bitmap_encoded ) ); 
SELECT bitmapFromString( unhex( bitmap_hex ) ); 

```

**Comment by lhuang09287750** [comment]
@vdimir thank you，SELECT base64Encode(toString(bitmap));  is what we need
