### ISSUE TITLE
Behavior of 'remote' when remote DB is down

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#43367]
Currently if my remote DB is not working right now, i will get exception.

So, if i have query like:
`select id from remote()
union all
select id from remote()
....
`
I will get exception when one of remote db is down.
It would be great to return nothing from remote query when remote db is not avilable right now.
I think it could be setting for definition of work of 'remote' operation (0 - current behavior, 1 - return nothing when remote db is down)

**Comment by alexey-milovidov** [comment]
Distributed tables have support for this mode of operation with the `skip_unavailable_shards` setting.
But the `remote` table function does not, because it has to obtain the table structure first.

Example:
https://fiddle.clickhouse.com/fa998b35-a942-4d1f-a892-c6f989b224cb
https://fiddle.clickhouse.com/0f4f6798-d824-4ad2-8f33-15cc57d641c6

**Comment by alexey-milovidov** [comment]
I checked the code and figured out that implementing this feature is non-trivial.
