### ISSUE TITLE
Storage policies don't work for `StripeLog` table engine at all

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#43421]
https://pastila.nl/?00ad7b6b/de8e258f58c3483bb8028a627d636398

**Comment by kssenii** [comment]
btw it works with `disk` argument https://github.com/ClickHouse/ClickHouse/blob/3cb202a63b526927a41a7c45e09fb7717b4bdf1e/tests/integration/test_log_family_s3/test.py#L52
https://github.com/ClickHouse/ClickHouse/blob/3cb202a63b526927a41a7c45e09fb7717b4bdf1e/tests/integration/test_log_family_s3/test.py#L55-L81
and looks like storage policy does not work for all log family engines because they all use this method https://github.com/ClickHouse/ClickHouse/blob/3cb202a63b526927a41a7c45e09fb7717b4bdf1e/src/Storages/StorageLogSettings.cpp#L9-L16
which checks only disk setting.

**Comment by alexey-milovidov** [comment]
We can simply select the disk from the storage_policy.
