### ISSUE TITLE
Question about Merge Tree allow-parts-merge Algorithm

### ISSUE THREAD

**Issue by zbtzbtzbt** [ClickHouse/ClickHouse#43734]
Hi, I read about parts merge algorithm, and I have two question:

```
1.lowered_base = interpolateLinear(settings.base = 5, min_base = 2,  ratio) // ratio between [1,2]
               = 5 + (2-5) * ratio
               = 5 -3*ratio
```
when ratio>5/3≈1.67,  **lowered_base will becomes negative num**, this seems unreasonable, **because min base is 2.**

2. In function interpolateLinear, **param min's value(settings.base = 5) is large than max's value(2)**, this seems unreasonable

---
code part:

https://github.com/ClickHouse/ClickHouse/blob/882e5ffd0b30b3fab4c3844ba3ff1fb83a7adaae/src/Storages/MergeTree/SimpleMergeSelector.cpp#L135-L140

https://github.com/ClickHouse/ClickHouse/blob/882e5ffd0b30b3fab4c3844ba3ff1fb83a7adaae/src/Common/interpolate.h#L6-L9

**Comment by filimonov** [comment]
Some reading about that topic
https://github.com/ClickHouse/ClickHouse/blob/882e5ffd0b30b3fab4c3844ba3ff1fb83a7adaae/src/Storages/MergeTree/SimpleMergeSelector.h#L35

Also since the lowered_base is used only in the next line

return (some_positive_number) > lowered_base 

it should not lead to any bad side effects. Do you see any?

**Comment by zbtzbtzbt** [comment]
ok, The logic of the algorithm is fine.
