### ISSUE TITLE
Float compare

### ISSUE THREAD

**Issue by shinlinx** [ClickHouse/ClickHouse#43791]
anybody tell me why? thanks.
### 
![image](https://user-images.githubusercontent.com/37905509/204492638-46bf7520-14c5-4d89-809e-9bfec12d5ed7.png)

**Comment by realyota** [comment]
That's because you convert `0.6` to `Float32` but the right side is actually a `Flota64` and you stumbled across the rounding error (since the comparison is made on exact value). `0.5` does not need any rounding to be performed (no mantissa is being used) so you can compare that number between different Float types. 

Please check how `0.6` is saved in IEEE-754 format: https://www.h-schmidt.net/FloatConverter/IEEE754.html

As you can see the `Float64` has a larger mantissa thus the rounding is bigger and when you compare it to `Float32` you get something like this:

https://baseconvert.com/ieee-754-floating-point
Float32: 0.60000002384185791015625
-- compare to
Float64: 0.59999999999999997779553950749686919152736663818359375

You should study this article: https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html
