### ISSUE TITLE
Code: 60. DB::Exception: Table default.table doesn't exist.

### ISSUE THREAD

**Issue by BrunoAonlineapp** [ClickHouse/ClickHouse#43815]
When performing a delete of the staging table to clean the data already migrated to definitive, it generates an exception in the mutation, I am specifying the name of the table with database.table

TABLE ENGINE = MergeTree

DELETE FROM hmg.table_stg
WHERE (key, item_key) IN (SELECT key, item_key FROM hmg.table)

Code: 60. DB::Exception: Table default.table doesn't exist. (UNKNOWN_TABLE) (version 22.8.6.71 (official build))

**Comment by den-crane** [comment]
I cannot reproduce it https://fiddle.clickhouse.com/998786a1-4c2e-4284-a8e6-f36ef688ac8d

**Comment by kceventus** [comment]
I realize this is a closed ticket, but I've just experienced something similar and have an explanation that might be helpful to someone.

In my case, I tried a Memory/temporary table first, before learning that would not work due to the aforementioned error message. When I changed to a MergeTree table, I still saw the same error, no matter what I tried.

Then I realized that multiple mutations were queued up, and every time I tried a different approach, the oldest mutation continued failing, giving the same error message.

By running a number of KILL MUTATION statements, I cleared the queue, to find that the later attempts worked fine.

**Comment by SMAH1** [comment]
I had same issue but SOLVED.

I have `view` like:
```sql
CREATE OR REPLACE VIEW Metrics_Aggrigate3 AS
....
```

and I query in ClickHouse command line like:
```sql
SELECT * FROM Metrics_Aggrigate2
```
and works.
I ran this code in C#:

```csharp
_linq2db.FromSql<MetricsInRange>("SELECT * FROM Metrics_Aggrigate2");
```

and got ERROR:
```
Code: 60. DB::Exception: Unknown table expression identifier 'Metrics_Aggrigate2' in scope SELECT * FROM Metrics_Aggrigate2. (UNKNOWN_TABLE) (version 24.10.2.80 (official build))
```

### SOLVED
so add `default` to name of view an run:

```csharp
_linq2db.FromSql<MetricsInRange>("SELECT * FROM default.Metrics_Aggrigate2");
```
