### ISSUE TITLE
Cluster configuration password encryption

### ISSUE THREAD

**Issue by pengchuhuai** [ClickHouse/ClickHouse#44030]
I want to use password_sha256_hex password encryption or some other ecryption method . but it is not encrypted

**Comment by den-crane** [comment]
@pengchuhuai it's impossible because clickhouse-server needs a password to connect to another  clickhouse-server .

duplicate https://github.com/ClickHouse/ClickHouse/issues/5441

You can use `secret`,  see https://clickhouse.com/docs/en/engines/table-engines/special/distributed/#distributed-clusters
Or you can use default user with the empty password and restrict access to servers using network settings https://clickhouse.com/docs/en/operations/settings/settings-users/#user-namenetworks .
