### ISSUE TITLE
A problem running Clickhouse container through docker

### ISSUE THREAD

**Issue by kkrgwbj** [ClickHouse/ClickHouse#4406]
(you don't have to strictly follow this form)

**running the error log**
2019.02.15 04:51:50.014038 [ 1 ] {} <Error> Application: Listen [::]: 0: DNS error: EAI: -9  If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>

version:18

i am changing listern_host to 0.0.0.0 also failed.

**Comment by nezed** [comment]
Can you please provide more info about how you are starting container and which docker network configuration is used?

**Comment by filimonov** [comment]
That error just means that ClickHouse can't bind to IPv6 address, as it's disabled, but Clickhouse should work properly using IPv4 only.

If you want to get rid of that error - you should adjust that file in docker:
[/etc/clickhouse-server/config.d/docker_related_config.xml](https://github.com/yandex/ClickHouse/blob/master/docker/server/docker_related_config.xml)

**Comment by filimonov** [comment]
PS. With `listen_try` it rather should not be reported as Error.

**Comment by renatga** [comment]
I do migration from 19.9.2.4 to 19.13.3.26 Clickhouse version and continue see this error. Was it actually fixed? I was thinking to add the file "docker_related_config.xml" as you described upper, but as I see it is already there(what means Dockerfile already included). It is really annoing since those ports (8123, 9000) are very important and  the message like "<Error> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000" makes user worry.  I also should say that when you run docker first time, the application show listen error meesage, but does not show "Ready for connection" in the end of log. In the same time, when you run it second time, the clickhouse shows "<Error> Application: Listen [::]:8123 failed:" and after that show "Information> Application: Listening http://0.0.0.0:8123" (good!) . In both cases clickhouse works fine (thru IPv4), but such messages must be get rid. Please, double check it and fix OR at least change the meesage type to warning.

**Comment by alexey-milovidov** [comment]
@renatga Ok, let's change the log level of this message to warning.
