### ISSUE TITLE
Result of querying on Nullable column is out of expectation

### ISSUE THREAD

**Issue by chenlujjj** [ClickHouse/ClickHouse#44332]
Reproducible Steps:
1.  create table
```
CREATE TABLE t_null(x Int8, y Nullable(Int8)) ENGINE = MergeTree ORDER BY tuple();
```
2. insert some values
```
INSERT INTO t_null VALUES (1, NULL), (2, 3);
```
now the table is

x | y
-- | --
1 | ᴺᵁᴸᴸ
2 | 3

3. try to exclude `y=3`
```
select * from t_null where y != 3
```
But the result is empty, which is out of expectation.

I have checked the doc [Functions for Working with Nullable Values | ClickHouse Docs](https://clickhouse.com/docs/en/sql-reference/functions/functions-for-nulls) and got some workaround ways:
```
select * from t_null where y != 3 OR isNull(y);

select * from t_null where coalesce(y, 0) != 3

select * from t_null where ifNull(y, 0) != 3

select * from t_null where assumeNotNull(y) != 3
```
I'm still wondering if there is a simple way to do this query. Maybe there can be a global setting on query behavior of nullable column.

**Comment by den-crane** [comment]
This is expected behaviour from SQL perspective. You can check it with any other RDBMS: mysql, postgresql, oracle, mssql, ....

Do not use `assumeNotNull` in this case, you may get incorrect results: https://kb.altinity.com/altinity-kb-functions/assumenotnull-and-friends/

https://clickhouse.com/docs/en/sql-reference/functions/functions-for-nulls/#assumenotnull
**In case the original value is NULL the result is undetermined. See also ifNull and coalesce functions.**

**Comment by chenlujjj** [comment]
@den-crane Thanks, I understand the point.
I noticed that in MySQL, there is a NULL-safe equal operator  `<=>` ([MySQL :: MySQL 8.0 Reference Manual :: 12.4.2 Comparison Functions and Operators](https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#operator_equal-to)).
So I can query like this, which is a bit more convenient:
```sql
CREATE TABLE test_null (x int, y int);

INSERT INTO test_null VALUES (1, NULL), (2, 3);

SELECT * FROM test_null WHERE NOT y <=> 3;
```

**Comment by den-crane** [comment]
You can vote https://github.com/ClickHouse/ClickHouse/issues/3889
