### ISSUE TITLE
Memory limit exception when using newer CH versions

### ISSUE THREAD

**Issue by itziklavon** [ClickHouse/ClickHouse#44385]
i have an instance with 2vcpu and 8GB of ram
when i run a query in the format of:
`SELECT
    serviceName,
    quantileMerge(0.99)(quantile) AS p99,
    avgMerge(avg) AS avgDuration,
    sum(count) AS numCalls
FROM signoz_index_aggregated
WHERE (timestamp >= '1671296908') AND (timestamp <= '1671297208') AND (kind = '2')
GROUP BY serviceName
ORDER BY p99 DESC
SETTINGS max_block_size = 2000000000`

if is getting an error:
`Received exception from server (version 22.12.1):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 18.00 GiB (attempt to allocate chunk of 17179869232 bytes), maximum: 9.31 GiB. OvercommitTracker decision: Memory overcommit isn't used. OvercommitTracker isn't set.: While executing ConvertingAggregatedToChunksTransform. (MEMORY_LIMIT_EXCEEDED)`

when running the same query on version 22.8
seems to work fine

**Comment by den-crane** [comment]
Is it the same without `SETTINGS max_block_size = 2000000000` ?

**Comment by itziklavon** [comment]
@den-crane without the settings works well (on both versions)

**Comment by den-crane** [comment]
But it's kinda expected that with ` max_block_size = 2000000000` Clickhouse server uses more memory.
Why do you set this setting?

**Comment by itziklavon** [comment]
we used it as to read the whole result in single bulk(we had issue about 2 years ago without it)
now it seems to be working

just wanted to know what changed?

**Comment by den-crane** [comment]
>we had issue about 2 years ago without it

What issue?

**Comment by den-crane** [comment]
just remove `max_block_size = 2000000000`.

>it read only partial data and not all(using different client, not clickhouse client)

Probably it was bug and this bug has been fixed.

>just wanted to know what changed?

to answer this question need to have the full repro: `create table / insert data ... `

**Comment by harry-hause** [comment]
I am seeing a similar issue on 22.10 but with the default max_block_size. 

Our current setting for one of our nodes is max_block_size: 65409.

For us the issue occurs after a couple weeks of starting the nodes. We then start to sporadically get queries that exceed memory that otherwise wouldn't. I then check the system stats with:

 ```SELECT *, formatReadableSize(value)
FROM system.asynchronous_metrics
WHERE (metric LIKE '%Cach%')
   OR (metric LIKE '%Mem%')
ORDER BY metric ASC FORMAT PrettyCompactMonoBlock;```

And observe these results:

┌─[1mmetric[0m───────────────────────┬───────[1mvalue[0m─┬─[1mformatReadableSize(value)[0m─┐
│ CompiledExpressionCacheBytes │      278528 │ 272.00 KiB                │
│ CompiledExpressionCacheCount │          26 │ 26.00 B                   │
│ HashTableStatsCacheEntries   │         640 │ 640.00 B                  │
│ HashTableStatsCacheHits      │       13024 │ 12.72 KiB                 │
│ HashTableStatsCacheMisses    │        5023 │ 4.91 KiB                  │
│ MMapCacheCells               │           0 │ 0.00 B                    │
│ MarkCacheBytes               │   332700320 │ 317.29 MiB                │
│ MarkCacheFiles               │        4070 │ 3.97 KiB                  │
│ MemoryCode                   │   417927168 │ 398.57 MiB                │
│ MemoryDataAndStack           │ 65660071936 │ 61.15 GiB                 │
│ MemoryResident               │ 29781385216 │ 27.74 GiB                 │
│ MemoryShared                 │   328396800 │ 313.18 MiB                │
│ MemoryVirtual                │ 66641268736 │ 62.06 GiB                 │
│ OSMemoryAvailable            │  2601517056 │ 2.42 GiB                  │
│ OSMemoryCached               │  2686816256 │ 2.50 GiB                  │
│ OSMemoryFreePlusCached       │  3200356352 │ 2.98 GiB                  │
│ OSMemoryFreeWithoutCached    │   513540096 │ 489.75 MiB                │
│ OSMemoryTotal                │ 33242615808 │ 30.96 GiB                 │
│ UncompressedCacheBytes       │           0 │ 0.00 B                    │
│ UncompressedCacheCells       │           0 │ 0.00 B                    │

There are no other running queries after checking with:
`SELECT * FROM system.processes LIMIT 10 FORMAT Vertical;`

It may be unrelated to this issue and I can create a separate issue if needed.
