### ISSUE TITLE
Functions are replacing by its code in SHOW CREATE VIEW in 22.12

### ISSUE THREAD

**Issue by ish1mura** [ClickHouse/ClickHouse#44590]
Hello!

### Describe the issue
We are export database structure to files and commit changes to git.
After upgrade from 22.11 to 22.12 functions missed from `SHOW CREATE VIEW` and replaced by function internal code.
This replacement appears only after view change, not changed views DDL not changing.

### How to reproduce
1 ) Create function:
```sql
CREATE FUNCTION fn_price_group_id AS arg_price_w_nds ->
  multiIf(coalesce(arg_price_w_nds, -1) < 0, 0, arg_price_w_nds > 16000, 16000, toInt16(round(arg_price_w_nds, 0)));
```
2 ) Create view:
```sql
DROP VIEW IF EXISTS default.v_test_view;

CREATE VIEW default.v_test_view AS
SELECT
    t.product_id AS product_id,
    t.price AS price,
    fn_price_group_id(t.price) AS price_group_id
FROM default.t_test AS t;

SELECT * FROM default.v_test_view o
```

3 ) Run:
```sql
SHOW CREATE VIEW default.v_test_view;
-- Same problem in system.tables:
SELECT create_table_query, as_select, * FROM system.tables t WHERE t.engine in ('View') AND t.name = 'v_test_view'
```

4 ) Export result:
![image](https://user-images.githubusercontent.com/16444298/209535024-5094112d-f9ed-4aef-894f-455a683e6a69.png)

### Versions
* Clickhouse `22.12.1.1752` (installed from apt repository)
* Debian 10

**Comment by alexey-milovidov** [comment]
In previous versions, UDFs were not expanded in table definitions, leading to a problem with server startup if a table depends on UDF and UDF depends on another table. This is fixed in https://github.com/ClickHouse/ClickHouse/pull/43539.

It introduced this change in behavior.

It looks unreasonable to provide a compatibility setting for this particular case, 
but it can be considered if there is no workaround and upgrading is not possible otherwise.
