### ISSUE TITLE
test_replicated_users flaky

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#44932]
https://s3.amazonaws.com/clickhouse-test-reports/44853/9756d46ad751aa3d3701e20de24ce55e25038850/integration_tests__tsan__[6/6].html

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/bb8cb829f9a2f51bb8044748b878f718e54aa763/integration_tests__asan__[3/3].html

**Comment by tavplubix** [comment]
Not flaky anymore: [CI DB](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X3JlcGxpY2F0ZWRfdXNlcnMnIEFTIG5hbWVfc3Vic3RyLAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cywKICAgICgnU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBBUyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKU0VMRUNUCiAgICB0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQpHUk9VUCBCWSBkCk9SREVSIEJZIGQgREVTQwo=)

Fixed in https://github.com/ClickHouse/ClickHouse/pull/44978
