### ISSUE TITLE
timezone via http protocol

### ISSUE THREAD

**Issue by hellmany** [ClickHouse/ClickHouse#4548]
Will be great to add support to set TimeZone via HTTP headers for this session (and later use requests with session-id but without this header) for HTTP queries.

Will be great when client set in his profile timezone for stats and without rewriting all queries where dates used with timezone.

**Comment by hellmany** [comment]
Is there any updates on this feature ?

**Comment by alexey-milovidov** [comment]
There are no updates on this feature.

**Comment by zhicwu** [comment]
ClickHouse JDBC driver uses HTTP interface. I didn't find a way to specify client/custom timezone in request, so I had to parse DateTime string returned from server(because we're using TabSeparatedWithNamesAndTypes at this point), and then re-format based using client/custom timezone... Would be great if we can add a stateless header in request to let client to set timezone for server to format datetime or date accordingly(instead of using server/column timezone).

**Comment by zvonand** [comment]
I am working on this in #41197

**Comment by alexey-milovidov** [comment]
This: #44149

**Comment by zvonand** [comment]
Partially solved by #44149 -- it introduced a user-level setting. You can also use it in HTTP.
