### ISSUE TITLE
dateDiff uses mode 1 for week comparisons

### ISSUE THREAD

**Issue by yakkomajuri** [ClickHouse/ClickHouse#45583]
**Describe the unexpected behaviour**

When using `dateDiff`, I'd expect it to use "mode 0" i.e. Sunday-based weeks, given that that's the default elsewhere such as `toStartOfWeek`.

However, it uses "mode 1" i.e. Monday-based weeks.

**How to reproduce**

https://fiddle.clickhouse.com/51453d67-1f73-442f-a84e-7412350e53ad

```sql
-- returns 0
SELECT dateDiff(
    'week',
    toDateTime('2023-01-23 00:00:00', 'UTC'), -- Monday
    toDateTime('2023-01-24 00:00:00', 'UTC')
)

-- returns 1
SELECT dateDiff(
    'week',
    toDateTime('2023-01-22 00:00:00', 'UTC'), 
    toDateTime('2023-01-23 00:00:00', 'UTC') -- Monday
)
```
* Which ClickHouse server version to use
Latest i.e. 22.12.3.5

**Expected behavior**

Ideally I'd like it to either:

a) default to 0 mode
b) allow specifying the mode

_However_, I understand that _a)_ would be a breaking change and _b)_ would be a confusing API, so would certainly be OK with nothing being done here, just expressing my thoughts.

Thanks!

**Comment by den-crane** [comment]
dateDiff uses https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#torelativeweeknum

toRelativeWeekNum does not specify how it calculates WeekNum.
But it seems you are right

```sql
SELECT
    toDate(number) AS x,
    dayOfWeek(x),
    toRelativeWeekNum(x)
FROM numbers(10)
┌──────────x─┬─dayOfWeek(x)─┬─toRelativeWeekNum(x)─┐
│ 1970-01-01 │            4 │                    0 │
│ 1970-01-02 │            5 │                    0 │
│ 1970-01-03 │            6 │                    0 │
│ 1970-01-04 │            7 │                    0 │
│ 1970-01-05 │            1 │                    1 │
│ 1970-01-06 │            2 │                    1 │
│ 1970-01-07 │            3 │                    1 │
│ 1970-01-08 │            4 │                    1 │
│ 1970-01-09 │            5 │                    1 │
│ 1970-01-10 │            6 │                    1 │
└────────────┴──────────────┴──────────────────────┘
```

Probably `toRelativeWeekNum` was implemented years before toStartOfWeek.


BTW, the next release will have `age` function (distance in whole time units)

```sql
SELECT age('week', toDateTime('2023-01-20 00:00:00', 'UTC'), toDateTime('2023-01-23 00:00:00', 'UTC')) AS d
┌─d─┐
│ 0 │
└───┘
```

**Comment by rschu1ze** [comment]
Different countries indeed have different opinions when a week should start (Sun or Mon). For that reason, `mode` arguments continue to be added to some date/time functions (e.g. `toStartOfWeek`, [`toDayOfWeek`](https://github.com/ClickHouse/ClickHouse/pull/45233), [`toWeekOfMonth`](https://github.com/ClickHouse/ClickHouse/issues/44416), ...).

I agree that changing the behavior from an opinionated default (week starts on Mon) to another opinionated default (week starts on Sun) will break existing queries, perhaps even of data if the function was used in a partition clause. And yes, the default are not consistent across functions because the programmers did not put too much thought into it.

Of course, the existing behavior should be documented at least (will do so).

Adding a `mode` to `date_diff` and its cousin function `age` feels awkward to me. Such an argument would only have any meaning if the unit argument is `week`.
