### ISSUE TITLE
DistrDirMonitor thread increase, so cpu high load

### ISSUE THREAD

**Issue by hwangpd** [ClickHouse/ClickHouse#4562]
We've made a cluster of 25 machines, and we're using a destibuted table.

Each equipment produces 20 destibuted tables a day, and data inserts them into the 0 system.
After several days, the number of threads in equipment number zero has increased greatly, and the number of cpu loads has increased.

![2019-03-06](https://user-images.githubusercontent.com/48166616/53857057-270bfa80-4018-11e9-8179-e5f5aeb8ae45.jpeg)

Upon investigation, the DistrDirMonitor thread was increased and gradually occupied the resource.
When we checked the directory (CHDATA/database/table) used in device 0, we found the default@equipment name.

The shard directory had a tmp directory, and it was empty.
That is to say, there was nothing in the file.
In order to eliminate the DistDirMonitor thread, the default@equipment name was deleted
(rm CHDATA/database/table/default*)

However, the number of DistDirMonitor threads remained the same and error logs were generated.
We re-run the CH server on equipment zero, and when we checked, the DistrDirMonitor thread was gone. 
I checked the data, there is no loss.

Question 1.
How do I get rid of the DistrDirMonitor thread after insert into the destibuted table?

Question 2.
Is it OK to remove the DistrDirMonitor thread by deleting the shard directory of the destibuted data directory and re-executing the CH server after insert into the destibuted table? 
Are there no data loss of data?
Is there any other way?

**Comment by blinkov** [comment]
@hwangpd, do you have any further questions?

**Comment by alexey-milovidov** [comment]
CC @azat

**Comment by azat** [comment]
Some basic information is missing, in particular:
- version of the server (and I assume that you do not use distributed storage policy, 5-th argument during `Distributed` creation, since I bet your version is too old and it does not have such setting).
- some server settings, can you please send `select name, value, changed from system.settings where name like '%distributed_directory_monitor%'`

> Each equipment produces 20 destibuted tables a day, and data inserts them into the 0 system.

So you have 20 distributed tables, hence you will have at least 20 additional threads for distributed sends.

> Upon investigation, the DistrDirMonitor thread was increased and gradually occupied the resource.

So you should have some distributed sends in background (possibly lots of them).

> The shard directory had a tmp directory, and it was empty.

tmp directory used only for storing one currently written batch, all pending batches are stored in the per-shard directory, i.e. `CHDATA/database/table/default@equipment` (or something similar in your case)

> That is to say, there was nothing in the file.
> In order to eliminate the DistDirMonitor thread, the default@equipment name was deleted
> (rm CHDATA/database/table/default*)
> However, the number of DistDirMonitor threads remained the same and error logs were generated.

Yes, you need to restart the server (DETACH/rm/ATTACH can be used to avoid restarting).

> We re-run the CH server on equipment zero, and when we checked, the DistrDirMonitor thread was gone.

So this looks like that thread was spinning and don't doing anything useful?
It is not easy to say what was the problem without logs/tracing output/...

> How do I get rid of the DistrDirMonitor thread after insert into the destibuted table?

**They should not consume CPU once the distributed sends has been done**, is it reproducible on your cluster? Can you send some details, i.e. related logs, or/and tracing for that thread, i.e. `strace -s200 -p <thread_id>` but better to use the following `perf trace -t <thread_id>` (since this will not use tricky `ptrace` interface, nevermind, but believe me it is better), where `<thread_id>` is the thread id of that `DistDirMonitor`

*If you are not sure on how to trace the thread, please write, I will try to write some clarifications*

> Is it OK to remove the DistrDirMonitor thread by deleting the shard directory of the destibuted data directory and re-executing the CH server after insert into the destibuted table?

This is not OK, you simply do not need to care about this actually.

> Are there no data loss of data?

Well, if the directory empty there should not be any data loss, *but* this is racy (some parallel INSERT can create a file there)

P.S. Also I want to add there are some fixes in upstream for distributed sends, so you can try to upgrade to the latest stable.

**Comment by azat** [comment]
Silence here, @alexey-milovidov can be closed I guess
