### ISSUE TITLE
insert IPv4 as int32 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#45795]
This commit will produce regression errors while trying to insert UInt32 as IPv4 without ::UInt32 like
INSERT INTO stats_logins (player_id, ip, time) VALUES (52471021, 2319771222, 1675099213);

_Originally posted by @kolya7k in https://github.com/ClickHouse/ClickHouse/issues/43221#issuecomment-1409048315_

**Comment by den-crane** [comment]
```sql
CREATE TABLE users (ip IPv4) ENGINE=Memory;
INSERT INTO users VALUES (2319771222);
DB::Exception: Conversion from UInt64 to IPv4 is not supported:

**Comment by den-crane** [comment]
Though it's a strange idea and it does not work with TSV/CSV/...

**Comment by kolya7k** [comment]
It's not backward incompatibility. Its a real error because it works with ::UInt32
CREATE TABLE users (ip IPv4) ENGINE=Memory;
INSERT INTO users VALUES (2319771222::UInt32);

So inseting IPv4 as UInt32 is absolutelu normal and works almost everywhere and the error here is lost support of UInt64 as IPv4

**Comment by den-crane** [comment]
>is absolutely normal 

IMHO it's not normal. And it's not documented. 
And it did not work with other formats.

**Comment by kolya7k** [comment]
[Its normal and it no way to insert IPv4 ](https://clickhouse.com/docs/en/sql-reference/data-types/domains/ipv4/#ipv4)
first line

**Comment by kolya7k** [comment]
And there is no functions to convert numbers to IPv4 and if you'll try to insert a lot of lines like
INSERT INTO users VALUES (2319771222::UInt32), {100+ lines};
Server will produce same error

**Comment by kolya7k** [comment]
And in the middle of documentation you can find
"Domain values are not implicitly convertible to types other than UInt32"

**Comment by den-crane** [comment]
My biggest concern is:

```
CREATE TABLE users (ip IPv4) ENGINE=Memory;

echo "2319771222" |clickhouse-client -q 'insert into users format CSV'
 DB::Exception: Invalid IPv4 value. (CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING) (version 22.8.13.20
```

**Comment by kolya7k** [comment]
From string, not from Int

**Comment by kolya7k** [comment]
You can insert it in last version by submitting ::UInt32, so the error is when 32-bit integers casts as UInt64 by default

**Comment by kolya7k** [comment]
https://github.com/ClickHouse/ClickHouse/issues/33928

**Comment by den-crane** [comment]
```sql
CREATE TABLE users (ip_ UInt32 EPHEMERAL, ip IPv4 default toIPv4(IPv4NumToString(ip_))) ENGINE=Memory;
INSERT INTO users(ip_) VALUES (2319771222);
select * from users;
┌─ip────────────┐
│ 138.68.230.86 │
└───────────────┘
```

**Comment by kolya7k** [comment]
It is a hack and not works with MaterizlizedMySQL

**Comment by den-crane** [comment]
You know, I am not Clickhouse developer. I am not a member of Clickhouse,inc.
I am nobody. My opinion is irrelevant. But I like to argue.  So let's continue to burn our time.

>not works with MaterizlizedMySQL

MaterizlizedMySQL is experimental hack and will be removed from CH codebase soon (during next 6 months).

>It is a hack and

No, EPHEMERAL is not a hack. The purpose of EPHEMERAL is exactly how I used it.

**Comment by kolya7k** [comment]
Where did you get this information about removal of MaterizlizedMySQL ?

**Comment by den-crane** [comment]
> Where did you get this information about removal of MaterizlizedMySQL ?

https://github.com/ClickHouse/ClickHouse/issues/36563#issuecomment-1107688405

**Comment by yakov-olkhovskiy** [comment]
let me defuse situation a little bit
Recently we moved IP types from domain to native - so all current incompatibilities most likely related to this fact.
Normally we don't want to mix IP types with any other types for numerous reasons - for example not clear endianness in case of integer types. But because previously, since those types were domain, some such operations "leaked out" and were (or could be) used - so, we prefer to support such "features" for backward compatibility.
Now, regarding specifically IPv4 and UInt - currently IPv4 is convertible to/from UInt32 (at least in contexts it suppose to) - for example `toIPv4(2319771222)`. However, apparently, in such insert the default type for integer is UInt64, and conversion to IPv4 would be narrowing (i.e. losing precision) which we would prefer to avoid if possible. However, if we have rational case which negatively impact users we can make an exception and support this feature.
