### ISSUE TITLE
New merge tree engine PR stucked

### ISSUE THREAD

**Issue by youennL-cs** [ClickHouse/ClickHouse#46081]
We’ve been working on PR "[[RFC] Replacing merge tree new engine](https://github.com/ClickHouse/ClickHouse/pull/41005/#top)") for a while and keeping it up to date. As per latests reviews on the open source project, we are not sure whether additional blockers have to be addressed. 

Could you please help clarify the next steps on the PR ?

**Comment by tavplubix** [comment]
Hello, the next step is making tests pass. Currently, Fast Test fails due to build errors, so other tests do not even start:
> Fast test — Cannot build ClickHouse
[Details](https://s3.amazonaws.com/clickhouse-test-reports/41005/86b43f564a8d43e444801866a213384d19c2d271/fast_test.html)

Previously there were some suspicious failures of Integration tests, for example, [test_log_levels_update](https://play.clickhouse.com/play?user=play#d2l0aCAKJ3Rlc3RfbG9nX2xldmVsc191cGRhdGUlJyBhcyBuYW1lX3BhdHRlcm4sCicyMDIyLTA5LTAxJyBhcyBzdGFydF9kYXRlLAooJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgYXMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzCnNlbGVjdCAKdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgcHVsbF9yZXF1ZXN0X251bWJlciBub3QgaW4gCihzZWxlY3QgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwcm4gZnJvbSBjaGVja3Mgd2hlcmUgcHJuIT0wIGFuZCBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIGNoZWNrX25hbWUgaW4gYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSAKYW5kIHRlc3RfbmFtZSBsaWtlIG5hbWVfcGF0dGVybiAKYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj) and [test_codec_encrypted](https://play.clickhouse.com/play?user=play#d2l0aCAKJ3Rlc3RfY29kZWNfZW5jcnlwdGVkJScgYXMgbmFtZV9wYXR0ZXJuLAonMjAyMi0wOS0wMScgYXMgc3RhcnRfZGF0ZSwKKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIGFzIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpzZWxlY3QgCnRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBhcyBkLApjb3VudCgpLCAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlciksIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIHB1bGxfcmVxdWVzdF9udW1iZXIgbm90IGluIAooc2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJuIGZyb20gY2hlY2tzIHdoZXJlIHBybiE9MCBhbmQgc3RhcnRfZGF0ZSA8PSBjaGVja19zdGFydF90aW1lIGFuZCBjaGVja19uYW1lIGluIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykgCmFuZCB0ZXN0X25hbWUgbGlrZSBuYW1lX3BhdHRlcm4gCmFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==) were failing. 

These failures might seem unrelated at the first glance, but accodring to the CI database (see the links above), these tests are not flaky and were not failing in master (`pull_request_number` for merge commits in master is 0), so they were somehow affected by the changes in https://github.com/ClickHouse/ClickHouse/pull/41005. Sorry for not clarifying this earlier, I should have replied to https://github.com/ClickHouse/ClickHouse/pull/41005/#issuecomment-1377358052, but forgot to do it, my bad.
