### ISSUE TITLE
toDecimal64(157/10000, 6) produce 0.015699, while all other number works as expected, is this number any special?

### ISSUE THREAD

**Issue by jasonbigl** [ClickHouse/ClickHouse#46100]
**Describe the unexpected behaviour**
`select toDecimal64(157/10000, 6);` produce `0.015699`, why not 0.0157?

but other numbers works as expected
`select toDecimal64(158/10000, 6);` produce `0.0158`
`select toDecimal64(156/10000, 6);` produce `0.0156`

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 22.9.3 revision 54460

**Expected behavior**
`select toDecimal64(157/10000, 6);` produce `0.0157`

**Additional context**
I found this issue when try to update my table, but found a few unexpected rows when I check the result, and I found all unexpected rows contains **157**

**Comment by shacuros** [comment]
Actually that's correct. It is because of the execution order. at first you are calculating 157/10000 which is a float, then this float will be converted to Decimal64. But as floats are not correct, a little error remains. For other values this will work, for some it won't.
In you case you have to convert to decial64 before doing the division, so it will devide decimal numbers already:

`SELECT
    toDecimal64(157 / 10000, 6),
    CAST(157 / 10000, 'Decimal64(6)'),
    CAST('157', 'Decimal64(6)') / 10000,
    157 / CAST('10000', 'Decimal64(6)')

Query id: 1958c0b7-eaeb-406d-aceb-2134edf254fd

Row 1:
──────
toDecimal64(divide(157, 10000), 6):         0.015699
CAST(divide(157, 10000), 'Decimal64(6)'):   0.015699
divide(CAST('157', 'Decimal64(6)'), 10000): 0.0157
divide(157, CAST('10000', 'Decimal64(6)')): 0.0157
`

**Comment by jasonbigl** [comment]
> Actually that's correct. It is because of the execution order. at first you are calculating 157/10000 which is a float, then this float will be converted to Decimal64. But as floats are not correct, a little error remains. For other values this will work, for some it won't. In you case you have to convert to decial64 before doing the division, so it will devide decimal numbers already:
> 
> ```
> SELECT
>     toDecimal64(157 / 10000, 6),
>     CAST(157 / 10000, 'Decimal64(6)'),
>     CAST('157', 'Decimal64(6)') / 10000,
>     157 / CAST('10000', 'Decimal64(6)')
> 
> Query id: 1958c0b7-eaeb-406d-aceb-2134edf254fd
> 
> Row 1:
> ──────
> toDecimal64(divide(157, 10000), 6):         0.015699
> CAST(divide(157, 10000), 'Decimal64(6)'):   0.015699
> divide(CAST('157', 'Decimal64(6)'), 10000): 0.0157
> divide(157, CAST('10000', 'Decimal64(6)')): 0.0157
> ```

thank you for your explanation
