### ISSUE TITLE
prometheus endpoint for standalone clickhouse-keeper return wrong result and failed to scrape by prometheus with error Get "http://xxx:7000/metrics": EOF

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#46136]
**Describe what's wrong**
Firstly, endpoint return a lot of useless metrics which constantly have zero values and not related to clickhouse-keeper itself

Second, endpoint return last metric without metric name and value only description

```
# HELP ClickHouseAsyncMetrics_jemalloc_background_thread_run_intervals An internal metric of the low-level memory allocator (jemalloc). See https://jemalloc.net/jemalloc.3.html
# TYPE ClickHouseAsyncMetrics_jemalloc_background_thread_run_intervals gauge
ClickHouseAsyncMetrics_jemalloc_background_thread_run_intervals 0
# HELP ClickHouseStatusInfo_DictionaryStatus "Dictionary Status."
# TYPE ClickHouseStatusInfo_DictionaryStatus gauge
```

after it, scraping from `prometheus` failed with follwing error 
```
Get "http://xxx:7000/metrics": EOF
```

**Does it reproduce on recent release?**
Yes, it reproducible with 23.1 and :head-alpine docker images

**How to reproduce**

```bash
git clone https://gist.github.com/b43501dbbf36b95e9b240a924b51328b clickhouse_keeper_metrics
cd clickhouse_keeper_metrics
bash ./repoduce.sh
```

**Comment by antonio2368** [comment]
So the empty description without metric is because we don't have any status set, same thing should happen with CH.
That part is useless for Keeper so you can set `status_info` for prometheus config to `false`.

> Firstly, endpoint return a lot of useless metrics which constantly have zero values and not related to clickhouse-keeper itself

Yes, it was a conscious decision. I split the AsyncMetrics but Metrics and ProfileEvents would require manually specifying parts we would like to have. That's much more work + it's hard to know what is useful and what is not for Keeper so for the initial support I just exposed as much as possible.

What should I get from the `reproduce.sh`? I consistently get correct result.

**Comment by Slach** [comment]
ok. I applied workaround with `<status_info>false</status_info>`

but found `clickhouse-keeper:head-alpine`
close TCP connection with prometheus with RST look screenshot 
![image](https://user-images.githubusercontent.com/105560/217751728-78a67fb5-c372-45b0-9241-8ed1d5d6a718.png)

and attached [prometheus-keeper.pcap.zip](https://github.com/ClickHouse/ClickHouse/files/10694701/prometheus-keeper.pcap.zip)

inside clickhouse-keeper trace log no errors found but this is not clear from logs was requests handled properly or not
```
2023.02.09 07:55:54.698007 [ 14 ] {} <Trace> PrometheusHandler-factory: HTTP Request for PrometheusHandler-factory.
Method: GET, Address: 10.244.0.9:41972, User-Agent: Prometheus/2.41.0, 
Content Type: , Transfer Encoding: identity, X-Forwarded-For: (none)
```
