### ISSUE TITLE
Kafka consumer disconnected (no reconnect then) when brokers got imbalanced

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#4631]
I have encountered this in error log today
```
2019.03.08 21:02:28.282106 [ 89 ] {} <Error> StorageKafka (kafka_source): Consumer error: Local: Broker node update
2019.03.08 21:02:30.283951 [ 47 ] {} <Error> void DB::StorageKafka::streamThread(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration
2019.03.08 21:06:37.267775 [ 869 ] {} <Error> StorageKafka (kafka_source): Consumer error: Broker: Group coordinator load in progress
2019.03.08 21:07:05.347050 [ 39 ] {} <Error> void DB::StorageKafka::streamThread(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration
```

Since then the consumer did not reconnect and consumed no message.I had to drop the Kafka Engine table and create it again. Then it started.

At that time, something happened in my cluster but it's up and running. (graphs are in UTC+1)

![image](https://user-images.githubusercontent.com/327717/54057570-9c7ff280-41f3-11e9-90fc-eea09c90f893.png)

![image](https://user-images.githubusercontent.com/327717/54057591-adc8ff00-41f3-11e9-8058-fee347833304.png)

Any ideas?

**Comment by kmatt** [comment]
I may be seeing a similar issue, where one or two nodes in a four node cluster, all consuming from the same group, fall behind. Only a DROP/CREATE of the Kafka table consumers seems to bring things back in sync for a time:

![image](https://user-images.githubusercontent.com/435936/54078818-099b9280-429d-11e9-8346-5efae263f24b.png)

**Comment by simPod** [comment]
This night it took 4:30h until it auto recovered.

![image](https://user-images.githubusercontent.com/327717/54083746-64c69700-4328-11e9-90a8-a09096e2776e.png)

**Comment by simPod** [comment]
Another observations showed that the time period when the lag is increasing has random length.

**Comment by kmatt** [comment]
Any suggestions on how to diagnose this issue, or where the problem may lie? On v19.3.5 we are currently dropping and recreating consumers to keep ingest balanced:

![image](https://user-images.githubusercontent.com/435936/54767379-6a976480-4bd3-11e9-9bc9-8d7b8c891c69.png)

**Comment by simPod** [comment]
There was no issue on my side for a while but it appeared just now. Meanwhile I tried upgrading to 19.4.1.3 where librdkafka is at v1 RC8 but it's happening there too. For now I have no clue what the cause might be.

**Comment by Junus** [comment]
I got same error `void DB::StorageKafka::streamThread(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration`. Drop Kakfa engine table and recreate help. ClickHouse server version 19.3.7

**Comment by kmatt** [comment]
Testing with message size and reconnect parameters to librdkafka is showing some improvements in my case:

    <kafka>
      <fetch_max_bytes>104857600</fetch_max_bytes>
      <fetch_message_max_bytes>104857600</fetch_message_max_bytes>
      <receive_message_max_bytes>105000000</receive_message_max_bytes>
      <reconnect_backoff_ms>5000</reconnect_backoff_ms>
      <reconnect_backoff_max_ms>60000</reconnect_backoff_max_ms>
    </kafka>

In the last 24 hours my consumption rates have remained balanced across the 4 node cluster.

**Comment by simPod** [comment]
@kmatt 👋 you wrote this 
```
Testing with message size and reconnect parameters to librdkafka is showing some improvements in my case:

<kafka>
  <fetch_max_bytes>104857600</fetch_max_bytes>
  <fetch_message_max_bytes>104857600</fetch_message_max_bytes>
  <receive_message_max_bytes>105000000</receive_message_max_bytes>
  <reconnect_backoff_ms>5000</reconnect_backoff_ms>
  <reconnect_backoff_max_ms>60000</reconnect_backoff_max_ms>
</kafka>
In the last 24 hours my consumption rates have remained balanced across the 4 node cluster.
```
I suppose the test was unsucessful? :)

**Comment by kmatt** [comment]
@simPod Correct - behavior returned shortly after I posted that message. Still looking at librdkafka parameters, currently heartbeat and timeout.

**Comment by simPod** [comment]
It is related to under-replicated partitions I believe

![image](https://user-images.githubusercontent.com/327717/55367284-9af0d400-54ec-11e9-90e8-bb31d054314d.png)

It started the same time the unde rreplication ocurred

**Comment by simPod** [comment]
Shouldn't we have [rebalance cb](https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_consumer_example.cpp#L232)?

@vavrusa you have implemented Kafka engine. If I may ask, is it forgotten or there's a reason for it [not to be present](https://github.com/yandex/ClickHouse/search?q=rebalance&type=Code) in ClickHouse code? Thanks!

**Comment by simPod** [comment]
But maybe it's implemented through cppkafka https://github.com/mfontanini/cppkafka/blob/4a887607b356eeef715306d442242d3a8d55c13e/src/consumer.cpp#L316

**Comment by matthew-formosa-gig** [comment]
We encountered the same issue and we experienced some data loss around the time of disconnection.

**Comment by abyss7** [comment]
Please, increase the verbosity of rdkafka in server config:
```
<kafka>
    <debug>all</debug>
</kafka>
```

So I can understand what is really happening from the client point of view.

**Comment by simPod** [comment]
I had to stabilize production solution so I dropped all kafka engine consumers, replaced by java consumer-inserters. Unfortunately, I can no longer help with this then 😞

**Comment by vezir** [comment]
I updated CH from 19.5.3.8 to 19.6.2.11 and at the same time i cleaned some kafka related table manualy because drop didnt work. May be different case but then I got same error
 
`void DB::StorageKafka::streamThread(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration, version = 19.6.2.11 (official build)`

with these lines

`2019.05.22 09:39:53.839818 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.839903 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840067 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840203 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840362 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840457 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840534 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840620 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840729 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840790 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.840949 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.841043 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.841133 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.841257 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.841417 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
2019.05.22 09:39:53.841582 [ 26 ] {} <Trace> StorageKafka (udpLogs): Re-joining claimed consumer after failure
`

and set `<debug>all</debug>` but i did not notice any difference in the logs.
The syslogs contains the logs below;

`May 22 09:38:10 bigdata22 clickhouse-server[29851]: %5|1558507090.764|REQTMOUT|ClickHouse 19.6.2.11#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5043ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 57453ms
May 22 09:38:10 bigdata22 clickhouse-server[29851]: %4|1558507090.765|REQTMOUT|ClickHouse 19.6.2.11#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 09:38:10 bigdata22 clickhouse-server[29851]: %3|1558507090.766|FAIL|ClickHouse 19.6.2.11#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 6007ms in state UP)
May 22 09:38:10 bigdata22 clickhouse-server[29851]: %3|1558507090.766|ERROR|ClickHouse 19.6.2.11#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 6007ms in state UP)
May 22 09:38:10 bigdata22 clickhouse-server[29851]: %5|1558507090.914|REQTMOUT|ClickHouse 19.6.2.11#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5191ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 56618ms
May 22 09:38:10 bigdata22 clickhouse-server[29851]: %4|1558507090.915|REQTMOUT|ClickHouse 19.6.2.11#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 09:38:10 bigdata22 clickhouse-server[29851]: %3|1558507090.915|FAIL|ClickHouse 19.6.2.11#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 7007ms in state UP)
May 22 09:38:10 bigdata22 clickhouse-server[29851]: %3|1558507090.916|ERROR|ClickHouse 19.6.2.11#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 7007ms in state UP)
May 22 09:38:11 bigdata22 snmpd[10470]: Connection from UDP: [213.155.98.45]:64970->[10.58.0.67]:161
May 22 09:38:11 bigdata22 clickhouse-server[29851]: %5|1558507091.325|REQTMOUT|ClickHouse 19.6.2.11#consumer-16| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5602ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 56209ms
May 22 09:38:11 bigdata22 clickhouse-server[29851]: %4|1558507091.325|REQTMOUT|ClickHouse 19.6.2.11#consumer-16| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 09:38:11 bigdata22 clickhouse-server[29851]: %3|1558507091.325|FAIL|ClickHouse 19.6.2.11#consumer-16| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 7008ms in state UP)
May 22 09:38:11 bigdata22 clickhouse-server[29851]: %3|1558507091.325|ERROR|ClickHouse 19.6.2.11#consumer-16| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 7008ms in state UP)
May 22 09:38:11 bigdata22 clickhouse-server[29851]: %5|1558507091.664|REQTMOUT|ClickHouse 19.6.2.11#consumer-14| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5944ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 54867ms
May 22 09:38:11 bigdata22 clickhouse-server[29851]: %4|1558507091.664|REQTMOUT|ClickHouse 19.6.2.11#consumer-14| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 09:38:11 bigdata22 clickhouse-server[29851]: %3|1558507091.664|FAIL|ClickHouse 19.6.2.11#consumer-14| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 9009ms in state UP)
May 22 09:38:11 bigdata22 clickhouse-server[29851]: %3|1558507091.664|ERROR|ClickHouse 19.6.2.11#consumer-14| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 9009ms in state UP)`

**Comment by vezir** [comment]
I changed my kafka related settings with;

`    <kafka>
       <fetch_max_bytes>104857600</fetch_max_bytes>
       <fetch_message_max_bytes>104857600</fetch_message_max_bytes>
       <receive_message_max_bytes>105000000</receive_message_max_bytes>
       <max_poll_interval_ms>300000</max_poll_interval_ms>
       <session_timeout_ms>10000</session_timeout_ms>
       <heartbeat_interval_ms>3000</heartbeat_interval_ms>
       <reconnect_backoff_ms>5000</reconnect_backoff_ms>
       <reconnect_backoff_max_ms>60000</reconnect_backoff_max_ms>
    </kafka>`

and restart CH and it works now. If any error occurs i ll let you know.

**Comment by vezir** [comment]
Hi, the error occured again.

the logs are below;

`May 22 11:09:34 bigdata22 clickhouse-server[31808]: %5|1558512574.943|REQTMOUT|ClickHouse 19.6.2.11#consumer-15| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5220ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 296462ms
May 22 11:09:34 bigdata22 clickhouse-server[31808]: %4|1558512574.943|REQTMOUT|ClickHouse 19.6.2.11#consumer-15| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 11:09:34 bigdata22 clickhouse-server[31808]: %3|1558512574.944|FAIL|ClickHouse 19.6.2.11#consumer-15| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 9010ms in state UP)
May 22 11:09:34 bigdata22 clickhouse-server[31808]: %3|1558512574.944|ERROR|ClickHouse 19.6.2.11#consumer-15| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 9010ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %5|1558512575.419|REQTMOUT|ClickHouse 19.6.2.11#consumer-8| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5695ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 291800ms
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %4|1558512575.419|REQTMOUT|ClickHouse 19.6.2.11#consumer-8| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.419|FAIL|ClickHouse 19.6.2.11#consumer-8| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 31032ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.419|ERROR|ClickHouse 19.6.2.11#consumer-8| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 31032ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %5|1558512575.429|REQTMOUT|ClickHouse 19.6.2.11#consumer-5| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5705ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 291790ms
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %4|1558512575.429|REQTMOUT|ClickHouse 19.6.2.11#consumer-5| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.429|FAIL|ClickHouse 19.6.2.11#consumer-5| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 15014ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.429|ERROR|ClickHouse 19.6.2.11#consumer-5| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 15014ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %5|1558512575.502|REQTMOUT|ClickHouse 19.6.2.11#consumer-24| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5779ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 291717ms
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %4|1558512575.502|REQTMOUT|ClickHouse 19.6.2.11#consumer-24| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.502|FAIL|ClickHouse 19.6.2.11#consumer-24| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 16017ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.502|ERROR|ClickHouse 19.6.2.11#consumer-24| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 16017ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %5|1558512575.520|REQTMOUT|ClickHouse 19.6.2.11#consumer-10| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5796ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 293885ms
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %4|1558512575.521|REQTMOUT|ClickHouse 19.6.2.11#consumer-10| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.521|FAIL|ClickHouse 19.6.2.11#consumer-10| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 10011ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.521|ERROR|ClickHouse 19.6.2.11#consumer-10| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 10011ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %5|1558512575.642|REQTMOUT|ClickHouse 19.6.2.11#consumer-26| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out LeaveGroupRequest in flight (after 5918ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 291577ms
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %4|1558512575.642|REQTMOUT|ClickHouse 19.6.2.11#consumer-26| [thrd:GroupCoordinator]: GroupCoordinator/8: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.643|FAIL|ClickHouse 19.6.2.11#consumer-26| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 21022ms in state UP)
May 22 11:09:35 bigdata22 clickhouse-server[31808]: %3|1558512575.643|ERROR|ClickHouse 19.6.2.11#consumer-26| [thrd:GroupCoordinator]: GroupCoordinator: 1 request(s) timed out: disconnect (after 21022ms in state UP`

**Comment by vezir** [comment]
I removed the kafka parameters from the config.xml and redefine the create table statement with kafka engine with these parameters;
`kafka_num_consumers = 4,
kafka_row_delimiter = '\n',
kafka_skip_broken_messages = 1,
kafka_max_block_size = 1000;`

Now, It seems ok. I am monitoring.

**Comment by hasnat** [comment]
try adding following config to your kafka brokers `group.initial.rebalance.delay.ms=0` This would possibly sort out errors like
```
REQTMOUT|ClickHouse 19.5.4.22#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/2: Timed out LeaveGroupRequest in flight (after 5940ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 86395669ms
REQTMOUT|ClickHouse 19.5.4.22#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator/2: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
```

**Comment by abyss7** [comment]
Can you tell if the initial number of consumers (`kafka_num_consumers`) exceeds at any point of time the total number of partitions for all consumed topics?

**Comment by hasnat** [comment]
> Can you tell if the initial number of consumers (`kafka_num_consumers`) exceeds at any point of time the total number of partitions for all consumed topics?
@abyss7 
No before it was setup as 3 consumers for a 3 partitions topic

We have another 8 consumers table on 8 partitions topic which never gave us any trouble.

only difference is for clickhouse 8/8 is on local network and 3/3 is different continent.

**Comment by spyros87** [comment]
> I removed the kafka parameters from the config.xml and redefine the create table statement with kafka engine with these parameters;
> `kafka_num_consumers = 4, kafka_row_delimiter = '\n', kafka_skip_broken_messages = 1, kafka_max_block_size = 1000;`
> 
> Now, It seems ok. I am monitoring.

I have applied the same configuration with @vezir . I need to monitor as well if this configuration is correct.

**Comment by spyros87** [comment]
For our config, it started to work smoothly again when we reduced the number of `kafka_num_consumers` to *1* .

**Comment by splichy** [comment]
@spyros87 how many partitions your topic have?
We are probably facing same issue, I have set `kafka_num_consumers` to match number of partitions(**2**), but after ~9h clickhouse stopped reading one of the topics - again(increasing LAG on one partition).
Problem introduced with upgrade from v18.12.17 to v19.7.3.9, we are running on v19.7.5.27 right now.
I will also try to set `kafka_num_consumers` to **1**

Strange thing is also reality, that kafka client is not reading partition 1(according to increasing LAG), but LAG on partition 0 stay low(messages are commited in kafka) - but data are not actually written to clickhouse :/ according to graph we are missing data(after I have set `kafka_num_consumers` to 1 and partition 1 was read)
![Screenshot from 2019-06-13 12-12-40](https://user-images.githubusercontent.com/16658908/59425098-95a9e280-8dd5-11e9-99fd-950b3be6a5c2.png)

**Comment by splichy** [comment]
@abyss7 including kafka debug log
[kafka_consumer_group_describe_20190613_1150__01.log](https://github.com/yandex/ClickHouse/files/3285512/kafka_consumer_group_describe_20190613_1150__01.log)
[kafka_debug_log_20190613_1150__01.log](https://github.com/yandex/ClickHouse/files/3285513/kafka_debug_log_20190613_1150__01.log)

**Comment by eupakhomov** [comment]
@abyss the issue reproduces on version 19.7.3.9 with kafka_num_consumers = 1

**Comment by vavrusa** [comment]
> We are probably facing same issue, I have set kafka_num_consumers to match number of partitions(2)

You should always set the `kafka_num_consumers` to be lower than the `number_of_kafka_partitions / number_of_clickhouse_nodes`. If your Kafka topic has 10 partitions for example and you have 2 clickhouse nodes, you shouldn't set it to more than 5 because one node may get more partitions assigned than the other one. Normally you don't really need to change the `kafka_num_consumers` setting unless your write throughput is in hundreds of thousands records per second.

> I removed the kafka parameters from the config.xml and redefine the create table statement with kafka engine with these parameters; kafka_num_consumers = 4, kafka_row_delimiter = '\n', kafka_skip_broken_messages = 1, ...

See the https://github.com/yandex/ClickHouse/issues/5545#issuecomment-502141729 for `kafka_skip_broken_messages` setting.

I would be wary of fiddling with Kafka client timeouts, at least make sure that the various I/O timeouts  can't exceed the session or rebalance timer, otherwise groups will have difficulty forming. If you have a high latency connection to Kafka or slow Kafka cluster, then it could help to increase some timeouts. The Kafka engine with a view attached to it will try to commit at most every `stream_flush_interval_ms` https://github.com/yandex/ClickHouse/blob/master/dbms/src/Core/Settings.h#L209 which is 7.5s by default. It must complete the commit within the rebalance or session timeout. I think the query execution only checks the limits on every block, so every `max_block_size` rows or EOF (actually this was updated in https://github.com/yandex/ClickHouse/commit/4a5832b18ad00af7bdb62bb0577d726887bf17e7 it seems). But anyway, the commit interval must be lower than the Kafka session timeouts. It would be perhaps better to implement `rebalance_cb` as @simPod suggested and cancel any pending queries if rebalance request comes in to force them to wrap up as soon as possible instead of relying on timers.

**Comment by spyros87** [comment]
This error might occur due to some bugs in the underlying Kafka Libraries ([cppkafka](https://github.com/ClickHouse-Extras/cppkafka/) and [librdkafka](https://github.com/edenhill/librdkafka/tree/8695b9d63ac0fe1b891b511d5b36302ffc84d4e2)). CH uses older versions of those that are currently available.

**Comment by splichy** [comment]
Hi, still happening even with kafka_skip_broken_messages=1 & kafka_num_consumers=1.
We have only standalone clickhouse instances(one for "production" and second for tests) each instance uses it's own Consumer Group. Topic is on 3 node kafka cluster, in 2 partitions.
Issue is on both CH instances. We are actually reading from multiple kafka clusters, but it looks that it happening with topics on remote kafka clusters(different country) with higher msg. rates.
So:
both CH independet instances are at Frankfurt
high msg. rate topic at FRA - OK(but didn't mean that issue cannot happen later)
high msg. rate topic at Prague - problem(stops reading after a few hours, but on both CH servers it stoped at different time)
low msg. rate topic at Prague - OK(at least didnt stoping after a few hours)

Yesterday CH stopped reading at 16:35:35, on second CH ~2h earlier
[kafka_debug_log_20190618_1635_.log](https://github.com/yandex/ClickHouse/files/3305219/kafka_debug_log_20190618_1635_.log)

**Comment by k0st1an** [comment]
Looks like #5680 . Is there a deadline for the decision? This is a critical problem.

**Comment by abyss7** [comment]
I have upgraded rdkafka library (as a suggested solution to #5680) in v19.11+ - since I still can't reproduce an issue, I would appreciate if someone will test 19.11 before it gets stable.

**Comment by florida-hehe** [comment]
> I got same error `void DB::StorageKafka::streamThread(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration`. Drop Kakfa engine table and recreate help. ClickHouse server version 19.3.7

 <Error> void DB::StorageKafka::streamThread(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration, version = 19.7.5.27.  recreate is not help.

**Comment by filimonov** [comment]
@florida-hehe can you please try to reproduce that on 19.11?

**Comment by filimonov** [comment]
Obsolete. If you see some of the problems discussed here on new versions please open new issue.

**Comment by sunchanglong1991** [comment]
I also encountered the same problem, what is the final solution? What caused it?

**Comment by aliabidzaidi** [comment]
I am facing the same issue, no kafka messages get consumed, even drop and create doesn't

**Comment by aliabidzaidi** [comment]
I am facing the same issue, 
no kafka messages get consumed, 
even table drop and create doesn't fix it


```
............
2021.08.24 18:32:41.183784 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2536241], http[1:2574600], http[2:#], http[3:#] ]
2021.08.24 18:32:42.300498 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2545179], http[1:2631167], http[2:#], http[3:#] ]
2021.08.24 18:32:43.352460 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2552673], http[1:2673827], http[2:2527222], http[3:2539316] ]
2021.08.24 18:32:44.296007 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2557921], http[1:2703717], http[2:2532373], http[3:2564532] ]
2021.08.24 18:32:45.351484 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2562038], http[1:2731864], http[2:2536578], http[3:2593568] ]
2021.08.24 18:32:46.371909 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2567232], http[1:2758206], http[2:2541875], http[3:2622240] ]
2021.08.24 18:32:47.282057 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2570732], http[1:2788615], http[2:2545030], http[3:2650681] ]
2021.08.24 18:32:48.176688 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2575170], http[1:2817665], http[2:2549822], http[3:2677906] ]
2021.08.24 18:32:49.065861 [ 1638 ] {} <Trace> StorageKafka (http_queue): Re-joining claimed consumer after failure
2021.08.24 18:32:49.072968 [ 1638 ] {} <Trace> StorageKafka (http_queue): Execution took 7931 ms.
2021.08.24 18:32:49.573118 [ 1638 ] {} <Debug> StorageKafka (http_queue): Started streaming to 1 attached views
2021.08.24 18:32:49.575185 [ 1638 ] {} <Trace> StorageKafka (http_queue): Already subscribed to topics: [http]
2021.08.24 18:32:49.575235 [ 1638 ] {} <Trace> StorageKafka (http_queue): Already assigned to: [ http[0:#], http[1:#], http[2:#], http[3:#] ]
2021.08.24 18:32:49.593569 [ 1638 ] {} <Trace> StorageKafka (http_queue): Rebalance initiated. Revoking partitions: [ http[0:#], http[1:#], http[2:#], http[3:#] ]
2021.08.24 18:32:49.595791 [ 1638 ] {} <Trace> StorageKafka (http_queue): Topics/partitions assigned: [ http[0:#], http[1:#], http[2:#], http[3:#] ]
2021.08.24 18:32:49.715806 [ 1638 ] {} <Trace> StorageKafka (http_queue): Rewind last poll after rebalance. Returned to committed position: [ http[0:#], http[1:#], http[2:1076173], http[3:908974] ]
2021.08.24 18:32:49.722110 [ 1638 ] {} <Trace> PushingToViewsBlockOutputStream: Pushing from testDB.http_queue (65961932-2737-41c1-a596-1932273731c1) to testDB.http_consumer (2b35cacd-5f3d-4202-ab35-cacd5f3db202) took 0 ms.
2021.08.24 18:32:49.722245 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled offset INVALID (topic: http, partition: 0)
2021.08.24 18:32:49.722275 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled offset INVALID (topic: http, partition: 1)
2021.08.24 18:32:49.722297 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled offset INVALID (topic: http, partition: 2)
2021.08.24 18:32:49.722318 [ 1638 ] {} <Trace> StorageKafka (http_queue): Polled offset INVALID (topic: http, partition: 3)
2021.08.24 18:32:49.722339 [ 1638 ] {} <Trace> StorageKafka (http_queue): Nothing to commit.
2021.08.24 18:32:49.722362 [ 1638 ] {} <Debug> StorageKafka (http_queue): Pushing 0.00 rows to testDB.http_queue (65961932-2737-41c1-a596-1932273731c1) took 149 ms.
2021.08.24 18:32:49.722501 [ 1638 ] {} <Trace> StorageKafka (http_queue): Stream(s) stalled. Reschedule.
2021.08.24 18:32:50.222804 [ 1627 ] {} <Debug> StorageKafka (http_queue): Started streaming to 1 attached views
2021.08.24 18:32:50.224697 [ 1627 ] {} <Trace> StorageKafka (http_queue): Already subscribed to topics: [http]
2021.08.24 18:32:50.224842 [ 1627 ] {} <Trace> StorageKafka (http_queue): Already assigned to: [ http[0:#], http[1:#], http[2:#], http[3:#] ]
2021.08.24 18:32:50.260174 [ 1627 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2537508], http[1:2573333], http[2:#], http[3:#] ]
2021.08.24 18:32:51.328008 [ 1627 ] {} <Trace> StorageKafka (http_queue): Polled batch of 65505 messages. Offsets position: [ http[0:2542308], http[1:2630955], http[2:2528740], http[3:#] ]
.
.

```
