### ISSUE TITLE
Why blocks_are_granules_size is true when using vertical merge algorithm ?

### ISSUE THREAD

**Issue by fanhualta** [ClickHouse/ClickHouse#46324]
When doing merge, I see that blocks_are_granules_size is set to true only when using the vertical merge algorithm, which means that use_average_block_sizes when reading input data. Why can the horizontal algorithm not set blocks_are_granules_size to true?

**Comment by alesapin** [comment]
Hello @fanhualta, thank you for your question. The variable `blocks_are_granules_size` is related to adaptive granularity, where we try to have granules with a size in bytes that is approximately equal to the `index_granularity_bytes` (default 10 MB). When performing a **Horizontal merge**, we have full blocks in memory containing all columns, making it easy to calculate their size in bytes and determine how many blocks to write before starting a new granule. However, during **Vertical merge**, it is impossible to calculate the size of a block in memory since columns are written one by one, and full blocks with all columns are never in memory. Instead, we assume that blocks in source parts have the same size as granules since vertical merges are only performed on large parts with many columns. Therefore, we don't set `blocks_are_granules_size` for **Horizontal merge** since calculating the block size in memory is more precise.
