### ISSUE TITLE
partitionId function. (generate partiitonId from input types/values)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#46584]
**Use case**

Debug purposes. 

**Describe the solution you'd like**

```
SELECT partitionId(toYYYYMM(today()))):

202302;
```

**Comment by rvasin** [comment]
Hello, we (Arenadata) wanted to implement this function but we found that the function `partitionID(`) already exists:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/partitionId.cpp

It was implemented on Mar 4, 2021 by [Amos Bird](https://github.com/amosbird)
See commit: https://github.com/ClickHouse/ClickHouse/commit/93b661ad5a39bd94e1d85c4b971ee32111bfde7b

Could you please verify it? Because this issue was created on Feb 20, 2023.
But the function was added in Mar 4, 2021 see PR  [#21401](https://github.com/ClickHouse/ClickHouse/pull/21401)

**Comment by UnamedRus** [comment]
OK, it was my mistake, tuple wrapper is unneded actually:

```
SELECT partitionId(1 = CAST('1', 'UInt32'), toYYYYMM(now()))

Query id: f6d2d547-316f-4948-8a69-48fc7a7c1e77

┌─partitionId(equals(1, CAST('1', 'UInt32')), toYYYYMM(now()))─┐
│ 1-202309                                                     │
└──────────────────────────────────────────────────────────────┘
```
