### ISSUE TITLE
Remove 1 parts inside 20230206-5_0_5634_999999999

### ISSUE THREAD

**Issue by JianboDM** [ClickHouse/ClickHouse#46638]
I found out that our data is missing，and in the log we found the info like this：Remove 1 parts inside 20230206-5_0_5634_999999999
clickhouse server version 20.3.8.53
the table engine is ReplicatedMergeTree
1：Will this cause data loss？
2：what does this log mean？
3：Why does this happen？

**Comment by tavplubix** [comment]
First of all, version 20.3 is obsolete (it's almost 3 years old), so you should upgrade.

> Remove 1 parts inside 

This message comes from here:
https://github.com/ClickHouse/ClickHouse/blob/6526c2a8abbab6f027672903cf05e1537274f109/src/Storages/StorageReplicatedMergeTree.cpp#L1938

On 20.3 it's possible only due to `ALTER TABLE ... DROP PART ...` query. So it means that someone dropped the data part manually.
