### ISSUE TITLE
Importing data from other RDBMS (SQLServer in my case)

### ISSUE THREAD

**Issue by pbuxtonccuk** [ClickHouse/ClickHouse#4663]
Hi,

Trying to move data from a SQLServer Azure datawarehouse to CLickhouse. 

I can't do it easily...    I had hoped that I could utilise SSIS, but the ODBC driver simply won't work with SSIS,   

Is there a recommended way to do this,

**Comment by alex-krash** [comment]
What amount of data (in terms of row count and data volume) you need to transfer?

**Comment by pbuxtonccuk** [comment]
Just shy of 200m rows.  What I would like is to be able to do an incremental update.    Now, currently, I am pulling this data from MSSQL, and putting it in the ELK stack, using Logstash .   I am aware of the ClickhouseMigrator project on Github, but it does't work.  I am also aware of the logstash-output-clickhouse plugin, and I get an obscure error on that  (HTTP 400) - probably down to lack of documentation as much as anything.

I would also like to push stuff in Clickhouse from a SYSLOG generated from the Barracuda firewall.

Thanks 
Paul

**Comment by TH-HA** [comment]
Hello , i've also used logstash to do that , but it lack of flexbility on the clickhouse export.Also logstash is very heavy and not really user friendly when developping.
 Instead to handle both case , i would suggest to use Apache NIFI. 
Nifi is able to query on MSSQL transform your data and push them to clickhouse ( i personally use the http interface instead of jdbc to push data in clickhouse as it fit my performance constraint). 
Nifi is also very good at receiving syslog and parse them , so you can use it also in a very simple manner to do that ( In fact Nifi was design to collect syslog).

Last interesting thing is Nifi allow to build a buffer very easily  ( Mechanism in Clickhouse are also powerfull but require more work to make things resilient where in Nifi you can have a basic implementation very quickly and easy to tune/debug - look at the MergeContent processor ).

**Comment by pbuxtonccuk** [comment]
Thanks for the pointer.  Never used NiFi, so going to be interesting to look at....  if there are any gotchas, i would appreciate any heads up!!

**Comment by pbuxtonccuk** [comment]
TH-HA

> Hello , i've also used logstash to do that , but it lack of flexbility on the clickhouse export.Also logstash is very heavy and not really user friendly when developping.
> Instead to handle both case , i would suggest to use Apache NIFI.
> Nifi is able to query on MSSQL transform your data and push them to clickhouse ( i personally use the http interface instead of jdbc to push data in clickhouse as it fit my performance constraint).
> Nifi is also very good at receiving syslog and parse them , so you can use it also in a very simple manner to do that ( In fact Nifi was design to collect syslog).
> 
> Last interesting thing is Nifi allow to build a buffer very easily ( Mechanism in Clickhouse are also powerfull but require more work to make things resilient where in Nifi you can have a basic implementation very quickly and easy to tune/debug - look at the MergeContent processor ).

Not sure if you will see this, but feel I am hitting my head against a brickwall.  

Can you give me an example of configuring the PostHTTP processor to insert into Clickhouse?  Reading from MSSQL ins't the problem.

**Comment by blinkov** [comment]
@pbuxtonccuk, do you have any further questions?
