### ISSUE TITLE
Faster distinct query query of low cardinality columns

### ISSUE THREAD

**Issue by hushengyue** [ClickHouse/ClickHouse#4670]
In our scenario, we have some columns defined as low cardinality string type. The total number of the distinct values are no more than 10K.  The values cannot be predicted.  When query the distinct values of these columns, clickhouse needs to scan all the data rows. 

Is it possible to accelerate such query? 

To my understanding, these low cardinality columns are stored with compressed reference to the raw values. It should be much faster to query the uniq raw values instead of scan all the data rows. 
For additional case,  the distinct query may followed with filter conditions. Is it possible to support faster distinct query with primary key filters too?

**Comment by den-crane** [comment]
Just use `select MYCOLUMN from t group by MYCOLUMN`
Instead  `select distinct(MYCOLUMN) from t`

low cardinality types have optimization to use low cardinality nature for GROUPBY by_single_LowC_column

**Comment by hushengyue** [comment]
Thanks den,  what about to select distinct values of multiple columns?  I guess there is no optimization for such case.

**Comment by blinkov** [comment]
@hushengyue, do you have any further questions?

**Comment by alexey-milovidov** [comment]
> Thanks den, what about to select distinct values of multiple columns? I guess there is no optimization for such case.

You're right, there is no such optimization.

> To my understanding, these low cardinality columns are stored with compressed reference to the raw values.

The details are a bit more complicated. LowCardinality columns are represented by "local" dictionaries. And there can be multiple independent dictionaries for a single column, even in single data part. We cannot just extract numeric indices and use them for aggregation, because there can be different indices in different dictionaries.

The algorithm is possible and it is implemented for single key case. But as it becomes more tricky, it is not implemented for multiple key case.
