### ISSUE TITLE
Naming convention about 'abstract' class

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#46943]
I am learning from CH code and have a question about naming convention for abstract class. I see some classes called 'I-***', for example IColumn, IDataType, have defined both pure virtual functions and normal virtual functions. In Java/C# context, these classes are 'abstract' classes. I am wondering if the classes with 'I-***' names are representing both abstract classes and interfaces in CH source code. 

By the way, is there no specific distinction between the abstract class and the interface in CH source code? Just want to follow the convention.

Thank you.

**Comment by tavplubix** [comment]
I would say that C++ does not have such a concept as an "interface". Java and C# have restrictions on multiple inheritance (to avoid the "diamond problem"), that's why interfaces are required (to allow classes implementing multiple interfaces). In C++ it's totally fine to have "interfaces" (well, maybe it would be better to call them "the most base abstract classes") with non-pure virtual methods, non-virtual methods, and even with fields. So the 'I-' prefix in a class name indicates that it's "the most base abstract class": it may or may not be a pure interface, it does not really matter.

**Comment by Alex-Cheng** [comment]
Thank you very much. So in CH repository, the I-* named classes are abstract base classes or interfaces (if there are all pure virtual functions) and we don't care about distingushing them.
