### ISSUE TITLE
simulate mysql/postgres schema

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#47286]
mysql: information_schema
postgres: pg_class

I think there might be others, but I think certain interfaces expecting Clickhouse to behave-like-MySQL or behave like Postgres would require this. for example DuckDB can't read Clickhouse without pg_class and Dremio chokes because if I understand correctly (just guessing) I would imagine they're reading information_schema.tables. These do look different in Clickhouse, it would be nice to fool these interfaces that make more advanced use of Clickhouse internals.

**Comment by UnamedRus** [comment]
>mysql: information_schema

Already exist.

**Comment by rschu1ze** [comment]
@alanpaulkwan You might be interested in related issue #48340

To add to the previous comment:

Only `INFORMATION_SCHEMA` is standardized. `pg_class` isn't and I don't see a particular reason why ClickHouse should imitate PostgreSQL-proprietary system tables. 1. PostgreSQL is just "yet another DBMS" out of dozens of other DBMS (a quite popular and good one, though). 2. ClickHouse already attempts to provide a certain level of (SQL-level) compatibility with MySQL and the mismatch of ClickHouse's and MySQL's data architecture, constraints, table/index types, assumptions etc. makes "emulated" system tables feel quite "foreign" to ClickHouse, see e.g. #49158 for an example what I mean. I fear the same will happen with `pg_*` system tables.

And yes, SQL IMHO unfortunately under-specifies system tables common to all SQL-compatible DBMSs. This leads to the situation that clients (@alanpaulkwan mentioned DuckDB, Dremio, ...) either need to resort to the minimalistic `INFORMATION_SCHEMA` table or implement DBMS-specific logic which queries the natively provided system tables.

About `INFORMATION_SCHEMA`: Different databases treat schema/table names case-sensitively or insensitively, and virtually none of them implement what the SQL standard says about case-sensitivity. MySQL's behavior is particularly "interesting" ([here](https://stackoverflow.com/questions/6134006/are-table-names-in-mysql-case-sensitive) and [here](https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html)). So basically, ClickHouse provides case-sensitive `INFORMATION_SCHEMA` whereas in MySQL the schema name is case-insensitive (`information_schema` works). Since database/table names are internally passed around as strings, adopting MySQL's case-insensitivity would mean a lot of changes (for questionable benefit).

I would say compatibility with other DBMSs needs to be decided on a case-by-case basis. If you have a more specific requirement, feel to open another ticket - thanks!
