### ISSUE TITLE
to improve insertion perfomance 

### ISSUE THREAD

**Issue by seven7777777** [ClickHouse/ClickHouse#4761]
Hi,
Thanks for your great Clickhouse, it really helps us a lot. Recently ,we are trying to use Clickhosue timeseries database, and we are now stuck in insertion performance. We have 64c/300g/nvme server, but we kept encountering "merge is slower than insert".
I wonder if we could write data directly into memory on insertion , merge data in memory in background and finally write merged data to disk.

**Comment by seven7777777** [comment]
It could be much slow if we merge on disk.

**Comment by den-crane** [comment]
Did you check https://clickhouse.yandex/docs/en/operations/table_engines/buffer/ it seem the pretty same.

**Comment by seven7777777** [comment]
Yes, I did check memory/buffer part before I post this issue. But I wonder if buffer engine works as I expect: merging in memory and writing merged block to disk.

**Comment by filimonov** [comment]
Each separate insert to MergeTree  creates one part stored as a separate directory on filesystem.

So the only acceptable way of inserts to MergeTree is bulk inserts.

Buffer engine definitely works in memory and allows to form a bigger parts, combining multiple smaller inserts into one bigger.

Merges will be executed (and should be executed) on disk afterwards. But most probably (if you have enough memory) it will happen in memory because of OS file caching.


So for example if you do 10K one-row inserts to MergeTree it will create 10K folders and clickhouse will try to merge that selecting few parts at once it will work slow because it will now use advantages of bulk (SIMD) processing and because of lot of filesystem operations.

If you insert 100K row in one bulk insert they will form one big bulk, and one directory on filesystem, so it is already merged (but still it will be merges with other bigger parts from the same partition). Buffer allows you to form one insert to MergeTree  from lot of inserts to Buffer table. So it allows to avoid lot of merges if you insert data in single rows.

**Comment by alexey-milovidov** [comment]
This will be addressed in the second step of "Polymorphic data parts" feature.
Polymorphic data parts is in development. The first step (compact data parts on disk) is addressed in this PR: https://github.com/ClickHouse/ClickHouse/pull/8290

**Comment by alexey-milovidov** [comment]
In-memory data parts are implemented in #10697 but they are experimental and not enabled by default.
