### ISSUE TITLE
binary search or eight-point search？lookup for a primary key index

### ISSUE THREAD

**Issue by iammagicc** [ClickHouse/ClickHouse#47804]
At yesterday,I saw a concept.It's "MarkRange".MergeTree divides a complete piece of data into multiple small interval data segments according to the interval granularity of the index_granularity, and a specific data segment is a MarkRange.It means that one particle corresponds to one MarkRange, and eight MarkRange are merged, corresponding to [start, end].

But what I saw on the official website is “When a query is filtering on a column that is part of a compound key and is the first key column, then ClickHouse is running the binary search algorithm over the key column's index marks.”

I don't know which one is true?
I hope someone can answer this question.

**Comment by alexey-milovidov** [comment]
Yes, it would be better to say that it uses a logarithmic search. If I recall correctly, 8-way is not hardcoded and can be changed.

**Comment by al13n321** [comment]
Do you mean the code in `MergeTreeDataSelectExecutor::markRangesFromPKRange()`? It has both a binary search and a "generic exclusion search".

The binary search is at [1]. It's a perfectly ordinary binary search.

The documentation [2] also says:

> The [generic exclusion search algorithm](https://github.com/ClickHouse/ClickHouse/blob/22.3/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L1444) that ClickHouse is using instead of the [binary search algorithm](https://github.com/ClickHouse/ClickHouse/blob/22.3/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L1452) when a query is filtering on a column that is part of a compound key, but is not the first key column is most effective when the predecessor key column has low(er) cardinality.

The implementation of that is at [3]. Is this what you're referring to?

This search is similar to an interval tree: you start with the full range, then recursively subdivide it until you reach length-1 ranges. (Or imagine a quad tree or octree, if you're more familiar with those.) This allows discarding long ranges early instead of iterating over all the granules. Useful when the query selects a very small subset of data: you don't want to iterate over the whole index just to find a few granules.

All of this is just an in-memory operation, since the whole index is in memory at the time of the search. So it's not super important. Scanning the whole index would be ok too, it's not like scanning all the data.

[1] https://github.com/ClickHouse/ClickHouse/blob/22.3/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L1442-L1485
[2] https://clickhouse.com/docs/en/optimize/sparse-primary-indexes
[3] https://github.com/ClickHouse/ClickHouse/blob/22.3/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L1390-L1438

**Comment by iammagicc** [comment]
To add, using a generic exclusion search may traverse most of the granule because it can't determine if the data is in the granule, so it still traverses most of the data. So I recommend optimizing the primary key query for this, you can see the related content here.https://clickhouse.com/docs/en/optimize/sparse-primary-indexes
