### ISSUE TITLE
QUALIFY Clause (Just like HAVING but for window functions)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#47819]
**Use case**

```
SELECT <column_list>
  FROM <data_source>
  [GROUP BY ...]
  [HAVING ...]
  QUALIFY <predicate>
  [ ... ]


    WITH dense_rank() OVER (ORDER BY number DESC) AS row
    SELECT row
    FROM numbers(10)
    QUALIFY row < 3
```

**Describe alternatives you've considered**

Subquery

```
SELECT *
FROM
(
    WITH dense_rank() OVER (ORDER BY number DESC) AS row
    SELECT row
    FROM numbers(10)
)
WHERE row < 3
```

**Additional context**
https://github.com/ClickHouse/ClickHouse/issues/47818

https://docs.teradata.com/r/2_MC9vCtAJRlKle2Rpb0mA/19NnI91neorAi7LX6SJXBw
https://docs.snowflake.com/en/sql-reference/constructs/qualify

**Comment by andrea-s** [comment]
Would this help with https://github.com/ClickHouse/ClickHouse/issues/35056 ?

**Comment by UnamedRus** [comment]
I don't think so.

Your question is about smart? condition pushdown

```
SELECT
    count(),
    sum(wf)
FROM
(
    SELECT
        number,
        max(number) OVER (PARTITION BY floor(number / 5)) AS wf
    FROM
    (
        SELECT *
        FROM system.numbers
        LIMIT 100000000.
    )
    ORDER BY number ASC
)
WHERE number = 1
```

TO

```
SELECT
    count(),
    sum(wf)
FROM
(
    SELECT
        number,
        max(number) OVER (PARTITION BY floor(number / 5)) AS wf
    FROM
    (
        SELECT *
        FROM system.numbers
        LIMIT 100000000.
    )
    WHERE floor(number / 5) = floor(1 / 5)
    ORDER BY number ASC
)
WHERE number = 1

Query id: 6ea32797-31db-48a4-8cc2-cd1cc8332f9d

┌─count()─┬─sum(wf)─┐
│       1 │       4 │
└─────────┴─────────┘

1 row in set. Elapsed: 0.145 sec. Processed 70.64 million rows, 565.13 MB (487.51 million rows/s., 3.90 GB/s.)
```

**Comment by PaulAlexAhlstrom** [comment]
Just adding some context I have to bump up this issue. I would really love if ClickHouse added `QUALIFY`. [Snowflake](https://docs.snowflake.com/en/sql-reference/constructs/qualify), [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#qualify_clause), and [DuckDB](https://duckdb.org/docs/sql/query_syntax/qualify.html) have the `QUALIFY` keyword. As an analytics engineer I use it primarily to deduplicate data, like so:

```
Select user_id, amount, updated_at
from table
qualify row_number() over (partition by user_id order by updated_at desc) = 1
```

This query deduplicates the table to get the row with the most recently updated user id. It's handy because it requires no subquery or modification to the table beyond this single line. If this feature is added I would consider proposing we move my company's data stack to ClickHouse Cloud.

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/62619

**Comment by UnamedRus** [comment]
> This query deduplicates the table to get the row with the most recently updated user id. It's handy because it requires no subquery or modification to the main query beyond this single line

BTW, for deduplication there is LIMIT 1 BY operator
