### ISSUE TITLE
HAVING clause can be used on columns not used in aggregation

### ISSUE THREAD

**Issue by wol-e** [ClickHouse/ClickHouse#47922]
**Describe the unexpected behaviour**
This query does run without errors:

```
SELECT
    number % 10 AS number_mod_10,
    count() AS n
FROM
    (SELECT number FROM system.numbers LIMIT 1000)
GROUP BY
    number_mod_10
HAVING number >= 10;
```

However, since I perform 'HAVING' on the field 'number' which is not present in the output of the GROUP BY I would expect this query to fail. Instead it seems that the HAVING has the same effect as when putting the corresponding WHERE statement:

```
SELECT
    number % 10 AS number_mod_10,
    count() AS n
FROM
    (SELECT number FROM system.numbers LIMIT 1000)
WHERE number >= 10
GROUP BY
    number_mod_10;
```
-> This query has the same output. 

This behaviour is rather unexpected to me. Is this intended behaviour? I could not find it being mentioned in the Docu. I also tried to recreate this example with MySQL  where I get the expected error "Unknown column 'number' in 'having clause'".

my clickhouse version is 22.11.4.3

**Comment by den-crane** [comment]
This is intended behaviour. In this case having predicates are pushed down to the WHERE section.

It's not documented because it's a part of internal implementation of Distributed queries (for generalization).

When the query Initiator rewrites distributed queries to shards it puts all predicates to HAVING section. Then shards optimize this queries and care predicates to where section if this push down is possible for a predicate.

**Comment by wol-e** [comment]
Thank you! I'll close it based on your feedback :+1:
