### ISSUE TITLE
Why a backport commit related to so many branches

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#48037]
![image](https://user-images.githubusercontent.com/1518453/227856357-0c1b4ab8-7da1-4c4d-9364-0d16fb58320d.png)

As shown at above screenshot, the backport commit relates to pull #41972 but relates to many branches, such as `backport/22.8/43009`. I cannot explain it and curious about it. Any guru give me some help?

**Comment by nvartolomei** [comment]
The UI shows you all the branches a commit is part of (unless it is also part of the default branch). Since backport branches are never merged into the default branch (master) and they are authored on top of the release branches (in this case, on top of `22.8` branch), these branches will show up for all prior backport commits.

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/about-commits
