### ISSUE TITLE
Range bloom filter index with bloomRF

### ISSUE THREAD

**Issue by awitten1** [ClickHouse/ClickHouse#48086]
I recently came across the paper [bloomRF](https://openproceedings.org/2023/conf/edbt/paper-190.pdf) on performing range queries with a bloom filter.  It would allow a ClickHouse bloom filter index to efficiently answer the question: "does this granule have any value in the range 42 to 4711?"  This paper's approach has advantages over alternatives such as SuRF.   I think it would be a cool feature to have in ClickHouse.

It's something I'd be interested in contributing if you think it's a good idea.

**Comment by rschu1ze** [comment]
Hi,

thanks, that's good to hear! This topic is similar to "Probabilistic data structures for approximate (range) filtering in ClickHouse queries." on the [intern task list](https://github.com/ClickHouse/ClickHouse/issues/42194). There has not been much (any) progress with that since November, so feel free to contribute. I also wrote you a mail ... perhaps we should have a call and chat about the further steps and the context of this work.

Thanks and regards
Robert
