### ISSUE TITLE
MySQL dialect compaitability

### ISSUE THREAD

**Issue by RealHarshThakur** [ClickHouse/ClickHouse#48340]
(you don't have to strictly follow this form)

**Describe the issue**
I was trying out the MySQL compatibility with a schema management [tool](https://atlasgo.io/) as lots of tools support MySQL for schema management already. Ran into this:
mysql: querying schemas: Error 47 (00000): Code: 47. DB::Exception: Missing columns: 'DEFAULT_COLLATION_NAME' while processing query: 'SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM (SELECT name AS catalog_name, name AS schema_name, 'default' AS schema_owner, NULL AS default_character_set_catalog, NULL AS default_character_set_schema, NULL AS default_character_set_name, NULL AS sql_path FROM system.databases HAVING SCHEMA_NAME NOT IN ('information_schema', 'innodb', 'mysql', 'performance_schema', 'sys')) AS SCHEMATA WHER%     
Is it possible to mimic those columns for “compatibility” in terms of DDL management?

**How to reproduce**
* Which ClickHouse server version to use: v23.x.x
* Non-default settings, if any: have a mysql port in Clickhouse config

**Expected behavior**
I'd like behaviour where TABLE CREATION with `innodb` is internally translated to MergeTree by Clickhouse and if other tables requested over MySQL-wire that are MySQL specific are translated back to Clickhouse tables.

**Comment by rschu1ze** [comment]
(The query string is somehow truncated after `WHER%`. @RealHarshThakur Could you please check the ClickHouse database log for the full query string? `DEFAULT_COLLATION_NAME` is not produced by the (partial) subquery.)

Anyways, [INFORMATION_SCHEMA](https://en.wikipedia.org/wiki/Information_schema) is standardized, unfortunately the copy of the SQL standard (2011) I have doesn't say anything about the actual contained tables/columns.

MySQL has column `INFORMATION_SCHEMA.SCHEMATA.DEFAULT_COLLATION_NAME` ([docs](https://dev.mysql.com/doc/refman/8.0/en/information-schema-schemata-table.html)).

But there is no such column in Postgres's / MS SQLServer's / Snowflake's / Druid's `INFORMATION_SCHEMA.SCHEMATA` ([docs](https://www.postgresql.org/docs/current/infoschema-schemata.html) [docs](https://learn.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/schemata-transact-sql?view=sql-server-ver16) [docs](https://docs.snowflake.com/en/sql-reference/info-schema/schemata) [docs](https://druid.apache.org/docs/latest/querying/sql-metadata-tables.html#schemata-table)). In case of doubt, I'd prefer Postgres over MySQL for standard compatibility.

It will be easy to add the column (it will have value `NULL` since columns don't have a collation). The question is ... should we do that, and if yes, what about the many other tables/columns which MySQL provides in `INFORMATION_SCHEMA`. Btw., I find Atlas seems to [support](https://atlasgo.io/atlas-schema/sql-types) only MySQL, Postgres and sqlite - expecting that all DBMS out there are SQL-compatible with these is not realistic, IMHO.

Maybe @slvrtrn and @mshustov have an opinion. They work on similar integrations.

**Comment by RealHarshThakur** [comment]
Oh yeah, completely understand. Mainly opened the issue wondering what "MySQL dialect compatibility" for CH means and I think its just wire compatible for the most part but there are bits where `show version()`, etc work, so kinda confused on where the boundaries are

**Comment by slvrtrn** [comment]
Hi @rschu1ze, thanks for pinging me. Currently, no input from our side regarding the `INFORMATION_SCHEMA` as it was not yet required in any of the currently tested tools.
