### ISSUE TITLE
Async inserts don't work if people are using log_comment setting with different values

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#48430]
**Describe the unexpected behaviour**
Async inserts use all settings in order to calculate hash for that insert.
If people use log_comment setting, it does mean that such inserts will be put in different queues and make async inserts useless.

https://github.com/ClickHouse/ClickHouse/blob/d7879c16e487798e2fd38be4a15c78c046d9a4ff/src/Interpreters/AsynchronousInsertQueue.cpp#L94

**Expected behavior**
log_comment and other similar settings will be excluded from hash calculation

**Comment by michaelsmithxyz** [comment]
I think at a minimum this should be called out as a big potential trap in the documentation for [asynchronous inserts](https://clickhouse.com/docs/en/optimize/asynchronous-inserts). We fell into this trap with our production cluster because we included a unique identifier in `log_comment` of each insert query that we issued, which functionally unknowingly disabled `async_insert` for us, which we muddled through for a long time not know the root cause of our relatively poor ingestion health.
