### ISSUE TITLE
Native DateTime64 column

### ISSUE THREAD

**Issue by Gladdy** [ClickHouse/ClickHouse#4860]
Hi Clickhouse dev team,

Has it been considered to add a native DateTime64 column type which would have the exact same functionality as the existing DateTime, but rather than storing seconds since epoch in an UInt32, store nanos since epoch in a UInt64?

I get that you could kind of emulate the functionality by just using an UInt64 to store the timestamp as nanos since epoch, but it would be significantly less convenient (eg. it doesn't wouldn't easily do timezone conversions, not do formatting, not have all the addTime functions for shifts and also the aggregations/sampling would be more complicated than need be). 

Thanks for your time,
Martijn

**Comment by den-crane** [comment]
https://github.com/yandex/ClickHouse/issues/3507

**Comment by Gladdy** [comment]
@den-crane Thanks for the reference, I managed to overlook that issue in my search. The issue raised there is the memory consumption for the lookup tables (I haven't dug into the implementation yet), but if you keep the resolution of the lookup tables the same, 2^32 seconds = 136 years and 2^64 nanos = 584 years, which would keep the increase in memory consumption limited to about 4x for the lookup tables. Furthermore, you could maybe limit the amount of entries in the lookup table to the same range as the 32-bit value if the memory constraint is really an issue.

@alexey-milovidov I'd be curious to know the reasoning behind marking the issue as `wontfix`: infeasible? not prioritized? I obviously have a lot less experience with the code base so would be interested in your thoughts.

**Comment by den-crane** [comment]
I don't really understand what is the difference if you store fraction in another column? 
Just convince for in your backend?

**Comment by Gladdy** [comment]
Convenience is definitely a big part of it with proper formatting etc when running analytic queries but also general table cleanliness and preventing bugs in accidentally rounding the times when forgetting the fractional part. Lastly I recently added an asof join to ClickHouse which currently only performs the asof operation on the last column (similar to kdb+), which would have to have significantly more complexity if it needed to understand multi column asof joins. A DateTime64 / nanos since epoch column would solve all of these issues and I can imagine it could be an useful feature for anyone currently falling back on splitting out the fractional part.

**Comment by filimonov** [comment]
IMHO it's nice to have 'someday', currently not high priority task at all. I would say that option with storing microseconds since Epoch in signed Int64 (exactly like in JavaScript Date) sounds better than nanoseconds (nanoseconds is too granular for most of database tasks, with microseconds DateTime64 can process any timestamp ranges you can imagine, i.e. you can store dates of birth of  Ramesses I and James T. Kirk).

The biggest disadvantage of high granular timestamp is that micro/nanoseconds fractions are quite 'random', i.e. have too big entropy and compresses very bad, data processing speed is obviously depends on data size (both compressed and uncompressed). Where conditions by timestamp are very common. So your WHERE conditions will need to process twice of data, and will require 5-10 times more data to read from disk (because usual 32bit timestamps are compressed really good almost always). And it will need to use bigger lookup tables and use more complicated calculations. 

So your selects will become significantly slower. And it database will have 64 bit time a lot of people will pick it first even if they don't really need that... So it will down Clickhouse for a lot of people.

**Comment by Gladdy** [comment]
There are some examples of use cases where it's useful (if not required) to have nanosecond precision, one of them is finance/trading (for pricing/trade/response time analytics).

I agree that it compresses less well, though I'd argue that if the high precision information is needed then there is not much you can do about that (and you'd get the same performance just using UInt64). Furthermore, in the odd case that you do store second-aligned timestamps in the DateTime64 field it should still compress pretty well, though you are still hitting the memory bottleneck of having to load twice as much data.

As for your last argument, a similar case could be made for Float64 and Float32. Some people would pick double precision even though they don't need it, but you'd think that people who run databases in which the difference in performance matters would be aware of the trade-offs between the different field types. Even more so for timestamps, as the granularity is more directly exposed to whoever interfaces with the db.

An option, rather than just adding a plain DateTime64 is to also make the granularity a parameter (currently for DateTime only the timezone is), such that users can select whether they want nanos/micros/millis/seconds since epoch in a 64 bit value, but (1) it might require quite a lot of code to handle all the conversions etc in case of people trying to shift/compare/join/etc on different granularities and (2) having to limit the time span inside the conversion tables (as 2^64 (milliseconds)) is quite a long time.

**Comment by filimonov** [comment]
> There are some examples of use cases where it's useful (if not required) to have nanosecond precision, one of them is finance/trading (for pricing/trade/response time analytics).

Of course there are some special scenarios when nanoseconds or even picosecond are needed. But because of CERN need picosecond precision, it would be quite stupid to use picoseconds for measuring loan duration.

I think that database should give a 'good enough' option for medium user, and a building blocks for complicated usage scenarios. Currently you can implement any precision with 2 fields, anyway for a fraction part of time (no matter if it's micro/nano/picoseconds) you don't need to apply any wierd calendar / timezones logic, and the speed of such an implementation will be comparible to DateTime64 in the cases then you need full precision, and much faster then you don't need that. So it's only convenience issue. As an alternative one Decimal filed and some extra typecasting 'magic' can be used.  Adding DateTime64 is a also quite a big task, for now it's not in priority.

**Comment by aadant** [comment]
@filimonov : MySQL and Postgres natively support datetime(6) and timestamp(6) that have microsecond precision. If you want to replicate them, you need to support this data type. I think MariaDB column store just added it. https://mariadb.com/kb/en/library/columnstore-data-types/

**Comment by filimonov** [comment]
> @filimonov : MySQL and Postgres natively support datetime(6) and timestamp(6) that have microsecond precision. If you want to replicate them, you need to support this data type. I think MariaDB column store just added it. https://mariadb.com/kb/en/library/columnstore-data-types/

I write above: "(DateTime64 is) nice to have someday. ... option with storing microseconds since Epoch in signed Int64 (exactly like in JavaScript Date) sounds better than nanoseconds".

So i agree that microseconds is nice thing. I'm not convinced about nanoseconds. Can you list some database supporting sub-microseconds (nanoseconds) precision? If the precision can be optionated (like in Decimal datatype) - nanoseconds can be acceptable, but not by default.

> There are some examples of use cases where it's useful (if not required) to have nanosecond precision, one of them is finance/trading (for pricing/trade/response time analytics).

How do you deal with those cases in other databases?

**Comment by aadant** [comment]
Datetime(6), timestamp(6), Datetime(3), timestamp(3) are supported by databases like MySQL, Postgres, Redshift, MariaDB column store, SAP IQ. For nanoseconds, people use an unsigned bigint (10 for epoch and 9 for nanoseconds).

**Comment by filimonov** [comment]
> For nanoseconds, people use an unsigned bigint (10 for epoch and 9 for nanoseconds).

That's exactly what i'm trying to say :) Microseconds is maximum precision usually needed from database (please read my comments above once again).

**Comment by aadant** [comment]
I was replying to your question :

>How do you deal with those cases in other >databases?

Please implement sub-second precision (milli and micro seconds) rather than second only. That’s enough for most cases. Timestamp(9) might be possible to implement with 64 bits but I doubt Datetime(9) is doable. That is low priority IMHO. For the milli and microsecond precision required for compatibility (heterogeneous replication and migration), you may want to create another feature request.

**Comment by filimonov** [comment]
> I was replying to your question.

Question was about nanoseconds :) Nevermind. I glad that we agree that microseconds are needed, while nanoseconds - sounds a bit like overkill.

**Comment by alexey-milovidov** [comment]
@den-crane 

> I don't really understand what is the difference if you store a seconds' fraction in another column?
> Just convince for in your backend?

1. Better compression of integer part.
2. A room for optimization if we will be able to read just integer part.

**Comment by aadant** [comment]
This is being addressed.

**Comment by stavrolia** [comment]
#7170 work in progress

**Comment by Enmk** [comment]
> #7170 work in progress

in fact, it is ready for review, so anyone willing to do that is welcome.

**Comment by alexey-milovidov** [comment]
`DateTime64` with custom resolution has been implemented.
Support for values outside of 1970..2016 is still to do.
