### ISSUE TITLE
Broken detached parts cleanup does not work with zero-copy replication

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#48746]
```
Initialization failed, table will remain readonly. Error: Code: 233. DB::Exception: Unexpected part name: ignored_all_58400_58417_3 for format version: 1. (BAD_DATA_PART_NAME), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c66f5 in /usr/bin/clickhouse
1. ? @ 0x1451d6ac in /usr/bin/clickhouse
2. DB::MergeTreePartInfo::fromPartName(String const&, StrongTypedef<unsigned int, DB::MergeTreeDataFormatVersionTag>) @ 0x1451d183 in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::unlockSharedDataByID(String, String const&, String const&, String const&, String const&, std::shared_ptr<DB::ZooKeeperWithFaultInjection> const&, DB::MergeTreeSettings const&, Poco::Logger*, String const&, StrongTypedef<unsigned int, DB::MergeTreeDataFormatVersionTag>) @ 0x14018e28 in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::removeSharedDetachedPart(std::shared_ptr<DB::IDisk>, String const&, String const&, String const&, String const&, String const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x1402f87f in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::removeDetachedPart(std::shared_ptr<DB::IDisk>, String const&, String const&) @ 0x1402f017 in /usr/bin/clickhouse
6. DB::MergeTreeData::clearOldBrokenPartsFromDetachedDirectory() @ 0x143c0d4d in /usr/bin/clickhouse
7. DB::ReplicatedMergeTreeAttachThread::runImpl() @ 0x146344fa in /usr/bin/clickhouse
8. DB::ReplicatedMergeTreeAttachThread::run() @ 0x14631b56 in /usr/bin/clickhouse
9. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12586586 in /usr/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0x1258960a in /usr/bin/clickhouse
11. ? @ 0x1258a44e in /usr/bin/clickhouse
12. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe19a46a in /usr/bin/clickhouse
13. ? @ 0xe19fb21 in /usr/bin/clickhouse
14. ? @ 0x7fe7a20c4b43 in ?
15. ? @ 0x7fe7a2156a00 in ?
```

(this particular issue was worked around by https://github.com/ClickHouse/ClickHouse/pull/48730, but we still need to make the background cleanup work)

**Comment by mlex** [comment]
As I understand it, the problem is, that when we try to remove detached parts on a zero-copy-replication disk, we call  `unlockSharedDataByID` with argument part_name like `ignored_all_58400_58417_3` (or generally `<prefix>_....` where `<prefix>` is one of the predefined prefixes for detached parts (`broken` , `unexpected`, `ignored`, ...).

Inside `unlockSharedDataByID` we call `getParentLockedBlobs` which then calls `MergeTreePartInfo::fromPartName` with that part name. But `MergeTreePartInfo::fromPartName` doesn't know about the prefix. Further up in the stack another method `DetachedPartInfo::parseDetachedPartName` is called, which does know about the prefix - perhaps we can use that instead? Anyway, `fromPartName` throws an exception because the the "part name is unexpected". This exception causes the whole `removeSharedDetachedPart` method to fail. And no detached parts are cleaned up. And the table remains readonly until server restart.

I didn't fully understand, why the Initialization failed... Unexpected part name error doesn't re-appear after server restart. Seems like something changes ctime of the detached part directory. Not sure what. Maybe it gets updated when we try to remove a broken detached part and rename it to something like `deleting_..., but then `unlockSharedDataByID` fails and we rename it back. The first part (rename to `deleting_...`) [happens just before the](https://github.com/ClickHouse/clickhouse-private/blob/master/src/Storages/MergeTree/MergeTreeData.cpp#L2448-L2453) `Will clean up {} detached parts log message`. I couldn't find the place where we rename it back to the original ignored_... though.
