### ISSUE TITLE
Propose SETTING make_head_request=0 for engine=URL and url() table function

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#49028]
**Use case**

Currently, clickhouse makes two HTTP requests during SELECT data from `engine=URL()` and `url()` table function
first `HEAD` to receive Content-Length header and decide to allow parallel download
second `GET` to retrieve whole content body

For some dynamic HTTP endpoints, generating data twice maybe a heavy operation. 
Moreover, custom HTTP servers may not implement HEAD method support and return error.

**Describe the solution you'd like**
I propose to add `SETTING make_head_request=0` for `engine=URL()` and `url()` table function

**Comment by alexey-milovidov** [comment]
> Moreover, custom HTTP servers may not implement HEAD method support and return error.

This case should already be supported.

**Comment by fionera** [comment]
> Moreover, custom HTTP servers may not implement HEAD method support and return error.
Yes returning a "501 NotImplemented" is fine and CH still works

**Comment by Slach** [comment]
@fionera but also HEAD operation could be heavy and server could make work twice

**Comment by tolmalev** [comment]
Hi @alexey-milovidov!
I'd like to vote for this feature. As mentioned above user is not always in control of the server that returns data and in many cases server will implement HEAD by running full processing of a GET request and then only returning headers at the end.

Funny enough, ClikcHouse is one such servers.
If you try this, you'll see that clickhouse will execute the query twice.
```
SELECT * FROM URL("HTTP://{clickhouse-url}?query=SELECT ....")
```

This might look stupid to make a request from one clickhouse to another clickhouse using URL table engine but I think that there is a an actual usecase for this.
I was trying to use this approach to implement very cheap distributed processing of parquet files in S3 using Google Cloud Run.

The idea was to write the following query that will effectively process each file on a separate Cloud Run container wich will be both fast and super cheap.
```
SELECT
  col1,
  max(col2) 
FROM (
    SELECT * FROM URL("HTTP://{cloud-run-url}?query=SELECT col1, max(col2) as col2 from s3('f1.parquet') GROUP BY 1 FORMAT Native", 'Native')

   UNION ALL 

   SELECT * FROM URL("HTTP://{cloud-run-url}?query=SELECT col1, max(col2)  as col2 from s3('f2.parquet') GROUP BY 1 FORMAT Native", 'Native')

   ....
) group by 1
```

In cloud run you can't use `remote` table function because it uses native TCP interface and it's not supported by cloud run load balancer and it's also not possible to connect directly to cloud run nodes.
But HTTP interface is perfect for this. Cloud run will start multiple instances based on configuration of the service and will charge you only for the time spent on actually query execution on each node.
First query like this may take some time to start multiple nodes but then you may have 100s of nodes in idle state ready to process requests without paying anything for it.

**Comment by alexey-milovidov** [comment]
@tolmalev it is in progress, submitted by @fionera, in review by @vdimir.
