### ISSUE TITLE
How to return an error from External UDFs?

### ISSUE THREAD

**Issue by knoguchi** [ClickHouse/ClickHouse#49379]
How do you return an error from an external UDF?   An external UDF is a daemon-like process that constantly running, reading from STDIN, and writing response to STDOUT.   One way is to let the process die when an error happens but it's not ideal because starting up the process is costly, and also I cannot return a meaningful error message.

Suppose there is an external UDF `f(key)`.  A key is one of `a` or `b`.  When something else is passed, I would like to raise "invalid key" error, or at least raise a generic error without interrupting the process.

**Comment by knoguchi** [comment]
Thanks for the idea.  That's one way to achieve my goal.

Here is my random thought.  If we can introduce header+body just like HTTP, the UDF can return error easily.   There is a config `send_chunk_header` in the XML that adds a header in the request.  Similarly it could add something like receive_status_header.

**Comment by davenger** [comment]
Actually returning error from UDF might not be the best approach because typically a query processes not one row but a set of rows. If the query calls UDF for those rows and one of the rows makes the UDF return an error, then the whole query will fail as there is now way to return error for one row and valid results for other rows. So the approach with returning a tuple of result and status (or error message) columns from UDF addresses this scenario.
