### ISSUE TITLE
clickhouse server startup time optmize

### ISSUE THREAD

**Issue by athree** [ClickHouse/ClickHouse#49659]
### Discussed in https://github.com/ClickHouse/ClickHouse/discussions/49653

<div type='discussions-op-text'>

<sup>Originally posted by **athree** May  8, 2023</sup>
i have a ck instance with
6 databases
total 3000+ tables
total 1.2W+ parts
total 110GB data on disk

host machine is 64 cpu、128GB mem、1.8TB nvme ssd.

under these conditions, my ck instance restart used 2s+, and my purpose is < 1s;

so, i profile the startup process, while it does not used up cpu(400%)/mem(2.4%)/disk(15%);

follow common advice from community, i try enable merge_tree_metadata_cache and increase max_part_loading_threads to 128, it does not work;

so i logged the startup process and found metadata load is not the bottle neck (maybe my data is exactly small)
and the most  time cost stage is loadTablesInTopologicalOrder in src/Databases/TablesLoader.cpp::TablesLoader::loadTables， this function takes 50%+ time.

so  how can i optimize this stage to achieve my <1s purpose?

PS. Or maybe my starting point is wrong, optimize ck startup time under 1s is unrealistic?

</div>

**Comment by cangyin** [comment]
`src/Databases/TablesLoader.cpp::TablesLoader::loadTables` is indeed called by `loadMetadata()` from Server::main().

**Comment by athree** [comment]
> 

yes, it is. but i do not understand where the time cost? and if the cost is reasonable.

**Comment by cangyin** [comment]
> found metadata load is not the bottle neck
yes, it is. `loadMetadata()` calls `TablesLoader::loadTables`, and

> most time cost stage is loadTablesInTopologicalOrder in src/Databases/TablesLoader.cpp::TablesLoader::loadTables

**Comment by nickitat** [comment]
maybe it will solve your problem #43424

**Comment by athree** [comment]
> maybe it will solve your problem #43424

ths, i scan the commits, it really optimize the hotspot i profiled in my case. i will follow this feature.

And may i ask some other question please
1. how this feature #43424 works up server startup? it seems can optimize loadTableFromMetadata from a high percentage time cost to almost zero. is there any quantized test? @serxa 
2. is ck startup a strict and meaningful issue, because TablesLoader is not the only time cost in startup process. or in another way, how can i define a strict startup time? 1s? 3s? 1min?
3. is it possible to restart server in dual proces， to ensure ck startup as a constant.

**Comment by serxa** [comment]
> How this feature works?

If it is DatabaseOrdinary or any of its subclasses (Atomic/Replicated/etc) then it will be possible to enable async loading. And if it is enabled, then the behavior will be the following:
1. First, initiate async loading of all databases. At this stage, we will read .sql files and analyze dependencies. It is done synchronously and any error at this stage will lead to the shutdown of the whole server.
2. Start listening to connections, while tables are loading in the background.
3. Any query that requires a table will wait for exactly this table to be started up. And if loading fails query will rethrow an error (instead of shutting down the whole server). The table that is waited for by at least one query will be loaded with higher priority.
4. DDL queries on a database will wait for exactly that database to be started up (all the tables are started up + DDLWorker as well). The priority of load jobs for all tables in the database will be increased.

>  is there any quantized test?

Feature is far from completion at the moment and there are no tests yet.

> can i define a strict startup time? 1s? 3s? 1min?

There is no way to do it. This feature will speed up startup time, but there are no guarantees or deadlines.

> is it possible to restart server in dual process

Could you please clarify the question? What is dual process?

> to ensure ck startup as a constant.

Anyways, as you can see in p.1  loading will be still partly synchronous and depend on the amount of tables you have. Thus it will not be a constant. But maybe it will be good enough. Also, note that even after CH server start, queries to not-yet-loaded tables will hang and wait for the loading process to be done for the corresponding table.

**Comment by serxa** [comment]
@athree I think it is not possible. At some point in time, the new server will scan the directory with data parts and start loading them. And it will not take into account any new data parts that can be possibly added by the old server INSERTs, unfortunately.

**Comment by athree** [comment]
> @athree I think it is not possible. At some point in time, the new server will scan the directory with data parts and start loading them. And it will not take into account any new data parts that can be possibly added by the old server INSERTs, unfortunately.

> @serxa why new server will not take into account any new data parts? you means in current-framework/loading-process, increment data parts can not be replay to new server?

**Comment by serxa** [comment]
Yes, exactly. And I think, there might be much more problems to deal with beside unexpected data parts. CH loads metadata at start and holds it in memory never rechecking changes on filesystem.

**Comment by athree** [comment]
ok， thanks for your comments

**Comment by EscaperLL** [comment]
you can use <storage_file_read_method>io_uring</storage_file_read_method>
<local_filesystem_read_prefetch>true</local_filesystem_read_prefetch>
