### ISSUE TITLE
system.replication_queue table  There are a lot of outstanding GET_PART records, and the exception information is Not executing fetch of part ...

### ISSUE THREAD

**Issue by lxswbr** [ClickHouse/ClickHouse#49817]
Clickhouse version 22.3.2.1

It often happens that a large number of GET_PART operations accumulate in the replication_queue, resulting in the replica data not being synchronized in time. Our configuration is
background_pool_size 64
background_fetches_pool_size 12
background_schedule_pool_size 160

Later, the background_fetches_pool_size was increased to 96, and the problem still exists

How to solve this problem, what is the cause?

**Comment by tbragin** [comment]
Replication queue can get backed up because the replicas are not processing ingest workloads fast enough, for instance when merges are processing significantly slower than inserts. I’d look at overall system health first (especially around how data is inserted and how merges are happening), not at replication queue in isolation. 

Some useful resources:
https://clickhouse.com/docs/knowledgebase/exception-too-many-parts 
https://stackoverflow.com/questions/62489744/clickhouse-replica-out-of-sync 

Since the ticket is quite old and there has been no interaction on it, going to close it. Please re-open if new information comes in.
