### ISSUE TITLE
DB::Exception: Unknown codec family code: 80:

### ISSUE THREAD

**Issue by fasolwbanke** [ClickHouse/ClickHouse#50260]
We have  table with ReplicatedReplacingMergeTree engine. One of the replicas began to return error for query: 
```
SELECT * FROM TABLE WHERE DateTime >= '2023-05-01'

Unknown codec family code: 80: (while reading column Revenue): (while reading from part /opt/data/db/table/202305_97_97_0/ from mark 24 with max_rows_to_read = 65
```

> This error was happing after adding new column with ALTER TABLE ADD COLUMN, and ALTER UPDATE dictGet(?.., (Column1, Column2)) WHERE (Column3= **) AND (toYYYYMM(Date) = **) SETTINGS allow_nondeterministic_mutations

We fixed it by SYSTEM DROP MARK CACHE on problem replica, but think it's bug and need checkout this moment 
1. Add new column to table 
2. Update column with dictget
3. Try to select new column on all replicas to hand problem

**Comment by alexey-milovidov** [comment]
Which version?

**Comment by fasolwbanke** [comment]
23.4.2.11

**Comment by alexey-milovidov** [comment]
How can I reproduce it?

**Comment by pkit** [comment]
@alexey-milovidov I can repro it right now on a table that has a permanent `Unknown codec family code` error.
I have stopped merges and copied all parts off that table to a new CH and the problem does not reproduce.
So, it's clearly a caching problem. And it probably won't repro when I drop caches or restart that instance.
Now is the chance to debug it. Any ideas? We can talk on Telegram or Slack, if needed.
I can also tell you what is different in that instance as it reproduces that problem once per month or two (yes, very rarely):
- it uses RowBinary for inserts, because of `client-rs`
- it uses a lot of RMVs because it ETLs from Postgres

**Comment by alexey-milovidov** [comment]
@pkit, create a new issue with a reproducer.
