### ISSUE TITLE
sumMap/minMap/maxMap do not support IPv4 / IPv6 as a map key anymore

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#50549]
```sql
select sumMap(map(i, c)) from (select toIPv4('0.0.0.0') i, 1 c);

select sumMap(map(i, c)) from (select toIPv6('::ffff:0.0.0.0') i, 1 c);

select minMap(map(i, c)) from (select toIPv4('0.0.0.0') i, 1 c);

select minMap(map(i, c)) from (select toIPv6('::ffff:0.0.0.0') i, 1 c);
```

I found it during testing

```sql
select cityHash64(hex(sumMapState(map(ip_ipv4, c)))) s from (select number::UInt32::IPv4 ip_ipv4, 1::UInt64 c from numbers(5))
```

**Comment by yakov-olkhovskiy** [comment]
besides IP types support (which I will fix in #50551) these functions are broken in general:
https://fiddle.clickhouse.com/639710ad-0315-4bdd-a914-ace49a302690
https://fiddle.clickhouse.com/9be6de52-c73b-4eb9-a8da-16dad48af7d4

The issue seems to be that there was change in implementation and state of these aggregate functions changed somehow - in examples above I deduced it to two specific keys - they appear to be swapped in these two implementations.
So, the support for IP types I will fix in aforementioned PR, however I will remove test for them since functions are broken for different reason than IP types - will fix it in separate PR.

**Comment by yakov-olkhovskiy** [comment]
simplified request:
```
SELECT cityHash64(hex(minMapState(map(ip, CAST('1', 'Int64'))))) AS minMapState FROM (SELECT reinterpretAsFixedString(number) AS ip
    FROM numbers(1010011135, 2)
    ORDER BY ip ASC
)
```
results will be different for 22.12 and latest
appears only for string - removing `reinterpretAsFixedString` fixes the issue, so, apparently, something in string sorting changed somewhere in-between...

**Comment by yakov-olkhovskiy** [comment]
After some investigation - map state based on `std::unordered_map`:
https://github.com/ClickHouse/ClickHouse/blob/master/src/AggregateFunctions/AggregateFunctionMap.h#L60
so, it's intrinsically non-stable. It doesn't impact serialization/deserialization of -MapState, and I don't see any meaningful use for map stability, though it worth mentioning in the doc.

**Comment by den-crane** [comment]
You can move tests for Map states to the section with `any` functions where I test against a single ip, better than nothing.
