### ISSUE TITLE
test_seekable_formats is flaky

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#50678]
https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3NlZWthYmxlX2Zvcm1hdHMlJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIGRlc2MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQo=

https://s3.amazonaws.com/clickhouse-test-reports/0/036ddcd47baf88ab0c360efe647e01060d1ce636/integration_tests__asan__[5_6].html

https://s3.amazonaws.com/clickhouse-test-reports/0/5d0522cfa6045ccecc77f79dd12b043260e1545b/integration_tests__asan__[5_6].html

https://s3.amazonaws.com/clickhouse-test-reports/0/e1889ffb3abe0eb1cc46e9a02ec1287a73b466ee/integration_tests__tsan__[5_6].html

https://s3.amazonaws.com/clickhouse-test-reports/0/4b1bb75a07b93e15adeef11f0392ac34115f5a05/integration_tests__tsan__[5_6].html

**Comment by binmahone** [comment]
hi @KochetovNicolai what's the issue with #50102 ?

**Comment by al13n321** [comment]
> https://github.com/ClickHouse/ClickHouse/pull/50102 ?

Why? The query returns many different PRs.

**Comment by nickitat** [comment]
> > #50102 ?
> 
> Why? The query returns many different PRs.

because it didn't fail for almost a month and after the pr started to fail [almost every day](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCAgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlICcyMDIzLTAxLTAxJyA8PSBjaGVja19zdGFydF90aW1lIGFuZCB0ZXN0X25hbWUgbGlrZSAnJXRlc3Rfc2Vla2FibGVfZm9ybWF0cyUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==)

**Comment by al13n321** [comment]
https://github.com/ClickHouse/ClickHouse/pull/50102 was merged 3 days ago.

**Comment by Avogar** [comment]
The memory exceeds while creating new segment in ParalleReadBuffer. It's totally ok I guess. The test checks that we don't load the whole file in the memory and read it using seeks. I suggest just set `max_download_threads=1` to not use ParalleReadBuffer in this test
