### ISSUE TITLE
A new format similar to RowBinary to support per-record omitted values

### ISSUE THREAD

**Issue by mzitnik** [ClickHouse/ClickHouse#50854]
**Use case**

Currently, we do not have a way to insert default values to ClickHouse when using native/row binary protocol.
The way we overcome that issue currently is to describe the table first and insert the default value (not so elegant). Still, we encounter a more significant problem when the default is computed from the server side.

**Describe the solution you'd like**
- Extending the current protocol 
- Adding a version to the protocol so it will be easier to support 

**Where it will help**
Various integrations that ingest data can benefit from it, simplify current logic, and unblock inserting data when there is a default value.  

**Reference**
[bcp](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/keep-nulls-or-use-default-values-during-bulk-import-sql-server?view=sql-server-ver16)

**Comment by tavplubix** [comment]
AFAIK, the native protocol already supports default values. Could you please clarify how exactly you insert data and what behavior you expect from the server? 

> Still, we encounter a more significant problem when the default is computed from the server side.

What problem?

**Comment by genzgd** [comment]
The problem arises with clients like clickhouse-go, python-driver, and JDBC (using row binary).  If the default value is based on some expression like dictGet or other server side computation, there's no way (that I know of) to indicate such a calculated expression should be applied when the column data is inserted.

(Maybe I'm not understanding something about the native protocol, but again we have similar issues with RowBinary).

**Comment by mzitnik** [comment]
In the java client we are using RowBinary protocol in some cases where the column has a default value (server computed) in the client, we can not guess the computed value, so having the option to tell the server in the protocol that we need the default will solve the issue

**Comment by zhicwu** [comment]
https://github.com/ClickHouse/clickhouse-java/issues/1296#issuecomment-1571088566 is a workaround but really should be automated.

**Comment by Avogar** [comment]
In RowBinary we cannot implement inserting NULL as default, because this format doesn't contain information about data types. So, for non-Nullable column we cannot understand if the value is NULL or not, we just read the binary representation of requested type. For Nullable columns we always write additional byte before the value that indicates if it's null or not.

To support defaults in RowBinary format we can add additional byte (0 or 1) before each column that will indicate if it's default or not (0 - not, 1 - yes). So, if it's 0, we just read the value after it, if it's 1, we don't read anything and insert default. We must add this additional byte for every column, otherwise we cannot understand when we need to read it and when we don't. It will brake current RowBinary specification, so we have 2 options:
1) Add a new setting to RowBinary format that enables new behaviour with defaults
2) Add new format like RowBinaryWithDefaults for this purpose.

I think we can do the second option as it will be more convinient for users (or both if setting will be useful for someone).
This will require changing the code of client side to support new format (adding additional byte 0 or 1 before all values and adding new method lile setDefault). It will work also for Nullable column, we will just have 2 extra bytes instead of 1.

I don't see other good ways how to support defaults in RowBinary format.

@alexey-milovidov WDYT?

Native format supports inserting `NULL` as default. But it won't work if column is actually `Nullable` and we want to insert default value.
Example:
Native data with 2 NULL values:
```
clickhouse-client -q "select NULL::Nullable(UInt32) as a, NULL::Nullable(UInt32) as b format Native" > data.native
clickhouse-client -q "create table test(a UInt32 DEFAULT 42, b Nullable(UInt32) DEFAULT 42) engine=MergeTree order by a"
clickhouse-client -q "insert into test from infile 'data.native'"
clickhouse-client -q "select * from test"
42    \N
```

So, we cannot insert NULL as default value for Nullable column using Native format (and actually any other format) and it cannot be fixed. But we still can insert defaults for Nullable column if if block just doens't contain this column at all:

```
clickhouse-client -q "select NULL::Nullable(UInt32) as a format Native" > data.native
clickhouse-client -q "create table test(a UInt32 DEFAULT 42, b Nullable(UInt32) DEFAULT 42) engine=MergeTree order by a"
clickhouse-client -q "insert into test from infile 'data.native'"
clickhouse-client -q "select * from test"
42    42
```

**Comment by genzgd** [comment]
I also prefer adding a new `WithDefaults` format.  I would also like to add something similar to the Native format (used over HTTP by both clickhouse-go and the clickhouse-connect Python client), since there's no way to specify "null" using Native format over HTTP (other than the null map) that I know of.

If it's an entirely new format, I wonder if we could get away with using just one byte for the marker for either nullable or non-nullable columns -- `0x00` for actual value follows, `0x01` for NULL, `0x02` for `server calculated default`.

**Comment by Avogar** [comment]
> I wonder if we could get away with using just one byte for the marker for either nullable or non-nullable columns 

Sure, one byte for Nullable is good idea.

> I would also like to add something similar to the Native format

Maybe we can also add new format NativeWithDefaults. Need to think about it

**Comment by mzitnik** [comment]
As we already discuss, I also like  the second option since it makes the solution more complete by supporting both Nullable and Defaults.

**Comment by zhicwu** [comment]
It's more of a compatibility issue for `clickhouse-java`. In the beginning, Java client uses `TabSeparated` format, which supports passing NULL to column with default values, which stopped working after switching to `RowBinary`. `input` function is a workaround that I know of, but it's very inconvenient to use.

**Comment by mzitnik** [comment]
I am adding to @genzgd and @zhicwu comments here. 
Supporting defaults will improve 
- Performance. 
- Compatibility and protocol completeness. 
- Less data going through the network (compared with JSON) also, in many cases, will reduce the cost of outgoing traffic.

**Comment by alexey-milovidov** [comment]
Where do you get the fact that some values in some records have to be default?

**Comment by Avogar** [comment]
Another alternative to `RowBinaryWithDefaults` is smth like `NamedRowBinary` with column name before each column instead of flag for default. It's more flexible: columns can be in arbitrary order (we will match them by names), if you want to insert the default value, just skip the column in the row (similar how it's dont in JSON/other formats with names). It will be similar to BSON format, but less complicated.

**Comment by Avogar** [comment]
If there is no objections, I will start implementing `RowBinaryWithDefaults` this week.

**Comment by alexey-milovidov** [comment]
Ok, although there are higher priority tasks:
- #33165
- #47207
- #42419
- #40622
- #39636
- #37452
- #34854

**Comment by mzitnik** [comment]
@Avogar ping when is done so we could start updating language drivers and other dependent integrations
