### ISSUE TITLE
http_timeout value for clickhouse-odbc-bridge is too large

### ISSUE THREAD

**Issue by xx25** [ClickHouse/ClickHouse#5089]
clickhouse-odbc-bridge starts with the following parameters:
/usr/bin/clickhouse-odbc-bridge odbc-bridge --http-port 9018 --listen-host localhost --http-timeout 1800000000

Value for http_timeout is hardcoded in sources and too large, so dictionaries are not working properly. 
If we launch it manually with lower value:
/usr/bin/clickhouse-odbc-bridge odbc-bridge --http-port 9018 --listen-host localhost --http-timeout 600
dictionaries are working properly.

Latest stable version 19.5.3.8 and testing 19.6.1.357 are affected.

**Comment by filimonov** [comment]
Broken since 19.1.

May be seconds vs microseconds issue. Jdbc bridge need to be checked. 

Also it looks like http_timeout misused - which leads to hanging requests like this

```
curl -X POST -D- "http://localhost:9018/identifier_quote?connection_string=DSN%3Dwhatever"
```

**Comment by alesapin** [comment]
It's not hardcoded for a long time, we use `http_receive_timeout` setting from query settings https://github.com/clickhouse/ClickHouse/blob/master/src/Storages/StorageXDBC.cpp#L128. By default, it's `DEFAULT_HTTP_READ_BUFFER_TIMEOUT=1800` and when we start bridge we convert this value to microseconds. It's OK because bridge uses this option with a default timespan constructor which also accepts microseconds https://github.com/clickhouse/ClickHouse/blob/master/programs/odbc-bridge/ODBCBridge.cpp#L172-L173 https://github.com/ClickHouse-Extras/poco/blob/master/Foundation/include/Poco/Timespan.h#L39.
