### ISSUE TITLE
use decimal type with pow function

### ISSUE THREAD

**Issue by netchose** [ClickHouse/ClickHouse#51073]
hello,

version 23.5.2

`SELECT pow(toDecimal32(2, 2), 3)`

produce DB::Exception: Illegal type Decimal(9, 2) of argument of function pow: While processing pow(toDecimal32(2, 2), 3). (ILLEGAL_TYPE_OF_ARGUMENT)

thanks a lot

**Comment by mgorshkov** [comment]
I am currently working on adding support for decimal types in pow function. Please assign this task to me if possible.

**Comment by mgorshkov** [comment]
@KochetovNicolai @kitaisreal @4ertus2
Hello!

- I did research on how Decimals are processed in CH functions:

+, -, *, / - 2 arguments, supported in all combinations with other types (FunctionBinaryArithmetics/DecimalBinaryOperation - does scaling to adjust precision)

multiplyDecimal, divideDecimal - 2 arguments, only Decimals supported (FunctionsDecimalArithmetics, with bound checks)

log - 1 argument, supported (FunctionMathUnary)
lgamma - 1 argument, supported (FunctionMathUnary)
sin - 1 argument, supported (FunctionMathUnary)
tan - 1 argument, supported (FunctionMathUnary)
exp2 - 1 argument, supported (FunctionMathUnary)
…

pow - 2 arguments, not supported (FunctionMathBinaryFloat64) 
atan2 - 2 arguments, not supported (FunctionMathBinaryFloat64) 
max2 - 2 arguments, not supported (FunctionMathBinaryFloat64)
min2 - 2 arguments, not supported (FunctionMathBinaryFloat64)
hypot - 2 arguments, not supported (FunctionMathBinaryFloat64)

So, we need to support Decimals in pow() function (both arguments). For other binary functions, like atan2 or max2, this is done for free.  
- The proposal is to adapt FunctionMathBinaryFloat64 for handling Decimals (since we don't need scaling, but cast to Float64 only), exactly as it is done in FunctionMathUnary.
- Class rename is not needed, since the implementation keeps returning Float64, but extends the functionality to handle Decimals as well.
- Outline of necessary steps:

1. allow decimals in check_argument_type;
2. check for ColumnVectorOrDecimal for both arguments in executeImpl lambda;
3. split executeTyped to executeTyped and executeInIterations, like in FunctionMathUnary;
4. overload the combinations of parameter types in executeTyped (ColumnDecimal + ColumnDecimal, ColumnDecimal + ColumnVector, ColumnVector + ColumnDecimal, ColumnVector + ColumnVector);
5. perform DecimalsUtils::convertTo< Float64 > for ColumnDecimal.

- This approach is proven to work fine:
![pow](https://github.com/ClickHouse/ClickHouse/assets/5475799/54a2e8c7-510e-4ff5-a62d-7be8f6f9b801)

- Please give some feedback if this approach is ok for the community.

**Comment by rvasin** [comment]
@rschu1ze @azat Could you please comment if the selected approach is OK, so Mikhail could fine-tune the implementation and create a PR.

**Comment by Algunenano** [comment]
I think it makes sense for pow() of decimal to operate and return decimal, not float. Otherwise what's the point?

**Comment by mgorshkov** [comment]
> I think it makes sense for pow() of decimal to operate and return decimal, not float. Otherwise what's the point?

Unary functions, like sinus, always return Float64, as I understand, but for some binary functions, like max2/min2 it makes sense returning decimal, if both arguments are decimals, to save the precision, but what if one is decimal, and the other one is float?
The underlying C API for pow, atan2, and hypot accepts doubles, and return doubles, so the client will not benefit from returning decimal for these.

**Comment by Algunenano** [comment]
Are we still taking about pow()? Because I understand why sin() would return a Float, but not why pow() would loose precision unnecessarily.

> The underlying C API for pow, atan2, and hypot accepts doubles, and return doubles, so the client will not benefit from returning decimal for these.

Then maybe we need to not use the underlying C API to implement this. The same way we don't use the std for add 2 decimals.

**Comment by mgorshkov** [comment]
> Are we still taking about pow()? Because I understand why sin() would return a Float, but not why pow() would loose precision unnecessarily.
> 
> > The underlying C API for pow, atan2, and hypot accepts doubles, and return doubles, so the client will not benefit from returning decimal for these.
> 
> Then maybe we need to not use the underlying C API to implement this. The same way we don't use the std for add 2 decimals.

Ok, I see. I need to think about it.

**Comment by rvasin** [comment]
I think decimals are good (and used in production this way) for currency calculations. So it makes sense to use decimal arithmetic for addition and subtraction (and OK for multiplication/division by integers). But not for functions like `pow`. While it's OK to pass decimal arguments to `pow`.

> Are we still taking about pow()? Because I understand why sin() would return a Float, but not why pow() would loose precision unnecessarily.
> 

When using

```sql
SELECT pow(toDecimal32(2.12323, 2), toDecimal32(3.12323, 3)) 
```

What should be the resulting precision? 2, 3, 6?

So I think this we still use C `pow` function which returns double and we need to return Float64.


 
> Then maybe we need to not use the underlying C API to implement this. The same way we don't use the std for add 2 decimals.

For addition/subtraction it's OK to use decimal arithmetic implemented in ClickHouse. But not for functions like `pow`, `sin`, `cos`.

**Comment by Algunenano** [comment]
> So I think this we still use C pow function which returns double and we need to return Float64.

Just because we need to think how to do it properly it's not ok to do it wrong.

```
SELECT
    CAST('0.1', 'Decimal(20, 10)') AS a,
    a * a AS b,
    toTypeName(b)

Query id: 4fe512f9-ed3d-4d43-8625-b42d4d8397a6

   ┌───a─┬────b─┬─toTypeName(b)───┐
1. │ 0.1 │ 0.01 │ Decimal(38, 20) │
   └─────┴──────┴─────────────────┘
```

Pow() is closer to multiply than it is to sine, as the result of sin() is known and limited and the we can understand the loss in precision. What's the point of having a fixed point type if you are going to always use the flawed floating point type?

**Comment by mgorshkov** [comment]
> > So I think this we still use C pow function which returns double and we need to return Float64.
> 
> Just because we need to think how to do it properly it's not ok to do it wrong.
> 
> ```
> SELECT
>     CAST('0.1', 'Decimal(20, 10)') AS a,
>     a * a AS b,
>     toTypeName(b)
> 
> Query id: 4fe512f9-ed3d-4d43-8625-b42d4d8397a6
> 
>    ┌───a─┬────b─┬─toTypeName(b)───┐
> 1. │ 0.1 │ 0.01 │ Decimal(38, 20) │
>    └─────┴──────┴─────────────────┘
> ```
> 
> Pow() is closer to multiply than it is to sine, as the result of sin() is known and limited and the we can understand the loss in precision. What's the point of having a fixed point type if you are going to always use the flawed floating point type?

You see, we may do the following:
1. In the first phase we can make a Float64 type cast inside CH instead of having the client do this manually (probably, the initial ask was about this). That's what I suggested. This will not spoil the precision compared to what we have now.
2. In the second phase we can tune up "the flawed" functions: pow(), min2(), max2().
What do you think about this?

**Comment by Algunenano** [comment]
2 phases and changing the return type is a breaking change that I'd rather not have.
