### ISSUE TITLE
Consistent ANY JOINs

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#5126]
I am not sure is it bug or not (and it does not bother me, just note from telegram).

create table l(A Int64, B Int64) Engine=Memory;
create table r(A Int64, C Int64) Engine=Memory;
insert into l values(1,1), (2,2);
insert into r values(1,1), (1,4), (1,5), (3,3);

select A,B,C from l any left join r using(A);
```
┌─A─┬─B─┬─C─┐
│ 1 │ 1 │ 1 │
│ 2 │ 2 │ 0 │
└───┴───┴───┘
```

select A,B,C from r any right join l using(A)
```
┌─A─┬─B─┬─C─┐
│ 1 │ 1 │ 1 │
│ 1 │ 1 │ 4 │
│ 1 │ 1 │ 5 │
└───┴───┴───┘
┌─A─┬─B─┬─C─┐
│ 2 │ 2 │ 0 │
└───┴───┴───┘
```

**Comment by abyss7** [comment]
Yes, it's definitely the bug. Will find out which versions it affects.

**Comment by 4ertus2** [comment]
The problem is
then we do ANY JOIN we make hash table with one value per key (for right table). That's OK for ANY LEFT JOIN. It's not OK for ANY RIGHT JOIN cause user expects symmetry of left and right joins. And also it's not clear what would be best for INNER & FULL ones. It could be interesting option to get any value from both sides for ANY INNER JOIN. For now it works like LEFT one.

It's possible to make correct ANY RIGHT JOIN but it would be slower than LEFT one cause we need to save vectors instead of one value in hash table like we do for ALL JOINS.

**Comment by 4ertus2** [comment]
Related #6351

**Comment by 4ertus2** [comment]
There's a setting any_join_distinct_right_table_keys now that disables incorrect ANY JOINS.
Default behaviour is reserved for SEMI-JOIN like one:
ANY LEFT JOIN - distinct keys in the right table (it's already OK)
ANY RIGHT JOIN - distinct keys in the left table (TODO)
ANY INNER | FULL JOIN - distinct keys in both tables (TODO)

**Comment by 4ertus2** [comment]
New `ANY JOIN` logic would be default starting from 19.18. Old logic is default before 19.14. Versions 19.14 - 19.17 has no default logic for `ANY INNER` and `ANY RIGHT` joins (it's possible to enable old logic using `any_join_distinct_right_table_keys`)
