### ISSUE TITLE
Catched `Logical error: 'Distributed task iterator is not initialized'.`

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#51486]
**Describe the bug**
A link to the report https://s3.amazonaws.com/clickhouse-test-reports/51478/5fdb19672bc443222560df00e0b76add05a1ad10/fuzzer_astfuzzerasan/report.html

**How to reproduce**
The query in the report is `SELECT number % NULL, NULL, sum(number) AS val FROM remote('127.0.0.{2,3}', numbers(toUInt64(-1))) GROUP BY number, number % 1023 WITH CUBE ORDER BY toUInt16(10) DESC NULLS LAST SETTINGS group_by_use_nulls = 1`

**Comment by nikitamikhaylov** [comment]
@rschu1ze @azat 

`SELECT number FROM remote('127.0.0.{2,3}', numbers(toUInt64(-1)))`

The problem is that we throw an exception during writing the progress (`total_size_rows` is exactly `toUInt64(-1)` which is greater than `2^63 - 1`). The exception introduced here https://github.com/ClickHouse/ClickHouse/pull/48154

For the data written to socket looks like this:

```
Server writes:
[Progress packet ID][Progress packet data.. (incomplete)][Exception packet ID][Exception data]..........
Client reads:
[Progress packet ID][Progress packet data ..........................................][Another packet ID]
```

And so `Another packet ID` by a chance is `Protocol::Server::ReadTaskRequest` (it is almost random).

I need some guidance on how to fix it properly. Several observations: 
- Looks like we have to be able to encode numbers from in `2^63 - 1` ... `2^64 - 1` range. I suggest writing the function like this. Thoughts? 
```
inline void writeVarUIntV2(UInt64 x, WriteBuffer & ostr)
{
    UInt64 first = std::min(VAR_UINT_MAX, x);
    UInt64 second = std::min(VAR_UINT_MAX, x - first);

    writeVarUInt(first, ostr);
    writeVarUInt(second, ostr);
}
```
- We can't throw any exceptions after we wrote Packet ID to the socket. Looks like we have to move sanity checks out of `writeVarUIntV2` ?

**Comment by azat** [comment]
>Looks like we have to be able to encode numbers from in 2^63 - 1 ... 2^64 - 1 range. I suggest writing the function like this. Thoughts?

But how this will preserve the compatibility with older versions?
The reason that is an assertion instead of something like this is that otherwise it will breaks the compatibility:

```patch
diff --git a/src/IO/VarInt.h b/src/IO/VarInt.h
index f6441391c8f..8e3c677e1f6 100644
--- a/src/IO/VarInt.h
+++ b/src/IO/VarInt.h
@@ -101,7 +101,7 @@ template <bool fast>
 inline void readVarUIntImpl(UInt64 & x, ReadBuffer & istr)
 {
     x = 0;
-    for (size_t i = 0; i < 9; ++i)
+    for (size_t i = 0; i < 10; ++i)
     {
         if constexpr (!fast)
             if (istr.eof()) [[unlikely]]
@@ -168,7 +168,7 @@ inline void writeVarUInt(UInt64 x, WriteBuffer & ostr)
     if (x > VAR_UINT_MAX) [[unlikely]]
         throwValueTooLargeForVarIntEncoding(x);
 
-    for (size_t i = 0; i < 9; ++i)
+    for (size_t i = 0; i < 10; ++i)
     {
         uint8_t byte = x & 0x7F;
         if (x > 0x7F)
```

>We can't throw any exceptions after we wrote Packet ID to the socket. Looks like we have to move sanity checks out of writeVarUIntV2 ?

Actually I think it should be OK, since you can write a client that will do so, and the server should not crash.
Right now it is LOGICAL_ERROR and it does not crash in the release build
But I think (and actually I thought about this before, since I already saw this LOGICAL_ERROR but for different reason - using old go driver that does not implements TCP protocol correctly) it is better to replace LOGICAL_ERROR with something different and maybe there is something else that should be fixed as well. Thoughts?

**Comment by rschu1ze** [comment]
> Right now it is LOGICAL_ERROR and it does not crash in the release build

Where exactly does `LOGICAL_ERROR` occur here?

Thoughts:
- The concrete issue is IMHO not as bad as it appears. Sending more than `1<<63 - 1)` rows to the client should rarely happen in practice.
- But: there were similar exceptions when writing var-ints from different callstacks by AST Fuzzer in the past:
    - https://s3.amazonaws.com/clickhouse-test-reports/0/fa5b2bd4a5b02336bca8837c473a7124f8ecedf2/fuzzer_astfuzzerasan/report.html
    - https://s3.amazonaws.com/clickhouse-test-reports/0/9331c6c260543680715ac7247be7160ff3e28f30/fuzzer_astfuzzerubsan/report.html
- Nobody knows for sure if there are not more hidden issues (there are too many places which write/read var-uint), and in particular if the handling on the server- or client side is correct if there is an exception during data transport.

The best solution is to lift the artificial upper limit for var-int. This will break compatibility and make the code (as far as I see) quite ugly because we are not simply adding a new field to the protocol but changing existing fields:

E.g. today we have

``` cpp
void ProgressValues::write(WriteBuffer & out, UInt64 client_revision) const
{
    writeVarUInt(read_rows, out);
    writeVarUInt(read_bytes, out);
    /// In new TCP protocol we can send total_bytes_to_read without total_rows_to_read.
    /// If client doesn't support total_bytes_to_read, send approx total_rows_to_read
    /// to indicate at least approx progress.
    if (client_revision < DBMS_MIN_PROTOCOL_VERSION_WITH_TOTAL_BYTES_IN_PROGRESS && total_bytes_to_read && !total_rows_to_read)
        writeVarUInt(getApproxTotalRowsToRead(read_rows, read_bytes, total_bytes_to_read), out);
    else
        writeVarUInt(total_rows_to_read, out);
    if (client_revision >= DBMS_MIN_PROTOCOL_VERSION_WITH_TOTAL_BYTES_IN_PROGRESS)
    {
        writeVarUInt(total_bytes_to_read, out);
    }
    if (client_revision >= DBMS_MIN_REVISION_WITH_CLIENT_WRITE_INFO)
    {
        writeVarUInt(written_rows, out);
        writeVarUInt(written_bytes, out);
    }
    if (client_revision >= DBMS_MIN_PROTOCOL_VERSION_WITH_SERVER_QUERY_TIME_IN_PROGRESS)
    {
        writeVarUInt(elapsed_ns, out);
    }
}
```

which will become
```cpp
void ProgressValues::write(WriteBuffer & out, UInt64 client_revision) const
{
    if (client_revision < DBMS_MIN_PROTOCOL_VERSION_WITH_FULL_RANGE_VARINT
    {
        writeVarUInt(read_rows, out);
        writeVarUInt(read_bytes, out);
        /// In new TCP protocol we can send total_bytes_to_read without total_rows_to_read.
        /// If client doesn't support total_bytes_to_read, send approx total_rows_to_read
        /// to indicate at least approx progress.
        if (client_revision < DBMS_MIN_PROTOCOL_VERSION_WITH_TOTAL_BYTES_IN_PROGRESS && total_bytes_to_read && !total_rows_to_read)
            writeVarUInt(getApproxTotalRowsToRead(read_rows, read_bytes, total_bytes_to_read), out);
        else
            writeVarUInt(total_rows_to_read, out);
        if (client_revision >= DBMS_MIN_PROTOCOL_VERSION_WITH_TOTAL_BYTES_IN_PROGRESS)
        {
            writeVarUInt(total_bytes_to_read, out);
        }
        if (client_revision >= DBMS_MIN_REVISION_WITH_CLIENT_WRITE_INFO)
        {
            writeVarUInt(written_rows, out);
            writeVarUInt(written_bytes, out);
        }
        if (client_revision >= DBMS_MIN_PROTOCOL_VERSION_WITH_SERVER_QUERY_TIME_IN_PROGRESS)
        {
            writeVarUInt(elapsed_ns, out);
        }
    }
    else
    {
        writeVarUIntFullRange(read_rows, out);
        writeVarUIntFullRange(read_bytes, out);
        writeVarUIntFullRange(total_rows_to_read, out);
        writeVarUIntFullRange(total_bytes_to_read, out);
        writeVarUIntFullRange(written_rows, out);
        writeVarUIntFullRange(written_bytes, out);
        writeVarUIntFullRange(elapsed_ns, out);
    }
}
```

The same is needed in all other protocol handlers. On the other hand, it is a chance to get rid of (some) old protocol versions, like in the example. I am not very familiar with the TCP protocol, maybe someone who knows it better can say if this is feasible?

**Comment by rschu1ze** [comment]
> Where exactly does LOGICAL_ERROR occur here?

Ah, just had to read the title 😄

**Comment by rschu1ze** [comment]
@azat Another idea: What about simply removing the upper-bound check in VarInt on the server side and write the full range (10 bytes at most instead of 9 bytes right now)? Current client will understand the format, but old clients will potentially throw an exception. Basically intentionally breaking compatibility to fix technical debt. What sounds terrible isn't terrible: 1. the current exception on the server side will be replaced by one on the client side where it can be identified quickly and fixed in the client. 2. The likelihood for that to happen is superlow and so far any such cases were generated by fuzzers.

**Comment by azat** [comment]
>the current exception on the server side will be replaced by one on the client side where it can be identified quickly and fixed in the client

You are talking about this particular case I guess, but there are more places where variable length integers is used.

>Current client will understand the format, but old clients will potentially throw an exception

Sounds tricky, but as long as you are fine with this, I'm fine as well.

P.S. Hope that it will not break in some odd place... Though it seems that everything should be OK, the only thing is that it is better not to mix older versions with newer.
