### ISSUE TITLE
Recovery after data loss doesn't work with more than 2 replicas per shard

### ISSUE THREAD

**Issue by vavrusa** [ClickHouse/ClickHouse#520]
This is a bit vague report, but we had an issue when one node was put back to production after a disk failure and [couldn't recover from peer replicas][1]. What happened was we put the node back to production, it started receiving parts, but the connection always broke before the part transfer was finished. There was a lot of network and disk i/o but nothing finished successfully, so the disk usage wasn't going up and the instance never recovered. Another strange thing is, when we stopped the faulty instance, the peer replicas continued to read and transmit parts (despite the receiver was down), so I had to restart the peer replicas as well to stop the disk i/o.

We did two things to mitigate the issue:
* Switch from xfs to ext4, the xfs nodes experienced strange performance degradation under load where overall load went up 8x and disk i/o almost stalled. It was also impossible to recover from replicas on xfs due to connection breaks, while it progressed from nodes on ext4.
* Change the affected node configuration to only two replicas per shard, so it is forced to recover from only one replica. This works even with xfs nodes, but makes recovery tedious.

I suspect the core of the issue is that receiving replica cannot moderate senders when it's not able to keep up which leads to connection breaks, there is currently no way to throttle throughput or have any sort of backpressure - the sender replicas just keep sending. I'm not sure how are you dealing with this, but this also affects read query performance while the replication is in progress. The secondary issue is that xfs is not really recommended as a filesystem, we're still investigating what causes this issue.

[1]: https://groups.google.com/forum/#!topic/clickhouse/uq9891JyV7M

**Comment by alexey-milovidov** [comment]
> I suspect the core of the issue is that receiving replica cannot moderate senders when it's not able to keep up which leads to connection breaks, there is currently no way to throttle throughput or have any sort of backpressure - the sender replicas just keep sending.

Yes, this is the cause.
We currently have a task to introduce following limits:
- max number of concurrent fetches (on fetching replica), per table;
- max number of concurrent fetches (on fetching replica), for all server;
- max number of concurrent sends (on source replica), per table;
- max number of concurrent sends (on source replica), for all server;

**Comment by alexey-milovidov** [comment]
We have experienced the following cases:

1. When replica is repaired, data is downloaded by too large number of parallel connections (equals to background_pool_size = 16 by default). As even one connection could utilize the network, each connection only downloaded data slower while total throughput is the same. It also leads to more random IO on source replica, raising the possibility of connection loss.

2. Fetches from source replica during repair could saturate all background_pool_size. Background pool is also used for background merges. So, during repair of one table, other tables on same server could become too unmerged.

3. One of our users installed a cluster with 10 replicas. When data is inserted to one replica, all 9 another replicas instantly request that data from that single replica, that leads to IO and network overload.

4. Another user have defined external dictionaries with cache layout and lifetime of 4 hours. Everything was fine, but when we have to repair replica, it could not repair due to connection loss every 4 hours. This was due to high number of created network connections when updating data for external dictionary. Solution was to always specify interval for randomization of lifetime (min and max).

**Comment by proller** [comment]
already in master:
```
<merge_tree>                                                                          
  <replicated_max_parallel_sends_for_table>2</replicated_max_parallel_sends_for_table>
  <replicated_max_parallel_sends>4</replicated_max_parallel_sends>                    
</merge_tree>                                                                         

<merge_tree>                                                                              
  <replicated_max_parallel_fetches_for_table>2</replicated_max_parallel_fetches_for_table>
  <replicated_max_parallel_fetches>4</replicated_max_parallel_fetches>                    
</merge_tree>                                                                             
```

**Comment by alexey-milovidov** [comment]
Marek, please, share your observations if will be any.

**Comment by vavrusa** [comment]
Will do on the next replication, thanks!
Is the new merge tree settings default or should I set it explicitly?

**Comment by alexey-milovidov** [comment]
New settings are default.

**Comment by alexey-milovidov** [comment]
We have tested new settings and convinced, that they are still not production ready.
The settings was disabled by default in master.

**Comment by bobrik** [comment]
Not sure if it's the right issue to complain, but during lengthy recovery all workers are busy replicating and merge queue never decreases.

![image](https://user-images.githubusercontent.com/89186/34368341-0e478a0c-ea68-11e7-8098-267e5c000300.png)

**Comment by alexey-milovidov** [comment]
It depends... Does the queue disappear after successful recovery? Does the recovery goes slower than expected? Do you see errors in log about failed fetches?

This issue is about using excessive number of network connections during replica recovery,
that can lead to slower recovery and periodic failures in fetching parts during recovery.

**Comment by bobrik** [comment]
It definitely disappears at the end, but it takes hours to take to the end. My main issue is that read queries run a lot slower because there's no throttling. We see writes at 1.8GB/s when reads from 2 replicas saturate disks at ~900MB/s.

Should I file an issue to throttle recovery bandwidth (hopefully with zookeeper override support)?

While I am at it, should I also file an issue for JBOD support in some way? We have 12 x 10TB disks in RAID0 as of now and it will be even more painful to replicate full 100TB datasets even across 50G network (disks will saturate a lot sooner anyway).
