### ISSUE TITLE
Crash bug: ClickHouse 23.7.1.857 Server and Client crashed by create table and insert statements

### ISSUE THREAD

**Issue by fuboat** [ClickHouse/ClickHouse#52026]
**Describe the bug**
 ClickHouse 23.7.1.857 Server and Client crashed by create table and insert statements.
When using the ClickHouse client to run the SQL statements, the **ClickHouse Client** terminated by SIGABRT.
When using the MySQL client or ODBC to run the SQL statements, the **ClickHouse Server** terminated by SIGSEGV.

**How to reproduce**
The SQL statement to reproduce:
```SQL
CREATE TABLE t1
(
    c1 DateTime DEFAULT now() NOT NULL,
    c2 DateTime DEFAULT now() NOT NULL,
    c3 DateTime DEFAULT now() NOT NULL,
    PRIMARY KEY(c1, c2, c3)
) ENGINE = MergeTree()
ORDER BY (c1, c2, c3);

INSERT INTO t1 (c1,c2,c3) VALUES(now() + INTERVAL '1 day 1 hour 1 minute 1 second', now(), now());
```

It can be reproduced on the official docker image. (`clickhouse/clickhouse-server:head` and `clickhouse/clickhouse-server:latest`).

The log traced by ClickHouse Server:
```
2023.07.11 08:31:38.126263 [ 3064 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.07.11 08:31:38.126303 [ 3064 ] {} <Fatal> BaseDaemon: (version 23.7.1.857 (official build), build id: EBF7F00D257A03E61ABF10B376C4A7BDD0EED2BA, git hash: 9aef39a7888e10995ea85faad559a110c0e22a82) (from thread 49) Received signal 11
2023.07.11 08:31:38.126317 [ 3064 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.07.11 08:31:38.126328 [ 3064 ] {} <Fatal> BaseDaemon: Address: 0x20. Access: read. Address not mapped to object.
2023.07.11 08:31:38.126340 [ 3064 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000014c3d9e4 0x0000000014c410f6 0x0000000014c3a137 0x0000000014c38924 0x0000000014c37b9e 0x0000000014a45e35 0x0000000014a45986 0x0000000014a5d1e9 0x0000000014a53e50 0x0000000014a53370 0x0000000014a53011 0x0000000014a5191d 0x0000000013bddfe9 0x00000000149d1fb5 0x00000000149ce8af 0x000000001798e714 0x000000001798f931 0x0000000017b11727 0x0000000017b0f15c 0x00007f955d78a609 0x00007f955d6af133
2023.07.11 08:31:38.126348 [ 3064 ] {} <Fatal> BaseDaemon: ########################################
2023.07.11 08:31:38.126357 [ 3064 ] {} <Fatal> BaseDaemon: (version 23.7.1.857 (official build), build id: EBF7F00D257A03E61ABF10B376C4A7BDD0EED2BA, git hash: 9aef39a7888e10995ea85faad559a110c0e22a82) (from thread 49) (query_id: mysql:15:3c2e1c3f-4509-40a2-a8f7-7ff21b4bef79) (query: INSERT INTO t1 (c1,c2,c3) VALUES) Received signal Segmentation fault (11)
2023.07.11 08:31:38.126370 [ 3064 ] {} <Fatal> BaseDaemon: Address: 0x20. Access: read. Address not mapped to object.
2023.07.11 08:31:38.126376 [ 3064 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000014c3d9e4 0x0000000014c410f6 0x0000000014c3a137 0x0000000014c38924 0x0000000014c37b9e 0x0000000014a45e35 0x0000000014a45986 0x0000000014a5d1e9 0x0000000014a53e50 0x0000000014a53370 0x0000000014a53011 0x0000000014a5191d 0x0000000013bddfe9 0x00000000149d1fb5 0x00000000149ce8af 0x000000001798e714 0x000000001798f931 0x0000000017b11727 0x0000000017b0f15c 0x00007f955d78a609 0x00007f955d6af133
2023.07.11 08:31:38.126424 [ 3064 ] {} <Fatal> BaseDaemon: 2. DB::ConstantExpressionTemplate::TemplateStructure::TemplateStructure(std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator, DB::TokenIterator, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool, std::shared_ptr<DB::Context const>) @ 0x0000000014c3d9e4 in /usr/bin/clickhouse
2023.07.11 08:31:38.126442 [ 3064 ] {} <Fatal> BaseDaemon: 3. DB::ConstantExpressionTemplate::Cache::getFromCacheOrConstruct(std::shared_ptr<DB::IDataType const> const&, bool, DB::TokenIterator, DB::TokenIterator, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, bool*, String const&) @ 0x0000000014c410f6 in /usr/bin/clickhouse
2023.07.11 08:31:38.126455 [ 3064 ] {} <Fatal> BaseDaemon: 4. DB::ValuesBlockInputFormat::parseExpression(DB::IColumn&, unsigned long) @ 0x0000000014c3a137 in /usr/bin/clickhouse
2023.07.11 08:31:38.126468 [ 3064 ] {} <Fatal> BaseDaemon: 5. DB::ValuesBlockInputFormat::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x0000000014c38924 in /usr/bin/clickhouse
2023.07.11 08:31:38.126477 [ 3064 ] {} <Fatal> BaseDaemon: 6. DB::ValuesBlockInputFormat::generate() @ 0x0000000014c37b9e in /usr/bin/clickhouse
2023.07.11 08:31:38.126490 [ 3064 ] {} <Fatal> BaseDaemon: 7. DB::ISource::tryGenerate() @ 0x0000000014a45e35 in /usr/bin/clickhouse
2023.07.11 08:31:38.126498 [ 3064 ] {} <Fatal> BaseDaemon: 8. DB::ISource::work() @ 0x0000000014a45986 in /usr/bin/clickhouse
2023.07.11 08:31:38.126506 [ 3064 ] {} <Fatal> BaseDaemon: 9. DB::ExecutionThreadContext::executeTask() @ 0x0000000014a5d1e9 in /usr/bin/clickhouse
2023.07.11 08:31:38.126516 [ 3064 ] {} <Fatal> BaseDaemon: 10. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014a53e50 in /usr/bin/clickhouse
2023.07.11 08:31:38.126525 [ 3064 ] {} <Fatal> BaseDaemon: 11. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x0000000014a53370 in /usr/bin/clickhouse
2023.07.11 08:31:38.126533 [ 3064 ] {} <Fatal> BaseDaemon: 12. DB::PipelineExecutor::execute(unsigned long) @ 0x0000000014a53011 in /usr/bin/clickhouse
2023.07.11 08:31:38.126542 [ 3064 ] {} <Fatal> BaseDaemon: 13. DB::CompletedPipelineExecutor::execute() @ 0x0000000014a5191d in /usr/bin/clickhouse
2023.07.11 08:31:38.126554 [ 3064 ] {} <Fatal> BaseDaemon: 14. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&) @ 0x0000000013bddfe9 in /usr/bin/clickhouse
2023.07.11 08:31:38.126564 [ 3064 ] {} <Fatal> BaseDaemon: 15. DB::MySQLHandler::comQuery(DB::ReadBuffer&) @ 0x00000000149d1fb5 in /usr/bin/clickhouse
2023.07.11 08:31:38.126572 [ 3064 ] {} <Fatal> BaseDaemon: 16. DB::MySQLHandler::run() @ 0x00000000149ce8af in /usr/bin/clickhouse
2023.07.11 08:31:38.126583 [ 3064 ] {} <Fatal> BaseDaemon: 17. Poco::Net::TCPServerConnection::start() @ 0x000000001798e714 in /usr/bin/clickhouse
2023.07.11 08:31:38.126591 [ 3064 ] {} <Fatal> BaseDaemon: 18. Poco::Net::TCPServerDispatcher::run() @ 0x000000001798f931 in /usr/bin/clickhouse
2023.07.11 08:31:38.126601 [ 3064 ] {} <Fatal> BaseDaemon: 19. Poco::PooledThread::run() @ 0x0000000017b11727 in /usr/bin/clickhouse
2023.07.11 08:31:38.126614 [ 3064 ] {} <Fatal> BaseDaemon: 20. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017b0f15c in /usr/bin/clickhouse
2023.07.11 08:31:38.126621 [ 3064 ] {} <Fatal> BaseDaemon: 21. ? @ 0x00007f955d78a609 in ?
2023.07.11 08:31:38.126628 [ 3064 ] {} <Fatal> BaseDaemon: 22. clone @ 0x00007f955d6af133 in ?
2023.07.11 08:31:38.277774 [ 3064 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: C8DB2CC6CEEB111C8AB95A0F4BA5538E)
2023.07.11 08:31:38.277991 [ 3064 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2023.07.11 08:31:38.278090 [ 3064 ] {} <Fatal> BaseDaemon: No settings were changed
```

**Comment by helifu** [comment]
I had the same problem yesterday:
`2023.07.12 09:42:08.951950 [ 1305355 ] {} <Trace> BaseDaemon: Received signal 11
2023.07.12 09:42:08.952165 [ 1307914 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.07.12 09:42:08.952221 [ 1307914 ] {} <Fatal> BaseDaemon: (version 23.7.1.1, build id: FBC6F5841BF95C134835498C9D2E03B52381317A, git hash: 7b3b6531eec6384da95bf0d941912d0516c81d3b) (from thread 1305373) Received signal 11
2023.07.12 09:42:08.952252 [ 1307914 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2023.07.12 09:42:08.952269 [ 1307914 ] {} <Fatal> BaseDaemon: Address: 0x30. Access: read. Address not mapped to object.
2023.07.12 09:42:08.952291 [ 1307914 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000008846a87 0x000000001275466a 0x0000000012754339 0x0000000012755056 0x0000000012ed149a 0x0000000012edeaaf 0x000000001420770b 0x00000000138025fe 0x00000000137f4591 0x00000000137f2e34 0x00000000138912f6 0x0000000013892204 0x0000000013bc1853 0x0000000013bbd92e 0x00000000149e2fe4 0x00000000149fa4b9 0x0000000017979474 0x000000001797a691 0x0000000017afc487 0x0000000017af9ebc 0x00007f9ea27f2ea5 0x00007f9ea251bb0d
2023.07.12 09:42:08.952320 [ 1307914 ] {} <Fatal> BaseDaemon: ########################################
2023.07.12 09:42:08.952432 [ 1307914 ] {} <Fatal> BaseDaemon: (version 23.7.1.1, build id: FBC6F5841BF95C134835498C9D2E03B52381317A, git hash: 7b3b6531eec6384da95bf0d941912d0516c81d3b) (from thread 1305373) (query_id: 26f62ed7-2bda-4d27-a8f5-2220b496e219) (query: SELECT * FROM viewIfPermitted(SELECT message FROM system.warnings ELSE null('message String'))) Received signal Segmentation fault (11)
2023.07.12 09:42:08.952486 [ 1307914 ] {} <Fatal> BaseDaemon: Address: 0x30. Access: read. Address not mapped to object.
2023.07.12 09:42:08.952539 [ 1307914 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000008846a87 0x000000001275466a 0x0000000012754339 0x0000000012755056 0x0000000012ed149a 0x0000000012edeaaf 0x000000001420770b 0x00000000138025fe 0x00000000137f4591 0x00000000137f2e34 0x00000000138912f6 0x0000000013892204 0x0000000013bc1853 0x0000000013bbd92e 0x00000000149e2fe4 0x00000000149fa4b9 0x0000000017979474 0x000000001797a691 0x0000000017afc487 0x0000000017af9ebc 0x00007f9ea27f2ea5 0x00007f9ea251bb0d
2023.07.12 09:42:09.001046 [ 1305632 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 403.46 MiB, peak 403.46 MiB, free memory in arenas 34.27 MiB, will set to 418.86 MiB (RSS), difference: 15.39 MiB
2023.07.12 09:42:10.001449 [ 1305632 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 418.86 MiB, peak 418.86 MiB, free memory in arenas 34.19 MiB, will set to 533.75 MiB (RSS), difference: 114.89 MiB
2023.07.12 09:42:10.538024 [ 1307914 ] {} <Fatal> BaseDaemon: 2. DB::FunctionToOverloadResolverAdaptor::useDefaultImplementationForNothing() const @ 0x0000000008846a87 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:10.561250 [ 1307914 ] {} <Fatal> BaseDaemon: 3. ./build-relwithdebug/src/./src/Functions/IFunction.cpp:454: DB::IFunctionOverloadResolver::getReturnTypeWithoutLowCardinality(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) const @ 0x000000001275466a in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:10.581748 [ 1307914 ] {} <Fatal> BaseDaemon: 4. ./build-relwithdebug/src/./src/Functions/IFunction.cpp:435: DB::IFunctionOverloadResolver::getReturnType(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) const @ 0x0000000012754339 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:10.603726 [ 1307914 ] {} <Fatal> BaseDaemon: 5. ./build-relwithdebug/src/./src/Functions/IFunction.cpp:440: DB::IFunctionOverloadResolver::build(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&) const @ 0x0000000012755056 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:10.767345 [ 1307914 ] {} <Fatal> BaseDaemon: 6. ./build-relwithdebug/src/./src/Interpreters/ActionsDAG.cpp:198: DB::ActionsDAG::addFunction(std::shared_ptr<DB::IFunctionOverloadResolver> const&, std::vector<DB::ActionsDAG::Node const*, std::allocator<DB::ActionsDAG::Node const*>>, String) @ 0x0000000012ed149a in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:10.939920 [ 1307914 ] {} <Fatal> BaseDaemon: 7. ./build-relwithdebug/src/./src/Interpreters/ActionsDAG.cpp:1204: DB::ActionsDAG::materializeNode(DB::ActionsDAG::Node const&) @ 0x0000000012edeaaf in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:10.996548 [ 1307914 ] {} <Fatal> BaseDaemon: 8. ./build-relwithdebug/src/./src/Interpreters/ActionsDAG.cpp:1195: DB::StorageView::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x000000001420770b in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.001963 [ 1305632 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 533.75 MiB, peak 533.75 MiB, free memory in arenas 34.20 MiB, will set to 638.41 MiB (RSS), difference: 104.66 MiB
2023.07.12 09:42:11.124475 [ 1307914 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build-relwithdebug/src/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:815: std::shared_ptr<DB::Context>::operator->[abi:v15000]() const
2023.07.12 09:42:11.124541 [ 1307914 ] {} <Fatal> BaseDaemon: 9. ./build-relwithdebug/src/./src/Interpreters/InterpreterSelectQuery.cpp:2516: DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x00000000138025fe in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.274471 [ 1307914 ] {} <Fatal> BaseDaemon: 10. ./build-relwithdebug/src/./src/Interpreters/InterpreterSelectQuery.cpp:1475: DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x00000000137f4591 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.421787 [ 1307914 ] {} <Fatal> BaseDaemon: 11.1. inlined from ./build-relwithdebug/src/./contrib/llvm-project/libcxx/include/optional:260: ~__optional_destruct_base
2023.07.12 09:42:11.421851 [ 1307914 ] {} <Fatal> BaseDaemon: 11. ./build-relwithdebug/src/./src/Interpreters/InterpreterSelectQuery.cpp:899: DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000137f2e34 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.466177 [ 1307914 ] {} <Fatal> BaseDaemon: 12. ./build-relwithdebug/src/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:352: DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x00000000138912f6 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.511118 [ 1307914 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build-relwithdebug/src/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:603: shared_ptr<DB::Context, void>
2023.07.12 09:42:11.511183 [ 1307914 ] {} <Fatal> BaseDaemon: 13. ./build-relwithdebug/src/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:380: DB::InterpreterSelectWithUnionQuery::execute() @ 0x0000000013892204 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.563625 [ 1307914 ] {} <Fatal> BaseDaemon: 14. ./build-relwithdebug/src/./src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000013bc1853 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.625379 [ 1307914 ] {} <Fatal> BaseDaemon: 15. ./build-relwithdebug/src/./src/Interpreters/executeQuery.cpp:1168: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x0000000013bbd92e in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.687046 [ 1307914 ] {} <Fatal> BaseDaemon: 16. ./build-relwithdebug/src/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x00000000149e2fe4 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.783015 [ 1307914 ] {} <Fatal> BaseDaemon: 17. ./build-relwithdebug/src/./src/Server/TCPHandler.cpp:2060: DB::TCPHandler::run() @ 0x00000000149fa4b9 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.786042 [ 1307914 ] {} <Fatal> BaseDaemon: 18. ./build-relwithdebug/base/poco/Net/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000017979474 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.790673 [ 1307914 ] {} <Fatal> BaseDaemon: 19.1. inlined from ./build-relwithdebug/base/poco/Net/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: std::default_delete<Poco::Net::TCPServerConnection>::operator()[abi:v15000](Poco::Net::TCPServerConnection*) const
2023.07.12 09:42:11.790716 [ 1307914 ] {} <Fatal> BaseDaemon: 19.2. inlined from ./build-relwithdebug/base/poco/Net/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:305: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
2023.07.12 09:42:11.790758 [ 1307914 ] {} <Fatal> BaseDaemon: 19.3. inlined from ./build-relwithdebug/base/poco/Net/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.07.12 09:42:11.790801 [ 1307914 ] {} <Fatal> BaseDaemon: 19. ./build-relwithdebug/base/poco/Net/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x000000001797a691 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.796259 [ 1307914 ] {} <Fatal> BaseDaemon: 20. ./build-relwithdebug/base/poco/Foundation/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x0000000017afc487 in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.801009 [ 1307914 ] {} <Fatal> BaseDaemon: 21.1. inlined from ./build-relwithdebug/base/poco/Foundation/./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::get()
2023.07.12 09:42:11.801080 [ 1307914 ] {} <Fatal> BaseDaemon: 21.2. inlined from ./build-relwithdebug/base/poco/Foundation/./base/poco/Foundation/include/Poco/SharedPtr.h:139: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::assign(Poco::Runnable*)
2023.07.12 09:42:11.801140 [ 1307914 ] {} <Fatal> BaseDaemon: 21.3. inlined from ./build-relwithdebug/base/poco/Foundation/./base/poco/Foundation/include/Poco/SharedPtr.h:180: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>::operator=(Poco::Runnable*)
2023.07.12 09:42:11.801180 [ 1307914 ] {} <Fatal> BaseDaemon: 21. ./build-relwithdebug/base/poco/Foundation/./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017af9ebc in /home/hzhelifu/clickhouse-opensource/build-relwithdebug/programs/clickhouse
2023.07.12 09:42:11.801265 [ 1307914 ] {} <Fatal> BaseDaemon: 22. start_thread @ 0x0000000000007ea5 in /usr/lib64/libpthread-2.17.so
2023.07.12 09:42:11.801341 [ 1307914 ] {} <Fatal> BaseDaemon: 23. clone @ 0x00000000000feb0d in /usr/lib64/libc-2.17.so
2023.07.12 09:42:11.801386 [ 1307914 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2023.07.12 09:42:11.801441 [ 1307914 ] {} <Information> SentryWriter: Not sending crash report
2023.07.12 09:42:11.801455 [ 1307914 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2023.07.12 09:42:11.801632 [ 1307914 ] {} <Fatal> BaseDaemon: No settings were changed
`

**Comment by alexey-milovidov** [comment]
@fuboat Thank you! This is a very good finding.
By the way, what type of fuzzer did you use? We need more of that.

**Comment by alexey-milovidov** [comment]
@helifu, you have another problem, and it is caused by the usage of an unofficial ClickHouse build (with your own modifications). We only support the official ClickHouse builds.

**Comment by tavplubix** [comment]
Introduced in https://github.com/ClickHouse/ClickHouse/pull/42195

**Comment by fuboat** [comment]
> @fuboat Thank you! This is a very good finding. By the way, what type of fuzzer did you use? We need more of that.

@alexey-milovidov  Hi, Alexey! Very sorry for the late response. 

I am a member of Wingtecher Lab. Recently I am trying implementing a work of other labs (a mutation-based DBMS Fuzzer [Squirrel](https://github.com/s3team/Squirrel)) on ClickHouse in some way. However, it still needs effort to make it work properly. It seems like that current implementation mainly finds bugs in one SELECT statement.

Here are some new crashes found by it:
#52403, #52406, #52407.
