### ISSUE TITLE
DateTime TimeZone Behavior Inconsistent

### ISSUE THREAD

**Issue by enqueue** [ClickHouse/ClickHouse#5206]
**Describe the bug**
ClickHouse uses Timezone-local times when inserting values, but Server-local times when querying. This is inconsistent.

**How to reproduce**
* Which ClickHouse server version to use: 19.5.2.6
* Which interface to use, if matters: Native clickhouse-client
* Non-default settings, if any: Server timezone = UTC
* `CREATE TABLE` statements for all tables involved:
```
CREATE TABLE tztest
(
    timeBerlin DateTime('Europe/Berlin'), 
    timeLA DateTime('America/Los_Angeles')
)
ENGINE = Memory
```
* Queries to run that lead to unexpected result:
```
INSERT INTO tztest (timeBerlin, timeLA) VALUES ('2019-05-06 12:00:00', '2019-05-06 12:00:00');
```
```
SELECT 
    toUnixTimestamp(timeBerlin), 
    toUnixTimestamp(timeLA)
FROM tztest 

┌─toUnixTimestamp(timeBerlin)─┬─toUnixTimestamp(timeLA)─┐
│                  1557136800 │              1557169200 │
└─────────────────────────────┴─────────────────────────┘
```
```
SELECT 1
FROM tztest 
WHERE timeBerlin = '2019-05-06 12:00:00'

Ok.

0 rows in set. Elapsed: 0.003 sec. 
```
```
SELECT 1
FROM tztest 
WHERE timeLA = '2019-05-06 12:00:00'

Ok.

0 rows in set. Elapsed: 0.003 sec.
```

**Expected behavior**
The queries should have returned the row, or ClickHouse should have used the server timezone when inserting the values. Either way, ClickHouse should behave consistent.

**Comment by filimonov** [comment]
It is not so obvious to say what behaviour is correct. 

If you use datatype with timezone specified you force ClickHouse to use the formatting rules for that timezone when reading/writing time from that field. That's why it was read according to tz rules you've specified in datatype. 

When querying you're comparing two datestamps. One stored in the table (with tz forced) and another provided in query. The timestamp used in query has no timezone enforced so it's created using system default tz. 

So that is expected. Maybe tz rules should be also enforced for inlined timestamp predicate when comparing with a column which has enforced tz in data type. But it can also create misunderstanding. 

Currently, it's really easy to workaround:
```
SELECT 1 FROM tztest WHERE timeBerlin = toDateTime('2019-05-06 12:00:00', 'Europe/Berlin').
```

Does it make sense?

**Comment by enqueue** [comment]
> It is not so obvious to say what behaviour is correct.

I agree. Particularly when time zones or leap seconds are involved :smile: 

I am not an expert on this issue, and if the current behavior fits most use cases or is consistent with SQL standard or with the behavior of many popular databases, it's OK. I would like to point out though that it might not be intuitive for some users:

```
SELECT timeBerlin
FROM tztest 

┌──────────timeBerlin─┐
│ 2019-05-06 12:00:00 │
└─────────────────────┘
```
```
SELECT 1
FROM tztest 
WHERE timeBerlin = '2019-05-06 12:00:00'

Ok.

0 rows in set. Elapsed: 0.006 sec.
```

**Comment by alexey-milovidov** [comment]
Yes, it makes sense.

When you type `timeBerlin = '2019-05-06 12:00:00'` you are comparing DateTime column with constant string literal. It is already a special case (it is supported only for constant string literals) and it is different from `timeBerlin = toDateTime('2019-05-06 12:00:00')` when you are comparing DateTime with DateTime.
