### ISSUE TITLE
Parsing DateTime from string is inconsistency 

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#52089]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

Any value < 10000 (including negative number) cannot be parsed as DateTime if it is a string, for example:

```sql
CREATE TABLE t (x UInt64, ts DateTime) ENGINE=Memory;
INSERT INTO t VALUES (10000, '10000'); -- this query success
INSERT INTO t VALUES (10000, '9999'); -- this query fail
```

Reproduce: https://fiddle.clickhouse.com/549cb626-5633-4989-8eee-9617b2186a27

**Expected behavior**
If we allow parsing data time from string as number, it should work for any number.

**Comment by zvonand** [comment]
@canhld94 This behavior is completely expected.

1. It is forbidden to parse 4-char strings because of ambiguity:
Imagine having an expression `toDateTime('1998')`.
What is '1998' here? A part of '1998-01-01` notation? A unix timestamp in seconds? Shall it result in `1970-01-01 00:33:18` or `1998-01-01 00:00:00`? Why, and why not the other one? 

> If toDateTime(9999) works then toDateTime('9999') should also work?

9999 brings no ambiguity. Numeric value is definitely a timestamp value, not a year number.


Maybe this shall be clarified in docs -- I will take a look

**Comment by canhld94** [comment]
@zvonand then it may becomes a burden for data importing. Imagine we have a table `t (s String, ts DateTime)`, and we want to import data from a TSV file with `cat file.tsv | clickhouse client --query "insert into table t format TSV"`, and `ts` in `file.tsv` are unix timestamps. If `file.txt` contains a timestamp < 10000 then the import will fail.

At least should we have a setting to tell that we want to use string as unix timestamp during data importing for DateTime column?

cc @Avogar how do you think about this?

**Comment by zvonand** [comment]
For now, you can convert such strings to DT via numeric types, e.g. UInt16

**Comment by canhld94** [comment]
@zvonand What we're doing now is to convert negative number to 0 and pad < 10000 number with 0. It works well but need to maintain some parsing code on application side.
