### ISSUE TITLE
why sum(int32) ,in  java's jdbcType become Long

### ISSUE THREAD

**Issue by chenglin321** [ClickHouse/ClickHouse#52296]
a column type is int32, in java's jdbcType is Integer type
but when my sql is  "select  sum(int32) as  total  from  table  "  , the "total"  in java's jdbcType become Long type.
this is why ?

**Comment by chenglin321** [comment]
![lQLPJwKtm3AoLJLNAmfNBl-wds_glel-XtEErIkc6MAGAA_1631_615](https://github.com/ClickHouse/ClickHouse/assets/3918176/3544ac61-5c5b-4583-8da4-84947b9e3987)
![lQLPJxNhJFT9BTrNAgbNBrCwtocylSSd8-4Eq7TfaQCaAA_1712_518](https://github.com/ClickHouse/ClickHouse/assets/3918176/c585d523-6cc5-4422-8183-23000d16258f)

**Comment by cangyin** [comment]
Result type of function `sum()` is deduced as 'nearest type' of the argument type

https://github.com/ClickHouse/ClickHouse/blob/2675b8fa7970d8c4b098d5635edaff29aecd085d/src/AggregateFunctions/AggregateFunctionSum.cpp#L20-L25


where 'nearest type' of some integer types are defined here:

https://github.com/ClickHouse/ClickHouse/blob/7f64787becb6b8d25cf2c04266c793e7ac3181ae/src/Core/Field.h#L208-L232


IMOO, result type of `sum` is made as `UInt64` or `Int64`, instead of same type as argument, to avoid numberic overflows.

CMIIW.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/sumwithoverflow

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/arithmetic-functions

**Comment by den-crane** [comment]
```
DESCRIBE TABLE
(
    SELECT
        sum(CAST('0', 'Int32')) AS a,
        sumWithOverflow(CAST('0', 'Int32')) AS b
)


┌─name─┬─type──┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ a    │ Int64 │              │                    │         │                  │                │
│ b    │ Int32 │              │                    │         │                  │                │
└──────┴───────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```

**Comment by chenglin321** [comment]
> ```
> DESCRIBE TABLE
> (
>     SELECT
>         sum(CAST('0', 'Int32')) AS a,
>         sumWithOverflow(CAST('0', 'Int32')) AS b
> )
> 
> 
> ┌─name─┬─type──┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
> │ a    │ Int64 │              │                    │         │                  │                │
> │ b    │ Int32 │              │                    │         │                  │                │
> └──────┴───────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
> ```

tks a lot
