### ISSUE TITLE
Failed materialized view query resulting in repeated reading of the original table

### ISSUE THREAD

**Issue by cyhyyq** [ClickHouse/ClickHouse#52354]
The table building statement is roughly as follows
**kafka table**
```
CREATE TABLE IF NOT EXISTS kafka_queue(
    ip     String
) ENGINE = Kafka();
```

**kafka consumer**
```
CREATE MATERIALIZED VIEW IF NOT EXISTS consumer TO query_logs AS
SELECT
	  ip,
FROM
	  kafka_queue
```

**original table**
```
CREATE TABLE IF NOT EXISTS query_logs(
    ip     String,
) ENGINE = ReplicatedReplacingMergeTree()
```

**materialized view**
```
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_distribution
ENGINE = ReplicatedSummingMergeTree()
POPULATE
AS SELECT
    IPv4StringToNum(ip) as ip,
from query_logs
```

If the function reports an error, it will cause the original table to repeatedly use the same data in Kafka

**Comment by den-crane** [comment]
It's expected. If one of chained materialized views fails in cancels the insertion. Then KafkaEngine try to repeat insertion.

two options:
* `toIPv4OrDefault('fsdsdf') = 0.0.0.0` use 'safe'  toIPv4OrDefault function instead of IPv4StringToNum
* ignore errors in matViews (session settings materialized_views_ignore_errors) https://github.com/ClickHouse/ClickHouse/pull/46658

-------------

IPv4StringToNum -- it the old function it produces the number instead of IP, try to avoid it.

**Comment by cyhyyq** [comment]
>
Thank you for your reply. This function is just an example to illustrate that if the materialized view fails to insert data, it will cause the original table to repeatedly insert data

**Comment by cyhyyq** [comment]
> 

And he did not cancel the insertion of the entire link, the original table data will grow infinitely
