### ISSUE TITLE
Assets aren't uploaded to a release because of failing API

### ISSUE THREAD

**Issue by shahargv** [ClickHouse/ClickHouse#52847]
Hey,

Version 23.7 has only 8 assets in the GitHub releases page (unlike 52 in previous releases). Among the missing files there's no RPM files.

I'd appreciate it if you can also add the missing files, so we could enjoy this new version.

Thanks!

**Comment by Felixoid** [comment]
Hello. The assets' upload failed due to the API [500](https://github.com/ClickHouse/ClickHouse/actions/runs/5681239145/job/15396951073#step:5:2876)

I'll adjust the [code](https://github.com/ClickHouse/clickhouse-repos-manager/blob/main/clickhouse-repos-manager/release.py#L192-L200), it obviously should have:

1. retries
2. check for the `message` key
3. raise exception in `else`

The assets are uploaded manually, but it still misses macos' binaries

**Comment by Felixoid** [comment]
BTW, for RPM packages consider using https://packages.clickhouse.com/rpm/stable/ repository

**Comment by Felixoid** [comment]
Please, leave it for me. I am fixing the issue in both repos and would like to have PR linked here

**Comment by alexey-milovidov** [comment]
We released the patch release yesterday, so the issue should be resolved.

**Comment by Felixoid** [comment]
I've deployed the fixed code, so now waiting for any new version being released

**Comment by Felixoid** [comment]
Fixed in https://github.com/ClickHouse/clickhouse-repos-manager/pull/2
