### ISSUE TITLE
Some queries does not respect max_threads and can make server non-resposible by starting too many threads

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#53287]
Happens on official build. 

Repro (tested on 23.7.4.5).

```bash
cat <<'EOF' | clickhouse-client -mn
DROP DATABASE IF EXISTS test_max_threads_leak;

CREATE DATABASE test_max_threads_leak;

CREATE TABLE test_max_threads_leak.test
(
    `a` String,
    `b` LowCardinality(String),
    `c` DateTime64(3),
    `val` String,
)
ENGINE = MergeTree
ORDER BY (a, b, c)
SETTINGS index_granularity = 8192, parts_to_delay_insert=0;

CREATE TABLE test_max_threads_leak.test_distributed
(
    `a` String,
    `b` LowCardinality(String),
    `c` DateTime64(3),
    `val` String,
)
ENGINE = Distributed('default', 'test_max_threads_leak', 'test', rand());

-- creating lot of parts, because the number of the threads clickhouse will start is proportional to the number of parts
SYSTEM STOP MERGES test_max_threads_leak.test;

INSERT INTO test_max_threads_leak.test (a, b, c, val) SELECT 'foo' as a, 'bar' as b, _CAST('1683504000', 'DateTime64') as c, 'baz' as val FROM numbers(4000) SETTINGS max_block_size = 1, min_insert_block_size_bytes=1,min_insert_block_size_rows=1;

select count() from system.parts where table = 'test' and active;
EOF

cat <<'EOF' | clickhouse-benchmark -i 250 -c 25 --max_threads=5 
SELECT DISTINCT 'val' AS fieldType, val AS value FROM test_max_threads_leak.test_distributed WHERE (a = 'foo') AND (value != '') AND (positionCaseInsensitiveUTF8(value, 'baz') > 0) AND (b = 'bar')  AND (c >= _CAST('1683504000', 'DateTime64')) ORDER BY c DESC LIMIT 5
EOF
```

clickhouse benchmark here starts 25 concurrent queries with max_threads=5. It should not use more than 125 threads. In practice, it tries to start more than 10000 and crashes with exceptions like 

```
An error occurred while processing the query ...
 Code: 439. DB::Exception: Received from localhost:9000. DB::Exception: Cannot schedule a task: cannot allocate thread (threads=238, jobs=238). Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e91fc37 in /usr/bin/clickhouse
1. ? @ 0x000000000ea0cf46 in /usr/bin/clickhouse
2. ? @ 0x000000000ea0dc8e in /usr/bin/clickhouse
3. ? @ 0x000000000ea08546 in /usr/bin/clickhouse
4. DB::PipelineExecutor::spawnThreads() @ 0x00000000152d58f7 in /usr/bin/clickhouse
5. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x00000000152d447e in /usr/bin/clickhouse
6. DB::PipelineExecutor::execute(unsigned long) @ 0x00000000152d4151 in /usr/bin/clickhouse
7. ? @ 0x00000000152e1f8d in /usr/bin/clickhouse
8. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000ea070cf in /usr/bin/clickhouse
9. ? @ 0x000000000ea0d0c1 in /usr/bin/clickhouse
10. ? @ 0x00007fc84a0cc609 in ?
11. __clone @ 0x00007fc849ff1133 in ?
. (CANNOT_SCHEDULE_TASK) (version 23.7.4.5 (official build))
```

Also, the numbers reported in that error message are incorrect. Older versions (23.3) report it better:

```
Code: 439. DB::Exception: Received from localhost:9000. DB::Exception: Cannot schedule a task: no free thread (timeout=0) (threads=10000, jobs=10000).
```

The real threads usage can be checked by query

```sql
select event_time, CurrentMetric_GlobalThreadActive from system.metric_log where event_time > now() - 600 order by event_time ; 
```

Was observed after the upgrade to 23.3.

**Comment by filimonov** [comment]
Related to https://github.com/ClickHouse/ClickHouse/issues/52624

**Comment by canhld94** [comment]
> Related to #52624

We may investigate more but think they're different problems. If you set num_streams=1, the pipeline may still contains many read streams, but if the executor only use 1 stream to execute the pipeline then it won't have thread leak.

**Comment by filimonov** [comment]
Yep, with direct query from MergeTree it still uses lot of streams but only few threads work simulatniously. 
But here (distributed +prefer localhost replica) it seem it start thread per stream.

**Comment by jorisgio** [comment]
> But here (distributed +prefer localhost replica) it seems it starts a thread per stream. 

I don't know how many shard you have in your cluster, but indeed it is even worse with prefer_localhost_replica=true.
 Because distributed engine raises the number of  threads allowed in executor to number of shards, if there is part of the pipeline that is not bound directly by max_threads just like in https://github.com/ClickHouse/ClickHouse/issues/52624 then it will use number of shards to execute the query.
 I wanted to try to switch Distributed engine to async io/epoll for this reason but it seemed too complex for me to tackle.

**Comment by jorisgio** [comment]
> Did you try that test?

Not exactly, i didn't know where this default cluster comes from, but tried a similar test. 

> It creates 10000 threads on the single shard.

max_thread_pool_size is 10000 by default so that is the limit, but it would create more than that i think. There is 4000 parts for me, so it would like to create thousands of threads if unbound, but max_distributed_connections is 1024 by default, so it will be bound to 1024 threads per query. You can try by setting max_distributed_connections to something like 20 it works in this case for me. I guess the part that sets limit_max_threads to max_distributed_connections does not take into account that the query was rewritten to prefer_localhost_replica.
What i am saying is that it is also a problem for Distributed queries with prefer_localhost_replica if there are many shards.

**Comment by jorisgio** [comment]
https://github.com/ClickHouse/ClickHouse/blob/dbe13e30168b75d9eaa073228c5242d6ca375337/src/Interpreters/InterpreterSelectQuery.cpp#L2338 but actually this comment is outdated no ? since there is async_socket_for_remote by default, the fix is just avoid increasing limit_max_thread if async_socket_for_remote is true, it should not have performance impact on distributed engine ? (i forgot this is actually what we did, set max_distributed_connections = max_threads) and it had no visible performance impact.

**Comment by filimonov** [comment]
> > Did you try that test?
> 
> Not exactly, i didn't know where this default cluster comes from, 

It comes from the freshly installed cluckhouse, from default config https://github.com/ClickHouse/ClickHouse/blob/9e7e58181360e3b24c27c67241304b2458832973/programs/server/config.xml#L808

> but tried a similar test.

Please also try the one I sent. 

> 
> > It creates 10000 threads on the single shard.
> 
> max_thread_pool_size is 10000 by default so that is the limit, but it would create more than that i think.

It will not. Try the test. 

> There is 4000 parts for me, so it would like to create thousands of threads if unbound

Problem does not happen when you am query local table. Try my test. 

> but max_distributed_connections is 1024 by default... 

One node is used. No connections to other nodes at all. 

Please run the test. The exact one in the first comment. You talk about some different problems.

**Comment by jorisgio** [comment]
I am pretty concinced I talk about the exact same problem, I apologise if am wrong though.

**Comment by filimonov** [comment]
Thanks for the explanation, now I've got it. And I'm sorry for my impatience :) 

Additionally, I was able to confirm that: lowering `max_distribured_connections` allows to workaround the problem.

Actually that prefer_localhost_replica optimization quite often leads to some unexpected behaviour (see https://github.com/ClickHouse/ClickHouse/issues/6349 https://github.com/ClickHouse/ClickHouse/issues/37090  https://github.com/ClickHouse/ClickHouse/issues/44487 etc)

Also, i've tried to follow the code and found that comment, which (probably) was the original idea:
https://github.com/ClickHouse/ClickHouse/blob/dbe13e30168b75d9eaa073228c5242d6ca375337/src/Interpreters/InterpreterSelectQuery.cpp#L2519

**Comment by azat** [comment]
Yes, the problem is clear, but it is not that easy to fix (except for ignoring this part under `max_distributed_connections`)

>Also, the numbers reported in that error message are incorrect. Older versions (23.3) report it better:

@filimonov This is likely because now PipelineExecutor uses ThreadPool - #48146

>but actually this comment is outdated no ?

@jorisgio More or less - yes.
And actually `max_distributed_connections` does nothing with `async_socket_for_remote`.

**Comment by jorisgio** [comment]
>Yes, the problem is clear, but it is not that easy to fix (except for ignoring this path under async_socket_for_remote)

I suspect it is a good enough fix, is there really a need not to run async_socket? Else can try to fix the the case of not async socket by bypassing this path when prefer local host was fully rewritten to local queries but it is fragile, i suspect there are corner cases with sun queries or stuffs like where in? Idk

**Comment by filimonov** [comment]
>  And actually max_distributed_connections does nothing with async_socket_for_remote.

Almost nothing - it actually works like max_threads there... 

I've did very simple test:
https://fiddle.clickhouse.com/f72b38b1-441d-48d2-8d68-ec148d804467

```
select * from remote('127.0.0.1:9000,127.0.0.2:9000,127.0.0.3:9000,127.0.0.4:9000,127.0.0.5:9000,127.0.0.6:9000,127.0.0.7:9000,127.0.0.8:9000', view(select sleep(0.5)));
```



### defaults 

* query time: 535
* number of derived queries: 7

As expected It talks to all 8 shards in parallel, and recognized 127.0.0.1 as localhost replica

#### defaults with prefer_localhost_replica=0 

* query time: 505
* number of derived queries: 8

Again - everything works in parallel, network connection to 127.0.0.1 this time.

#### max_distributed_connections=1 

* query time: 1130
* number of derived queries: 7

It FIRST executes the query on the localhost (prefer_localhost_replica=1) and then on the other nodes in parallel. 
It seems like that max_distributed_connections works like another thread limit here, and async_socket_for_remote works after that.

### max_distributed_connections=1, prefer_localhost_replica=0 

* query time: 640
* number of derived queries: 8

Once we turn off prefer_localhost_replica it talks to all 8 shards in parallel, but again the query speed in worse, because the pipeline is executed by a single thread.

#### max_distributed_connections=1, async_socket_for_remote=0 

* query time: 4109
* number of derived queries: 7

Talks to nodes sequentially.

**Comment by filimonov** [comment]
So i think we can do 2 things:

1) patch which can be ported to older versions like 23.3 / 22.8 - i've drafted PR https://github.com/ClickHouse/ClickHouse/pull/53504/files 

2) (maybe) get rid of  async_socket_for_remote=0 at all? 

it w

**Comment by azat** [comment]
>is there really a need not to run async_socket?

Yes, it is useful if you still want to limit number of connections to remote shards.

**Comment by Enmk** [comment]
Is it fixed by https://github.com/ClickHouse/ClickHouse/pull/53504 ?

**Comment by groeneai** [comment]
I ran into this issue from the opposite direction and want to record what I found, because it turns out
`max_distributed_connections` has a second, live defect that shares the same root, and fixing either
one properly seems to need a design decision I should not make on my own.

## The second defect: on FreeBSD, SunOS and Android the compensation never engages at all

`async_socket_for_remote` is a *request* for asynchronous socket reads. Whether the asynchronous
implementation exists is a *build* property: `RemoteQueryExecutor::readAsync` is

```cpp
#if defined(OS_LINUX) || defined(OS_DARWIN)
    ... real implementation ...
#else
    return read();          // src/QueryPipeline/RemoteQueryExecutor.cpp:702-704
#endif
```

and the same for `sendQueryAsync` (`:581-583`), `processParallelReplicaPacketIfAny` (`:1208`) and the
whole `RemoteQueryExecutorReadContext` class (`.h:3`, `.cpp:1`).

The planner's compensation, however, is keyed on the *setting*:

```cpp
// src/Planner/PlannerJoinTree.cpp:1504
bool is_sync_remote = table_expression_data.isRemote() && !settings[Setting::async_socket_for_remote];
```

byte-identical at `src/Interpreters/InterpreterSelectQuery.cpp:2793`. Neither site mentions any
platform macro. So on a build without the asynchronous path the setting reads `1`, the reads block
anyway, and no compensation happens.

Measured on a build with the asynchronous path forced off, `SELECT sleep(1.5) FROM remote('127.{1..10}', system.one)`
with `max_threads=1, max_distributed_connections=10, prefer_localhost_replica=0`:

| configuration | wall time |
|---|---|
| asynchronous path compiled in | 1.70 s |
| asynchronous path not compiled in | **15.12 s** (10 x 1.5 s, fully serialized) |
| `async_socket_for_remote=0` explicitly | 1.60 s |

`01602_max_distributed_connections` fails 3/3 there, and `01514_distributed_cancel_query_on_error`
fails 3/3. `ci/defs/job_configs.py` builds `amd_freebsd`, but no functional-test job consumes that
artifact, which is why this has never shown up in CI.

## Five fixes I designed and then refuted

I tried, in order, and rejected each with code evidence:

1. **Make the two `is_sync_remote` predicates build-aware.** `max_distributed_connections` defaults to
   1024 and is a cap, not a count of servers, so this raises the whole plan's limit to 1024 for a
   2-shard query. `is_sync_remote` also suppresses the `max_streams_to_max_threads_ratio`
   multiplication (`PlannerJoinTree.cpp:1556`) and supplies the `|| is_sync_remote` disjunct at
   `:2024` that overrides a limit local storage already chose. This is the behaviour this issue is
   about, so widening its reach is the wrong direction, and it reddens
   `02845_threads_count_in_distributed_queries`.
2. **`pipeline.setMaxThreads(...)` inside `initializePipeline`.** Erased one statement later:
   `QueryPlan::buildQueryPipeline` calls `limitMaxThreads(max_threads)` (`QueryPlan.cpp:259-263`) and
   `limitMaxThreads` only lowers (`QueryPipelineBuilder.h:220-224`).
3. **Compute the compensation from the storage's cluster topology.** Any count derived before
   `storage->read()` is a prediction the runtime contradicts: `SelectStreamFactory` can replace a
   logically remote shard with a local plan (`SelectStreamFactory.cpp:216-270`),
   `ReadFromCluster` truncates its loop at `max_replicas_to_use` and skips unavailable pools
   (`IStorageCluster.cpp:161-185`), `ReadFromParallelReplicasStep` skips `exclude_pool_index`
   (`ReadFromParallelReplicas.cpp:143-145`), and `getClusterQueriedNodes` undercounts custom-key
   parallel replicas, which create one source per `per_replica_pools` entry
   (`ReadFromRemote.cpp:777-825`).
4. **Ask each plan step how many sources it will create, then walk the plan.** Same prediction problem
   as (3), plus `ReadFromParallelReplicasStep` is created during optimization
   (`Optimizations/optimizeTree.cpp:367`), and a walk over `Node::children` misses nested plans reached
   through `getChildPlans` (`StorageMerge.cpp:1237-1246`).
5. **Have each step report the count it actually created, and widen the existing clamp at
   `QueryPlan.cpp:259-263`.** This measures rather than predicts, but the raise does not survive
   composition: the executor's thread count comes from the *final* builder
   (`QueryPipelineBuilder::getPipeline` -> `setNumThreads(builder.getNumThreads())`, `:934-939`), while
   `mergePipelines` (`:277-299`), `selectPipeline` (`:302-343`) and `joinPipelines` (`:718-726`) all
   `return left` after folding only `pipe.max_parallel_streams`, discarding the other inputs'
   `max_threads`. A `JOIN` whose right side is the remote read loses the raise entirely.

   Interesting detail: master does not have this problem only because it writes
   `QueryPlan::max_threads` **once** and `:262` then applies it to *every* source step of that plan, so
   both sides of a join already carry the raised value. Raising one side only makes "keep left" fatal.

   Also, lazy shards cannot be handled this way: `addLazyPipe`'s callback can build a real
   `RemoteSource` at execution time (`ReadFromRemote.cpp:725-734`), and `DelayedSource::work` converts
   the builder with `getPipe` (`DelayedSource.cpp:113-116`), which drops thread-limit metadata after
   the executor's thread count has already been chosen.

## What the fix actually seems to require

The only mechanism left standing is a **minimum thread requirement** carried through every pipeline
composition boundary and applied at the final builder. Today `max_threads` is a maximum that only ever
narrows (`getNumThreads` returns `max(1, min(maxParallelStreams, max_threads))`,
`QueryPipelineBuilder.h:206-214`); there is no notion of "this pipeline needs at least N threads
because N of its sources block".

That is a change to core thread accounting, and it has design questions I do not think a bug-fix PR
should answer unilaterally:

1. Where is a minimum enforced, given that `getNumThreads` is advisory and `use_concurrency_control`
   can override the outcome anyway?
2. What is its composition rule at each of `unitePipelines` (`:225`), `mergePipelines` (`:277`),
   `selectPipeline` (`:302`), `joinPipelines` (`:718`, `:435`, `:812`), `addPipelineBefore` (`:878`)
   and `getPipeline` (`:934`)? A union of two blocking reads plausibly wants the sum; a join, the max;
   a selector, something else.
3. How does it interact with the memory-limited `max_threads` from
   `getMaxThreadsForAvailableMemory`?
4. `DelayedSource` deliberately discards this metadata, and nested plans cross a
   `buildQueryPipeline` boundary. Do those become part of the contract?

And, relevant to this issue specifically: **such a mechanism is also what would let the unbounded
behaviour reported here be bounded properly.** Instead of assigning `max_distributed_connections`
wholesale, a query could ask for "at least as many threads as I have blocking sources, capped by
`max_distributed_connections`", which is what the comment at `PlannerJoinTree.cpp:1492-1502` describes
wanting, and what `02845`'s `peak_threads >= 1` assertions for `async_socket_for_remote=0` currently
document as "actually a bad behaviour, but it used to work like that for a long time".

## What I would suggest

Doing (2) above, deciding the composition rule for a minimum thread requirement, once, and then
using it for both halves: bounding the existing `async_socket_for_remote=0` compensation (this issue)
and making it engage on builds where the asynchronous path is absent (the FreeBSD/SunOS/Android
defect). Splitting them means designing the same mechanism twice.

I am happy to implement whichever shape the owners of this code prefer, but I would rather not pick
the composition semantics myself. If there is a simpler framing I have missed, I would like to hear it:
five of my attempts were wrong for reasons that were only obvious after reading the composition
code.

For context, https://github.com/ClickHouse/ClickHouse/pull/112124 discloses the FreeBSD/SunOS/Android
half in its description, since a guard it adds makes the same serialization reachable on the
`arm_msan` lane.
