### ISSUE TITLE
Cannot load to ephemeral column from Avro

### ISSUE THREAD

**Issue by ltrk2** [ClickHouse/ClickHouse#53477]
**Describe what's wrong**

When loading from a file of `Avro` format into a column of `ephemeral` type, the values don't seem to get populated.

**Does it reproduce on recent release?**

It's reproducible in 23.7.4.5.

**How to reproduce**

https://fiddle.clickhouse.com/2b6ed6af-12d6-4829-b376-ed40e9564043

**Expected behavior**

Performing the same thing using `RowBinary` format or inserting directly into the table results in the expected behaviour.

https://fiddle.clickhouse.com/ac7ef343-4a08-4dbc-afc1-b211c54bdda5

**Comment by cangyin** [comment]
That's exactly expected, as per [documented](https://clickhouse.com/docs/en/sql-reference/statements/create/table#ephemeral):

> Ephemeral column. Columns of this type are **not stored** in the table and it is not possible to SELECT from them. The only purpose of ephemeral columns is to **build default value expressions of other columns** from them.

**Comment by cangyin** [comment]
> set input_format_avro_allow_missing_fields=1;

you allowed the missing field `id_default` to be inserted as default value (0), that's why there are zeros under `id_default`.

**Comment by cangyin** [comment]
please read the doc about
- [](rl)

**Comment by Avogar** [comment]
From documentation:
```
An insert without explicitly specified columns will skip columns of this typ
```

So, just `insert into idsephemeral FROM INFILE 'x' format Avro;` will insert only ordinary columns and skip ephemeral columns, so you should write `insert into (id) idsephemeral FROM INFILE 'x' format Avro;` or `insert into idsephemeral (id, id_default) FROM INFILE 'x' format Avro;`. But it also won't work because of a bug: we use StorageFile to read data from file and it doesn't support ephemeral columns, and when we propogate columns description from the insertion table to the StorageFile, we don't change Ephemeral columns to ordinary, I fixed it.

**Comment by ltrk2** [comment]
@Avogar thanks for fixing it!
