### ISSUE TITLE
How to choose parameters for Buffer table in Clickhouse?

### ISSUE THREAD

**Issue by cherrypas** [ClickHouse/ClickHouse#54166]
Hi!
I want to create a buffer table to reduce the number of small inserts, but I don't understand how to select parameters for the table? For example, I want the buffer table to flash the data to the target table every 4 hours or when the number of rows reaches 10000. But there are other parameters such as min\max bytes and num_layers.
I am mainly interested in this parameter: num_layers. In the documentation it is mentioned that the recommended is 16, but why?

**Comment by filimonov** [comment]
> min\max bytes

That allows to flush earlier if the rows collected by buffer table was too big. Imagine normally you flush 10000 rows and every row take 100 bytes. So your Buffer table will collect 1MB of data in ram, and your system is stable. But suddenly you have a 10000 rows, when every row is 1MB size. So your Buffer table will try to allocate 10GB of ram, and you may start getting problems on server due to that. If you will setup max bytes to let's say 100 mb clickhouse will be flushing 100 rows instead of 10000 in those conditions. 

> num_layers

It is the level of parallelism. During writing / flushing the layer is locked.

**Comment by filimonov** [comment]
Also: did you check async_inserts?

**Comment by alexey-milovidov** [comment]
The recommended value for num_layers is 1.

**Comment by guoxiaolongzte** [comment]
If the num_Layers are set too large, will the RAM also increase?

**Comment by alexey-milovidov** [comment]
Yes, it can be up to proportional to the num_layers.
But don't increase the num_layers too much (or set it to 1, and don't worry).
This is an "expert-level" parameter, which shouldn't be used normally.

**Comment by cherrypas** [comment]
> Also: did you check async_inserts?
I read about it, but didn't catch the difference between async_inserts and buffer tables.
