### ISSUE TITLE
Remove the `UNDROP` query

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#54658]
This feature wasn't implemented completely - @tavplubix pointed out that there are corner cases when you create another table concurrently with UNDROP or something similar. It remains under experimental for a long time without further progress (no one is interested in finishing the implementation) - maybe now is the time to remove it.

**Comment by den-crane** [comment]
I also suggest considering lowering `database_atomic_wait_for_drop_and_detach_synchronous`.

```
<database_atomic_wait_for_drop_and_detach_synchronously>1</database_atomic_wait_for_drop_and_detach_synchronously>
```

The current behaviour creates a lot of questions, like "I dropped huge table, but disk space is not freed", "I dropped replicated table, and I am unable to create it back, because of an error Replica already exists".

**Comment by tavplubix** [comment]
> This feature wasn't implemented completely

It was

>  @tavplubix pointed out that there are corner cases when you create another table concurrently with UNDROP or something similar.

You missed the point. Yes, there are some restrictions, but it's not a big problem. It's impossible to undrop a table that has already been cleaned up by the background thread, but it's obvious. Also, it's impossible to undrop a table if another table with the same name already exists, but it's expected behavior. 

> It remains under experimental for a long time without further progress

It was under the flag because the initial implementation was really bad. It got better after a few iterations of code review, but I decided to keep it experimental just in case. Stress tests and tsan found no bugs, so let's remove the experimantal flag.

> I also suggest considering lowering database_atomic_wait_for_drop_and_detach_synchronous.
> The current behaviour creates a lot of questions, like "I dropped huge table, but disk space is not freed", "I dropped replicated table, and I am unable to create it back, because of an error Replica already exists".


Lowering `database_atomic_wait_for_drop_and_detach_synchronous` will not avoid these questions, enabling `database_atomic_wait_for_drop_and_detach_synchronously` will
