### ISSUE TITLE
Direct import from archives don't work for table function s3

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#54726]
**Use case**

```
milovidov-desktop :) SELECT count() FROM s3('https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-*.csv.zip :: *.csv')

SELECT count()
FROM s3('https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-*.csv.zip :: *.csv')

Query id: f0f8e741-05a1-4792-bba9-31dd14f82b4d


0 rows in set. Elapsed: 0.022 sec. 

Received exception:
Code: 1001. DB::Exception: Poco::URISyntaxException: Bad URI syntax. (STD_EXCEPTION)
```

**Comment by Priyansh121096** [comment]
It seems as if spaces are not allowed in the URIs. I tried without spaces and this is what I got:
```
SELECT count()
FROM s3('https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-*.csv.zip::*.csv')

Query id: 6b4f3ff8-7278-4f90-b0ad-6cf5cbf54a77

0 rows in set. Elapsed: 5.749 sec. 

Received exception from server (version 23.9.1):
Code: 636. DB::Exception: Received from localhost:9000. DB::Exception: Cannot extract table structure from CSV format file, because there are no files with provided path in S3 or all files are empty. You must specify table structure manually: Cannot extract table structure from CSV format file. You can specify the structure manually. (CANNOT_EXTRACT_TABLE_STRUCTURE)
```

Then, I tried setting the schema explicitly. This seemed to work initially but failed on a bad file:
```
SELECT count()
FROM s3('https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-*.csv.zip', 'CSV', 'index UInt32, address String')

Query id: 007e04a0-f13f-4c0d-9cfc-3a00deddedd7

↓ Progress: 12.45 million rows, 1.11 GB (926.75 thousand rows/s., 82.46 MB/s.) █████████████▋                                                                                                           (0.5 CPU, 54.05 MB RAM) 9%
0 rows in set. Elapsed: 13.431 sec. Processed 12.45 million rows, 1.11 GB (926.75 thousand rows/s., 82.46 MB/s.)
Peak memory usage: 330.39 MiB.

Received exception from server (version 23.9.1):
Code: 117. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse CSV format: found \r (CR) not followed by \n (LF). Line must end by \n (LF) or \r\n (CR LF) or \n\r.: (in file/uri top-1m-2017-04-15.csv.zip): (while reading header): While executing CSVRowInputFormat: While executing S3. (INCORRECT_DATA)
```

So, I tried doing the same for a smaller time frame. But the returned count seems way off the expected count (I expected the count to be >31M). 
```
SELECT count()
FROM s3('https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-2018-01*.csv.zip', 'CSV', 'index UInt32, address String')

Query id: 45ff2cd9-8c5d-4646-840f-dc3a8f249196

┌─count()─┐
│  648463 │
└─────────┘

1 row in set. Elapsed: 0.637 sec. Processed 648.46 thousand rows, 372.00 B (1.02 million rows/s., 583.68 B/s.)
Peak memory usage: 172.26 KiB.
```

**Comment by divanik** [comment]
Hi, @Priyansh121096. Thank you for your comment.
I wonder why did you expect >31M rows in the query result? I did a query that showed that there are approximately 20K rows in each file and 31 files, that's why number 648463 seems sane

```
SELECT _file, count()
FROM s3('https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-2018-01-*.csv.zip', 'NOSIGN', 'CSV', 'index UInt32, address String') GROUP BY _file ORDER  BY _file;
```
|file                                           | count()|
| --------------------------- | ------  |
| top-1m-2018-01-01.csv.zip | 20792 |
| top-1m-2018-01-02.csv.zip |   20560 |
| top-1m-2018-01-03.csv.zip |   20530 |
| top-1m-2018-01-04.csv.zip |   20782 |
| top-1m-2018-01-05.csv.zip |   20920 |
| top-1m-2018-01-06.csv.zip |   20838 |
| top-1m-2018-01-07.csv.zip |   20758 |
| top-1m-2018-01-08.csv.zip |   20727 |
| top-1m-2018-01-09.csv.zip |   20725 |
| top-1m-2018-01-10.csv.zip |   20983 |
| top-1m-2018-01-11.csv.zip |   20636 |
| top-1m-2018-01-12.csv.zip |   20430 |
| top-1m-2018-01-13.csv.zip |   20568 |
| top-1m-2018-01-14.csv.zip |   20560 |
| top-1m-2018-01-15.csv.zip |   20727 |
| top-1m-2018-01-16.csv.zip |   20471 |
| top-1m-2018-01-17.csv.zip |   21167 |
| top-1m-2018-01-18.csv.zip |   21145 |
| top-1m-2018-01-19.csv.zip |   20938 |
| top-1m-2018-01-20.csv.zip |   20948 |
| top-1m-2018-01-21.csv.zip |   21067 |
| top-1m-2018-01-22.csv.zip |   21162 |
| top-1m-2018-01-23.csv.zip |   20991 |
| top-1m-2018-01-24.csv.zip |   21489 |
| top-1m-2018-01-25.csv.zip |   21381 |
| top-1m-2018-01-26.csv.zip |   21736 |
| top-1m-2018-01-27.csv.zip |   21031 |
| top-1m-2018-01-28.csv.zip |   21010 |
| top-1m-2018-01-29.csv.zip |   21076 |
| top-1m-2018-01-30.csv.zip |   21209 |
| top-1m-2018-01-31.csv.zip |   21106 |

**Comment by alexey-milovidov** [comment]
@divanik, Each CSV inside the zip archive contains one million records.
But in your query, you are asked to read each file as CSV, and assuming, ClickHouse cannot read zip files without specifying the internals with `file.zip :: data.csv`, it looks like it interpreted the binary data as CSV, splitting it by newline characters.

**Comment by alexey-milovidov** [comment]
I am also copying and converting these files to our bucket, so you can use it for validation:

```
:) SELECT count() FROM s3('s3://clickhouse-public-datasets/cisco-umbrella/original/*.parquet')

SELECT count()
FROM s3('s3://clickhouse-public-datasets/cisco-umbrella/original/*.parquet')

Query id: 9f14ba33-4f73-4e91-9056-147f275e79ea

┌────count()─┐
│ 2615000000 │ -- 2.62 billion
└────────────┘

1 row in set. Elapsed: 6.790 sec. Processed 2.61 billion rows, 28.83 KB (383.83 million rows/s., 4.25 KB/s.)
Peak memory usage: 194.60 MiB.
```

**Comment by divanik** [comment]
`SELECT _file, count()
FROM s3('https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-2018-01-1*.csv.zip :: *.csv', 'NOSIGN') GROUP BY _file ORDER  BY _file;
`

|file                                           | count()|
| --------------------------- | ------  |
| top-1m-2018-01-11.csv.zip | 1000000 |
| top-1m-2018-01-12.csv.zip | 1000000 |
| top-1m-2018-01-13.csv.zip | 1000000 |
| top-1m-2018-01-14.csv.zip | 1000000 |
| top-1m-2018-01-15.csv.zip | 1000000 |
| top-1m-2018-01-16.csv.zip | 1000000 |
| top-1m-2018-01-17.csv.zip  | 1000000 |
| top-1m-2018-01-18.csv.zip | 1000000 |
| top-1m-2018-01-19.csv.zip | 1000000 |
| top-1m-2018-01-20.csv.zip| 1000000 |

**Comment by divanik** [comment]
#62259

**Comment by dorsegal** [comment]
@alexey-milovidov 
I have a use case with archive that contains `csv.gz` file. So every file in the archive is compressed as well.

```
SELECT *
FROM s3('https://bucket.s3.amazonaws.com/folder/20240518.tar.gz'', 'CSV',  'index UInt32, address String')
```
 I get  this error:
```
{ "meta": [ { "name": "index", "type": "UInt32" }, { "name": "address", "type": "String" } ], "data": [ ], "rows": 0, "exception": "Code: 27. DB::Exception: Cannot parse input: expected ',' before: 'filename.csv.gz\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\00000664\\00001755\\00001753\\000000637474\\014622062352\\0015771\\0 0\\0\\0\\0': (at row 1)\n: \nRow 1:\nColumn 0, name: index, type: UInt32, ERROR: text \"filename\" is not like UInt32\n\n: (in file\/uri bucket/folder/20240518.tar.gz): While executing ParallelParsingBlockInputFormat: While executing S3. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 24.2.2.16100 (official build))" }
```
