### ISSUE TITLE
`test_format_avro_confluent` is flaky

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#54753]
https://s3.amazonaws.com/clickhouse-test-reports/54671/0df86a189a3b45d441c62aedbf27af11ef4f3931/integration_tests__tsan__[5_6].html

cc: @ilejn, @evillique

**Comment by ilejn** [comment]
Thanks and sorry for troubling.
Looking into this.

**Comment by ilejn** [comment]
The only assumption I have at the moment - get_free_port we use in cluster.py is not robust enough.

https://pastila.nl/?01363224/d3654372d132a0b7c8f535fb957309c7#KKa7oxewrYvRz37mhrNvgg==

**Comment by rschu1ze** [comment]
The flakiness disappeared after Feb 24.

**Comment by ilejn** [comment]
Hello @rschu1ze , do we have a guess what is the reason?

**Comment by rschu1ze** [comment]
I checked again and noticed that my original query only considered error status `FAIL` but I should have checked for `ERROR` too. There were more failures with `ERROR` after Feb 24 but they were caused due to infra issues like `port is already allocated` as far as I see. The original logfiles ([here](https://github.com/ClickHouse/ClickHouse/issues/54753#issue-1900993443)) are gone and the error is not copypasted into this issue, so we actually don't know what the problem was. Let's keep this issue closed and create a new one if `test_format_avro_confluent` flakes again.

And no, I can't tell why there were no `FAIL`ed runs after Feb 24 :-/

**Comment by ilejn** [comment]
>  There were more failures with `ERROR` after Feb 24 but they were caused due to infra issues like `port is already allocated` as far as I see.

I used to think that port collision is the only issue. Will look into this, thanks.

BTW, port collision is not exactly an infra issue. See https://github.com/ClickHouse/ClickHouse/pull/55055#issue-1915255635
