### ISSUE TITLE
[Question] High IO on merge processes

### ISSUE THREAD

**Issue by igor-sh8** [ClickHouse/ClickHouse#5500]
Hi. 
We faced with some strange behavior on our clickhouse servers. 
We have such architecture:
6 x Client (30mln insert rows per minute) -> 4x Servers (20 cores, 128 RAM, Sata SSD Raid 6) -> 4 x Buffer tables per server -> 4 x Plain tables (mergetree engine) with partitions by (date,hour) and order by (Date, 3+ other dimensions) per server -> 200 Materialized views to table (summingmergetree engine) with partitions by date per server. 
Most of these materialized views - just simple slices 3+ dimensions and only two tables have 30+ dimensions. 
Our Plain tables have something about 200GB per table per day and the two largest tables - 10 GB per table per day. 
At some moment  of time we face with high IO 90-100 % on the server. At this time we see a lot of long lasting merge processes (16 - limited by BackgroundPool setting). If we decrease  BackgroundPool - we got 300 merge Exceptions.  
The main our idea that the reason of such high IO - background merge of our Plain tables.
We think so, because at first we created Plain tables with Date partition and the IO was much more then on (Date, Hour) partition.  
Ideaaly we do not need to select queries from these tables and data will store about 3 days in such tables, so how can we disable or maybe maximum decrease impact from merges on these tables    
Have you any suggestions ?
Thanks in advance.

**Comment by den-crane** [comment]
You can reduce number of the merges using Buffer tables settings (make larger batches).

You can set smaller max_bytes_to_merge_at_max_space_in_pool for these plain tables and reduce number of final merges. https://github.com/yandex/ClickHouse/issues/2607

You can set weaker compression for the first level (small) parts.

**Comment by igor-sh8** [comment]
Thanks. 
Your advises really helped us. 
Just want to clarify a little about min_merge_bytes_to_use_direct_io and max_bytes_to_merge_at_max_space_in_pool. How to work with this settings ? What are the numbers in which cases we need to set ? Maybe you have some suggestions ?

**Comment by den-crane** [comment]
>Your advises really helped us.

What did you change? And to what?

min_merge_bytes_to_use_direct_io -- this parameter controls a size of merge which should use direct disk read/write (without using Linux cache). The idea is to save more cache for selects. But it can cause more I/O because during merges (depends of insert batch size).

max_bytes_to_merge_at_max_space_in_pool -- this parameter controls a maximum of part size. So when you insert data CH creates a level0 part for each insert (i.e. ~100Mb size). During the merges several level0 parts are merged into level1 ( 8 level0 -> 1 level1 = 800Mb size) parts. CH needs it to make selects faster (reduce number of reads). And so on until part became max_bytes_to_merge_at_max_space_in_pool = 150 GB. These final merges able to cause large I/O because need to read 150GB in several pieces and write them back merged into one piece. 

Not sure what is going on with your system. Because merges depends on insert size (how many rows you insert at once) /  insert frequency (how many insert per minute). Of table widget (CH has two different type of merge (vertical / horizontal).

**Comment by igor-sh8** [comment]
Thanks for detailed info. 
We set min_merge_bytes_to_use_direct_io to 0 and made bigger parts in Buffer tables.
But we were still afraid IO problem in some near future so in our case (we do not need really store such big table) we decided to use Null Engine.

**Comment by kevinKaiF** [comment]
> > Your advises really helped us.
> 
> What did you change? And to what?
> 
> min_merge_bytes_to_use_direct_io -- this parameter controls a size of merge which should use direct disk read/write (without using Linux cache). The idea is to save more cache for selects. But it can cause more I/O because during merges (depends of insert batch size).
> 
> max_bytes_to_merge_at_max_space_in_pool -- this parameter controls a maximum of part size. So when you insert data CH creates a level0 part for each insert (i.e. ~100Mb size). During the merges several level0 parts are merged into level1 ( 8 level0 -> 1 level1 = 800Mb size) parts. CH needs it to make selects faster (reduce number of reads). And so on until part became max_bytes_to_merge_at_max_space_in_pool = 150 GB. These final merges able to cause large I/O because need to read 150GB in several pieces and write them back merged into one piece.
> 
> Not sure what is going on with your system. Because merges depends on insert size (how many rows you insert at once) / insert frequency (how many insert per minute). Of table width (number of columns) (CH has two different type of merge (vertical / horizontal).


what should set  max_bytes_to_merge_at_max_space_in_pool ?  Do you have some suggestion about  a setting in a production environment ?
