### ISSUE TITLE
Is flush function in OutputFormatWithUTF8ValidationAdaptorBase correct?

### ISSUE THREAD

**Issue by awakeljw** [ClickHouse/ClickHouse#55010]
In the file OutputFormatWithUTF8ValidationAdaptor.h, Is the flush function implementation correct?
I found this question when i used formatBlock function. when IOutputFormat flushed, it will write buffer twice. But I can't reproduce this problem through query.
In the code, 
```
 void flush() override
  {
      ostr->next();
 
      if (validating_ostr)
          this->out.next();
  }
```
but ostr is equal to this->out when validate_utf8 is true. so The code will execute twice. Actually, `ostr->next()` is enough. I comment like this 
```
 void flush() override
  {
      ostr->next();
 
 //     if (validating_ostr)
 //         this->out.next();
  }
```
it works out

**Comment by nickitat** [comment]
not exactly, `ostr` in this case is equal to `std::make_unique<WriteBufferValidUTF8>(this->out).get()` which is another buffer wrapping `this->out`. maybe it is actually unnecessary in this particular case, because this wrapper doesn't seem to accumulate any data inside itself, but still should be no harm if we would call `next()` on both buffers.
