### ISSUE TITLE
Migration cluster from CentOS to Ubuntu

### ISSUE THREAD

**Issue by boldakovds** [ClickHouse/ClickHouse#55379]
Hello!

Can you help me with a few question about migrating Clickhouse cluster 4 nodes (2 shards, 2 replica) from CentOS (3.10 core) to Ubuntu (5.15 core).
1) What's the best way to migrate CentOS to Ubuntu OS?
2) Can i change OS on 1 node (remove from cluster, reinstall OS, add to cluster)? 
(same version clickhosue of course)?
3) What should i especially pay attention to at he process of migration?

**Comment by alexey-milovidov** [comment]
ClickHouse server is compatible with both CentOS and Ubuntu.

There are two ways of migration:

1. (extending the cluster) Add a new replica (third replica of the shard) with CentOS as usual and wait for it to be fully synchronized. Then drop the tables on the old replica and remove the old machine.

2. (in-place) Sync the files in the ClickHouse data directory (/var/lib/clickhouse) preserving their ownership, and install the same ClickHouse version on the new server. Pay attention that the servers don't run at the same time, otherwise, the replicas will conflict (it will check on startup and refuse to start).

The first option is the most natural and less error-prone but takes more resources. If you don't have spare servers, proceed with the second option.

Do it gradually by replicas and observe the result. Do not start the migration of the next replica until checking the logs and monitoring.

Possible mistakes are (what to avoid): - migrating all the replicas at the same time and removing old ones without waiting for the data to be replicated; manually editing metadata in ZooKeeper in case of configuration errors (it is never required, and if you do it, it will lead to troubles).

**Comment by boldakovds** [comment]
So, it's ok if one cluster will has 1 replica on CentOS and 1 replica on Ubuntu OS? (different OS on one cluster)

**Comment by den-crane** [comment]
> So, it's ok if one cluster will has 1 replica on CentOS and 1 replica on Ubuntu OS? (different OS on one cluster)

yes, it's OK.
