### ISSUE TITLE
Convenience function for custom start of interval

### ISSUE THREAD

**Issue by tbragin** [ClickHouse/ClickHouse#55619]
**Use case**
A way to get time buckets aligned to a custom time range. 

**Describe the solution you'd like**
`toStartOfInterval` gets timestamps considering the calendar format, that is the start of minute/hour/day and so on. But is it not possible to mention a `start_time` so that the buckets start from it.

TimescaleDB provides this facility with `time_bucket(time_column, interval, start_time, end_time)` where the buckets start from the given start_time. https://docs.timescale.com/api/latest/hyperfunctions/time_bucket/#optional-arguments-for-interval-time-inputs

**Describe alternatives you've considered**

Currently a query to do this is quite verbose. Idea is to make it more concise. 

```sql
SELECT
    toDateTime(
        toUInt32(
            toStartOfInterval(
                toDateTime(toUInt32(timestamp - toDateTime('2023-01-01 12:15:00'))),
                INTERVAL 1 hour
            )
        )
        + toDateTime('2023-01-01 12:15:00')
    )
     AS bucket,
    COUNT(*)
FROM
    events
WHERE timestamp > toDateTime('2023-01-01 12:15:00')
GROUP BY bucket
ORDER BY bucket;
```

**Comment by rschu1ze** [comment]
To whoever likes to implement this (I heard someone whisper @yariks5s 😄).

Timescale's `time_bucket()`, respectively Postgres's `date_bin()` are generalizations of our `toStartOfInterval()`. I consider ClickHouse's naming more speaking than `time_bucket` and `date_bin`, so we might simply add another overload to SQL function `toStartOfInterval()` instead of introducing a new function. This will get us:
- `toStartOfInterval(time_or_data, INTERVAL x unit [, time_zone])` and
- `toStartOfInterval(time_or_data, INTERVAL x unit, origin [, time_zone])`
Basically: the type of the 3rd argument (if given), i.e. String or Date/Time dispatches between the variants.

The actual calculation can be done similar to above SQL, something like this:

```cpp
for (size_t i = 0; i != size; ++i)
{
    auto td = time_data[i];
    if (origin.get() != null) // <-- assuming origin is wrapped in std::optional<>
        td -= origin;
    result_data[i] = static_cast<ToFieldType>(ToStartOfInterval<unit>::execute(td, num_units, time_zone, scale_multiplier));
    if (origin.get() != null)
         result_data[i] += origin;
```

(there are now two additional `if`s. Branch prediction will likely do a good job, so we don't additional templatization / `constexpr if`)

Caveat: `HOUR` intervals will produce funny results due to #54906. Consider making a variant of `toStartOfHourInterval()` (Common/DateLUTImpl.h) with rollover. It can be based on (copypasted from) the existing implementation of `toStartOfMinuteInterval()` in the same file but with an additional factor `60 *` to calculate the divisor.

**Comment by rschu1ze** [comment]
Just to note: The functionality requested in this issue looked straightforward but the implementation was difficult because there were tons of special cases (which all need test coverage). The corresponding PR needed ca. 10 months until completion (with interruptions due to other priorities) and got more than 40 review comments. Thumbs up for @yariks5s!

**Comment by th0th** [comment]
Thanks @yariks5s!
