### ISSUE TITLE
NOT_FOUND_COLUMN_IN_BLOCK when using a column multiple time in where 

### ISSUE THREAD

**Issue by Zarathustra2** [ClickHouse/ClickHouse#55758]
This seems to be fixed starting in `23.8` but is an issue in `23.7.5.30`. ( I have not tried more 23.7 to see if any version is okay). 

`23.6.3.87` is also fine so this bug was introduced in `23.7` but got fixed in `23.8`

```
CREATE TABLE issue
(
    `id` UUID,
    `underlying_symbol` LowCardinality(String),
    `price` Decimal(18, 4),
    `option_type` Enum8('call' = 1, 'put' = 2),
    `strike` Decimal(18, 4),
    `underlying_price` Decimal(18, 4)
)
ENGINE = MergeTree
ORDER BY id;

insert into issue (id, underlying_symbol, price, option_type, strike, underlying_price) values ('8c325f7c-c71f-457f-8abe-5d8a0ae9cc4a', 'MSFT', 0.22, 'call', 342.5, 330.47);

SELECT o0.id FROM issue AS o0 WHERE  (o0.underlying_symbol IN ('MSFT')) AND (o0.option_type = 'call') AND ((o0.underlying_price > 0) AND (((o0.strike > o0.underlying_price) AND (o0.option_type = 'call')) OR ((o0.strike < o0.underlying_price) AND (o0.option_type = 'put')))) ;

Received exception from server (version 23.7.5):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column equals(option_type, 'call') in block: while executing 'INPUT : 2 -> equals(option_type, 'call') UInt8 : 2': While executing MergeTreeInOrder. (NOT_FOUND_COLUMN_IN_BLOCK)
(query: SELECT o0.id FROM issue AS o0 WHERE  (o0.underlying_symbol IN ('MSFT')) AND (o0.option_type = 'call') AND ((o0.underlying_price > 0) AND (((o0.strike > o0.underlying_price) AND (o0.option_type = 'call')) OR ((o0.strike < o0.underlying_price) AND (o0.option_type = 'put')))) ;)
```

Link to fiddle: https://fiddle.clickhouse.com/d3ec6a8e-17e3-4d08-9058-93d66237769b

**Comment by den-crane** [comment]
related `move_all_conditions_to_prewhere`

duplicate https://github.com/ClickHouse/ClickHouse/issues/53453
fixed https://github.com/ClickHouse/ClickHouse/pull/53492

v23.8.3.48-lts.md:* Fix: moved to prewhere condition actions can lose column [#53492](https://github.com/ClickHouse/ClickHouse/pull/53492) ([Yakov Olkhovskiy](https://github.com/yakov-olkhovskiy)).
v23.9.1.1854-stable.md:* Fix: moved to prewhere condition actions can lose column [#53492](https://github.com/ClickHouse/ClickHouse/pull/53492) ([Yakov Olkhovskiy](https://github.com/yakov-olkhovskiy)).


it was backported to 23.7, but a version of 23.7 with the fix was not yet released.
