### ISSUE TITLE
Idea: make Log, TinyLog, StripeLog tables only available under a setting.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#55911]
**Use case**

Sometimes people create these tables by mistake because they don't know that `MergeTree` is better.

**Describe the solution you'd like**

Add settings `allow_table_engine_log`, `allow_table_engine_tinylog`, `allow_table_engine_stripelog`.
If a table engine is not allowed, an exception will be thrown on CREATE statements, containing an explanation.

**Describe alternatives you've considered**

A setting to automatically interpret Log/TinyLog/StripeLog as MergeTree.

A way to allow/disallow or convert table engines in a generic way.

**Comment by bharatnc** [comment]
Can I take this?

**Comment by vdimir** [comment]
Maybe juse add message system.warning if such tables exists (or was recently created not to have it permanent for cases where used knows what he's doing)? We show it on client startup.

**Comment by bharatnc** [comment]
> Maybe just add message system.warning if such tables exists (or was recently created not to have it permanent for cases where used knows what he's doing)? We show it on client startup.

@vdimir I am not quite sure. I think the motivation here is to probably to stop people using these tables unless they absolutely need them (which from my experience is almost never in production) and so disabling them by default sounds ok to me. But, it's also worth noting that it's also quite an invasive change in the sense that a lot of tests need to be fixed by setting these settings explicitly - for them all to pass.

I have the PR #56002 in progress for this. @alexey-milovidov what do you think ?

**Comment by jsc0218** [comment]
somewhat similar to #38316

**Comment by nikitamikhaylov** [comment]
Completed via https://github.com/ClickHouse/ClickHouse/issues/38316
