### ISSUE TITLE
Avro Support

### ISSUE THREAD

**Issue by julienfr112** [ClickHouse/ClickHouse#5601]
Reopen #1342 for triage.

**Comment by alexey-milovidov** [comment]
I've read the specs briefly. Avro format looks very sound. In simplest case it will be similar to RowBinary format. Schema parsing and processing may be a bit more complicated.

By the way, I'm not familiar with popular use cases of Avro format. Could you please tell, why you are using Avro; where data comes from; why that system is using Avro, what is the background of this task?

**Comment by anindo-bandyopadhyay** [comment]
@alexey-milovidov we are using confluent KSQL as our ETL tool on top of Kafka. We are pushing data to Kafka from multiple transaction databases using CDC, then we enrich information by combining data in different Kafka topics using KSQL. Confluent recommends using AVRO format, since it not only saves space, it is also faster to process using KSQL. So we convert all the source data to AVRO format using confluent schema registry before pushing to Kafka topics. 
Hope this helps.

**Comment by Sugaroverdose** [comment]
@alexey-milovidov confluent have C library which serialise/deserialise avro and supports schema registry 
https://github.com/confluentinc/libserdes

**Comment by kirankn** [comment]
Our usecase also requires Kafka to have Avro encoded data. It would be very nice if Clickhouse could support Avro for input.

**Comment by Maiakov** [comment]
Kafka nowadays is one of the most popular event streaming platform and the most preferred message format for it is Avro. I really believe that adding avro connector extremely important for my company and whole the community in general.

**Comment by bksunday** [comment]
+1 for Avro support. This schema validated format is super useful on large scale projects involving many separate teams that may not even need to speak to each other to work with the data.

With Kafka and the AvroRegistry it ensures data is of the expected structure and type, and the full doc (schema) on that structure is viewable and easily understandable by anyone on the project(s). A "contract" is made on a topic once you push avro to it. Otherwise the data is rejected. Forces the devs to send clear predictable stuff that anyone can build on

Confluent Kafka Connect module even uses it to let you dump data from topic directly to an sql table and can even do upserts for you and give you exactly once delivery. (which any kafka consumer can do too)

.. It's probably obvious but I'd go with supporting an avro schema where the main type is a `record` with its `fields`.

```json
{
  "type": "record",
  "name": "Something",
  "fields": [
    {"name": "some_id", "type": "int", "doc": "A super useful ID of something"},
    {"name": "some_string", "type": "string", "doc": "blabla"}
  ]
}
```

and just for kicks:
```sql
CREATE TABLE my_kafka_data ENGINE = Kafka()
  SETTINGS kafka_topic_list = 'my_kafka_topic', kafka_format = 'AvroRecord'
```

**Comment by vasyaabr** [comment]
+1
It would be efficient to store queues in Avro format, because of smaller size.

**Comment by danek2003** [comment]
+1

**Comment by alexey-milovidov** [comment]
This task is assigned to external contributor, Pavel Kruglov.

**Comment by oandrew** [comment]
Hi everyone. I ended up creating a PR to support Avro + AvroConfluent.
https://github.com/ClickHouse/ClickHouse/pull/8571

**Comment by Sugaroverdose** [comment]
@oandrew any chance that it will support basic authentication on schema registry, as well as multiple urls?

**Comment by oandrew** [comment]
@Sugaroverdose most likely with the next PR once the current one is merged. Probably using libserdes would be the easiest. The main issue would be to figure out how to share state across different instances of InputFormat

**Comment by Sugaroverdose** [comment]
@oandrew just to make it clear what i mean when saying 'multiple url's':
Multiple urls are used just to support failover like confluent client does:
in config client gets list of strings(maybe choose first node from list randomly, to spread load) and if chosen schema registry node responded with status 5xx or timed out - try another one. 

So you don't have to slap HA load balancer on top of schema registry - client knows that there are multiple nodes of schema registry and can handle failure of it's nodes without leading to inability to read/write kafka topic until failed node has been restored or deserialiser/serialiser configuration changed

**Comment by alexey-milovidov** [comment]
In master.

**Comment by alexey-milovidov** [comment]
> This task is assigned to external contributor, Pavel Kruglov @Avogar.

@Avogar didn't participated in Avro development but he will be happy to implement Thrift and MsgPack :)

**Comment by filimonov** [comment]
> @Avogar didn't participate in Avro development but he will be happy to implement Thrift and MsgPack :)

 One more format-related task: is to make all formats which are avaliable as input for output too (to make roundtrips possible)

**Comment by alexey-milovidov** [comment]
@filimonov Ok and what are the priorities?
I think, the first priority is ORC, that was developed by Andrey Konyaev from ArenaData.
