### ISSUE TITLE
[RFC] Boost up CI with source files Digest

### ISSUE THREAD

**Issue by mkaynov** [ClickHouse/ClickHouse#56015]
This proposes a new source digesting technique in the CI pipeline aimed at improving overall efficiency, including computational resource utilization, reliability, pipeline execution time, and artifact/job reusability. It addresses the CI execution flow and does not cover the content of tests/checks running in the pipeline.

By source files digesting, we mean a technique that calculates a hash value over a specific part of the CH source code to facilitate the reuse of build artifacts, skip jobs if already run, and more.

### Three Ways to Improve CI with source files Digest:

1. **Digest to Reuse Build Artifacts:**
   - To reuse build artifacts whenever possible, the digest is calculated over CH source files `./src`, `./base`, `./cmake`, `./programs`, git submodules, and builder docker image(s). This is simplified bash commands to give an idea how digest is calculated for a build:
```bash
SOURCE_DIGEST=$(find ./src -type f | xargs md5sum | sort | md5sum)
MODULES_DIGEST=$(git submodule status | md5sum)
DOCKER_BUILDER_DIGEST=$(find ./docker/packager/ -type f | xargs md5sum | sort | md5sum)
BUILD_DIGEST=$(echo $SOURCE_DIGEST-$MODULES_DIGEST-$DOCKER_BUILDER_DIGEST | md5sum)
```
   - CI build jobs should calculate this digest before the build and check if the desired build with the resulting digest is already uploaded on S3. If uploaded, the job is skipped. The digest is part of the S3 URL path, e.g.: `https://s3.console.aws.amazon.com/s3/buckets/clickhouse-builds?prefix=PRs/storage/<digest>/package_release/clickhouse`.

>    **Benefits:**
>    - Can be done on a shallow cloned repo without git history or GH API usage.
>    - Artifact reuse across any git branches.
>    - Locally Reproducible.
> 
>    **Possible Obstacles:**
>    - GitHub's merge from master before testing may modify sources and digest value, decreasing the artifact reuse rate. Possible solution: Disable merge from master.
>    - Automatic build versioning may modify sources. Possible solution: Count digest before autogeneration.

2. **Digest to tag docker images:**
   - Instead of relying on GH API, git history, and CH CI database, propose calculating the digest for a docker image and using this digest as the image tag.
   - The digest is calculated based on docker files and dependent-on docker images. Shallow clone is enough to calculate docker digest. If a docker image with the resulting tag exists, CI reuses it; otherwise, it builds it.
   - This works automatically on any repo branch: master, release, or PR and avoids rebuilding docker image whenever possible.

3. **Tests Digest:**
   - A digest could be calculated against each test category (Functional, Integration, etc.). If this digest is written to the CI checks database, it provides a means to skip certain Test Cases for a specific build and test digests match. This could be beneficial in case of job re-run due to AWS spot instance restarts.

**Comment by Algunenano** [comment]
Nice approach.

Some comments:
* `SOURCE_DIGEST=$(find ./src -type f | xargs md5sum | sort | md5sum)`  is missing other source folders (base/ cmake/ programs/ at least) which is worrisome because somebody needs to keep this updated with any folder changes or you'll get old/invalid artifacts and won't notice a thing.
* Any estimation / verification on which percentage of runs would be improved by this?
* Based on the above, what is the reason we are rebuilding the same thing multiple times? Would a different approach help there?

**Comment by mkaynov** [comment]
> Nice approach.
> 
> Some comments:
> 
> * `SOURCE_DIGEST=$(find ./src -type f | xargs md5sum | sort | md5sum)`  is missing other source folders (base/ cmake/ programs/ at least) which is worrisome because somebody needs to keep this updated with any folder changes or you'll get old/invalid artifacts and won't notice a thing.
> * Any estimation / verification on which percentage of runs would be improved by this?
> * Based on the above, what is the reason we are rebuilding the same thing multiple times? Would a different approach help there?

Thanks for the comment. I updated source paths in the text for the build digest. 
* It's difficult to give some numbers on how many runs could be improved by build digest usage, but given the fact that some commits address only tests, docs, ci scripts without touching the CH binary, it's expected to be beneficial.
* Docker images digesting: We do not change dockers too often (at least for master or PRs) and main benefit here, I think, is making CI scripts more generic and simple when it comes to maintaining docker tags.
* Test digests: this is the most tricky thing too implement. From the CI _checks_ DB I would estimate number of failed jobs  due to spot instance going down (number of completed job steps <= 5) as ~2-3%. There are also other cases when it can help to skip some unnecessary work (e.g. binary and certain test category has not been changed in the commit). I don't expect it will take place very often but anyway can help get faster results for a developer.

* Why do we rebuild the same thing? Because we have nothing to control it at the moment and this improvements suggest to change this.

**Comment by Algunenano** [comment]
> Why do we rebuild the same thing? Because we have nothing to control it at the moment and this improvements suggest to change this.

Have we thought of any way to allow retry on certain tasks only? Many of the reruns I've seen are from people retrying because of flaky CI (flaky tests or instances), and what has happened is people rebase / merge master to retrigger a full CI run. If a limited number of people could re-run a single task then we'd avoid rerunning the other 100+ tasks unnecessarily.

**Comment by mkaynov** [comment]
> > Why do we rebuild the same thing? Because we have nothing to control it at the moment and this improvements suggest to change this.
> 
> Have we thought of any way to allow retry on certain tasks only? Many of the reruns I've seen are from people retrying because of flaky CI (flaky tests or instances), and what has happened is people rebase / merge master to retrigger a full CI run. If a limited number of people could re-run a single task then we'd avoid rerunning the other 100+ tasks unnecessarily.

Yes, this is a good point where we can improve. First of all, flaky tests are so annoying and there shouldn't be flaky tests in CI, I believe. Regarding re-run failed job, actually, it's possible now, though it will require manual work-around to reset failed job status via GH API before rerun. I think we can improve here but this topic is not in scope now. However, described approach with digesting can help too in case of pipeline re-run as it allows to skip builds (1), skip docker builds if any (2), skip successful test jobs (3).

**Comment by mkaynov** [comment]
> We already use ccache / sccache to reuse object files compiled from unchanged source files between builds. Are digests orthogonal to that?

sccache speeds up our builds significantly, but still loads, compiles, links, dumps, etc. _Build Digest_ lets you skip the build step entirely when possible, so I'd say it's orthogonal

**Comment by antaljanosbenjamin** [comment]
> The digest is calculated based on docker files and dependent-on docker images. Shallow clone is enough to calculate docker digest. If a docker image with the resulting tag exists, CI reuses it; otherwise, it builds it.

@Felixoid please correct me if I am wrong, but I think two docker images from the same docker files could be different depending on when they were built, e.g.: `sudo apt install` can install different versions of package. I am not sure currently how do we ensure the freshness of packages (especially questionable with [enrich_images](https://github.com/ClickHouse/ClickHouse/blob/1d5f75fd716c36f474a94ca4d67bf7598ab1cd4b/tests/ci/docker_manifests_merge.py#L178-L243), we kind of reusing old images), but we should think about this also.

Speaking of `enrich_images`, doesn't that skip the building of docker images?

**Comment by mkaynov** [comment]
> I think two docker images from the same docker files could be different depending on when they were built, e.g.: `sudo apt install` can install different versions of package.

You are right. There is nightly job that continuously update latest docker images, images(tags) built for previous commits are not being updated. I thinks it's appropriate and it should work the same way with digest as a tag.

**Comment by rschu1ze** [comment]
> sccache speeds up our builds significantly, but still loads, compiles, links, uploads, etc. Build Digest lets you skip the build step entirely when possible, so I'd say it's orthogonal

Thanks. Very generally speaking, the effort that any CI will do falls into two categories:
- work that cannot be avoided because it has never been done before
- work that can be avoided because it was done before.

I wonder how big the relation between both categories is for ClickHouse's CI. I'll give an example.

Think about functional/integration/other tests: Their output depends on the tested ClickHouse binary which will be different between different PRs. So the only chance to save work will be "within" a PR. For example, I often run into the situation that I change the C++ code and the tests. This then goes into one or multiple commit. CI then often finds issues (e.g. flaky tests) which I then fix by adjusting tests while the code remains unchanged (example [here](https://github.com/ClickHouse/ClickHouse/pull/55983, commit "Try to stabilize test"). Builds currently start regardless and because of sccache they will be "fast" (compared to a scratch build). The question is however how much *not* starting the build jobs (due to digests) would save us in relation to the unavoidable costs of CI jobs for such a commit. The unavoidable costs are dominated by the cost of the test jobs.

But maybe I miss something as I am not an expert in CI and other are other situations where digests are useful.

**Comment by mkaynov** [comment]
@rschu1ze
I see following cases where we could save work with build digest:
1. commits within a PR with no CH source files touched 
2. pipeline reruns
3. whole PR could touch only tests (for instance), so build could be taken from base branch

I think you make a good point that relation of avoidable builds against all jobs is small and  I don't expect _build skip by the digest_ to be more than a small share in total CI execution time, given that build jobs itself are small part of pipeline duration, though I do expect important benefits of this:
1. we still avoid wasting many VM-hours and storage in absolute numbers, as we have many parallel builds for each commit and  it comes at zero cost: easy to calculate, code should be simple and generic and work for any branch or for re-runs
2. it opens up door for next improvement: skipping tests if say _build and test digest_ pair already done which might save way more time (item 3 - tests digest)

**Comment by Felixoid** [comment]
Huh, it's a lot to follow up on the very first day after the vacation, so I've postponed it. So far I'll address only the most controversial topic of docker images.

The digest as the tags IMHO won't work for us. For many reasons:

- The directory with a Dockerfile itself won't provide the full picture of the image. First, because we have `FROM` (in details below), and second because we don't pin every software version there in apt and pipy. As @antaljanosbenjamin said. And I am against the idea of global pinning.
- We'll lose the `docker buildx --cache-from` feature because we won't know the previous digest. This is a game-breaker.
- Then the script to determine each `FROM_TAG` will become much more complex, and will work in the [build_and_push_one_image](https://github.com/ClickHouse/ClickHouse/blob/1e4fe038f562029fc24a0e7a33e5d428ea0474f9/tests/ci/docker_images_check.py#L213) stage. The whole dependency tree building will look redundant and broken at the same time.
- Now we can run `docker run ... clickhouse/binary-builder:56015 bash` and investigate it without additional steps to identify the image tag. Losing it is a slight inconvenience.
- Think of the cloud repo, where directories could be different `just because`. So, the whole system will break, because the tag does not exist?
- Altogether, it will probably cause the reworking of the whole docker building system.

Given it, what's the flaw of the current system? Using clickhouse service for getting the last built images? We are heavily bound to this service. We don't use anything else, and the full checkout after the recent `filter:tree=0` is very fast now.

JFYI, there's a ticket to improve the mentioned places a little bit https://github.com/ClickHouse/ClickHouse/issues/41568, but it's about a completely orthogonal problem.

**Comment by Felixoid** [comment]
Now, regarding the first, the most promising part. Digest to reuse the build artifacts. I'll describe it in python code, the place where it would be mostly implementer is near the cargo cache in [ccache_utils](https://github.com/ClickHouse/ClickHouse/blob/c5b1aa4/tests/ci/ccache_utils.py#L101) (side notes - let's rename it to cache_helper? ccache is dead, long live the ccache)

- It should respect `force tests` label.
- The full list of files to get the digest from the repo is `./programs ./src ./contrib/*-cmake ./base ./cmake ./rust + **/CMakeLists.txt`
- Instead of long running `git submodule status` we should calculate the instant `.git/modules/contrib/*/HEAD`. It mostly will cross with `**/CMakeLists.txt`, but well, it shouldn't make things worse.
- `DOCKER_BUILDER_DIGEST` should be calculated out from `docker/packager/packager` + `docker_builder_tag`. Simple as is
- Here is a tricky part. We don't actually know currently the state of the CI script. Sure, we can check the script itself, but it's unreliable. I think of something like https://github.com/thebjorn/pydeps to build the dependency tree. **5 minutes later** we'll calculate this nice thing `[k.__file__ for k in sys.modules.values() if hasattr(k, '__file__') and 'tests/ci' in k.__file__]`, but instead of `tests/ci` we should use a proper files' directory
- The digest should also include the build_type. Like `package_release` etc.
- And the main discussed thing. We won't change the scheme or build artifacts, but instead save the build report in `ccache/build-reports`. Because it will allow to have a lightweight "symlink" to the build results.

I think, that's it
