### ISSUE TITLE
[clickhouse-odbc-bridge] performance

### ISSUE THREAD

**Issue by bibabolynn** [ClickHouse/ClickHouse#56192]
ClickHouse uses clickhouse-server  and a separate program clickhouse-odbc-bridge to comunicate with external database instead of one clickhouse-server process ,  will this affects the performance of query and mutation of external databases. 

Is there anywhere I can get the performance data related ?
Does clickhouse offer a way to build  odbc bridge in clickhouse-server ?

Thanks.

**Comment by alexey-milovidov** [comment]
ODBC drivers can only run in a separate process because otherwise, they are a source of security vulnerabilities, supply-chain attacks, memory unsafety, remote code execution, memory leaks, data races, deadlocks, everything else, and even more.

However, the way how clickhouse-server interacts with clickhouse-odbc-bridge could be optimized.
