### ISSUE TITLE
Return same datas by query cache after change some alias

### ISSUE THREAD

**Issue by uranuswch** [ClickHouse/ClickHouse#56258]
ClickHouse version: 23.8.3

```
CREATE OR REPLACE TABLE test
(
    `id` UInt64
)
ENGINE = MergeTree
ORDER BY id;

INSERT INTO test VALUES (1),(2),(3);
```

If I set `use_query_cache=1`, `SELECT id FROM test` and `SELECT id AS id1 FROM test` return the same datas, column name is `id`, which `id1` should the correct answer for the second query.

Is it by design?

**Comment by den-crane** [comment]
>Is it by design?

It's an issue.

https://fiddle.clickhouse.com/b97c64db-4769-43b4-a9ea-9ca43c1cbc9c

**Comment by rschu1ze** [comment]
Mini repro: https://fiddle.clickhouse.com/fe5c7c45-0293-4bde-981c-71008c8b173b

The query result cache indexes the stored query results by the hashes of the corresponding query ASTs. A query is answered directly from the cache only if the hash of its AST matches a hash of another querie's AST stored in the query cache.

The problem is (as far as I see), that hashing of ASTs (`IAST::getTreeHash()`) ignores aliases, i.e. is based on the underlying column name. Queries `SELECT id FROM test` and `SELECT id AS id_x FROM test` produce the same hash. They also produce the same result, if one considers field names not part of the result.

I could change the hashing to hash "physically" instead of "logically". At this point it seems like a trade-off: logical hashing makes the query cache cover (a few) more cases at the cost of surprising result field names (we could document that). I could actually not come up with a counter example, where the current behavior causes truly wrong results.

**Comment by Algunenano** [comment]
Here you go, the cache returning wrong results:

```
production-01 :) Select 10 as dummy, dummy from system.one limit 1;

SELECT
    10 AS dummy,
    dummy
FROM system.one
LIMIT 1

Query id: 832da2f7-4219-4dfd-a882-35cc3f6a74a7

┌─dummy─┬─dummy─┐
│    10 │    10 │
└───────┴───────┘

1 row in set. Elapsed: 0.001 sec. 

production-01 :) Select 10 as other, dummy from system.one limit 1;

SELECT
    10 AS other,
    dummy
FROM system.one
LIMIT 1

Query id: 8591aa82-fc9d-4fb8-8a60-50bd6d457160

┌─dummy─┬─dummy─┐
│    10 │    10 │
└───────┴───────┘

1 row in set. Elapsed: 0.001 sec. 
```

Without cache:
```
production-01 :) Select 10 as other, dummy from system.one limit 1 settings use_query_cache = 0

SELECT
    10 AS other,
    dummy
FROM system.one
LIMIT 1
SETTINGS use_query_cache = 0

Query id: 58b4f6fd-9004-462d-b0ad-a0b51efac1a2

┌─other─┬─dummy─┐
│    10 │     0 │
└───────┴───────┘

1 row in set. Elapsed: 0.001 sec.
```

**Comment by Algunenano** [comment]
Note that this issue is also present in CTE's caching -> https://github.com/ClickHouse/ClickHouse/issues/33825
