### ISSUE TITLE
Configurable limit on the number of databases, tables, partitions, or parts per user and per server.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#56347]
**Use case**

See also https://github.com/ClickHouse/ClickHouse/issues/56346

**Describe the solution you'd like**

A global per-server counter could be implemented with ProfileEvents.
In an attempt to create a database, table, or on INSERT, an exception will be thrown if the threshold is exceeded.

Per-user counters are slightly more complex to implement.
As we don't have attribution of a table to the user who created it,
we can count all visible (accessible for SHOW, INSERT, or SELECT) databases and tables for a user.

This counter does not need to be persisted. It should be calculated on the fly.

**Comment by FTang21** [comment]
Hello, I am graduate student and I would like to work on this as part of my project. Would it be possible for me to work on this and have it be assigned to me?

**Comment by alexey-milovidov** [comment]
@FTang21, this task could be good for that.

But there are two considerations:
- it is not big and well-contained - maybe a few weeks of work maximum if you know the codebase;
- we need it in the perspective of two months;

**Comment by FTang21** [comment]
HI @alexey-milovidov,

Thank you for your response. I have discussed with my instructor that this issue should be sufficient work in addition to other issues I will be working on in other repositories. The deadline for my project is about a month time, so I hope to complete in the next few weeks. 

Aside from that, if I get permission to work on this, is there any other advice that you can give to get started on this issue besides the details that have already been provided.

**Comment by alexey-milovidov** [comment]
Ok, let's start working on this issue. I will be happy to advise, and we can discuss the details right here.

**Comment by ramseyxu** [comment]
What I will do in the first PR:

Throw an exception when:

1. Total number of databases exceeds a specified threshold
2. Total number of tables exceeds a specified threshold
3. Total number of ReplicatedMergeTree family tables (like ReplicatedMergeTree, ReplicatedReplacingMergeTree, etc.) exceeds a specified threshold, due to their higher Keeper usage.

Global-level limitation can address the majority of problems more effectively and with greater simplicity.

Partitions and parts limitations are less related and combining them into a single PR is unnecessary. This approach will help maintain clarity and focus.

My design:

1. Counting existing number of tables/databases
    
    Previous PR [[Warnings on a large number of dbs/tables](https://github.com/ClickHouse/ClickHouse/pull/57375/files#diff-c7c4cea868f661341c1e9866836dc34c1c88723f9f33b4e09db530c2ea074036)](https://github.com/ClickHouse/ClickHouse/pull/57375/files#diff-c7c4cea868f661341c1e9866836dc34c1c88723f9f33b4e09db530c2ea074036) already has a counter for AttachedTable/AttachedDatabase. I will reuse them.
    
    Add a new Metric to count ReplicatedMergeTree family tables: AttachedReplicatedMergeTreeFamilyTable
    
    It is also maintained when attach/detach table in DatabasesCommon & DatabasesLazy
    
    The method to check if is replicated table refer to below
    
2. Add settings to control threshold of throwing exceptions
    1. max_table_num: default 5000 (same as warning
    2. max_database_num: default 1000 (same as warning
    3. max_replicated_merge_tree_family_table_num: default 3000 (my intuition
3. Check tables/databases count during creation. Throw exceptions if the limits are exceed.
    
    In `InterpreterCreateQuery::doCreateTable` before `database->createTable`
    
    It won’t override any parser or interpreter exceptions. And won’t leave any garbage metadata (generated in `database->createTable`)
    
    To check if it’s replicatedMergeTree family table, there’s an existing example around `database->createTable`
    
    `bool is_replicated_storage = typeid_cast<const StorageReplicatedMergeTree *>(res.get()) != nullptr;`
