### ISSUE TITLE
First Map key is lost in str_to_map

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#56357]
```
SELECT
    str_to_map('{"a":"1", "b":"2"}'),
    str_to_map('{"b":"2", "a":"1"}')

Query id: c1a1fe08-9430-4de2-94f5-abb206745914

┌─extractKeyValuePairs('{"a":"1", "b":"2"}')─┬─extractKeyValuePairs('{"b":"2", "a":"1"}')─┐
│ {'':'1','b':'2'}                           │ {'':'2','a':'1'}                           │
└────────────────────────────────────────────┴────────────────────────────────────────────┘

1 row in set. Elapsed: 0.002 sec.
```

https://fiddle.clickhouse.com/9f3209f4-c0b9-44e4-9795-491be94fa8f3

**Comment by alexey-milovidov** [comment]
@arthurpassos PTAL^

**Comment by arthurpassos** [comment]
This is expected behavior. The character `{` is considered to be a normal character, thus it's part of the key. Since it's the first character it finds, it assumes the key is not a quoted key. But then it proceeds to find a quoting character `"`, which is not expected at that position and causes the behavior you are seeing.

To fix this, you can specify that the character `{` is a pair delimiter. When overriding the special characters, you might wanna consider specifying the default ones. You can read more in **[extractKeyValuePairs docs](https://clickhouse.com/docs/en/sql-reference/functions/tuple-map-functions#extractkeyvaluepairs)**.

```
arthur :) select extractKeyValuePairs('{"a":"1", "b":"2"}', ':', '{ ,;')

SELECT extractKeyValuePairs('{"a":"1", "b":"2"}', ':', '{ ,;')

Query id: 3202b338-2343-4e0f-81bc-82c536117d77

┌─extractKeyValuePairs('{"a":"1", "b":"2"}', ':', '{ ,;')─┐
│ {'a':'1','b':'2'}                                       │
└─────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.006 sec. 
```

**Comment by arthurpassos** [comment]
Will look into it. There is a chance this is expected behavior because of the `{` character. In the meantime, you can get it working if you set it to be a pair delimiter. See example below:

```
arthur :) select extractKeyValuePairs('{"a":"1", "b":"2"}', ':', '{ ,;')

SELECT extractKeyValuePairs('{"a":"1", "b":"2"}', ':', '{ ,;')

Query id: 3202b338-2343-4e0f-81bc-82c536117d77

┌─extractKeyValuePairs('{"a":"1", "b":"2"}', ':', '{ ,;')─┐
│ {'a':'1','b':'2'}                                       │
└─────────────────────────────────────────────────────────┘

```

**Comment by qoega** [comment]
1. This behaviour(losing key) looks as a bug. There is no error shown etc.
2. I see the biggest UX issue is that you can't parse toString back to Map.
```
SELECT
    extractKeyValuePairs('{"a":"1", "b":"2"}', ':', '{ ,;') AS m,
    toTypeName(m) AS type,
    toString(m) AS s,
    extractKeyValuePairs(s) AS e,
    m = e AS eq

Query id: ce8878a4-5dee-48bf-a853-b44f616c9993

┌─m─────────────────┬─type────────────────┬─s─────────────────┬─e───────────────────────────────────┬─eq─┐
│ {'a':'1','b':'2'} │ Map(String, String) │ {'a':'1','b':'2'} │ {'{\'a\'':'\'1\'','\'b\'':'\'2\'}'} │  0 │
└───────────────────┴─────────────────────┴───────────────────┴─────────────────────────────────────┴────┘
```
3. We should support parsing of JSON to Map and our toString to Map without any additional settings.

**Comment by arthurpassos** [comment]
> 1. This behaviour(losing key) looks as a bug. There is no error shown etc.
> 2. I see the biggest UX issue is that you can't parse toString back to Map.
> 
> ```
> SELECT
>     extractKeyValuePairs('{"a":"1", "b":"2"}', ':', '{ ,;') AS m,
>     toTypeName(m) AS type,
>     toString(m) AS s,
>     extractKeyValuePairs(s) AS e,
>     m = e AS eq
> 
> Query id: ce8878a4-5dee-48bf-a853-b44f616c9993
> 
> ┌─m─────────────────┬─type────────────────┬─s─────────────────┬─e───────────────────────────────────┬─eq─┐
> │ {'a':'1','b':'2'} │ Map(String, String) │ {'a':'1','b':'2'} │ {'{\'a\'':'\'1\'','\'b\'':'\'2\'}'} │  0 │
> └───────────────────┴─────────────────────┴───────────────────┴─────────────────────────────────────┴────┘
> ```
> 
> 3. We should support parsing of JSON to Map and our toString to Map without any additional settings.

First of all, there was never a requirement or association between Map x toString x extractKeyValuePairs. The main goal was to build a generic function (i.e, customizable to user needs) that could handle semi-structured data (i.e, it can contain noise and irregularities). For specific data formats like JSON, other functions should be used.

`str_to_map` and any other alias was not something I created or was part of the design.

Regarding your bullet points:

1. I think I can address this use case by either changing the logic in `extractKeyValuePairs` or customizing the `str_to_map` alias to pass those arguments by default.
2. `extractKeyValuePairs` default quoting character is double quotes. When you call `extractKeyValuePairs` with the output of `toString`, you are passing a string with single quotes. That's why you see different outputs. In order to get the same output, you need to override the default quoting character to be single quotes in the 2nd call. Again, `toString(map_value)` and `extractKeyValuePairs()` were not designed to be compatible or anything of the sort.
3. Again, function was not designed to handle specific data formats like JSON.
