### ISSUE TITLE
Non-deterministic query throws if query_cache is enabled

### ISSUE THREAD

**Issue by jaumecastell** [ClickHouse/ClickHouse#56504]
**Describe the unexpected behaviour**
With version  23.10.1.1, query cache is not working properly, as it throws for non-deterministic queries, instead of not caching and giving results.

**How to reproduce**
* Which ClickHouse server version to use:  23.10.1.1
* Queries to run that lead to unexpected result: Any query of this type: 

SELECT count() FROM <table> WHERE datetime >= now() - INTERVAL 5 minute

**Expected behavior**
The query finishes correctly and results are not cached.

**Error message and/or stacktrace**
Code: 704. DB::Exception: Received from localhost:9000. DB::Exception: Unable to cache the query result because the query contains a non-deterministic function. Use setting `query_cache_store_results_of_queries_with_nondeterministic_functions = 1` to cache the query result regardless. (CANNOT_USE_QUERY_CACHE_WITH_NONDETERMINISTIC_FUNCTIONS)

**Comment by den-crane** [comment]
example  https://fiddle.clickhouse.com/4311ce42-43c2-40a8-9c86-b5cbd1698db3

**Comment by den-crane** [comment]
Maybe one more setting to not throw exception.
Or 
query_cache_store_results_of_queries_with_nondeterministic_functions
    0 - Disabled
    1 - Enabled
    2 - Suppress/Pass (default)

**Comment by rschu1ze** [comment]
The behavior is due to recent PR #54801. In general, I think throwing an exception by default is less surprising + confusing for users than silently caching a non-deterministic result.

About https://github.com/ClickHouse/ClickHouse/issues/56504#issuecomment-1803694186: I like that, let me implement it.

**Comment by jaumecastell** [comment]
Hi @den-crane @rschu1ze , thanks for the quick reply. So, just to clarify, in previous versions non-deterministic were cached? Or not cached and no exception was thrown?

**Comment by rschu1ze** [comment]
@jaumecastell Results of queries with non-deterministic functions were cached in previous versions and no exception was thrown. Since this behavior was rather surprising, starting from ClickHouse v23.9, such queries now throw an exception.

PR #56519 which I just pushed (it will likey end up in v23.11) will not change this behavior but add a third option to ignore such queries, i.e. don't cache the result but also don't throw an exception.

**Comment by jaumecastell** [comment]
Hi @rschu1ze thank you very much for the explanation and for the work of adding this. I'll keep an eye on it to see when it's deployed.
