### ISSUE TITLE
a bug when a table using annoy index one more columns

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#57557]
(1) create table :
CREATE TABLE 02354_annoy
(
    id Int32,
    embedding Array(Float32),
	embedding_2 Array(Float32),
    INDEX annoy_index embedding TYPE annoy(100) GRANULARITY 1,
	INDEX annoy_index2 embedding_2 TYPE annoy(100) GRANULARITY 1,
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity=5;

(2) insert data:
INSERT INTO 02354_annoy VALUES (1, [0.0, 0.0, 10.0],[0.0, 1.0, 10.0,100])
(3) select 
3-1)SELECT *
FROM 02354_annoy
WHERE L2Distance(embedding, [0.0, 0.0, 10.0]) < 1.0
 order by  L2Distance(embedding, [0.0, 0.0, 10.0])  LIMIT 5;
that's ok.

3-2) select using the second annoy index column
SELECT *
FROM 02354_annoy
WHERE L2Distance(embedding_2, [0.0, 0.0, 10.1,90.0]) < 1.0
 order by  L2Distance(embedding_2, [0.0, 0.0, 10.1,90.0])  LIMIT 5;

get error: DB::Exception: The dimension of the space in the request (4) does not match with the dimension in the index (3). (INCORRECT_QUERY)

there may be a bug in using annoy index in one table on columns  twice

**Comment by rschu1ze** [comment]
Hi, you must be using some ancient version of ClickHouse because syntax `[...] TYPE annoy(100) [...]` in `CREATE TABLE` was disallowed a long time ago. Please check the [docs](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/annindexes#annoy-annoy) and try with a recent ClickHouse version again.

I also tried on recent `master`-branch version, and both SELECTs worked as expected.
