### ISSUE TITLE
(ANNOY index - experimental feature) problem about using annoy index

### ISSUE THREAD

**Issue by miaojianxin** [ClickHouse/ClickHouse#57737]
1.  create table

 CREATE TABLE test_data10yi_annoy_index_part
(
	t date,
    id Int32,
	my_id Int32,
	my_type  String,
    embedding Array(Float32),
   
INDEX annoy_image embedding TYPE annoy('cosineDistance',1000) GRANULARITY 1000
)
ENGINE = MergeTree
PARTITION BY t
ORDER BY id

2. insert data  the embedding  is 512 dim  
   insert data  quantity 10,000,000 records
4.  select *  from test_data10yi_annoy_index_part  order by cosineDistance(.....) limit 10;
  the select is very slow,  can you show me how to use the annoy index? thank you

**Comment by miaojianxin** [comment]
I use the newest source in  clickhouse master  and compile it,

before use annoy index, I set allow_experimental_annoy_index=1

**Comment by melvynator** [comment]
What's your index granularity? 

Can you run `EXPLAIN indexes`?

**Comment by rschu1ze** [comment]
Kindly first the explanations and usage recommendations in the [docs](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/annindexes) carefully:
- Annoy index parameter `NumTrees` in the example is 1000 which is 10x larger than the default of 100
- The index granularity in the example is 1000 which is much lower than the default index granularity of 1 million for ANN indexes.

In the examples, the parameters are set in a way that accuracy is favored over speed. If you want things otherwise, please change the parameters.
