### ISSUE TITLE
[Experimental feature: Inverted Index] Error "Needle must not contain whitespace or separator characters" in hasToken

### ISSUE THREAD

**Issue by infisamk** [ClickHouse/ClickHouse#57823]
Version 23.11.1

When I search records by string with some characters (```!`@"%&(-_=[\.,'/<>```), then I recived error:

```sql
SET allow_experimental_inverted_index = true;
CREATE TABLE events (
  d DateTime DEFAULT NOW(),
  body String,
  INDEX inv_idx body TYPE inverted(2) GRANULARITY 1
) ENGINE=MergeTree ORDER BY d;

INSERT INTO events (body) VALUES ('<username>test</username>');
INSERT INTO events (body) VALUES ('<eventId>1</eventId>');
INSERT INTO events (body) VALUES ('<username>test</username><eventId>1</eventId>');

SELECT * FROM events where hasToken(body, '<eventId');
```
```
Received exception from server (version 23.11.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Needle must not contain whitespace or separator characters: while executing 'FUNCTION hasToken(body : 0, '<eventId' :: 1) -> hasToken(body, '<eventId') UInt8 : 2': While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (BAD_ARGUMENTS)
(query: SELECT * FROM events where hasToken(body, '<eventId');)
```

https://fiddle.clickhouse.com/641326b2-51af-490a-b468-cfc9955ca246

How I can search string with these characters?

**Comment by rschu1ze** [comment]
This is unrelated to the inverted index, the same happens for bloom-filter based indexes `ngrambf_v1` and `tokenbf_v1`. These indexes are based on tokenization, e.g. `tokens` or `ngrams(n)` for the inverted index (see [here](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/invertedindexes)).

The thing is that `hasToken()` rejects patterns that are no tokens (based on the `token` tokenizer).

What would work is

```sql
SELECT * FROM events where hasToken(body, 'eventId');` -- that's actually a token
```

or

```sql
SELECT * FROM events where hasTokenOrNull(body, '<eventId');` -- fails gracefully
```

Of course, I hear you say that 

```sql
[...]
INDEX inv_idx body TYPE inverted(2) GRANULARITY 1
[...]
```

uses the `ngram` tokenizer and that at least prefix `<ev` is a valid token. Correct, but it seems that `hasTokens()` was purpose-build for the `token` tokenizer, so that wont' work at the moment. Try with a `LIKE` filter.
