### ISSUE TITLE
Query overcommit tracker development status

### ISSUE THREAD

**Issue by tomershafir** [ClickHouse/ClickHouse#58004]
I wonder whats the development status of the query overcommit manager? did you observe its usefulness? do you plan to improve it?

**Comment by alexey-milovidov** [comment]
It is enabled by default, and we achieved the goal of setting `max_memory_usage` to zero by default instead of a fixed value. This was more than a year ago. So far, it works without any issues.

We also want to rework the thresholds of spilling to disk. Currently, it is static, but we want to make it adaptive.

**Comment by tomershafir** [comment]
@alexey-milovidov I wonder wdyt on trying to pull some Linux OOMKIller ideas, as theoretically you solve similar problems, for example: 
- Use Linux PSI to trigger kill, rather than experience degraded performance, like oomd does.
- Postpone kill if things should get better soon, by stats.
- Try improve victim selection score calc.
- More flexible user config.
I dont know your problem distribution, I would guess none, then the above is less relevant :)
I can elaborate if it makes sense
