### ISSUE TITLE
Flush cached result when user switch role

### ISSUE THREAD

**Issue by santrancisco** [ClickHouse/ClickHouse#58054]
Cache query results are tied to the user and their queries. The authorisation on the data being accessed is checked at the time the queries execute but not when retrieving the cache. As such, Any changes on user's permission in between queries will not be reflected on the cached query result.

Simple steps to test

```
CREATE USER admin IDENTIFIED BY  'password';

GRANT CURRENT GRANTS ON *.* TO admin WITH GRANT OPTION;

-- Login as admin.  Could be done anytime after admin creation, but must be
-- done before table can be queried, after grants are given

-- 1. Create the table
CREATE TABLE user_data
(
    ID UInt32,
    userID UInt32
)
ENGINE = MergeTree
ORDER BY userID;

-- 2. Create roles with row-level security

-- Role for users with userID = 1

CREATE ROLE user_role_1;
GRANT SELECT ON user_data TO user_role_1;
CREATE ROW POLICY user_policy_1 ON user_data
    FOR SELECT USING userID = 1 TO user_role_1;

-- Role for users with userID = 2

CREATE ROLE user_role_2;
GRANT SELECT ON user_data TO user_role_2;
CREATE ROW POLICY user_policy_2 ON user_data
    FOR SELECT USING userID = 2 TO user_role_2;

-- 3. Grant roles to the admin user

GRANT user_role_1, user_role_2 TO admin;

INSERT INTO user_data (ID, userID) VALUES (1, 1), (2, 2), (3, 1), (4, 3), (5, 2), (6, 1), (7, 4), (8, 2);


-- Switch to admin if not already done so

-- Policy test

SET ROLE user_role_1;

-- only returns rows for user_role_1
SELECT * FROM user_data;

SET ROLE ALL;
SET ROLE user_role_2;

-- only returns rows for user_role_2
SELECT * FROM user_data;

SET ROLE ALL;
SET ROLE user_role_1;

-- only returns rows for user_role_1
SELECT * FROM user_data SETTINGS use_query_cache=1;

SET ROLE ALL;
SET ROLE user_role_2;

-- 🚨🚨🚨🚨 user_role_1 ROWS is returned here instead of user_role_2🚨🚨🚨🚨
SELECT * FROM user_data SETTINGS use_query_cache=1;
```

While i think the current behaviour is somewhat expected from a caching layer (this is similar to how web server caching behaves where CDN doesnt have context of user permissions and one would rely on the cache to eventually expire) and the issue only surface in a very particular setup & usage of cached query. For now, i [updated the documentation to warn about this behavior](https://github.com/ClickHouse/ClickHouse/pull/58053) until we solve it properly.

**Describe the solution you'd like**

A simple fix would be to flush any cache result when the roles are updated.

A more complex fix that may help when users switching roles/context all the time and still want to use cached query results is to incorporate into the query cache some sort of hash key with current grant (or at least the rolenames) to be checked when returning cache result.=

**Comment by rschu1ze** [comment]
When it comes to security, we rather keep things simple, i.e. flush the cache instead of adding grants/roles to the query cache key. Since flushing would affect only the entries of a single user (leaving other user's entries cached), and role changes are rather rare, performance impact will be negligible in the common case.

@vitlibar I guess you know RBAC best. I have a few questions:
- I suppose these queries are affected:
    - DROP USER (needs query cache flush to prevent the creation of a new user with the same name that could access query cache entries of the dropped user)
    - SET ROLE (needs query cache flush to prevent bypassing row policies, that's @santrancisco's example)
    - anything else I missed?

- Could you please point me to files/functions in the code for each of the scenarios where a cache flush could be done?

**Comment by vitlibar** [comment]
Flushing the cache doesn't look quite good because
1. there can be simultaneous sessions with the same user and different roles
2. it seems maybe difficult to understand when the cache must be flushed. For example, users as well as roles can be stored in ZooKeeper and so they can be changed remotely. We can subscribe on that of course but that would seem quite complicated.

I think it's both easier and reliable to improve [QueryCache::Key](https://github.com/ClickHouse/ClickHouse/blob/6aee18ced8f2428c2d48dd0be78dd29be68cd97d/src/Interpreters/Cache/QueryCache.h#L55) instead. For example, we could replace `user_name` there with `user_id` (that will help with the case with `DROP USER` and then creating a user with the same name again), and also we could add `std::vector<UUID> current_roles` and maybe `Settings settings` to `QueryCache::Key` like it's done for `AsynchronousInsertQueue::InsertQuery`.
