### ISSUE TITLE
version GLIBC_2.30 not found

### ISSUE THREAD

**Issue by zhongyuankai** [ClickHouse/ClickHouse#58615]
我在ubuntu上编译，在centos8上运行出现
I compiled `v23.8.9.54-lts` on ubuntu, and when I ran it on `centos8`, `version GLIBC_2.30 not found` appeared.
```
./clickhouse: /lib64/libpthread.so.0: version `GLIBC_2.30' not found (required by ./clickhouse)
```
**Operating system**
CentOS Linux release 8.2.2004 (Core)

Linux version 4.18.0-193.6.3.el8_2.v1.4.x86_64 (builder@8.2.kbuilder.kernel.didi.com) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Fri Aug 12 15:54:33 CST 2022

ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

`pthread_cond_clockwait` symbol uses `GLIBC_2.30`
```
ubuntu@ubuntu:/data/ClickHouse/build/programs$ objdump -T clickhouse | grep GLIBC_2.30
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.30  pthread_cond_clockwait
```

Is there any good way to solve this problem?

**Comment by Algunenano** [comment]
Recommendations (by order):
* Use official builds. `curl https://clickhouse.com/ | sh` is your friend.
* Use the same build flags as the CI, which are the default. Same compiler too (clang 17)
* Do not change `GLIBC_COMPATIBILITY` nor `CMAKE_TOOLCHAIN_FILE`.

Other than that, since it's a custom build there is little we can do to help. You'll need to verify your changes / build
