### ISSUE TITLE
Problems with comparing Float type columns

### ISSUE THREAD

**Issue by giovanimarin** [ClickHouse/ClickHouse#58680]
I'm combine Grafana ad-hoc filter with clickhouse, and this way it's possible customize query, always with I select a fields and set a value filter, Grafana's plugin add a condition "AND <field> = <value>.
I have a fields type float32, and clickhouse default float value is float64, then, compare not work, only if a use toFloat32 function, but on this case, I can't use the function.
One possible solution is change my field to float64, but this will impact on storage, because I have billions of rows. Other option it could a possible parameter, that would change clickhouse default float value to float32, but I don't know if this parameter exists.

Tha fact is that I can't compare a simple decimal value with other.

Others test that I did with my field type float32:
"AND my_field = toFloat32(49.9)" - ok
"AND my_field = 49.9" - fail
"AND toFloat64(my_field) = toFloat64(49.9)" - fail
"AND toFloat64(my_field) = toFloat64(49.9)" - fail
"AND my_field = 49.900001525878906"  - ok
"AND toFloat64(my_field) = 49.9" - fail

The main problems is, why when I compare my field (float32) with 49.900001525878906 work?

**Comment by Algunenano** [comment]
This is basically the expected behaviour.

The parser reads `49.9` as a Float64 value by default (and it's not changeable via settings AFAIK), and Float32(49.9) is different from Float64(49.9). Float64 is a superset of Float32, i.e. all numbers that can be represented by Float32 can also be represented by Float64, but the opposite is not true.

The only odd thing here, which you didn't mention, is that comparing with a string does not work:

```
create table my_table (my_field Float32) ENGINE=Memory();
insert into my_table values ('49.9');
Select * from my_table where my_field = '49.9';
```

^ I would expect the above to work but we are promoting the type from Float32 to Float64 before parsing the string:

https://github.com/ClickHouse/ClickHouse/blob/2c8fd5dbb143729050d7f2b245c51991dced59db/src/Interpreters/convertFieldToType.cpp#L491-L502

@alexey-milovidov Do you remember which "overflows" where you trying to cover with this check?

Some thoughts:
* Maybe we should not promote for floating point, as in this case overflow isn't really possible (at least in the same sense as with integers).
* For integers maybe we should not promote at all either and ignore values outside of the range (so any comparison against them will be always false). It's still suboptimal though.
* Right now it is still possible to get invalid results if you really try. e.g. 2^64 is equal to UInt8(0): in `Select * from my_table where my_field::UInt8 = '18446744073709551616'` will return true for 0.

**Comment by Algunenano** [comment]
The comparison with a constant string is now changed in https://github.com/ClickHouse/ClickHouse/pull/58724, so doing `Select * from my_table where my_field = '49.9';` should work exactly for Float32 (no implicit cast to Float64 first).

**Comment by giovanimarin** [comment]
OK, but how to explain a field float32, that must be 4 bytes and 7 decimal numbers after the dot, when campare with "49.900001525878906" return true?

This is a expected behavior too?

**Comment by Algunenano** [comment]
Because `49.9` and `49.900001525878906` represent the same number:

```
SELECT
    hex(toFloat32('49.9')),
    hex(toFloat32('49.900001525878906'))

Query id: 5baeac29-2a96-418c-8bd8-8053e6e5b5d8

Row 1:
──────
hex(toFloat32('49.9')):               9A994742
hex(toFloat32('49.900001525878906')): 9A994742

1 row in set. Elapsed: 0.000 sec.
```

A Float32 number covers has many (infinite) decimal representations, we just choose one to show it:

```
Select reinterpret(unhex('9A994742'), 'Float32');

SELECT reinterpret(unhex('9A994742'), 'Float32')

Query id: bd83af16-e243-4f32-b938-824b041ab116

┌─reinterpret(unhex('9A994742'), 'Float32')─┐
│                                      49.9 │
└───────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 
```

Decimal numbers are meaningless when talking about floating point numbers.

**Comment by alexey-milovidov** [comment]
Reference: https://float.exposed/ from @Ciechan
