### ISSUE TITLE
Keep compatible with ZooKeeper `MultiRead`

### ISSUE THREAD

**Issue by lzydmxy** [ClickHouse/ClickHouse#58747]
ClickHouse Keeper differs slightly from ZooKeeper in its implementation of `MultiRead` request.

Specifically, the difference lies in the error sub-responses related to MultiRead.For example, in MultiRead, we attempt to get a non-existent node.

Zookeeper MultiRead Response
```
MultiHeader(type=-1, done=False, err=-101) -101
```
type = -1 means it's an error reponse

ClickHouse Keeper  MultiRead Response
```
MultiHeader(type=4, done=False, err=-101)
```

Can we keep compatible with ZooKeeper `MultiRead`? With https://github.com/ClickHouse/ClickHouse/pull/50796, I want to use `MultiRead` for ZooKeeper.

**Comment by antonio2368** [comment]
We decided to slightly change how MultiRead works because it made more sense when integrating with CH.
Read request don't do any changes (i.e. subrequests in MultiRead don't affect each other) which means that aborting MultiRead on first invalid node would mean extra MultiRead requests for other nodes.
Problem now is that CH's logic relies heavily on our version of MultiRead so it will be hard and complex to support both types.
