### ISSUE TITLE
new analyzer multiple join using, unconsistent left most table column names

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#59317]
**How to reproduce**
```
create table t1(a int, b int) ENGINE=Memory;

SET allow_experimental_analyzer=1;

DESCRIBE TABLE
(
    SELECT *
    FROM t1
    LEFT JOIN t1 AS a USING (a)
    LEFT JOIN t1 AS b USING (a)
)
┌─name────────┬─type──┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ a           │ Int32 │              │                    │         │                  │                │
│ _local.t1.b │ Int32 │              │                    │         │                  │                │
│ a.b         │ Int32 │              │                    │         │                  │                │
│ b.b         │ Int32 │              │                    │         │                  │                │
└─────────────┴───────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```

**Comment by yakov-olkhovskiy** [comment]
This is expected behavior - ref #65267
The condition for name qualification is a detected names collision. Left table unqualified names only enabled for single join (unclear historical reasons - see https://github.com/ClickHouse/ClickHouse/issues/22627#issuecomment-2209287823) with setting `single_join_prefer_left_table=1`:
```
SET allow_experimental_analyzer=1;
create table t1(a int, b int) ENGINE=Memory;

SET single_join_prefer_left_table=1;

DESCRIBE TABLE
(
    SELECT *
    FROM t1
    LEFT JOIN t1 AS x USING (a)
);

a	Int32					
b	Int32					
x.b	Int32					

SET single_join_prefer_left_table=0;

DESCRIBE TABLE
(
    SELECT *
    FROM t1
    LEFT JOIN t1 AS x USING (a)
);

a	Int32					
default.t1.b	Int32					
x.b	Int32					
```
- for multiple joins left table unqualified names "privilege" does not apply:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Analyzer/Resolve/QueryAnalyzer.cpp#L4467-L4469

we had some discussion on this with @vdimir and @KochetovNicolai and decided to left it as is for now. Please feel free to raise this issue again if you think it is reasonable to somehow change this behavior.

**Comment by UnamedRus** [comment]
It's incorrect (or at least different) behavior AFAIK.
https://www.db-fiddle.com/f/gpbWnZhczwxYgkExV6QG76/0
https://www.db-fiddle.com/f/w6TKAGR7XVk5yxXAPa6LAZ/0


I do think that all "inconsistencies" should be kept open, especially about names after joins
