### ISSUE TITLE
Question on S3 Bucket in Cluster Mode

### ISSUE THREAD

**Issue by sevenaces88** [ClickHouse/ClickHouse#59820]
Hi All,

I have a cluster with 4 nodes. I have configured 2 cluster one with 4 shards and 1 replica, the other with 2 shards and 2 replica. I have configured it to use only a single S3 bucket for ALL the nodes.

Questions:
1. Can i know whether it's the correct setup? Or do each nodes requires it's own S3 bucket?
2. If each nodes requires it's own S3 bucket, what is the implication if all nodes are using the same one single bucket for storage?

Thanks.

Clickhouse version: v24.1.2.5

**Comment by alexey-milovidov** [comment]
Yes, this setup is correct. Different shards and clusters will use different files in a bucket.

Using a shared bucket has some advantages:
- the underlying storage of the S3 bucket is incrementally scaled and partitioned depending on the load, and having a single large bucket will have better performance;
- you don't face a limit on the maximum number of S3 buckets per account;
- you have a simpler configuration.

If you put different data in the same path, it will be difficult to delete the data related to a single cluster, and it will be impossible to configure different access rules. That's why I recommend putting the data for different clusters into different prefixes.

In most cases, I recommend using a shared bucket.

But there are rare scenarios when you can prefer multiple buckets:
- the logical separation to different buckets looks cleaner;
- it's easier to specify intelligent tiering separately for different clusters;
- it's easier to account costs or to manage the buckets as an isolated entity;
