### ISSUE TITLE
Arrays of LowCardinality are not optimized for function calculations

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#6005]
Arrays of LowCardinality Strings do not use LowCardinality optimisations for string operations.

```
create table test_lc_array (
 s LowCardinality(String),
 a Array(LowCardinality(String)) default array(s)
) Engine = MergeTree 
PARTITION BY tuple()
ORDER BY tuple()
;

insert into test_lc_array (s)
select concat('qwertyuiopasdfghjkl', toString(number%10))
from numbers(100000000)
;  

select count() from test_lc_array where s = 'qwertyuiopasdfghjkl0';

1 rows in set. Elapsed: 0.200 sec. Processed 100.00 million rows, 100.46 MB (501.07 million rows/s., 503.36 MB/s.) 
<Debug> MemoryTracker: Peak memory usage (for query): 2.04 MiB.

select count() from test_lc_array where a[1] = 'qwertyuiopasdfghjkl0';

1 rows in set. Elapsed: 2.033 sec. Processed 100.00 million rows, 900.46 MB (49.19 million rows/s., 442.93 MB/s.) 
<Debug> MemoryTracker: Peak memory usage (for query): 16.74 MiB.

select count() from test_lc_array where has(a, 'qwertyuiopasdfghjkl0');

1 rows in set. Elapsed: 1.136 sec. Processed 100.00 million rows, 900.46 MB (88.06 million rows/s., 792.97 MB/s.) 
 <Debug> MemoryTracker: Peak memory usage (for query): 10.99 MiB.

select count() from test_lc_array where indexOf(a, 'qwertyuiopasdfghjkl0')>0;

1 rows in set. Elapsed: 1.211 sec. Processed 100.00 million rows, 900.46 MB (82.60 million rows/s., 743.81 MB/s.) 
<Debug> MemoryTracker: Peak memory usage (for query): 12.74 MiB.
```

**Comment by richardartoul** [comment]
@alex-zaitsev Do you have a moment to shed some light on how Array(LowCardinality(String)) columns work? My understanding (please correct me if I'm wrong) is that the storage engines in clickhouse can basically do whatever they want but when a query is executed they're responsible for generative "native format" blocks for the query execution engine to operate on.

My understanding of the Array() column native format is that its basically $NUM_ROWS uint64 offsets where each offset defines the beginning of an individual array, and then each array is an integer describing the number of elements in the array, and then the array itself is just encoded using the standard native format encoding of a non-nullable column for that type (so Array(uint64) the array itself would just be $ARRAY_LENGTH 8 byte uint64s)

That implies to me that implementing Array(LowCardinality(String)) would be difficult because the format would imply a dictionary per array where what you'd really want is a dictionary per Array column. Is that whats going on here? My understanding was that Array(LowCardinality(string)) definitely saves disk space so I'm curious about the interaction between the storage engine, the native format, and the query execution engine here.

**Comment by richardartoul** [comment]
I guess the `LowCardinality` native format does have flags for re-using the same dictionary as the previous block, so I guess that could be used where the first array element has the dictionary and all subsequent arrays just set the flag to keep reusing the previous dictionary?

**Comment by alexey-milovidov** [comment]
@richardartoul 

> My understanding (please correct me if I'm wrong) is that the storage engines in clickhouse can basically do whatever they want but when a query is executed they're responsible for generating "native format" blocks for the query execution engine to operate on.

True.

> My understanding of the Array() column native format is that its basically $NUM_ROWS uint64 offsets where each offset defines the beginning of an individual array, and then each array is an integer describing the number of elements in the array, and then the array itself is just encoded using the standard native format encoding of a non-nullable column for that type (so Array(uint64) the array itself would just be $ARRAY_LENGTH 8 byte uint64s)

Almost correct. The values may be represented by any column, including Nullable and LowCardinality... and LowCardinality(Nullable(...)) as well.

> That implies to me that implementing Array(LowCardinality(String)) would be difficult because the format would imply a dictionary per array

But `Array(LowCardinality(String))` already works. It doesn't use dictionary per array. Dictionaries are used for column with array values and in this column, array bounds are not accounted (there are accounted in offsets column) - all elements of all arrays are simply placed one to each other in a single column in memory.

What this task is about is to optimize functions calculation for `Array(LowCardinality(...))`. Currently, LowCardinality is converted to full column first and then function is calculated. The goal is to calculate function once per each dictionary value - it's what is already done for LowCardinality without Array.
