### ISSUE TITLE
How to update or delete data via Distributed Table Engine

### ISSUE THREAD

**Issue by DaleAuto** [ClickHouse/ClickHouse#60265]
The clichouse docs only introduces how to use Distributed Table Engine writing or reading data.  [https://clickhouse.com/docs/en/engines/table-engines/special/distributed](url)

For example:

I hava a Distributed Table named **table_distribute**, which point to two tables **table_local_1** and **table_local_2**

I got an error 'Table engine Distributed doesn't support mutations' when updating data via Distributed Table Engine.

Updating each table that the Distributed table is pointing to is the only way to update data?

Or any other suggestions?

**Comment by pufit** [comment]
You can't alter distributed tables because `Distributed` doesn't store data or know anything about the underlying tables. The tables can have different table engines, so we can't guarantee to execute `ALTER` for all of them.

Please also check these two articles, they can be useful
https://clickhouse.com/docs/en/optimize/avoid-mutations
https://clickhouse.com/blog/handling-updates-and-deletes-in-clickhouse#deleting-and-updating-using-collapsingmergetree

**Comment by DaleAuto** [comment]
[https://clickhouse.com/blog/handling-updates-and-deletes-in-clickhouse#deleting-and-updating-using-collapsingmergetree](url)
It is useful for me. Thanks a lot
