### ISSUE TITLE
color, render functions (wrap value in ansi encoded color codes)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#60684]
**Use case**

Add some colors to clickhouse-client output. 

**Describe alternatives you've considered**

Manually append ansii color codes to values 

```
SELECT '\x1b[42mTEEST\x1b[0m' as a;
```
![image](https://github.com/ClickHouse/ClickHouse/assets/9449405/28dd32b2-e98b-4b3e-be31-c4fde6480652)

**Additional context**

https://starburstdata.github.io/latest/functions/color.html
https://talyian.github.io/ansicolors/

**Comment by anupgithb** [comment]
Hey! If this isn't already being worked on, can you please assign it to me? I'd like to work on it! @UnamedRus  @alexey-milovidov

**Comment by alexey-milovidov** [comment]
This task is slightly non-trivial; we need to collect proposals first.

We shouldn't do it like Starburst.
Their `bar` function is directly influenced by ClickHouse, but their approach to colors is error-prone.

For example, the functions are named `color`, not `terminalColor`, `ANSIColor`, etc. - which will lead to confusion. For example, if you use these functions in a GUI or Web UI instead of TUI, you could expect some reasonable results, but you won't get it. The fact that the function is named just, simply, `color`, makes vibes from the BASIC programming language.

Their return value and specification of colors is a string - that can be similar to CSS, but the problem - it is unstructured data, which has to be parsed and formatted. And it does not correspond to modern CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color

It is underspecified how the colors interpolate, and what is the color space.

It does not provide ways to render gradients with custom palettes, which is needed for accessibility (to support color blindness).

**Comment by alexey-milovidov** [comment]
You forgot to reference our examples:

https://twitter.com/tbragin/status/1749580473800556779
https://twitter.com/ClickHouseDB/status/1759063640299196479
