### ISSUE TITLE
coalesce(NaN, 0) returns null

### ISSUE THREAD

**Issue by poweroftrue** [ClickHouse/ClickHouse#61412]
**Describe what's wrong**

Coalesce returns null where it should return NaN or zero 

> A clear and concise description of what works not as it is supposed to.

Here's a simplified query of what I was running:
```sql
select coalesce(countIf(false)/countIf(false), 0)
```  
This should in theory returns NaN (0/0) or at least 0 but it returns null

**Does it reproduce on the most recent release?**

It does locally running on Docker

**Comment by alexey-milovidov** [comment]
Does not reproduce: https://fiddle.clickhouse.com/0eb2f366-73d0-4ece-aa4f-06fb12992fb6

**Comment by alexey-milovidov** [comment]
Take the following considerations:

1. The JSON data format, see https://www.json.org/ does not support NaNs or other denormal numbers, that's why if you choose to output your data in JSON, they denormal numbers will be converted to JSON's `null` for standard conformance. You can also prefer to wrap denormal numbers as strings by enabling the `output_format_json_quote_denormals` setting.

**Comment by poweroftrue** [comment]
Thanks @alexey-milovidov 

It turned out the local web UI uses json 
<img width="1402" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/10044038/f81a821c-65be-4071-9bb7-0a4256e08f28">
