### ISSUE TITLE
4 clickhouse servers in cluster. How many house-keeper need to enabled? can be 4 nodes? any suggestion?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#61510]
4 clickhouse servers in cluster. How many house-keepers need to enabled? can be 4 nodes? any suggestion? Thanks

**Comment by davenger** [comment]
The recommended Keeper setup is 3 nodes.
Note that 4 or any other even number of nodes doesn't make much sense because Keeper implements consensus protocol where it needs confirmation from more than half of nodes. For 3 nodes the quorum is 2, for 4 nodes the quorum is 3 and for 5 nodes the quorum is also 3.
