### ISSUE TITLE
Name collision if there are tables with the same name in different databases

### ISSUE THREAD

**Issue by askmyhat** [ClickHouse/ClickHouse#61947]
**Describe what's wrong**

Wrong table is selected when using * and there are tables with the same name in different databases
https://fiddle.clickhouse.com/6cb63667-b633-4016-844d-032db5af375b

**Comment by den-crane** [comment]
It's fixed in the new analyzer. 

https://fiddle.clickhouse.com/7fd96e7d-cf3c-4f1f-bd49-0d44cc340f5f
https://fiddle.clickhouse.com/11af3409-3614-4a11-b4d7-5ac058bce9a1
https://fiddle.clickhouse.com/8e3108dc-753e-4248-b6c6-ce45b2bd8ccb

The new analyzer was enabled by default today, with the latest version 24.3.1.2672.
The old analyzer will be dropped during the next 2 releases (months). https://youtu.be/FGhdXXXTuTg 

It's unlikely that this issue will be fixed with the old analyzer (the issue exists for 6 years).
