### ISSUE TITLE
Improve OvercommitTracker by Linux memory management ideas

### ISSUE THREAD

**Issue by tomershafir** [ClickHouse/ClickHouse#62058]
Follow up on https://github.com/ClickHouse/ClickHouse/issues/58004.

I wonder wdyt on trying to pull some Linux OOMKIller ideas, as theoretically you solve similar problems, for example:

- Use Linux PSI to trigger kill, rather than experience degraded performance, like oomd does.
- Postpone kill if things should get better soon, by stats.
- Try improve victim selection score calc.
- More flexible user config.
- Pin killer code to avoid crash.

I dont know your problem distribution, I would guess none, then the above is less relevant :)
I can elaborate if it makes sense

**Comment by nikitamikhaylov** [comment]
Thanks for ideas, but I don't think complicating this component even further would make sense. When it comes to the memory pressure the best strategy is to get rid of this state as soon as possible, because memory is such a resource which couldn't be throttled easily. 

On your ideas above: 
> - Postpone kill if things should get better soon, by stats.
> - Pin killer code to avoid crash.

It is already so and controlled by a setting `memory_usage_overcommit_max_wait_microseconds`. 

> - Try improve victim selection score calc.
> - More flexible user config.

Please take a look at settings `memory_overcommit_ratio_denominator` and `memory_overcommit_ratio_denominator_for_user`.
