### ISSUE TITLE
JOIN on BETWEEN or a range?

### ISSUE THREAD

**Issue by BruceWangs** [ClickHouse/ClickHouse#62211]
SELECT
            s.*,
            n.id AS network_id
        FROM
            source AS s
                LEFT JOIN
            flatten_network AS n ON IPv4StringToNum(s.ip) BETWEEN n.ip_start_num AND n.ip_end_num。 

error: Unsupported JOIN ON conditions. Unexpected 'IPv4StringToNum(ip) >= ip_start_num': While processing IPv4StringToNum(ip) >= ip_start_num.

**Comment by hanfei1991** [comment]
`ON` conditions should contain `=` operator, otherwise you should use `CROSS JOIN`.
https://clickhouse.com/docs/en/sql-reference/statements/select/join#on-section-conditions

**Comment by vdimir** [comment]
For such a use case, you may also consider the [ip_trie](https://clickhouse.com/docs/en/sql-reference/dictionaries#ip_trie) dictionary (also you may check [this article](https://medium.com/@chayut_o/clickhouse-ip-trie-structured-dictionary-to-perform-ip-based-lookup-for-geoip-location-and-asn-228527dfd0b0)). It allows matching IP addresses against a set of masks with associated attributes. The drawback is that it requires a different syntax (`dictGet` instead of `JOIN`) and supports only masks, not arbitrary ranges. But probably, it fits your use case.
