### ISSUE TITLE
TOO_MANY_PARTS error when `WHERE _part = <one partition>` is used

### ISSUE THREAD

**Issue by khan-t** [ClickHouse/ClickHouse#62324]
**Describe the unexpected behaviour**
I have two identical table (`abc` and `abc_s3`) of different `storage_policy`. I want to move partition between the table of different `storage_policy` but I'm unable. So I resort to use `INSERT`. But I'm getting `too many partition in a single insertion` error, even though `WHERE _part = '2024-01-01'` is used.

**How to reproduce**
* Which ClickHouse server version to use
`23.10.1.1976`

* Which interface to use, if matters
Dbeaver and Clickhouse-client

* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE dev.abc
(
    `snapshotDate` Date,
    `number` UInt32 CODEC(ZSTD(9))
)
ENGINE = MergeTree
PARTITION BY snapshotDate
ORDER BY snapshotDate;
```
```
CREATE TABLE dev.abc_s3
(
    `snapshotDate` Date,
    `number` UInt32 CODEC(ZSTD(9))
)
ENGINE = MergeTree
PARTITION BY snapshotDate
ORDER BY snapshotDate
SETTINGS storage_policy = 's3';
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

* Queries to run that lead to unexpected result
`INSERT INTO dev.abc_s3 SELECT _part, * FROM dev.abc WHERE _part = '20200315_140_140_0'`

**Expected behavior**
Insertion of just one partition to work just fine.

**Error message and/or stacktrace**
`Code: 252. DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by 'max_partitions_per_insert_block' setting. ...`

**Additional context**
I already have many other `_part` inserted. But one part is not working, and I foresee other partition might have the same error in the future.

**Comment by den-crane** [comment]
This is expected behaviour. Such insert creates many parts even if you query only one partition or even a single part (` _part = '20200315_140_140_0'`). Insert separates input data by a million rows (max_insert_block_size) or by size 256MB (min_insert_block_size_bytes). It is necessary because the sorting the data during the a part forming requires a lot of memory.

see example https://kb.altinity.com/altinity-kb-queries-and-syntax/atomic-insert/

-----

You can add the same local disk of `abc` to the storage policy of the second table `storage_policy = 's3'`, then use `attach partition from` and then `alter move` to move to another disk. https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-s3-object-storage/s3_cache_example/

-----

Another even easier option: you can just use one table and move data to s3 using TTL rules or using `alter table ... move`.

**Comment by khan-t** [comment]
Great info and suggestion. What should I do if I want to clone the data from one table to another?

**Comment by den-crane** [comment]
alter table attach partition from https://clickhouse.com/docs/en/sql-reference/statements/alter/partition#attach-partition-from
