### ISSUE TITLE
Is attach from table with different storage policy allowed on 24.3?

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#62764]
https://fiddle.clickhouse.com/bced1271-9198-4257-8acf-b50e87eb9d00

I thought that the feature 'allow attach from different disks' was reverted on 24.3 by this https://github.com/ClickHouse/ClickHouse/pull/62572.

**Comment by Algunenano** [comment]
It's still available in `24.3` because there hasn't been any new release with the revert. It won't be possible in the next minor version (or the next major version unless it's reintroduced properly).

It causes crashes and has some bugs, so although it's currently possible to use it in some versions of 24.3 I'd recommend not to use it.
