### ISSUE TITLE
inverted  how to accelerate 

### ISSUE THREAD

**Issue by dongjicheng** [ClickHouse/ClickHouse#62862]
1.when apply an inverted index, how to accelerate function count()/hasToken()(when inverted(1))  without unzip hit Granules.
2.when i use myself tokenizer split text by space, then index it by inverted(1)，i find count() very slowly when use hastToken.
```[tasklist]
### Tasks
```

**Comment by kssenii** [comment]
@rschu1ze could you please take a look?

**Comment by rschu1ze** [comment]
I don't understand the first question, @dongjicheng could you please re-phrase it? What you probably mean is that the inverted index stores row numbers instead of granule numbers. That's intended and useful for intersection (AND queries). Please provide evidence that " unzip hits Granules".

About the second question, please provide a minimal reproducible example (dataset, query), otherwise it is too difficult to argue about "very slowly".

**Comment by alexey-milovidov** [comment]
Inverted indices are not supported by ClickHouse.
