### ISSUE TITLE
Why I am not able to access system.numbers as user with no privileges from 24.4?

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#63347]
```sql
create user user1
```

user1:
```sql
 select * from system.numbers limit 10
```
```
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: user1: Not enough privileges. To execute this query, it's necessary to have the grant SELECT(number) ON system.numbers. (ACCESS_DENIED)
```
But I can select from `numbers()` and `system.one`.

And I no longer have access to system.build_options, system.parts and system.processes with user1 from 24.4.

**Comment by den-crane** [comment]
24.4 ? It started with 24.1

It's expected behaviour.
The majority of system tables are not available by default anymore.
The tables related to database schema is available: system.tables, system.columns, ...

`numbers()` -- is not a table, it's a table function.
`system.one` -- is a special table, AFAIK it's needed for `select *` (select without from section).


You can do something like `grant select on system.* to user1;`
Or change settings back https://github.com/ClickHouse/ClickHouse/pull/58584/files

https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#-clickhouse-release-241-2024-01-30

Enable various changes to improve the access control in the configuration file. These changes affect the behavior, and you check the config.xml in the access_control_improvements section. In case you are not confident, keep the values in the configuration file as they were in the previous version. https://github.com/ClickHouse/ClickHouse/pull/58584 ([Alexey Milovidov](https://github.com/alexey-milovidov)).

**Comment by alsugiliazova** [comment]
I compared with 24.3 and saw these difference. I was curious because didn’t see anything related in 24.4 changelog. Just wanted to clarify for myself, thanks.

**Comment by den-crane** [comment]
I definitely see that this behaviour started with 24.1

```
24.2.3.70

create user user1 identified by 'x';

clickhouse-client -u user1 --password x

select * from system.numbers;

Received exception from server (version 24.2.3):
Code: 497. DB::Exception: Received from localhost:9000.
DB::Exception: user1: Not enough privileges. To execute this query, it's necessary to have the grant 
SELECT(number) ON system.numbers. (ACCESS_DENIED)
