### ISSUE TITLE
Not executed automatic deduplication

### ISSUE THREAD

**Issue by Nikowl** [ClickHouse/ClickHouse#64147]
If you do it manually, then everything is ok. But automatic deduplication does not occur even after a week
```sql
OPTIMIZE TABLE order_txt FINAL DEDUPLICATE;
```
```
CREATE TABLE order_txt
(
    `partner_id`                      UUID,
    `order_id`                        UInt32,
    `data`                            String
)
ENGINE = ReplacingMergeTree
PRIMARY KEY (partner_id, order_id)
ORDER BY (partner_id, order_id);
```

**Comment by den-crane** [comment]
Merges are eventual and may never happen. It depends on the number of inserts that happened after, the number of parts in the partition, size of parts. If the total size of input parts are greater than the maximum part size then they will never be merged.

https://clickhouse.tech/docs/en/operations/settings/merge-tree-settings/#max-bytes-to-merge-at-max-space-in-pool

https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replacingmergetree/ ReplacingMergeTree is suitable for clearing out duplicate data in the background in order to save space, but it doesn’t guarantee the absence of duplicates.
