### ISSUE TITLE
Questions about the difference between the DELETE statement and TTL? 

### ISSUE THREAD

**Issue by Maplestory1998** [ClickHouse/ClickHouse#64450]
After reading docs about TTL and lightweight DELETE, There are some questions about their performance diff。

In my occasaion,the following is the create statement
```sql
CREATE TABLE my_table
(
    id UInt32,
    timestamp Int64
    ORDER BY (`timestamp`, `id`) 
) 
ENGINE = MergeTree()
PARTITION BY toStartOfWeek(toDateTime(`timestamp` / 1000))
ORDER BY (timestamp, id)
SETTINGS index_granularity = 8192;
```
Q1:
Insteading of adding TTL for the `timestamp` column, If the statement "DELETE FROM my_table where timestamp < now() - INTERVAL 1 DAY“ is execed periodically, would performance be significantly worse?

Q2:
As the above statements, timestamp is the partitioning key. If there are multi partitions, could I assume that based on the timestamp in the where condition the clickhouse can quickly determine which partitions will not be hit, so that the delete statement will have no effect on those partitions?

**Comment by den-crane** [comment]
TTL can drop whole partitions if a partitioning expression is aligned with a TTL expression of if ttl_only_drop_parts is set.

A1: with LWD your data may never be removed at all. Because Clickhouse does not force the real deletion of rows marked as deleted by LWD. It delete data during usual merge which may never happen for the old parts.

A2: LWD mutates all parts (recreates parts using hardlinks), but reads (and writes is_deleted=1 column) only parts which match a condition and it uses minmax index derived from a partition expression. Mutation of all parts is mandatory by another reasons.

I would use TTL if possible and aligned TTL expression with PartitionBy expression and adjust PartitionBy if possible.
