### ISSUE TITLE
 vulnerabilities of the zlib component

### ISSUE THREAD

**Issue by mazhaonan** [ClickHouse/ClickHouse#64490]
Is it possible to upgrade the current version of the zlib component to 1.3.1 or higher, as there are vulnerabilities in the existing version of the zlib component?

**Comment by mazhaonan** [comment]
The zlib component version currently used by clickhouse is 1.0.7, but there is an input validation error vulnerability in zlib1.3 and earlier versions, which is caused by integer overflow and heap based buffer overflow

**Comment by duhy-max** [comment]
I'm concerned about that, too

**Comment by duhy-max** [comment]
and i find this : https://github.com/ClickHouse/ClickHouse/issues/12709

**Comment by mazhaonan** [comment]
> I'm concerned about that, too

I am just a Java project manager and I really don't want to compile the source code for clickhouse on my own. However, I cannot refuse the client's request, so I was wondering if the community experts could help me solve it

**Comment by duhy-max** [comment]
I am looking at the latest lts version code v24.3.3.102-lts, which does not use the zlib library, it already uses Zlib-ng and is the internal module of clickhouse

> > I'm concerned about that, too
> 
> I am just a Java project manager and I really don't want to compile the source code for clickhouse on my own. However, I cannot refuse the client's request, so I was wondering if the community experts could help me solve it

**Comment by Algunenano** [comment]
> The zlib component version currently used by clickhouse is 1.0.7

Where? How did you get this? I can't find this library anywhere, but maybe I missed something. As mentioned by @duhy-max CH does not use `zlib` and it uses `zlib-ng`, so it's not necessarily affected by zlib vulnerabilities.

If you are worried about a particular CVE, it's better to share that exact CVE.

Another thing to keep in mind is that just because the code is present in CH repo / submodules, it does not mean it's actually used, so it needs to be verified case per case to see the possible affectation. Obviously upgrading to non-vulnerable releases is still preferred.
