### ISSUE TITLE
Stream Parser for Alter Query

### ISSUE THREAD

**Issue by Sundarcj** [ClickHouse/ClickHouse#6534]
Hi Team,
 I am having a use case to update a large amount of data. like column transformation (case transformation ie. upper case, lowercase, title case). for that, I need to apply to alter query for the entire table which has billions of rows and I'm using merge tree engine with a single node (not distributed). so it took almost 2 hours for an update.
So, is there any other better way to do it?

Second Usecase:
    It is Many to One Update scenario. I have a column called row_state which have 3 possible values 
    0-> normal
     1 -> row is hidden
     2-> row is deleted
I need to update this row_state for a set of random Rows.for that also I used Alter query with `row_id IN ( 1,2,3,..etc`. unfortunately, I need to update for a large number of rows.which can't be executed by single query so I split it by some chunk of rows and suddenly CH crashed.
can anyone help me!!

**Comment by 4ertus2** [comment]
> So, is there any other better way to do it?
For one-to-one updates you may try to use ALIASES with expressions: https://clickhouse.yandex/docs/en/query_language/create/#create-default-values
Then you are able to select from this virtual column instead of source one.

> Second Usecase
It's something very special. It's not a good idea to update source data this way in analitical systems. Instead you may have filter ALIAS columns with hidden or delete rules and add them in WHERE clause. Or a filter table that could be JOINed to source one to filter data (if there's not much unnormal rows).

**Comment by Sundarcj** [comment]
For first use case, the thing is in my table user can  transform any column

**Comment by 4ertus2** [comment]
The general OLAP solution is to have big fact table that is immutable and small tables that could be joined to it. It also called as star schema. Then you are able to change joined tables as needed. If you have lots of mutations on the fact table or very big dimensions it's something strange and you need some special solution.

**Comment by filimonov** [comment]
First use case is not clear. You want to allow user to modify data stored in table in any way? Howwould you imagine that? I.e. you have (let's say) column with 500Gb of string. And you want to allow user to rewrite that 500Gb of strings? What are better options than just read-process-write back?  

There are several workarounds for second use case - including dictionaries, joins, or Replacing / Collapsing engines.

**Comment by blinkov** [comment]
@Sundarcj, do you have any further questions?

**Comment by alexey-milovidov** [comment]
> I need to update this row_state for a set of random Rows.for that also I used Alter query with row_id IN ( 1,2,3,..etc. unfortunately, I need to update for a large number of rows.which can't be executed by single query so I split it by some chunk of rows and suddenly CH crashed.
can anyone help me!!

The proper solution is to write these ids to another table; distribute this table across all replicas and use ALTER ... WHERE `row_id IN (SELECT id FROM that_table)`. This is slightly unusual but it works.

Explicit list of values for ALTER query won't work because the full expression is written to ZooKeeper log and it has the limit of 1 MiB of node value by default. It means that expressions in ALTER are assumed to be small.

PS. 
> I split it by some chunk of rows and suddenly CH crashed.

ClickHouse should never crash :) If you can still reproduce the issue on recent releases, please file a bug report in separate issue.
