### ISSUE TITLE
ClickHouse on low memory machine

### ISSUE THREAD

**Issue by stevelukis** [ClickHouse/ClickHouse#65476]
### Question

We have a ClickHouse server (version 24.4.1.2088) running inside a Docker container alongside a Django web server on an 8GB machine.

The max_server_memory_usage_to_ram_ratio is set to 0.4.

We notice that the memory usage of ClickHouse grows over time, and then we get a lot of `Exception: Memory limit (total) exceeded...` around 3GB memory usage. The memory usage is reset to baseline after the server is restarted.

![image](https://github.com/ClickHouse/ClickHouse/assets/20234730/092a2bed-30f7-4e90-93ad-205bcfb87df8)

The thing is that we don't have any SELECT queries running yet; we just do async inserts for now. There are around 4 inserts per second.

We have two tables with 45 million and 12 million rows.

It was written here that: "If your system has less than 16 GB of RAM, you may experience various memory exceptions because default settings do not match this amount of memory. The recommended amount of RAM is 32 GB or more. You can use ClickHouse in a system with a small amount of RAM, even with 2 GB of RAM, but it requires additional tuning and can ingest at a low rate."

Given our current setup and data size, what would be a good configuration for a low memory machine? If an upgrade is needed, how much memory would be required to handle our current data size?

**Comment by den-crane** [comment]
>The max_server_memory_usage_to_ram_ratio is set to 0.4.

Why ? 

8GB * 0.4 = 3.2 GB -- you allowed Clickhouse to use only 3.2GB. Mark cache size by default is 5GB.

>Given our current setup and data size, what would be a good configuration for a low memory machine? If an upgrade is needed, how much memory would be required to handle our current data size?

It makes no sense since you don't allow clickhouse to use 60% of RAM.

**Comment by stevelukis** [comment]
@den-crane Because we want to leave enough memory for our web server.

If we were to move our ClickHouse server to a separate machine and restore max_server_memory_usage_to_ram_ratio to default , how many memory will be enough for our data size?

**Comment by den-crane** [comment]
> how many memory will be enough for our data size?

Maybe 8G maybe 128G. You should test.

**Comment by alexey-milovidov** [comment]
Lower the size of the mark cache in the config.xml. It can be set as low as 500 MB, but it cannot be set to zero.

Lower the number of query processing threads down to 1.
Lower the max_block_size to 8192. Values as low as 1024 can still be practical.

To flush the memory that is cached by the memory allocator, you can run the
```
SYSTEM JEMALLOC PURGE
```
command.

**Comment by chfritz** [comment]
I've followed the instructions from https://clickhouse.com/docs/operations/tips#using-less-than-16gb-of-ram (which match what Alexey said above), running 25.7 in a docker container with a 4GB memory limit. But I'm still getting these errors even without ingesting any data (or running queries):

`
2025.08.14 00:04:44.404122 [ 670 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {a1b473a7-40a8-4ed9-9d61-365c8e87d292::202508_1_4905_250}: Code: 241. DB::Exception: (total) memory limit exceeded: would use 3.60 GiB (attempt to allocate chunk of 4.16 MiB bytes), current RSS: 859.29 MiB, maximum: 3.60 GiB. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):
`

The error is a bit funny. It says it has allocated 859.29 MiB so far and would like to allocate a new chunk of 4.16 MiB, but can't because that would put it over the limit of 3.6 GiB? That doesn't add up. Am I doing something wrong?

The instructions do say that (emphasis mine):
> You can use ClickHouse in a system with a small amount of RAM (as low as 2 GB), but **these setups require additional tuning** and can only ingest at a low rate.

Are these additional tuning steps documented, too, somewhere?

For completeness, here are the config files I've used:

`/etc/clickhouse-server/config.d/myfile.xml`:
```xml
<?xml version="1.0"?>
<clickhouse>
  <mark_cache_size>524288000</mark_cache_size>
</clickhouse>
```

`/etc/clickhouse-server/users.d/myfile.xml`:
```xml
<?xml version="1.0"?>
<clickhouse>
  <profiles>
    <default>
      <max_block_size>1024</max_block_size>  <!-- also tried 8192 -->
      <max_download_threads>1</max_download_threads>
      <input_format_parallel_parsing>0</input_format_parallel_parsing>
      <output_format_parallel_formatting>0</output_format_parallel_formatting>
    </default>
  </profiles>
</clickhouse>
```

And I've used `clickhouse-client -q "select * from system.settings" | grep max_block_size` (and similar) to check that the settings were applied.

**Comment by daffaalex22** [comment]
Did anyone managed to do this without error? @chfritz @stevelukis

**Comment by chfritz** [comment]
> Did anyone managed to do this without error?

To a degree. Since I was running on a host that did have more than 4 GB of RAM, I just increased the Docker memory limit of the container to 8 GB. The container now works (without error) and, as suggested by the seeming math mistake in the error message, *doesn't* ever seem to use more than 1GB of RAM.

**Comment by vitaliyf** [comment]
@daffaalex22 check if perhaps https://github.com/ClickHouse/ClickHouse/issues/75590 is relevant

**Comment by daffaalex22** [comment]
> > Did anyone managed to do this without error?
> 
> To a degree. Since I was running on a host that did have more than 4 GB of RAM, I just increased the Docker memory limit of the container to 8 GB. The container now works (without error) and, as suggested by the seeming math mistake in the error message, _doesn't_ ever seem to use more than 1GB of RAM.

@chfritz With that 8GB setup, can you share how much query/inserts throughput are you using?

**Comment by chfritz** [comment]
> With that 8GB setup, can you share how much query/inserts throughput are you using?

@daffaalex22 I haven't done any load testing yet. My first goal was merely for it to not crash, even when idle (which it did when the container was only granted 4 GB). We might be starting to put load on it in the next few weeks though and I can report back then.

**Comment by daffaalex22** [comment]
Cool, would be helpful for me & others if you can share! @chfritz
