### ISSUE TITLE
I need an unexpected set of privileges when inserting into the first source table in cascading materialized view 

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#65651]
### Question

Version 24.5.3.5

https://fiddle.clickhouse.com/acd5fcf2-d867-4baf-a3b1-cd6af6501fd2

```sql
create table source (x Int16) engine MergeTree order by x;

create table target1 (x Int16) engine MergeTree order by x;

create user definer1;

create materialized view mv1 to target1 definer=definer1 sql security DEFINER as select x from source;

create table target2 (x Int16) engine MergeTree order by x;

create materialized view mv2 to target2 as select x from target1;

create table target3 (x Int16) engine MergeTree order by x;

create materialized view mv3 to target3 as select x from target2;

grant select on source to definer1;
grant insert on target1 to definer1;
grant select on target1 to definer1;
grant select on target2 to definer1;

insert into source select number from numbers(10);

select * from mv3;
```

Why definer1 should have a select for target2? 
@pufit Can you please explain that?

**Comment by yariks5s** [comment]
@alsugiliazova The reason definer1 should have a SELECT privilege on target2 is due to the operation of the materialized view mv3.

1.	Materialized View mv1 reads from source and writes into target1. Since it uses DEFINER security with definer1, it requires definer1 to have the necessary privileges on both source (SELECT) and target1 (INSERT).
2.	Materialized View mv2 reads from target1 and writes into target2.
3.	And materialized View mv3 reads from target2 and writes into target3. When you query mv3, it triggers reads from target2.

When mv2 writes to target2, any subsequent query on mv3 reads from target2. Without SELECT privileges on target2, definer1 cannot read the data needed for the mv3 materialized view. If definer1 lacks SELECT privileges on target2, any attempt to query mv3 (which depends on target2) would fail. This ensures that all views and materialized views function correctly and the data pipeline remains intact.

@pufit correct me if I'm wrong
