### ISSUE TITLE
Why is it that when the HTTP client disconnects, only the "readonly" queries are canceled.

### ISSUE THREAD

**Issue by luffyhwl** [ClickHouse/ClickHouse#65875]
### Question

Only cancel queries that have "readonly"\"cancel_http_readonly_queries_on_client_close" set. Why can't we cancel all types of queries?

**Comment by CurtizJ** [comment]
INSERT queries are being canceled automatically if connection closed. Server will try to connect to the client to fetch new portion of data, and if it fails to do so, the query will be cancelled. 

DDL queries are either cheap and executed immediately or run and wait for asynchronous operations (mutations, queries in DDL queue and similar). Cancelling the query itself doesn't make sense because it almost doesn't consume any resources, but this feature was implemented mostly to avoid wasting resources uselessly. Cancelling asynchronous operations is not easy and may be dangerous, there are other mechanisms to cancel some of them (e.g. `KILL MUTATION` query).
