### ISSUE TITLE
GLIBC Security vulnerabilities for clickhouse server version 24.2.0-alpine

### ISSUE THREAD

**Issue by nnaik25** [ClickHouse/ClickHouse#66125]
### Company or project name

Self

### Question

Hello,

We are seeing below security vulnerabilities reported for GLIBC libraries packaged with server version 24.2.0-alpine

CVE-2021-38604
CVE-2020-6096
CVE-2020-1752
CVE-2021-3326
CVE-2022-23219
CVE-2021-35942
CVE-2022-23218
CVE-2021-27645
CVE-2023-4527
CVE-2019-25013
CVE-2020-29562
CVE-2020-27618
CVE-2020-10029
CVE-2023-4813

Library - /lib/libpthread.so.0

Can you please let me know if these are fixed? If yes, what is the version?

If not, what is the plan to fix these vulnerabilities?

**Comment by Algunenano** [comment]
The libraries come from `ubuntu:20.04` image. If they were fixed in the base image that was used at the time, then the CVEs are covered. 

https://github.com/ClickHouse/ClickHouse/blob/46ed1862502da43d2ffe087e33ba6ce451a8b16c/docker/server/Dockerfile.alpine#L1-L2

https://github.com/ClickHouse/ClickHouse/blob/46ed1862502da43d2ffe087e33ba6ce451a8b16c/docker/server/Dockerfile.alpine#L20-L21

You can find the build logs as part of the CH CI logs. For example, for `v24.2.3.70-stable`:
- Tag: https://github.com/ClickHouse/ClickHouse/releases/tag/v24.2.3.70-stable
- Commit: https://github.com/ClickHouse/ClickHouse/commit/8a7b8c7afb6718831e8da261ca1e68f3f741f177
- Docker server image: https://s3.amazonaws.com/clickhouse-test-reports/60606/8a7b8c7afb6718831e8da261ca1e68f3f741f177/docker_server_image.html
- Docker alpine amd64: https://s3.amazonaws.com/clickhouse-test-reports/60606/8a7b8c7afb6718831e8da261ca1e68f3f741f177/docker_server_image//home/ubuntu/actions-runner/_work/_temp/test/clickhouse__clickhouse-server:head-alpine-amd64.log
- Donor:
```
#5 [glibc-donor 1/2] FROM docker.io/library/ubuntu:20.04@sha256:21ae67bf44d1d0a53ecdce48742c766e44aea4d16e18a3b88a3888eddaf782b5
#5 resolve docker.io/library/ubuntu:20.04@sha256:21ae67bf44d1d0a53ecdce48742c766e44aea4d16e18a3b88a3888eddaf782b5 0.0s done
#5 CACHED
```

So glibc comes from `ubuntu:20.04@sha256:21ae67bf44d1d0a53ecdce48742c766e44aea4d16e18a3b88a3888eddaf782b5` . You could use whatever tool you use to validated CVEs to investigate further.

If you don't trust the images themselves, you can build your own custom images by simply downloading the binaries in any glibc capable docker image that's you consider safe.

**Comment by santrancisco** [comment]
Hi team

I double checked the version of libc in our latest ubuntu 20.04 build and found it is `(Ubuntu GLIBC 2.31-0ubuntu9.16)`

```
root@3e2380304678:~# /lib/aarch64-linux-gnu/libc.so.6
GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.16) stable release version 2.31.
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 9.4.0.
libc ABIs: UNIQUE ABSOLUTE
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/glibc/+bugs>.
```

Further digging into the change log of this specific 2.31 glibc build by ubuntu -  https://changelogs.ubuntu.com/changelogs/pool/main/g/glibc/glibc_2.31-0ubuntu9.16/changelog

if you search for any of these CVEs listed above, there are already fixes implemented.

My understanding is also that some security tools may report this version to be vulnerable to certain CVEs purely because the version is "2.31" and some CVEs just simply says "vulnerable up to 2.34"  eg - https://nvd.nist.gov/vuln/detail/CVE-2022-23219 without knowing that some minor versions contain fixes that was back-ported.

**Comment by nnaik25** [comment]
Thank you for your prompt response !!
