### ISSUE TITLE
how to achieve path analysis using click house, does anyone has relative experiences to share? 

### ISSUE THREAD

**Issue by Chr1sxu** [ClickHouse/ClickHouse#6719]
I'd like to build path analysis using clikhouse, but I couldn't find some helpful tips in documentation like funnel analysis. Does anyone has relative experiences to share?

sincerely appreciate

**Comment by filimonov** [comment]
Please check `windowFunnel` and `sequenceMatch` functions. They are quite straightforward. 

Also there is bit outdated but still nice video https://www.youtube.com/watch?v=YpurT78U2qA
(Outdated because most of it is about workaround of limitation of  `sequenceMatch` which is not exist anymore since beginning of 2019)

There was some discussion on github too (use searchbox in github to find tests and discussion), for example: 
https://github.com/yandex/ClickHouse/issues/2096

**Comment by blinkov** [comment]
@Chr1sxu, do you have any further questions?

**Comment by blinkov** [comment]
Feel free to re-open the issue if it is still relevant.
