### ISSUE TITLE
Test `03037_dynamic_merges_2_vertical_wide_merge_tree` is too long

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67721]
https://s3.amazonaws.com/clickhouse-test-reports/67701/090fb59194462324507d75f032aa803303c3e041/stateless_tests__aarch64_.html

**Comment by Avogar** [comment]
For this test I think we can reduce the table size to make it faster (at least let's try). This timeout happened because of random setting `index_granularity=1` and I still don't want to use fixed value of this setting in this test. If reducing size won't help, maybe we can somehow set the minimum value of settings `index_granularity/merge_max_block_size` in this test
