### ISSUE TITLE
DB::Exception: DB::Exception: Unknown setting allow_experimental_analyzer.

### ISSUE THREAD

**Issue by mneedham** [ClickHouse/ClickHouse#67859]
**Company or project name**

ClickHouse

**Problem**

I'm running a 22.7 and 24.7 server:

```bash
docker network create my-network

docker run -d --name clickhouse-server-227  --network my-network --ulimit nofile=262144:262144 clickhouse/clickhouse-server:22.7
docker run -d --name clickhouse-server-247  --network my-network --ulimit nofile=262144:262144 clickhouse/clickhouse-server:24.7
```
I connect to 24.7 and try to run a query against 22.7:

```bash
$ docker run --network my-network -it --ulimit nofile=262144:262144 clickhouse/clickhouse-server:24.7 clickhouse-client --host clickhouse-server-227

SELECT
    *,
    version()
FROM remote('clickhouse-server-227', 'system', 'settings')
LIMIT 1
FORMAT Vertical

Query id: 19acb298-1685-4203-b8d1-de878aa8e424


Elapsed: 0.004 sec.

Received exception from server (version 24.7.2):
Code: 115. DB::Exception: Received from clickhouse-server-247:9000. DB::Exception: Received from clickhouse-server-227:9000. DB::Exception: Unknown setting allow_experimental_analyzer. (UNKNOWN_SETTING)
```

**Comment by Algunenano** [comment]
This is expected (https://github.com/ClickHouse/ClickHouse/pull/65777/). The new analyzer changes how headers are generated in different releases and it's not backwards compatible.

You can't run a recent CH server (24.5+) with an old version that didn't know about the analyzer (should be 22.11). And when running against 22.11+ it should be disabled in the initiator for compatibility, unless the other replica uses 24.3+ (when it became the default option).

Updated to change 22.10 to 22.11. The final setting name was introduced in 22.11 (https://github.com/ClickHouse/ClickHouse/pull/42649)

**Comment by random-ua** [comment]
Why not make it possible to disable `allow_experimental_analyzer` completely via `remote()` arguments ? 

We are trying to migrate large dataset from 22.7 to 24.x and unable to do this because of [compatibility issue](https://github.com/ClickHouse/ClickHouse/issues/67045) with `BACKUP/RESTORE`. So we tried to use `INSERT ... FROM SELECT * FROM remote(old-server)` instead - and have this issue. What  would you recommend for migration from older Clickhouse if both options doesn't work ?

**Comment by mykhailo-mishchenko** [comment]
I also tried adding `SETTINGS allow_experimental_analyzer=0` to queries with `remote()` to an old server. It does not change anything. Is it possible to have a compatibility mode?

**Comment by Algunenano** [comment]
> Why not make it possible to disable allow_experimental_analyzer completely via remote() arguments ?

Because the analyzer changes how the blocks headers are send between servers, and in case of incompatibilities it can lead to incorrect results. This means that in order to avoid such problems we need to ensure the same value for the `allow_experimental_analyzer` is used in both servers.

> We are trying to migrate large dataset from 22.7

Upgrade the server to a version that has the setting (22.11).

> Is it possible to have a compatibility mode?

`allow_experimental_analyzer` **is** the compatibility mode. You must upgrade to a version with the setting (20+ releases ago) if you want to communicate with a server with 24.5+
