### ISSUE TITLE
Please create a better Debian repository

### ISSUE THREAD

**Issue by bzed** [ClickHouse/ClickHouse#6828]
Hi,

while it is very nice and appreciated that you are providing a debian repository of your clickhouse builds, unfortunately it is impossible to mirror it with common tools like aptly or debmirror. This is mainly due to the directory layout. Your repository is used as

```deb http://repo.yandex.ru/clickhouse/deb/stable/ main/```

while a common Debian repository is

```deb http://debian.foo/debian stretch main```

so what your repository basically is missing is the debian release in the path/directory structure, which results in the common mirroring tools to fail. Right now I'm using wget -r ...., but thats not really optimal.

Also it would be nice to have builds done in the appropriate debian release instead of a common one supposed to work on all releases.

Thanks for your work,

Bernd

**Comment by alexey-milovidov** [comment]
I will ask if it is possible to provide these repositories via symlinks or similar mechanics without actually duplicating files.

> Also it would be nice to have builds done in the appropriate debian release instead of a common one supposed to work on all releases.

We intentionally make portable packages that can be installed on a wide range of systems. It's not easy and I consider it as a significant achievement. Otherwise it's too cumbersome to build for every version of Ubuntu and Debian. And ClickHouse can be installed on very old systems that are no longer supported by maintainers, such as Ubuntu Lucid. (Many companies use these systems in production and don't care at all about the package repositories.)

Even more, recently we created rpm packages that contain exactly the same set of binaries. And they can be installed on CentOS 5 (we check it in our CI). There are many less known Linux distros such as russian AstraLinux, GosLinux, we don't build ClickHouse for them and ClickHouse can be successfully installed and work on such systems.

Portable binaries look like the right way. AFAIK, Go and Rust use this way by default. It's very good when you can build ClickHouse on your development machine, scp to server and run.

We build new testing package every night and we build development packages for every commit (and we already spent multiple TBs of storage for them). If these packages will be slightly different for every Debian, Ubuntu, RedHat, CentOS systems, we will burn 100x times more resources.

**Comment by Tigro** [comment]
Hi bzed.

Sorry, but our repo has non standart Debian pull structure to save old versions of clickhouse software.
So "deb http://debian.foo/debian stretch main" will not work one of these fine days.

To mirror your can use debmirror (with many options to override standart behavior), but the best way to use rsync

rsync repo.yandex.ru::yandexrepo/clickhouse/

---
rsync -avHP --delete repo.yandex.ru::yandexrepo/clickhouse/ /some/path
--

Also we can create symlinks like stretch or bullseye, but it will only symlinks to stable.
