### ISSUE TITLE
Test `02378_part_log_profile_events`is flaky

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#68500]
https://s3.amazonaws.com/clickhouse-test-reports/68488/da0a8051d8c8e8c2c72145e15cdf5a96e99641d2/stateless_tests__debug__s3_storage__[1_2].html

Broken in https://github.com/ClickHouse/ClickHouse/pull/68015

**Comment by CurtizJ** [comment]
#68015 is not related. All tests with mutations and `system.part_log` are flaky because mutation query (and then `SYSTEM FLUSH LOGS` query) may return earlier than the entry is added to the part log. It became more flaky after #67472 where flushing of logs was made parallel (the [first](https://s3.amazonaws.com/clickhouse-test-reports/67472/ec3232be092d09a46a2ac5f501cafa49fb42649b/stateless_tests__release_.html) failure in this PR on 30 July).

This test should be rewritten in the way like in #68409.

**Comment by KochetovNicolai** [comment]
More:
 https://s3.amazonaws.com/clickhouse-test-reports/0/59664d2762b4f2b14680bb191c4f3445e534f18b/stateless_tests__aarch64_.html
https://s3.amazonaws.com/clickhouse-test-reports/0/72b7ed8fba26bac621bf59ea81287605114ece16/stateless_tests__debug__s3_storage__[1_2].html
[
CI DB](https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBsaWtlICclMDIzNzhfcGFydF9sb2dfcHJvZmlsZV9ldmVudHMlJwogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPiBub3coKSAtIGludGVydmFsIDIgbW9udGgKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBkZXNjLCBjaGVja19uYW1lLCB0ZXN0X25hbWU=)

**Comment by nikitamikhaylov** [comment]
One more case: https://s3.amazonaws.com/clickhouse-test-reports/68843/a82421719383041a839289093d1882265a068cd1/stateless_tests__aarch64_.html
