### ISSUE TITLE
unexpected behavior of input_format_allow_errors_num & input_format_allow_errors_ratio

### ISSUE THREAD

**Issue by slimtom95** [ClickHouse/ClickHouse#6897]
**Version**: 2019/9/10 Master [1bd75b1](https://github.com/yandex/ClickHouse/commit/1bd75b1e74430be8e4f8e6a4aef2d00a305db3cf)

**Input Format**: JSONEachRow

**Setup SQL**:
```
create table default.test_input_ignore_error (a Int16, b Int16) Engine = Log()

insert into default.test_input_ignore_error format JSONEachRow {}
```

### 1. input_format_allow_errors_num
- Settings: `input_format_allow_errors_num= 1` and  `input_format_allow_errors_ratio= 0 `

- **Behavior: insertion never throw exception, good records got abandoned after the first bad record**

- **Expected Behavior: insertion throws exception if number of bad lines exceeds 
`input_format_allow_errors_num` and if insertion succeeds, all good rows should be inserted.**

- Reproduce SQL:
    ```set input_format_allow_errors_num= 1```
    ```set input_format_allow_errors_ratio= 0```
  
    + insertion never throw exception

    ```insert into default.test_input_ignore_error format JSONEachRow {1} {2} {3}```

    **Result:** Ok. 0 rows in set. Elapsed: 0.004 sec
    **Expected Result:** throw exception when meet the second bad record

    + good records got abandoned after the first bad record

    ```insert into default.test_input_ignore_error format JSONEachRow {} {2} {} {} {}```

    **Result:** Ok. 1 rows in set. Elapsed: 0.002 sec. 
    **Expected Result:** insert 4 rows not 1

### 2. input_format_ignore_errors_ratio 
- Settings: `input_format_allow_errors_num= 0` and  `input_format_allow_errors_ratio= 0.5 `

- **Behavior: the error ratio is not a error ratio in this BATCH but in the records we've SEEN. Also, good records ignored after the first bad record**

  For example, `G` for good and `B` for bad records, set ignore ratio to 0.5: 

  a input sequence `G B G B` is fine. But `G B B G` is not accepted, because CH will reject the second `B`  for a error ratio 0.75 in `G B B` seen records.

- **Expected Behavior: error ratio should calculate on the whole batch ( as the name of this setting implies) and if insertion succeeds, all good rows should be inserted.**

- Reproduce SQL:
    ```set input_format_allow_errors_num = 0```
    ```set input_format_allow_errors_ratio= 0.5```

    ```insert into default.test_input_ignore_error format JSONEachRow {1} {} {} {} {}```

    **Result:** Exception on client: Code: 26. DB::Exception: Cannot parse JSON string: expected opening quote: (Already have 1 errors out of 1 rows, which is 1 of all rows): (at row 1)
    **Expected Result:** insert 4 rows

**Comment by tavplubix** [comment]
Skipping errors in `JSONEachRow` works only if rows are delimited by `\n`, because parser skips all characters until the new line (or until EOF if there is no `\n`) to find the beginning of next row.  For queries like
```
insert into default.test_input_ignore_error format JSONEachRow {} {2} {} {} {}
```
parser ignores all data after bad record until EOF and counts it as one bad record. In this case `{}` is considered as one good record and `{2} {} {} {}` is considered as one bad record (2 records in total), so `input_format_allow_errors_num` works almost as you expected (but `JSONEachRow` does not).

We should describe this behaviour in documentation.

Also it's recommended to use both `input_format_allow_errors_num` and `input_format_ignore_errors_ratio` settings. Exception is thrown if both relative and absolute number of errors are greater than the corresponding setting, so when `input_format_allow_errors_num=2` and `input_format_allow_errors_ratio=0.5` sequence like `G B B G` or `B B G G` will be parsed successfully.

**Comment by slimtom95** [comment]
Thanks for the hints on `'\n'` delimitter, and it's a good idea to mention it in the docs.

I'll retest these settings with `'\n'` when I get back to work, let's just keep this thread open a few more days..

**Comment by slimtom95** [comment]
Hi @tavplubix 

With delimitter `\n`, now I have only one concern about `input_format_allow_errors_ratio`

> Behavior: the error ratio is not a error ratio in this BATCH but in the records we've SEEN. 

If we use  `input_format_allow_errors_ratio` alone(and less than 1 of course), any bad records at the front would cause a failure of the whole batch, for example `B G G G G`

So, is this behavior as expected or by design?

**Comment by tavplubix** [comment]
When inserting we don't know the total amount of rows until all of them are parsed, so errors ratio is calculated for rows we've seen. Probably, we could parse all rows just to calculate errors ratio for the whole batch, but it doesn't seem to be ok for large inserts. Because of it, `input_format_allow_errors_ratio` should be used in pair with `input_format_allow_errors_num` to allow skipping errors in the front.

**Comment by slimtom95** [comment]
Thanks for the detailed explanation!
