### ISSUE TITLE
Materialized View Operating on a Table Managed by a Refreshed Materialized View

### ISSUE THREAD

**Issue by Mdarwish1** [ClickHouse/ClickHouse#69098]
Materialized views on tables managed by refreshable materialized views are not functioning correctly due to the way data is ingested by the refreshable materialized view. The materialized view should be able to operate on this table so that each time the refreshable materialized view ingests data, it triggers the necessary transformations.

**Comment by al13n321** [comment]
Suppose there's a refreshable MV with target table `mid` and a regular MV that reads from `mid` and writes to table `out`:
```
CREATE MATERIALIZED VIEW rmv REFRESH EVERY 10 MINUTE TO mid ...;
CREATE MATERIALIZED VIEW mv TO out AS SELECT ... FROM mid;
```
[RMV] -> mid -> [MV] -> out

I can think of a few ways this chain could behave:
 1. The regular MV doesn't do anything, `out` stays empty. This is what currently happens. It kind of makes sense because refreshable MV technically doesn't insert data into the target table. It replaces the target table with a prepopulated new table.
 2. Each refresh *adds* rows to `out`. So `out` will grow and accumulate data from all refreshes, but `mid` will only have data from the latest refresh. This seems weird and likely unexpected to most people. Btw, if you want both `mid` and `out` to accumulate data from all refreshes, you can create the refreshable view with `APPEND` keyword (see https://clickhouse.com/docs/en/sql-reference/statements/create/view#refreshable-materialized-view), and the MV will work and add rows to `out`.
 3. Each refresh *replaces* the whole `out` table, like a refreshable MV. But there's already an intended way to do it: use a dependent refreshable MV instead of a regular MV, see https://clickhouse.com/docs/en/sql-reference/statements/create/view#refresh-dependencies

Which of these do you mean (if any)?

I currently think (1) makes the most sense, but (3) seems reasonable too (i.e. effectively turn a regular MV into a refreshable MV if its source table is the output of a refreshable MV), if that's what most people prefer. Option (2) seems too confusing.

**Comment by Mdarwish1** [comment]
I also prefer the first scenario, where using the word "APPEND" can provide the user with an option to send data to "out" if needed. However, I disagree with the third scenario because there are situations where multiple materialized views (MV) insert data into "out," not just from "mid." Therefore, it wouldn't make sense for the data in "out" to be deleted if "mid" is refreshed. I am satisfied with the current behavior along with the "APPEND" option: if multiple MVs are sending data to "out," there won't be an issue, and "out" will remain meaningful.
(I will wait for the version in clickhouse that contains append to fully test the behavior)

**Comment by al13n321** [comment]
APPEND is available. Example:
```sql
create table a (x DateTime) engine Memory;
create materialized view mv (x DateTime) engine Memory as select * from a;
create materialized view rmv refresh every 1 second append to a as select now() as x settings allow_experimental_refreshable_materialized_view=1;

select * from mv;                                         
                                                   
SELECT *                                           
FROM mv                                       
                                                   
Query id: d853e622-cdcf-4360-93b1-7fd84c18d6cd
                                                   
   ┌───────────────────x─┐                                                                                                                                                                                    
1. │ 2024-10-09 22:31:57 │
   └─────────────────────┘                                                                             
   ┌───────────────────x─┐
2. │ 2024-10-09 22:31:57 │                                                                                                                                                                                    
   └─────────────────────┘
   ┌───────────────────x─┐                                                                                                                                                                                    
3. │ 2024-10-09 22:31:58 │
   └─────────────────────┘                                                                                                                                                                                    
   ┌───────────────────x─┐                    
4. │ 2024-10-09 22:31:59 │                         
   └─────────────────────┘ 

4 rows in set. Elapsed: 0.001 sec.
```

But having a MV read directly from another MV (refreshable or not) doesn't work:
```
create table a (x Int64) engine Memory;
create materialized view mv1 (x Int64) engine Memory as select x*10 as x from a;
create materialized view mv2 (x Int64) engine Memory as select x*10 as x from mv1;
insert into a values (1);

select * from mv1;

SELECT *
FROM mv1

Query id: b6bb03ca-37b6-4c8f-87ca-dc26da2edfaa

   ┌──x─┐
1. │ 10 │
   └────┘

1 row in set. Elapsed: 0.001 sec. 

select * from mv2;

SELECT *
FROM mv2

Query id: 13a40f91-a28a-4c94-bcdd-49506ada31cd

Ok.

0 rows in set. Elapsed: 0.001 sec.
```
