### ISSUE TITLE
{table} and {database} macro in ReplicatedMergeTree vs RENAME TABLE 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#6917]
If table was created with {database} and {table} macros in zookeeper path, then RENAME operation makes it stop working. 

Probably those macros should be unfold at the moment of table creation.

**Comment by filimonov** [comment]
Related https://github.com/yandex/ClickHouse/pull/3251

**Comment by filimonov** [comment]
Similar https://github.com/yandex/ClickHouse/issues/6104

**Comment by alexey-milovidov** [comment]
We can unfold these macros at the table creation
but we should not unfold all other macros (shard, layer, etc.)
because there is typical scenario when table metadata (`.sql`) is copied between shards.

And the proposed logic of unfolding some macros and not unfolding other macros looks questionable.

**Comment by tavplubix** [comment]
Related #12135
