### ISSUE TITLE
Keeper dynamic reconfiguration recommendations

### ISSUE THREAD

**Issue by andrewjstone** [ClickHouse/ClickHouse#69355]
### Company or project name

Oxide Computer Company

### Question

Hi, I'm currently working on a mechanism to automate dynamic reconfiguration of clickhouse keeper clusters across server sleds in our rack. I have spent some time reading the keeper and nuraft code, and the clickhouse documentation and I understand that only one node should be added or removed at a time due to the limitations of the nuraft reconfiguration protocol. 

My original plan, which I have started working on, was to update the raft configuration in the XML files on each node with only one addition or removal at a time. Then the leader would apply this configuration change asynchronously. In the common case this should work fine, and I've tested it out plenty with success. However, I've also seen reconfiguration fail when I didn't have the new keeper online yet. While that's easy to rectify programmatically, presumably failure can occur for a host of other reasons and it does not appear like there is a way to figure out if the reconfiguration itself has failed or is still in flight without looking at the logs output from the keepers. While I can poll the configuration from `/keeper/config` using the `clickhouse-keeper-client`, that only tells me if the reconfiguration has *succeeded*. An unchanged configuration is not enough information to tell me if the operation is still in flight or has failed. It's the relatively unbounded asynchrony that is the issue. I know the reconfiguration will get retried up to 20 times by default in the background, but I also don't want to assume it failed because of some configured retries and timeouts.

One other option, which I noticed is no longer marked experimental, is to issue a `reconfig` command to a keeper node. From reading the keeper code it appears that this command will return success or failure right away. Now of course it's possible that my keeper client gets disconnected after the reconfiguration operation finishes but before the response is received. However, in that case I can simply try again, as the operation is blocking and I will either succeed idempotently if the member was added to or removed from the configuration, or get an error I believe. While this sounds like a plausible way forward, I have some questions about the `reconfig` command to help me determine if I should proceed in this direction instead. 

1. Is `reconfig` the recommended strategy for dynamic reconfiguration of keeper clusters right now?
2. If I issue a `reconfig` command, do I still need to update the `keeper-config.xml` files after the fact with the latest configuration?
3. If I issue a `reconfig` command via `clickhouse-keeper-client` will I always get a `success | fail` back if the connection is healthy?
4. If I get a `success` back after submitting a dynamic reconfiguration, does that mean that the configuration was actually *committed* to the raft log?
5. Will this be true if I enable`quorum-reads`?
6. If I get a `failure` back after submitting a dynamic reconfiguration, does that mean that the request absolutely will not get committed to the raft log and applied as a new configuration?
7. Are updates via `reconfig` idempotent?
8. Are the configurations returned from `/keeper/config` committed configurations? If I read a configuration from `/keeper/config` and don't make any membership changes, is that configuration stable indefinitely?
9. When a keeper has a lot of data it will have snapshots and a relatively large amount of log entries not yet in a snapshot to transfer to a new member before that member is capable of committing any new entries. It seems like when adding a replica we should wait for it to be caught up before we add another replica, or else we can potentially affect liveness as described in section 4.2 of [Diego's Ongaro's raft thesis](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf).
     1. How much data does the keeper maintain, and in practice do you expect this to be a problem?
     2. How can I monitor this information? Is the `lgif` four letter word command the best way? 
     3. Is there any way to see how many comitted entries have been applied to the state machine on a server so far?
     4. If not, is that something you'd be willing to add?
11. Is there anything special about the way nuraft and keeper handle the addition or removal of servers, that is different from what the raft thesis describes for single node reconfigurations?
12. Is there anything else I should be aware of? Any tips or tricks?

I know this is a long detailed list and I greatly appreciate your time here. Understanding dynamic reconfiguration fully will give us the confidence and ability to automate it for lights out operation. Thanks!

**Comment by antonio2368** [comment]
> Is reconfig the recommended strategy for dynamic reconfiguration of keeper clusters right now?

It was done by an external contributor so there could be some bugs I'm not aware of, but I reviewed the PR and the tests look fairly stable now. There could be some undetected bugs of course.

> If I issue a reconfig command, do I still need to update the keeper-config.xml files after the fact with the latest configuration?

No, enabling `reconfig` with `enable_reconfiguration` you will disable the updates using the config file changes.


> If I issue a reconfig command via clickhouse-keeper-client will I always get a success | fail back if the connection is healthy?

You should get the result back if the connection is healthy.

> If I get a success back after submitting a dynamic reconfiguration, does that mean that the configuration was actually committed to the raft log?

Now it's a bit more complicated, there is a setting `async_replication` (https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper#internal-coordination-settings) which I recommend to enable but is for now disabled because of backward compatibility.
If async replication is used, success will just mean the request was accepted by the leader but it doesn't mean it's committed. If it's not used, success will be returned on commit.

> Will this be true if I enablequorum-reads?

This doesn't affect config changes.

> If I get a failure back after submitting a dynamic reconfiguration, does that mean that the request absolutely will not get committed to the raft log and applied as a new configuration?

It's hard to say, e.g. there is a timeout for forwarding requests to the leader so it can be failure because of that while the config was accepted.

> Are updates via reconfig idempotent?

Of course, they are deduplicated based on the ID and that is what allows you to write a more robust logic regardless of the "uncertainties" by Raft.
You can poll the `/keeper/config` node and retry the operation after some time without any fear of creating duplicate servers or removing a node you didn't want to.

> Are the configurations returned from /keeper/config committed configurations? If I read a configuration from /keeper/config and don't make any membership changes, is that configuration stable indefinitely?

Yes, it's the committed config, and it should be stable if you don't do any changes to the config.

> When a keeper has a lot of data it will have snapshots and a relatively large amount of log entries not yet in a snapshot to transfer to a new member before that member is capable of committing any new entries. It seems like when adding a replica we should wait for it to be caught up before we add another replica, or else we can potentially affect liveness as described in section 4.2 of [Diego's Ongaro's raft thesis](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf).

Yes you should wait for it to sync so you don't increase quorum while the replicas are still stale.

> How much data does the keeper maintain, and in practice do you expect this to be a problem?

Snapshot is created after 100k logs by default (controlled by `coordination_settings.snapshot_distance`).
We didn't see many problems with syncing replicas but you can control some aspects of replication. E.g. you can control the max batch size of a single append request (controlled by `coordination_settings.max_requests_append_size` by default it's `100`)

> How can I monitor this information? Is the lgif four letter word command the best way?

Yes, that's a good command to see the current state, but you can also use `Prometheus` endpoint and continuously monitor it.

> Is there any way to see how many comitted entries have been applied to the state machine on a server so far?
If not, is that something you'd be willing to add?

`lgif` is the answer.

> Is there anything special about the way nuraft and keeper handle the addition or removal of servers, that is different from what the raft thesis describes for single node reconfigurations?
Is there anything else I should be aware of? Any tips or tricks?

Maybe I forgot some details, but I don't think it's 100% same as in the paper. In the paper, the new config is used instantly when it is stored in the logs, while in Nuraft the config is used only after it is committed (stored by majority of the nodes).
In any case, cluster reconfiguration is really messy in Raft, and can seem hacked-in so it's hard to cover all the cases perfectly and return all the information in a synchronous way.
As I said before, I would use the simplest way of polling the `/keeper/config` and retrying the operations after some arbitrary timeout until the poll returns the expected node.

**Comment by andrewjstone** [comment]
Thank you so much for the detailed answers @antonio2368. This is really helpful. This definitely gives me a way forward and some paths for testing. I very much appreciate all your help!
