### ISSUE TITLE
arrayMax / arrayMin with a function parameter not working anymore

### ISSUE THREAD

**Issue by alfonsonishikawa** [ClickHouse/ClickHouse#69600]
ClickHouse 24.8.2.3

Examples
========

This taken from the documentation:

```
SELECT arrayMax(x -> (-x), [1, 2, 4]) AS res;
```

returns the error:

```
Code: 49. DB::Exception: Unexpected return type from arrayMax. Expected Int16. Got UInt8. Action: FUNCTION arrayMax(__lambda :: 1, [1, 2, 4] :: 0) -> arrayMax(lambda(tuple(x), negate(x)), [1, 2, 4]) Int16 : 3, input block structure:__lambda Function(UInt8 -> Int16) Function(size = 1), [1, 2, 4] Array(UInt8) Const(size = 1, Array(size = 1, UInt64(size = 1), UInt8(size = 3))): while executing 'FUNCTION arrayMax(__lambda :: 1, [1, 2, 4] :: 0) -> arrayMax(lambda(tuple(x), negate(x)), [1, 2, 4]) Int16 : 3'. (LOGICAL_ERROR) (version 24.8.2.3 (official build)) 
```
But the error persists event with this:
```
SELECT arrayMax(x -> toUInt16(-x), [1, 2, 4]) AS res;
```

This other that used to work too:
```
select arrayMax(x -> x.1, [(1, 'a'), (0, 'b')])
```

now fails with

```
Code: 49. DB::Exception: Unexpected return type from arrayMax. Expected UInt8. Got Tuple(UInt8, String).
```

**Comment by SaltTan** [comment]
Works in 24.6 https://fiddle.clickhouse.com/fb396b27-0796-4830-98e4-b6fdac5fdbad
maybe this PR is related? https://github.com/ClickHouse/ClickHouse/pull/65455

**Comment by rschu1ze** [comment]
Also see ^^ duplicate report.

The regression has definitely been introduced by #65455 and it was noted in the community Slack ([here](https://clickhousedb.slack.com/archives/CUDSPUJ68/p1726225453099589)).

The regression is bad enough to justify a revert of #65455. On the other hand, the PR has been in for a while and it seems users rely on the new functionality already :-/

**Comment by Scartiloffista** [comment]
hi! slack reporter here

i started to work on it (very small C++ experience), but it seems to me that the problem could be [here](https://github.com/ClickHouse/ClickHouse/blob/4c4a051d5ee86c112a8eaff6f6f01e89c991838d/src/Functions/array/arrayAggregation.cpp#L374), in the `execute`, the return value is copied from there but it probably keeps the (wrong) type from the parameter array

i think so because the exception is reported [here](https://github.com/ClickHouse/ClickHouse/blob/4c4a051d5ee86c112a8eaff6f6f01e89c991838d/src/Interpreters/ExpressionActions.cpp#L636) and it's that `action.node->function->execute` that returns a wrong `res_column.type->getName`,

**Comment by Algunenano** [comment]
Looks the same as https://github.com/ClickHouse/ClickHouse/issues/68895
