### ISSUE TITLE
New JSON type "unflattens" keys with `.` characters

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#69846]
Keys containing the `.` character are valid JSON, however when inserted into the new JSON column these values are "unflattened" into a nested structure.

**Release version**
Reproduces on master (24.9.1.3283)

**How to reproduce**
```
CREATE TABLE unflattened (v JSON) ENGINE=Memory;
INSERT INTO unflattened VALUES('{"key.with.dots":"value"}')
SELECT v FROM unflattened

   ┌─v─────────────────────────────────┐
1. │ {"key":{"with":{"dots":"value"}}} │
   └───────────────────────────────────┘
```

**Expected Behavior**
The initial key/field label (with dots) should be preserved.  The behavior may be acceptable or unavoidable, but at the moment inserting such a JSON string does not return the same JSON string when querying.

**Comment by Avogar** [comment]
Unfortunately it's unavodiable because we store flattented JSON paths inside JSON column, so we cannot know if `key.with.dots` is a single key or a flattened path `{"key" : {"with" : {"dots"}}}`.
Probably we can escape dots in keys during parsing, but in this case to read the `key.with.dots` subcolumn from the JSON you will need to write
```
json.`key\.with\.dots`
```
