### ISSUE TITLE
submodules contrib/liburing and contrib/sysroot are always modified

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#70287]
### Company or project name

Prothentic,Inc.

### Question

I found that submodules contrib/liburing and contrib/sysroot are always modified. I tried several approaches as following but failed to remove the changes:
1. delete the folder and then `git submodule update --init -f`
2. In contrib/liburing, run `git restore`
3. git checkout .
4. git stash
It seems that there is a tool which automatically change the content of liburing and sysroot.

<img width="956" alt="image" src="https://github.com/user-attachments/assets/a1b9d35f-e873-4058-b55b-e3ab2ebb8240">

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/293b7384-5611-4dea-a4cb-1d20a73f4280">

**Comment by Algunenano** [comment]
IIRC this is because there are files with the same name but different upper-case vs lower-case and macOS is case insensitive: https://discussions.apple.com/thread/251191099?sortBy=rank

AFAIK you can either change to a [different filesystem ](https://brianboyko.medium.com/a-case-sensitive-src-folder-for-mac-programmers-176cc82a3830) or just add ignores to those submodules in your local git config.

**Comment by SayeedKhan21** [comment]
should this be added to docs as well @Algunenano ?? and also that latest llvm version (19) gives error while building so it  should be 18 or probably less to avoid getting unnecessary errors ??

**Comment by Algunenano** [comment]
LLVM 19 support is in progress.

**Comment by SayeedKhan21** [comment]
@Algunenano I am working on doc changes on these above mentioned changes required to build on macOs , so should i mention use of lower llvm versions or not ??
