### ISSUE TITLE
Clarifications on the Recommended Maximum Number of Tables in ClickHouse

### ISSUE THREAD

**Issue by minQZ** [ClickHouse/ClickHouse#70424]
### Question

Hello,

I have reviewed the documentation [here](https://clickhouse.com/docs/knowledgebase/maximum_number_of_tables_and_databases), which recommends using around 5,000 tables. I have three questions regarding this recommendation:

1. Is the recommendation of 5,000 tables based solely on the number of tables, regardless of their size? If size is also a factor, what is the assumed amount of data per table for this recommendation?
2. The document mentions that having more than 5,000 tables can affect the startup time. Does this impact only the startup time, or could it also affect query performance?
3. Does the 5,000 table limit include detached tables, or are they excluded from this count?

I would appreciate any clarification on these points.

Thank you!

**Comment by minQZ** [comment]
If anyone has insights, even answering one of the questions would be greatly appreciated. Thank you!

**Comment by den-crane** [comment]
>Is the recommendation of 5,000 tables based solely on the number of tables, regardless of their size? 

Regardless. 5000 tables Replicated MergeTree tables. Replication brings some overhead. 

>The document mentions that having more than 5,000 tables can affect the startup time

The startup time is less affected with recent version because now tables are attached asynchronously not during startup. 
It affects query execution because replication uses CPU. So if one table uses ~0.1% of one CPU for Replication, then 5000 tables will use 100% of five CPU.

https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/

**Comment by minQZ** [comment]
@den-crane 

Hello,

Thank you for your previous response. I conducted a performance test in an environment with 32,000 ReplicatedMergeTree tables replicated twice. Each table, on average, has 50 columns and 2,000 rows. Interestingly, the results showed almost no difference in performance compared to when there were 0 tables. 

This makes me wonder if the overhead you mentioned for replication is primarily related to situations where data is actively being inserted into the tables, rather than a constant overhead regardless of activity. Could you provide some clarification on this?

Additionally, if possible, I would appreciate any insights regarding my third question: Does the 5,000 table limit include detached tables, or are they excluded from this count?

Thank you for your time and assistance.

**Comment by den-crane** [comment]
Right, active insertion creates much bigger impact and this limit 5000 is about active / modified tables. But even idle / inactive MergeTree* and especially ReplicatedMergeTree* tables bring the constant overhead. MergeSelector/MergeCleaner constantly iterate through all tables.

I did tests a while ago https://github.com/ClickHouse/ClickHouse/issues/31919 
The problem was related to ZK communication.
It was improved since when https://github.com/ClickHouse/ClickHouse/pull/50107
But anyway it depends on a setup. For example if you use built-in Keeper and Clickhouse communicates with local Keeper, it has less ZK communication overhead. Or if you use 40Gbit network and Keeper and compression in Keeper communication then overhead is less noticeable. 

>Does the 5,000 table limit include detached tables, or are they excluded from this count?

Only attached tables are accounted.

**Comment by minQZ** [comment]
@den-crane

Thank you for the detailed answers. They have clarified everything I needed to know.
