### ISSUE TITLE
Left join a table in view vs table itself different results

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#70465]
**Company or project name**

Clickouse employee :smile: 

**Describe the unexpected behaviour**

A materialized view with a view doing `SELECT * FROM table` in a left join gives different results compared to using the table itself in the materialized view.

**How to reproduce**

Run this Fiddle:

https://fiddle.clickhouse.com/893c0f89-52f2-4017-8f53-7ab14f0d642f

**Expected behavior**
Both materialized views should give the same result.

**Comment by alsugiliazova** [comment]
https://fiddle.clickhouse.com/8ad256a3-b017-440b-b5ee-2981c784a9f1
affected by analyzer

**Comment by vdimir** [comment]
I'd say its expected behaviour. When you reference source table in mv query it contains only inserted subset of rows. In the first excaple it's referenced though a view, so technically different table and we expect it to read all data from `t0`

https://github.com/ClickHouse/ClickHouse/discussions/59187
https://github.com/ClickHouse/ClickHouse/pull/50857/files

**Comment by vdimir** [comment]
Please review changes to documentation with clarification on this case:
https://github.com/ClickHouse/clickhouse-docs/pull/2827
