### ISSUE TITLE
(text in a foreign language) The index is not used when a table of type Set is used in a filter condition.

### ISSUE THREAD

**Issue by microcropoc** [ClickHouse/ClickHouse#70475]
Приветствую. Подскажите пожалуйста, почему не используется индекс при использовании таблицы типа Set в условии фильтрации.

```sql
CREATE TABLE test_numbers
ENGINE = MergeTree ORDER BY id
AS
SELECT number AS id FROM system.numbers LIMIT 1000000

CREATE TABLE table_ids
ENGINE = Set
AS
SELECT number FROM system.numbers LIMIT 1

SELECT id FROM test_numbers
WHERE
    id IN table_ids
FORMAT JSON

--"rows_read": 1000000

SELECT id FROM test_numbers
WHERE
    id IN (SELECT number FROM system.numbers LIMIT 1)
FORMAT JSON

--"rows_read": 8193
```
Если использовать подзапрос вместо Set таблицы, то индекс используется, хотя, судя по плану запроса, подзапрос превращается в тот же Set

```sql
EXPLAIN SELECT id FROM test_numbers
WHERE
    id IN (SELECT number FROM system.numbers LIMIT 1)

--CreatingSets (Create sets before main query execution)          
--  Expression ((Project names + Projection))                     
--    Filter ((WHERE + Change column names to column identifiers))
--      ReadFromMergeTree (default.test_numbers) 
```

Проверял на версии 24.10.1.1405

**Comment by alexey-milovidov** [comment]
The set at the right hand side of the IN operator can be used for an index if we can enumerate the values in the set and order them. The implementation of Set tables can store hash values instead of original values in some cases, and in those cases, the values cannot be extracted back and ordered. For this reason, it was not implemented for Set tables in general.
