### ISSUE TITLE
DataPart compaction issues.

### ISSUE THREAD

**Issue by easymanlo** [ClickHouse/ClickHouse#70628]
### Question

Is there official documentation on the underlying DataPart merge strategy in ClickHouse? Additionally, which class contains the corresponding source code? I am not very clear about the DataPart merge strategy.

<img width="992" alt="image" src="https://github.com/user-attachments/assets/58c8c507-211d-4981-ba75-9306c5199301">
<img width="824" alt="image" src="https://github.com/user-attachments/assets/0a633dbc-d2bc-4418-96d4-aa2b682863aa">

![image](https://github.com/user-attachments/assets/c1b02e62-c433-4e92-92f6-d4d44cbd172a)

![image](https://github.com/user-attachments/assets/ec6b761a-5166-47da-bbb3-9c45da91c6c5)

**Comment by den-crane** [comment]
>After a 7-hour interval, theoretically, there should be no further merges.

It's not correct statement. Part may stay unmerged forever. 
Merges are eventual and may never happen. It depends on the number of inserts that happened after, the number of parts in the partition, size of parts.
Clickhouse server has an internal goal to minimize number of merges, because merges are very expensive from CPU and disk resource perspective.

See [min_age_to_force_merge_seconds](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#min_age_to_force_merge_seconds) if you want to force merges.

And yes, the MergeSelector does not scheduler merges for parts from different disks.

**Comment by easymanlo** [comment]
"Thank you for your answer, but I would like to know the merging strategy for parts. Could you please explain it in more detail? I still don't understand this part. Thank you very much."

**Comment by alexey-milovidov** [comment]
It is described in the `SimpleMergeSelector` class.
