### ISSUE TITLE
Use `Join` as layout for dictionaries and for function `transform`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#7088]
**Use case**
It can be used to add support for all available types.

**Comment by filimonov** [comment]
Also it has a lower memory usage, without visible performance impact.

**Comment by alexey-milovidov** [comment]
If it will have no performance impact (that's unlikely), we can even get rid of a huge chunk of code, that it very optimistic.

**Comment by amosbird** [comment]
> for function `transform`

Hmm, what's the purpose of this one? I feel that dictGet / joinGet is equivalent.

**Comment by alexey-milovidov** [comment]
@amosbird Function `transform` allows to specify simple inline transformation without creating a dictionary.
But currently it does not support all the ClickHouse types.

**Comment by amosbird** [comment]
> @amosbird Function `transform` allows to specify simple inline transformation without creating a dictionary.
> But currently it does not support all the ClickHouse types.

Ok.. but how can `Join` layout apply to the `transform` function?

**Comment by alexey-milovidov** [comment]
Join is a key-value data structure for lookups. This is exactly what is needed in `transform`.
Currently `transform` builds very specialized hash table. Join data structure looks like a generalization.

**Comment by amosbird** [comment]
Ah, I thought the `join` layout means the JOIN engine that needs to be somehow passed into `transform`.

**Comment by alexey-milovidov** [comment]
Yes, it's about reuse of the internal data structure: basically a hash table pointing to blocks.

**Comment by pmimanukyan** [comment]
I will do this task.

**Comment by alexey-milovidov** [comment]
This task is free to take.

**Comment by alexey-milovidov** [comment]
I have implemented generic variant of function transform.

**Comment by canhld94** [comment]
So there's a proposal long time ago but never been implemented. We've been having problem with storage join recently because it's not replicated. I did some test to see if we can use hash dictionary over replicated table to replace storage join, but the result not good:

- Memory: hashed dictionary will use more memory compared to join table, likely 2x-3x for single key and can be 10x for composite key
- Performance: `dictGet` and `joinGet` have same performance for single key, however JOIN with join table will be cheaper than dictionary with composite key (direct join doesn't support dictionaries with composite key)
- Other: dictionary doesn't support enum columns

So in-order to keep using storage join, we need to use this set-up with an additional RMV.

```
┌─────────────────────┐    ┌──────────────────────────────┐    ┌─────────────────────┐
│  Replicated Table   │───▶│   Refreshable Materialized   │───▶│   In-Memory Join    │
│      Source         │    │           View               │    │       Table         │
└─────────────────────┘    └──────────────────────────────┘    └─────────────────────┘
         │                                   │                           │
         │                                   │                           │
         ▼                                   ▼                           ▼
┌─────────────────────┐    ┌──────────────────────────────┐    ┌─────────────────────┐
│ - Data ingestion    │    │ - Transforms source data     │    │ - Fast lookups      │
│ - Replication       │    │ - Refreshed on startup       │    │ - Query performance │
│ - Persistence       │    │ - Manual refresh trigger     │    │ - Memory resident   │
└─────────────────────┘    └──────────────────────────────┘    └─────────────────────┘
```

It'd be good to have dictionaries using `HashJoin` layout. Nevertheless, the dictionary code is :exploding_head: and not trivial at all to add new layout (and make it work out-of-the-box with what we have currently with storage join).
