### ISSUE TITLE
Allow to change maximum number of threads in global ThreadPool in config.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#7099]
**Use case**
The user has large number of concurrently running distributed queries, that may be almost idle all the time. And default 10 000 threads are not enough.

**Comment by bharatnc** [comment]
@alexey-milovidov  I would like to work on this issue.

This is my first time contributing and I wanted to know if what I have on my mind sounds right to you , before I start contributing to this issue.

**Steps:**
1. For making the max threads in GlobalThreadPoolConfig: https://github.com/ClickHouse/ClickHouse/blob/55b81c97e6b13c4ac5f53da5eec7fb4ff5b875de/dbms/src/Common/ThreadPool.h#L131 I think the configuration has to be parsed with the help of the ConfigProcessor defined in: `Common/Config/ConfigProcessor.h`.
2. Then override the default value which is defined here: `GlobalThreadPool() : FreeThreadPool(10000, 1000, 10000) {}` later in the `ThreadPool.cpp`file particularly in this method:

```cpp

template <typename Thread>
void ThreadPoolImpl<Thread>::setMaxFreeThreads(size_t value)
{
    DB::ConfigProcessor processor(argv[1], false, true);
    auto config = processor.loadConfig().configuration;
    std::lock_guard lock(mutex);
    max_free_threads = value;
}
```
https://github.com/ClickHouse/ClickHouse/blob/55b81c97e6b13c4ac5f53da5eec7fb4ff5b875de/dbms/src/Common/ThreadPool.cpp#L44

I think a helper method can be used to override the value of `10000` if the config is actually present in the configuration file.

I also had the following questions:
1. As for the setting itself, which config file / section should this setting live in? I could see that there are several of them.
2. Should we also make the other two parameters `queue_size_` and `max_threads_` configurable while doing this for `max_free_threads_`?
3. Is there a similar example/pattern in the codebase that you could point me to so that I can make it uniform and similar to other settings?

Thank you!
