### ISSUE TITLE
Roung function issue, version 24.5

### ISSUE THREAD

**Issue by kazhou2024** [ClickHouse/ClickHouse#71002]
SELECT round(3.455, 2), round(98.625, 2) AS rounded_value;

3.46  	98.62

![image](https://github.com/user-attachments/assets/544f6108-7f45-4834-8726-9b3c0ae676d3)

**Comment by ligen131** [comment]
This is as expected.

According to the [ClickHouse documentation on Rounding Functions](https://clickhouse.com/docs/en/sql-reference/functions/rounding-functions#round):

> the function uses banker’s rounding for Float* inputs

[Banker's rounding](https://en.wikipedia.org/wiki/Rounding#cite_note-8), also known as round half to even, rounds a number to the nearest even digit in the last place specified. `round(3.455, 2)` results in 3.46 because it rounds up to the nearest even number 6, while `round(98.625, 2)` stays at 98.62 because the number 2 is already even.
