### ISSUE TITLE
Failure to parse unix time

### ISSUE THREAD

**Issue by vad0** [ClickHouse/ClickHouse#71177]
> version 24.9.2.

> Dijkstra Markets

> What is wrong

I have a table with column `message_received_time  DateTime64(9, 'UTC')`.
The following query returns some meaningful results:
```
SELECT toUnixTimestamp64Nano(message_received_time), message_received_time
FROM uds_trade
WHERE message_received_time = toDateTime64('2024-10-26 12:06:23.808540260', 9, 'UTC')
```
  ┌─toUnixTimestamp64Nano(message_received_time)─┬─────────message_received_time─┐
1. │                          1729944383808540260 │ 2024-10-26 12:06:23.808540260 │
   └──────────────────────────────────────────────┴───────────────────────────────┘

But the following query does not return anything:
```
SELECT message_received_time
FROM uds_trade
WHERE message_received_time = 1729944383.808540260
```
Using Unix time works well in inequality constraints, but fails to retrieve existing data when used in equality constraints.

It looks like a float arithmetic issue to me. Probably the Unix timestamp is parsed into a float64 variable and then converted to int64. It can be fixed if decimal floats are used on a query parsing stage.

**Comment by max-vostrikov** [comment]
It is a float64 issue - you can't write `1729944383.808540260` because it is too much numbers, even for float64. You are actually writing something else (more specifically 1729944383.808540260 = 1729944383.808540416 for float64)
The datetime64 seems to be working correctly here.
Look at my example - https://fiddle.clickhouse.com/61f281b4-36ec-4161-89ec-8dad21e616d8:
If you get the Decimal type, you can select the value you want - `toDecimal128(1729944383, 9) + toDecimal128(0.808540260, 9)`.

I do not see it as a bug, it is expected that float64 have limits. Does it solve you issue?
