### ISSUE TITLE
Why Nullable data type is not supported in bloom filter text indexes?

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#71338]
### Company or project name

N/A

### Question

I see that `bloom_filter` index can be used on many data types possibly wrapped in `Nullable`, `LowCardinality` or `Array`. But seems for bloom filter indexes (tokenbf/ngrambf), `Nullable` is not allowed.

**Comment by amabilee** [comment]
`Nullable` data types are not supported in `bloom` filter text indexes because `bloom` filters do not include null values.

The primary purpose of a `bloom` filter is to enable **data skipping**. When a query is executed, the `bloom` filter is checked first to **quickly** determine if a data file might contain relevant rows. If the `bloom` filter indicates that the file does not contain the element, the file is skipped, saving I/O operations.

However, if the query involves null values, the `bloom` filter cannot provide this data skipping capability, and the data file must be read anyway.

Hope that helps!

**Comment by cangyin** [comment]
@amabilee Thanks, it make sense
```sql
SELECT NULL LIKE '%abc%'

┌─like(NULL, '%abc%')─┐
│ ᴺᵁᴸᴸ                │
└─────────────────────┘
```
But I see that `bloom_filter` supports Nullable  types:
```sql
CREATE TABLE test
(
  i UInt32,
  a Nullable(String)
)
ENGINE = MergeTree
ORDER BY i
SETTINGS index_granularity=1;

-- This is not supported
ALTER TABLE test ADD INDEX a1 a TYPE bloom_filter GRANULARITY 1;

-- But this is not supported
-- ALTER TABLE test ADD INDEX a2 a TYPE tokenbf_v1(512,3,0) GRANULARITY 1;

INSERT INTO test VALUES (1, NULL);
INSERT INTO test VALUES (2, 'hello world');

select * from test where a = 'hello world';
```
https://fiddle.clickhouse.com/77e499f3-83ba-4d78-be8c-53faccd50d0f

**Comment by cangyin** [comment]
Perhaps a setting like `nullable_allow_data_skipping_indices` for user to know that data skipping indices may drop data blocks containing NULL values.

And under that terms, Ngrambf/Tokenbf can support Nullable.

**Comment by cangyin** [comment]
> However, if the query involves null values, the `bloom` filter cannot provide this data skipping capability, and the data file must be read anyway.

I think NULL values can be actually skipped by skip indices: https://fiddle.clickhouse.com/ae35349f-ad72-4484-b159-c41ae4e3b4d7
```sql

select 1 where NULL like '%%';
select 2 where NULL is NULL;

2
```

So I guess that why the `bloom_filter` supports Nullable type.

@melvynator Please reopen the ticket, some one or me can implement that feature.
