### ISSUE TITLE
Could someone explain the relationship between OSIOWaitTime,OSCPUWaitTime,OSCPUVirtualTime in profileevent of a query?

### ISSUE THREAD

**Issue by livingston0318** [ClickHouse/ClickHouse#71339]
### Question

I was trying to do a test, that comparing query time between a single query to 2 same query in parallel, both of these query have the same SQL, but the single query is always  fast one, can someone explain the relationship between OSIOWaitTime,OSCPUWaitTime,OSCPUVirtualTime?
<img width="504" alt="image" src="https://github.com/user-attachments/assets/8dcccc44-f41c-42f7-9188-35dd6059f24c">
the node is 48 core， and each query has a setting for max_threads=10

**Comment by livingston0318** [comment]
clickhouse version is 24.8.4.13

**Comment by livingston0318** [comment]
What I thought is that, there might be some racing condition, which causes waiting time for queries in parallel, does anyone have any idea?

**Comment by nickitat** [comment]
meaning of this metrics explained in the docs:
https://github.com/ClickHouse/ClickHouse/blob/01db925bbc1ba0395c15345e6c37a085449348a8/src/Common/ProfileEvents.cpp#L370-L372
when you run multiple queries in parallel you should expect slowdown because those queries will compete for resources. it makes sense to lower `max_threads` proportionally to have better timings.
