### ISSUE TITLE
ClickHouse successfully creates protobuf schema with recursive fields

### ISSUE THREAD

**Issue by topofstack** [ClickHouse/ClickHouse#71455]
Likely related to the fix of [70630](https://github.com/ClickHouse/ClickHouse/issues/70630)  issue

Here's message.proto file that contains recursive field `google.protobuf.Struct`:
```proto
message Message {
  string event = 1
  google.protobuf.Struct payload = 2;
}
```

The default command creating schema based on provided proto file works correctly with expected output:
```sql
CREATE TABLE Message
ENGINE = File('ProtobufSingle')
SETTINGS format_schema='example.com/test/message.proto:Message';
```

output:
```
Code: 36. DB::Exception: ClickHouse doesn't support type recursion (google.protobuf.Struct.fields): The table structure cannot be extracted from a ProtobufSingle format file. You can specify the structure manually. (BAD_ARGUMENTS) (version 24.8.6.70 (official build))
```

But if `input_format_protobuf_skip_fields_with_unsupported_types_in_schema_inference` flag is provided:

```sql
CREATE TABLE Message
ENGINE = File('ProtobufSingle')
SETTINGS format_schema='example.com/test/message.proto:Message',
input_format_protobuf_skip_fields_with_unsupported_types_in_schema_inference = 1;
```

the following DDL is generated

```sql
CREATE TABLE RecursiveMessage
(
    `event` String,
    `payload_fields` Map(String, Tuple(null_value Enum8('NULL_VALUE' = 0), number_value Float64, string_value String, bool_value UInt8, list_value_values Array(Tuple(null_value Enum8('NULL_VALUE' = 0), number_value Float64, string_value String, bool_value UInt8))))
)
ENGINE = File('ProtobufSingle')
SETTINGS format_schema = 'recursive.proto:RecursiveMessage', input_format_protobuf_skip_fields_with_unsupported_types_in_schema_inference = 1
```

No more crashes, but looks like that expected behavior is to skip `payload` field entirely. Instead column definition is generated.

Issue can be reproduced on the latest release: `v24.8.6.70-lts`

**Comment by Algunenano** [comment]
> No more crashes, but looks like that expected behavior is to skip payload field entirely. 

It's hard to determine what to expect exactly in this case.

The struct is defined as:

```
message Struct {
  map<string, Value> fields = 1;
}

message Value {
  oneof kind {
    NullValue null_value = 1;
    double number_value = 2;
    string string_value = 3;
    bool bool_value = 4;
    Struct struct_value = 5;
    ListValue list_value = 6;
  }
}

enum NullValue {
  NULL_VALUE = 0;
}

message ListValue {
  repeated Value values = 1;
}

message Message {
  string event = 1
  google.protobuf.Struct payload = 2;
}

```

Technically everything contains recursion (Message -> Struct -> Value -> ListValue), but:
* Message is not recursive itself.
* Struct is not recursive itself.
* Value is not **directly** recursive itself.
* ListValue is the first point where we encounter a loop in the types, as it contain a Value.

So at what point to do consider skipping members? There are multiple options:
* If you skip any message that contains recursion. That means that Message should be empty too. Just because you put the boundary at google's types level does not mean CH knows or cares about your vs google's members.
* If you skip the first instance of recursion, then you remove the link between ListValue and Value, which is what's currently happening.

I'd argue that the second option is the one that provides greatest compatibility, since you can store anything except a value with a ListValue containing itself oneOf ListValue again.

**Comment by topofstack** [comment]
My opinion is that it will be a `partially` compatible field with no real world usage. From what I've seen users tend to use `google.protobuf.Struct` as a way to store JSON exclusively.  Otherwise using this type has no real benefits over using non WellKnownType message. But yeah, we have no way to distinguish.

I get your point, looks like current implementation is the most flexible one.
