### ISSUE TITLE
When to use KafkaConsumer2?

### ISSUE THREAD

**Issue by Tiaonmmn** [ClickHouse/ClickHouse#71571]
### Question

I can see there're files on src/Storages/Kafka/KafkaConsumer* andsrc/Storages/Kafka/KafkaConsumer2* .What's the difference between two Consumer? On latest ClickHouse version, when I use Kafka table engine to get data, what version is used?

**Comment by antaljanosbenjamin** [comment]
The gist of the [difference](https://github.com/ClickHouse/ClickHouse/blob/5f5b1ebe2684a74bea4f927d80a42e65d451c707/src/Storages/Kafka/StorageKafka2.h#L41-L42) is `StorageKafka2` (and everything in the same folder with postfix of `2`) is meant to use Keeper as main source of information about committed offsets instead of the Kakfa brokers. You can read more about the new, experimental way [here](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka#experimental-engine-to-store-committed-offsets-in-clickhouse-keeper).

> On latest ClickHouse version, when I use Kafka table engine to get data, what version is used?

If you specify `kafka_keeper_path`, then you use `KafkaConsumer2`, otherwise `KafkaConsumer`.
