### ISSUE TITLE
which is better between drop partition and delete?

### ISSUE THREAD

**Issue by qiaochaojie** [ClickHouse/ClickHouse#7192]
I want to update some day's data. I need to delete first.  But I find sometimes drop partition works, sometimes delete works.  which is better? How can I make sure the old data is deleted and new inserted data not be deleted?

**Comment by qiaochaojie** [comment]
the ch version is 19.7.3

**Comment by alex-krash** [comment]
@qiaochaojie , 
ALTER TABLE DROP PARTITION
1. Synchronous request
2. Deals only with the data, matching condition predicate (e.g. you have 1 year of data, partitioned by day, and want to drop a single day - only this day will be affected, but not others). No read is performed, just deletion.

ALTER TABLE ... DELETE
1. Asynchronous request (data manipulation is performed in background). In order to track progress, you need to query ```system.mutations``` table.
2. You may watch issue that part of day has been already processed, and half - not. It occur if your partition consists of multiple ```parts```.
3. This modification scans source data, modify, write. And is much more expensive in terms of resource usage.

Summary:
Use DROP PARTITION when possible. DELETE should be used in very rare cases (as of official documentation - to meet GDPR law conditions)

**Comment by qiaochaojie** [comment]
@alex-krash Thanks for your answer!  I have a question.  when I use the command like 'alter table xx on cluter drop partition ', it just returned immediately and did not report any error.  after a few minutes, I find the partition still exists.  It seems like not synchronous

**Comment by alex-krash** [comment]
@qiaochaojie , I've just tried dropping on cluster via ```clickhouse-client```, and it was synchronous.
What connector are you using?

**Comment by qiaochaojie** [comment]
@alex-krash I use clickhouse-client too. Below is the version information 

ClickHouse client version 19.7.3.1.
Connecting to 127.0.0.1:9000 as user default.
Connected to ClickHouse server version 19.7.3 revision 54419

**Comment by den-crane** [comment]
@qiaochaojie 
>  I have a question. when I use the command like 'alter table xx on cluter drop partition ', it just returned immediately and did not report any error. after a few minutes, I find the partition still exists. It seems like not synchronous

Such behavior is observed when one makes a mistake in partition name (partition does not exists). Then CH silently does nothing. Check the partition name with system.parts. And provide your `alter drop` example.

**Comment by qiaochaojie** [comment]
@den-crane Thanks for your answer. I drop partition with this 'alter table xx on cluster '{cluster}' drop partition(20191001)'.  The system.parts shows that partition field is just like '20191001'.

**Comment by qiaochaojie** [comment]
@den-crane  It seems like a bug.  When I use the command 'alter table xx drop partition(20191001)' , It works.  After that,  when I use 'alter table xx on cluster xx drop partition(p_20191001)' on other tables. it all works.  I do not know why

**Comment by alexey-milovidov** [comment]
@qua

**Comment by den-crane** [comment]
> Does `DROP PARTITION` propagate changes into the `MATERIALIZED VIEW`s?

No.  `MATERIALIZED VIEW` is an insert trigger and it  watches only inserts into base-table.

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://youtu.be/ckChUkC3Pns?t=9326

**Comment by tzaretskaya** [comment]
@alex-krash This question is of big relevance for me, too. Thank you for the answer!!
I need to reload data for a time period within a single day. If I drop a partition and insert the data it takes about 4-6 hours. My goal is lowest execution time. What about `DELETE IN PARTITION`? Is it more effective than `DROP PARTITION` coupled with insertion?
