### ISSUE TITLE
Raft communication issue between Keeper versions 24.8 and 24.9

### ISSUE THREAD

**Issue by IngaFeick** [ClickHouse/ClickHouse#72542]
**Describe what's wrong**

When doing a rolling upgrade from 24.8.5.115 to 24.9.x (or higher) in a cluster of 3 Clickhouse Keeper instances, the first node to be upgraded to the new version (24.9.x) fails to rejoin the cluster, while logging errors about Raft CRC mismatches and "wrong version number (SSL routines)". See the error logs at the end of this issue. 

We were able to reproduce this with all combinations of these versions:
- v24.9.1.3278-stable, v24.9.2.42-stable, v24.9.3.128-stable, v24.10.3.21-stable, 24.11.1.2557 for the node that gets upgraded ("new version") 
- v24.8.5.115-lts and v24.8.7.41-lts for the rest of the cluster ("old version")

The issue can be reproduced with this [simple docker setup](https://github.com/IngaFeick/clickhouse_issue). 

Raft config:
```xml
...
      <raft_configuration>
            <secure>true</secure>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper1</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper2</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper3</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
...
```
The full configuration can be found in the [demo project](https://github.com/IngaFeick/clickhouse_issue/blob/test_setup/configs/keeper_config1.xml).

**Does it reproduce on the most recent release?**

Yes, we also tested this for version 24.11.1.2557 (for the upgrading node, against a 24.8 cluster). 

**Expected behavior**

We'd expect not to see the Raft issues logged and for the upgraded node to join the keeper cluster. 

**Error message and/or stacktrace**

On the node that has the new version (`clickhouse-keeper3` in the test project):
```
2024.11.27 09:46:51.624272 [ 1 ] {} <Information> Application: Starting ClickHouse Keeper 24.9.3.128 (revision: 54492, git hash: 9a816c73dd4eb5f2ff994b1d9a57c5829f3e4811, build id: A9A66E90E64E24ED57A14DD646BCCF42890A11ED)
...
2024.11.27 09:46:51.682274 [ 1 ] {} <Debug> KeeperDispatcher: Server initialized, waiting for quorum
2024.11.27 09:46:52.983484 [ 47 ] {} <Error> RaftInstance: CRC mismatch: local calculation 80c715d9, from header 4e9b794d, message: &, message in bytes: 0x16 0x3 0x1 0x1 0x26 0x1 0x0 0x1 0x22 0x3 0x3 0x6a 0x73 0x9b 0x2b 0x45 0x1e 0xad 0xd2 0x34 0x7a 0x75 0x81 0x38 0xf8 0xf2 0xe7 0x3e 0xeb 0xe7 0xd3 0x2 0x4d 0x6c 0x10 0xbe 0x33 0xb9 0x84 0x82 0xf5 0x51 0xec 0x20 0xa2 0xf5 0x4d 0x79 0x9b 0x4e 0x16 0xb9 0x60 0x99 : received from socket ::ffff:172.23.0.14:40052
...
2024.11.27 09:48:12.248144 [ 43 ] {} <Error> RaftInstance: bad log data size in the header -1893392286, stop this session to protect further corruption
```

On the other nodes with the old versions (`clickhouse-keeper1` and `clickhouse-keeper2` in the test project): 
```
2024.11.27 12:14:02.894655 [ 44 ] {} <Error> RaftInstance: session 459 handshake with ::ffff:172.23.0.16:42346 failed: error 167772427, wrong version number (SSL routines)
2024.11.27 12:14:02.975671 [ 53 ] {} <Error> RaftInstance: failed SSL handshake with peer 3, clickhouse-keeper3:9234, error 104, Connection reset by peer
```

**Comment by aszlig** [comment]
Bisected to commit 3c47f3df4b11b6824aec87a9cffb51c97683cccb.

**Comment by antonio2368** [comment]
I can't believe it, I accidentally removed `asio_opts.enable_ssl_ = true;`... 
So SSL was completely disabled no matter what config and my tests were useless.
Thanks a lot for reporting this and creating such a good reproducer.
I'm working on a fix and hopefully will push it really soon.

**Comment by antonio2368** [comment]
I made a fix https://github.com/ClickHouse/ClickHouse/pull/72730
But still there are some things needed to do for a successful upgrade even with the fix.
Keeper previously ignored some advanced SSL configurations from config (not related to the bug reported here).
This means that for specific configurations new Keeper could expect some things that old Keeper simply cannot be configured to provide (e.g. `strict` verification mode).

First of all, there was a bug in your repro, `</openssl>` should go after `<client>` section in config for Keeper 1 and 2 (Keeper 3 was correct).

When you run your repro with Keeper 3 set to Keeper with the fix it can still fail because of `verificationMode` set to strict.
The communication works in a way where leader will be a client and try to connect to other peers (which act as servers).
In older Keeper's, only `relaxed` and `none` were supported.
So when a majority of Keepers pick a leader which is on older version it will try to connect to a Keeper with new version.
Because `relaxed` is set on old Keeper it will not send required certs, but new Keeper will fail because of missing cert because it's set to `strict`.
One way to solve it temporarily, is to configure `verificationMode` to `relaxed` until you update.
After that you should be able to use `strict`.

**Comment by IngaFeick** [comment]
Thanks @antonio2368 I will give it a try!
