### ISSUE TITLE
Block_number query with wrong result

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#72788]
**Describe the bug**
After a few inserts into a MergeTree table, A `count()` query on block number is wrong.

**How to reproduce**
Run Fiddle:
https://fiddle.clickhouse.com/6099695a-f825-43d3-9471-6075d40b918a

**Comment by CurtizJ** [comment]
It's expected behaviour. Columns `_block_number` returns the minimal block number in part if it is not materialized (with enabled setting `enable_block_number_column`). So, the result in that case is not deterministic and depends on current set of parts. If you enable setting `enable_block_number_column` for table or add query `SYSTEM STOP MERGES` the both queries will return 2.
