### ISSUE TITLE
Can I disable UDF unwrapping and how?

### ISSUE THREAD

**Issue by skiiddie** [ClickHouse/ClickHouse#72917]
### Question

Is there a way to disable unwrapping of functions into expressions?
So that when running `show create` like below or `select create_table_query from system.tables`
```
CREATE FUNCTION echo AS (argument) -> format('The value of the argument is "{}"', argument);
CREATE TABLE demo (column String DEFAULT echo('some')) ENGINE = Memory;
SHOW CREATE demo;
```
instead of this
```
CREATE TABLE default.demo
(
    `column` String DEFAULT format('The value of the argument is "{}"', 'some')
)
ENGINE = Memory
```
we could get this
```
CREATE TABLE default.demo
(
    `column` String DEFAULT echo('some')
)
ENGINE = Memory
```
[Link to playground](https://fiddle.clickhouse.com/8c9f5712-0f47-4e9f-867b-33cbaa54c7ad)

**Comment by den-crane** [comment]
No settings. The current behaviour is intentional.

./v22.12.1.1752-stable.md:* Substitute UDFs in `CREATE` query to avoid failures during loading at the startup. Additionally, UDFs can now be used as `DEFAULT` expressions for columns. [#43539](https://github.com/ClickHouse/ClickHouse/pull/43539) ([Antonio Andelic](https://github.com/antonio2368)).

**Comment by skiiddie** [comment]
Okay, thanks.
