### ISSUE TITLE
segfault after upgrading to 24.11.1.2557 - JSON columns?

### ISSUE THREAD

**Issue by jesse-triplewhale** [ClickHouse/ClickHouse#73042]
self-hosted. version: 24.11.1.2557

We upgraded from 24.10.1.2812 -> 24.11.1.2557, and got repeated seg faults on startup - attached: [v11.csv](https://github.com/user-attachments/files/18080581/v11.csv)

we restored the cluster by downgrading back to `24.10.1.2812`. After doing so, we got errors for the same table / part - but not a segfault this time:
```
<Error> aa7bd6dc-bea1-4074-be44-0baf704e8257::20241210_8557_8582_5 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 117. DB::Exception: Invalid version for Object structure serialization.: (while reading column data): (while reading from part /var/lib/clickhouse/store/aa7/aa7bd6dc-bea1-4074-be44-0baf704e8257/20241210_8557_8577_4/ in table sonic_system.pixel_custom_events (aa7bd6dc-bea1-4074-be44-0baf704e8257) located on disk default of type local, from mark 0 with max_rows_to_read = 902): While executing MergeTreeSequentialSource. (INCORRECT_DATA), Stack trace (when copying this message, always include the lines below):
```

We see this on different replicas for different tables, but it seems to only happen on JSON columns, so this issues seems to be with JSON

**Comment by Avogar** [comment]
Most likely the segfault happenned because of backward-incompatible change: https://github.com/ClickHouse/ClickHouse/pull/71182. It changed the escaping of JSON paths during files creation. And data with old escaping may be read incorrectly and lead to the corrupted data in memory that can lead to the crash. 

The downgrade led to `Invalid version for Object structure serialization` error because of forward-incompatible change in https://github.com/ClickHouse/ClickHouse/pull/70442 where the new serialization of JSON columns was implemented and set by default in 24.11. So after upgrade the new parts with new serialization were created. There is a setting `merge_tree_use_v1_object_and_dynamic_serialization` that prevents usage of the new serialization in new versions (it's also controlled by setting `compatibility`, we recommend using it during upgrade to keep the old settings values in such cases).

So I would say it's expected. The JSON feature was considered as experimental in 24.10 version, so breasking changes are expected. In 24.11 we marked it as beta, so no more breaking changes  will take place.

**Comment by Avogar** [comment]
If new broken parts were created by merge, maybe you can restore the data from the source parts if they weren't deleted

**Comment by Avogar** [comment]
This change was listed in the section `Experimental feature`.

**Comment by jesse-triplewhale** [comment]
Thank you @Avogar
