### ISSUE TITLE
There is no supertype for types UInt64, Int64 when using alter table update

### ISSUE THREAD

**Issue by skyfirezju** [ClickHouse/ClickHouse#7306]
when I used sql like `ALTER TABLE XXX update cost = ? , traffic = ? where  1` 
, and I also prepare sql ,  and cost, traffic type is `Nullable(Int64)`,  unfortunately get such error below:

`code: 386, message: There is no supertype for types UInt64, Int64 because some of them are signed integers and some are unsigned integers, but there is no signed integer type, that can exactly represent all required unsigned integer values`

I also found error exists  when exceed Int32  max limit = 2147483647 , but I don't know why?

**Comment by filimonov** [comment]
Can you please provide full example (i.e. minimal table create statement + some failing alter)?

**Comment by silence44** [comment]
@filimonov I have same issue and here is steps to reproduce.

CREATE TABLE mydb.test3 (\`id\` UInt64, \`i\` Int64) ENGINE = MergeTree() PRIMARY KEY id ORDER BY id SETTINGS index_granularity = 8192;

INSERT INTO mydb.test3 VALUES (1, 5756242266);

ALTER TABLE mydb.test3 UPDATE i = 5756242267 WHERE id =1;

Then I got error: Code: 386. DB::Exception: Received from clickhouse_server:9000. DB::Exception: There is no supertype for types UInt64, Int64 because some of them are signed integers and some are unsigned integers, but there is no signed integer type, that can exactly represent all required unsigned integer values. 

As I read from documentation ranges are:
Int32 - [ -2147483648 : 2147483647 ]
Int64 - [ -9223372036854775808 : 9223372036854775807 ]

So my value of "i" is more the int32 but still less than int64.

**Comment by filimonov** [comment]
Can you try:
```
ALTER TABLE mydb.test3 UPDATE i = toInt64(5756242267) WHERE id =1
```

**Comment by silence44** [comment]
Hello @filimonov . Query that you provided works. 
But that is not a solution for me, because I have to store all column types and do casting on every query, handle column type changes etc.

Update behavior have to be similar to insert in this case, but currently it is different. 
May you please label this issue as a bug?

**Comment by filimonov** [comment]
Related issues: #4165 #3746 #7442 #6778

**Comment by alexey-milovidov** [comment]
We should apply type conversion automatically.
