### ISSUE TITLE
Efficiently Handling Null or Empty Checks for Nullable and Array Columns in ClickHouse

### ISSUE THREAD

**Issue by minQZ** [ClickHouse/ClickHouse#73166]
### Question

Hello,

I have encountered a scenario where I need to determine whether a column is either:
* Nullable and check if it's NULL.
* Array and check if it's empty.

To handle this, I wrote the following SQL condition:
`if(startsWith(toTypeName(vtlVar), 'Array'), empty(vtlVar), isNull(vtlVar))`

This works functionally as expected, but I have a few concerns and questions about its performance and potential optimization:

1. Performance Impact:
Does repeatedly calling toTypeName() and startsWith() introduce any significant overhead, especially on large datasets?
Are there any internal optimizations in ClickHouse that mitigate the cost of type detection at runtime?

2. Recommended Best Practices:
Is there a better approach to achieve the same result without relying on toTypeName()?

3. Future Improvements:
Are there any plans to introduce functions like isNullOrEmpty() to simplify this type of check?

Any insights or suggestions would be greatly appreciated. If additional context or a sample dataset is needed, I’d be happy to provide it.

Thank you for your help!

**Comment by yariks5s** [comment]
> 1. Performance Impact

`toTypeName()` and `startsWith()` are both quite lightweight operations, but, of course, they are executed in the runtime. When dealing with large datasets and billions of rows, even these small operations could contribute some overhead.

> 2. Recommended Best Practices

The best thing you can do is to change the schema so that there are no nullable arrays. From my knowledge, there are no ways to do it more efficiently, but you can try to do it like this:

``` SQL
CASE 
    WHEN empty(vtlVar) THEN 1
    ELSE (CASE WHEN isNull(vtlVar) THEN 1 ELSE 0 END)
END
```

I'm not sure if it will help, but worth trying.

> 3. Future Improvements

Yes, it's a good idea to add something like `isNullOrEmpty()`, I've created an issue about it.
