### ISSUE TITLE
How the index file works

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#7473]
I want to know How index work except for primary key.

When the tables is created, data is sorted by primary key. and primary.idx file is created which has information for granules.

so, when I send a select query with using primary key, the clickhouse find granules in the primary.idx and use (column).mrk2 to find data in the (column).bin. Do I understand right?

Then......

When I add an index using an alter table query, skp_idx_(index_name).idx and skp_idx_(index_name).mrk2 files are created. what roles of these files??

And I have to use 'optimize final' for using index right away. 

However, These index files(.idx and .mrks) is created a little later. but I can use a new index by the way.

How these works??

**Comment by den-crane** [comment]
Imagine you've created a table 
create table T(A Int, B Int) order by A
insert into T values(1,1)    --- first part no skip index
alter table add index min_max(B);
insert into T values(1,2)   --- second part with skip index with B_min_max=(2,2)

And you run a query `select * from T where B>10000000`
Ch unable to use primary index to filter because there is no conditions on column A.
Then CH will scan 2 parts. The first part does not have index so CH will read column B and checks condition `B>10000000` in contrary in the second CH will use B_min_max=(2,2) index and will skip to read column B because obviously this part does not have rows with  `B>10000000`.
Later a merge process will merge these 2 parts to a new one with skip index B_min_max=(1,2).

**Comment by chu1070y** [comment]
Thanks for explanation of How index works.

Could you tell me more details about the role of these files individually ((index_name).idx, (index_name).mrks)?

**Comment by chu1070y** [comment]
Thanks for explanation of How index works.

Could you tell me more details about the role of these files individually ((index_name).idx, (index_name).mrks)?
