### ISSUE TITLE
Do not store ZooKeeperPtr in StorageReplicatedMergeTree

### ISSUE THREAD

**Issue by janplus** [ClickHouse/ClickHouse#7536]
**Use case**

Hi team,

Currently `StorageReplicatedMergeTree` store `ZooKeeperPtr` to decrease race condition on `Context::getZooKeeper()`, and re-new the stored `ZooKeeperPtr` in `ReplicatedMergeTreeRestartingThread`. But when there is thousand ReplicatedMergeTree tables, the re-new will delay due to schedule, since one `ReplicatedMergeTreeRestartingThread` started new session for zookeeper, other tables still need wait for its own ReplicatedMergeTreeRestartingThread to be scheduled. During the gap, the alter query will fail on `Session expired` exception.

**Describe the solution you'd like**

If we do not store the `ZooKeeperPtr` in `StorageReplicatedMergeTree`, and directly use the `Context::getZooKeeper()`, the race condition may increase. So we could change the `zookeeper_mutex` from `std::mutex` to `std::shared_mutex`, and change the definition of `Context::getZooKeeper()` to `Context::getZooKeeper(bool reNew = true)`. Then we could only require `std::shared_lock` when call `storage.getZooKeeper()`, and require `std::lock_guard` in `ReplicatedMergeTreeRestartingThread`. Therefore,  all tables will get the new session zookeeper if one ReplicatedMergeTreeRestartingThread call startNewSession, and the race condition does not increase.

**Comment by janplus** [comment]
@blinkov @alexey-milovidov

**Comment by Akazz** [comment]
Hi @janplus,
Your initial concern is understandable and we might need to look into it more thoroughly.

And yet the matter of question is a bit more complicated than it may seem. Current implementation suggests that instance of `StorageReplicatedMergeTree` needs to react on every event of ZK session loss with calling `ReplicatedMergeTreeRestartingThread::partialShutdown()`. This means that your suggested solution would not work as expected.

As to addressing the lock contention problem that you also mentioned, `std::shared_mutex` needs to be used with care because of the possible writer starvation problem and thus a more fine grained locking scheme might be needed.

**Comment by Akazz** [comment]
And of course it is important to investigate the reasons for your Zookeeper sessions timing out, as there can be a number of those:
 - Poor (overloaded) network connection
 - Insufficient CPU resources or high memory pressure (to which ZK is known to be very susceptible)
 - You might as well simply try to raise the ZK session timeout setting

**Comment by janplus** [comment]
@Akazz Thanks for your advise, I will dig this problem and look into it more thoroughly.

**Comment by alexey-milovidov** [comment]
We cannot start using new ZooKeeper connection without full reinitialization of the state in memory (it is what RestartingThread is doing). Whenever ZooKeeper session has expired we should assume that our knowledge about anything from ZooKeeper is obsolete.

Maybe in some cases it isn't required but it's difficult to figure out these cases.
