### ISSUE TITLE
geo pointInEllipses()  function translation Chinese error

### ISSUE THREAD

**Issue by wangyiedge** [ClickHouse/ClickHouse#7566]
error location：
https://clickhouse.yandex/docs/zh/query_language/functions/geo/#pointinellipses

In the definition of ellipse axis here, the unit is meter, which is wrong. There is no unit defined in the English document, but there is a description "coordinates are geometric in the Cartesian coordinate system", so the actual unit should be degree.This will cause very serious misleading. Please correct it as soon as possible.

此处对椭圆轴的定义中，指明单位为米，这是错误的。英文文档虽然没有明确说明单位，但是定义中有说明“ Coordinates are geometric in the Cartesian coordinate system”（中文文档中没有），所以单位应该是度。实际测试也是如此。这会造成非常严重的误导，请尽快改正。

**Comment by alexey-milovidov** [comment]
Coordinates don't have any unit. You can pass meters or degrees as long as all coordinates have the same unit and if you're Ok with assumption of planar space.

**Comment by zhang2014** [comment]
This is because the update of the English document is not timely synchronized with the Zh document, I will try to synchronize them immediately(this is not difficult, because we have already had the [diff script tool](https://github.com/ClickHouse/ClickHouse/pull/7498), I think the update synchronization should be more and more frequent in the future :) )
