### ISSUE TITLE
SHOW TABLES ON CLUSTER

### ISSUE THREAD

**Issue by mobydi** [ClickHouse/ClickHouse#7571]
**Use case**
I would like to execute SHOW TABLES ON CLUSTER to see tables on remote machines

I have a big cluster and in case of issue would like to have brief pictures of tables in database

**Comment by alex-krash** [comment]
```
SELECT hostName(), database, name FROM cluster('your_cluster', system.tables)
```

**Comment by alexey-milovidov** [comment]
`SHOW TABLES ON CLUSTER` is questionable, because it's expected that the query with ON CLUSTER modifier will return the dataset of the same structure as without ON CLUSTER.

But to look for tables on cluster, we have to add hostname field to differentiate hosts.

Another concern is that currently all ON CLUSTER queries are intended to perform some modifying actions on cluster, not for informational queries.

**Comment by tfrokt** [comment]
> SELECT hostName(), database, name FROM cluster('your_cluster', system.tables)

This only shows tables on the current machine.
