### ISSUE TITLE
bugs everyday ....

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7830]
why numeric types can't join?
I think it's  unreasonable.

```
Received exception from server (version 19.17.2):
Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: Type mismatch of columns to JOIN by: path_direction Int8 at left, t2.path_direction UInt8 at right.

0 rows in set. Elapsed: 0.011 sec.
```

**Comment by den-crane** [comment]
Because CH has a strong typing. 

select * from (select toInt8(1) a) t join (select toUInt8(1) b) t1 on a=b;
DB::Exception: Type mismatch of columns to JOIN by: a Int8 at left, b UInt8 at right.

select * from (select toInt8(1) a) t join (select toUInt8(1) b) t1 on **toUInt8**(a)=b
┌─a─┬─b─┐
│ 1 │ 1 │
└───┴───┘
1 rows in set. Elapsed: 0.002 sec.

**Comment by Tasselmi** [comment]
> Because CH has a strong typing.
> 
> select * from (select toInt8(1) a) t join (select toUInt8(1) b) t1 on a=b;
> DB::Exception: Type mismatch of columns to JOIN by: a Int8 at left, b UInt8 at right.
> 
> select * from (select toInt8(1) a) t join (select toUInt8(1) b) t1 on **toUInt8**(a)=b
> ┌─a─┬─b─┐
> │ 1 │ 1 │
> └───┴───┘
> 1 rows in set. Elapsed: 0.002 sec.

but actually, 0L = 0 INT
numeric types are defined by human beings or computer bits(8/16/32/64).
Numeric strong types I think it's unreasonable.

**Comment by den-crane** [comment]
We are not humans.

**Comment by Tasselmi** [comment]
> We are not humans.

who are you ? ...............orz.

**Comment by den-crane** [comment]
Software developers who like strong typing.
