### ISSUE TITLE
Kafka Engine new design proposal

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#7837]
The current state of Kafka Engine performance and number of bugs suggest to make some crucial changes in code and architecture.

The addressed problems are:
1. Low performance of consumption.
2. No exacly-once guarantee.

### Exactly-once

For the exactly-once support it's better to have as low number of destinations as possible.
The single originating destination is the best choice. Let's integrate it into grammar:

`CREATE STREAM kafka_stream TO another_table ENGINE Kafka SETTINGS … ;`

If another table has columns with the names of virtual columns from Kafka Engine they will be filled automatically. All other columns are parsed according to the setting `kafka_format` value. Depending on the format the columns are read using names or position.

To temporarily stop consumption the stream may be detached.

### Performance

For better performance it's better to consume messages in a separate thread pool (without rescheduled tasks and predefined number of threads) without any limits, like maximum block size, time, etc.

### Insertion into Kafka

Another change to the grammar:

`CREATE STREAM kafka_stream FROM another_table ENGINE Kafka SETTINGS … ;`

This should work like a materialized view, but in async way without blocking inserts. It's meaningful for other possible streams in the future where settings of the "producers" and "consumers" may differ. And it looks meaningless to be able to produce and consume from the same topic simultaneously.
Also we should add support for insertion into multiple topics at once. And add setting to customize the number of rows per message.

### Obsolete stuff

1. The setting `kafka_row_delimiter`.
2. SELECT/INSERT Kafka table directly.

**Comment by josepowera** [comment]
Just a comment regarding "as low number of destinations as possible" for Exactly-Once

There should be a way to send to multiple destinations at the end (using MV, cascded MV or something similar) as in issue #6430

**Comment by abyss7** [comment]
> Just a comment regarding "as low number of destinations as possible" for Exactly-Once
> 
> There should be a way to send to multiple destinations at the end (using MV, cascded MV or something similar) as in issue #6430

This should work out-of-the-box, using MVs on `another_table` from example.

**Comment by yuzhichang** [comment]
FYI. https://github.com/edenhill/librdkafka/pull/2377 (released in librdkafka v1.2.0) provides `transaction aware consumer`.

**Comment by josepowera** [comment]
With removing of kafka_row_delimiter you could probably also remove "1 kafka message= multiple CH rows" and go to "1 kafka message= 1 CH row".  Makes kafka offsets etc simpler.

**Comment by filimonov** [comment]
> No exacly-once guarantee.

Kafka by default can work only in 'at-least-once' or 'at-most-once' models. To have guarantees you need to use EOS semantics (producer also need to support that on it's end).

Support for EOS semantics is still in progress on rdkafka side. 

The main source of duplicates right now - is lack of processing of consumer group rebalance (sync commit on group revocation is needed).

> CREATE STREAM kafka_stream TO another_table ENGINE Kafka SETTINGS … ;
> 
> If another table has columns with the names of virtual columns from Kafka Engine they will be filled automatically. All other columns are parsed according to the setting kafka_format value. Depending on the format the columns are read using names or position.

Not clear how to do migrations. Let's say you want to add one extra column to target stable (because it will start appearing in the target stream at the end of the day). It will try to parse it out? Will it accept DEFAULT expression from the target table as optional in kafka stream?

> For better performance it's better to consume messages in a separate thread pool (without rescheduled tasks and predefined number of threads) without any limits, like maximum block size, time, etc.

I think you can still parse / insert in mutliple threads, while consuming itself is usually give very good performance even when consuming using single rdkafka consumer (it uses background thread).

> Insertion into Kafka
> Another change to the grammar:
> CREATE STREAM kafka_stream FROM another_table ENGINE Kafka SETTINGS … ;

It will be more cumbersome when we will need to strem only few columns of many, hard to to some calculations / undict some ids / apply extra conditions (maybe still can be done using table with Null engine in the middle)

> This should work like a materialized view, but in async way without blocking inserts. 

That would be cool part, but how can that work? does it mean it will collect everything in memory? If yes - what with OOM situations and server restarts? If no - it should store data somewhere (double write), or use MergeTree block numbers (but that mean it will not work with non-MergeTree engines, and mergetree data can also be cleared).

**Comment by filimonov** [comment]
> With removing of kafka_row_delimiter you could probably also remove "1 kafka message = possible multiple CH rows" and go to "1 kafka message= 1 CH row". Makes kafka offsets etc simpler.

One size does not suit all. It should support both options (and is already support that), and user can choose.
