### ISSUE TITLE
(RFC) Engine = DistributedSet / DistributedJoin.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#7906]
Ability to access sharded Engine=Set / Engine=Join.

Distributed over Set / over Join? DHT? Other ideas?

**Comment by smirnov-vs** [comment]
Hello.
I have two distributed tables and I need to JOIN them without GLOBAL, cause data is sharded by same key.
So I wrote something like
```
SELECT * FROM
(
    SELECT id, * FROM table1 WHERE <...>
)
ALL LEFT JOIN
(
    SELECT id, * FROM table2_local WHERE <...>
)
USING (id)
```
table1 is Distrubuted, table2 is local sharded table
In this query clickhouse doesn't understand me. I want to make distributed query but it doesn't work because distributed table is in subquery. So I have only one part of full result.
On other hand I need to filter both tables before JOIN. 
Other way is to filter first table after JOIN but this is very long query.

Can this feature help with this situation in future or there is some workaround already?
