### ISSUE TITLE
merge cycle

### ISSUE THREAD

**Issue by JongMinP** [ClickHouse/ClickHouse#7952]
I wonder if there is a merge cycle in the MergeTree product.
I wonder how the Merge cycle is set if it exists.

**Comment by filimonov** [comment]
ClickHouse do background merges all the time. There is background merge pool, It periodically wakes up to check if something should be merged. If it has nothing to do it can sleep a bit longer. 

It uses some heuristics to peek the parts to be merged, it depends on part sizes, currently executed merges, number of the parts.

**Comment by JongMinP** [comment]
It periodically wakes up to check if something should be merged
=>I wonder something    example) insert?,  event?

**Comment by kaijianding** [comment]
@filimonov I found duplicates in my ReplacingMergeTree table are not removed after 1 day, I have to do OPTIMIZE FINAL to remove duplicates. Any idea why background merge is not happening? My version is 19.7.3

**Comment by den-crane** [comment]
@kaijianding 

https://clickhouse.yandex/docs/en/operations/table_engines/replacingmergetree/

Data deduplication occurs only during a merge. Merging occurs in the background at an unknown time, so you can't plan for it.
**Some of the data may remain unprocessed.** Although you can run an unscheduled merge using the OPTIMIZE query, don't count on using it, because the OPTIMIZE query will read and write a large amount of data.

**Comment by kaijianding** [comment]
@den-crane I get that merging occurs at an unknown time, but it doesn't happen for a very long time(maybe for one day), any idea to make it happen more frequently?

**Comment by den-crane** [comment]
@kaijianding 
>but it doesn't happen for a very long time(maybe for one day)

it could never happen for that partition. Especially if no more inserts in that partition.

>any idea to make it happen more frequently

No such feature. Try run optimize.
