### ISSUE TITLE
groupBitmap incorrect result

### ISSUE THREAD

**Issue by kaijianding** [ClickHouse/ClickHouse#7962]
**Describe the bug or unexpected behaviour**
id is UInt64 column
groupBitmap(id) is not the same as count distinct(id)

**How to reproduce**
* Which ClickHouse server version to use
19.17.4
* Reproduce steps
```sql
create table test(id UInt64) Engine=MergeTree() ORDER BY tuple() SETTINGS index_granularity = 8192
```

then insert 200000 random numbers:
generate random numbers in shell with multiple threads
```shell
#/bin/bash
all_num=20
thread_num=20
a=$(date +%H%M%S)
# mkfifo
touch tempfile
tempfifo="my_temp_fifo"
mkfifo ${tempfifo}
exec 6<>${tempfifo}
rm -f ${tempfifo}
for ((i=1;i<=${thread_num};i++))
do
{
    echo
}
done >&6
#
for num in `seq 1 ${all_num}`
do
{
    read -u6
    {
        for i in {1..10000}
        do
          echo `date +%s%N` >> tempfile
        done
        echo "" >&6
    } &
}
done
wait
exec 6>&-
b=$(date +%H%M%S)
echo -e "startTime:\t$a"
echo -e "endTime:\t$b"
```

insert into table test
```shell
cat tempfile| ../bin/clickhouse-client --port 9000 --query="INSERT INTO test FORMAT CSV"
```

* Queries to run that lead to unexpected result

select count(distinct id) from test;
200000

select groupBitmap(id) from test;
199996
select length(bitmapToArray(groupBitmapState(id))) from test;
199996

This difference is more significant in my real scenario, it leads to 1~8% error

It seems some numbers are lost in the bitmap

**Expected behavior**
groupBitmap(id) == count distinct(id)

**Comment by filimonov** [comment]
Hm.

AFAIK roaring bitmap support only 32bit numbers.
https://github.com/RoaringBitmap/roaring/issues/136

> generate random numbers in shell with multiple threads
cool script. :) bit in clickhouse you can do much simpler:

```
create table test Engine=MergeTree() ORDER BY tuple() SETTINGS index_granularity = 8192 as select rand64() as id from numbers_mt(200000);

SELECT countDistinct(id) FROM test;
200000

select groupBitmap(id) from test;
199995

select count(distinct toUInt32(id)) from test;
199995
```

@andyyzh can you comment on that? Why didn't we forbid to use roaring bitmaps against 64bit numbers?

**Comment by kaijianding** [comment]
@filimonov It would be wonderful if the 64-bit bitmap is supported, it would be very useful for a scenario like order_id, user_id, product_id

**Comment by andyyzh** [comment]
Clickhouse use the C language version of RoaringBitmap/CRoaring, which use 32-bit integer,
The 64 bit version of CPP is to wrap two 32-bit CRoaring into 64 bit implementation instead of long type. The performance is not good. [roaring64map.hh](https://github.com/RoaringBitmap/CRoaring/blob/master/cpp/roaring64map.hh)

**Comment by alexey-milovidov** [comment]
CC @sundy-li

**Comment by sundy-li** [comment]
Hmm, just notice this issue.

To add `64-bit bitmap` support is easy,  but I do agree with @andyyzh, I don't think it's needed. 
Because when you need `64-bit bitmap`,  mostly you are using bitmap the wrong way.

> What's the main reason for `roaring bitmap` performances better than bitsets?  

 It's better Compression for the bitmap.

> Is `roaring bitmap` always getting high compression ratio？  

Not yet. See this [script](https://gist.github.com/sundy-li/8acddd5c3fa97167477732f7d5a06b65), It takes `200MB` for storing 100million uint32, I can't image how much memory it will take for uint64.


So, I always suggest people use bitmap following these rules.

- Don't put random numbers into the bitmap, please use a dictionary to generate sequence ids for better compression.
- Sharding the data by the bitmap key, such as `userid`,  this will significantly improve the performance combining with `distributed_group_by_no_merge`.
- If your sequence ids overflow `4294967295`, congratulations, you are serving a great company that covers half of world's population. And I also think `64-bit bitmap` is not the problem, you can use another UInt8 column to store the extra bit.

```
select groupBitmapOr(uv)  from table where bit_33 = 0 union all select groupBitmapOr(uv) from table where bit_33 = 1;
```
