### ISSUE TITLE
How to limit the memory usage but still get the query running?

### ISSUE THREAD

**Issue by WesleyBatista** [ClickHouse/ClickHouse#8067]
Hello community! first of all, congrats for the great work!

___
_I find incredible the pace of releases ClickHouse has, and I think this is possible thanks to the great effort of the community contributions._
___

I have two queries issuers at the moment that are, time to time (not always), executing queries on clickhouse "in parallel", making one or the other get lower performance, and requiring from us to increase the timeout of the queries.

I would like to prioritize queries from **issuer 1**, and for that we thought about limiting the resource for the other queries from **issuer 2**. In other words, I would like to **slow down the queries from issuer 2 in order to get issuer 1 queries faster**.

According to the [documentation](https://clickhouse.yandex/docs/en/query_language/select/#select-group-by-in-external-memory):
> You can enable dumping temporary data to the disk to restrict memory usage during GROUP BY. The max_bytes_before_external_group_by setting determines the threshold RAM consumption for dumping GROUP BY temporary data to the file system

these would be the relevant settings to tweak and accomplish this:
- [max_bytes_before_external_group_by](https://clickhouse.yandex/docs/en/operations/settings/query_complexity/#settings-max_bytes_before_external_group_by)
- [max_memory_usage](https://clickhouse.yandex/docs/en/operations/settings/query_complexity/#settings_max_memory_usage)

Happens that whenever the query reaches the thresholds it gives me this error:
```
clickhouse_driver.errors.ServerException: Code: 241.
DB::Exception: Memory limit (for query) exceeded: would use 300.50 MiB (attempt to allocate chunk of 4199420 bytes), maximum: 298.02 MiB. Stack trace:
```

then I increase a bit the memory and the same error again:
```
clickhouse_driver.errors.ServerException: Code: 241.
DB::Exception: Memory limit (for query) exceeded: would use 312.69 MiB (attempt to allocate chunk of 4383380 bytes), maximum: 309.94 MiB. Stack trace:
```

_My clickhouse version is **19.13.3**. I wrote a very dumb python script to help me to test the configurations [here](https://gist.github.com/WesleyBatista/6fee9afeadf7535925a3a957271b9600). Hope this helps me to get some help :sweat:_

**Comment by den-crane** [comment]
How much memory your server has?


'max_memory_usage': 312500000, 
'max_bytes_before_external_group_by': 156250000,

would use 300.50 MiB  / maximum: 298.02 MiB
would use 312.69 MiB / maximum: 309.94 MiB

I don't see any contradiction here. max_memory_usage is a limit. 
A query failed because it needs more memory than the limit allow.

309.94 MiB -- it's rather small numbers for CH because it can run e.g. 48 streams which allocate 2MB buffers each to read a data and uncompress. `Order by` and `JOINs` also like memory. 
My typical queries use ~25 GB RAM, Joins with large tables use 150GB RAM.

**Comment by WesleyBatista** [comment]
> How much memory your server has?

**20 GB**

@den-crane, thank you for your time :)

The examples were to show that the memory control feels like not working, and when it does it works by throwing error instead of keeping the query running with limited resources.
For instance, the same query runs if I provide these settings:

| max_memory_usage | max_bytes_before_external_group_by | elapsed_time |
|------------------|------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|
| 20000000000 | 10000000000 | 26.30159616 |
| 10000000000 | 5000000000 | 33.75502014 |
| 5000000000 | 2500000000 | 33.19518733 |
| 2500000000 | 1250000000 | 31.55387759 |
| 1250000000 | 625000000 | 32.08035469 |
| 625000000 | 312500000 | 30.15583706 |
| 312500000 | 156250000 | DB::Exception: Memory limit (for query) exceeded: would use 300.50 MiB (attempt to allocate chunk of 4199420 bytes), maximum: 298.02 MiB. Stack trace: |

No matter the settings I provide _(with exception of the first)_, it finishes in about the same time.

As I said, the available RAM is 20 GB, and it is like if the query would consume something up to 625 MB anyway (either limiting or not), and when we provide some lower limits it fails. 

I would like to find a way of make the query run with limited RAM (probably at cost of longer runtime, but it would be OK). Would this be possible?

**Comment by den-crane** [comment]
>works by throwing error

Yes it's by design. max_memory_usage -- it is a limiter. It just throws an error to a client. It does NOT reduce memory usage.

>I would like to find a way of make the query run with 
>limited RAM (probably at cost of longer runtime, 
>but it would be OK). Would this be possible?

No it's not possible. You can reduce memory usage by max_bytes_before_external_group_by / max_bytes_before_external_sort/max_block_size to some point like 4GB, but there is no way to reduce memory usage any query or reduce memory usage lower than some lowest point like 1-2GB.

**Comment by windylcx** [comment]
> than some lowest point like 1-2GB.

but if   there is a way to  reduce memory usage lower than 100GB?   because the node's physical RAM is 128G 
and i don't want to throw an error but to keep the query running,even it will cost a long way?

**Comment by bakwc** [comment]
I faced a similar issue running a super simple `SELECT * FROM ... WHERE *` without any joins / etc.
The solution was to reduce `max_block_size` option (from default 65K to 16K).
The problem was following:
 * Query was executed in parallel by multiple threads (by default most of queries runs in parallel in CH)
 * Each thread consumed a 2Gb of memory, so in total it was ±40Gb of memory.
