### ISSUE TITLE
CREATE TEMPORARY TABLE doesn't work with on cluster

### ISSUE THREAD

**Issue by Ubusubus** [ClickHouse/ClickHouse#8095]
**Describe the bug or unexpected behaviour**
CREATE TEMPORARY TABLE doesn't work with on cluster statement

**How to reproduce**
```
curl -X POST --silent 'http://<host>:8123/?session_id=1234&session_timeout=3600&user=<user>&password=<pass>' --data 'CREATE TEMPORARY TABLE if not exists temp123456 on cluster <cluster> ( rdid String )'
Code: 442, e.displayText() = DB::Exception: There was an error on [<another_host_from_cluster>:9000]: Code: 442, e.displayText() = DB::Exception: Temporary tables cannot be inside a database. You should not specify a database for a temporary table. (version 19.17.5.18 (official build)) (version 19.17.5.18 (official build))
```
All is ok, if you CREATE TABLE on one host:
```
curl -X POST --silent 'http://<host>:8123/?session_id=1234&session_timeout=3600&user=<user>&password=<pass>' --data 'CREATE TEMPORARY TABLE if not exists temp123456 ( rdid String )'
curl -X POST --silent 'http://<host>:8123/?session_id=1234&session_timeout=3600&user=<user>&password=<pass>' --data 'SHOW TEMPORARY TABLES'
temp123456
```
* Which ClickHouse server version to use
19.17.5.18
But we got same error with 19.13.7.57

**Comment by filimonov** [comment]
It is by design. 
https://clickhouse.yandex/docs/en/query_language/create/#temporary-tables

TEMPORARY TABLES live only in the session. Distributed DDL queries are executed remotely using another session, so anyway you will not be able to see them.  

You can just creare Engine=Memory tables with unique name. 

At the same time the error message could be improved.

**Comment by Ubusubus** [comment]
Ok.
I think it's good to fix documentation for such things.
https://github.com/ClickHouse/ClickHouse/pull/8114
