### ISSUE TITLE
The bar() function doesn't add up spaces to align to the width

### ISSUE THREAD

**Issue by hatarist** [ClickHouse/ClickHouse#828]
```
:) SELECT bar(3, 0, 10, 10) AS bar_

┌─bar_─┐
│ ███  │
└──────┘

:) SELECT bar(3, 0, 10, 10) AS bar_ FORMAT CSV

"███"
```

I suppose it should fill up the rest of the width with whitespaces?

I'd expect that:
```
:) SELECT bar(3, 0, 10, 10) AS bar_

┌─bar_────────┐
│ ███         │
└─────────────┘
```

**Comment by alexey-milovidov** [comment]
It was not supposed.
But we could add padding.

PS. Sometimes I specify max width greater than needed, 
but default (PrettyCompact) format displays everything aligned by actual maximum,
so lack of padding has its use.

**Comment by cipriancraciun** [comment]
I think the bar function is very useful for quickly visualizing numerical data.

However I think just adding "space padding" is not enough, as that covers only one use-case, meanwhile I think `bar` has the following separate use-cases:
* used as is without any padding is OK for exporting in machine readable format JSON, TSV (but meant for import not viewing);
* used with padding (perhaps spaces) is best for directly viewing the query result on a terminal;  even in machine readable format (TSV), if the column is set first it yields a clear indication;
* used with padding that is not space, like for example lines or dots, could give the impression of a progress bar, thus adding to the visual impact;
* used in reverse mode (but with padding to the left and right), could allow one to juxtapose two columns A/B, like for example `____# | ###___` or reversed like `###___ | ____#` to quickly compare them;
* perhaps even a "centered" variant (with padding) might be of some use in some fields;
* if the actual value is less or above the specified min and max, a special character might be added, like `<____` or `####>` to indicate out of range;
* perhaps add a variant that just draws a line where the value would be, thus allowing one to create a "vertical line graph", i.e. `__|____ `, and the following one might be `_|_____`, etc.  (replace `_` with spaces, as I was forced by GitHub's markup language to use it instead of space);

Anyway, even as it is it's an invaluable asset.

**Comment by alexey-milovidov** [comment]
You did not even mention support for negative values :)
And adding color support with ANSI terminal escape sequences.

... but I don't want to make this function to have dozen parameters.

**Comment by alexey-milovidov** [comment]
This task is easy, but no one did care to implement it.
