### ISSUE TITLE
mysql_port enabled required certificates?

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#8302]
```
MySQLHandlerFactory: Failed to read RSA keys. Error: Code: 76, e.displayText() = DB::Exception: Cannot open certificate file: /etc/clickhouse-server/server.crt. (version 19.18.1.1739 (official build))
```

**Comment by yurriy** [comment]
The server generates keys if it cannot read them, thus certificates are not required.
This warning is supposed to help in case if user has provided a client with a server key, and server has generated other keys. In this case the server won't be able to decrypt a password.
I'll remove this warning on startup, since we can print it during authentication, only when this particular case happens.

**Comment by blinkov** [comment]
@filimonov, do you have any further questions?
