### ISSUE TITLE
Confused about materialized table

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#8347]
I create a materialized table like 
`CREATE MATERIALIZED VIEW db.table ENGINE = MergeTree() PARTITION BY day ORDER BY name
AS SELECT name,age,day FROM db.origin-table`
Here I have two question:
Q1: When I do a insert,is the insert operation is the multiple insert(insert into origin-table && materialized table both) or insert into origin-table only,select from origin-table and insert into materialized table later?
Q2: After I create the materialized table,if I need to add a column 'zone' to origin-table and materialized table both,is there a way to change the materialized table syntax `AS SELECT name,age,day FROM db.origin-table` to `AS SELECT name,age,day,zone FROM db.origin-table`

**Comment by nvartolomei** [comment]
1. When you insert into `db.origin-table` ClickHouse will automatically apply the SELECT statement from MV over the same batch of data and write synchronously data to `db.table`. By default this is sequential, but you can enable `parallel_view_processing` setting (Enables pushing to attached views concurrently instead of sequentially.) for parallel writes.

From docs:

> The execution of ALTER queries on materialized views has not been fully developed, so they might be inconvenient. If the materialized view uses the construction TO [db.]name, you can DETACH the view, run ALTER for the target table, and then ATTACH the previously detached (DETACH) view.
— https://clickhouse.yandex/docs/en/query_language/create/#create-view

I suggest you do the following:

1. Create MV using explicit `TO` syntax.

```sql
CREATE TALBE db.table (name,age,day...) ENGINE = MergeTree() PARTITION BY day ORDER BY name;

CREATE MATERIALIZED VIEW db.table_view TO db.table
AS SELECT name,age,day FROM db.origin-table;
```

2. When you want to alter

```sql
ALTER db.origin-table ADD COLUMN ...
DROP db.table_view; -- we drop the view which in this case holds no data (if it is created with TO) but is just a link/pipe from origin-table to table
ALTER db.table ADD COLUMN ...

--- create new MV definition
CREATE MATERIALIZED VIEW db.table_view TO db.table
AS SELECT name,age,day,zone FROM db.origin-table;
```

One caveat: you need to stop writing to db.table while MV is dropped, otherwise writes happening during this time frame will be missed.

**Comment by byx313** [comment]
thx for the reply!
About the Q2,I can not get further information about `TO` syntax in official document,so I guess you create `db.table_view` and drop it is aim to cut the link between `db.table` and 'db.origin-table'?After that you create the table again is aim to create the link again?

**Comment by nvartolomei** [comment]
@byx313 exactly.

**Comment by den-crane** [comment]
```
# alter MV with implicit storage .inner (without TO) 
1. stop ingestion 
2. detach table MVX
3. alter table `.inner.MVX` add column ..... 
4. attach MATERIALIZED VIEW MVX as select new_SELECT_.....
5. start ingestion 


# how to convert MV implicit storage .inner (without TO) to explicit storage (with TO)
1. stop ingestion 
2. detach table MVX
3. rename table `.inner.MVX` to MVX_store;
4. create table `.inner.MVX` as MVX_store engine=TinyLog;
5. attach table MVX
6. drop table MVX
7. rename table MVX_store to MVX
8. create materialized view MVX_mv to MVX as select ....
9. start ingestion 
```
