### ISSUE TITLE
How can I get default compression method for a column?

### ISSUE THREAD

**Issue by achimbab** [ClickHouse/ClickHouse#8405]
I tested compressed bytes for some columns at https://github.com/ClickHouse/ClickHouse/issues/8366

I wonder what compression method is applied to the column `A`.

| compression method |  disk | rows/s |
| --------------------- | ----- | ------- |
| default | 766.34 MiB | 3.89 million |
| lz4 | 2.98 GiB | 2.26 billion |
| none | 2.98 GiB | 2.34 billion |

```SQL
CREATE TABLE compressionTest
(
    `A` Int64,
    `col_lz4` Int64 CODEC(LZ4),
    `col_none` Int64 CODEC(NONE)
)
ENGINE = MergeTree
ORDER BY A

-- Repeat 4 times
INSERT INTO compressionTest SELECT
    number,
    cityHash64(number),
    cityHash64(number)
FROM numbers(100000000)
```

**Comment by alexey-milovidov** [comment]
Your test is slightly incorrect.

1. default is lz4 or the value specified in config.xml in `compression` section.

2. cityHash64 of sequential numbers won't compress at all (neither by lz4 or zstd).

3. The compression ratio depends on whether your data parts was merged. You have four identical data parts, each ordered by number. When these data parts are merged, the numbers and their corresponding hashes will be placed together, four in a row, and you will get roughly four times compression ratio.

4. The time when data is merged is non-deterministic, unless you run OPTIMIZE FINAL. That's why you get paradoxical results that two identical compression methods (default and lz4) look different.

**Comment by achimbab** [comment]
@alexey-milovidov 
Now I know clearly!
Thank you a lot. :)

**Comment by maciejskorski** [comment]
Just a remark: sometimes **clickhouse metadata may report default codec as None** which is very confusing (!).

Creating a copy of a column and setting the codec explicitly helps reassuring that `LZ4` is the default choice:

<img width="1453" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/31315784/02d773fa-9fef-4a77-acea-827621181a43">

**Comment by alexey-milovidov** [comment]
It is an empty string, which does not mean "None" (there is a compression codec named None, btw)
it means "automatic choice" that can be affected by global table compression settings, recompression TTL, and compression rules by the size and age of data parts.
