### ISSUE TITLE
topK(N) N parameter always <= 10 against Distributed table 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#8546]
```
create table topX(A Int64) Engine=Memory;
insert into topX select number from numbers(100);
insert into topX select number from numbers(30);

-- local table topK(30) = 30
SELECT length(topK(30)(A)) FROM topX
┌─length(topK(30)(A))─┐
│                  30 │
└─────────────────────┘

-- distributed  table topK(30) = 10 ???
SELECT length(topK(30)(A))
FROM remote('localhost,127.0.0.1', currentDatabase(), topX)

┌─length(topK(30)(A))─┐
│                  10 │
└─────────────────────┘


SELECT length(topK(3)(A))
FROM remote('localhost,127.0.0.1', currentDatabase(), topX)

┌─length(topK(3)(A))─┐
│                  3 │
└────────────────────┘
```

It could be Documentation issue?

**Comment by mga-chka** [comment]
I think it has been fixed because on version 20.9.3.45 I have the following behavior (which looks logical)


SELECT length(topK(30)(A))
FROM topX

┌─length(topK(30)(A))─┐
│                  30 │
└─────────────────────┘

1 rows in set. Elapsed: 0.003 sec. 

christophe :) SELECT length(topK(30)(A))
:-] FROM remote('localhost,127.0.0.1', currentDatabase(), topX)

SELECT length(topK(30)(A))
FROM remote('localhost,127.0.0.1', currentDatabase(), topX)

┌─length(topK(30)(A))─┐
│                  30 │
└─────────────────────┘

1 rows in set. Elapsed: 0.008 sec. 

christophe :) SELECT length(topK(3)(A))
:-] FROM remote('localhost,127.0.0.1', currentDatabase(), topX)

SELECT length(topK(3)(A))
FROM remote('localhost,127.0.0.1', currentDatabase(), topX)

┌─length(topK(3)(A))─┐
│                  3 │
└────────────────────┘

1 rows in set. Elapsed: 0.009 sec.

And on version 20.3.8 I get the same problem as yours.
