### ISSUE TITLE
Number of columns in order by caluse

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#8607]
Description: We have a table with 6 Billion rows 
                    create table contact_in
                    (
                     domain String,
                     topic String,
                     category String,
                     job_level String.
                     job_function String,
                     created_date Date,
                     ----
                     ----
) ENGINE = MergeTree PARTITION BY category
ORDER BY
  (topic, domain,job_level,job_function) SETTINGS index_granularity = 8192

**The most used columns in the queries we have put in order by.**

How many columns can be used in the order by clause? 
Is it mandatory to use Date column in order by ? because we have only one date stored in the above "created_date" column.
Indexing will be done on all the columns in order by?
Query executing time is more with the above settings.
Should we change index granularity to something else?

and how to use the Skip index on this table?

Please help us to solve this.

**Comment by den-crane** [comment]
>The most used columns in the queries we have put in order by.

It's not quite right.
All table -- all columns will be sorted in order of `ORDER BY`
You have to define `ORDER BY` to achieve maximum compression to put similar values in columns as close as possible. The same time  `ORDER BY` -- creates an PRIMARY KEY index. This index can be used for filtering `where` conditions by index's **PREFIX**.
If most of your queries contain `where topic` topic have to be on the first position in INDEX (order by).

Long indexes are useless and make performance worse because PRIMARY INDEX stored in memory -- bigger index -- less memory for queries. 

Also INDEX filtering works mostly by prefix -- no sense to put some column XXX into index on 7th position, it will be used only if leading 6 columns has equality conditions in `where`.

For example in your case index will be used for a column job_function only if `where  topic='some' and domain ='somexxx'  and job_level = ''somezzzz' and job_function >/=/< ....`

>Is it mandatory to use Date column in order by

No. If you don't use date filtering in where conditions you don't need to put Date in orderby/index.
