### ISSUE TITLE
ALTER TABLE table_name DELETE WHERE  QUESTION

### ISSUE THREAD

**Issue by 865357384** [ClickHouse/ClickHouse#8679]
I'll use it first  “ALTER TABLE table_name DELETE WHERE colum”   ，Then use “insert into table_name select * from  ” .   This will show that the previous statement was executed （But the data has not been deleted）, but the data was inserted later.    Can you answer my question?

**Comment by MeteHanC** [comment]
Alter table mutations are executed asynchronously. So when you ran the mutation query, you just scheduled the mutation job. Data is not updated/deleted right away. You can check the mutation status by using 'system.mutations' table.

**Comment by 865357384** [comment]
I see the status of my delete operation statement is “is_done=1”  in this table.  but  The amount of data has doubled

**Comment by MeteHanC** [comment]
You might have executed the 'insert' query before the deletion took place. I assume you are inserting from the same table that you want to delete data from.  You should wait for the mutation to be completed. As I said, it does not work real time, it is rather an asynchronous job.

**Comment by 865357384** [comment]
How can I wait for it to complete this operation? Do I need to delay for the next task?

**Comment by MeteHanC** [comment]
Delaying is not wise since you don't have any clue about how long it will take. You can wait until your task is completed programmatically. Though, I am struggling to understand your purpose, there might be better ways but I need to understand your use case first.

**Comment by 865357384** [comment]
My use case is actually very simple, which is to delete data first and then insert data, similar to simple ETL work.

**Comment by MeteHanC** [comment]
You might want to take a look at [CollapsingMergeTree](https://clickhouse.yandex/docs/en/operations/table_engines/collapsingmergetree/). 

Basically, you can add a Sign column to your table and rather than actually deleting the data you can insert the exact same rows with -1 Sign. And execute your query like this ;

`insert into test_table select a, b, c, d from collapsing_table group by a, b, c, d having sum(Sign) > 0`

With this way you won't have to wait for mutation to be completed after the inserting the unwanted data with -1 Sign, you can run the insertion query right away and it will work as you expected (Alter table mutations are only for bulk updates anyway)

And if you worry about the storage, ClickHouse will delete the invalid rows you marked. However you can not plan for it since this will take place eventually, during the merge of data parts

**Comment by 865357384** [comment]
OK，Thank you very much.
