### ISSUE TITLE
system.distribution_queue table

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#8683]
**Use case**
This task is requested by Yandex.Metrica.

**Describe the solution you'd like**
Add a table that will contain the size of send queue for asynchronous INSERTS to Distributed tables - for each Distributed table.

**Comment by alexey-milovidov** [comment]
Implementation is fairly easy. Provide a method in StorageDistributed to get queue size. Add system storage similar to system.replication_queue. It will go through all databases and tables, do dynamic_cast to StorageDistributed and collect the result.

**Comment by alexey-milovidov** [comment]
@azat Are you interested implementing this task?

**Comment by azat** [comment]
Yes, thanks!
I thought about implementing it via metrics, but maybe provide system table will be better.

Do you have some pros and cons for both?

I thought about provide this via metrics because basically you are interested in monitoring this, yes any system table can be exported via, say custom http handlers, but this is one extra step.

**Comment by alexey-milovidov** [comment]
But we don't have per-table metrics, only total.

**Comment by azat** [comment]
Ah, indeed! This definitely should be per table (and per disk)

**Comment by azat** [comment]
@alexey-milovidov taken
