### ISSUE TITLE
Optimize query on huge table

### ISSUE THREAD

**Issue by nshah14285** [ClickHouse/ClickHouse#9482]
Hello,

Are there any pros or cons to run query `optimize table test final;` on the huge table at every 5 or 10 minutes of intervals on a table with CollapsingMergeTree engine?

Reason to run `optimize table test final;` manually is - CollapsingMergeTree is not deleting the rows with -1 sign. So we have to run optimize query manually to get the correct stats from the table.

Any help would be appreciated.

Thanks,
Nishit

**Comment by den-crane** [comment]
The main problem of optimize final (table or partition does not matter) that it re-writes/re-merges a partition fully even if partition have only 1 part which is excessive in 99.9999% occasions!!!! It re-merges old data which was finally merged already!!!

It needed because sometimes one needs to collapse rows (duplicates) inserted with single insert into partition with forever single part. It is a very very rare necessity.

So I recommend to run optimize final against partitions which have more than one part. You can use something like this
```
select concat('optimize table ',database, '.','\`', table, '\` partition ',partition , ' final;')
from system.parts
where active and (engine like '%ReplacingMergeTree' or  engine like '%CollapsingMergeTree')
group by database,table,partition
having   count()>1
```
