### ISSUE TITLE
Woboq code browser must be indexed by search systems.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#9597]
**Use case**
https://www.google.com/search?newwindow=1&sxsrf=ALeKk032ubAdPxPHJDlDdJv_8BqgDgZ0uQ%3A1583870986414&ei=CvRnXuDtGOSrrgSEuonADw&q=%22Unknown+status%2C+client+must+retry%22&oq=%22Unknown+status%2C+client+must+retry%22&gs_l=psy-ab.3...4840.5646..5919...0.2..0.103.158.1j1......0....1..gws-wiz.......0i71.5FXPdJLUl2c&ved=0ahUKEwjgmo-c25DoAhXklYsKHQRdAvgQ4dUDCAo&uact=5

We should make our Woboq Code Browser accessible on the website:
`https://clickhouse.tech/codebrowser/`

**Comment by blinkov** [comment]
So the current entry point is https://clickhouse.tech/codebrowser/html_report/ClickHouse/index.html

Some parts of it have started showing up in Google search index, but it'll take a while to be relatively complete because there are not so many inbound links and user activity is low. 

Here's a query to check current documents count: https://www.google.com/search?client=safari&rls=en&q=site:clickhouse.tech+inurl:codebrowser&ie=UTF-8&oe=UTF-8
