### ISSUE TITLE
Lookups by UUID

### ISSUE THREAD

**Issue by jondeandres** [ClickHouse/ClickHouse#9778]
Hello,

we are considering using CH for analytics and data aggregation features, and we think it'd work pretty well for that.

However we are also wondering if we could use CH for single row lookups by primary key. We'd want to do single row lookups by a `uuid` column. Could you explain us if that's a good use case for CH or not?

Thank you very much.

**Comment by qoega** [comment]
Actually we don't know your specific case.
The best way to answer your question is to try your estimated rps with close to real data in tables. And we don't know how big your cluster is and whether you have very hot keys.

What you should be conserned of is whether you want to make updates in this table or not. It is not recommended to make queries with FINAL, as they work much slower than ordinary queries. 

Currently there are no PREPARED QUERIES in ClickHouse and each query would be analyzed, etc. If your scenario is about thousands of qps, there should be no problems at all. If you need millions qps there could be a bottleneck.

There is a tool for benchmarking queries that can help you to try your load.

**Comment by filimonov** [comment]
Clickhouse is not good for single row lookup. Clickhouse is not a key-value storage, it's analitycal database which fill the best in conditions when wide range of rows need to be processed.

> When NOT to use ClickHouse
>     ✕ Transactional workloads (OLTP)
>     ✕ Key-value requests with high rate
>     ✕ Blob or document storage
>     ✕ Over-normalized data


Sometimes you can still use it for such goals (because clickhouse is main database in the project and key-value lookups are some secondary requirement) 

In that case - check that articles
https://www.altinity.com/blog/clickhouse-in-the-storm-part-1
https://www.altinity.com/blog/clickhouse-in-the-storm-part-2
