### ISSUE TITLE
 select toDateTime64(1584009186942540518, 9)  convert overflow

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#9786]
SELECT toDateTime64(1584009186942540518, 9)

Received exception from server (version 20.4.1):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: DateTime64 convert overflow.

This works for some reason, but it's not as documented https://clickhouse.tech/docs/en/data_types/datetime64/
```
SELECT toDateTime64(1584009186.9425404, 9)

┌─toDateTime64(1584009186.9425404, 9)─┐
│       2020-03-12 10:33:06.942540288 │
└─────────────────────────────────────┘
```

**Comment by UnamedRus** [comment]
CSV import doesnt work too.
but VALUES works
CREATE TABLE dt
(
    timestamp DateTime64(9, 'Europe/Moscow'), 
    event_id UInt8
)
ENGINE = TinyLog

~$ cat data.csv 
1584009186942540518, 4
~$ cat data.csv | clickhouse-client --password test --query="INSERT INTO dt FORMAT CSV"
~$ clickhouse-client --password test --query="SELECT * FROM dt"
2020-04-10 12:49:40.324695040  4
When
**1584009186**942540518
1584009186
Is equivalent to:
03/12/2020 @ 10:33am (UTC)

**Comment by filimonov** [comment]
I think that FR will cover the usecase: https://github.com/ClickHouse/ClickHouse/issues/10672 ?

**Comment by den-crane** [comment]
Yes, it covers.

**Comment by mdelvecchio-wasabi** [comment]
I don't understand why this issue was closed with a fix for the problem.  I am seeing the same error in https://github.com/ClickHouse/ClickHouse/issues/10661.

We hacked our way around the 1-second resolution of DateTime columns by adding a UInt64 column of nanoseconds since the epoch.  But when I try to convert that column to a DateTime64(9) column, I get the same error:

```
ALTER TABLE db.table MODIFY COLUMN `EndTimeNS` DateTime64(9)

Received exception from server (version 20.3.5):
Code: 407. DB::Exception: Received from localhost:9000. DB::Exception: DateTime64 convert overflow. 
```

It seems that if this issue is fixed, then my column change would work.

I think that this wasn't fixed because https://github.com/ClickHouse/ClickHouse/issues/10672 covers this somehow, but I don't see how.

Thanks.

**Comment by den-crane** [comment]
@mdelvecchio-wasabi 
I closed this (my) issue because it was not a bug at all. 
I had a wrong expectation that it should work but it should not.

WRONG: select toDateTime64(1584009186942540518, 9)
RIGHT: select toDateTime64('1584009186.942540518', 9)

**Comment by mdelvecchio-wasabi** [comment]
I guess I disagree with the "WRONG" assessment.  I think this should work, as nanoseconds since the epoch is the natural value for DateTime64(9).  Particularly since this notation works in the VALUES clause.

Thanks.

**Comment by den-crane** [comment]
I agree that behavior is inconsistent. Probably CH should not support this in the Values as well.
