### ISSUE TITLE
Feature: Time type

### ISSUE THREAD

**Issue by inv2004** [ClickHouse/ClickHouse#979]
If we have Date field in partition key, It would be perfect to have Time (without Date) type.
Now it is possible to emulate time with UInt32, but it is quite unreadable and not easy to use.

**Comment by alexey-milovidov** [comment]
Time type will have almost no advantages over DateTime.

In memory, we need more than two bytes for representation of Time up to seconds resolution, and due to alignment and for simpler arithmetic, it will be four bytes, just as for DateTime.

On disk, full DateTime will compress to similar size as Time, because many consecutive dates in DateTime column and higher bytes in binary representation of DateTime will be the same.

**Comment by inv2004** [comment]
I suppose that Time type with ms (or nano?) instead of UInt32 would help to track events more precise and would have some sugar to make work with time more accurate.

For better understanding, could you please show how to work with time in current realization?

SELECT event WHERE date = '2017.02.02' AND time < '1970-01-02 12:00:00' // without ms or nano
SELECT event WHERE date = '2017.02.02' AND time < '12:00:00.000' // with ms
SELECT event WHERE date = '2017.02.02' AND time < 43200000 // with UInt32

**Comment by alexey-milovidov** [comment]
Agree. Special time type with custom resolution will be way more convenient.

**Comment by alexey-milovidov** [comment]
Now we have DateTime64 data type that support up to nanosecond precision.

We still don't have dedicated Time (without Date) type but it is "won't fix".
