### ISSUE TITLE
Next LTS version

### ISSUE THREAD

**Issue by iameugenejo** [ClickHouse/ClickHouse#9875]
Is there any plan on making 19.16 as another LTS version?

**Comment by alexey-milovidov** [comment]
LTS versions are scheduled every half year.

The version is named LTS when the following conditions are met:
- at least half year has passed since previous LTS release;
- at least one big customer started to use this version.

Now half year has been passed since 19.14 and Yandex Cloud voted for 20.3 to be the next LTS version. It means that the next LTS version will be 20.3.

LTS version have backports for simple bugfixes during one year.

**Comment by alexey-milovidov** [comment]
PS. Our internal customers: Yandex Metrica, Yandex Banner System, Yandex Market, ... prefer stable versions over LTS, because they contain more fresh features and overall improvements.
